{
  goals:'<strong>To read a news article that mixes facts, plans, forecasts and possibilities, and brief someone who has not read it: who says each part, how sure it is, and where each number sits.</strong><ul>'+
        '<li>To read the article once for the story before working on the details.</li>'+
        '<li>To attribute each piece of information to the source that gives it, going back to the line.</li>'+
        '<li>To tell what is already happening from what is planned or expected and from what is only possible, by the words around it.</li>'+
        '<li>To keep the meaning of <em>up to</em>, <em>at least</em> and <em>between</em> when saying a number.</li>'+
        '<li>To answer an interruption and a question the article does not answer, and to ask one back.</li></ul>',
  product:'The briefing on screen 9, said live to the person she chose (you), with the sentence starters closed: what the article is about, what has already happened, what is planned or expected, what is only possible, each with who says it, and her own reading marked as hers. Then, on screen 10, her answers to two questions and one question of her own.',
  criteria:'<ul><li>Each piece of information comes with who says it, in the same sentence.</li>'+
           '<li>The plan, the forecast and the possibility are marked as such (<em>says it will</em>, <em>expect</em>, <em>could</em>), without being asked.</li>'+
           '<li><em>Up to 300</em> and <em>at least 60</em> keep their meaning: 300 as the most, 60 as the least.</li>'+
           '<li>After the interruption on screen 9 she goes back to the point she had left.</li></ul>',
  prep:'<ul><li>Read the article before the lesson. Already happening: nine to twelve extra days per trip (the carriers); 12-hour shifts on arrival days at the largest site since May (the company). A plan: up to 300 temporary workers before November, with no length given (the company). Not confirmed: at least 60 people have left since April (a union representative). A possibility: between 800 and 1,200 jobs in the state could move to temporary contracts if the detour lasts into next year (the consultancy). A forecast: the route reopens by the end of the year (the carriers); an analyst says it could be March. The Campinas site: the company declined to comment.</li>'+
       '<li>Screen 1 asks for news someone repeated to her this week. She asked for current events as material, and her answer is the only real news in the lesson. The article is a sample with an invented company; if she asks, say so.</li>'+
       '<li>The interruption on screen 9 and the two questions on screen 10 are written in the notes on those screens, for both options.</li>'+
       '<li>In an earlier lesson she said she could not see the point of a task that had no context. On screens 2 and 9, read who is asking and what they need with her before she starts.</li></ul>',
  language:'<strong>Saying who says it:</strong> <em>According to the carriers,&hellip;</em> &middot; <em>The company says&hellip;</em> &middot; <em>A union representative says&hellip;, but the company has not confirmed it.</em><br><strong>Saying how sure it is:</strong> <em>&hellip; has already&hellip;</em> &middot; <em>&hellip; says it will&hellip;</em> &middot; <em>&hellip; expect&hellip; to&hellip;</em> &middot; <em>&hellip; could&hellip; if&hellip;</em> &middot; <em>That is a forecast, not a fact.</em><br><strong>Where the number sits:</strong> <em>up to 300</em> &middot; <em>as many as 300</em> &middot; <em>at least 60</em> &middot; <em>between 800 and 1,200</em><br>Numbers in full: <em>one thousand three hundred twelve</em> &middot; <em>nine to twelve days</em> &middot; <em>between eight hundred and one thousand two hundred</em>.',
  transcript:'The audio in this lesson is the five model sentences on screen 8. The model briefing on the same screen is written, behind a button: open it after she has given the three pieces of information herself.',
  difficulties:'<ul><li><strong>Up to may turn into at least, or disappear.</strong> &ldquo;They are hiring 300 people&rdquo; drops the maximum; &ldquo;at least 300&rdquo; turns it upside down. Screen 7 works on it.</li>'+
       '<li><strong>The union figure may sound like a company figure.</strong> &ldquo;At least 60 people left&rdquo; said without the source is the one number in the article that nobody has confirmed.</li>'+
       '<li><strong>Could may come out as will.</strong> The consultancy estimate is a possibility with a condition (<em>if the detour lasts</em>); without <em>could</em> and <em>if</em> it sounds like a plan.</li>'+
       '<li><strong>Portuguese may appear under pressure.</strong> In recent lessons it appeared when she was unsure what a task was for, more than when a word was missing.</li></ul>',
  scaffolding:'The article is on screen 4 and behind the <em>Show the article</em> button on screen 5. On screens 9 and 10 the sentence starters are behind a closed button: open them only if she stops, let her look, and close them again.<br><br>'+
    'If a number stalls on screen 8, say the first half of it (<em>between eight hundred&hellip;</em>) and let her finish. If the briefing is clean on the first attempt, the challenge on screen 9 asks her which piece of information she would check before repeating it in a meeting.',
  feedback:'One point on screen 11, taken from a sentence with a number that she said on screen 9, and then the replay: the same briefing to the person from the other option, who needs something different first.<br><br>'+
    'Leave corrections for screen 11. Interrupting the briefing for language costs the sentences that were still coming.',
  evidence:'<ul><li><strong>Whether up to, at least and between kept their meaning in her own sentences.</strong> It is the main record of the lesson.</li>'+
    '<li>Whether the plan, the forecast and the possibility were marked without prompting on screen 9.</li>'+
    '<li>Whether the union figure kept its source.</li>'+
    '<li>What she did after the interruption: back to the point, a new start, or Portuguese.</li>'+
    '<li>The news she brought on screen 1, in her words. It can come back in later lessons.</li></ul>',
  prepost:'The pre-class reads a different, shorter news item about a late coffee harvest, asks who gives each piece of information and how ranges and approximate numbers are said, and ends with four sentences that put the source in the sentence. It does not touch the article of the lesson, the meaning of <em>up to</em> and <em>at least</em>, or the difference between a plan and a possibility. The post-class has an optional recording, an optional written note, a news release and a talk about numbers in the news, and a language reference.',
  key:'<strong>Screen 4:</strong> already happened &mdash; ships take a detour of nine to twelve days, and Norvale moved its largest site to 12-hour shifts in May; not yet &mdash; the hiring of up to 300 temporary workers, the reopening of the route, and anything about the Campinas site. <strong>Screen 5:</strong> the carriers &mdash; nine to twelve extra days, reopening by the end of the year; the company &mdash; up to 300 temporary workers; a union representative &mdash; at least 60 people have left; the consultancy &mdash; between 800 and 1,200 jobs; nobody &mdash; Norvale is closing Campinas. <strong>Screen 6:</strong> already happening &mdash; <em>adds nine to twelve days to each trip</em>, <em>moved its largest site to 12-hour shifts</em>; planned or expected &mdash; <em>will hire up to 300 temporary workers</em>, <em>expect the route to reopen</em>; could happen &mdash; <em>could move to temporary contracts</em>, <em>could easily be March</em>. <strong>Screen 7:</strong> &ldquo;Norvale will hire at least 300 temporary workers.&rdquo; is the different one.'
}
