# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80"
BG5 = "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1400&q=80"
BG6 = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1400&q=80"

D = {
    'n': 20,
    'reading': True,
    'partner_name': 'sebastian',
    'grammar_point_pt': "inversao para enfase (inversion for emphasis): quando comecamos a frase com um adverbio negativo ou limitante, o auxiliar vem ANTES do sujeito, como numa pergunta -- para dar forca e impacto retorico. 'Never before have we seen demand like this' (nunca antes vimos), 'Not only did we recover, but we also grew' (nao so nos recuperamos como tambem crescemos), 'Only by taking bold risks did we build this momentum' (so ao assumir riscos ousados construimos esse impulso). Ferramenta de quem inspira uma sala: discursos, keynotes, e o momento de compartilhar uma visao",
    'chapter_tag': 'The Room You Want to Move',
    'title_h1': 'Sharing Your Vision and Inspiring the <span class="accent">Room</span>',
    'title_sub': 'Cast a bold picture of the future, rally people to it, and speak with the emphasis that makes a keynote land.',
    'short_title': 'Sharing Your Vision',
    'menu_title': 'Sharing Your Vision and Inspiring the Room',
    'menu_desc': 'Inspire an audience using inversion for emphasis',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=600&q=80",
    'stamp_label': 'Visionary Speaker',
    'stamp_img': "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&q=80",
    'phases': ['The Room You Want to Move', 'Words That Inspire', 'The Keynote',
               'Emphasis by Inversion', 'Voices', 'Your Turn', 'The Summit'],

    'warm_h2': 'From the Hard Talk to the <span class="accent">Big Picture</span>',
    'warm_p': "Last time you held your composure in a high-stakes conversation -- de-escalating, standing your ground, knowing your walk-away point. That was leadership under pressure. Today is the other half of leadership: lifting your eyes from the deal in front of you to the future you want to build. This is the final session of your program, and it is fitting that it is about vision. A director doesn't only close deals; she gives her team, her partners, and a whole room a reason to follow. Today you learn to share a vision and inspire the people who hear it -- to speak not just clearly, but with the emphasis that makes people lean in. By the end of this hour, you will stand in front of the room and move it.",
    'warm_prompt': 'In one sentence: if you could inspire a room about the future of tourism, what would you want them to feel?',
    'missions': [
        'Learn the language of vision, inspiration, and leaving a legacy.',
        'Use inversion for emphasis -- Never before have we..., Not only did we..., Only by... did we...',
        'Deliver a short, bold vision that rallies a room around where you are going next.',
    ],

    'vocab_trans_h2': 'Words That <span class="accent">Inspire</span>',
    'vocab': [
        ("Vision", "a clear, ambitious picture of the future you want to build (visao de futuro)", "Every strong leader starts with a vision people can see."),
        ("Keynote", "the main speech that sets the theme of an event (palestra principal)", "She was invited to give the keynote at the tourism summit."),
        ("To inspire", "to fill people with the desire and confidence to act (inspirar)", "A good leader doesn't just inform -- she inspires."),
        ("Legacy", "the lasting impact you leave behind (legado)", "I want our legacy to be a company that raised the whole industry."),
        ("Turning point", "a moment of decisive change in a story or journey (ponto de virada)", "That deal was the turning point for the whole company."),
        ("To rally", "to bring people together and energize them around a cause (mobilizar, unir em torno de)", "She rallied the team around one bold goal for the year."),
        ("Resilience", "the ability to recover and keep going after difficulty (resiliencia)", "Our resilience during the downturn is why we're still here."),
        ("Momentum", "the force of steady, ongoing progress (impulso, embalo)", "Once the bookings started, the momentum was unstoppable."),
        ("To champion", "to actively support and promote a cause or idea (defender, promover ativamente)", "I've always championed sustainable tourism."),
        ("Bold", "brave, confident, and willing to take risks (ousado, audacioso)", "It was a bold move, and it paid off."),
        ("To envision", "to picture something clearly as a future possibility (vislumbrar, imaginar)", "I envision a company that leads, not follows."),
        ("Aspiration", "a strong hope or ambition to achieve something (aspiracao)", "Our aspiration is to be the region's most trusted operator."),
    ],

    'gram_trans_h2': 'Flip It for <span class="accent">Emphasis</span>',
    'gram_trans_sub': 'negative / limiting adverbial first &rarr; auxiliary before the subject',
    'gram_examples': [
        ("", "Never before have we seen demand like this.", '"<span class="accent" style="font-weight:700">Never before have we</span> seen demand like this."'),
        ("", "Not only did we recover, but we also grew stronger.", '"<span class="accent" style="font-weight:700">Not only did we</span> recover, but we also grew stronger."'),
        ("", "Only by taking bold risks did we build this momentum.", '"Only by taking bold risks <span class="accent" style="font-weight:700">did we</span> build this momentum."'),
    ],
    'gram_disc_q': 'In each sentence, a negative or limiting phrase jumps to the front -- and then the word order flips, so the auxiliary (have, did) comes BEFORE the subject, just like in a question. Normal order would be "We have never seen..." What does moving the phrase to the front, and inverting, do to the feeling of the sentence?',
    'gram_table': [
        ("Never / Rarely / Seldom + aux + subject", "front a negative adverb, then invert for impact", "Never <strong>have we</strong> seen demand like this."),
        ("Not only ... but also ...", "front 'not only', invert, add the second, bigger point", "Not only <strong>did we</strong> recover, but we also grew."),
        ("Only by / when / after ... + aux + subject", "front 'only + ...', then invert the MAIN clause", "Only by being bold <strong>did we</strong> get here."),
    ],
    'gram_rule_foot': "Inversion for emphasis takes a negative or limiting phrase -- never, rarely, not only, only by/when/after -- and moves it to the front of the sentence. When you do that, the word order flips: the auxiliary comes before the subject, exactly like a question ('have we', 'did we', not 'we have', 'we did'). It's the grammar of speeches and vision: it makes a claim sound bigger, prouder, and more inspiring. Use it sparingly, at the moments you most want the room to lean in.",

    'lf_h2': 'Front and <span class="accent">Flip</span>',
    'lf_title': 'Read each line and complete the inversion',
    'lf_items': [
        ["A", "", "Never before have we", " reached so many travelers.", "strong"],
        ["B", "", "Not only did we survive", ", but we also came out stronger.", "strong"],
        ["C", "", "Rarely do you see", " a team this determined.", "soft"],
        ["D", "", "Only by being bold did we", " build this momentum.", "soft"],
    ],
    'lf_followup': "After a fronted negative or limiting phrase, invert: put the auxiliary (have, did, do) BEFORE the subject -- 'have we', 'did we', 'do you' -- just like a question. That inversion is what gives the line its punch.",

    'mistakes': [
        ("Never before we have seen demand like this.", 'Never before <strong>have we</strong> seen demand like this.'),
        ("Not only we recovered, but we also grew.", 'Not only <strong>did we</strong> recover, but we also grew.'),
    ],
    'mistake_note': "After a fronted negative phrase, you MUST invert: the auxiliary goes before the subject. 'Never before HAVE WE seen', not 'Never before we have seen'. And with 'Not only', add the auxiliary and use the base verb: 'Not only DID WE recover', not 'Not only we recovered'. If you don't invert, it isn't emphasis -- it's just a broken sentence.",

    'read_trans_h2': 'Read the <span class="accent">Keynote</span>',
    'reading_h2': 'The Room You Want to <span class="accent">Move</span>',
    'read_block': {
        'rtitle': 'The Room You Want to Move',
        'paras': [
            "Anyone can read numbers off a slide. What separates a manager from a leader is the ability to stand in front of a room and make people believe in a future they cannot yet see. That is what a vision is: not a forecast, but a picture -- bold, clear, and specific enough that the people who hear it can imagine their own place inside it. When you share a vision well, you are not reporting the past; you are recruiting people into what comes next. You give them a reason to bring their best, and you rally them around something bigger than this quarter's target.",
            "The best vision speeches are built on a simple emotional arc: where we were, the turning point, and where we are going. They name the difficulty honestly -- the downturn, the doubt, the hard year -- because resilience only inspires when the struggle was real. Then they mark the moment things changed, and they let the momentum carry the room forward. Notice how the great ones speak at the peak moments. They don't say 'we have never seen demand like this.' They say 'Never before have we seen demand like this.' The words are almost the same; the feeling is not. Fronting the emphasis and inverting the order makes the claim land like a drumbeat.",
            "You do not need to be a natural orator to do this. You need a clear aspiration, the courage to say it out loud, and a few well-placed moments of emphasis. Champion the thing you actually believe in. Envision it concretely, in a sentence someone could repeat over coffee. And remember that the point of inspiring a room is not applause -- it is what people do on Monday morning. The leaders whose legacy outlasts them are simply the ones who gave others a future worth working toward, and made them feel, for a moment, that reaching it was inevitable.",
        ],
        'source': 'Adapted from a leadership communication guide',
        'link': 'https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "A good leader inspires a room only by reporting last quarter's numbers accurately.", False],
            ["b", "Sharing a vision means painting a bold, clear picture of the future, naming the real struggle, and using well-placed emphasis to make people believe and act.", True],
            ["c", "The main goal of a vision speech is to win applause in the room.", False],
        ],
        'tf': [
            ["The text says a vision is the same thing as a forecast.", "f", "It says a vision is not a forecast but a picture -- bold, clear, and specific enough for people to imagine their place in it."],
            ["According to the text, naming the real difficulty makes resilience more inspiring.", "t", "The second paragraph says resilience only inspires when the struggle was real, so the best speeches name the difficulty honestly."],
            ["The text says 'Never before have we seen demand like this' feels different from the plain version.", "t", "It says the words are almost the same but the feeling is not -- fronting the emphasis and inverting makes the claim land like a drumbeat."],
            ["The text says the point of inspiring a room is the applause you get.", "f", "It says the point is not applause but what people do on Monday morning."],
        ],
    },

    'dialogue_h2': 'Andrea Shares Her Vision with <span class="accent">Sebastian</span>',
    'dialogue': [
        ('sebastian', 'arthur', "Andrea, you're closing our tourism summit. In one line -- what's the vision you want to leave the room with?",
         "Andrea, you're closing our tourism summit. In one line -- what's the vision you want to leave the room with?"),
        ('andrea', 'ellen', "That we stopped following the market and started leading it. Never before have we had a chance like the one in front of us.",
         "That we stopped following the market and started leading it. <span class=\"vocab-highlight\">Never before have we</span> had a chance like the one in front of us."),
        ('sebastian', 'arthur', "Strong opening. But the last two years were brutal for the industry. Won't that ring hollow?",
         "Strong opening. But the last two years were brutal for the industry. Won't that ring hollow?"),
        ('andrea', 'ellen', "No -- I'll name it. Not only did we survive the downturn, but we also came out with better partners and a bolder plan. The struggle is the point.",
         "No -- I'll name it. <span class=\"vocab-highlight\">Not only did we</span> survive the downturn, but we also came out with better partners and a <span class=\"vocab-highlight\">bolder</span> plan. The struggle is the point."),
        ('sebastian', 'arthur', "And how do you get them to actually follow you out of the room?",
         "And how do you get them to actually follow you out of the room?"),
        ('andrea', 'ellen', "By making the aspiration concrete. I envision us as the region's most trusted operator within three years -- and I'll tell them exactly how we get there.",
         "By making the <span class=\"vocab-highlight\">aspiration</span> concrete. I <span class=\"vocab-highlight\">envision</span> us as the region's most trusted operator within three years -- and I'll tell them exactly how we get there."),
        ('sebastian', 'arthur', "That's a legacy worth chasing. How do you want them to feel as they walk out?",
         "That's a <span class=\"vocab-highlight\">legacy</span> worth chasing. How do you want them to feel as they walk out?"),
        ('andrea', 'ellen', "Like it's already happening. Only by moving together did we get this far -- and rarely do you get a moment this good to build on. Let's not waste it.",
         "Like it's already happening. <span class=\"vocab-highlight\">Only by</span> moving together did we get this far -- and <span class=\"vocab-highlight\">rarely do you</span> get a moment this good to build on. Let's not waste it."),
    ],
    'comprehension': [
        ("1. What is the one-line vision Andrea wants to leave the room with?", "That the company stopped following the market and started leading it."),
        ("2. How does Andrea handle the fact that the last two years were brutal?", "She names it -- not only did they survive the downturn, they came out with better partners and a bolder plan."),
        ("3. What concrete aspiration does Andrea envision, and by when?", "Becoming the region's most trusted operator within three years."),
    ],

    'listen1_h2': 'The <span class="accent">Keynote</span>',
    'listen1_sub': 'A leader closes a conference with her vision. Sound first -- no text.',
    'listen1_qs': [
        ("1. What arc does the speaker use to build her vision?", "Where they were, the turning point, and where they are going next."),
        ("2. Why does she name the hard years instead of hiding them?", "Because resilience only inspires when the struggle was real -- the difficulty makes the recovery mean something."),
        ("3. What does she say the real point of the speech is?", "Not the applause, but what people actually do afterward -- the action they take."),
    ],
    'listen2_h2': 'Emphasis by <span class="accent">Inversion</span>',
    'listen2_sub': 'A short tip on inversion for emphasis. Sound first -- no text.',
    'listen2_qs': [
        ("1. What happens to the word order after a fronted negative phrase?", "It inverts -- the auxiliary comes before the subject, like in a question ('have we', 'did we')."),
        ("2. What example does the speaker use to show the difference in feeling?", "'We have never seen demand like this' versus 'Never before have we seen demand like this'."),
        ("3. What advice does the speaker give about using inversion?", "Use it sparingly, only at the peak moments where you most want the room to lean in."),
    ],
    'listenings': [
        {'file': 'a20_listening_keynote.mp3', 'voice': 'ellen',
         'text': "I want to close by telling you where we're going. But first, let me tell you where we were. Two years ago, this industry was on its knees. Bookings vanished, partners pulled out, and there were mornings I wasn't sure we'd make it. I won't pretend that was easy, because resilience doesn't mean anything if the struggle wasn't real. And then came the turning point. We made one bold decision to stop competing on price and start leading on trust. Never before have we grown the way we've grown since. Not only did we recover, but we also came out with better partners and a clearer purpose than we've ever had. So here is the vision. Within three years, I want us to be the most trusted operator in the region, the name people reach for first. That is the legacy I want us to build together. And here is the thing about a moment like this. Rarely do you get a chance this good. So let's not applaud it. Let's go and make it inevitable."},
        {'file': 'a20_listening_inversiontip.mp3', 'voice': 'arthur',
         'text': "Let's talk about inversion for emphasis, the grammar of great speeches. Normally, English word order is subject first, then verb. We have never seen demand like this. That's fine, but it's flat. Now watch what happens when you take the negative phrase and move it to the front. Never before have we seen demand like this. Did you feel that? When a negative or limiting phrase goes first, the word order flips. The auxiliary jumps in front of the subject, exactly like a question. Have we, not we have. Did we, not we did. It works with never, rarely, seldom, little, and with not only, followed by but also. It works with only, as in only by working together did we get here. One warning. This is a spice, not a sauce. Use it once or twice, at the peak moments where you want the room to lean in. Invert every sentence and it stops sounding powerful and starts sounding strange. Place it well, and you can make a simple claim feel like history."},
    ],

    'gapfill_parts': [
        "Andrea closes the summit with a bold ",
        ["1"], ": the company stopped following the market and started leading it. She names the hard years honestly -- not only did they survive the downturn, but they also built ",
        ["2"], " and better partners. She makes the aspiration concrete: she ",
        ["3"], " the company as the region's most trusted operator in three years. For emphasis at the peak, she inverts: '",
        ["4"], " before have we had a chance like this.' Her goal is a ",
        ["5"], " the whole team can be proud to build.",
    ],
    'gapfill_bank': ["vision", "momentum", "envisions", "Never", "legacy"],
    'vocabnote': "Inversion for emphasis: front a negative/limiting phrase, then put the auxiliary before the subject -- 'Never before HAVE WE seen', 'Not only DID WE recover, but we also...', 'Only by being bold DID WE get here.' Same words, bigger impact. Use it at peak moments only.",

    'bank_label_top': 'The Keynote',
    'bank_label': 'Useful language for sharing a vision',
    'bank_items': [
        "Let me tell you where we're going -- but first, where we were.",
        "Never before have we had a chance like this one.",
        "Not only did we survive, but we also came out stronger.",
        "The turning point came when we chose to be bold.",
        "I envision us as the region's most trusted operator.",
        "Only by moving together did we get this far.",
        "That is the legacy I want us to build.",
        "Rarely do you get a moment this good -- let's not waste it.",
    ],

    'scenarios_h2': 'Move the <span class="accent">Room</span>',
    'scenario_items': [
        ["Scenario 1", "Open with where you were and the turning point -- name the struggle honestly, then mark the moment it changed."],
        ["Scenario 2", "Hit a peak moment with inversion: 'Never before have we...' or 'Not only did we..., but we also...'."],
        ["Scenario 3", "Make the aspiration concrete: 'I envision us as... within [time]', so people can picture it."],
        ["Scenario 4", "Close by rallying the room around the legacy -- what you want them to do, not just feel."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = vision, 2 = momentum, 3 = envisions, 4 = Never, 5 = legacy.",
        "Never + invert: 'Never before have we had a chance like this.'",
        "Not only + invert + but also: 'Not only did we survive, but we also grew.'",
        "Only by + invert main clause: 'Only by being bold did we get here.'",
    ],
    'answerkey_note': "Inversion: after a fronted negative/limiting phrase (never, rarely, not only, only by/when), the auxiliary comes before the subject -- have we, did we, do you.",

    'roleplays': [
        {'h2': 'The <span class="accent">Opening</span>',
         'scenario': "Open a short vision speech. Set the arc: name where you were and the honest struggle, then mark the turning point that changed everything.",
         'keywords': ["Let me tell you where we were...", "the turning point came when...", "and then everything changed"]},
        {'h2': 'The <span class="accent">Peak</span>',
         'scenario': "Deliver the emotional high point using inversion. Front a negative or limiting phrase and invert for impact -- make one big claim land like a drumbeat.",
         'keywords': ["Never before have we...", "Not only did we..., but we also...", "Only by... did we..."]},
        {'h2': 'The <span class="accent">Summit</span>',
         'scenario': "Close the whole program: cast your bold vision for the future of your company, make the aspiration concrete, and rally the room to build the legacy with you.",
         'keywords': []},
    ],

    'survival_h2': 'Speak to <span class="accent">Inspire</span>',
    'survival': [
        ("Let me tell you where we're going.", "Deixe-me contar para onde estamos indo."),
        ("Never before have we had a chance like this.", "Nunca antes tivemos uma chance como esta."),
        ("Not only did we survive, but we also grew.", "Nao so sobrevivemos, como tambem crescemos."),
        ("I envision us as the region's most trusted operator.", "Vislumbro nos como o operador mais confiavel da regiao."),
        ("That is the legacy I want us to build.", "Esse e o legado que quero que construamos."),
    ],
    'learned': [
        "I can share a bold vision using a clear arc: where we were, the turning point, where we're going.",
        "I can use inversion for emphasis at a peak moment: 'Never before have we...'.",
        "I can use 'Not only did we..., but we also...' to add a bigger, prouder point.",
        "I can make an aspiration concrete so a room can picture it and rally to it.",
        "I know the words: vision, keynote, to inspire, legacy, turning point, to rally, resilience, momentum, to champion, bold, to envision, aspiration.",
    ],
    'badge_name': 'Visionary Speaker Badge',
    'badge_p': 'You can stand in front of a room, share a bold vision, and inspire people to build it with you. Twenty lessons -- and you can now lead the conversation, the negotiation, and the room. Congratulations, Andrea.',
    'next_lesson': 'Program complete -- keep speaking, keep leading',

    # ----- new B2 slides (pipeline v2) -----
    'spot_errors': [
        ("Never before we have seen demand like this.", "Never before have we seen demand like this."),
        ("Not only we recovered, but we also grew.", "Not only did we recover, but we also grew."),
        ("Only by being bold we got here.", "Only by being bold did we get here."),
        ("Rarely you see a team this committed.", "Rarely do you see a team this committed."),
    ],
    'bridge5': {
        'h2': 'Voices That <span class="accent">Inspire</span>',
        'sub': 'Listen to a leader close with her vision, then move a room of your own.',
        'bg': BG5,
    },
    'register': [
        ("Numbers are up. That's the update.", "Never before have we grown like this -- and I want to tell you what it means for where we go next."),
        ("We had a rough couple of years, but whatever.", "Not only did we survive the downturn, but we also came out with a bolder plan and better partners."),
        ("The goal is to do a bit better next year.", "I envision us as the region's most trusted operator within three years -- here's how we get there."),
        ("Anyway, thanks, see you Monday.", "Only by moving together did we get this far. Let's go make the rest inevitable."),
    ],
    'artifact': {
        'label': 'The Keynote Outline',
        'h2': 'Vision Keynote <span class="accent">Outline</span>',
        'meta': [
            ("Speaker:", "Andrea Aggio -- Commercial Director"),
            ("Occasion:", "Closing keynote, Regional Tourism Summit"),
            ("One-line vision:", "We stopped following the market and started leading it"),
        ],
        'paras': [
            "Where we were: name the downturn honestly -- vanished bookings, partners pulling out, the hard mornings. Resilience only inspires when the struggle was real.",
            "The turning point: the bold decision to compete on trust, not price. Peak line, delivered with inversion: 'Never before have we grown the way we have since.' Then: 'Not only did we recover, but we also came out with better partners and a clearer purpose.'",
            "Where we're going: the concrete aspiration -- the region's most trusted operator within three years -- and the rally. Close on legacy: 'Only by moving together did we get this far. Rarely do you get a moment this good. Let's not applaud it; let's make it inevitable.'",
        ],
    },
    'artifact_qs': [
        ("1. According to the outline, what is the one-line vision?", "That the company stopped following the market and started leading it."),
        ("2. What was the turning point?", "The bold decision to compete on trust, not price."),
        ("3. What concrete aspiration does the close name, and by when?", "Becoming the region's most trusted operator within three years."),
    ],
    'pron_lines': [
        ("Never before have we seen this.", "'have we' links and lifts -- ha-vwee; fall on NEVER, rise into SEEN; let it ring."),
        ("Not only did we recover.", "'did we' -- di-dwee; punch NOT and reCOVer; the inversion carries the weight."),
        ("Only by moving together did we get here.", "'did we' after the long phrase -- keep the pace, then land GET HERE."),
        ("Rarely do you get a moment this good.", "'do you' -- duh-yuh; stress RARELY and GOOD; slow, deliberate."),
    ],
    'bridge6': {
        'h2': 'Now You Move the <span class="accent">Room</span>',
        'sub': 'Your turn: cast the vision and inspire them to follow.',
        'bg': BG6,
    },
    'quickfire': [
        {'situation': "Open your vision speech. Set the arc.",
         'tips': ["Where we were -> turning point -> where we go.", "'Let me tell you where we were.'", "Name the struggle honestly."]},
        {'situation': "Deliver a peak claim with 'Never before'.",
         'tips': ["Front it, then invert.", "'Never before have we seen this.'", "Auxiliary before subject -- have we."]},
        {'situation': "Add a bigger point with 'Not only'.",
         'tips': ["'Not only did we survive...'", "'...but we also grew.'", "did we + base verb, then but also."]},
        {'situation': "Explain how you got here with 'Only by'.",
         'tips': ["'Only by being bold...'", "'...did we build this.'", "Invert the MAIN clause."]},
        {'situation': "Close by rallying the room to the legacy.",
         'tips': ["Make it concrete: 'within three years'.", "'Let's make it inevitable.'", "Ask for action, not applause."]},
    ],

    'preclass_title': 'Sharing Your Vision and Inspiring the Room',
    'preclass_desc': "How to share a bold vision and inspire an audience -- using inversion for emphasis. Key words: vision, keynote, to inspire, legacy, turning point, to rally, resilience, momentum, to champion, bold, to envision, aspiration. Structure: front a negative/limiting phrase, then invert (Never before HAVE WE...; Not only DID WE...; Only by... DID WE...).",
    'context': ("Andrea is invited to give the closing <strong>keynote</strong> at a tourism summit. She wants to "
                "<strong>inspire</strong> the room with a bold <strong>vision</strong>: the company stopped following "
                "the market and started leading it. She names the hard years to show <strong>resilience</strong>, then "
                "marks the <strong>turning point</strong> with emphasis -- 'Not only <strong>did we</strong> survive the "
                "downturn, but we also grew.' She makes the <strong>aspiration</strong> concrete: 'I <strong>envision</strong> "
                "us as the region's most trusted operator in three years.' To build <strong>momentum</strong> at the peak, "
                "she inverts: '<strong>Never before have we</strong> had a chance like this.' She <strong>rallies</strong> "
                "the room around the <strong>legacy</strong> she wants them to build together."),
    'context_quiz': [
        ("1. In 'Never before have we had a chance like this', the word order after 'Never before' is:",
         [("A", "inverted -- auxiliary before subject (have we).", True),
          ("B", "normal -- subject before auxiliary (we have).", False),
          ("C", "a question with a question mark.", False)]),
        ("2. Which sentence uses inversion correctly?",
         [("A", "Not only did we recover, but we also grew.", True),
          ("B", "Not only we recovered, but we also grew.", False),
          ("C", "Not only recovered we, but grew we also.", False)]),
        ("3. Which sentence is correct after 'Only by being bold'?",
         [("A", "Only by being bold did we get here.", True),
          ("B", "Only by being bold we got here.", False),
          ("C", "Only by being bold we did get here.", False)]),
    ],
    'tip_title': 'Inversion for Emphasis',
    'tip_sub': "Como inverter a ordem para dar forca a uma frase -- a gramatica dos discursos e das visoes (em ingles e portugues).",
    'tip_rows': [
        ("Never / Rarely / Seldom", "adverbio negativo na frente -> auxiliar antes do sujeito. negative adverb first -> invert.", "Never <strong>have we</strong> seen this."),
        ("Not only ... but also", "'not only' na frente, inverte, e acrescenta o ponto maior. front, invert, add.", "Not only <strong>did we</strong> recover, but we also grew."),
        ("Only by / when / after", "'only + ...' na frente -> inverte a clausula PRINCIPAL. invert the main clause.", "Only by being bold <strong>did we</strong> get here."),
        ("Regra de ouro / Golden rule", "use com moderacao, so no pico. a pinch, not a sauce -- peak moments only.", "inverter tudo soa estranho."),
    ],
    'fill': [
        ('"Never before ', "have we", "Dica: apos adverbio negativo, inverta -- auxiliar antes do sujeito", "Never before have we had a chance like this.", ' had a chance like this."'),
        ('"Not only ', "did we", "Dica: apos 'not only', inverta e use o verbo base", "Not only did we survive, but we also grew.", ' survive, but we also grew."'),
        ('"Only by being bold ', "did we", "Dica: inverta a clausula PRINCIPAL apos 'only by...'", "Only by being bold did we build this momentum.", ' build this momentum."'),
        ('"I ', "envision", "Dica: imaginar/vislumbrar algo como possibilidade futura", "I envision us as the region's most trusted operator.", ' us as the region\'s most trusted operator."'),
        ('"That is the ', "legacy", "Dica: o impacto duradouro que voce deixa", "That is the legacy I want us to build.", ' I want us to build."'),
        ('"Rarely ', "do you", "Dica: apos 'rarely', inverta -- auxiliar antes do sujeito", "Rarely do you get a moment this good.", ' get a moment this good."'),
    ],
    'order_intro': "Coloque as partes de um discurso de visao na ordem correta.",
    'order': [
        "Start with where you were -- and name the real struggle honestly.",
        "Mark the turning point where everything changed.",
        "Hit the peak with an inversion: 'Never before have we...'.",
        "Make the aspiration concrete -- what, and by when.",
        "Rally the room around the legacy and ask for action.",
    ],
    'speech': [
        ("Let me tell you where we're going.", "Deixe-me contar para onde estamos indo."),
        ("Never before have we had a chance like this.", "Nunca antes tivemos uma chance como esta."),
        ("Not only did we survive, but we also grew.", "Nao so sobrevivemos, como tambem crescemos."),
        ("I envision us as the region's most trusted operator.", "Vislumbro nos como o operador mais confiavel da regiao."),
        ("Only by moving together did we get this far.", "So avancando juntos chegamos ate aqui."),
    ],
    'quiz': [
        ("You open the peak of your keynote and want maximum emphasis. You say:",
         [("A", "Never before have we had a chance like this.", True),
          ("B", "Never before we have had a chance like this.", False),
          ("C", "We never had a chance like this before, I think.", False)]),
        ("You want to add a bigger, prouder point after a first one. You say:",
         [("A", "Not only did we recover, but we also grew stronger.", True),
          ("B", "Not only we recovered, but we grew stronger too.", False),
          ("C", "We recovered and also we grew, not only.", False)]),
        ("You explain what made the success possible. You say:",
         [("A", "Only by being bold did we build this momentum.", True),
          ("B", "Only by being bold we built this momentum.", False),
          ("C", "We built this momentum only being bold.", False)]),
        ("You describe imagining the company clearly as a future possibility. You call it:",
         [("A", "to envision it.", True),
          ("B", "to champion it.", False),
          ("C", "to rally it.", False)]),
    ],
    'think': "This is your final lesson -- so make it real. Imagine you are giving the closing keynote at a tourism summit, sharing your vision for the future of Escape Turismo. Record a one-minute vision speech. Build the arc: where you were (name the struggle), the turning point, and where you're going. Use at least one inversion for emphasis ('Never before have we...' or 'Not only did we..., but we also...') at your peak moment, and make one concrete aspiration ('I envision us as... within...'). Close by rallying the room around the legacy you want to build. Take your time -- and be bold.",

    'media': [
        ('series', "Chef's Table (Netflix)",
         "A documentary series where each episode profiles a visionary chef who took a bold risk, survived a turning point, and built a legacy in the hospitality world. Rich in the language of vision, resilience, and inspiring people to follow a bold idea -- and set squarely in Andrea's own industry. Connection to Lesson 20: sharing a bold vision and building a legacy.",
         'Tip: watch how each chef sells a vision in a single, clear sentence people can repeat.',
         'https://www.imdb.com/title/tt4295140/'),
        ('podcast', 'Masters of Scale',
         "Reid Hoffman's podcast on how leaders envision the future and rally people around bold, counter-intuitive bets. Every episode is a story of vision, turning points, and momentum -- and the language of inspiring a room. Connection to Lesson 20: sharing your vision and building a legacy.",
         'Tip: after an episode, write one sentence of vision, then rewrite it with an inversion for emphasis.',
         'https://podcasts.apple.com/us/podcast/masters-of-scale/id1227971746'),
        ('youtube', '"Inversion for Emphasis" -- Advanced English Grammar',
         "A clear, C1-level explanation of the exact grammar of this class: fronting a negative or limiting phrase and inverting the word order for emphasis. Connection to Lesson 20: 'Never before have we...' and 'Not only did we..., but we also...'.",
         'Tip: after each example, build your own inverted sentence about your company\'s future.',
         'https://www.youtube.com/watch?v=-Guv_qUFCOk'),
    ],
}
