# -*- coding: utf-8 -*-
"""As seis aulas do intensivo da Rita.

A REGUA e o artefato de teste da aula 1 (uma aula, feito para verificar a instrucao). Dele
vem: as CINCO FUNCOES como produto, as cinco linhas do mapa de fala, os quatro movimentos
de reparo, a cena como ela e de fato (ele pode chegar acompanhado, e ela abre OU apoia o
CEO) e as doze telas -- com feedback e retask na mesma tela, porque o retask e o feedback
aplicado, nao um exercicio a parte.

As aulas 2 a 6 saem da tabela do planejamento da regua, que da para cada aula a LINGUAGEM
PRINCIPAL e o PRODUTO CENTRAL. Nada aqui e inventado: os fatos vem do deck de marco de 2026
e do site publico, e numero que nao esta la ela encaminha.
"""

ESTAGIOS = [
    {'n': 'Real-world need and outcome', 'min': 5},
    {'n': 'Situation analysis',          'min': 5},
    {'n': 'Initial attempt and model',   'min': 8},
    {'n': 'Language and strategy toolkit','min': 9},
    {'n': 'Supported rehearsal',         'min': 10},
    {'n': 'Real-world performance',      'min': 9},
    {'n': 'Feedback and upgrade',        'min': 4},
    {'n': 'Focused retask and transfer', 'min': 5},
]

A1 = {
 'data': '20 August', 'cod': 'E1',
 'tema': "Company overview & Rita's role",
 'temaPre': 'Company overview & your role',
 'titulo': 'Company Overview<br><span class="accent">& Your Role</span>',
 'sub': 'Receiving a visitor from Carestream in S&atilde;o Paulo:<br>who we are, what we do, and what you are responsible for.',
 'desc': ('Abrir a recep&ccedil;&atilde;o ao presidente da Carestream: o que a empresa faz, h&aacute; quanto tempo, '
          'os tr&ecirc;s modelos e a fun&ccedil;&atilde;o dela &mdash; numa abertura curta e funcional, com slide e mapa de fala.'),
 'nav': ['Lesson opening', 'Your first minute', 'What makes this hard', 'Your first version',
         'A clear, simple opening', 'Five lines', 'When something goes wrong', 'Change one thing',
         'Essential message first', 'The opening, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The president of Carestream, visiting from the United States. Other people may join &mdash; this is not confirmed.'),
   ('Where', 'Your office in S&atilde;o Paulo. He has just arrived.'),
   ('Why', 'You open the presentation, or you support the CEO while he opens it.'),
   ('Outcome', 'He learns five things: what the company does, how long it has worked in the market, '
               'the three ways it works, who it works with, and what you are responsible for.'),
   ('With you', 'Your slide and your speech map, on the day too. Consulting them is not failure.'),
 ],
 'perguntas': ['Which of the five would you say first?',
               'Which one is hardest to say in English today?',
               'What would you do if he asked something that is not yours?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['He speaks fast, with an unfamiliar accent', 'You may answer before you understand the complete question.'],
    ['A word does not come', 'You may pause and lose the next part of your message.'],
    ['He asks about an area that is not yours', 'You may answer from memory, and the information may not be exact.'],
    ['He asks for a figure that is not on the slide', 'You may improvise a number in front of the CEO.']]),
 'tentativa': ('He has just <span class="accent">arrived</span>',
               'You are in the room. He is in front of you. The presentation is about to start.',
               'Open the presentation. Use anything you would use today &mdash; the slide, your notes, your own words. Nothing is corrected now.'),
 'modelo_t': 'A clear, <span class="accent">simple opening</span>',
 'modelo_txt': ['Let me give you a short overview of the company.',
                'We have been in the healthcare market for 38 years. We represent international brands, '
                'we distribute medical technology, and we provide technical services. We work with hospitals, '
                'clinics and specialized centers in Brazil.',
                'I am responsible for Corporate Management &mdash; IT, HR, projects, quality, corporate '
                'controlling, marketing and business processes.'],
 'modelo_q': 'What did it do that your version did not?',
 'linhas_t': 'Your <span class="accent">speech map</span>',
 'linhas': [('Let me give you a short overview of the company.', 'you announce, and the room is yours'),
            ('We have been in the healthcare market for 38 years.', 'the company in time'),
            ('We represent international brands, we distribute medical technology, and we provide technical services.', 'the three business models'),
            ('We work with hospitals, clinics and specialized centers in Brazil.', 'who the company works with'),
            ('I am responsible for Corporate Management.', 'your own role &mdash; and where his next question goes')],
 'apoio_t': 'Four moves that keep the <span class="accent">conversation going</span>',
 'apoio': [('Could you repeat that, please?', 'he spoke too fast'),
           ('That is with our technical team &mdash; [name] can give you more detail.', 'another person is responsible for that area'),
           ('Let me check the slide.', 'you need a moment, and a number'),
           ('I would need to confirm that.', 'you do not have the figure, and you will not supply one')],
 'ensaio_t': 'The same lines, <span class="accent">six ways</span>',
 'ensaio': [('To a customer, not a partner', 'We work with hospitals and clinics all over Brazil.'),
            ('Only the services part', 'We provide technical services: installation, training and maintenance.'),
            ('Only the representation part', 'We represent international brands here in Brazil.'),
            ('Start from the years', 'We have been in this market for 38 years, and we work in three ways.'),
            ('Start from your own role', 'I am responsible for Corporate Management &mdash; and the company works in three ways.'),
            ('In one sentence', 'We distribute and represent medical technology in Brazil, and we service what we sell.')],
 'mapa_t': 'Start with the essential message, <span class="accent">then add two details</span>',
 'mapa_lead': 'Your speech map stays in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the company, the time in the market, and your role.',
          '<strong>Then add:</strong> the three ways the company works, and who it works with. Nothing else.'],
 'perf': ('Good morning. <span class="accent">Welcome to Imagem.</span>',
          'He has just come into the room. Your slide is on the screen behind you. Your speech map is on the table. '
          'After you finish, he will ask you two or three short questions.',
          [('The scene', 'Open the presentation. The five functions, in your own words, with the map available.'),
           ('After you finish', 'Two or three short questions &mdash; the ones a visitor really asks first.')],
          ['a short overview', 'for 38 years', 'we represent', 'we distribute', 'I am responsible for']),
 'cmp': [('&ldquo;We sell many products for hospitals, many brands, many things.&rdquo;',
          '&ldquo;We represent international brands, we distribute medical technology, and we provide technical services.&rdquo;'),
         ('&ldquo;I work with IT, and HR, and quality, and controlling, and marketing, and&hellip;&rdquo;',
          '&ldquo;I am responsible for Corporate Management.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. Not the whole opening. The clearer version above stays on the screen.',
 'recap': ['Opening the presentation with the five functions',
           'Saying how long the company has worked in the market',
           'Saying the three ways the company works, in one sentence',
           'Saying who the company works with',
           'Saying what you are responsible for',
           'Four moves to keep the conversation going when something goes wrong'],
 'conf': ['Opening the company presentation in English',
          'Saying what I am responsible for',
          'Asking someone to repeat, or passing a question on'],
 'fecho_t': 'Lesson <span class="accent">complete</span>',
 'fecho': [('Today you opened the company presentation',
            'With your slide and your speech map in front of you &mdash; the way it will be on the day.'),
           ('You practiced five reusable lines',
            'The company, the time in the market, the three ways it works, who it works with, and your own role. '
            'And four ways to keep the interaction going.')],
 'proxima': 'Next: the story of the company, and how it is organized today.',
}

A2 = {
 'data': '24 August', 'cod': 'E2',
 'tema': 'History, expertise & organization',
 'temaPre': 'The story of the company',
 'titulo': 'The story of<br><span class="accent">the company</span>',
 'sub': 'Four moments from 1988 to today &mdash;<br>and how the company is organized now.',
 'desc': ('Narrativa apoiada de quatro marcos at&eacute; a organiza&ccedil;&atilde;o de hoje, com o papel da Rita '
          'e os n&uacute;meros gerais.'),
 'nav': ['Lesson opening', 'Why he asks', 'What makes this hard', 'Your first version',
         'Four moments', 'Five lines', 'When the question is not yours', 'Change one thing',
         'The story, then your part', 'The story, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The same visitor. He already knows what the company does.'),
   ('Why', 'He asks how the company started &mdash; and what he wants is a story he can follow, not a timeline.'),
   ('Outcome', 'He learns four moments, how the company is organized today, and where you sit in it.'),
   ('Numbers you own', '38 years &middot; 1988 &middot; 146 employees. Anything else you confirm later.'),
   ('With you', 'Your slide and your speech map. About thirty seconds for the story.'),
 ],
 'perguntas': ['If you had to choose four moments from 38 years, which ones matter to him?',
               'How is the company organized today, in one sentence?',
               'What would you pass on to someone else?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['You start in 1988 and try to reach 2026 date by date', 'He stops following at the fifth date, and the story loses its shape.'],
    ['He asks about a partner you do not handle', 'You may answer from memory instead of passing it on.'],
    ['He asks how many people work in an area that is not yours', 'You may give a number you are not sure of.'],
    ['The word for a business change does not come', 'The sentence stops in the middle of the story.']]),
 'tentativa': ('&ldquo;How did the company <span class="accent">start</span>?&rdquo;',
               'No list, no notes. About thirty seconds.',
               'Tell him the story of the company as you would tell it today.'),
 'modelo_t': 'Four moments, <span class="accent">not thirteen</span>',
 'modelo_txt': ['We started as a distributor of Kodak film in 1988.',
                'In 1996, we became a sales representative for GE Diagnostic Imaging. This allowed us to '
                'represent other international brands.',
                'Today we are organized into commercial, technical service and corporate areas, with 146 employees. '
                'I oversee Corporate Management.'],
 'modelo_q': 'What links the four moments? Say it in one sentence.',
 'linhas_t': 'Your <span class="accent">speech map</span>',
 'linhas': [('We started as a distributor of Kodak film in 1988.', 'where it began'),
            ('In 1996, we became a sales representative for GE Diagnostic Imaging.', 'the step that changed the company'),
            ('This allowed us to represent other international brands.', 'the link between two moments'),
            ('Today we are organized into commercial, technical service and corporate areas.', 'how it works now'),
            ('I oversee Corporate Management.', 'where you sit in it')],
 'apoio_t': 'When the question is <span class="accent">not yours</span>',
 'apoio': [('Could you repeat that, please?', 'he spoke too fast'),
           ('That is with our commercial team &mdash; [name] can give you more detail.', 'another area answers it'),
           ('Let me check the slide.', 'the date or the number is on the screen'),
           ('I would need to confirm that.', 'the deck does not give it')],
 'ensaio_t': 'The same story, <span class="accent">four ways</span>',
 'ensaio': [('In one minute', 'The four moments, one sentence each.'),
            ('In thirty seconds', 'Where it started, the step up, and today.'),
            ('In one sentence', 'We started in 1988 and today we represent, distribute and service medical technology.'),
            ('Starting from today', 'Today we are organized into three areas &mdash; and it started in 1988 with Kodak film.')],
 'mapa_t': 'The story, <span class="accent">then your part</span>',
 'mapa_lead': 'Your speech map stays in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the four moments, in order.',
          '<strong>Then add:</strong> how the company is organized today, and what you oversee.'],
 'perf': ('&ldquo;I would like to understand the <span class="accent">company</span>.&rdquo;',
          'About one minute. Slide and speech map with you. He asks one follow-up at the end.',
          [('His side', '&ldquo;Where did it start, and what do you do here?&rdquo;'),
           ('Your side', 'Four moments, how it is organized today, and your own area.')],
          ['we started as', 'we became', 'this allowed us to', 'today we are organized into', 'I oversee']),
 'cmp': [('&ldquo;The company is old, from the eighties, and grew a lot.&rdquo;',
          '&ldquo;We started as a distributor of Kodak film in 1988.&rdquo;'),
         ('&ldquo;We have many areas and many people.&rdquo;',
          '&ldquo;Today we are organized into commercial, technical service and corporate areas, with 146 employees.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. Not the whole story.',
 'recap': ['Telling 38 years in four moments',
           'Saying what a sales representative does',
           'Linking one moment to the next with <em>this allowed us to&hellip;</em>',
           'Saying how the company is organized today',
           'Saying what you oversee',
           'Passing on a question about another area'],
 'conf': ['Telling the story of the company',
          'Explaining how the company is organized today',
          'Saying what I oversee, without a list that never ends'],
 'fecho_t': 'Lesson <span class="accent">complete</span>',
 'fecho': [('Today you told the story of the company',
            'Four moments, with the link between them &mdash; not a timeline.'),
           ('You said where you sit in it',
            'How the company is organized today, and what you oversee. And what you pass on.')],
 'proxima': 'Next: the portfolio &mdash; the categories, the partners, and one example each.',
}

A3 = {
 'data': '25 August', 'cod': 'E3',
 'tema': 'Commercial portfolio & partners',
 'temaPre': 'What the company sells',
 'titulo': 'The portfolio,<br><span class="accent">in four categories</span>',
 'sub': 'What the company sells, for which partners &mdash;<br>and one example each. Not a catalogue.',
 'desc': 'Vis&atilde;o geral do portf&oacute;lio: categorias, parceiros e um exemplo por categoria.',
 'nav': ['Lesson opening', 'What he wants to place', 'What makes this hard', 'Your first version',
         'Four categories', 'Five lines', 'When the number is not yours', 'Change one thing',
         'Categories, then partners', 'The portfolio, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The president of Carestream. He knows imaging better than anyone in the room.'),
   ('Why', 'He wants to place his own products inside what you carry.'),
   ('Outcome', 'He learns the four categories, one example of each, and which brands you represent &mdash; his own included.'),
   ('Not today', 'Partner share is confidential and belongs to lesson 5. Today you pass it on.'),
   ('With you', 'The portfolio slide and your speech map.'),
 ],
 'perguntas': ['Which category is the one he cares about most?',
               'Which example would you give for that category?',
               'What do you say when he asks which partner is biggest?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['You list every product', 'He loses the shape, and the portfolio sounds like a catalogue.'],
    ['A product name does not come in English', 'The sentence stops, when the category would have answered.'],
    ['He asks which partner is biggest', 'You may give a share number that is not yours to give.'],
    ['He asks about a solution you do not know well', 'You may explain it from memory instead of passing it on.']]),
 'tentativa': ('&ldquo;What does your <span class="accent">portfolio</span> look like?&rdquo;',
               'No list. About thirty seconds.',
               'Tell him what the company sells, as you would tell it today.'),
 'modelo_t': 'Four categories, <span class="accent">one example each</span>',
 'modelo_txt': ['Our portfolio covers four main areas: diagnostic imaging, advanced surgical technology, '
                'hospital care, and cardiology.',
                'This solution is used for diagnosis &mdash; X-ray, ultrasound and bone densitometry, for example.',
                'We represent international brands, and our technical team can provide more detail on any of them.'],
 'modelo_q': 'Why one example each, and not the whole catalogue?',
 'linhas_t': 'Your <span class="accent">speech map</span>',
 'linhas': [('Our portfolio covers four main areas.', 'the shape, before any product'),
            ('Diagnostic imaging &mdash; for example, X-ray and ultrasound.', 'category, then one example'),
            ('This solution is used for diagnosis in hospitals and clinics.', 'what the product is for'),
            ('We represent international brands, including Carestream.', 'his own company, in your words'),
            ('Our technical team can provide more detail.', 'where the detail lives')],
 'apoio_t': 'When the number is <span class="accent">not yours</span>',
 'apoio': [('Could you repeat that, please?', 'he spoke too fast'),
           ('Our technical team can provide more detail.', 'the product question goes deeper than your area'),
           ('Let me check the slide.', 'the category or the brand is on the screen'),
           ('I would need to confirm that.', 'partner share &mdash; not today, and not from memory')],
 'ensaio_t': 'The same portfolio, <span class="accent">four ways</span>',
 'ensaio': [('To someone who knows the products', 'The four categories, no examples. He will ask for them.'),
            ('To someone who has never seen it', 'Four categories, one example each, slowly.'),
            ('Starting from imaging', 'The category he came for, first &mdash; then the other three.'),
            ('In one sentence', 'We cover imaging, surgery, hospital care and cardiology, and we represent international brands.')],
 'mapa_t': 'Categories, <span class="accent">then partners</span>',
 'mapa_lead': 'Your speech map stays in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the four categories, with one example each.',
          '<strong>Then add:</strong> the brands you represent, and where the detail lives.'],
 'perf': ('&ldquo;Walk me through <span class="accent">what you carry</span>.&rdquo;',
          'About one minute. Portfolio slide and speech map with you. He asks two short questions at the end.',
          [('Your side', 'Four categories with one example each, then the partners &mdash; his own named.'),
           ('His side', 'One question about a category, and one about partner share.')],
          ['our portfolio covers', 'for example', 'is used for', 'we represent', 'more detail']),
 'cmp': [('&ldquo;We sell X-ray, ultrasound, densitometry, staplers, monitors, pacemakers&hellip;&rdquo;',
          '&ldquo;Our portfolio covers four main areas. Diagnostic imaging, for example X-ray and ultrasound.&rdquo;'),
         ('&ldquo;Carestream is about thirty per cent, I think.&rdquo;', '&ldquo;I would need to confirm that.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. Not the whole portfolio.',
 'recap': ['Presenting the portfolio as four categories',
           'Giving one example per category, and stopping there',
           'Saying what a solution is used for',
           'Naming the brands the company represents',
           'Passing a product question to the technical team',
           'Refusing a share number without losing the conversation'],
 'conf': ['Presenting what the company sells',
          'Naming partners and what we do for them',
          'Saying <em>I would need to confirm that</em> in front of a partner'],
 'fecho_t': 'Lesson <span class="accent">complete</span>',
 'fecho': [('Today you presented the portfolio',
            'Four categories, one example each &mdash; and the brands, including his.'),
           ('You kept a number to yourself',
            'Partner share is lesson 5, and it is confidential. Passing it on is the right answer, not a gap.')],
 'proxima': 'Next: where the company operates, and what the service team can do.',
}

A4 = {
 'data': '26 August', 'cod': 'E4',
 'tema': 'Commercial and service coverage',
 'temaPre': 'Where the company operates',
 'titulo': 'Coverage<br><span class="accent">and service</span>',
 'sub': 'Where the company operates, and who keeps<br>the equipment running after it is installed.',
 'desc': ('Explica&ccedil;&atilde;o da cobertura comercial e da capacidade de servi&ccedil;o, com um benef&iacute;cio operacional.'),
 'nav': ['Lesson opening', 'The question behind the question', 'What makes this hard', 'Your first version',
         'Where and who', 'Five lines', 'When you do not have the figure', 'Change one thing',
         'Coverage, then service', 'The answer, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The president of Carestream, deciding whether to expand XR operations with you.'),
   ('Why', 'Behind the coverage question there is another one: can you support what you sell?'),
   ('Outcome', 'He learns where the company operates, that the service team is in-house, and one operational benefit.'),
   ('Numbers you own', 'The service team and its technicians, from the deck. Response time is not there &mdash; you confirm it later.'),
   ('With you', 'The coverage slide and your speech map.'),
 ],
 'perguntas': ['What would you want to hear, if you were the one buying?',
               'Which half matters more to him: where you are, or who supports it?',
               'What do you say about response time?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['You list the states, then list the service team', 'He hears two lists and does not see that they are one answer.'],
    ['He asks about response time', 'You may improvise an SLA the company has not given you.'],
    ['He asks about a state you do not cover', 'You may say more than the deck supports.'],
    ['The word for a service activity does not come', 'The strongest part of the answer stops halfway.']]),
 'tentativa': ('&ldquo;Where do you <span class="accent">operate</span>?&rdquo;',
               'About thirty seconds. No map.',
               'Tell him where the company operates and who supports the equipment.'),
 'modelo_t': 'Where, <span class="accent">and who</span>',
 'modelo_txt': ['Our headquarters is in S&atilde;o Paulo, with our distribution centre.',
                'We operate directly in several states, and we have a logistics branch in Santa Catarina for imports.',
                'Our service team includes technicians, coordinators and applications support &mdash; it is in-house, '
                'not outsourced. That is the operational benefit: we install it, we train your people, and we maintain it.'],
 'modelo_q': 'Which half of that answer is he really asking about?',
 'linhas_t': 'Your <span class="accent">speech map</span>',
 'linhas': [('Our headquarters is in S&atilde;o Paulo.', 'where the operation sits'),
            ('We operate directly in several states.', 'reach, without reading a map'),
            ('Our service team includes technicians, coordinators and applications support.', 'what the team actually is'),
            ('The team is in-house, not outsourced.', 'the operational benefit'),
            ('I would need to confirm that detail.', 'response time, and anything else the deck does not give')],
 'apoio_t': 'When you do not have <span class="accent">the figure</span>',
 'apoio': [('Could you repeat that, please?', 'he spoke too fast'),
           ('That is with our technical team &mdash; [name] can give you more detail.', 'the service question goes deeper'),
           ('Let me check the slide.', 'the states and the team are on the screen'),
           ('I would need to confirm that detail.', 'response time is not in the deck')],
 'ensaio_t': 'The same answer, <span class="accent">four questions</span>',
 'ensaio': [('&ldquo;Where are you located?&rdquo;', 'S&atilde;o Paulo first, then reach.'),
            ('&ldquo;Do you cover the whole country?&rdquo;', 'Direct operation in several states, logistics nationwide.'),
            ('&ldquo;What happens after we buy?&rdquo;', 'Straight to the service team &mdash; installation, training, maintenance.'),
            ('&ldquo;How fast do you respond?&rdquo;', 'The confirmation line, said calmly, and the answer continues.')],
 'mapa_t': 'Coverage, <span class="accent">then service</span>',
 'mapa_lead': 'Your speech map stays in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the headquarters, the states, and the logistics branch.',
          '<strong>Then add:</strong> the service team, that it is in-house, and what it does.'],
 'perf': ('&ldquo;Who installs it, and who <span class="accent">keeps it running</span>?&rdquo;',
          'About one minute. Coverage slide and speech map with you. He asks about response time at the end.',
          [('Your side', 'Both halves, joined: where the company is, and the in-house service team.'),
           ('His side', 'One question about a state, and one about response time.')],
          ['our headquarters is in', 'we operate directly in', 'our service team includes', 'in-house', 'confirm that detail']),
 'cmp': [('&ldquo;We have people in many states and also a service team.&rdquo;',
          '&ldquo;We operate directly in several states &mdash; and our service team is in-house.&rdquo;'),
         ('&ldquo;We answer in about 24 hours, I believe.&rdquo;', '&ldquo;I would need to confirm that detail.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. Not the whole answer.',
 'recap': ['Answering coverage and service as one answer',
           'Saying where the headquarters and the distribution centre are',
           'Saying <em>we operate directly in&hellip;</em> without promising an office everywhere',
           'Saying what the service team includes',
           'Saying <em>in-house</em>, and why it matters to him',
           'Refusing a response time you do not have'],
 'conf': ['Explaining where the company operates',
          'Explaining what happens after the sale',
          'Refusing a figure and keeping the conversation'],
 'fecho_t': 'Lesson <span class="accent">complete</span>',
 'fecho': [('Today you answered the support question',
            'Coverage and service as one answer &mdash; where the company is, and who keeps it running.'),
           ('You gave one operational benefit',
            'The service team is in-house. It is the strongest thing you can say in that moment, and it is true.')],
 'proxima': 'Next: the charts &mdash; the main message of each one, and the question you cannot answer.',
}

A5 = {
 'data': '27 August', 'cod': 'E5',
 'tema': 'Results, growth & integrated Q&A',
 'temaPre': 'The charts, and the questions',
 'titulo': 'The charts,<br><span class="accent">one message each</span>',
 'sub': 'He can read the numbers. Your job is the message &mdash;<br>and what to say when the figure is not confirmed.',
 'desc': ('Mensagem principal por gr&aacute;fico priorit&aacute;rio, um n&uacute;mero, uma compara&ccedil;&atilde;o e duas '
          'oportunidades &mdash; com o que dizer quando o dado n&atilde;o se confirma.'),
 'nav': ['Lesson opening', 'What a chart needs from you', 'What makes this hard', 'Your first version',
         'One message per chart', 'Five lines', 'When the figure is not confirmed', 'Change one thing',
         'The message, then the number', 'The results, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The president of Carestream, looking at the results slide before you speak.'),
   ('Why', 'Numbers on a slide do not carry a message. You give each chart one.'),
   ('Outcome', 'He learns one message per priority chart, one number, one comparison, and two opportunities.'),
   ('Confidentiality', 'Revenue, net income and partner share are authorised for this meeting only. Confirm before the lesson. '
                       'Recurring revenue and commissions were never given &mdash; those you pass on.'),
   ('With you', 'The results slide and your speech map.'),
 ],
 'perguntas': ['If he sees one chart and you say one sentence, what should that sentence do?',
               'Which chart matters most to him?',
               'What do you say when the figure is not on the slide?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['You read every number on the chart', 'He stops listening, because he is already reading it.'],
    ['He asks for a figure that is not on the slide', 'You may improvise a number in front of the CEO.'],
    ['He asks about recurring revenue', 'You may treat a missing figure as something you forgot.'],
    ['You say an opportunity as a plan', 'He may write down a commitment the company has not made.']]),
 'tentativa': ('&ldquo;How did <span class="accent">last year</span> go?&rdquo;',
               'About thirty seconds. One chart: net income, 2024 to 2025.',
               'Give him the headline, as you would give it today.'),
 'modelo_t': 'One message <span class="accent">per chart</span>',
 'modelo_txt': ['Net income increased from 87.7 to 105.6 million reais &mdash; about twenty per cent.',
                'Carestream accounts for a much larger share of our partner mix than in 2024: it increased '
                'from eighteen to thirty-eight per cent.',
                'One opportunity is the Midea portfolio in Brazil. We expect to expand with Danaher and Leica '
                'in the interior of S&atilde;o Paulo. Anything beyond that, I would need to confirm.'],
 'modelo_q': 'What does &ldquo;about twenty per cent&rdquo; do that &ldquo;105.6&rdquo; does not?',
 'linhas_t': 'Your <span class="accent">speech map</span>',
 'linhas': [('Net income increased from 87.7 to 105.6 million reais.', 'the number, from the deck'),
            ('That is about twenty per cent.', 'the message, which the chart does not say'),
            ('Carestream accounts for thirty-eight per cent of our partner mix.', 'his own company, in your numbers'),
            ('One opportunity is the Midea portfolio in Brazil.', 'a possibility, said as one'),
            ('I would need to confirm that figure.', 'recurring revenue, commissions, anything not in the deck')],
 'apoio_t': 'When the figure is <span class="accent">not confirmed</span>',
 'apoio': [('Could you repeat that, please?', 'he spoke too fast'),
           ('Let me check the slide.', 'the figure is on the screen and you want it exact'),
           ('I would need to confirm that figure.', 'it was never given to you &mdash; nothing to remember'),
           ('That is an opportunity, not a commitment.', 'before he writes it down as a plan')],
 'ensaio_t': 'The same results, <span class="accent">four questions</span>',
 'ensaio': [('&ldquo;How was last year?&rdquo;', 'One message. Stop.'),
            ('&ldquo;And how much of that is us?&rdquo;', 'The mix, and what it means for him.'),
            ('&ldquo;What is your recurring revenue?&rdquo;', 'The confirmation line, calmly, and keep going.'),
            ('&ldquo;So you are launching Midea?&rdquo;', 'The opportunity, said as an opportunity.')],
 'mapa_t': 'The message, <span class="accent">then the number</span>',
 'mapa_lead': 'Your speech map stays in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the message of the chart, in one sentence.',
          '<strong>Then add:</strong> the number, the comparison, and one opportunity &mdash; as an opportunity.'],
 'perf': ('&ldquo;Give me the headline, and where you see <span class="accent">this going</span>.&rdquo;',
          'About one minute, then two questions. Results slide and speech map with you.',
          [('Your side', 'One message per chart, then the two opportunities.'),
           ('His side', 'One question about the mix, and one figure you were never given.')],
          ['increased from', 'accounts for', 'about twenty per cent', 'one opportunity is', 'confirm that figure']),
 'cmp': [('&ldquo;In 2024 we had 87.74 and in 2025, 105.63, and in January&hellip;&rdquo;',
          '&ldquo;Net income increased from 87.7 to 105.6 million reais &mdash; about twenty per cent.&rdquo;'),
         ('&ldquo;We will launch Midea in Brazil.&rdquo;',
          '&ldquo;One opportunity is the Midea portfolio &mdash; that is an opportunity, not a commitment.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. Not the whole results block.',
 'recap': ['Giving each chart one message instead of reading it',
           'Saying a number with <em>increased from&hellip; to&hellip;</em>',
           'Saying what a share means for the person in the room',
           'Saying an opportunity as an opportunity',
           'Refusing a figure that was never given to you',
           'Coming back to the message after a hard question'],
 'conf': ['Summarising a chart in one sentence',
          'Talking about growth with the partner in the room',
          'Refusing a number without losing authority'],
 'fecho_t': 'Lesson <span class="accent">complete</span>',
 'fecho': [('Today you gave the charts a message',
            'One sentence each &mdash; the part he cannot read from the slide.'),
           ('You separated opportunity from commitment',
            'And you refused a figure that was never given to you, without treating it as a gap.')],
 'proxima': 'Next: the whole meeting, once, with interruptions.',
}

A6 = {
 'data': '28 August', 'cod': 'E6',
 'tema': 'Full meeting simulation',
 'temaPre': 'The whole meeting',
 'titulo': 'The whole meeting,<br><span class="accent">once</span>',
 'sub': 'Nothing new today. You run what you built,<br>with the same slides and the same speech map.',
 'desc': 'Apresenta&ccedil;&atilde;o funcional com apoio, Q&amp;A previs&iacute;vel e estrat&eacute;gias de reparo.',
 'nav': ['Lesson opening', 'Monday is the meeting', 'What makes this hard', 'First run',
         'The five blocks', 'Five lines', 'The repair moves, together', 'Change one thing',
         'The block you chose', 'The meeting, for real', 'Feedback and focused retask',
         'Lesson complete'],
 'brief': [
   ('Who', 'The president of Carestream. On 31 August, for real.'),
   ('Why', 'This is the last run before the meeting. Nothing new enters today.'),
   ('Outcome', 'You present with support, answer the predictable questions, and repair what breaks.'),
   ('Pressure', 'He interrupts twice, and one question belongs to another area.'),
   ('With you', 'The same slides and the same speech maps as on the day.'),
 ],
 'perguntas': ['Which part of the meeting still worries you?',
               'Which block would you cut if he had ten minutes?',
               'What is your line for a question that is not yours?'],
 'riscos_tab': (['What can happen', 'What it does to you'],
   [['He interrupts in the middle of a block', 'You may lose the place you were in and restart from the top.'],
    ['He asks something from another area', 'You may answer from memory instead of passing it on.'],
    ['A word does not come', 'The sentence stops, and the block stops with it.'],
    ['He asks two questions at once', 'You may answer the second and drop the first.']]),
 'tentativa': ('Open, and keep going until <span class="accent">I stop you</span>',
               'Slides and speech maps with you.',
               'He has just sat down. Begin.'),
 'modelo_t': 'The <span class="accent">five blocks</span>',
 'modelo_txt': ['Welcome and the company: what it does, how long, the three models, who it works with, and your role.',
                'The story in four moments, and how the company is organized today.',
                'The portfolio in four categories, with the partners &mdash; then coverage and the in-house service team, '
                'and the results with one message per chart.'],
 'modelo_q': 'Which block would you never cut?',
 'linhas_t': 'The lines that <span class="accent">open each block</span>',
 'linhas': [('Let me give you a short overview of the company.', 'block 1'),
            ('We started as a distributor of Kodak film in 1988.', 'block 2'),
            ('Our portfolio covers four main areas.', 'block 3'),
            ('Our headquarters is in S&atilde;o Paulo, and our service team is in-house.', 'block 4'),
            ('Net income increased from 87.7 to 105.6 million reais.', 'block 5')],
 'apoio_t': 'The repair moves, <span class="accent">together</span>',
 'apoio': [('Could you repeat that?', 'he spoke too fast, or two questions came at once'),
           ('If I understood correctly, you are asking about&hellip;', 'you check before you answer'),
           ('Let me check the slide.', 'the number is on the screen'),
           ('[Name] can provide more detail.', 'the question belongs to another area')],
 'ensaio_t': 'The block <span class="accent">you chose</span>',
 'ensaio': [('As it is', 'The block you named at the start, with the map in front of you.'),
            ('Shorter', 'The same block in one sentence &mdash; the ten-minute version.'),
            ('Interrupted', 'The same block, and he cuts in halfway. Come back to where you were.'),
            ('Without the map', 'Only if it is already comfortable. Consulting is not failure on the day.')],
 'mapa_t': 'Five blocks, <span class="accent">in order</span>',
 'mapa_lead': 'Your speech maps stay in front of you. Both times.',
 'mapa': ['<strong>First:</strong> the five blocks, one after the other, with the repair moves when you need them.',
          '<strong>Then:</strong> the questions &mdash; the predictable ones, and the one that is not yours.'],
 'perf': ('The <span class="accent">full meeting</span>',
          'Slides and speech maps with you, exactly as on Monday. He will interrupt twice.',
          [('Your side', 'Five blocks, in order, and the repair moves when something breaks.'),
           ('His side', '&ldquo;How long have you been in the market?&rdquo; &middot; &ldquo;Who handles installation?&rdquo; '
                        '&middot; &ldquo;What is your recurring revenue?&rdquo; &middot; &ldquo;Who decides on new partnerships?&rdquo;')],
          ['let me check the slide', 'if I understood correctly', 'can provide more detail', 'I would need to confirm']),
 'cmp': [('&ldquo;Sorry, sorry &mdash; where was I? I do not remember.&rdquo;',
          '&ldquo;Let me check the slide. So &mdash; where the company operates.&rdquo;'),
         ('&ldquo;I think it is around thirty per cent, more or less.&rdquo;', '&ldquo;I would need to confirm that.&rdquo;')],
 'retask': 'Try it now &mdash; say only the part we changed. It is the part you take to Monday.',
 'recap': ['Running the five blocks in order, with support',
           'Coming back to your place after an interruption',
           'Checking a question before answering it',
           'Passing on what belongs to another area',
           'Refusing a figure and keeping the room',
           'Closing the meeting yourself'],
 'conf': ['Presenting the whole company on 31 August',
          'Handling an interruption without losing my place',
          'Answering a question I did not prepare for'],
 'fecho_t': 'Intensive <span class="accent">complete</span>',
 'fecho': [('Today you ran the whole meeting',
            'Five blocks, two interruptions, and a question that was not yours &mdash; and you came back each time.'),
           ('On 31 August nothing in that room will be new',
            'The same slides, the same speech maps, and the same four moves for when something goes wrong.')],
 'proxima': 'The meeting is on 31 August. You have everything you practiced here in front of you.',
}

AULAS = {1: A1, 2: A2, 3: A3, 4: A4, 5: A5, 6: A6}
for _n, _a in AULAS.items():
    _a['n'] = _n
    _a['mod'] = 'ESP'
    _a['stages'] = [dict(s) for s in ESTAGIOS]
    assert len(_a['nav']) == 12, 'a aula %d nao tem 12 rotulos de tela' % _n
