# -*- coding: utf-8 -*-
"""Pre-class das seis aulas, no formato da REGUA.

Seis atividades, sempre nas mesmas seis funcoes: contextualizar, preparar lexico, reutilizar
lexico, processar o input principal, notar e organizar a linguagem, aplicar brevemente. O
rotulo da funcao e do PROFESSOR (em portugues); a aluna ve 'Activity N'.

Duas regras que vem da regua e nao se negociam:
  1. o pre-class NAO adianta a producao oral -- nao ha gravacao aqui, e a primeira versao
     falada acontece na etapa 3 da aula, sem modelo antes;
  2. a aula corre igual se ela nao fez o pre-class.

'nota' e o gabarito do professor: por que a resposta e essa, o que costuma gerar duvida, o
que e so reconhecimento, de onde vem o fato e onde aquilo reaparece no in-class. As respostas
o proprio exercicio ja carrega -- o gabarito as extrai, ninguem as escreve duas vezes.
"""

DECK = 'Deck institucional de mar&ccedil;o de 2026.'
SITE = 'Site p&uacute;blico da empresa.'

PRE = {}

PRE[1] = {'intro': ('Six short activities, about 15&ndash;20 minutes. Do them before the lesson. Nothing here is a '
                    'test &mdash; it prepares the words you will use in class. You do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'The president of Carestream is arriving at your office in S&atilde;o Paulo. You have about one minute before the presentation starts. Choose the best answer.',
   'q': 'What does he most want to hear in that first minute?',
   'ops': [('Every product the company sells.', 0),
           ('Who the company is, how long it has worked, and who you are.', 1),
           ('The revenue for each partner last year.', 0),
           ('The name of every manager in the company.', 0)],
   'rat': 'In the first minute a visitor is placing you: the company, the time it has been working, and your own position. Detail comes later &mdash; and much of it is not yours to give.',
   'nota': {'alt': 'Nenhuma. A, C e D s&atilde;o conte&uacute;do real do deck &mdash; e por isso s&atilde;o plaus&iacute;veis e ainda assim erradas para o primeiro minuto.',
            'pq': 'C &eacute; o dado que ela menos est&aacute; autorizada a oferecer; D &eacute; a &aacute;rea que ela deve encaminhar.',
            'duvida': 'Se ela escolher A, aceite o racioc&iacute;nio &mdash; o deck de fato abre pelo portf&oacute;lio &mdash; e separe a ordem do DECK da primeira pergunta do VISITANTE.',
            'inclass': 'A etapa 1 abre com a mesma cena e a transforma no produto observ&aacute;vel: as cinco fun&ccedil;&otilde;es, com o slide e o mapa de fala dispon&iacute;veis.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each expression with its meaning. These six expressions come back in every activity of this lesson.',
   'pares': [('healthcare market', 'the business of hospitals, clinics and health products'),
             ('medical technology', 'machines and equipment used in hospitals'),
             ('to represent a brand', "to sell and speak for another company's brand in your country"),
             ('to distribute', 'to bring products from the maker to the hospital or clinic'),
             ('to provide technical services', 'to install equipment, train people and repair machines'),
             ('to be responsible for', 'to have an area of the company under your management')],
   'nota': {'pq': 'S&atilde;o o n&uacute;cleo produtivo da aula &mdash; as que ela DIZ, n&atilde;o s&oacute; entende. <em>Represent</em>, <em>distribute</em> e <em>provide technical services</em> s&atilde;o os tr&ecirc;s modelos de neg&oacute;cio do deck.',
            'duvida': 'Se ela confundir <em>represent</em> e <em>distribute</em>, gaste o tempo aqui: &eacute; a distin&ccedil;&atilde;o sobre a qual o slide de overview inteiro se apoia.',
            'recon': '<em>specialized centers</em>, <em>regulatory support</em> e <em>corporate management</em> aparecem no texto e n&atilde;o se cobram em produ&ccedil;&atilde;o. N&atilde;o treine.',
            'inclass': 'A etapa 4 pega estas seis e as coloca nas cinco linhas.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the sentences about your company. Use one word in each gap.',
   'banco': ['healthcare', 'represent', 'distribute', 'provide', 'responsible'],
   'itens': [('We work in the ', 'healthcare', ' market.'),
             ('We ', 'represent', ' international brands in Brazil.'),
             ('We ', 'distribute', ' medical technology to hospitals and clinics.'),
             ('We also ', 'provide', ' technical services: installation, training and maintenance.'),
             ('I am ', 'responsible', ' for Corporate Management.')],
   'nota': {'alt': 'A checagem ignora mai&uacute;sculas e espa&ccedil;os. Nada al&eacute;m do banco &eacute; aceito: cada lacuna tem uma palavra.',
            'pq': 'As cinco frases n&atilde;o s&atilde;o exemplos &mdash; s&atilde;o as cinco linhas da aula, j&aacute; nas palavras da empresa dela. Ela as encontra aqui como lacuna e as reencontra na etapa 4 como linguagem para dizer.',
            'inclass': 'A frase 5 &eacute; a que ela mais vai precisar e menos espera: <em>responsible for</em> &eacute; a estrutura do pr&oacute;prio cargo.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('Imagem Healthcare Solutions has been in the healthcare market for <strong>38 years</strong>. The company '
             'started in 1988. Today it works with hospitals, clinics and specialized centers in Brazil.<br><br>'
             'The company works in three ways. It <strong>represents</strong> international brands in Brazil. It '
             '<strong>distributes</strong> medical technology &mdash; equipment for diagnostic imaging, surgery, hospital '
             'care and cardiology. And it <strong>provides technical services</strong>: installation, training, '
             'preventive maintenance and repair.<br><br>'
             'The head office is in S&atilde;o Paulo. The CEO is Thomaz Rodrigues. The company has 146 employees.'),
   'perguntas': [
     ('1. What is the text mainly about?',
      [('The history of the company, year by year.', 0), ('What the company does and how it works.', 1),
       ('The people who work in each area.', 0)],
      'The text gives one date and one name, but everything else answers the same question: what the company does.'),
     ('2. How long has the company been in the healthcare market?',
      [('146 years.', 0), ('38 years.', 1), ('1988 years.', 0)],
      '38 years. The other two numbers are in the text, and that is why they are here: in the meeting, the risk is saying the right number for the wrong question.'),
     ('3. The text says the company works in three ways. Which three?',
      [('It represents, it distributes, and it provides technical services.', 1),
       ('It makes equipment, it sells it, and it repairs it.', 0),
       ('Diagnostic imaging, surgery, and cardiology.', 0)],
      'A. C names the product areas, not the business models. B is wrong on the first verb: the company does not make the equipment.')],
   'nota': {'pq': 'Uma leitura, tr&ecirc;s perguntas, uma opera&ccedil;&atilde;o: ler para informa&ccedil;&atilde;o. As tr&ecirc;s op&ccedil;&otilde;es da pergunta 2 s&atilde;o n&uacute;meros reais do texto.',
            'duvida': 'Se ela responder C na pergunta 3, est&aacute; lendo o portf&oacute;lio em vez do modelo de neg&oacute;cio &mdash; distin&ccedil;&atilde;o da etapa 3 do in-class.',
            'fonte': '38 anos, 1988, representa&ccedil;&atilde;o/distribui&ccedil;&atilde;o/servi&ccedil;o, sede em S&atilde;o Paulo, CEO Thomaz Rodrigues e 146 employees: ' + DECK +
                     ' Hospitais, cl&iacute;nicas e centros especializados, e as quatro categorias de produto: ' + SITE +
                     ' Nada aqui &eacute; inferido, e nenhum n&uacute;mero foi recalculado.',
            'inclass': 'A etapa 3 traz o mesmo texto como modelo, depois da produ&ccedil;&atilde;o dela.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines make an opening. Put them in order, from 1 to 5.',
   'linhas': [('Let me give you a short overview of the company.', 1),
              ('We have been in the healthcare market for 38 years.', 2),
              ('We represent international brands, we distribute medical technology, and we provide technical services.', 3),
              ('We work with hospitals, clinics and specialized centers in Brazil.', 4),
              ('I am responsible for Corporate Management.', 5)],
   'nota': {'alt': 'Trocar 3 e 4 ainda produz uma abertura utiliz&aacute;vel e deve ser aceito na fala. Aqui conta como erro s&oacute; porque a atividade pede UMA ordem &mdash; diga isso se ela levantar, e trate o racioc&iacute;nio dela como evid&ecirc;ncia, n&atilde;o como falha.',
            'pq': 'A ordem &eacute; o mapa de fala: anunciar, situar a empresa no tempo, dizer os tr&ecirc;s modelos, dizer para quem, dizer quem ela &eacute;. Termina nela porque &eacute; para l&aacute; que vai a pr&oacute;xima pergunta do visitante.',
            'inclass': 'Este &eacute; o mapa que fica na frente dela nas etapas 5 e 6. Ela consulta &mdash; nunca se pede que ela recite.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each. Use the lines from activity 5 to help you.',
   'perguntas': ['What does Imagem do?', 'What are you responsible for?'],
   'modelo': ['Imagem has been in the healthcare market for 38 years. We represent international brands, we distribute medical technology, and we provide technical services.',
              'I am responsible for Corporate Management &mdash; IT, HR, projects, quality, corporate controlling, marketing and business processes.'],
   'nota': {'pq': 'Escrita curta, n&atilde;o grava&ccedil;&atilde;o. &Eacute; a evid&ecirc;ncia mais barata de acesso lexical que voc&ecirc; ter&aacute; antes de ouvi-la falar &mdash; leia antes de abrir a aula.',
            'inclass': 'A etapa 3 pede exatamente isto em voz alta, sem modelo antes.'}},
 ]}

PRE[2] = {'intro': ('Six short activities, about 15&ndash;20 minutes. They prepare the words for the story of the '
                    'company. Nothing here is a test, and you do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'The visitor already knows what the company does. Now he asks how it started. Choose the best answer.',
   'q': 'What does he most want from the story?',
   'ops': [('Every year of the company, in order.', 0),
           ('A few moments he can follow, and where you fit today.', 1),
           ('The names of all the partners since 1988.', 0),
           ('The revenue of each year.', 0)],
   'rat': 'A story he can repeat has four moments, not thirteen dates. And it ends where you are.',
   'nota': {'alt': 'Aceite tamb&eacute;m quem responder B e acrescentar &ldquo;e como a empresa est&aacute; organizada hoje&rdquo;.',
            'pq': 'O risco desta aula &eacute; COMPRIMENTO. Quatro momentos t&ecirc;m forma; treze datas t&ecirc;m lista.',
            'inclass': 'A etapa 1 abre com a mesma pergunta, agora em voz alta.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each expression with its meaning. These six come back in every activity of this lesson.',
   'pares': [('a sales representative', "a company that sells another company's products in a market"),
             ('to allow someone to', 'to make something possible for someone'),
             ('to be organized into', 'to be divided into areas or departments'),
             ('to oversee', 'to be responsible for an area and its results'),
             ('an external audit', "an independent check of the company's accounts"),
             ('a milestone', 'an important moment in the history of a company')],
   'nota': {'pq': 'S&atilde;o as palavras que sustentam &ldquo;a empresa &eacute; organizada&rdquo;, que &eacute; a impress&atilde;o que a aula 2 tem de deixar.',
            'duvida': '<em>Representative</em> em ingl&ecirc;s tamb&eacute;m nomeia a PESSOA. Aqui &eacute; a EMPRESA que representa a marca.',
            'recon': '<em>governance</em> e <em>board</em> aparecem no texto e n&atilde;o se cobram em produ&ccedil;&atilde;o.',
            'inclass': 'A etapa 4 pega estas seis e as coloca nas cinco linhas.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the sentences about your company. Use one word in each gap.',
   'banco': ['distributor', 'representative', 'allowed', 'organized', 'oversee'],
   'itens': [('We started as a ', 'distributor', ' of Kodak film in 1988.'),
             ('In 1996, we became a sales ', 'representative', ' for GE Diagnostic Imaging.'),
             ('This ', 'allowed', ' us to represent other international brands.'),
             ('Today we are ', 'organized', ' into commercial, technical service and corporate areas.'),
             ('I ', 'oversee', ' Corporate Management.')],
   'nota': {'pq': 'As cinco frases s&atilde;o as cinco linhas da aula, j&aacute; nas palavras da empresa dela.',
            'inclass': 'A frase 3 &eacute; a articula&ccedil;&atilde;o: sem ela, os marcos viram lista.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('Imagem Healthcare Solutions started in 1988 as a distributor of Kodak film. In 1996, it became a sales '
             'representative for GE Diagnostic Imaging. This allowed the company to represent other international '
             'brands over the following years &mdash; Medtronic, Siemens, Guerbet and Dr&auml;ger among them.<br><br>'
             'In 2025 the company strengthened its governance, with an external audit and a board. In 2026 it expanded '
             'with Danaher and Leica, and started Carestream XR operations.<br><br>'
             'Today the company is organized into commercial, technical service and corporate areas, and has 146 '
             'employees. The CEO is Thomaz Rodrigues.'),
   'perguntas': [
     ('1. What changed in 1996?',
      [('The company started.', 0), ('The company became a representative for an international brand.', 1),
       ('The company opened a new office.', 0)],
      '1988 is when it started. 1996 is the step that made everything after it possible.'),
     ('2. What did representing GE allow the company to do?',
      [('To make its own equipment.', 0), ('To represent other international brands.', 1),
       ('To open a branch abroad.', 0)],
      'That is the link between the moments &mdash; and the sentence you will say: <em>this allowed us to&hellip;</em>'),
     ('3. How is the company organized today?',
      [('Into commercial, technical service and corporate areas.', 1),
       ('Into four product categories.', 0), ('Into one area per partner.', 0)],
      'The product categories are the portfolio, which is lesson 3. The areas are the organization.')],
   'nota': {'pq': 'Quatro marcos e uma organiza&ccedil;&atilde;o. A pergunta 2 treina justamente a articula&ccedil;&atilde;o entre dois marcos.',
            'fonte': '1988, 1996, as marcas, 2025 (governan&ccedil;a e conselho), 2026 (Danaher, Leica, Carestream XR), 146 employees e o CEO: ' + DECK,
            'inclass': 'A etapa 3 traz o mesmo texto como modelo, depois da produ&ccedil;&atilde;o dela.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines tell the story. Put them in order, from 1 to 5.',
   'linhas': [('We started as a distributor of Kodak film in 1988.', 1),
              ('In 1996, we became a sales representative for GE Diagnostic Imaging.', 2),
              ('This allowed us to represent other international brands.', 3),
              ('Today we are organized into commercial, technical service and corporate areas.', 4),
              ('I oversee Corporate Management.', 5)],
   'nota': {'alt': 'Come&ccedil;ar por hoje e voltar a 1988 tamb&eacute;m funciona na fala. Aqui conta como erro s&oacute; porque a atividade pede uma ordem.',
            'pq': 'A ordem &eacute; o mapa: onde come&ccedil;ou, o passo que mudou tudo, o que isso permitiu, como est&aacute; hoje, onde ela est&aacute;.',
            'inclass': 'Este &eacute; o mapa que fica na frente dela nas etapas 5 e 6.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each.',
   'perguntas': ['How did the company start?', 'How is it organized today, and what do you oversee?'],
   'modelo': ['We started as a distributor of Kodak film in 1988. In 1996 we became a sales representative for GE Diagnostic Imaging, and this allowed us to represent other international brands.',
              'Today we are organized into commercial, technical service and corporate areas, with 146 employees. I oversee Corporate Management.'],
   'nota': {'pq': 'Leia antes da aula: mostra se os quatro marcos j&aacute; t&ecirc;m ordem na cabe&ccedil;a dela.',
            'inclass': 'A etapa 3 pede exatamente isto em voz alta, sem modelo antes.'}},
 ]}

PRE[3] = {'intro': ('Six short activities, about 15&ndash;20 minutes. They prepare the words for the portfolio. '
                    'Nothing here is a test, and you do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'The president of Carestream knows imaging better than anyone in the room. Choose the best answer.',
   'q': 'What does he most want to place?',
   'ops': [('Every product in the catalogue.', 0),
           ('Where his own products sit inside what you carry.', 1),
           ('The price of each category.', 0),
           ('The name of every supplier.', 0)],
   'rat': 'He is placing himself in your portfolio. The four categories do that; a product list does not.',
   'nota': {'pq': 'A forma antes do detalhe. Quem lista produtos perde o ouvinte no quinto nome.',
            'inclass': 'A etapa 1 abre com a mesma pergunta.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each expression with its meaning.',
   'pares': [('a portfolio', 'everything a company sells, grouped'),
             ('to cover', 'to include, as a range'),
             ('a solution', 'a product or system, seen from what it does'),
             ('to be used for', 'to have a purpose or an application'),
             ('diagnostic imaging', 'equipment that produces images for diagnosis'),
             ('a category', 'a group of products of the same kind')],
   'nota': {'pq': 'S&atilde;o as palavras que permitem falar por CATEGORIA em vez de por produto.',
            'recon': '<em>bone densitometry</em>, <em>surgical staplers</em> e <em>cardiac rhythm</em> aparecem como exemplos e n&atilde;o se cobram em produ&ccedil;&atilde;o.',
            'inclass': 'A etapa 4 pega estas seis e as coloca nas cinco linhas.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the sentences about your company. Use one word in each gap.',
   'banco': ['covers', 'imaging', 'used', 'represent', 'detail'],
   'itens': [('Our portfolio ', 'covers', ' four main areas.'),
             ('Diagnostic ', 'imaging', ' &mdash; for example, X-ray and ultrasound.'),
             ('This solution is ', 'used', ' for diagnosis in hospitals and clinics.'),
             ('We ', 'represent', ' international brands, including Carestream.'),
             ('Our technical team can provide more ', 'detail', '.')],
   'nota': {'pq': 'As cinco linhas da aula, j&aacute; nas palavras da empresa dela.',
            'inclass': 'A frase 5 &eacute; a que a protege quando a pergunta de produto vai mais fundo que a &aacute;rea dela.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('The portfolio covers four main areas. <strong>Diagnostic imaging</strong> includes X-ray, ultrasound and '
             'bone densitometry. <strong>Advanced surgical technology</strong> includes surgical staplers and instruments. '
             '<strong>Hospital care</strong> includes monitoring and anaesthesia. <strong>Cardiology and cardiac rhythm</strong> '
             'includes pacemakers.<br><br>'
             'The company represents international brands &mdash; Medtronic, Carestream, GE, Guerbet and others. In 2026 it '
             'expanded with Danaher and Leica, and started Carestream XR operations.<br><br>'
             'The share of the business held by each partner is confidential and is not in this deck.'),
   'perguntas': [
     ('1. How many main areas does the portfolio cover?',
      [('Four.', 1), ('Six.', 0), ('One for each brand.', 0)],
      'Four categories. Every product sits in one of them &mdash; that is why the shape comes before any product name.'),
     ('2. Which of these is a business model, not a product category?',
      [('Hospital care.', 0), ('To represent an international brand.', 1), ('Cardiology.', 0)],
      'The categories say WHAT is sold. Representing says HOW.'),
     ('3. The visitor asks which partner is the biggest. What is true?',
      [('The deck gives the share of each partner.', 0),
       ('The share is confidential and is not in the deck.', 1),
       ('All partners are the same size.', 0)],
      'It is confidential and belongs to lesson 5, where it is authorised for this meeting only.')],
   'nota': {'pq': 'A pergunta 3 planta a recusa antes de ela precisar dela na aula.',
            'fonte': 'As quatro categorias e os exemplos: ' + SITE + ' As marcas, a expans&atilde;o de 2026 e o in&iacute;cio das opera&ccedil;&otilde;es Carestream XR: ' + DECK,
            'inclass': 'A etapa 4 traz a mesma recusa como linha de apoio.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines present the portfolio. Put them in order, from 1 to 5.',
   'linhas': [('Our portfolio covers four main areas.', 1),
              ('Diagnostic imaging &mdash; for example, X-ray and ultrasound.', 2),
              ('This solution is used for diagnosis in hospitals and clinics.', 3),
              ('We represent international brands, including Carestream.', 4),
              ('Our technical team can provide more detail.', 5)],
   'nota': {'pq': 'Categoria, exemplo, para que serve, quem s&atilde;o as marcas, onde mora o detalhe.',
            'inclass': 'Este &eacute; o mapa que fica na frente dela nas etapas 5 e 6.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each.',
   'perguntas': ['What does your portfolio cover?', 'The visitor asks which partner is the biggest. What do you say?'],
   'modelo': ['Our portfolio covers four main areas: diagnostic imaging, advanced surgical technology, hospital care, and cardiology. In imaging, for example, X-ray and ultrasound.',
              'I would need to confirm that &mdash; our commercial team can give you more detail.'],
   'nota': {'pq': 'A segunda pergunta &eacute; a recusa por escrito, antes de ela ter de dizer isso na cara do parceiro.',
            'inclass': 'A etapa 6 traz exatamente esta pergunta no fim da produ&ccedil;&atilde;o.'}},
 ]}

PRE[4] = {'intro': ('Six short activities, about 15&ndash;20 minutes. They prepare the words for coverage and service. '
                    'Nothing here is a test, and you do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'The visitor asks where the company operates. Choose the best answer.',
   'q': 'What is he really asking?',
   'ops': [('For a map of the offices.', 0),
           ('Whether you can support what you sell, wherever his customers are.', 1),
           ('For the address of the head office.', 0),
           ('How many people work in logistics.', 0)],
   'rat': 'Behind the coverage question there is a support question. Coverage and service are one answer, not two lists.',
   'nota': {'pq': 'Inverte a ordem intuitiva: primeiro quem sustenta, depois onde estamos.',
            'duvida': 'Ela tende a come&ccedil;ar pela geografia, porque &eacute; o que o slide mostra. A ordem do slide n&atilde;o &eacute; a ordem da resposta.',
            'inclass': 'A etapa 3 pergunta exatamente qual metade ele quer primeiro.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each expression with its meaning.',
   'pares': [('headquarters', 'the main office of the company'),
             ('a distribution centre', 'where products are stored and shipped from'),
             ('a branch', 'a smaller office of the same company, in another place'),
             ('in-house', 'done by the company itself, not by another company'),
             ('applications support', 'people who train and help the customer use the equipment'),
             ('maintenance', 'keeping equipment working after it is installed')],
   'nota': {'pq': '<em>In-house</em> &eacute; a palavra comercial da aula: pr&oacute;prio, n&atilde;o terceirizado.',
            'duvida': 'Ela pode ler <em>own</em> como posse. Aqui o sentido &eacute; organizacional.',
            'recon': '<em>response time</em> aparece nas perguntas e n&atilde;o se cobra em produ&ccedil;&atilde;o &mdash; o dado n&atilde;o existe no deck.',
            'inclass': 'A etapa 4 pega estas seis e as coloca nas cinco linhas.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the sentences about your company. Use one word in each gap.',
   'banco': ['headquarters', 'directly', 'includes', 'in-house', 'confirm'],
   'itens': [('Our ', 'headquarters', ' is in S&atilde;o Paulo.'),
             ('We operate ', 'directly', ' in several states.'),
             ('Our service team ', 'includes', ' technicians, coordinators and applications support.'),
             ('The team is ', 'in-house', ', not outsourced.'),
             ('I would need to ', 'confirm', ' that detail.')],
   'nota': {'pq': 'As cinco linhas da aula. A quarta &eacute; o benef&iacute;cio operacional; a quinta &eacute; o que a protege.',
            'inclass': 'A etapa 4 inteira, e a etapa 6.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('The headquarters and the distribution centre are in S&atilde;o Paulo. The company operates directly in '
             'several states, with a branch in Mato Grosso do Sul and teams in Rio de Janeiro, Esp&iacute;rito Santo and '
             'Mato Grosso. A logistics branch in Santa Catarina handles imports.<br><br>'
             'The service team is <strong>in-house</strong>: technicians, coordinators and applications support. The '
             'company installs the equipment, trains the customer&rsquo;s people, and maintains what it sells.<br><br>'
             'Response times are not given in this deck.'),
   'perguntas': [
     ('1. Where does the company operate?',
      [('In one city only.', 0), ('Directly in several states, with logistics for imports in Santa Catarina.', 1),
       ('In every state of Brazil, with an office in each.', 0)],
      'Directly in several states. Saying <em>an office everywhere</em> promises more than the deck supports.'),
     ('2. What does <em>in-house</em> mean here?',
      [('The service is done by another company.', 0), ('The service team belongs to the company.', 1),
       ('The service is done at the customer&rsquo;s house.', 0)],
      'It is the operational benefit: the company installs, trains and maintains with its own people.'),
     ('3. The visitor asks how fast you respond to a service call. What is true?',
      [('The deck gives a response time.', 0), ('The response time is not in the deck.', 1),
       ('The answer is 24 hours.', 0)],
      'Not in the deck. The right answer is to confirm later &mdash; never to improvise an SLA.')],
   'nota': {'pq': 'Duas armadilhas de propor&ccedil;&atilde;o e uma de dado inexistente. A terceira &eacute; a mais prov&aacute;vel na reuni&atilde;o.',
            'fonte': 'Sede e centro de distribui&ccedil;&atilde;o, filiais, equipes por estado, log&iacute;stica em Santa Catarina e a equipe de servi&ccedil;o pr&oacute;pria: ' + DECK + ' Tempo de resposta n&atilde;o consta em fonte alguma.',
            'inclass': 'A etapa 2 traz o mesmo risco na tabela.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines answer the coverage question. Put them in order, from 1 to 5.',
   'linhas': [('Our headquarters is in S&atilde;o Paulo.', 1),
              ('We operate directly in several states.', 2),
              ('Our service team includes technicians, coordinators and applications support.', 3),
              ('The team is in-house, not outsourced.', 4),
              ('I would need to confirm that detail.', 5)],
   'nota': {'alt': 'Come&ccedil;ar pelo servi&ccedil;o (3 e 4) e depois dizer onde a empresa est&aacute; tamb&eacute;m funciona &mdash; e &eacute; o que o retask da aula pede.',
            'pq': 'Onde, alcance, o que a equipe &eacute;, por que isso importa, e o que se confirma depois.',
            'inclass': 'Este &eacute; o mapa que fica na frente dela nas etapas 5 e 6.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each.',
   'perguntas': ['Where does the company operate?', 'Who installs and maintains the equipment?'],
   'modelo': ['Our headquarters and distribution centre are in S&atilde;o Paulo, and we operate directly in several states. Imports come through our logistics branch in Santa Catarina.',
              'Our service team is in-house: technicians, coordinators and applications support. We install the equipment, we train your people, and we maintain it.'],
   'nota': {'pq': 'A segunda resposta &eacute; o argumento comercial da aula. Leia antes: se sair fraca no papel, sair&aacute; fraca na sala.',
            'inclass': 'A etapa 6 pergunta exatamente isso.'}},
 ]}

PRE[5] = {'intro': ('Six short activities, about 15&ndash;20 minutes. They prepare the words for the numbers &mdash; '
                    'and for the figure you will not give. You do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'The results slide is on the screen and the visitor is already reading it. Choose the best answer.',
   'q': 'What should your sentence do?',
   'ops': [('Read the numbers out loud, in order.', 0),
           ('Say what the numbers mean, in one sentence.', 1),
           ('Explain how the numbers were calculated.', 0),
           ('Compare with the competition.', 0)],
   'rat': 'He can already read the chart. One message per chart is what he cannot get from the slide.',
   'nota': {'pq': 'Separa LER de RESUMIR &mdash; a decis&atilde;o central da aula 5.',
            'duvida': 'Ler parece seguro porque o n&uacute;mero est&aacute; l&aacute;. &Eacute; o que faz ele parar de ouvir.',
            'inclass': 'A etapa 3 compara &ldquo;about twenty per cent&rdquo; com &ldquo;105.6&rdquo;.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each expression with its meaning.',
   'pares': [('net income', 'what the company keeps after all costs and taxes'),
             ('to increase from&hellip; to&hellip;', 'to go up from one figure to another'),
             ('to account for', 'to represent a share of a total'),
             ('partner mix', 'how the business is divided between the brands you represent'),
             ('an opportunity', 'something that may happen, and has not been decided'),
             ('a commitment', 'something you promise to do')],
   'nota': {'pq': 'As duas &uacute;ltimas s&atilde;o as perigosas: uma ela n&atilde;o pode assumir, a outra ela n&atilde;o tem.',
            'duvida': '<em>Recurring revenue</em> soa como algo que qualquer diretora saberia. N&atilde;o foi fornecido &mdash; e por isso a resposta &eacute; encaminhar, n&atilde;o lembrar.',
            'recon': '<em>gross margin</em> e <em>commissions</em> podem aparecer na conversa e n&atilde;o est&atilde;o autorizados.',
            'inclass': 'A etapa 4 pega estas seis e as coloca nas cinco linhas.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the sentences about your company. Use one word in each gap.',
   'banco': ['increased', 'about', 'accounts', 'opportunity', 'confirm'],
   'itens': [('Net income ', 'increased', ' from 87.7 to 105.6 million reais.'),
             ('That is ', 'about', ' twenty per cent.'),
             ('Carestream ', 'accounts', ' for thirty-eight per cent of our partner mix.'),
             ('One ', 'opportunity', ' is the Midea portfolio in Brazil.'),
             ('I would need to ', 'confirm', ' that figure.')],
   'nota': {'pq': 'As cinco linhas da aula: o n&uacute;mero, a mensagem, a participa&ccedil;&atilde;o, a possibilidade e a recusa.',
            'inclass': 'A etapa 4 inteira.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('Net income increased from 87.7 million reais in 2024 to 105.6 million in 2025 &mdash; about twenty per cent. '
             'In the first two months of 2026 the company is ahead of the same period last year: 17.85 against 12.52.<br><br>'
             'Carestream accounts for thirty-eight per cent of the partner mix in 2026, against eighteen per cent in 2024.<br><br>'
             'Two opportunities are open: the Midea portfolio in Brazil, and an expansion with Danaher and Leica in the '
             'interior of S&atilde;o Paulo. Neither is a commitment. Recurring revenue and commissions are not in this deck.'),
   'perguntas': [
     ('1. What is the message of the first chart?',
      [('The company grew about twenty per cent last year.', 1),
       ('The company earned 105.6 million reais.', 0),
       ('The company earned more in 2025 than in 2024, in every month.', 0)],
      'B is the figure, not the message. C says more than the text supports.'),
     ('2. What does the partner mix say to the visitor?',
      [('That his company is a small part of the business.', 0),
       ('That his company grew from eighteen to thirty-eight per cent of the mix.', 1),
       ('That the company sells only Carestream.', 0)],
      'It is his own company, in your numbers &mdash; and it is authorised for this meeting.'),
     ('3. He asks for the recurring revenue. What is true?',
      [('It is in the deck, under another name.', 0),
       ('It was never given to you, and you confirm it later.', 1),
       ('You can estimate it from the other figures.', 0)],
      'Not a memory problem: the figure does not exist for you. Estimating it in front of the CEO is the risk.')],
   'nota': {'pq': 'Uma leitura, tr&ecirc;s opera&ccedil;&otilde;es: mensagem, leitura para o interlocutor e limite do dado.',
            'duvida': 'Confidencialidade: receita, lucro e participa&ccedil;&atilde;o por parceiro est&atilde;o autorizados PARA ESTA REUNI&Atilde;O. Confirme antes da aula.',
            'fonte': 'Lucro l&iacute;quido 87,74 &rarr; 105,63 (R$ mi), 12,52 &rarr; 17,85 nos dois primeiros meses, mix Carestream 18% &rarr; 38%, Midea, Danaher e Leica: ' + DECK + ' Receita recorrente e comiss&otilde;es n&atilde;o constam.',
            'inclass': 'A etapa 4 traz a recusa como linha de apoio.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines carry the results. Put them in order, from 1 to 5.',
   'linhas': [('Net income increased from 87.7 to 105.6 million reais.', 1),
              ('That is about twenty per cent.', 2),
              ('Carestream accounts for thirty-eight per cent of our partner mix.', 3),
              ('One opportunity is the Midea portfolio in Brazil.', 4),
              ('I would need to confirm that figure.', 5)],
   'nota': {'pq': 'N&uacute;mero, mensagem, o que isso significa para ele, o que pode vir, e o limite.',
            'inclass': 'Este &eacute; o mapa que fica na frente dela nas etapas 5 e 6.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each.',
   'perguntas': ['How did last year go?', 'He asks what your recurring revenue is. What do you say?'],
   'modelo': ['Net income increased from 87.7 to 105.6 million reais &mdash; about twenty per cent. The first two months of this year are ahead of the same period last year.',
              'I would need to confirm that figure &mdash; it is not in the material I have here.'],
   'nota': {'pq': 'A segunda &eacute; a recusa por escrito. Escrita antes, ela sai mais calma na sala.',
            'inclass': 'A etapa 6 traz exatamente esta pergunta no meio da produ&ccedil;&atilde;o.'}},
 ]}

PRE[6] = {'intro': ('Six short activities, about 15&ndash;20 minutes. Nothing new here &mdash; they put the five blocks '
                    'back together before the simulation. You do not need to record anything.'),
 'ex': [
  {'k': 'quiz', 't': 'Contextualizar',
   'instr': 'Monday is the meeting. Today is the last run. Choose the best answer.',
   'q': 'What is the aim of this lesson?',
   'ops': [('To learn the last part of the deck.', 0),
           ('To run the whole meeting once, with interruptions.', 1),
           ('To memorise the presentation.', 0),
           ('To correct every mistake from the other lessons.', 0)],
   'rat': 'Nothing new enters today. What is not ready by now is handled with the repair moves, not with new content.',
   'nota': {'pq': 'Fecha a expectativa: simula&ccedil;&atilde;o, n&atilde;o conte&uacute;do novo, n&atilde;o mem&oacute;ria.',
            'inclass': 'A etapa 1 abre com a mesma frase.'}},
  {'k': 'match', 't': 'Preparar l&eacute;xico',
   'instr': 'Match each move with the moment you use it.',
   'pares': [('Could you repeat that?', 'he spoke too fast, or asked two things at once'),
             ('If I understood correctly, you are asking about&hellip;', 'you want to check before you answer'),
             ('Let me check the slide.', 'the number is on the screen and you want it exact'),
             ('[Name] can provide more detail.', 'the question belongs to another area'),
             ('I would need to confirm that.', 'the figure is not in the deck'),
             ('Let me come back to that.', 'you were interrupted and want to finish the block')],
   'nota': {'pq': 'S&atilde;o os seis movimentos de repara&ccedil;&atilde;o do intensivo inteiro, reunidos.',
            'inclass': 'A etapa 4 traz os quatro principais como linhas de apoio.'}},
  {'k': 'gap', 't': 'Reutilizar l&eacute;xico',
   'instr': 'Complete the opening line of each block. Use one word in each gap.',
   'banco': ['overview', 'distributor', 'covers', 'headquarters', 'increased'],
   'itens': [('Let me give you a short ', 'overview', ' of the company.'),
             ('We started as a ', 'distributor', ' of Kodak film in 1988.'),
             ('Our portfolio ', 'covers', ' four main areas.'),
             ('Our ', 'headquarters', ' is in S&atilde;o Paulo, and our service team is in-house.'),
             ('Net income ', 'increased', ' from 87.7 to 105.6 million reais.')],
   'nota': {'pq': 'Uma linha de entrada por bloco. Com ela, o bloco come&ccedil;a mesmo se o resto vier devagar.',
            'inclass': 'A etapa 4 as re&uacute;ne como o mapa da reuni&atilde;o inteira.'}},
  {'k': 'leitura', 't': 'Processar input &mdash; <em>input principal</em>',
   'instr': 'Read the text once. Then answer the three questions.',
   'texto': ('A visit does not always run to plan. If the president has ten minutes instead of thirty, the meeting still '
             'has to place the company, say what it sells, and show that it can support what it sells.<br><br>'
             'One sentence per block does that. The blocks are: the company and your role; the story and the '
             'organization; the portfolio and the partners; coverage and service; results and what is ahead.<br><br>'
             'Anything outside those five &mdash; price, contract terms, commissions &mdash; belongs to someone else in the room.'),
   'perguntas': [
     ('1. If you only have ten minutes, what do you do?',
      [('Speak faster and keep all the detail.', 0), ('Give one sentence per block, and stop.', 1),
       ('Cut the last two blocks completely.', 0)],
      'The shape survives; the detail is what you drop. That is why each block has one opening line.'),
     ('2. He asks about contract terms. What do you do?',
      [('Answer with what you remember.', 0), ('Pass it to the person responsible.', 1),
       ('Say the company does not discuss that.', 0)],
      'It is not your area, and passing it on is what a director does in a real meeting.'),
     ('3. He interrupts in the middle of a block. What keeps the meeting on track?',
      [('Starting the block again from the top.', 0),
       ('Answering shortly and coming back to where you were.', 1),
       ('Finishing the block and answering at the end.', 0)],
      'Answer, then <em>let me come back to that</em>. The block continues from where it stopped.')],
   'nota': {'pq': 'Prepara a vers&atilde;o de dez minutos e as duas interrup&ccedil;&otilde;es da etapa 6.',
            'fonte': 'Os cinco blocos s&atilde;o os das aulas 1 a 5 deste intensivo. Nada novo entra aqui.',
            'inclass': 'A etapa 5 pede exatamente a vers&atilde;o curta.'}},
  {'k': 'ord', 't': 'Notar e organizar linguagem',
   'instr': 'These five lines open the five blocks of the meeting. Put them in order, from 1 to 5.',
   'linhas': [('Let me give you a short overview of the company.', 1),
              ('We started as a distributor of Kodak film in 1988.', 2),
              ('Our portfolio covers four main areas.', 3),
              ('Our headquarters is in S&atilde;o Paulo, and our service team is in-house.', 4),
              ('Net income increased from 87.7 to 105.6 million reais.', 5)],
   'nota': {'pq': 'A ordem dos blocos &eacute; a ordem da reuni&atilde;o. &Eacute; o &uacute;nico mapa que ela leva inteiro para segunda.',
            'inclass': 'Este &eacute; o mapa da etapa 6 &mdash; a reuni&atilde;o completa.'}},
  {'k': 'escrita', 't': 'Aplicar brevemente',
   'instr': 'Write two short answers. One or two sentences each.',
   'perguntas': ['Which part of the meeting still worries you?', 'He asks who decides on new partnerships. What do you say?'],
   'modelo': ['The results block &mdash; I am not sure what I can say about the partner share.',
              'Thomaz decides on new partnerships &mdash; he can give you more detail on that.'],
   'nota': {'pq': 'A primeira resposta define por onde a aula come&ccedil;a. Leia antes de abrir a aula.',
            'inclass': 'A etapa 1 pergunta exatamente isso, e a etapa 5 trabalha o bloco que ela nomear.'}},
 ]}
