# -*- coding: utf-8 -*-
"""Pre-class das seis aulas.

Cada bloco tem cinco atividades e leva 15-20 minutos. A aula funciona sem ele: o pre-class
PREPARA o vocabulario e a leitura do contexto, nao adianta a producao -- a primeira versao
oral acontece na etapa 3, na aula, sem modelo antes.

'nota' e o gabarito do PROFESSOR (em portugues, invisivel para a aluna): por que a resposta
e essa, o que costuma gerar duvida e onde aquilo reaparece no in-class. As respostas em si
o akBuild() extrai do proprio exercicio -- nao se escrevem duas vezes.
"""

PRE = {}

PRE[1] = {'intro': 'About 15&ndash;20 minutes. Five short activities. You do not need to finish them before the lesson &mdash; the lesson works either way.',
 'ex': [
  {'k': 'quiz', 't': 'Who is coming', 'instr': 'Read the note and answer.',
   'doc': ('VISIT &mdash; 31 AUGUST', ['<strong>Visitor:</strong> President of Carestream, from the United States',
                                       '<strong>Where:</strong> Head office, S&atilde;o Paulo',
                                       '<strong>Opening the meeting:</strong> Rita Rodrigues, Corporate Management Director',
                                       '<strong>Also in the room:</strong> Thomaz Rodrigues, CEO']),
   'q': 'What does he most need in your first minute?',
   'ops': [('The full history of the company, year by year.', 0),
           ('Who you are, what the company does, and why he is in the right place.', 1),
           ('The financial results for 2025.', 0)],
   'rat': '<strong>B.</strong> The first minute places the visitor. History comes in lesson 2 and the numbers in lesson 5.',
   'nota': {'alt': 'Quem responde <em>b</em> e acrescenta &ldquo;e o que a minha area faz&rdquo; esta certa &mdash; e exatamente o objetivo da aula.',
            'pq': 'O primeiro minuto SITUA. Historia e numeros tem aula propria; antecipa-los aqui e o erro mais comum de abertura.',
            'duvida': 'A op&ccedil;&atilde;o <em>a</em> atrai porque hist&oacute;ria parece o come&ccedil;o natural. &Eacute; o come&ccedil;o da EMPRESA, n&atilde;o o da reuni&atilde;o.',
            'inclass': 'Etapa 1: a pergunta &ldquo;o que ele precisa saber ao fim de hoje?&rdquo; e a mesma, agora em voz alta.'}},
  {'k': 'match', 't': 'Six words you will use', 'instr': 'Match each word to what it means.',
   'pares': [('distribute', 'to bring a product from the maker to hospitals and clinics'),
             ('medical technology', 'the equipment hospitals use to diagnose and treat'),
             ('nationwide', 'in the whole country'),
             ('corporate management', 'IT, HR, quality, controlling and business processes &mdash; your area'),
             ('business processes', 'how the company organises its work'),
             ('to represent a brand', 'to sell another company&rsquo;s products, without making them')],
   'nota': {'pq': 'S&atilde;o as seis palavras produtivas da aula 1. Ela vai DIZER as seis na etapa 4.',
            'duvida': '<em>Distribute</em> x <em>produce</em>: a empresa n&atilde;o fabrica. Se ela trocar, corrija aqui &mdash; na reuni&atilde;o esse erro muda o que a empresa &eacute;.',
            'inclass': 'As seis voltam nas cinco linhas da etapa 4.'}},
  {'k': 'gap', 't': 'Put each word in the right place', 'instr': 'Complete with one word from Activity 2.',
   'itens': [('We ', 'distribute', ' medical technology to hospitals and clinics.'),
             ('We have teams in several states. We work ', 'nationwide', '.'),
             ('IT, HR and quality are part of ', 'corporate management', '.'),
             ('We do not make the equipment &mdash; we ', 'represent', ' international brands.')],
   'nota': {'pq': 'Recupera&ccedil;&atilde;o lexical com as candidatas j&aacute; vistas na atividade 2.',
            'duvida': 'Na 4, <em>represent</em> sozinho basta; se ela escrever <em>represent brands</em>, aceite oralmente e mostre a lacuna.',
            'inclass': 'Etapa 4, linha 3 e linha 5.'}},
  {'k': 'leitura', 't': 'Read and find the answer', 'instr': 'One short text about your own company. Read it once.',
   'texto': ('Imagem Healthcare Solutions has worked in the healthcare market for 38 years. The company '
             'started in 1988. Today it distributes medical technology to hospitals, clinics and specialised '
             'centres in Brazil, represents international brands, and provides installation, training and '
             'maintenance. The company has 146 employees.'),
   'q': 'Which sentence is true?',
   'ops': [('The company produces medical equipment in Brazil.', 0),
           ('The company started in 1996.', 0),
           ('The company distributes medical technology and also provides services.', 1)],
   'rat': '<strong>C.</strong> The text says <em>distributes</em> and <em>provides installation, training and maintenance</em> &mdash; two things, not one.',
   'nota': {'pq': 'A leitura confirma o par distribuir/prestar servi&ccedil;o, que &eacute; a resposta da aula 4 j&aacute; plantada aqui.',
            'duvida': '1996 aparece no texto? N&atilde;o &mdash; e &eacute; justamente a data da GE, que ela sabe de cor. Ver a data certa (1988) escrita ajuda.',
            'inclass': 'Etapa 3: a frase &ldquo;we distribute medical technology&rdquo; vem do modelo.'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Two ways of saying the same thing. Choose the one that works in the meeting.',
   'linhas': [('He asks something that belongs to another area.', 'b', 'I do not know.', 'Thomaz can give you more detail on that.'),
              ('A word goes past you and you lose the sentence.', 'a', 'Sorry, could you say that again?', 'Sorry, my English is very bad.'),
              ('He asks for a number you do not have.', 'b', 'I think it is around thirty.', 'I would need to confirm that detail.')],
   'nota': {'pq': 'As tr&ecirc;s linhas de reparo da aula 1. A escolha errada n&atilde;o &eacute; gramatical: &eacute; de POSTURA.',
            'duvida': 'Pedir desculpa pelo pr&oacute;prio ingl&ecirc;s parece educado e custa autoridade. Vale dizer isso a ela em voz alta.',
            'inclass': 'Etapa 4, tela &ldquo;When you do not have it&rdquo;.'}},
 ]}

PRE[2] = {'intro': 'About 15&ndash;20 minutes. Five short activities, all about the company&rsquo;s history and how it is organised today.',
 'ex': [
  {'k': 'multi', 't': 'Four moments, not thirteen', 'instr': 'Mark the <strong>four</strong> moments a visitor can follow in thirty seconds.',
   'doc': ('COMPANY TIMELINE &mdash; from the deck', ['1988 &middot; the company starts, distributing Kodak film',
        '1996 &middot; becomes a sales representative for GE Diagnostic Imaging',
        '2016&ndash;2021 &middot; adds Medtronic, Siemens, Guerbet and Dr&auml;ger',
        '2025 &middot; governance strengthened: external audit and a board',
        '2026 &middot; expands with Danaher and Leica; Carestream XR operations start']),
   'ops': [('1988 &mdash; where it started', 1), ('1996 &mdash; the first brand represented', 1),
           ('Every year between 2016 and 2021, one by one', 0), ('From 2016 &mdash; the portfolio widens', 1),
           ('2026 &mdash; Carestream XR operations', 1), ('The exact month of each contract', 0)],
   'rat': 'Four moments carry 38 years: where it started, the first brand, the portfolio widening, and today.',
   'nota': {'pq': 'O risco desta aula &eacute; COMPRIMENTO. Quatro momentos e uma forma; treze datas e uma lista.',
            'duvida': 'Ela pode querer incluir 2025 (governan&ccedil;a). N&atilde;o est&aacute; errado &mdash; s&oacute; n&atilde;o cabe nos quatro. Fica como linha de apoio.',
            'inclass': 'Etapa 3: o modelo tem exatamente estes quatro.'}},
  {'k': 'match', 't': 'Words for a company history', 'instr': 'Match each word to what it means.',
   'pares': [('a sales representative', 'a company that sells another company&rsquo;s products in a market'),
             ('to expand', 'to grow into new products, brands or regions'),
             ('governance', 'the rules and controls that say how a company is run'),
             ('external audit', 'an independent check of the company&rsquo;s accounts'),
             ('a board', 'the group that oversees the company above the CEO'),
             ('a business unit', 'a part of the company with its own director and results')],
   'nota': {'pq': 'S&atilde;o as palavras que sustentam &ldquo;a empresa &eacute; organizada&rdquo; &mdash; a impress&atilde;o que a aula 2 tem de deixar.',
            'duvida': '<em>Representative</em> em ingl&ecirc;s tamb&eacute;m &eacute; pessoa. Aqui &eacute; a EMPRESA que representa a marca.',
            'inclass': 'Etapa 4: a glosa da linha 2 diz exatamente isto.'}},
  {'k': 'gap', 't': 'Say it in one line', 'instr': 'Complete with one word from Activity 2.',
   'itens': [('In 1996 we became a sales ', 'representative', ' for GE Diagnostic Imaging.'),
             ('In 2025 we strengthened our ', 'governance', ', with an external audit and a board.'),
             ('From 2016 we started to ', 'expand', ' the portfolio with new brands.')],
   'nota': {'pq': 'Tr&ecirc;s lacunas, tr&ecirc;s linhas que ela vai dizer na etapa 4.',
            'inclass': 'Etapa 4, linhas 2 e 4.'}},
  {'k': 'leitura', 't': 'Where you sit', 'instr': 'Read your own area, written as a visitor would read it.',
   'texto': ('Corporate Management brings together IT, HR, quality, corporate controlling and business '
             'processes. The team has nine people and reports to the CEO, Thomaz Rodrigues. Service, with '
             'its own technicians and coordinators, is a separate area with its own director.'),
   'q': 'A visitor asks how many people work in service. What is true?',
   'ops': [('It is in your area, so you give the number.', 0),
           ('It is a separate area &mdash; you can forward the question.', 1),
           ('You should estimate the number.', 0)],
   'rat': '<strong>B.</strong> Nine people is your number. Service is a different area, with its own director.',
   'nota': {'pq': 'Separa o que ela POSSUI do que ela ENCAMINHA. &Eacute; o crit&eacute;rio de precis&atilde;o do dado.',
            'duvida': 'Ela conhece o n&uacute;mero da &aacute;rea de servi&ccedil;o (trinta t&eacute;cnicos, aula 4). Saber n&atilde;o &eacute; o mesmo que ser dela &mdash; na aula 4 ele volta como n&uacute;mero autorizado.',
            'inclass': 'Etapa 4: &ldquo;Service is a different area, with its own director.&rdquo;'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Choose the version that works with a visitor.',
   'linhas': [('He asks how the company started.', 'b', 'It is a long story, since 1988, many things happened.', 'We started in 1988, distributing Kodak film.'),
              ('He asks what a sales representative does.', 'a', 'We sell for them &mdash; we do not make it.', 'We are partners of them.'),
              ('He asks who runs the service team.', 'b', 'I am not sure, someone else.', 'Service is a different area, with its own director.')],
   'nota': {'pq': 'Mesma informa&ccedil;&atilde;o, duas formas: a que ele consegue repetir e a que ele n&atilde;o consegue.',
            'inclass': 'Etapa 7 do in-class, tabela &ldquo;What he hears&rdquo;.'}},
 ]}

PRE[3] = {'intro': 'About 15&ndash;20 minutes. Five short activities about the portfolio and the partners.',
 'ex': [
  {'k': 'multi', 't': 'Four categories', 'instr': 'Mark the <strong>four</strong> categories the company sells in.',
   'doc': ('PORTFOLIO &mdash; from the deck', ['Diagnostic imaging &middot; X-ray, ultrasound, bone densitometry',
        'Advanced surgical technology &middot; surgical staplers and instruments',
        'Hospital care &middot; monitoring, anaesthesia, infusion',
        'Cardiology and cardiac rhythm &middot; pacemakers and related devices']),
   'ops': [('Diagnostic imaging', 1), ('Advanced surgical technology', 1), ('Software licensing', 0),
           ('Hospital care', 1), ('Cardiology and cardiac rhythm', 1), ('Hospital construction', 0)],
   'rat': 'Four categories. Everything the company sells sits in one of them &mdash; that is why the shape comes before any product name.',
   'nota': {'pq': 'A forma antes do detalhe. Quem lista produtos perde o ouvinte no quinto nome.',
            'duvida': '<em>Software licensing</em> e <em>hospital construction</em> soam plaus&iacute;veis num distribuidor grande. N&atilde;o est&atilde;o no deck &mdash; e o que n&atilde;o est&aacute; no deck ela encaminha.',
            'inclass': 'Etapa 3: o modelo &eacute; exatamente categoria + um exemplo.'}},
  {'k': 'match', 't': 'One example each', 'instr': 'Match each category to one example from the deck.',
   'pares': [('Diagnostic imaging', 'X-ray and ultrasound'),
             ('Advanced surgical technology', 'surgical staplers'),
             ('Hospital care', 'monitoring and anaesthesia'),
             ('Cardiology and cardiac rhythm', 'pacemakers')],
   'nota': {'pq': 'Um exemplo por categoria &eacute; o suficiente para situar. O exemplo serve &agrave; categoria, nunca o contr&aacute;rio.',
            'inclass': 'Etapa 3 e etapa 4, linha 3.'}},
  {'k': 'gap', 't': 'The shape of the answer', 'instr': 'Complete with one word.',
   'itens': [('We work with four main ', 'areas', '.'),
             ('Our largest area is diagnostic ', 'imaging', '.'),
             ('We also ', 'represent', ' international brands.'),
             ('I would need to ', 'confirm', ' that detail.')],
   'nota': {'pq': 'As quatro linhas que sustentam a etapa 4 desta aula, incluindo a recusa.',
            'duvida': 'Na 2, <em>largest</em> &eacute; verdadeiro POR CATEGORIA. N&atilde;o &eacute; participa&ccedil;&atilde;o de parceiro &mdash; essa &eacute; confidencial e s&oacute; entra na aula 5.',
            'inclass': 'Etapa 4 inteira.'}},
  {'k': 'leitura', 't': 'The partners', 'instr': 'Read and answer.',
   'texto': ('The company represents international brands: Medtronic, Carestream, GE, Guerbet and others. '
             'In 2026 it expanded with Danaher and Leica, and started Carestream XR operations. The share '
             'of the business held by each partner is confidential and is not in this deck.'),
   'q': 'The visitor asks which partner is the biggest. What do you say?',
   'ops': [('Carestream, about thirty-eight per cent.', 0),
           ('I would need to confirm that detail.', 1),
           ('All of them are the same size.', 0)],
   'rat': '<strong>B.</strong> Partner share is confidential and belongs to lesson 5, where it is authorised for this meeting only.',
   'nota': {'pq': 'A recusa aqui &eacute; PROCEDIMENTO, n&atilde;o inseguran&ccedil;a. Ela sabe o n&uacute;mero &mdash; e ele n&atilde;o &eacute; para esta aula.',
            'duvida': 'Ela pode achar que est&aacute; escondendo algo do pr&oacute;prio parceiro. Explique: participa&ccedil;&atilde;o por parceiro s&oacute; entra na aula 5, com autoriza&ccedil;&atilde;o confirmada.',
            'inclass': 'Etapa 4, tabela &ldquo;What it protects&rdquo;.'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Choose the version a visitor can repeat.',
   'linhas': [('He asks what you sell.', 'b', 'X-ray, ultrasound, densitometry, staplers, monitors, pacemakers&hellip;', 'We work with four main areas. Diagnostic imaging, for example X-ray and ultrasound.'),
              ('He asks about a product you do not know in English.', 'a', 'That sits in our hospital care area.', 'I do not know this product.'),
              ('He asks if you carry his brand.', 'b', 'Yes, many brands.', 'We represent Carestream &mdash; this year we started Carestream XR operations.')],
   'nota': {'pq': 'A categoria responde mesmo quando o nome do produto n&atilde;o vem. &Eacute; a estrat&eacute;gia de continuidade desta aula.',
            'inclass': 'Etapa 4 e etapa 6.'}},
 ]}

PRE[4] = {'intro': 'About 15&ndash;20 minutes. Five short activities about where the company operates and who supports what it sells.',
 'ex': [
  {'k': 'multi', 't': 'Where the company is', 'instr': 'Mark the <strong>three</strong> statements the note supports.',
   'doc': ('COVERAGE &mdash; from the deck', ['Head office and distribution centre &middot; S&atilde;o Paulo',
        'Branch &middot; Mato Grosso do Sul', 'Teams &middot; Rio de Janeiro, Esp&iacute;rito Santo, Mato Grosso',
        'Logistics branch for imports &middot; Santa Catarina', 'Own service team &middot; 30 technicians, coordinators, applications support']),
   'ops': [('The company has teams in more than one state', 1), ('There is an office in every state', 0),
           ('Imports come through a logistics branch in Santa Catarina', 1),
           ('The service team is outsourced', 0), ('The service team belongs to the company', 1),
           ('Response time is 24 hours', 0)],
   'rat': 'Teams in several states, logistics through Santa Catarina, and an in-house service team. The deck does not give a response time.',
   'nota': {'pq': 'Duas armadilhas de propor&ccedil;&atilde;o (&ldquo;escrit&oacute;rio em todo estado&rdquo;) e uma de dado inexistente (SLA).',
            'duvida': 'O tempo de resposta &eacute; a pergunta mais prov&aacute;vel do visitante e a que n&atilde;o tem n&uacute;mero. Vale marcar isso agora.',
            'inclass': 'Etapa 2: o terceiro risco &eacute; exatamente esse.'}},
  {'k': 'match', 't': 'Words for an operation', 'instr': 'Match each word to what it means.',
   'pares': [('a distribution centre', 'where products are stored and shipped from'),
             ('a branch', 'a smaller office of the same company, in another place'),
             ('in-house', 'done by the company itself, not by another company'),
             ('applications support', 'people who train and help the customer use the equipment'),
             ('response time', 'how long it takes to attend a call for service'),
             ('maintenance', 'keeping equipment working after it is installed')],
   'nota': {'pq': '<em>In-house</em> e a palavra-chave comercial da aula: pr&oacute;prio, n&atilde;o terceirizado.',
            'duvida': 'Ela pode traduzir <em>own</em> como posse. Aqui o sentido &eacute; organizacional.',
            'inclass': 'Etapa 4: a glosa da linha 3.'}},
  {'k': 'gap', 't': 'One answer, two halves', 'instr': 'Complete with one word.',
   'itens': [('Our head office and ', 'distribution', ' centre are in S&atilde;o Paulo.'),
             ('We have a logistics ', 'branch', ' in Santa Catarina for imports.'),
             ('We have our own service ', 'team', ' &mdash; thirty technicians.'),
             ('I would need to confirm our response ', 'time', '.')],
   'nota': {'pq': 'A resposta &eacute; UMA, em duas metades: onde estamos e quem sustenta.',
            'inclass': 'Etapa 4 inteira, e a etapa 6.'}},
  {'k': 'leitura', 't': 'What he is really asking', 'instr': 'Read and answer.',
   'texto': ('A visitor from a manufacturer asks where you operate. He is not asking for a map: he is '
             'asking whether the equipment he sells through you will be installed, trained and maintained '
             'anywhere his customers are. Coverage and service are one answer.'),
   'q': 'Which answer does the visitor need first?',
   'ops': [('The list of states, in order.', 0),
           ('That you have your own service team.', 1),
           ('The address of the head office.', 0)],
   'rat': '<strong>B.</strong> Behind the coverage question there is a support question. The service team is the half that answers it.',
   'nota': {'pq': 'Inverte a ordem intuitiva: primeiro quem sustenta, depois onde estamos.',
            'duvida': 'Ela tende a come&ccedil;ar pela geografia, porque &eacute; o que o slide mostra. A ordem do slide n&atilde;o &eacute; a ordem da resposta.',
            'inclass': 'Etapa 3, pergunta do modelo; e o retask da etapa 8 pede service first.'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Choose the version that keeps you accurate.',
   'linhas': [('He asks how fast you respond.', 'b', 'About 24 hours, I believe.', 'I would need to confirm our response time.'),
              ('He asks who installs the equipment.', 'a', 'We have our own service team &mdash; thirty technicians.', 'We have partners who do that.'),
              ('He asks if you cover the whole country.', 'b', 'Yes, everywhere.', 'We have teams in several states, and logistics runs nationwide.')],
   'nota': {'pq': 'Duas recusas e uma afirma&ccedil;&atilde;o forte. A do meio &eacute; o benef&iacute;cio comercial da empresa &mdash; e ela &eacute; verdadeira.',
            'inclass': 'Etapa 4 e etapa 6.'}},
 ]}

PRE[5] = {'intro': 'About 15&ndash;20 minutes. Five short activities about the numbers &mdash; and about the one you will not give.',
 'ex': [
  {'k': 'quiz', 't': 'What a chart needs from you', 'instr': 'Read the note and answer.',
   'doc': ('RESULTS &mdash; from the deck', ['Net income &middot; 2024: R$ 87.74 m &nbsp;&rarr;&nbsp; 2025: R$ 105.63 m',
        'First two months &middot; 2025: 12.52 &nbsp;&rarr;&nbsp; 2026: 17.85',
        'Partner mix &middot; Carestream: 18% (2024) &nbsp;&rarr;&nbsp; 38% (2026)',
        'Not in the deck &middot; recurring revenue, commissions']),
   'q': 'He is looking at the chart while you speak. What should your sentence do?',
   'ops': [('Read the numbers out loud, in order.', 0),
           ('Say what the numbers mean, in one sentence.', 1),
           ('Explain how the numbers were calculated.', 0)],
   'rat': '<strong>B.</strong> He can already read the chart. One sentence per chart is what he cannot get from the slide.',
   'nota': {'pq': 'Separa LER de RESUMIR. &Eacute; a decis&atilde;o central da aula 5.',
            'duvida': 'Ela tende a ler porque o n&uacute;mero est&aacute; l&aacute; e parece seguro. Ler &eacute; o que faz ele parar de ouvir.',
            'inclass': 'Etapa 3: a pergunta do modelo compara &ldquo;about twenty per cent&rdquo; com &ldquo;105.63&rdquo;.'}},
  {'k': 'match', 't': 'Words for results', 'instr': 'Match each word to what it means.',
   'pares': [('net income', 'what the company keeps after all costs and taxes'),
             ('to grow by', 'to increase by an amount or a percentage'),
             ('the same period last year', 'the identical months of the previous year, for comparison'),
             ('partner mix', 'how the business is divided between the brands you represent'),
             ('recurring revenue', 'income that repeats every month or year'),
             ('a commitment', 'something you promise to do &mdash; not the same as a possibility')],
   'nota': {'pq': 'As duas &uacute;ltimas s&atilde;o as perigosas: uma ela n&atilde;o tem, a outra ela n&atilde;o pode assumir.',
            'duvida': '<em>Recurring revenue</em> soa como algo que qualquer diretor saberia. N&atilde;o foi fornecido &mdash; e por isso a resposta &eacute; encaminhar, n&atilde;o lembrar.',
            'inclass': 'Etapa 4, tabela &ldquo;Why&rdquo;.'}},
  {'k': 'gap', 't': 'One sentence per chart', 'instr': 'Complete with one word.',
   'itens': [('Net income ', 'grew', ' about twenty per cent last year.'),
             ('The first two months of this year are ', 'ahead', ' of the same period last year.'),
             ('Carestream has grown from eighteen to thirty-eight per cent of our partner ', 'mix', '.'),
             ('That is a possibility, not a ', 'commitment', '.')],
   'nota': {'pq': 'Tr&ecirc;s resumos e a linha que protege toda oportunidade.',
            'duvida': 'Em 1, <em>grew</em> (n&atilde;o <em>growed</em>). Se sair errado, corrija sem interromper o racioc&iacute;nio &mdash; a forma volta na etapa 4.',
            'inclass': 'Etapa 4, linhas 1 a 4.'}},
  {'k': 'leitura', 't': 'A possibility is not a promise', 'instr': 'Read and answer.',
   'texto': ('Two things are ahead: the company sees potential for the Midea portfolio in Brazil, and it '
             'is expanding with Danaher and Leica in the interior of S&atilde;o Paulo. The first has not been '
             'decided. The second is already happening in 2026.'),
   'q': 'Which sentence is safe to say to a visitor?',
   'ops': [('We will launch Midea in Brazil this year.', 0),
           ('We see potential for Midea in Brazil &mdash; that is a possibility, not a commitment.', 1),
           ('Midea is already part of our portfolio.', 0)],
   'rat': '<strong>B.</strong> Say the possibility as a possibility. In a room with the CEO, a promise you did not authorise is expensive.',
   'nota': {'pq': 'Distingue o que est&aacute; acontecendo (Danaher, Leica) do que est&aacute; sendo estudado (Midea).',
            'duvida': 'O futuro simples em ingl&ecirc;s (<em>we will launch</em>) soa a ela como plano, e chega ao visitante como compromisso.',
            'inclass': 'Etapa 4, tela &ldquo;Where it is going&rdquo;.'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Choose the version that is both true and safe.',
   'linhas': [('He asks how last year went.', 'b', 'In 2024 we had 87.74 and in 2025, 105.63, and in January&hellip;', 'Net income grew about twenty per cent last year.'),
              ('He asks what share his company has.', 'a', 'Carestream has grown from eighteen to thirty-eight per cent of our partner mix.', 'I cannot talk about that.'),
              ('He asks about recurring revenue.', 'b', 'I think it is around thirty per cent.', 'I would need to confirm that figure.')],
   'nota': {'pq': 'A do meio &eacute; a que ela PODE dizer: autorizada para esta reuni&atilde;o e sobre ele. Recusar o que &eacute; permitido tamb&eacute;m custa.',
            'duvida': 'Depois de duas recusas, a tend&ecirc;ncia &eacute; recusar tudo. Confirme com ela a lista do que est&aacute; autorizado antes da aula.',
            'inclass': 'Etapa 5: as tr&ecirc;s perguntas em press&atilde;o crescente.'}},
 ]}

PRE[6] = {'intro': 'About 15&ndash;20 minutes. Nothing new here &mdash; five activities that put the five blocks back together.',
 'ex': [
  {'k': 'multi', 't': 'The five blocks', 'instr': 'Mark the <strong>five</strong> blocks of your meeting, in any order.',
   'doc': None,
   'ops': [('Welcome, who you are, what the company does', 1), ('Where it came from, and how it is organised', 1),
           ('What it sells, and for which partners', 1), ('The price list, product by product', 0),
           ('Where it operates, and who keeps it running', 1), ('How last year went, and where it is going', 1),
           ('The contract terms', 0)],
   'rat': 'Five blocks, one per lesson. Price and contract are not yours, and not this meeting.',
   'nota': {'pq': 'Confirma o mapa da reuni&atilde;o. As duas distratoras s&atilde;o comerciais &mdash; &aacute;rea de outro diretor.',
            'inclass': 'Etapa 3: os cinco blocos, na ordem.'}},
  {'k': 'match', 't': 'One line from each lesson', 'instr': 'Match each block to the line that opens it.',
   'pares': [('Block 1 &middot; who you are', 'Welcome to Imagem Healthcare Solutions. I am Rita Rodrigues.'),
             ('Block 2 &middot; history', 'We started in 1988 and today we distribute nationwide.'),
             ('Block 3 &middot; portfolio', 'We work with four main areas, and we represent international brands.'),
             ('Block 4 &middot; coverage', 'We have teams in several states and our own service team.'),
             ('Block 5 &middot; results', 'Net income grew about twenty per cent last year.')],
   'nota': {'pq': 'Uma linha de entrada por bloco. Com ela, o bloco come&ccedil;a mesmo se o resto vier devagar.',
            'inclass': 'Etapa 4: as cinco linhas que seguram a sala.'}},
  {'k': 'gap', 't': 'When he interrupts', 'instr': 'Complete with one word.',
   'itens': [('Of course &mdash; let me come ', 'back', ' to that.'),
             ('Thomaz can give you more ', 'detail', ' on that.'),
             ('I would need to ', 'confirm', ' that detail.')],
   'nota': {'pq': 'As tr&ecirc;s formas de voltar. S&atilde;o as mesmas da aula 1, agora sob interrup&ccedil;&atilde;o real.',
            'inclass': 'Etapa 4, tabela &ldquo;And then&rdquo;.'}},
  {'k': 'leitura', 't': 'Ten minutes instead of thirty', 'instr': 'Read and answer.',
   'texto': ('A visit does not always run to plan. If the president has ten minutes instead of thirty, the '
             'meeting still has to place the company, say what it sells and show that it can support what '
             'it sells. One sentence per block does that.'),
   'q': 'If you only have ten minutes, what do you do?',
   'ops': [('Speak faster and keep all the detail.', 0),
           ('Give one sentence per block, and stop.', 1),
           ('Cut the last two blocks completely.', 0)],
   'rat': '<strong>B.</strong> The shape survives; the detail is what you drop. That is why each block has one opening line.',
   'nota': {'pq': 'Prepara a varia&ccedil;&atilde;o do ensaio: a vers&atilde;o de dez minutos.',
            'duvida': 'Cortar blocos parece razo&aacute;vel &mdash; e deixa o visitante sem saber se a empresa sustenta o que vende.',
            'inclass': 'Etapa 5, segunda varia&ccedil;&atilde;o.'}},
  {'k': 'pair', 't': 'Which one would you say?', 'instr': 'Last check. Choose what you would actually say on Monday.',
   'linhas': [('He interrupts in the middle of block 3.', 'b', 'Sorry, sorry &mdash; where was I?', 'Of course &mdash; let me come back to that.'),
              ('He asks who decides on new partnerships.', 'a', 'Thomaz can give you more detail on that.', 'I decide with the team.'),
              ('A word does not come and the sentence stops.', 'b', 'Sorry, my English&hellip;', 'Let me say that again.')],
   'nota': {'pq': '&Eacute; a &uacute;ltima checagem antes da reuni&atilde;o. Nenhuma novidade &mdash; s&oacute; a escolha certa, r&aacute;pida.',
            'inclass': 'Etapa 4 e etapa 6, com as duas interrup&ccedil;&otilde;es.'}},
 ]}
