# -*- coding: utf-8 -*-
"""As seis aulas do intensivo da Rita, em dados.

O IN-CLASS ja existia (72 telas escritas e validadas na geracao de 19/08). Aqui ele e
reorganizado nas TRECE telas do molde Private Black e ganha o que faltava: a tela de
retask (etapa 8, que antes vivia espremida na de feedback), o fecho com recapitulacao e
confianca, e o cartao de preparacao do professor.

O que NAO muda: os fatos da empresa. 1988, GE em 1996, 146 employees, 30 tecnicos,
lucro liquido 87,74 -> 105,63 (R$ mi), Carestream de 18% para 38% do mix, CEO Thomaz
Rodrigues, nove pessoas na area dela. Numero que nao esta aqui, ela encaminha.
"""

ESTAGIOS = [
    {'n': 'Real-world need and outcome', 'min': 5},
    {'n': 'Situation analysis',          'min': 5},
    {'n': 'Initial attempt and model',   'min': 8},
    {'n': 'Language and strategy toolkit','min': 9},
    {'n': 'Supported rehearsal',         'min': 10},
    {'n': 'Real-world performance',      'min': 9},
    {'n': 'Feedback and upgrade',        'min': 4},
    {'n': 'Focused retask and transfer', 'min': 5},
]

NAV = ['Lesson opening', 'What this lesson is for', 'Where it breaks', 'Your first version',
       'A model, after yours', 'The lines you take', 'When you do not have it',
       'Same thing, different listener', 'The whole thing, with the map',
       'The real thing', 'How it went', 'Once more, one change', 'Today and next']

A1 = {
 'data': '20 August', 'cod': 'E1',
 'tema': 'Company overview & your role',
 'temaPre': 'Before the first minute',
 'titulo': 'Company overview<br><span class="accent">and your role</span>',
 'sub': 'The first minute of the meeting: who you are,<br>what the company does, and what your area covers.',
 'desc': 'A abertura da reuniao: quatro movimentos, cinco linhas e uma saida para quando a palavra nao vem.',
 'brief': [
   ('Who', 'The president of Carestream, visiting from the United States. He has never been to your office.'),
   ('When', '31 August 2026, head office, S&atilde;o Paulo.'),
   ('Your part', 'You open the presentation. Thomaz, the CEO, is in the room.'),
   ('Conditions', 'Your slides and your speaking map are with you &mdash; on 31 August too. They are not scaffolding to remove.'),
   ('Pressure', 'He speaks fast, and he asks before you finish.'),
   ('Success', 'He knows who you are, what the company does and where your area sits &mdash; without asking twice.'),
 ],
 'perguntas': ['By the end of today, what should he know about you?',
               'And about the company?',
               'What do you want him to remember when he leaves the room?'],
 'riscos': [('He speaks fast, and you lose one word.', 'Ask him to repeat. The line is on the next screens, and it costs nothing.'),
            ('He asks something outside your area.', 'Forward it. Thomaz or the service director answers &mdash; and you keep the floor.'),
            ('You know the answer in Portuguese and it does not come in English.', 'Say the part you have. A short true sentence beats a long one you cannot finish.')],
 'tentativa': ('Open the meeting now', 'No preparation, no model. Thirty seconds is enough.', 'He has just walked in. What do you say?'),
 'modelo': [('Move 1', 'Welcome to Imagem Healthcare Solutions.', 'The company first: he is in the right place.'),
            ('Move 2', 'I am Rita Rodrigues, Corporate Management Director.', 'Name and role, in one breath.'),
            ('Move 3', 'We distribute medical technology to hospitals and clinics nationwide.', 'What the company does, in one sentence he can repeat.'),
            ('Move 4', 'My area covers IT, HR, quality, corporate controlling and business processes.', 'Where you sit &mdash; so he knows what to ask you.')],
 'modelo_q': 'What did the model do that your version did not?',
 'linhas': [('Welcome to Imagem Healthcare Solutions.', 'the room is placed'),
            ('I am Rita Rodrigues, Corporate Management Director.', 'name and role'),
            ('We distribute medical technology to hospitals and clinics nationwide.', 'what the company does'),
            ('My area covers IT, HR, quality, corporate controlling and business processes.', 'your scope'),
            ('I would need to confirm that detail.', 'for anything you do not have')],
 'apoio_t': 'Three ways to <span class="accent">keep going</span>',
 'apoio': [('Sorry, could you say that again?', 'when a word goes past you'),
           ('Let me check that for you.', 'when you have the answer, not now'),
           ('Thomaz can give you more detail on that.', 'when it is not your area')],
 'apoio_tab': (['The situation', 'What you say', 'What he hears'],
   [['A word went past', '<em>Sorry, could you say that again?</em>', 'Normal. He repeats and you keep the floor.'],
    ['You have it, not now', '<em>Let me check that for you.</em>', 'You will come back to him. Nothing is dropped.'],
    ['Not your area', '<em>Thomaz can give you more detail on that.</em>', 'The company has an answer &mdash; it is just not yours.']]),
 'ensaio': [('A supplier from Germany, visiting for the first time.', 'Same four moves. He does not know the company at all.'),
            ('A hospital director, here for one hour.', 'Same four moves, shorter: he wants what you sell.'),
            ('The president of Carestream, on 31 August.', 'Same four moves, with his company named in move 3.')],
 'mapa': ['Welcome', 'Name and role', 'What the company does', 'What your area covers'],
 'perf': ('Open the meeting, from the top',
          'Your slides and your map are with you. About one minute. No interruption.',
          [('Your side', 'The four moves, in your own words, from Welcome to what your area covers.'),
           ('His side', 'He has just sat down and says nothing. He is listening.')],
          ['Welcome to', 'Corporate Management Director', 'we distribute', 'my area covers']),
 'cmp': [('&ldquo;I work with many things in the company.&rdquo;', '&ldquo;My area covers IT, HR, quality, corporate controlling and business processes.&rdquo;'),
         ('&ldquo;We sell equipment.&rdquo;', '&ldquo;We distribute medical technology to hospitals and clinics nationwide.&rdquo;')],
 'retask': ('Once more, <span class="accent">with one change</span>',
            'Start with the part you just worked on. Then keep going and open the meeting again, from the top.',
            [('Your side', 'The same opening, with the point from the feedback applied.'),
             ('His side', 'This time he interrupts once, early, with a question about the company.')],
            ['Welcome to', 'my area covers', 'let me come back to that']),
 'recap': ['Opening a meeting with four moves, in order',
           'Saying your role so the visitor knows what to ask you',
           'Saying what the company does in one sentence',
           'Asking for a repetition without losing the floor',
           'Forwarding a question that is not yours',
           'Running the opening once, uninterrupted'],
 'conf': ['Opening a meeting in English with a visitor in the room',
          'Saying what my area covers, without a list that never ends',
          'Asking someone to repeat, in the moment'],
 'fecho_t': 'Today, and <span class="accent">what is next</span>',
 'proxima': 'In the next lesson you tell the company&rsquo;s history in four dates, and say how it is organised today.',
}

A2 = {
 'data': '24 August', 'cod': 'E2',
 'tema': 'History, expertise & organization',
 'temaPre': 'Before the history question',
 'titulo': 'Where the company<br><span class="accent">comes from</span>',
 'sub': 'Thirty-eight years in four moments &mdash;<br>and where you sit in the company today.',
 'desc': 'A historia da empresa em quatro datas, a area dela em uma frase, e a linha que encaminha o que nao e dela.',
 'brief': [
   ('Who', 'The same visitor. He now knows what the company does.'),
   ('Why', 'He asks how the company started &mdash; and what he wants is a story he can follow, not a timeline.'),
   ('Your part', 'Four moments from 1988 to 2026, then where you sit today.'),
   ('Conditions', 'Slides and map with you. About thirty seconds for the history.'),
   ('Pressure', 'He asks about a partner or a headcount that is not in your area.'),
   ('Success', 'He can repeat the shape: started in 1988, grew by representing brands, today distributes nationwide.'),
 ],
 'perguntas': ['If you had to choose four moments from 38 years, which ones matter to him?',
               'What does your area cover, in one sentence?',
               'What would you forward, and to whom?'],
 'riscos': [('You start in 1988 and try to reach 2026 date by date.', 'Four moments. The fifth is where you lose him.'),
            ('He asks about a partner you do not handle.', 'Name it and forward it. Commercial is a different area.'),
            ('He asks how many people work in an area that is not yours.', 'You own the number nine, for your team. The rest you confirm later.')],
 'tentativa': ('Tell him the history now', 'No list, no notes. Thirty seconds.', '&ldquo;How did Imagem Healthcare start?&rdquo;'),
 'modelo': [('1988', 'We started in 1988, distributing Kodak film.', 'Where it began &mdash; one product, one market.'),
            ('1996', 'In 1996 we became a sales representative for GE Diagnostic Imaging.', 'The step up: representing a brand, not just selling film.'),
            ('From 2016', 'From 2016 we added Medtronic, and then Siemens, Guerbet and Dr&auml;ger.', 'The portfolio widens.'),
            ('2026', 'In 2026 we expanded with Danaher and Leica, and started Carestream XR operations.', 'Today &mdash; and his own company is in it.')],
 'modelo_q': 'What links the four moments? Say it in one sentence.',
 'linhas': [('We started in 1988.', 'the first moment'),
            ('We became a sales representative for GE Diagnostic Imaging in 1996.', 'representative = we sell for them, we do not make it'),
            ('From 2016 we added Medtronic, Siemens, Guerbet and Dr&auml;ger.', 'the portfolio widens'),
            ('In 2025 we strengthened our governance, with external audit and a board.', 'the company is organised, not improvised'),
            ('This year we started Carestream XR operations.', 'his company, said in your own timeline')],
 'apoio_t': 'Your area, <span class="accent">in one sentence</span>',
 'apoio': [('I lead Corporate Management: IT, HR, quality, corporate controlling and business processes.', 'your scope, once'),
           ('We are a team of nine.', 'a number you own'),
           ('Service is a different area, with its own director.', 'the forwarding line for this lesson')],
 'apoio_tab': (['He asks about', 'You say', 'Why that works'],
   [['Your team', '<em>We are a team of nine.</em>', 'It is your number. You do not need to confirm it.'],
    ['Another area', '<em>Service is a different area, with its own director.</em>', 'He gets an answer about the company, just not from you.'],
    ['A figure you are unsure of', '<em>I would need to confirm that detail.</em>', 'Better than a number that turns out wrong in front of the CEO.']]),
 'ensaio': [('You have one minute.', 'All four moments, with one sentence each.'),
            ('You have thirty seconds.', 'Four moments, no sentences to spare.'),
            ('You have one sentence.', 'Where it started and what it is today. This is the version he will actually get.')],
 'mapa': ['Four moments', 'Where you sit', 'Your team of nine', 'What you forward'],
 'perf': ('He asks about the company. Answer.',
          'About one minute. Slides and map with you. No interruption.',
          [('His side', '&ldquo;I would like to understand the company a little better. Where did it start, and what do you do here?&rdquo;'),
           ('Your side', 'History in four moments, then your area, then what you forward.')],
          ['we started in', 'sales representative', 'we are a team of nine', 'a different area']),
 'cmp': [('&ldquo;The company is very old, from the eighties.&rdquo;', '&ldquo;We started in 1988, distributing Kodak film.&rdquo;'),
         ('&ldquo;I do many things, IT, HR, quality, controlling, processes, projects&hellip;&rdquo;', '&ldquo;I lead Corporate Management &mdash; five areas, a team of nine.&rdquo;')],
 'retask': ('Once more, <span class="accent">one sentence shorter</span>',
            'Start with the part you just worked on, then give the whole history again &mdash; one moment shorter than last time.',
            [('Your side', 'The same four moments with the feedback applied, ending in your area.'),
             ('His side', 'He asks one follow-up: <em>and who runs the service side?</em>')],
            ['we started in 1988', 'representative for', 'a team of nine', 'a different area']),
 'recap': ['Telling 38 years in four moments instead of a timeline',
           'Saying what a sales representative does, in English',
           'Saying where you sit and what your team covers',
           'Owning the numbers that are yours',
           'Forwarding what belongs to another area',
           'Running the history plus your area in one turn'],
 'conf': ['Telling the company history without losing the listener',
          'Saying what my area covers in one sentence',
          'Answering a question about an area that is not mine'],
 'fecho_t': 'Today, and <span class="accent">what is next</span>',
 'proxima': 'In the next lesson you present the portfolio: what the company sells, and for which partners.',
}

A3 = {
 'data': '25 August', 'cod': 'E3',
 'tema': 'Commercial portfolio & partners',
 'temaPre': 'Before the portfolio question',
 'titulo': 'What the company<br><span class="accent">sells</span>',
 'sub': 'Four categories, one example each &mdash;<br>and the partners behind them. Not a catalogue.',
 'desc': 'O portfolio em quatro categorias com um exemplo cada, os parceiros pelo nome, e a recusa de um numero que ainda nao e dela.',
 'brief': [
   ('Who', 'The president of Carestream. He knows imaging better than anyone in the room.'),
   ('Why', 'He wants to know where his products sit inside what you carry.'),
   ('Your part', 'Four categories, one example each. Then the partners, his own included.'),
   ('Conditions', 'Slides and map with you. He will look at the portfolio slide while you speak.'),
   ('Pressure', 'He asks which partner is biggest &mdash; a share number that belongs to lesson 5.'),
   ('Success', 'He can place Carestream inside your portfolio without you reading a list.'),
 ],
 'perguntas': ['Which category is the one he cares about most?',
               'Which example would you give for that category?',
               'What do you say when he asks for a partner share?'],
 'riscos': [('You list every product and he loses the shape.', 'Four categories. The example serves the category, not the other way round.'),
            ('He asks about a product you do not know in English.', 'Name the category and move. The category is the answer he needs.'),
            ('He asks which partner is biggest.', 'That is a number for another day. Forward it &mdash; the line is on the next screens.')],
 'tentativa': ('Tell him what you sell', 'No list. Thirty seconds.', '&ldquo;What does your portfolio look like?&rdquo;'),
 'modelo': [('Category 1', 'Diagnostic imaging &mdash; for example, X-ray and ultrasound.', 'The one he came for.'),
            ('Category 2', 'Advanced surgical technology &mdash; for example, surgical staplers.', 'One example is enough to place it.'),
            ('Category 3', 'Hospital care &mdash; for example, monitoring and anaesthesia.', 'Where the hospital lives day to day.'),
            ('Category 4', 'Cardiology and cardiac rhythm &mdash; for example, pacemakers.', 'The fourth, and then you stop.')],
 'modelo_q': 'Why one example each, and not the whole catalogue?',
 'linhas': [('We work with four main areas.', 'the shape, before any product'),
            ('Our largest area is diagnostic imaging.', 'true by category &mdash; not a share number'),
            ('For example, X-ray, ultrasound and bone densitometry.', 'examples serve the category'),
            ('We also represent international brands.', 'the bridge to the partners'),
            ('I would need to confirm that detail.', 'for any number you do not own')],
 'apoio_t': 'Naming <span class="accent">who you work with</span>',
 'apoio': [('We represent Medtronic, Carestream, GE, Guerbet and others.', 'his company, said right'),
           ('This year we started Carestream XR operations.', '2026, from the deck'),
           ('We also expanded with Danaher and Leica.', 'the most recent step')],
 'apoio_tab': (['He asks', 'You say', 'What it protects'],
   [['<em>Which partner is biggest?</em>', '<em>Our largest area is diagnostic imaging.</em>', 'True, and it answers the shape of the question.'],
    ['<em>What share is Carestream?</em>', '<em>I would need to confirm that detail.</em>', 'The share is lesson 5 material, and it is confidential.'],
    ['<em>Do you carry X?</em>', '<em>That sits in our hospital care area.</em>', 'The category answers even when the product does not come.']]),
 'ensaio': [('A hospital buyer who knows the products.', 'Straight to the categories. He will ask for examples himself.'),
            ('A visitor who has never seen your catalogue.', 'Four categories, one example each, slowly.'),
            ('The president of Carestream, on 31 August.', 'Same four, with imaging first and his brand named.')],
 'mapa': ['Four categories', 'One example each', 'Partners', 'What you forward'],
 'perf': ('Present the portfolio',
          'About one minute. Slides and map with you. No interruption.',
          [('His side', '&ldquo;Walk me through what you carry.&rdquo;'),
           ('Your side', 'Four categories with one example each, then the partners &mdash; his own named.')],
          ['four main areas', 'for example', 'we represent', 'I would need to confirm']),
 'cmp': [('&ldquo;We sell X-ray, ultrasound, densitometry, staplers, monitors, pacemakers&hellip;&rdquo;', '&ldquo;We work with four main areas. Diagnostic imaging, for example X-ray and ultrasound.&rdquo;'),
         ('&ldquo;Carestream is about thirty per cent, I think.&rdquo;', '&ldquo;I would need to confirm that detail.&rdquo;')],
 'retask': ('Once more, <span class="accent">imaging first</span>',
            'Start with the part you just worked on, then give the portfolio again &mdash; this time opening with the category he came for.',
            [('Your side', 'Four categories, imaging first, with the feedback applied.'),
             ('His side', 'He asks for the partner share. You forward it and keep going.')],
            ['four main areas', 'for example', 'we represent', 'confirm that detail']),
 'recap': ['Presenting a portfolio as four categories, not a list',
           'Giving one example per category and stopping there',
           'Naming the partners, including the visitor&rsquo;s own company',
           'Answering a share question without inventing a number',
           'Using the category when the product name does not come',
           'Running the whole portfolio in one turn'],
 'conf': ['Presenting what the company sells without reading a list',
          'Naming partners and what we do for them',
          'Refusing a number I do not have, and keeping the conversation'],
 'fecho_t': 'Today, and <span class="accent">what is next</span>',
 'proxima': 'In the next lesson you say where the company operates, and what the service team can do.',
}

A4 = {
 'data': '26 August', 'cod': 'E4',
 'tema': 'Commercial and service coverage',
 'temaPre': 'Before the coverage question',
 'titulo': 'Where you are, and<br><span class="accent">what you can do there</span>',
 'sub': 'Coverage and service answer one question:<br>if he buys, who is near him and who keeps it running.',
 'desc': 'Cobertura e servico como uma resposta so, com o numero que ela tem (trinta tecnicos) e o que ela encaminha.',
 'brief': [
   ('Who', 'The president of Carestream, deciding whether to expand XR operations with you.'),
   ('Why', 'Behind the question about coverage there is another one: can you support what you sell?'),
   ('Your part', 'Where the company is, and who keeps the equipment running &mdash; as one answer, not two lists.'),
   ('Conditions', 'Slides and map with you. He may ask about response time.'),
   ('Pressure', 'Response time is a number the deck does not give you.'),
   ('Success', 'He hears an operation, not a map: teams in several states and your own service team.'),
 ],
 'perguntas': ['What would you want to hear, if you were the one buying?',
               'Which is the stronger half for him: where you are, or who supports it?',
               'What do you say about response time?'],
 'riscos': [('You list the states, then list the service team, and he does not see the link.', 'One answer, two halves: where we are, and who keeps it running.'),
            ('He asks about response time.', 'You do not have that number. Confirm later &mdash; do not improvise it.'),
            ('He asks about a state you do not cover.', 'Say where you are, and that logistics runs nationwide from S&atilde;o Paulo.')],
 'tentativa': ('Tell him where you operate', 'Thirty seconds. No map.', '&ldquo;Where do you operate, and who supports the equipment?&rdquo;'),
 'modelo': [('Half 1 &middot; where', 'Our head office and distribution centre are in S&atilde;o Paulo.', 'The centre of the operation.'),
            ('Half 1 &middot; where', 'We also have a branch in Mato Grosso do Sul, and teams in Rio, Esp&iacute;rito Santo and Mato Grosso.', 'Reach, without reading a map.'),
            ('Half 1 &middot; where', 'We have a logistics branch in Santa Catarina for imports.', 'Why delivery works nationwide.'),
            ('Half 2 &middot; who', 'And we have our own service team &mdash; technicians, coordinators and applications support.', 'The half that answers <em>and if something breaks?</em>')],
 'modelo_q': 'Which half of that answer is the one he is really asking about?',
 'linhas': [('Our head office and distribution centre are in S&atilde;o Paulo.', 'where the operation sits'),
            ('We have teams in several states, and a logistics branch in Santa Catarina.', 'reach, in one line'),
            ('We have our own service team.', 'own = not outsourced &mdash; this is the operational benefit'),
            ('The team includes technicians, coordinators and applications support.', 'what the team actually is'),
            ('I would need to confirm our response time.', 'for anything the deck does not say')],
 'apoio_t': 'The number <span class="accent">you can say</span>',
 'apoio': [('Our service team has thirty technicians.', 'from the deck &mdash; a number she owns'),
           ('We also have remote care and applications support.', 'capability, not a promise'),
           ('I would need to confirm our response time.', 'for anything the deck does not say')],
 'apoio_tab': (['He asks', 'You say', 'Why'],
   [['<em>Who installs it?</em>', '<em>We have our own service team &mdash; thirty technicians.</em>', 'A number you own, and it answers the real question.'],
    ['<em>How fast do you respond?</em>', '<em>I would need to confirm our response time.</em>', 'The deck does not give it. A wrong SLA is worse than a pause.'],
    ['<em>Do you cover the whole country?</em>', '<em>We have teams in several states, and logistics runs nationwide.</em>', 'True, and it does not promise an office everywhere.']]),
 'ensaio': [('&ldquo;Where are you located?&rdquo;', 'Start with S&atilde;o Paulo, then reach.'),
            ('&ldquo;Do you cover the whole country?&rdquo;', 'Teams in several states, logistics nationwide.'),
            ('&ldquo;What happens after we buy?&rdquo;', 'Straight to the second half: your own service team.')],
 'mapa': ['Where the company is', 'Which teams', 'Our own service', 'What you forward'],
 'perf': ('He is deciding. Answer him.',
          'About one minute. Slides and map with you. No interruption.',
          [('His side', '&ldquo;If we expand XR operations with you, who installs it and who keeps it running?&rdquo;'),
           ('Your side', 'Both halves, joined: where you are, and the service team &mdash; with the number you own.')],
          ['head office', 'teams in several states', 'our own service team', 'thirty technicians']),
 'cmp': [('&ldquo;We have people in many states and also a service team.&rdquo;', '&ldquo;We have teams in several states &mdash; and our own service team, thirty technicians.&rdquo;'),
         ('&ldquo;We answer in about 24 hours, I believe.&rdquo;', '&ldquo;I would need to confirm our response time.&rdquo;')],
 'retask': ('Once more, <span class="accent">service first</span>',
            'Start with the part you just worked on, then answer again &mdash; opening with the half he cares about.',
            [('Your side', 'Service first, then coverage, with the feedback applied.'),
             ('His side', 'He asks for a response time. You forward it and finish the answer.')],
            ['our own service team', 'thirty technicians', 'teams in several states', 'confirm']),
 'recap': ['Answering a coverage question as one answer, not two lists',
           'Saying <em>our own service team</em> and what it means',
           'Using the number you own &mdash; thirty technicians',
           'Refusing a response time you do not have',
           'Connecting where the company is to what it can do there',
           'Running the whole answer in one turn'],
 'conf': ['Explaining where the company operates',
          'Explaining what happens after the sale',
          'Saying <em>I would need to confirm</em> without losing the room'],
 'fecho_t': 'Today, and <span class="accent">what is next</span>',
 'proxima': 'In the next lesson you take the charts: what each one says, in one sentence.',
}

A5 = {
 'data': '27 August', 'cod': 'E5',
 'tema': 'Results, growth & integrated Q&A',
 'temaPre': 'Before the numbers',
 'titulo': 'The charts,<br><span class="accent">in one sentence each</span>',
 'sub': 'He can read the numbers. Your job is to say<br>what they mean &mdash; and to refuse the one you do not have.',
 'desc': 'Uma frase por grafico, duas oportunidades ditas como possibilidade, e a recusa de um numero confidencial.',
 'brief': [
   ('Who', 'The president of Carestream, looking at the results slide before you speak.'),
   ('Why', 'Numbers on a slide do not carry meaning by themselves. You give each chart one sentence.'),
   ('Your part', 'Growth, comparison, partner mix &mdash; and two opportunities, said as possibilities.'),
   ('Conditions', 'Confidentiality: revenue, net income and partner share are authorised for this meeting only. Confirm before the lesson.'),
   ('Pressure', 'He asks for recurring revenue &mdash; a percentage that was never given to you.'),
   ('Success', 'He hears three sentences and a direction, not a spreadsheet read aloud.'),
 ],
 'perguntas': ['If he sees one chart and you say one sentence, what should that sentence do?',
               'Which chart matters most to him?',
               'What do you say when the figure is not on the slide?'],
 'riscos': [('You read every number and he stops listening.', 'One sentence per chart. He is already reading the numbers.'),
            ('He asks for a figure that is not on the slide.', 'Confirm later. The deck is the limit of what you say.'),
            ('He asks about recurring revenue.', 'That percentage was never given to you. It is not a memory problem &mdash; it does not exist for you.')],
 'tentativa': ('Summarise the growth', 'Thirty seconds. One chart: net income, 2024 to 2025.', '&ldquo;How did last year go?&rdquo;'),
 'modelo': [('Chart 1 &middot; growth', 'Net income grew about twenty per cent from 2024 to 2025.', '87.74 &rarr; 105.63, R$ million, from the deck.'),
            ('Chart 2 &middot; comparison', 'The first two months of 2026 are ahead of the same period last year.', '12.52 &rarr; 17.85, same period.'),
            ('Chart 3 &middot; mix', 'Carestream is now a much larger share of our business than in 2024.', 'From eighteen to thirty-eight per cent &mdash; his own company.'),
            ('The shape', 'Growing, ahead of last year, and increasingly with him.', 'Three sentences and a direction.')],
 'modelo_q': 'What does &ldquo;about twenty per cent&rdquo; do that &ldquo;105.63&rdquo; does not?',
 'linhas': [('Net income grew about twenty per cent last year.', '2024: 87.74 &middot; 2025: 105.63, R$ million'),
            ('The first two months of this year are ahead of last year.', '12.52 &rarr; 17.85, same period'),
            ('Carestream has grown from eighteen to thirty-eight per cent of our partner mix.', 'his company, in your numbers'),
            ('That is a possibility, not a commitment.', 'the line that protects every opportunity'),
            ('I would need to confirm that figure.', 'for anything the deck does not give you')],
 'apoio_t': 'Where it is <span class="accent">going</span>',
 'apoio': [('We see potential for the Midea portfolio in Brazil.', 'possibility, never a commitment'),
           ('We are expanding with Danaher and Leica in the interior of S&atilde;o Paulo.', 'already happening, 2026'),
           ('That is a possibility, not a commitment.', 'say it before he writes it down as a promise')],
 'apoio_tab': (['He asks', 'You say', 'Why'],
   [['<em>How was last year?</em>', '<em>Net income grew about twenty per cent.</em>', 'One sentence. He has the chart in front of him.'],
    ['<em>How much of that is Carestream?</em>', '<em>From eighteen to thirty-eight per cent of our partner mix.</em>', 'Authorised for this meeting, and it is about him.'],
    ['<em>What is your recurring revenue?</em>', '<em>I would need to confirm that figure.</em>', 'It was never given to you. Nothing to remember, nothing to guess.']]),
 'ensaio': [('&ldquo;How was last year?&rdquo;', 'One sentence. Stop.'),
            ('&ldquo;And how much of that is Carestream?&rdquo;', 'The mix, and what it means for him.'),
            ('&ldquo;What percentage is recurring revenue?&rdquo;', 'The refusal, said calmly, and then keep going.')],
 'mapa': ['Growth', 'Comparison', 'Partner mix', 'Two possibilities', 'What you forward'],
 'perf': ('Present the results',
          'About one minute, then he asks two questions. Slides and map with you.',
          [('His side', '&ldquo;Give me the headline on last year, and where you see this going.&rdquo;'),
           ('Your side', 'One sentence per chart, then the two opportunities &mdash; as possibilities.')],
          ['grew about twenty per cent', 'ahead of last year', 'partner mix', 'a possibility, not a commitment']),
 'cmp': [('&ldquo;In 2024 we had 87.74 and in 2025, 105.63, and in January&hellip;&rdquo;', '&ldquo;Net income grew about twenty per cent last year.&rdquo;'),
         ('&ldquo;We will launch Midea in Brazil.&rdquo;', '&ldquo;We see potential for Midea in Brazil &mdash; that is a possibility, not a commitment.&rdquo;')],
 'retask': ('Once more, <span class="accent">under pressure</span>',
            'Start with the part you just worked on, then give the results again &mdash; this time he interrupts with the question you cannot answer.',
            [('Your side', 'Three sentences, with the feedback applied.'),
             ('His side', 'He asks for recurring revenue in the middle. You refuse it and finish the picture.')],
            ['about twenty per cent', 'ahead of last year', 'a possibility', 'confirm that figure']),
 'recap': ['Giving each chart one sentence instead of reading it',
           'Saying what a number means, not what it is',
           'Talking about growth with the partner in the room',
           'Saying an opportunity as a possibility, not a promise',
           'Refusing a confidential or missing figure, calmly',
           'Running the results with two questions on top'],
 'conf': ['Summarising a chart in one sentence',
          'Talking about growth with the partner in the room',
          'Refusing a number without losing authority'],
 'fecho_t': 'Today, and <span class="accent">what is next</span>',
 'proxima': 'The next lesson is the whole meeting, from the welcome to the questions: you present, he asks, and you close.',
}

A6 = {
 'data': '28 August', 'cod': 'E6',
 'tema': 'Full meeting simulation',
 'temaPre': 'Before the meeting itself',
 'titulo': 'The whole meeting,<br><span class="accent">once</span>',
 'sub': 'Nothing new today. You run what you built,<br>with the same slides and the same map as on Monday.',
 'desc': 'A reuniao inteira, com interrupcoes: cinco blocos, tres formas de voltar e nada de conteudo novo.',
 'brief': [
   ('Who', 'The president of Carestream. On Monday, for real.'),
   ('Why', 'This is the last run before 31 August. Nothing new enters today.'),
   ('Your part', 'Five blocks in order, from welcome to results, with questions on top.'),
   ('Conditions', 'Slides and map with you, exactly as on Monday.'),
   ('Pressure', 'He interrupts twice, and one question is not yours.'),
   ('Success', 'You get through the five blocks, come back after each interruption, and close.'),
 ],
 'perguntas': ['Which part of the meeting still worries you?',
               'Which block would you cut if he only had ten minutes?',
               'What is your line for a question that is not yours?'],
 'riscos': [('He interrupts in the middle of your opening.', 'Take it in, answer short, and come back with <em>let me come back to that</em>.'),
            ('He asks something from an area that is not yours.', 'Forward it &mdash; Thomaz, or the service director.'),
            ('A word does not come and the sentence stops.', 'Say the part you have and keep the block moving.')],
 'tentativa': ('Open, and keep going until I stop you', 'Slides and map with you.', 'He has just sat down. Begin.'),
 'modelo': [('Block 1', 'Welcome, who you are, what the company does.', 'Lesson 1.'),
            ('Block 2', 'Where it came from, and how it is organised.', 'Lesson 2.'),
            ('Block 3', 'What it sells, and for which partners.', 'Lesson 3.'),
            ('Block 4 and 5', 'Where it operates and who keeps it running &mdash; then how last year went.', 'Lessons 4 and 5.')],
 'modelo_q': 'Which block is the one you would never cut?',
 'linhas': [('Welcome to Imagem Healthcare Solutions. I am Rita Rodrigues, Corporate Management Director.', 'lesson 1'),
            ('We started in 1988 and today we distribute medical technology nationwide.', 'lessons 2 and 1'),
            ('We work with four main areas, and we represent international brands.', 'lesson 3'),
            ('We have teams in several states and our own service team.', 'lesson 4'),
            ('Net income grew about twenty per cent last year.', 'lesson 5')],
 'apoio_t': 'Three ways <span class="accent">back in</span>',
 'apoio': [('Of course &mdash; let me come back to that.', 'takes the interruption and keeps your place'),
           ('Thomaz can give you more detail on that.', 'when it is not your area'),
           ('I would need to confirm that detail.', 'when the deck does not have it')],
 'apoio_tab': (['It happens', 'You say', 'And then'],
   [['He interrupts mid-block', '<em>Of course &mdash; let me come back to that.</em>', 'Answer in one sentence and return to the block you left.'],
    ['Not your area', '<em>Thomaz can give you more detail on that.</em>', 'The company answers; you keep the presentation.'],
    ['No number for it', '<em>I would need to confirm that detail.</em>', 'Move to the next block without apologising twice.']]),
 'ensaio': [('The block you named at the start.', 'Twice: once as it is, once shorter.'),
            ('The block you would cut.', 'Say it in one sentence &mdash; that is the ten-minute version.'),
            ('The opening, from memory.', 'No map this time. It is the one you will say first on Monday.')],
 'mapa': ['Welcome and who you are', 'Where it came from', 'What it sells', 'Where it operates', 'How last year went'],
 'perf': ('The full meeting',
          'Slides and map with you, exactly as on Monday. He will interrupt twice.',
          [('Your side', 'Five blocks, in order, with the repair lines when you need them.'),
           ('His side', '&ldquo;How long have you been in the market?&rdquo; &middot; &ldquo;Who handles installation?&rdquo; &middot; &ldquo;What is your recurring revenue?&rdquo; &middot; &ldquo;Who decides on new partnerships?&rdquo;')],
          ['welcome to', 'we started in 1988', 'four main areas', 'our own service team', 'let me come back to that']),
 'cmp': [('&ldquo;Sorry, sorry &mdash; where was I? I do not remember.&rdquo;', '&ldquo;Let me come back to that. So &mdash; where the company operates.&rdquo;'),
         ('&ldquo;I think it is around thirty per cent, more or less.&rdquo;', '&ldquo;I would need to confirm that detail.&rdquo;')],
 'retask': ('Once more, <span class="accent">the part you take to Monday</span>',
            'Start with the part you just worked on. Then run the two blocks around it, so it lands where it will land on Monday.',
            [('Your side', 'The corrected part, then the blocks before and after it.'),
             ('His side', 'One interruption, in the middle, and then silence until you finish.')],
            ['let me come back to that', 'welcome to', 'our own service team', 'about twenty per cent']),
 'recap': ['Running the five blocks in order, without notes to read',
           'Coming back to your place after an interruption',
           'Forwarding a question that is not yours, in the moment',
           'Refusing a number and keeping the room',
           'Saying the ten-minute version if he is short of time',
           'Closing the meeting yourself, instead of trailing off'],
 'conf': ['Presenting the whole company on 31 August',
          'Handling an interruption without losing my place',
          'Answering a question I did not prepare for'],
 'fecho_t': 'Monday, and <span class="accent">what you take with you</span>',
 'proxima': 'On 31 August you will have the same slides and the same map in front of you. Nothing in that room will be new.',
}

AULAS = {1: A1, 2: A2, 3: A3, 4: A4, 5: A5, 6: A6}
for _n, _a in AULAS.items():
    _a['n'] = _n
    _a['mod'] = 'ESP'
    _a['nav'] = list(NAV)
    _a['stages'] = [dict(s) for s in ESTAGIOS]
