{
  identity:'Lesson 02 &middot; Block 1 (Build) &middot; Listening into Interaction &middot; receptive level B1, productive level B1 &middot; online, 60 minutes &middot; second lesson of the first cycle. Assessment model in force: <strong>continuous teacher-led assessment</strong>. This lesson does not create, prepare or presuppose a test.',
  goals:'<strong>To follow a three-way call about teaching material and come into it to check one point.</strong><ul>'+
        '<li>To keep track of who is arguing for what, without a transcript.</li>'+
        '<li>To tell a position from a proposal, and both from a question.</li>'+
        '<li>To hear a speaker change their own position mid-turn.</li>'+
        '<li>To come in by naming what was said, not by opening a new subject.</li>'+
        '<li>To ask one checking question and hand the call back.</li></ul>',
  product:'The recorded call runs in three parts and stops after each one. At each stop the learner decides whether to come in. When she does, she names what she heard, asks the one thing she needs settled, and returns the call to whoever was speaking. You play the person chairing, and you answer with a question of your own once. Roughly five minutes, with a language menu available and no full script.<br><br><strong>You play one person, and only after she comes in.</strong> The three speakers exist in the recording; you never perform them.',
  criteria:'<ol><li>Says who was arguing for what, naming all three speakers.</li>'+
           '<li>Identifies the turn where a speaker moves off their own position.</li>'+
           '<li>Comes in by referring to something said, and asks one checking question.</li>'+
           '<li>Returns to her point after the call moves on, without being invited back.</li></ol>'+
           '<p>Criterion 4 is the one to watch. Her strategy at work is to write first and read it out; a call gives her no time for that, and this is the first lesson of the cycle where that strategy simply cannot run (H2 of the profile).</p>',
  prep:'<ul><li>Listen to the whole call before the lesson. The door opens at Rachel&rsquo;s line <em>I am not sure we agree it is too long</em> &mdash; a position turning into a different one. It is the target of stage 5 and must not be given away earlier.</li>'+
       '<li><strong>The third speaker exists and barely speaks.</strong> Marta chairs: she asks, she reformulates, she closes. If the learner describes her as &ldquo;the one who agrees&rdquo;, go back to the line where Marta restates the disagreement. Chairing is not agreeing.</li>'+
       '<li>Choose which question you will ask back in stage 7 before the lesson. Both are written out in the note on that screen; neither asks for anything the call does not contain.</li>'+
       '<li>The transcript exists from screen 5 onwards, and not before.</li>'+
       '<li><strong>Pacing.</strong> Stage 5 is the longest and the most analytical. If she stalls, cut one of the three extracts rather than extending &mdash; the production in stage 7 cannot shrink.</li></ul>',
  language:'<strong>Naming what you are about to do:</strong> <em>Can I check one thing before we move on?</em> &middot; <em>Sorry to jump in &mdash; I heard you say&hellip;</em> &middot; <em>Just to be clear&hellip;</em><br><strong>Reporting a position:</strong> <em>Peter is arguing for&hellip;</em> &middot; <em>Rachel&rsquo;s point is that&hellip;</em> &middot; <em>They disagree about&hellip;, not about&hellip;</em><br><strong>Handing it back:</strong> <em>That was all I needed.</em> &middot; <em>Sorry &mdash; you were saying?</em><br>Pronunciation: the weak forms in <em>could have</em> and <em>would have</em>, which is where she loses the second half of a fast turn.',
  transcript:'The recording has a transcript, and it opens at screen 5 &mdash; not before. <strong>Keep it closed during the first listening.</strong> That screen is the only place in the lesson where the evidence is purely auditory; a transcript there replaces the skill with reading. From stage 5 it is the right tool: the analysis is about what a specific line does, and she has to be able to point at the line.',
  difficulties:'<ul><li><strong>Three voices, two of them female.</strong> Following who is who is part of the task, not an accident of casting. If she loses track in the first listening, that is data &mdash; do not fix it by naming them for her.</li>'+
       '<li><strong>Waiting to be invited.</strong> The likely failure in stage 7 is not language: it is waiting for a pause that a real call does not offer. The three stops exist to make the decision explicit.</li>'+
       '<li><strong>Chairing read as agreeing.</strong> Marta never states a position of her own. Learners routinely score her as the tie-breaker.</li></ul>',
  scaffolding:'<strong>If the learner needs support:</strong> in stage 7, let her keep the two-line note from stage 6 in view. If she comes in and immediately opens a new subject, stop her and rebuild the first sentence &mdash; it has to contain something someone actually said.<br><strong>Challenge:</strong> if she comes in cleanly at the first stop, use the second question back &mdash; <em>and which of the two would you go with?</em> &mdash; which forces a position rather than a check.',
  feedback:'Two points, from her own formulation. The likely one to develop is the opening of the turn: naming what she heard before asking. The replay is one stop, not the whole call &mdash; the one where she waited longest.',
  evidence:'Record: whether all three speakers were correctly attributed; whether she identified the turn where Rachel moves; at which of the three stops she came in, and what she said first; whether she returned to her point after the call moved on. Separate observation from interpretation: writing first as turn avoidance is <strong>observed</strong> here for the first time and is not decided by one lesson.',
  prepost:'The pre-class prepares the situation and the vocabulary of the call, and gives her the two shortest extracts to hear &mdash; never the turn where the position changes. The post-class offers a listening on chairing meetings and a short reading on disagreeing in English, both optional.',
  key:'<strong>Stage 3 (gist):</strong> a planning call about one unit of a coursebook; three people, one chairing. <strong>Stage 4:</strong> Peter &mdash; cut the second reading text; Rachel &mdash; keep it and move it; Marta &mdash; chairs, and states no position of her own. <strong>Stage 5:</strong> the move is Rachel&rsquo;s <em>I am not sure we agree it is too long</em>; Peter concedes at <em>that is a better one than mine, honestly</em>. <strong>Stage 6:</strong> any opening that refers to something said is acceptable, including forms not on the list.'
}
