#!/bin/bash
API_KEY="$ELEVENLABS_API_KEY"
A="sfJopaWaOtauCD3HKX6Q"; E="BIvP0GN1cAtSRTxNHnWS"
O="public/audio/dienane-brandao-de-mesquita"; M="eleven_multilingual_v2"
g() { [ -f "$O/$2" ] && return; echo "GEN $2"
  curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/$3" \
    -H "xi-api-key: $API_KEY" -H "Content-Type: application/json" \
    -d "{\"text\":\"$1\",\"model_id\":\"$M\",\"voice_settings\":{\"stability\":0.5,\"similarity_boost\":0.75,\"style\":0.0,\"use_speaker_boost\":true}}" \
    --output "$O/$2"; sleep 0.3; }
echo "=== AULA 4 ==="
g "Water" "water.mp3" "$E"
g "Coffee" "coffee.mp3" "$E"
g "Bread" "bread.mp3" "$E"
g "Rice" "rice.mp3" "$E"
g "Chicken" "chicken.mp3" "$E"
g "Fruit" "fruit.mp3" "$E"
g "Menu" "menu.mp3" "$E"
g "Order" "order.mp3" "$E"
g "Can I have some water, please?" "can_i_have_some_water_please.mp3" "$E"
g "I have coffee every morning." "i_have_coffee_every_morning.mp3" "$E"
g "I eat bread for breakfast." "i_eat_bread_for_breakfast.mp3" "$E"
g "We have rice for lunch." "we_have_rice_for_lunch.mp3" "$E"
g "I cook chicken for dinner." "i_cook_chicken_for_dinner.mp3" "$E"
g "I eat fruit every day." "i_eat_fruit_every_day.mp3" "$E"
g "Can I see the menu, please?" "can_i_see_the_menu_please.mp3" "$E"
g "I would like to order, please." "i_would_like_to_order_please.mp3" "$E"
g "I would like a coffee and some bread." "i_would_like_a_coffee_and_some_bread.mp3" "$E"
g "Can I have an orange juice?" "can_i_have_an_orange_juice.mp3" "$E"
g "I would like some rice and chicken." "i_would_like_some_rice_and_chicken.mp3" "$E"
g "Do you have any fruit?" "do_you_have_any_fruit.mp3" "$E"
g "Good morning. Welcome to Hotel Brasília. What would you like for breakfast?" "good_morning_welcome_to_hotel_brasilia.mp3" "$A"
g "Good morning! I would like a coffee, please." "good_morning_i_would_like_a_coffee_please.mp3" "$E"
g "Of course. Would you like some bread or fruit?" "of_course_would_you_like_some_bread_or_fruit.mp3" "$A"
g "Some bread and an orange, please." "some_bread_and_an_orange_please.mp3" "$E"
g "Would you like some water too?" "would_you_like_some_water_too.mp3" "$A"
g "Yes, please. Can I have some water?" "yes_please_can_i_have_some_water.mp3" "$E"
g "Of course. Anything else?" "of_course_anything_else.mp3" "$A"
g "No, thank you. That is all." "no_thank_you_that_is_all.mp3" "$E"
g "Good morning. Welcome to Hotel Brasília. What would you like for breakfast? Of course, one coffee. Would you like some bread or fruit? Some bread and eggs. Very good. Would you like some water too? One water. Anything else? No? Your order will be ready in five minutes." "listening4_1_waiter_order.mp3" "$A"
g "Hi. I would like to order lunch, please. Can I have some rice and chicken? And a salad too, please. For drinks, I would like some water. Actually, can I have an orange juice instead? Thank you." "listening4_2_ana_lunch.mp3" "$E"
echo "=== DONE ===" && ls -1 "$O"/*.mp3 | wc -l
