#!/bin/bash
API_KEY="$ELEVENLABS_API_KEY"
ARTHUR="sfJopaWaOtauCD3HKX6Q"
ELLEN="BIvP0GN1cAtSRTxNHnWS"
OUT="public/audio/dienane-brandao-de-mesquita"
MODEL="eleven_multilingual_v2"
gen() {
  local t="$1" f="$2" v="$3"
  [ -f "$OUT/$f" ] && { echo "SKIP $f"; return; }
  echo "GEN $f"
  curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/$v" \
    -H "xi-api-key: $API_KEY" -H "Content-Type: application/json" \
    -d "{\"text\":\"$t\",\"model_id\":\"$MODEL\",\"voice_settings\":{\"stability\":0.5,\"similarity_boost\":0.75,\"style\":0.0,\"use_speaker_boost\":true}}" \
    --output "$OUT/$f"
  sleep 0.3
}
echo "=== AULA 3 AUDIO ==="
gen "Mother" "mother.mp3" "$ELLEN"
gen "Father" "father.mp3" "$ELLEN"
gen "Brother" "brother.mp3" "$ELLEN"
gen "Sister" "sister.mp3" "$ELLEN"
gen "Husband" "husband.mp3" "$ELLEN"
gen "Children" "children.mp3" "$ELLEN"
gen "Home" "home.mp3" "$ELLEN"
gen "Together" "together.mp3" "$ELLEN"
gen "My mother lives in Belém." "my_mother_lives_in_belem.mp3" "$ELLEN"
gen "My father is 75 years old." "my_father_is_75_years_old.mp3" "$ELLEN"
gen "I have one brother." "i_have_one_brother.mp3" "$ELLEN"
gen "My sister works in Belém." "my_sister_works_in_belem.mp3" "$ELLEN"
gen "Her husband is a teacher." "her_husband_is_a_teacher.mp3" "$ARTHUR"
gen "She has two children." "she_has_two_children.mp3" "$ELLEN"
gen "My home is in Altamira." "my_home_is_in_altamira.mp3" "$ELLEN"
gen "We have dinner together." "we_have_dinner_together.mp3" "$ELLEN"
gen "My family lives in Belém." "my_family_lives_in_belem.mp3" "$ELLEN"
gen "His name is Carlos." "his_name_is_carlos.mp3" "$ARTHUR"
gen "Her name is Ana." "her_name_is_ana.mp3" "$ELLEN"
gen "Our home is beautiful." "our_home_is_beautiful.mp3" "$ELLEN"
gen "Their children go to school." "their_children_go_to_school.mp3" "$ARTHUR"
gen "How many brothers do you have?" "how_many_brothers_do_you_have.mp3" "$ARTHUR"
gen "I have one brother and one sister." "i_have_one_brother_and_one_sister.mp3" "$ELLEN"
gen "My brother lives in Belém with his family." "my_brother_lives_in_belem_with_his_family.mp3" "$ELLEN"
gen "Her children are very young." "her_children_are_very_young.mp3" "$ARTHUR"
gen "We are a small family." "we_are_a_small_family.mp3" "$ELLEN"
gen "My mother is my best friend." "my_mother_is_my_best_friend.mp3" "$ELLEN"
gen "Do you live with your family?" "do_you_live_with_your_family.mp3" "$ARTHUR"
gen "No, my family is in Belém. I live in Altamira for work." "no_my_family_is_in_belem_i_live_in_altamira_for_wo.mp3" "$ELLEN"
gen "Tell me about your family." "tell_me_about_your_family.mp3" "$ARTHUR"
gen "I have a brother and a sister. They live in Belém." "i_have_a_brother_and_a_sister_they_live_in_belem.mp3" "$ELLEN"
gen "That is nice! Are your parents in Belém too?" "that_is_nice_are_your_parents_in_belem_too.mp3" "$ARTHUR"
gen "Yes, my mother and father live in Belém." "yes_my_mother_and_father_live_in_belem.mp3" "$ELLEN"
gen "Do you see them often?" "do_you_see_them_often.mp3" "$ARTHUR"
gen "I visit my family every month. We have dinner together." "i_visit_my_family_every_month_we_have_dinner_toget.mp3" "$ELLEN"
gen "That sounds wonderful. Family is important." "that_sounds_wonderful_family_is_important.mp3" "$ARTHUR"
gen "Yes, my family is very important to me." "yes_my_family_is_very_important_to_me.mp3" "$ELLEN"
gen "My family is very important to me." "my_family_is_very_important_to_me.mp3" "$ELLEN"
# Listening passages
gen "My name is Pedro. I have a big family. My mother and father live in São Paulo. I have two brothers and one sister. My sister's name is Maria. Her husband is a doctor. They have three children. My brothers live in Rio. We visit our parents every month. Family is very important to me." "listening3_1_pedro_family.mp3" "$ARTHUR"
gen "Hello, I am Ana. My family is small. I have one sister. Her name is Sofia. She lives in Recife with her husband. They have one son. My mother lives with me in Brasília. My father passed away two years ago. I miss him very much. But my mother and I are happy together." "listening3_2_ana_family.mp3" "$ELLEN"
echo "=== DONE ===" && ls -1 "$OUT"/*.mp3 | wc -l
