# -*- coding: utf-8 -*-
# Aula 5 -- A Semester Abroad (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "A Semester <span class='accent'>Abroad</span>",
    'hero_line': 'What you would do in your first week, and what a friend wishes he had done in his',
    'menu_desc': 'Real choices of an exchange year, and the second, third and mixed conditionals -- 34 slides',
    'grammar_point': 'second, third and mixed conditionals',
    'phases': ['The Plan', 'Words of the Year Abroad', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'theo', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1513635269975-59663e0ac1ad?w=1400&q=80',
        'ch2': U + 'photo-1529156069898-49953e39b3ac?w=1400&q=80',
        'ch_grammar': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch4': U + 'photo-1522202176988-66273c2fd55f?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1541339907198-e08756dedf3f?w=1400&q=80',
        'ch7': U + 'photo-1513635269975-59663e0ac1ad?w=1400&q=80',
        'pc': U + 'photo-1513635269975-59663e0ac1ad?w=600&q=80',
    },
    'warmup': {
        'heading': "Your First Day in a <span class='accent'>New City</span>",
        'sub': 'Think of your month in Scotland. What surprised you on the first day, and what was harder than you expected?',
    },
    'target': {
        'heading': "Imagine, Regret, <span class='accent'>Decide</span>",
        'steps': [
            'Imagine: what you would do if you were abroad now.',
            'Regret: what somebody would have done differently, if they had known.',
            'Decide: what you will do, because of what you learned.',
        ],
    },
    'diagnostic': {
        'heading': "If You Were in London <span class='accent'>Tomorrow&hellip;</span>",
        'p1': 'A friend asks: &ldquo;If you were starting your exchange in London tomorrow, what would you do in the first week?&rdquo;',
        'p2': 'Answer for sixty seconds. Say at least three things you would do, and one thing you would not do.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Year Abroad</span>",
            'sub': 'Thirteen words every exchange student uses in the first month'},
    'vocab': [
        {'word': 'Housing', 'def': 'The rooms or apartments where people live, especially the ones a university offers', 'ex': 'The university offers housing for exchange students.', 'icon': 'building'},
        {'word': 'A roommate', 'def': 'A person who shares a room or an apartment with you', 'ex': 'My roommate was from Germany, and we cooked together on Sundays.', 'icon': 'users'},
        {'word': 'To settle in', 'def': 'To start to feel comfortable in a new place or situation', 'ex': 'It took me three weeks to settle in.', 'icon': 'anchor'},
        {'word': 'Homesick', 'def': 'Sad because you are far from your home and your family', 'ex': 'I felt homesick every Sunday night.', 'icon': 'compass'},
        {'word': 'Culture shock', 'def': 'The confusion people feel when they live in a very different culture for the first time', 'ex': 'The culture shock was not the language; it was dinner at six.', 'icon': 'globe'},
        {'word': 'A stipend', 'def': 'A fixed amount of money paid regularly to help a student with living costs', 'ex': 'The stipend covers rent, but not much more.', 'icon': 'coin'},
        {'word': 'To budget', 'def': 'To plan how much money you will spend on each thing', 'ex': 'If you do not budget, London eats your money in a week.', 'icon': 'chart'},
        {'word': 'A course load', 'def': 'The amount of work from all the classes a student is taking', 'ex': 'Law students usually have a heavy course load.', 'icon': 'book'},
        {'word': 'An elective', 'def': 'A course that a student chooses, not one that is required', 'ex': 'I took an elective on human rights and loved it.', 'icon': 'star'},
        {'word': 'Office hours', 'def': 'The times when a professor is available to talk to students', 'ex': 'Go to office hours in the first week, not the last.', 'icon': 'clock'},
        {'word': 'To fall behind', 'def': 'To fail to do work as fast as you should, so you have more to do later', 'ex': 'I missed two classes and fell behind with the reading.', 'icon': 'alert'},
        {'word': 'To make the most of', 'def': 'To use a situation or a chance in the best possible way', 'ex': 'Make the most of every weekend, because the semester ends fast.', 'icon': 'zap'},
        {'word': 'To look back on', 'def': 'To think about something that happened in the past', 'ex': 'When I look back on that year, I remember the people, not the exams.', 'icon': 'eye'},
    ],
    'pron_heading': "Say It Without <span class='accent'>Stopping</span>",
    'pron': ['Housing', 'A stipend', 'An elective', 'If I had gone to office hours earlier, I would not have fallen behind.'],
    'vocab_fill': [
        ('The university gives exchange students a room, so they do not have to look for ', 'housing', ' alone.'),
        ('In the first two weeks everything is new, and it takes time to ', 'settle in', '.'),
        ('She missed her family every weekend and felt very ', 'homesick', '.'),
        ('Life in London is expensive, so you have to ', 'budget', ' every month.'),
        ('I stopped reading for a week and started to ', 'fall behind', ' in two classes.'),
        ('You only have one semester there, so ', 'make the most of', ' it.'),
    ],
    'ch_grammar': {'heading': "The Year That Did Not <span class='accent'>Happen (Yet)</span>",
                   'sub': 'Four sentences about an exchange: one imagined, one regretted, one mixed'},
    'grammar': {
        'heading': "Imagined, or <span class='accent'>Regretted?</span>",
        'examples': [
            "If I <span style='color:#1d4ed8;font-weight:700'>were</span> in London now, I <span style='color:#1d4ed8;font-weight:700'>would go</span> to office hours in the first week.",
            "If he <span style='color:#b91c1c;font-weight:700'>had budgeted</span>, he <span style='color:#b91c1c;font-weight:700'>would not have spent</span> his stipend in a month.",
            "If I <span style='color:#b91c1c;font-weight:700'>had chosen</span> a lighter course load, I <span style='color:#1d4ed8;font-weight:700'>would be</span> less tired now.",
            "If she <span style='color:#1d4ed8;font-weight:700'>were</span> more organized, she <span style='color:#b91c1c;font-weight:700'>would not have fallen</span> behind last month.",
        ],
        'prompt': 'All four sentences are about things that are not real. Which ones imagine the present, which ones imagine the past, and which two mix a past cause with a present result, or a present fact with a past result? Look at the blue and red forms.',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Imagine the present or the future', 'if + past, would + base verb', 'If I <strong>were</strong> there, I <strong>would go</strong> to office hours.'),
            ('Imagine a different past (regret)', 'if + had + participle, would have + participle', 'If he <strong>had budgeted</strong>, he <strong>would not have spent</strong> it all.'),
            ('A past cause, a present result', 'if + had + participle, would + base verb', 'If I <strong>had chosen</strong> fewer classes, I <strong>would be</strong> less tired now.'),
            ('A present fact, a past result', 'if + past, would have + participle', 'If she <strong>were</strong> organized, she <strong>would not have fallen</strong> behind.'),
            ('Less certain', 'could / might in place of would', 'If I had asked, I <strong>might have</strong> gotten a better room.'),
            ('With be', 'If I were, formal and correct for every person', 'If I <strong>were</strong> you, I would apply now.'),
            ('The trap', 'never <em>would</em> in the if-clause', 'Not <em>If I would have known</em>. Say <strong>If I had known</strong>.'),
        ],
        'oneliner': 'Move each clause back in time to show it is not real: past for the present, had + participle for the past, and never would after if.',
    },
    'grammar_practice': {
        'heading': "Imagine It, <span class='accent'>Then Regret It</span>",
        'items': [
            ('If I ', 'were', ' in London now, I would go to office hours in the first week. (imagine the present)'),
            ('If he had budgeted, he ', 'would not have spent', ' his stipend in a month. (a different past)'),
            ('If she ', 'had known', ' about the elective, she would have taken it. (the if-clause, past)'),
            ('If I had chosen a lighter course load, I ', 'would be', ' less tired now. (past cause, present result)'),
            ('If I ', 'were', ' you, I would apply for housing before March. (advice)'),
            ('If we had asked earlier, we ', 'might have gotten', ' a room on campus. (less certain)'),
        ],
    },
    'ch4': {'heading': "Coffee With Somebody Who <span class='accent'>Went</span>",
            'sub': 'One conversation, two recordings, one welcome sheet'},
    'dialogue': {
        'heading': "What Theo Would <span class='accent'>Do Differently</span>",
        'guest_name': 'Theo', 'guest_initial': 'T',
        'lines': [
            ('u', 'Luiza! So you are really going to apply. Good. Ask me anything, because nobody told me the useful things.'),
            ('l', 'Okay. If you were starting your semester in London again tomorrow, what would you do first?'),
            ('u', 'I would sort out my <span class="vocab-highlight">housing</span> before anything else. I waited, and I ended up in a tiny room with a <span class="vocab-highlight">roommate</span> who never slept.'),
            ('l', 'That sounds terrible. Did it take you long to <span class="vocab-highlight">settle in</span>?'),
            ('u', 'About a month. The <span class="vocab-highlight">culture shock</span> was not the language, it was the rhythm. Dinner at six, pubs closed early, and I was <span class="vocab-highlight">homesick</span> every Sunday.'),
            ('l', 'And the classes? My brother said the <span class="vocab-highlight">course load</span> was heavier than at GV.'),
            ('u', 'He is right. If I had gone to <span class="vocab-highlight">office hours</span> in the first week, I would not have <span class="vocab-highlight">fallen behind</span> in two classes.'),
            ('l', 'And money? The <span class="vocab-highlight">stipend</span> does not look very generous.'),
            ('u', 'It is not. If I had learned to <span class="vocab-highlight">budget</span> earlier, I would still have some savings now. Honestly, I spent too much in the first month.'),
            ('l', 'Then I will learn from your mistakes. When you <span class="vocab-highlight">look back on</span> it, was it worth it?'),
            ('u', 'Completely. Just <span class="vocab-highlight">make the most of</span> it, and take one <span class="vocab-highlight">elective</span> that has nothing to do with law.'),
        ],
        'comp': [
            ('What would Theo do first if he started his semester again?', 'He would sort out his housing before anything else.'),
            ('What was the culture shock for Theo, and when did he feel homesick?', 'The rhythm, not the language: dinner at six and pubs closing early. He felt homesick every Sunday.'),
            ('Why did Theo fall behind, according to him?', 'Because he did not go to office hours in the first week.'),
            ('What is his final advice about electives?', 'To take one elective that has nothing to do with law.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Podcast', 'title': "What I Wish I <span class='accent'>Had Known</span>",
         'blurb': 'A student who came back from an exchange year. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'People ask me what I would change about my exchange year, and my answer surprises them. I would not choose a different city or a different university. I would change the first three weeks. I arrived thinking I would make friends in class, but in a big law school nobody talks in class. If I had joined a club in the first week, I would have met people much faster. The second thing is money. I did not budget, because the stipend looked like a lot in my currency, and by November I was eating pasta every night. And the third thing is the one I tell everyone. If you feel homesick, do not hide in your room. Go to one event, just one, even when you do not want to. That is how the culture shock ends.',
         'qs': [
             ('What does she say she would not change, and what would she change?', 'She would not change the city or the university. She would change the first three weeks.'),
             ('What does she say would have happened if she had joined a club in the first week?', 'She would have met people much faster.'),
             ('Why did she not budget, and what is her advice for students who feel homesick?', 'The stipend looked like a lot in her currency. Her advice is to go to one event instead of hiding in your room.'),
         ]},
        {'label': 'Listening 2 &middot; A Voicemail', 'title': "The Housing Office <span class='accent'>Calls</span>",
         'blurb': 'A message from a host university. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Hello, this is a message for incoming exchange students from the university housing office. We have had a lot of questions, so here is the short version. Rooms on campus are allocated in order of application, and last year every room was taken by the end of May. If you apply after that, you will have to find private housing, which is usually more expensive and further from the law school. When you apply, please tell us if you would prefer a single room or a shared room with a roommate. Shared rooms cost about thirty percent less. And one more thing. Your stipend will not arrive before you do, so plan to cover your first month of rent yourself. If you have questions, our office hours are Monday to Thursday, from ten to four.',
         'qs': [
             ('How are rooms on campus allocated, and what happened last year?', 'In order of application. Last year every room was taken by the end of May.'),
             ('What happens if a student applies too late, and how much less does a shared room cost?', 'They have to find private housing, usually more expensive and further away. A shared room costs about thirty percent less.'),
             ('What does he say about the stipend, and when are the office hours?', 'It will not arrive before the student, so they must pay the first month of rent themselves. Office hours are Monday to Thursday, ten to four.'),
         ]},
    ],
    'artifact': {
        'heading': "The Welcome Sheet in <span class='accent'>Your Inbox</span>",
        'title': 'EXCHANGE STUDENT WELCOME SHEET', 'subtitle': 'Partner Law School, London &middot; Incoming student: L. Sato Eccheli',
        'rows': [
            ('Campus housing', 'Apply by May 31 &mdash; single or shared room', True),
            ('Course load', 'Minimum 4 courses; at least 1 elective allowed', False),
            ('Stipend', 'First payment in week 3 &mdash; bring one month of rent', True),
            ('Academic advisor', 'Office hours: Tuesdays, 14:00&ndash;16:00', False),
            ('Orientation week', 'Clubs fair on day 2 &mdash; strongly recommended', False),
        ],
        'note': 'Student services note: most students who fall behind in the first month did not meet their academic advisor. Book a meeting in your first week, even if everything seems fine.',
        'qs': [
            ('What is the deadline for campus housing, and what choice does the student make?', 'May 31. The student chooses a single or a shared room.'),
            ('When does the first stipend payment arrive, and what does the sheet say to bring?', 'In week 3, so the student should bring one month of rent.'),
            ('According to the note, what do most students who fall behind have in common?', 'They did not meet their academic advisor in the first month.'),
        ],
    },
    'ch5': {'heading': "Train for the <span class='accent'>Year Abroad</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('If I would have known, I would have applied earlier.', 'If I <strong>had known</strong>, I would have applied earlier.'),
        ('If I am in London now, I would go to office hours.', 'If I <strong>were</strong> in London now, I would go to office hours.'),
        ('If he had budgeted, he would not spend all his stipend last month.', 'If he had budgeted, he <strong>would not have spent</strong> all his stipend last month.'),
        ('If I had chosen fewer classes, I would have been less tired now.', 'If I had chosen fewer classes, I <strong>would be</strong> less tired now.'),
    ],
    'speaking': [
        ('If you were starting your exchange tomorrow, what would you do first?', 'I would apply for housing before anything else, and I would go to office hours in the first week.'),
        ('What would you have done differently in Scotland, if you could go back?', 'If I had known how short a month was, I would have spoken to more people and made the most of every weekend.'),
        ('How would you avoid falling behind with a heavy course load?', 'I would read a little every day, and if I felt lost, I would go to office hours instead of waiting.'),
        ('If you could take one elective abroad, what would it be?', 'I would take something that has nothing to do with law, maybe art history, because I would never do it at GV.'),
    ],
    'building': [
        ('I / be / in London now / go to office hours (imagine the present)', 'If I were in London now, I would go to office hours.'),
        ('he / budget / not spend his stipend in a month (a different past)', 'If he had budgeted, he would not have spent his stipend in a month.'),
        ('I / choose a lighter course load / be less tired now (past cause, present result)', 'If I had chosen a lighter course load, I would be less tired now.'),
        ('I / be / you / apply for housing before May (advice)', 'If I were you, I would apply for housing before May.'),
    ],
    'roleplays': {
        'heading': "The Same Coffee, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Theo Asks <span class='accent'>You</span>",
             'scenario': 'Now Theo asks you: if you were abroad tomorrow, what would you do first, how would you budget, and which elective would you take? Answer each question in two sentences with a second conditional.',
             'chips': ['If I were', 'housing', 'to budget', 'an elective']},
            {'heading': "The Month in <span class='accent'>Scotland</span>",
             'scenario': 'Tell your teacher about your month in Scotland: one thing you would have done differently, one thing that went well, and one way that month still affects you now. Use a third conditional and a mixed conditional.',
             'chips': ['If I had known', 'I would be', 'culture shock', 'to settle in']},
            {'heading': "Advice in <span class='accent'>Two Minutes</span>",
             'scenario': 'A younger student at GV is thinking about the exchange. Give advice in two minutes: what they should do before they go, what you would do in the first week, and what they will look back on.',
             'footer': 'No notes, two minutes. Use If I were you at least once, and do not stop when a word does not come.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for <span class='accent'>the Year Abroad</span>", 'sub': 'What you take with you'},
    'survival_heading': "Five Sentences for <span class='accent'>the Year Abroad</span>",
    'survival': [
        'If I were starting tomorrow, I would sort out my housing first.',
        'If he had gone to office hours earlier, he would not have fallen behind.',
        'If I had budgeted in the first month, I would still have some savings now.',
        'If I were you, I would take one elective that has nothing to do with law.',
        'When I look back on that month, I remember the people, not the classes.',
    ],
    'checklist': [
        'I can imagine a different present with if + past and would.',
        'I can talk about a regret with if + had + participle and would have.',
        'I can mix a past cause with a present result.',
        'I never use would in the if-clause.',
        'I know the words: housing, a roommate, to settle in, homesick, culture shock, a stipend, to budget, a course load, an elective, office hours, to fall behind, to make the most of, to look back on.',
    ],
    'badge': {'name': 'The Year Abroad', 'line': 'What you would do, what others wish they had done, and what you will do because of it.',
              'next': 'Next lesson: How the TOEFL Reads You -- the reading section and the art of inference'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we plan your year abroad, and we learn from somebody who already made the mistakes.\' Contexto: o irmao dela fez o mesmo intercambio da GV e hoje mora em Londres; ela passou um mes na Escocia. E tema de energia alta para ela: deixe falar muito. Correcao em bloco, no fim de cada atividade.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta sobre a Escocia. Callback das aulas 1 a 4: exija uma palavra da candidatura (a host university, a semester abroad, to keep up with) e um verbo de relato (\'my brother told me that...\'). ANOTE se ela ja usa \'would\' sozinha e se aparece \'if I would\' &mdash; e o erro que a aula ataca.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos: imaginar, lamentar, decidir. Nao de a regra ainda. Diga que o Take an Interview do TOEFL novo faz exatamente perguntas hipoteticas como estas.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Sessenta segundos, cronometrado. ANOTE a frase condicional exata que ela produziu e se usou \'would\' no lugar certo. Compare com o role-play livre.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words that every exchange student uses in the first month.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'housing\': incontavel &mdash; nunca \'a housing\' nem \'housings\'; e a palavra americana (o britanico diz accommodation). CCQ \'to settle in\': \'Is it the first day, or after some time? (Depois de um tempo.)\' CCQ \'homesick x culture shock\': \'Which one is about missing home, and which one about a different culture? \' Pronuncia: HOU-sing, com /z/.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a stipend\': \'Is it a salary for a job? (Nao, ajuda de custo para estudante.)\' CCQ \'a course load\': \'Is it one class or all of them? (Todas.)\' CCQ \'an elective\': \'Do you have to take it? (Nao.)\' \'Office hours\' e sempre plural.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'to fall behind\': \'Are you ahead or late with the work? (Atrasada.)\' CCQ \'to make the most of\': \'Is it a waste or the best use? (Melhor uso.)\' CCQ \'to look back on\': \'Past or future? (Passado.)\'',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> HOU-sing (com /z/), STI-pend, e-LEC-tive. Na frase longa, dois blocos com a pausa na virgula: \'If I had gone to office hours earlier / I would not have fallen behind.\' Cobre as contracoes na fala: I would have vira I\'d have, e would not have vira wouldn\'t have. Se travar, recomeca o bloco.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ela diz a palavra ANTES de clicar, escolhendo do banco. Se fechar rapido, peca uma frase com \'homesick\' sobre a Escocia.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about a year abroad. None of them is real. Which ones imagine, and which ones regret?\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Which sentence imagines the present? Which one regrets the past? Which two mix them?\' Espere ela ver. So entao Reveal the Rule. CCQ: \'If I were in London now &mdash; am I in London? (Nao.)\' CCQ: \'If he had budgeted &mdash; did he budget? (Nao.) Is it too late? (Sim.)\' CCQ misto: \'If I had chosen fewer classes, I would be less tired now &mdash; when was the choice, and when is the tiredness? (Passado; agora.)\' Obstaculo numero um do brasileiro: \'if I would have known\' (calco de \'se eu tivesse sabido\' com o would do portugues coloquial).',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na quarta (misto), pergunte de novo quando e a causa e quando e o resultado. Na quinta, peca um conselho real dela para um calouro.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now coffee with somebody who already went, two recordings, and the welcome sheet from a host university.\'',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e o Theo: veterano da GV que voltou de um semestre em Londres, sincero e bem-humorado. Clique Next Line e toque o audio. Nas falas da Luiza, ela fala PRIMEIRO. PRAGMATICA para comentar: o Theo nunca da conselho seco; ele conta o erro dele com condicional (\'If I had gone...\'). E a forma mais natural de aconselhar sem parecer arrogante.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre o LUCAS, nunca sobre a Luiza (REGRA 27F). Depois pergunte se o irmao dela contou algo parecido.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Depois peca que ela resuma os tres conselhos em trinta segundos (aula 3) com reported speech.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Recado de voz, voz masculina, com numeros e datas. Cobre os numeros exatos: e o tipo de detalhe que o listening do TOEFL cobra. Os dados sao ficticios, escritos para a aula.',
        'artifact': '<strong>Artefato (4 min):</strong> Folha de boas-vindas ficticia, com o nome dela. Peca que ela transforme cada linha em conselho condicional: \'If I were you, I would apply for housing before May.\' So depois as 3 perguntas.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\'',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Os quatro erros: would na if-clause, presente no lugar de were, resultado passado sem have, e resultado presente com have (misto errado). Enquadramento: \'os mais comuns\'.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas como o Theo faria. Respostas na tela sao sugestao. A segunda e sobre a Escocia real dela: deixe contar a historia inteira antes de corrigir. Correcao em bloco, no fim, no maximo tres pontos.',
        'building': '<strong>Sentence Building (4 min):</strong> Ela monta a frase COMPLETA em voz alta antes de clicar, num bloco so com pausa na virgula.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same coffee, three times. The last one is you giving advice.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o Theo perguntando. Tres perguntas, duas frases por resposta, uma segunda condicional em cada. Corrija so o would na if-clause, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Ela conta a Escocia real com uma terceira condicional e uma mista. Conteudo real primeiro; se ela so conseguir a terceira, ajude a montar a mista no fim com a propria historia dela.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota. Cronometre. No fim, dois numeros: quantas vezes recomecou uma frase (compare com as aulas anteriores) e quantas condicionais usou.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you imagined your first week. Now you have five sentences, and somebody else&rsquo;s mistakes to avoid.\'',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete com as contracoes naturais da fala (I\'d, wouldn\'t have).',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 5. Item em que ela hesitar entra no warm-up da aula 6.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the best advice about a year abroad always starts with if I had known.\' Homework (ORALMENTE, nunca escrito na tela): perguntar ao irmao, em ingles se possivel, o que ele faria diferente no intercambio, e trazer tres respostas dele em reported speech com condicional. Proxima aula: como o TOEFL le voce, a secao de reading.',
    },
    'pc': {
        'title': 'A Semester Abroad -- Imagining and Regretting',
        'desc': 'What you would do in your first week abroad, and what a friend wishes he had done in his.',
        'match_idx': [0, 2, 4, 5, 9, 10],
        'context': [
            'Almost every conversation about an exchange year uses sentences that are not real. Students imagine a year that has not started, and people who came back describe a year that could have been different. English shows that a sentence is not real by moving its verbs one step back in time.',
            'To imagine the present or the future, use <strong>if</strong> + past and <strong>would</strong>: &ldquo;If I <strong>were</strong> in London now, I <strong>would go</strong> to <strong>office hours</strong> in the first week.&rdquo; With <em>be</em>, English uses <strong>were</strong> for every person in careful speech, and &ldquo;If I were you&rdquo; is the classic way to give advice.',
            'To talk about a different past, the regret, use <strong>if</strong> + <strong>had</strong> + participle and <strong>would have</strong> + participle: &ldquo;If he <strong>had budgeted</strong>, he <strong>would not have spent</strong> his <strong>stipend</strong> in a month.&rdquo; The most common mistake is to put <em>would</em> in the if-clause, as in &ldquo;if I would have known&rdquo;. English never does that.',
            'Real life often mixes the two. A choice in the past can change the present: &ldquo;If I <strong>had chosen</strong> a lighter <strong>course load</strong>, I <strong>would be</strong> less tired now.&rdquo; And a fact that is true now can explain a past result: &ldquo;If she <strong>were</strong> more organized, she <strong>would not have fallen behind</strong>.&rdquo; Once you control these forms, you can <strong>make the most of</strong> other people&rsquo;s mistakes before you make your own.',
        ],
        'context_quiz': [
            ('According to the text, how does English show that a sentence is not real?', ['By using the future tense.', 'By moving the verbs one step back in time.', 'By adding the word maybe.'], 1),
            ('Which sentence does the text say is always wrong?', ['If I would have known, I would have applied.', 'If I were you, I would apply.', 'If he had budgeted, he would have saved.'], 0),
            ('What does &ldquo;If I had chosen a lighter course load, I would be less tired now&rdquo; show?', ['A regret with a past result.', 'A plan for the future.', 'A past choice with a present result.'], 2),
        ],
        'tip_title': 'Second, Third and Mixed Conditionals',
        'tip_lead': 'Past for an imagined present, had + participle for an imagined past, and never would after if.',
        'tip_rows': [
            ('Imagined present', 'if + past, would + verb', 'If I <strong>were</strong> there, I <strong>would go</strong>.'),
            ('Imagined past', 'if + had + participle, would have + participle', 'If he <strong>had budgeted</strong>, he <strong>would have saved</strong>.'),
            ('Past cause, present result', 'if + had + participle, would + verb', 'If I <strong>had chosen</strong> fewer classes, I <strong>would be</strong> less tired.'),
            ('Present fact, past result', 'if + past, would have + participle', 'If she <strong>were</strong> organized, she <strong>would not have fallen</strong> behind.'),
            ('Advice', 'If I were you, I would + verb', '<strong>If I were you</strong>, I would apply now.'),
            ('Less certain', 'might / could', 'We <strong>might have gotten</strong> a room.'),
        ],
        'tip_never': 'if I would have known &middot; if I am in London now, I would go &middot; he would not spend it last month &middot; I would have been less tired now',
        'blanks': [
            ('If I ', 'were', ' in London now, I would go to office hours in the first week.', 'Hint: be, for an imagined present -- one word', None),
            ('If he ', 'had budgeted', ', he would not have spent his stipend in a month.', 'Hint: the if-clause of a regret -- two words', None),
            ('If I had known about the elective, I ', 'would have taken', ' it.', 'Hint: the result of a regret -- three words', None),
            ('If I had chosen a lighter course load, I ', 'would be', ' less tired now.', 'Hint: past cause, present result -- two words', None),
            ('It took me a month to ', 'settle in', ' after I arrived.', 'Hint: start to feel comfortable in a new place -- two words', None),
            ('Life abroad is expensive, so you have to ', 'budget', ' carefully.', 'Hint: plan how you spend your money -- one word', None),
        ],
        'order_title': 'Put the Advice in Order',
        'order_lead': 'A younger student asks for advice about the exchange. Put your answer in a logical order.',
        'order': [
            'If I were you, I would apply for housing before May.',
            'A friend waited, and he ended up in a tiny room far from campus.',
            'In the first week, go to office hours, even if everything seems fine.',
            'If he had done that, he would not have fallen behind in two classes.',
            'Budget from the first day, because the stipend arrives late.',
            'And make the most of it, because the semester ends very fast.',
        ],
        'quiz': [
            ('A friend asks what you would do if you started your exchange tomorrow. You say:', ['If I start tomorrow, I would apply for housing.', 'If I started tomorrow, I would apply for housing first.', 'If I would start tomorrow, I apply for housing.'], 1),
            ('You want to talk about a regret from your month in Scotland. You say:', ['If I had known, I would have spoken to more people.', 'If I would have known, I would speak to more people.', 'If I knew, I would have spoken to more people last year.'], 0),
            ('You want to give advice to a younger student. You say:', ['If I am you, I would apply now.', 'If I would be you, I apply now.', 'If I were you, I would apply now.'], 2),
            ('You missed classes and now you have too much reading. You say:', ['I fell behind in two classes.', 'I fell back in two classes.', 'I stayed behind in two classes.'], 0),
        ],
        'think': 'Imagine you are starting your exchange semester next month. In ninety seconds, say what you would do in your first week, one mistake somebody you know made and what would have happened if they had done it differently, and what you think you will look back on. Use at least one second, one third and one mixed conditional.',
    },
    'media': [
        {'id': 'series', 'type': 'Series', 'title': 'Emily in Paris &mdash; Season 1, Episode 1, &ldquo;Emily in Paris&rdquo;',
         'desc': 'An American who moves abroad for a year and gets every piece of culture shock on the first day. Light, fast, and full of the language of settling in.',
         'tip': 'Tip: every time Emily makes a mistake, say what she would have done if she had known, in one sentence.',
         'url': 'https://www.tvmaze.com/episodes/1922969/emily-in-paris-1x01-emily-in-paris', 'cta': 'See the episode on TVmaze'},
        {'id': 'video', 'type': 'Video', 'title': 'Utah State University &mdash; &ldquo;Study Abroad Culture Shock &amp; Reverse Culture Shock&rdquo; (YouTube)',
         'desc': 'Real students talking about the culture shock of going abroad and the surprise of coming home. Natural, unscripted American English at normal speed.',
         'tip': 'Tip: choose one student and report what they said in three sentences, with at least one conditional.',
         'url': 'https://www.youtube.com/watch?v=8-ZHA7ZQIgM', 'cta': 'Watch on YouTube'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Chimamanda Ngozi Adichie &mdash; &ldquo;The danger of a single story&rdquo; (TED)',
         'desc': 'A novelist on what happens when we know only one story about a place or a people. Essential before you live in another country, and beautifully clear English.',
         'tip': 'Tip: pause after her story about her American roommate and say what the roommate would have thought if she had known more.',
         'url': 'https://www.ted.com/talks/chimamanda_ngozi_adichie_the_danger_of_a_single_story', 'cta': 'Watch on TED'},
    ],
}
