# -*- coding: utf-8 -*-
# Aula 8 -- The Fine Print You Already Signed (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The Fine Print You <span class='accent'>Already Signed</span>",
    'hero_line': 'The terms of the apps on your phone, and the modals that decide what you must, may and may not do',
    'menu_desc': 'The terms of service nobody reads, and the modals of obligation and permission in legal English -- 35 slides',
    'grammar_point': 'modals of obligation and permission in legal language',
    'phases': ['The Click', 'Words of the Contract', 'The Text Itself', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'daniel', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1450101499163-c8848c66ca85?w=1400&q=80',
        'ch2': U + 'photo-1486312338219-ce68d2c6f44d?w=1400&q=80',
        'ch3': U + 'photo-1454165804606-c3d57bc86b40?w=1400&q=80',
        'ch_grammar': U + 'photo-1505664194779-8beaceb93744?w=1400&q=80',
        'ch5': U + 'photo-1519389950473-47ba0277781c?w=1400&q=80',
        'ch_rp': U + 'photo-1517048676732-d65bc937f952?w=1400&q=80',
        'pc': U + 'photo-1450101499163-c8848c66ca85?w=600&q=80',
    },
    'warmup': {
        'heading': "The Last Time You Clicked <span class='accent'>I Agree</span>",
        'sub': 'Which app did you accept terms for recently, maybe for delivery or streaming? Did you read anything, and what do you think you agreed to?',
    },
    'target': {
        'heading': "Read a Contract Like a <span class='accent'>Law Student</span>",
        'steps': [
            'Find what you must do, and what the company must do.',
            'Find what you may do, and what you may not do.',
            'Find the clause that says who pays when something goes wrong.',
        ],
    },
    'diagnostic': {
        'heading': "Your Order Arrived <span class='accent'>Cold</span>",
        'p1': 'Your food delivery arrives two hours late and cold. The app says: &ldquo;Under our terms of service, we are not responsible for delays.&rdquo;',
        'p2': 'Is the app right? Answer in three sentences, as a law student, and say what you would want to check in the terms.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Contract</span>",
            'sub': 'Thirteen words from every terms of service, including the ones on your phone'},
    'vocab': [
        {'word': 'Terms of service', 'def': 'The rules a user must accept in order to use a website or an app', 'ex': 'Nobody reads the terms of service before clicking I agree.', 'icon': 'doc'},
        {'word': 'The fine print', 'def': 'The small, detailed part of a contract that people often do not read', 'ex': 'The fee was hidden in the fine print.', 'icon': 'eye'},
        {'word': 'Liability', 'def': 'Legal responsibility for something, especially for damage or loss', 'ex': 'The company tried to limit its liability for late deliveries.', 'icon': 'scale'},
        {'word': 'To waive', 'def': 'To officially give up a right or a claim', 'ex': 'By accepting, users waive the right to a class action.', 'icon': 'hand'},
        {'word': 'Consent', 'def': 'Permission for something to happen, given freely', 'ex': 'The app cannot share your location without your consent.', 'icon': 'key'},
        {'word': 'To opt out', 'def': 'To choose not to take part in something', 'ex': 'You can opt out of marketing emails in the settings.', 'icon': 'filter'},
        {'word': 'To terminate', 'def': 'To officially end an agreement', 'ex': 'The company may terminate your account if you break the rules.', 'icon': 'lock'},
        {'word': 'A dispute', 'def': 'A serious disagreement, especially one that goes to a court or an arbitrator', 'ex': 'Any dispute will be decided under Brazilian law.', 'icon': 'message'},
        {'word': 'Arbitration', 'def': 'A way to settle a dispute outside court, with a private decision maker', 'ex': 'The contract says every dispute goes to arbitration.', 'icon': 'users'},
        {'word': 'A third party', 'def': 'A person or a company that is not one of the two sides of an agreement', 'ex': 'Your data may be shared with a third party for payment.', 'icon': 'link'},
        {'word': 'Void', 'def': 'Describes a clause or a contract that has no legal effect', 'ex': 'A clause that removes all liability can be void under consumer law.', 'icon': 'alert'},
        {'word': 'To be entitled to', 'def': 'To have the right to have or to do something', 'ex': 'You are entitled to a refund if the order never arrives.', 'icon': 'star'},
        {'word': 'A refund', 'def': 'Money that is paid back to you, for example when a product or service fails', 'ex': 'I asked for a refund, and it arrived in five days.', 'icon': 'coin'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['Liability', 'Arbitration', 'To be entitled to', 'The user may opt out, but the company shall not share data without consent.'],
    'ch3': {'heading': "The Contract on <span class='accent'>Your Phone</span>",
            'sub': 'Four short paragraphs. Read once for the argument; the detail comes after.'},
    'reading': {
        'heading': "Nobody Reads It, <span class='accent'>Everybody Signs It</span>",
        'rtitle': 'Nobody Reads It, Everybody Signs It',
        'paras': [
            'Most people accept dozens of contracts every year without reading a single line. Every time you open a new app and click I agree, you accept its terms of service, and those terms usually describe your rights and obligations more precisely than any conversation with the company ever will. The fine print is not decoration. It is the contract.',
            'Terms of service are written in a particular kind of English. Obligations are marked with shall and must: the user shall keep the password secret; the company must protect personal data. Permissions are marked with may: the company may change the price, and you may cancel at any time. Prohibitions use may not or shall not, and the difference between may and must is often the difference between an option and a duty.',
            'Two kinds of clauses deserve more attention than the rest. The first limits the company&rsquo;s liability, for example by saying that it is not responsible for delays or errors. The second decides where a dispute will be resolved: in a court, or in private arbitration, sometimes in another country. Some terms also ask users to waive rights they did not know they had, such as the right to join other consumers in a collective case.',
            'However, a contract is not stronger than the law. In many countries, including Brazil, consumer law protects users from abusive clauses, and a clause that removes all of a company&rsquo;s liability for its own failures can be void. Personal data also cannot simply be shared with a third party without a legal basis, and in many cases that basis is the user&rsquo;s consent. So the next time an app says you are not entitled to a refund, the honest answer is: that depends on what the law says, not only on what you clicked.',
        ],
        'source': 'Written for this lesson, from the general structure of consumer terms of service and the principles of consumer and data protection law.',
    },
    'gist': {
        'prompt': 'What is the main argument of the text?',
        'choices': [
            ['a', 'Users should never accept terms of service, because every clause is abusive.', False],
            ['b', 'Terms of service are real contracts written in precise legal language, but they cannot override consumer law.', True],
            ['c', 'Arbitration is always better for consumers than going to court.', False],
        ],
    },
    'tf': [
        ['According to the text, the fine print is only decoration.', 'f', 'The text says the fine print is not decoration; it is the contract.'],
        ['In terms of service, may usually marks a permission, and must marks a duty.', 't', 'The text says permissions are marked with may, and obligations with shall and must.'],
        ['The text says every dispute must be resolved in a public court.', 'f', 'The text says a clause may send disputes to a court or to private arbitration.'],
        ['A clause that removes all of a company&rsquo;s liability can be void under consumer law.', 't', 'The text says such a clause can be void in many countries, including Brazil.'],
        ['According to the text, clicking I agree always decides whether you are entitled to a refund.', 'f', 'The text says it depends on what the law says, not only on what you clicked.'],
    ],
    'artifact': {
        'heading': "The Update You <span class='accent'>Scrolled Past</span>",
        'title': 'TERMS OF SERVICE &mdash; SUMMARY OF CHANGES', 'subtitle': 'Food delivery app &middot; Account: L. Sato Eccheli',
        'rows': [
            ('Late deliveries', 'We may offer a credit; refunds only if the order never arrives', True),
            ('Personal data', 'May be shared with third parties for payment and delivery', False),
            ('Marketing', 'You may opt out at any time in Settings', False),
            ('Disputes', 'Shall be resolved by arbitration', True),
            ('Account', 'We may terminate accounts that break these terms', False),
        ],
        'note': 'By continuing to use the app after 30 days, you consent to these changes. If you do not agree, you may close your account before that date.',
        'qs': [
            ('What does the app promise for late deliveries, and when is a refund offered?', 'It may offer a credit. A refund is offered only if the order never arrives.'),
            ('Which change uses shall, and what does that mean for the user?', 'Disputes shall be resolved by arbitration, so arbitration is an obligation, not an option.'),
            ('According to the note, how does a user consent to the changes, and what can a user who does not agree do?', 'By continuing to use the app after 30 days. A user who does not agree may close the account before that date.'),
        ],
    },
    'ch_grammar': {'heading': "Must, May, <span class='accent'>May Not</span>",
                   'sub': 'Four clauses from real-looking terms, and the one word that turns an option into a duty'},
    'grammar': {
        'heading': "An Option, or <span class='accent'>a Duty?</span>",
        'examples': [
            "The user <span style='color:#b91c1c;font-weight:700'>shall</span> keep the password confidential.",
            "The company <span style='color:#1d4ed8;font-weight:700'>may</span> change the delivery fee at any time.",
            "Users <span style='color:#b91c1c;font-weight:700'>may not</span> share their account with a third party.",
            "Customers <span style='color:#1d4ed8;font-weight:700'>are entitled to</span> a refund if the order never arrives.",
        ],
        'prompt': 'In each clause, who has a duty, who has a choice, and who has a right? Which words make it a duty, and which make it only an option? And what changes when you add not?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('A duty, in formal legal texts', 'shall + base verb', 'The user <strong>shall</strong> keep the password confidential.'),
            ('A duty, in everyday and legal English', 'must / is required to + base verb', 'The company <strong>must</strong> protect personal data.'),
            ('A permission or an option', 'may + base verb', 'You <strong>may</strong> cancel at any time.'),
            ('A prohibition', 'may not / shall not / is prohibited from + -ing', 'Users <strong>may not</strong> share their account.'),
            ('A right', 'is entitled to + noun / verb', 'Customers <strong>are entitled to</strong> a refund.'),
            ('No duty', 'is not required to / does not have to', 'You <strong>are not required to</strong> give your phone number.'),
            ('The trap', 'must not &ne; does not have to', '<strong>You must not</strong> share it (forbidden). <strong>You do not have to</strong> share it (optional).'),
        ],
        'oneliner': 'Shall and must create duties, may creates options, may not forbids, and must not is never the same as do not have to.',
    },
    'grammar_practice': {
        'heading': "Duty, Option, <span class='accent'>or Right?</span>",
        'items': [
            ('The user ', 'shall', ' keep the password confidential. (a formal duty)'),
            ('You ', 'may', ' cancel your subscription at any time. (an option)'),
            ('Users ', 'may not', ' share their accounts with a third party. (a prohibition)'),
            ('Customers ', 'are entitled to', ' a refund if the order never arrives. (a right)'),
            ('You ', 'are not required to', ' give your phone number to create an account. (no duty)'),
            ('Users ', 'are prohibited from', ' reselling the service. (a prohibition, with -ing)'),
        ],
    },
    'detective': [
        ('You must not give your phone number; it is optional.', 'You <strong>do not have to</strong> give your phone number; it is optional.'),
        ('Users may to cancel at any time.', 'Users <strong>may cancel</strong> at any time.'),
        ('Customers are entitled of a refund.', 'Customers are entitled <strong>to</strong> a refund.'),
        ('Users are prohibited to resell the service.', 'Users are prohibited <strong>from reselling</strong> the service.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>",
            'sub': 'Legal clauses and plain English &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Terms in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each clause to the same idea in plain English',
        'hint': 'Tap a clause, then tap the sentence that means the same',
        'pairs': [
            ('The Company shall not be liable for delays caused by third parties.', 'The app says it will not pay if another company makes the delivery late.'),
            ('The User may terminate this Agreement at any time.', 'You can close your account whenever you want.'),
            ('Any dispute arising from these Terms shall be resolved by arbitration.', 'If you disagree with the app, a private arbitrator decides, not a court.'),
            ('The User waives the right to participate in a class action.', 'You give up the right to join other users in a collective case.'),
            ('Continued use of the Service constitutes consent to these Terms.', 'If you keep using the app, you agree to the rules.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Seminar Summary</span>",
    'gap': {
        'parts': [
            'Most users never read the ', ['1', 'terms of service'], ' of the apps they use, and the most important rules are often in ',
            ['2', 'the fine print'], '. One clause usually limits the company&rsquo;s ', ['3', 'liability'],
            ' for delays, and another sends every ', ['4', 'dispute'], ' to ', ['5', 'arbitration'],
            ' instead of a court. Some terms even ask users to ', ['6', 'waive'],
            ' rights they did not know they had. But consumer law still applies: an abusive clause can be ', ['7', 'void'],
            ', and a user who never received the order may be ', ['8', 'entitled to'], ' a refund.',
        ],
        'bank': ['terms of service', 'the fine print', 'liability', 'dispute', 'arbitration', 'waive', 'void', 'entitled to'],
    },
    'quickfire': [
        {'situation': 'A friend says the app is right to refuse a refund, because she clicked I agree. Answer in two sentences.', 'tips': ['Not necessarily. A contract cannot remove rights that consumer law gives you, so an abusive clause can be void.', 'Use can be void and entitled to.']},
        {'situation': 'Explain the difference between you must not and you do not have to.', 'tips': ['You must not means it is forbidden; you do not have to means it is optional.', 'must not is a prohibition; do not have to is no duty.']},
        {'situation': 'Tell a classmate how to stop marketing emails from an app.', 'tips': ['You can opt out in the settings; you are not required to receive them.', 'opt out, are not required to.']},
        {'situation': 'Explain what arbitration is, without using the word arbitration.', 'tips': ['It is a way to resolve a dispute outside court, where a private person makes the decision.', 'A relative clause: where a private person decides.']},
        {'situation': 'Rewrite this rule in legal English: you cannot share your account.', 'tips': ['Users may not share their account with any third party.', 'may not, a third party.']},
        {'situation': 'Say what the app may do with your data, according to the update.', 'tips': ['The app may share personal data with third parties, but only for payment and delivery.', 'may + base verb, with a limit.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Consumer Lawyer', 'title': "Three Clauses <span class='accent'>Worth Reading</span>",
         'blurb': 'A consumer lawyer on how to read terms of service in five minutes. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Nobody is going to read forty pages of terms before ordering dinner, and I would never ask you to. But there are three clauses I always read, and you can find them in five minutes with the search function. First, look for the word liable. That clause tells you what the company says it will not pay for. Second, look for dispute or arbitration. That tells you where you will have to go if something goes wrong, and sometimes it is another country. Third, look for share or third parties. That tells you who else receives your data. And remember that finding a clause is not the same as accepting it. If a clause says the company is never responsible for anything, a court may decide that it is void. The contract is important, but it is not the only thing that protects you.',
         'qs': [
             ('Why does the lawyer say she would never ask you to read all the terms?', 'Because nobody is going to read forty pages before ordering dinner.'),
             ('What are the three words or ideas she searches for, and what does each clause tell you?', 'Liable: what the company will not pay for. Dispute or arbitration: where you have to go if something goes wrong. Share or third parties: who else receives your data.'),
             ('What can a court decide about a clause that says the company is never responsible?', 'That it is void.'),
         ]},
        {'label': 'Listening 2 &middot; An App Notice', 'title': "We Have Updated <span class='accent'>Our Terms</span>",
         'blurb': 'An app notice read aloud. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'We have updated our terms of service, and we want to explain the most important changes in plain language. Starting next month, if your order arrives more than forty-five minutes late, you may receive a credit for your next order. You are entitled to a full refund only if the order never arrives. We may share some personal data with payment and delivery partners, but we shall not sell your data to advertisers. You may opt out of marketing messages at any time, and you are not required to give us your birthday. Finally, disputes that cannot be solved by our support team shall be resolved by arbitration. If you continue to use the app after thirty days, you consent to these changes. If you do not agree, you may close your account before then.',
         'qs': [
             ('What may a user receive if an order is more than forty-five minutes late, and when is a full refund given?', 'A credit for the next order. A full refund only if the order never arrives.'),
             ('What will the app share, and what does it promise it will not do?', 'Some personal data with payment and delivery partners. It shall not sell data to advertisers.'),
             ('What happens to disputes the support team cannot solve, and how does a user consent to the changes?', 'They are resolved by arbitration. A user consents by continuing to use the app after thirty days.'),
         ]},
    ],
    'roleplays': {
        'heading': "The Same Contract, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Explain the <span class='accent'>Update</span>",
             'scenario': 'Your friend received the app update and did not read it. Explain three changes: one duty, one option and one right, using shall, may and entitled to.',
             'chips': ['may offer a credit', 'is entitled to', 'shall be resolved', 'to opt out']},
            {'heading': "The Refund <span class='accent'>Argument</span>",
             'scenario': 'Your delivery never arrived, and the support agent says you are not entitled to a refund under the terms. Disagree politely, explain why the clause may not protect the company, and ask for a clear solution.',
             'chips': ['a refund', 'liability', 'void', 'consumer law']},
            {'heading': "Two Minutes, <span class='accent'>No Notes</span>",
             'scenario': 'Explain to a first-year law student why terms of service matter, which three clauses are worth reading, and what a user can do when a clause seems abusive.',
             'footer': 'No notes, two minutes. Use must, may and may not at least once each.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>Any Contract</span>",
    'survival': [
        'The fine print is not decoration; it is the contract.',
        'The user shall keep the password confidential, but may cancel at any time.',
        'You must not share your account, but you do not have to give your phone number.',
        'A clause that removes all liability can be void under consumer law.',
        'If the order never arrives, the customer is entitled to a refund.',
    ],
    'checklist': [
        'I can find the liability, dispute and data clauses in a terms of service.',
        'I use shall and must for duties, may for options and may not for prohibitions.',
        'I know that must not and do not have to mean different things.',
        'I can explain a legal clause in plain English.',
        'I know the words: terms of service, the fine print, liability, to waive, consent, to opt out, to terminate, a dispute, arbitration, a third party, void, to be entitled to, a refund.',
    ],
    'badge': {'name': 'The Fine Print Reader', 'line': 'What you must do, what you may do, and what no clause can take away from you.',
              'next': 'Next lesson: Forty-Five Seconds of Opinion -- giving your view with reasons, in conversation'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we read the contract that is already on your phone.\' Contexto: ela disse que gosta de pedir iFood &mdash; o texto usa um app de delivery generico, sem nomear empresa real. E Direito do Consumidor encontrando o ingles juridico: registro que ela vai precisar no intercambio. Texto curto, velocidade.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta. Callback das aulas 6 e 7: exija um modal de deducao (\'I must have accepted it...\') e uma causativa (\'I had my account deleted\'). Deixe ela contar de algum app real.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Diga que contrato em ingles gira em torno de poucas palavras: shall, must, may, may not. Nao de a regra ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Ela argumenta como estudante de Direito em tres frases. Se ela citar o CDC, otimo: cobre o ingles (\'consumer law\', \'abusive clause\'). ANOTE se ela confunde must not com don\'t have to.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words from every terms of service.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'the fine print\': \'Big letters or small details? (Detalhes pequenos.)\' CCQ \'liability\': \'Is it a right or a responsibility? (Responsabilidade.)\' CCQ \'to waive\': \'Do you get a right or give one up? (Abre mao.)\' Pronuncia: li-a-BIL-i-ty.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'to opt out\': \'Joining or not joining? (Nao participar.)\' CCQ \'arbitration\': \'A public court or a private decision maker? (Privado.)\' CCQ \'a third party\': \'One of the two sides, or someone outside? (De fora.)\' Pronuncia: ar-bi-TRA-tion.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'void\': \'Does the clause still work? (Nao, nula.)\' CCQ \'to be entitled to\': \'Is it a favor or a right? (Direito.)\' Cobre a preposicao TO.',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> li-a-BIL-i-ty, ar-bi-TRA-tion, en-TI-tled. Na frase longa, dois blocos: \'The user may opt out / but the company shall not share data without consent.\'',
        'matching': '<strong>Matching (3 min):</strong> Ela liga palavra e definicao. Se errar, volte ao CCQ.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'Four paragraphs. Skim first: I will stop you after two minutes.\'',
        'reading': '<strong>Leitura (5 min):</strong> Dois minutos de skim cronometrado (tecnica da aula 6), pergunte a ideia central, depois segunda leitura para detalhe. Anote o tempo e compare com as aulas 2, 4 e 6.',
        'gist': '<strong>Gist (3 min):</strong> Ela escolhe e elimina as outras duas em voz alta.',
        'tf': '<strong>True or False (6 min):</strong> Ela diz TRUE ou FALSE e LE a linha que prova antes de clicar.',
        'artifact': '<strong>Artefato (4 min):</strong> Resumo ficticio de atualizacao de termos, com o nome dela. Peca que ela classifique cada linha: dever, opcao, direito ou proibicao. So depois as 3 perguntas. A nota do fim (consentimento por uso continuado) e um bom gancho para discutir com ela se isso seria valido no Brasil.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four clauses. One word in each one decides if it is a duty, an option or a right.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Who has a duty, who has a choice, who has a right?\' Espere ela ver shall/may/may not/entitled to. So entao Reveal the Rule. CCQ: \'The company may change the fee &mdash; does it have to? (Nao, pode.)\' CCQ: \'You must not share it vs you do not have to share it &mdash; which one is optional? (Do not have to.)\' Obstaculo numero um do brasileiro: must not como \'nao precisa\' (em portugues \'nao deve\' e ambiguo). Obstaculo dois: prohibited to (o certo e prohibited from + -ing).',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na sexta, cobre from + -ing.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros: must not por do not have to, may to, entitled of, prohibited to. Enquadramento: \'os mais comuns\'.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: the terms in plain English, a summary, quick questions, and two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ela liga a clausula ao ingles simples e EXPLICA. E parafrase de registro juridico, exatamente o que ela faz em Direito Global. Se fechar rapido, peca que ela escreva uma clausula nova em ingles juridico a partir de uma regra simples.',
        'gap': '<strong>Gap-fill (4 min):</strong> Ela arrasta, toca ou digita e confere com Check. Se errar, aponte a palavra ao redor (\'limits the company\'s ___\', \'entitled ___\').',
        'quickfire': '<strong>Quick fire (5 min):</strong> Uma pergunta por vez. Ela responde ANTES da dica. Regra: cada resposta com um modal de obrigacao ou permissao. Corrija so o modal, no fim.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Depois peca que ela abra os termos de um app real no celular e procure as tres palavras que a advogada cita, em dois minutos.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Aviso de app lido em voz alta, voz masculina, cheio de shall/may/entitled. Depois pergunte qual mudanca ela nao aceitaria.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same contract, three times. The last one is you explaining it to a first-year student.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a amiga que nao leu. Ela explica tres mudancas com shall, may e entitled to. Corrija so os modais, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o atendente do suporte que nega o reembolso. Ela discorda com educacao, usa o argumento de clausula nula e pede solucao clara. Seja firme: e o tipo de conversa real que ela vai ter morando fora.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota. Cronometre. No fim, dois numeros: quantas vezes recomecou e quantos modais usou.',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete em blocos. A terceira resume a armadilha da aula: peca que ela explique a diferenca em uma frase dela.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 8. Item em que ela hesitar entra no warm-up da aula 9.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, a contract is important, but it is not the only thing that protects you.\' Homework (ORALMENTE, nunca escrito na tela): abrir os termos de UM app que ela usa, achar as clausulas de liability, dispute e data, e explicar cada uma em ingles simples em voz alta. Proxima aula: dar opiniao com razoes em quarenta e cinco segundos.',
    },
    'pc': {
        'title': 'The Fine Print You Already Signed -- Obligation and Permission',
        'desc': 'The terms of the apps on your phone are real contracts. Learn the modals that decide what you must, may and may not do.',
        'match_idx': [0, 2, 3, 5, 8, 11],
        'context': [
            'Legal English uses a very small set of words to create duties, options and prohibitions, and <strong>terms of service</strong> use all of them. Once you recognize them, a long clause in <strong>the fine print</strong> becomes a simple question: who has to do what?',
            'Duties are marked with <strong>shall</strong> in formal legal texts and with <strong>must</strong> or <strong>is required to</strong> in both legal and everyday English: &ldquo;The user <strong>shall</strong> keep the password confidential.&rdquo; Options and permissions are marked with <strong>may</strong>: &ldquo;You <strong>may</strong> <strong>opt out</strong> of marketing emails at any time.&rdquo;',
            'Prohibitions use <strong>may not</strong>, <strong>shall not</strong> or <strong>is prohibited from</strong> + <em>-ing</em>: &ldquo;Users <strong>may not</strong> share their account.&rdquo; A right is often written with <strong>is entitled to</strong>: &ldquo;Customers <strong>are entitled to</strong> a refund if the order never arrives.&rdquo;',
            'The most dangerous pair for Brazilian speakers is <strong>must not</strong> and <strong>do not have to</strong>. &ldquo;You <strong>must not</strong> share it&rdquo; means it is forbidden. &ldquo;You <strong>do not have to</strong> give your phone number&rdquo; means it is optional. In a contract, confusing the two is not a small mistake: it changes a <strong>liability</strong>, a right, and sometimes the whole <strong>dispute</strong>.',
        ],
        'context_quiz': [
            ('According to the text, which words mark a duty?', ['may and can', 'shall, must and is required to', 'may not and is entitled to'], 1),
            ('What does &ldquo;You do not have to give your phone number&rdquo; mean?', ['It is optional.', 'It is forbidden.', 'It is required by law.'], 0),
            ('Why does the text call must not and do not have to a dangerous pair?', ['Because they sound informal.', 'Because they are only used in British English.', 'Because confusing them changes a duty into an option, or the reverse.'], 2),
        ],
        'tip_title': 'Obligation and Permission in Legal English',
        'tip_lead': 'Shall and must for duties, may for options, may not for prohibitions, entitled to for rights.',
        'tip_rows': [
            ('A formal duty', 'shall + verb', 'The user <strong>shall</strong> keep it confidential.'),
            ('A duty', 'must / is required to + verb', 'The company <strong>must</strong> protect data.'),
            ('An option', 'may + verb', 'You <strong>may</strong> cancel at any time.'),
            ('A prohibition', 'may not / is prohibited from + -ing', 'Users <strong>may not</strong> share their account.'),
            ('A right', 'is entitled to', 'Customers <strong>are entitled to</strong> a refund.'),
            ('No duty', 'is not required to / does not have to', 'You <strong>do not have to</strong> give your birthday.'),
        ],
        'tip_never': 'you must not give your number (if it is optional) &middot; users may to cancel &middot; entitled of a refund &middot; prohibited to resell',
        'blanks': [
            ('The user ', 'shall', ' keep the password confidential.', 'Hint: a formal legal duty -- one word', None),
            ('You ', 'may', ' cancel your subscription at any time.', 'Hint: an option, not a duty -- one word', None),
            ('Users ', 'may not', ' share their account with anyone else.', 'Hint: a prohibition -- two words', None),
            ('It is optional: you ', 'do not have to', ' give your birthday.', 'Hint: no duty, not a prohibition -- four words', 'don\'t have to'),
            ('If the order never arrives, you are entitled to a ', 'refund', '.', 'Hint: money paid back to you -- one word', None),
            ('You can stop the marketing emails: just ', 'opt out', ' in the settings.', 'Hint: choose not to take part -- two words', None),
        ],
        'order_title': 'Put the Advice in Order',
        'order_lead': 'A friend is about to accept the terms of a new app. Put your advice in a logical order.',
        'order': [
            'You do not have to read all forty pages.',
            'First, search for the word liable to see what they will not pay for.',
            'Then search for dispute or arbitration.',
            'After that, check who they may share your data with.',
            'If a clause looks abusive, remember that it may be void.',
            'And if you do not agree, you may close the account.',
        ],
        'quiz': [
            ('The app says giving your birthday is optional. You explain:', ['You must not give your birthday.', 'You do not have to give your birthday.', 'You shall give your birthday.'], 1),
            ('You want to write a prohibition in legal English. You write:', ['Users may not share their account.', 'Users may to share their account.', 'Users are prohibited to share their account.'], 0),
            ('The order never arrived. You tell support:', ['I am entitled of a refund.', 'I must a refund.', 'I am entitled to a refund.'], 2),
            ('You do not want marketing emails. You say:', ['I want to opt out of marketing emails.', 'I want to waive marketing emails.', 'I want to terminate marketing emails.'], 0),
        ],
        'think': 'Think of an app you use every week. In ninety seconds, explain to a friend what you probably agreed to in its terms of service: one thing you must do, one thing the company may do, one thing you may not do, and one right you are entitled to, even if the terms say otherwise.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'Computerphile &mdash; &ldquo;Blindly Accepting Terms and Conditions?&rdquo; (YouTube)',
         'desc': 'A short, clear conversation about why people accept terms without reading them and what that can cost. Good listening practice on today&rsquo;s exact topic.',
         'tip': 'Tip: every time you hear a rule, say whether it is a duty, an option or a right.',
         'url': 'https://www.youtube.com/watch?v=9Hb2oMlRI0I', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'Silicon Valley &mdash; Season 1, Episode 1, &ldquo;Minimum Viable Product&rdquo;',
         'desc': 'A comedy about building a tech company, where contracts, equity and fine print decide everything. Fast American English and a lot of business and legal vocabulary.',
         'tip': 'Tip: when a contract or an offer appears, say what the character must, may or may not do.',
         'url': 'https://www.tvmaze.com/episodes/10897/silicon-valley-1x01-minimum-viable-product', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Glenn Greenwald &mdash; &ldquo;Why privacy matters&rdquo; (TED)',
         'desc': 'A journalist and lawyer on why people who say they have nothing to hide still care about privacy. Useful for the data clauses in any terms of service.',
         'tip': 'Tip: summarize his main argument in three blocks, and say whether you agree and why.',
         'url': 'https://www.ted.com/talks/glenn_greenwald_why_privacy_matters', 'cta': 'Watch on TED'},
    ],
}
