# -*- coding: utf-8 -*-
# Aula 3 -- Say It Once, Clearly (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "Say It Once, <span class='accent'>Clearly</span>",
    'hero_line': 'A classmate missed the seminar, and you have thirty seconds to tell them what the professor said',
    'menu_desc': 'Summarizing what somebody said without stumbling, and the reported speech that carries it -- 34 slides',
    'grammar_point': 'reported speech with backshift and reporting verbs',
    'phases': ['The Seminar', 'Words of the Summary', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'ethan', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1524178232363-1fb2b075b655?w=1400&q=80',
        'ch2': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch_grammar': U + 'photo-1456513080510-7bf3a84b82f8?w=1400&q=80',
        'ch4': U + 'photo-1522202176988-66273c2fd55f?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1529156069898-49953e39b3ac?w=1400&q=80',
        'ch7': U + 'photo-1541339907198-e08756dedf3f?w=1400&q=80',
        'pc': U + 'photo-1524178232363-1fb2b075b655?w=600&q=80',
    },
    'warmup': {
        'heading': "What Did Your Professor <span class='accent'>Say This Week?</span>",
        'sub': 'One class, one professor, one idea. What did they say, and did you agree?',
    },
    'target': {
        'heading': "A Summary in <span class='accent'>Three Blocks</span>",
        'steps': [
            'Who said it, and the main point, in one sentence.',
            'One piece of evidence they used to back it up.',
            'Your reaction: do you agree, and why, in one sentence.',
        ],
    },
    'diagnostic': {
        'heading': "You Missed the <span class='accent'>Class?</span>",
        'p1': 'An exchange student in your Global Law course missed the seminar and texts you: &ldquo;What did the professor say today? Anything important?&rdquo;',
        'p2': 'Answer out loud for forty-five seconds, as if you were sending a voice message. Say what the professor said, not what you think.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Summary</span>",
            'sub': 'Thirteen words for reporting an argument, and for keeping your own sentence alive'},
    'vocab': [
        {'word': 'To sum up', 'def': 'To give the most important ideas of something in a few words', 'ex': 'To sum up, the professor thinks precedents should guide judges, not control them.', 'icon': 'filter'},
        {'word': 'A key point', 'def': 'One of the most important ideas in an argument or a talk', 'ex': 'Her key point was that courts need to be predictable.', 'icon': 'key'},
        {'word': 'To point out', 'def': 'To tell somebody a fact they may not have noticed', 'ex': 'He pointed out that the treaty had never been ratified.', 'icon': 'eye'},
        {'word': 'To argue', 'def': 'To give reasons to show that an idea is true or right', 'ex': 'The author argues that sovereignty is changing.', 'icon': 'message'},
        {'word': 'To claim', 'def': 'To say that something is true, often without giving proof', 'ex': 'The article claims that most treaties are ignored.', 'icon': 'mic'},
        {'word': 'To acknowledge', 'def': 'To accept or admit that something is true or exists', 'ex': 'She acknowledged that the other side had a fair point.', 'icon': 'hand'},
        {'word': 'A counterargument', 'def': 'A reason that is given against another argument', 'ex': 'The strongest counterargument came from a student in the back row.', 'icon': 'scale'},
        {'word': 'To back up', 'def': 'To support an idea with facts, numbers or examples', 'ex': 'You need a real case to back up that claim.', 'icon': 'layers'},
        {'word': 'Evidence', 'def': 'Facts or information that show whether something is true', 'ex': 'The professor asked for evidence, not opinions.', 'icon': 'doc'},
        {'word': 'To get your point across', 'def': 'To make other people understand your idea clearly', 'ex': 'I knew the answer, but I could not get my point across.', 'icon': 'target'},
        {'word': 'To stumble over', 'def': 'To make a mistake or stop when you are saying a word or a sentence', 'ex': 'I always stumble over long words when I am nervous.', 'icon': 'alert'},
        {'word': 'To rephrase', 'def': 'To say the same thing again in different words', 'ex': 'Let me rephrase that, because it came out wrong.', 'icon': 'refresh'},
        {'word': 'To trail off', 'def': 'To speak more and more quietly until you stop, without finishing', 'ex': 'He started a strong sentence and then trailed off.', 'icon': 'clock'},
    ],
    'pron_heading': "Say It in <span class='accent'>One Block</span>",
    'pron': ['To acknowledge', 'A counterargument', 'Evidence', 'The professor argued that precedents should guide judges, not control them.'],
    'vocab_fill': [
        ('The class was long, so let me ', 'sum up', ' the three main ideas.'),
        ('My classmate did not notice the date, so I wanted to ', 'point out', ' that the deadline had changed.'),
        ('A strong claim needs a real case to ', 'back up', ' the argument.'),
        ('You can present your argument, but also ', 'acknowledge', ' the other side.'),
        ('He started a strong sentence, but then he began to ', 'trail off', ' and nobody heard the end.'),
        ('When a word does not come, do not stop: ', 'rephrase', ' it and keep going.'),
    ],
    'ch_grammar': {'heading': "What She Said, <span class='accent'>Told Later</span>",
                   'sub': 'Four sentences about one seminar, and the verbs that move back in time'},
    'grammar': {
        'heading': "Why Did <span class='accent'>Is Become Was?</span>",
        'examples': [
            "She <span style='color:#b91c1c;font-weight:700'>said that</span> precedents <span style='color:#b91c1c;font-weight:700'>guided</span> judges.",
            "He <span style='color:#b91c1c;font-weight:700'>told me that</span> he <span style='color:#b91c1c;font-weight:700'>had read</span> the case.",
            "She <span style='color:#1d4ed8;font-weight:700'>pointed out that</span> we <span style='color:#1d4ed8;font-weight:700'>would</span> discuss it on Friday.",
            "He <span style='color:#1d4ed8;font-weight:700'>asked whether</span> the treaty <span style='color:#1d4ed8;font-weight:700'>was</span> binding.",
        ],
        'prompt': 'The exact words in the seminar were: <em>&ldquo;Precedents guide judges&rdquo;</em>, <em>&ldquo;I have read the case&rdquo;</em>, <em>&ldquo;We will discuss it on Friday&rdquo;</em> and <em>&ldquo;Is the treaty binding?&rdquo;</em> Compare them with the red and blue words. What happened to the verbs? And why <em>told me</em>, <em>pointed out</em> and <em>asked whether</em>, instead of only <em>said</em>?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Report a statement', 'said (that) + clause', 'She <strong>said that</strong> precedents <strong>guided</strong> judges.'),
            ('Say who heard it', 'told + person + (that)', 'He <strong>told me that</strong> he <strong>had read</strong> the case.'),
            ('Move the time back', 'present &rarr; past, past &rarr; had + participle, will &rarr; would', '&ldquo;I will&rdquo; &rarr; she said she <strong>would</strong>'),
            ('Report a yes/no question', 'asked + whether / if + statement order', 'He <strong>asked whether</strong> it <strong>was</strong> binding.'),
            ('Show the kind of statement', 'argued / pointed out / claimed / acknowledged that', 'She <strong>acknowledged that</strong> the court was slow.'),
            ('Still true, or reported right away', 'backshift is optional', 'She said the TOEFL <strong>has</strong> four sections.'),
            ('The trap', 'never <em>said me</em>; never <em>asked if was</em>', 'Not <em>He said me that</em>. Say <strong>He told me that</strong>.'),
        ],
        'oneliner': 'Choose a verb that shows what kind of statement it was, and move the tense one step back.',
    },
    'grammar_practice': {
        'heading': "Report It, <span class='accent'>Don&rsquo;t Quote It</span>",
        'items': [
            ('&ldquo;Precedents guide judges.&rdquo; &rarr; She said that precedents ', 'guided', ' judges. (present &rarr; past)'),
            ('&ldquo;I have read the case.&rdquo; &rarr; He told me that he ', 'had read', ' the case. (present perfect &rarr; past perfect)'),
            ('&ldquo;We will vote on Friday.&rdquo; &rarr; She said that we ', 'would', ' vote on Friday. (will &rarr; ?)'),
            ('&ldquo;Is the treaty binding?&rdquo; &rarr; He asked ', 'whether the treaty was', ' binding. (a yes/no question)'),
            ('Ethan said that. &rarr; Ethan ', 'told me', ' that he had missed the class. (say who heard it)'),
            ('&ldquo;You are right about that.&rdquo; &rarr; She ', 'acknowledged', ' that I was right about that. (she admits it)'),
        ],
    },
    'ch4': {'heading': "The Voice Message After <span class='accent'>the Seminar</span>",
            'sub': 'One conversation, two recordings, one rubric'},
    'dialogue': {
        'heading': "Ethan Missed the <span class='accent'>Class</span>",
        'guest_name': 'Ethan', 'guest_initial': 'E',
        'lines': [
            ('e', 'Luiza, hey. I overslept and missed the whole seminar. Please tell me Professor Reeves did not say anything important.'),
            ('l', 'Sorry, she did. Her <span class="vocab-highlight">key point</span> was that precedents should guide judges, not control them.'),
            ('e', 'Okay, and how did she <span class="vocab-highlight">back</span> that <span class="vocab-highlight">up</span>? She always asks for <span class="vocab-highlight">evidence</span>.'),
            ('l', 'She used two old cases. She <span class="vocab-highlight">pointed out</span> that the court had changed its mind twice in ten years, and she <span class="vocab-highlight">argued</span> that nobody had noticed.'),
            ('e', 'Did anyone disagree? That sounds like the kind of thing Marcus would fight about.'),
            ('l', 'He did. He <span class="vocab-highlight">claimed</span> that a court without fixed rules was dangerous. It was a good <span class="vocab-highlight">counterargument</span>, and she <span class="vocab-highlight">acknowledged</span> that he had a point.'),
            ('e', 'And what did you say? You were talking about this all week.'),
            ('l', 'I started well, but I <span class="vocab-highlight">stumbled over</span> the word jurisprudence and <span class="vocab-highlight">trailed off</span>. So I stopped, <span class="vocab-highlight">rephrased</span> it, and I think I finally <span class="vocab-highlight">got my point across</span>.'),
            ('e', 'Good enough for me. Can you <span class="vocab-highlight">sum up</span> the reading for Friday too, or is that too much to ask?'),
            ('l', 'It is too much to ask. But she told us the reading was short, so you have no excuse. Did you at least see the new deadline?'),
        ],
        'comp': [
            ('Why did Ethan miss the seminar?', 'He overslept.'),
            ('What does Ethan say Professor Reeves always asks for?', 'Evidence.'),
            ('Who does Ethan think would fight about the idea?', 'Marcus.'),
            ('What does Ethan ask Luiza to do at the end?', 'To sum up the reading for Friday too.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Podcast', 'title': "Thirty Seconds, <span class='accent'>No Stumbling</span>",
         'blurb': 'A speaking coach on summarizing out loud. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'When students tell me they stumble over their words, I ask them to summarize something out loud, and almost every time the problem is not vocabulary. The problem is that they try to say everything in one long sentence, so they run out of breath and trail off. A spoken summary needs blocks, not sentences. Block one: who said it, and the main point. Block two: one piece of evidence, only one. Block three: your reaction. Between the blocks, you breathe. And if a word does not come, you do not wait for it. You rephrase and keep going, because the listener cannot see the word you are looking for. They only hear the silence. Try it tonight with anything, a class, a video, a conversation. Thirty seconds, three blocks, and no word is allowed to stop you.',
         'qs': [
             ('According to the coach, what is usually the real problem when students stumble?', 'Not vocabulary: they try to say everything in one long sentence, so they run out of breath and trail off.'),
             ('What are the three blocks of a spoken summary?', 'Who said it and the main point; one piece of evidence; your reaction.'),
             ('What should you do when a word does not come, and why?', 'Rephrase and keep going, because the listener cannot see the word you are looking for; they only hear the silence.'),
         ]},
        {'label': 'Listening 2 &middot; A Lecture', 'title': "Should the Past <span class='accent'>Decide?</span>",
         'blurb': 'Part of a law lecture on precedent. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Let us start with a simple question that has divided lawyers for centuries. When a court has already decided a case, should the next court be forced to decide the same way? In the common law tradition, the answer is mostly yes. Earlier decisions, called precedents, give the system something it badly needs: predictability. A company that signs a contract today wants to know how a judge will read it in five years. But precedent has a cost. Societies change faster than courts, and a rule that made sense fifty years ago can produce an unfair result today. That is why higher courts sometimes overrule their own decisions. The real debate, then, is not whether the past should matter. It is how much weight it should carry, and who gets to decide when it is time to let it go.',
         'qs': [
             ('What simple question does the lecturer say has divided lawyers?', 'Whether the next court should be forced to decide a case the same way as an earlier court.'),
             ('What does precedent give the system, and what example does he use?', 'Predictability. A company that signs a contract today wants to know how a judge will read it in five years.'),
             ('What cost of precedent does he mention, and what is the real debate?', 'Societies change faster than courts, so an old rule can produce an unfair result. The real debate is how much weight the past should carry, and who decides when to let it go.'),
         ]},
    ],
    'artifact': {
        'heading': "The Rubric Your Professor <span class='accent'>Uses</span>",
        'title': 'SEMINAR PARTICIPATION RUBRIC', 'subtitle': 'Global Law &middot; Seminar 3 &middot; Student: L. Sato Eccheli',
        'rows': [
            ('Summary of the reading', 'Main point stated in under 30 seconds', True),
            ('Use of evidence', 'At least one case or source to back up each claim', False),
            ('Engagement', 'Responds to a classmate&rsquo;s point before adding a new one', False),
            ('Counterargument', 'Acknowledges the strongest argument against your view', True),
            ('Clarity', 'Rephrases instead of stopping when a word does not come', False),
        ],
        'note': 'Professor&rsquo;s note: I do not grade accent. I grade whether the class can follow you. A short, clear contribution is worth more than a long one that trails off.',
        'qs': [
            ('How long should the summary of the reading take?', 'Under thirty seconds.'),
            ('What must a student do before adding a new point?', 'Respond to a classmate&rsquo;s point.'),
            ('According to the professor&rsquo;s note, what is graded, and what is not?', 'Whether the class can follow you is graded; accent is not.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Seminar Star</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('She said me that the reading was short.', 'She <strong>told me</strong> that the reading was short.'),
        ('He asked if was the treaty binding.', 'He asked <strong>if the treaty was</strong> binding.'),
        ('The professor said that she will discuss it on Friday.', 'The professor said that she <strong>would</strong> discuss it on Friday.'),
        ('Marcus argued me that the court was dangerous.', 'Marcus <strong>argued that</strong> the court was dangerous.'),
    ],
    'speaking': [
        ('What did the professor say today?', 'She said that precedents should guide judges, not control them, and she backed it up with two old cases.'),
        ('Did anybody disagree with her?', 'Yes. Marcus claimed that a court without fixed rules was dangerous, and she acknowledged that he had a point.'),
        ('What was the key point of your last class at GV?', 'The key point was that a signature is not the same as ratification, and the professor pointed out that the headlines often get it wrong.'),
        ('What do you do when you stumble over a word?', 'I stop trying to find the perfect word, I rephrase it, and I keep going.'),
    ],
    'building': [
        ('she / say / precedents guide judges (report a statement)', 'She said that precedents guided judges.'),
        ('he / tell / me / he / read the case (present perfect moves back)', 'He told me that he had read the case.'),
        ('he / ask / the treaty / be binding (a yes/no question)', 'He asked whether the treaty was binding.'),
        ('she / acknowledge / Marcus / have a point (she admits it)', 'She acknowledged that Marcus had a point.'),
    ],
    'roleplays': {
        'heading': "The Same Seminar, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Ethan Asks <span class='accent'>Again</span>",
             'scenario': 'Ethan asks the same three questions: what the professor said, how she backed it up, and whether anybody disagreed. Answer each one in two sentences, with a reporting verb in every answer.',
             'chips': ['She argued that', 'She pointed out that', 'evidence', 'a counterargument']},
            {'heading': "Summarize <span class='accent'>a Real Class</span>",
             'scenario': 'Choose a real class you had at GV this week. Summarize it for your teacher in three blocks: who said what, one piece of evidence, and your reaction. Then report one question a classmate asked.',
             'chips': ['The key point was', 'He asked whether', 'to back up', 'I acknowledged that']},
            {'heading': "Thirty Seconds, <span class='accent'>No Notes</span>",
             'scenario': 'Your teacher plays a short video or reads a paragraph. Summarize it in thirty seconds, in three blocks, reporting what the speaker said.',
             'footer': 'No notes, thirty seconds. If a word does not come, rephrase and keep going.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for <span class='accent'>Every Summary</span>", 'sub': 'What you say when somebody asks what they missed'},
    'survival_heading': "Five Sentences for <span class='accent'>Every Summary</span>",
    'survival': [
        'Her key point was that precedents should guide judges, not control them.',
        'She backed it up with two cases from the last ten years.',
        'Marcus claimed that the court was dangerous, and she acknowledged that he had a point.',
        'He asked whether the treaty was binding.',
        'Let me rephrase that, because it came out wrong.',
    ],
    'checklist': [
        'I can summarize what somebody said in three blocks, in thirty seconds.',
        'I move the tense back when I report: is becomes was, will becomes would.',
        'I say told me, and never said me.',
        'I choose a verb that shows the kind of statement: argued, pointed out, claimed, acknowledged.',
        'I know the words: to sum up, a key point, to point out, to argue, to claim, to acknowledge, a counterargument, to back up, evidence, to get your point across, to stumble over, to rephrase, to trail off.',
    ],
    'badge': {'name': 'The Clear Summary', 'line': 'Three blocks, one breath each, and no word allowed to stop you.',
              'next': 'Next lesson: Who Judges a State? -- international courts, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today you summarize what other people said, and you do it without stopping.\' Esta aula ataca o incomodo numero um dela: \'eu travo nas palavras, ai eu tenho que repetir\'. Resumir e a tarefa que mais expoe isso, e e o que ela faz no seminario da GV e fara no intercambio. Fluidez antes de precisao: correcao em bloco, no fim de cada atividade.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta da tela. Callback da aula 2: exija pelo menos duas palavras de tratados na resposta, se a aula dela tiver sido de Direito Global (a treaty, binding, to ratify, a breach, sovereignty). Se nao, peca que conte o que o professor disse usando \'said that\'. ANOTE se ela faz o backshift sozinha ou fica no presente &mdash; e o diagnostico da gramatica de hoje.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 blocos. Diga que entre um bloco e outro ela respira: e a tecnica para nao travar. Nao de a regra do reported speech ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Quarenta e cinco segundos, como mensagem de voz. Cronometre. ANOTE: quantas vezes ela recomecou, e se tentou dizer tudo numa frase so. Esse numero e comparado com o role-play livre do capitulo 6.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words to report an argument, and three to rescue your own sentence.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'to sum up\': \'Is it everything, or the most important ideas? (O mais importante.)\' CCQ \'to point out\': \'Does the other person already know it? (Nao necessariamente.)\' CCQ \'to argue x to claim\': \'Which one usually comes with reasons? (Argue.)\' Obstaculo: \'argue\' em ingles e defender com razoes, nao so \'discutir\'.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'to acknowledge\': \'Is she agreeing with the whole idea, or admitting one part is true? (Admitindo uma parte.)\' CCQ \'to back up\': \'With opinions or with facts? (Fatos.)\' \'Evidence\' e incontavel: nunca \'an evidence\' nem \'evidences\' &mdash; erro classico do brasileiro. Pronuncia: ac-KNOW-ledge, sem o K.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> Estas tres sao sobre ELA: stumble over, rephrase, trail off. Pergunte qual das tres acontece mais com ela, e deixe contar. CCQ \'to trail off\': \'Does the sentence end, or disappear? (Some.)\'',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> ac-KNOW-ledge, COUN-ter-ar-gu-ment (acento na primeira), EV-i-dence. Na frase longa, peca a frase num bloco so, sem pausa no meio. Se travar, recomeca do inicio do bloco. A tarefa Listen and Repeat do TOEFL novo e exatamente isto: repetir uma frase inteira com o mesmo ritmo.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ela diz a palavra ANTES de clicar, escolhendo do banco. Na quinta, a expressao sai exatamente como foi ensinada no card. Se fechar rapido, peca uma frase dela com \'trail off\'.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four things people said in a seminar, and how you tell them the next day.\' Passe ao proximo.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'What happened to guide, have read, will and is?\' Espere ela ver o backshift. Depois: \'Why told me and not said me?\' So entao Reveal the Rule. CCQ: \'She said that precedents guided judges &mdash; is she talking about the past only? (Nao, e a fala dela reportada; o recuo e gramatical.)\' CCQ: \'He asked whether it was binding &mdash; is this a question or a statement now? (Afirmacao, ordem normal.)\' Obstaculos do brasileiro: \'said me\' (calco de \'me disse\') e \'asked if was\' (ordem de pergunta). Diga que backshift e opcional quando a coisa continua verdade.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela fala a frase reportada INTEIRA antes de clicar, num bloco so. Na quarta, cobre a ordem de afirmacao. Na sexta, peca uma segunda frase com \'acknowledged that\' sobre um colega real.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now the conversation after the seminar, two recordings and the rubric your professor uses.\' Passe ao proximo.',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e o Ethan: aluno de intercambio americano na turma dela, simpatico e meio desligado. Clique Next Line e toque o audio. Nas falas da Luiza, ela fala PRIMEIRO. PRAGMATICA para comentar: repare que a Luiza admite que travou (\'I stumbled over the word\') e conta o que fez (\'I rephrased it\') &mdash; e o comportamento que queremos que vire habito dela. E no fim ela nega o favor com humor: registro natural entre colegas.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre o ETHAN, nunca sobre a Luiza (REGRA 27F). Ela responde antes de revelar. Depois pergunte: \'Do you have an Ethan in your class at GV?\'',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Esta gravacao descreve o problema dela com as palavras dela. Depois das respostas: \'Which of the three blocks is hardest for you?\'',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Contexto diferente: aula de Direito, voz masculina, ritmo de palestra. Depois das perguntas, peca que ela RESUMA a gravacao em trinta segundos com os tres blocos e reported speech (\'He argued that...\'). E o treino da tarefa de hoje com material real.',
        'artifact': '<strong>Artefato (4 min):</strong> Rubrica ficticia de seminario, com o nome dela. Peca que ela leia cada criterio e diga como se sai hoje, de 1 a 5, com uma frase. So depois as 3 perguntas. A nota do professor repete o que ela disse na consultoria sobre sotaque: aponte.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\' Passe ao proximo.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Os quatro erros classicos: said me, ordem de pergunta no reported question, will sem recuo, argue com objeto indireto. Enquadramento: \'os mais comuns\', nunca \'voce errou\'.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas como o Ethan faria. Respostas na tela sao sugestao. Regra do bloco: um verbo de relato por resposta e nenhuma frase recomecada. Correcao em bloco no fim, no maximo tres pontos.',
        'building': '<strong>Sentence Building (4 min):</strong> Ela monta a frase COMPLETA em voz alta e so depois clica. Cobre o recuo do tempo verbal e o told me.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same seminar, three times. The last one is thirty seconds, with no notes.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o Ethan, sem o texto na tela. Tres perguntas, duas frases por resposta, um verbo de relato em cada. Corrija so said me e o backshift, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Ela escolhe uma aula REAL da semana na GV. Exija os tres blocos e uma pergunta de colega reportada (\'She asked whether...\'). Conteudo real e o que ela mais quer: deixe ela contar, e so depois corrija.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Leia um paragrafo curto de qualquer noticia ou toque 40 segundos de um video em ingles. Ela resume em trinta segundos, cronometrado, sem nota. No fim, dois numeros: quantas vezes recomecou (compare com o slide 4) e quantos verbos de relato usou.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you told me about one class. Now you can tell anyone what they missed, in thirty seconds.\' Passe ao proximo.',
        'survival': '<strong>Survival card (3 min):</strong> Leia cada frase e toque o audio. Ela repete num bloco so. A quinta e a ferramenta anti-trava: peca que ela use em voz alta pelo menos uma vez na semana.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 3. Item em que ela hesitar entra no warm-up da aula 4.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the class cannot see the word you are looking for. It only hears the silence.\' Homework (ORALMENTE, nunca escrito na tela): depois de UMA aula da GV nesta semana, gravar um resumo de noventa segundos em ingles com os tres blocos e trazer a gravacao. Proxima aula: quem julga um Estado, em leitura.',
    },
    'pc': {
        'title': 'Say It Once, Clearly -- Reporting What Somebody Said',
        'desc': 'A classmate missed the seminar. Summarize what the professor said, in three blocks, without stumbling.',
        'match_idx': [0, 3, 5, 7, 8, 10],
        'context': [
            'The day after a seminar, the most common question in any law school is simple: what did the professor say? Answering it well is harder than it looks, because you are not repeating the words. You are <strong>reporting</strong> them, and English changes the sentence when it moves from somebody&rsquo;s mouth into your summary.',
            'The first change is the verb. If the professor said &ldquo;Precedents guide judges,&rdquo; your report is &ldquo;She <strong>said that</strong> precedents <strong>guided</strong> judges.&rdquo; The tense moves one step back: <em>is</em> becomes <em>was</em>, <em>have read</em> becomes <em>had read</em>, and <em>will</em> becomes <em>would</em>. When the idea is still true, or when you report it right away, the change is optional.',
            'The second change is who heard it. <strong>Say</strong> does not take a person directly, so &ldquo;she said me&rdquo; is always wrong. Use <strong>told</strong>: &ldquo;She <strong>told me that</strong> the reading was short.&rdquo; Questions become statements: &ldquo;Is it binding?&rdquo; turns into &ldquo;He <strong>asked whether</strong> it <strong>was</strong> binding.&rdquo;',
            'Finally, a good summary does not use <em>said</em> for everything. A professor who gives reasons <strong>argues</strong>; one who shows a fact you missed <strong>points out</strong>; a classmate who admits the other side is right <strong>acknowledges</strong> it. The verb tells your listener what kind of statement it was, and a short summary with the right verbs <strong>gets your point across</strong> faster than a long one that <strong>trails off</strong>.',
        ],
        'context_quiz': [
            ('According to the text, what happens to the tense when you report a statement?', ['It stays exactly the same.', 'It usually moves one step back, like is to was.', 'It always becomes the future.'], 1),
            ('Why is &ldquo;she said me that&rdquo; wrong?', ['Because say does not take a person directly; you use told.', 'Because that cannot follow said.', 'Because me should be I.'], 0),
            ('What does the text say a verb like argue or acknowledge adds to a summary?', ['It makes the sentence longer.', 'It avoids the past tense.', 'It tells the listener what kind of statement it was.'], 2),
        ],
        'tip_title': 'Reported Speech',
        'tip_lead': 'Choose a verb that shows the kind of statement, and move the tense one step back.',
        'tip_rows': [
            ('A statement', 'said (that) + clause', 'She <strong>said that</strong> it <strong>was</strong> short.'),
            ('Say who heard it', 'told + person + (that)', 'He <strong>told me that</strong> he <strong>had read</strong> it.'),
            ('Tense moves back', 'is &rarr; was &middot; has &rarr; had &middot; will &rarr; would', 'She said she <strong>would</strong> come.'),
            ('A yes/no question', 'asked whether / if + statement order', 'He <strong>asked whether</strong> it <strong>was</strong> binding.'),
            ('A wh- question', 'asked + wh- word + statement order', 'She <strong>asked where</strong> the room <strong>was</strong>.'),
            ('The kind of statement', 'argued / pointed out / claimed / acknowledged that', 'He <strong>pointed out that</strong> the date had changed.'),
        ],
        'tip_never': 'she said me that &middot; he asked if was the treaty binding &middot; she said she will come tomorrow &middot; he argued me that',
        'blanks': [
            ('She told us that the reading ', 'was', ' short.', 'Hint: she said is; in a report the present moves one step back -- one word', None),
            ('He said that he ', 'had read', ' the case before class.', 'Hint: he said I have read; the present perfect moves back -- two words', None),
            ('She said we ', 'would', ' vote on Friday.', 'Hint: she said we will; what does will become? -- one word', None),
            ('Ethan ', 'told', ' me that he had missed the class.', 'Hint: the reporting verb that takes a person -- one word', None),
            ('He asked ', 'whether', ' the treaty was binding.', 'Hint: a yes/no question in a report -- one word', None),
            ('When a word does not come, do not stop: ', 'rephrase', ' it and keep going.', 'Hint: say it again in other words -- one word', None),
        ],
        'order_title': 'Put the Summary in Order',
        'order_lead': 'A classmate missed the seminar. Put your voice message in a logical order.',
        'order': [
            'You missed a good one: Professor Reeves talked about precedent.',
            'Her key point was that precedents should guide judges, not control them.',
            'She backed it up with two cases where the court changed its mind.',
            'Marcus claimed that a court without fixed rules was dangerous.',
            'She acknowledged that he had a point, but she did not change her view.',
            'She told us the reading for Friday was short, so do not skip it.',
        ],
        'quiz': [
            ('Your classmate asks what the professor said. You answer:', ['She said me that precedents guide judges.', 'She told me that precedents guided judges.', 'She told that precedents guide judges to me.'], 1),
            ('You want to report a question a classmate asked. You say:', ['He asked whether the treaty was binding.', 'He asked if was the treaty binding.', 'He asked is the treaty binding.'], 0),
            ('The professor admitted that the other side was partly right. You say:', ['She claimed that he had a point.', 'She pointed him that he had a point.', 'She acknowledged that he had a point.'], 2),
            ('You stumble over a long word in the middle of your summary. You say:', ['Sorry, I forgot the word, I cannot continue.', 'Let me rephrase that.', 'Wait, how do you say it in Portuguese?'], 1),
        ],
        'think': 'Think of the last class you had at GV. In ninety seconds, record a voice message for a classmate who missed it: say who said what, give one piece of evidence the professor used, report one question or counterargument from the class, and give your own reaction. Use at least three different reporting verbs.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Julian Treasure &mdash; &ldquo;How to speak so that people want to listen&rdquo; (TED)',
         'desc': 'Ten minutes on pace, pitch and silence: the tools behind a clear summary that does not trail off. Useful for the seminar and for the new TOEFL speaking tasks.',
         'tip': 'Tip: try his warm-up exercises once, then record a thirty-second summary of the talk in three blocks.',
         'url': 'https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen', 'cta': 'Watch on TED'},
        {'id': 'series', 'type': 'Series', 'title': 'How to Get Away with Murder &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'A law professor, a seminar full of ambitious students and a lot of fast arguing about evidence. Much darker than your classes, but full of the language of today&rsquo;s lesson.',
         'tip': 'Tip: after each scene in the classroom, pause and report in one sentence what the professor argued.',
         'url': 'https://www.tvmaze.com/episodes/2056/how-to-get-away-with-murder-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'video', 'type': 'Video', 'title': 'TST Prep &mdash; &ldquo;TOEFL Speaking: Listen and Repeat Training (2026)&rdquo; (YouTube)',
         'desc': 'Practice for the new Listen and Repeat task: you hear a sentence once and repeat it with the same rhythm, in one block. It is the exact skill that stops you from stumbling.',
         'tip': 'Tip: repeat each sentence without pausing in the middle. If you stop, start the whole sentence again.',
         'url': 'https://www.youtube.com/watch?v=iR529CoRuZo', 'cta': 'Watch on YouTube'},
    ],
}
