# -*- coding: utf-8 -*-
# Aula 9 -- Forty-Five Seconds of Opinion (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "Forty-Five Seconds <span class='accent'>of Opinion</span>",
    'hero_line': 'Four questions, no preparation, and the concession that makes an opinion sound mature',
    'menu_desc': 'The TOEFL interview task, and concession and contrast with although, despite and whereas -- 34 slides',
    'grammar_point': 'concession and contrast with although, despite, whereas and however',
    'phases': ['The Question', 'Words of an Opinion', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'nathan', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1522202176988-66273c2fd55f?w=1400&q=80',
        'ch2': U + 'photo-1517048676732-d65bc937f952?w=1400&q=80',
        'ch_grammar': U + 'photo-1488190211105-8b0e65b80b4e?w=1400&q=80',
        'ch4': U + 'photo-1454165804606-c3d57bc86b40?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1524178232363-1fb2b075b655?w=1400&q=80',
        'ch7': U + 'photo-1541339907198-e08756dedf3f?w=1400&q=80',
        'pc': U + 'photo-1522202176988-66273c2fd55f?w=600&q=80',
    },
    'warmup': {
        'heading': "Studying the Night <span class='accent'>Before Class</span>",
        'sub': 'At GV you study every topic the night before the class. Do you think it works? Give one good thing and one bad thing about it.',
    },
    'target': {
        'heading': "Forty-Five Seconds, <span class='accent'>Four Moves</span>",
        'steps': [
            'Your position, in the first sentence.',
            'One reason, and one example from your own life.',
            'A concession: the strongest point on the other side, in one sentence.',
            'Back to your position, so the answer has an end.',
        ],
    },
    'diagnostic': {
        'heading': "Online or <span class='accent'>in Person?</span>",
        'p1': 'An interviewer on a screen asks: &ldquo;Some people say you can learn a language better online than in a classroom. What do you think?&rdquo;',
        'p2': 'You have no preparation time. Start speaking now, and stop at forty-five seconds.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>an Opinion</span>",
            'sub': 'Thirteen words for weighing two sides before you choose one'},
    'vocab': [
        {'word': 'A drawback', 'def': 'A disadvantage or a problem that makes something less attractive', 'ex': 'The main drawback of online classes is the lack of contact.', 'icon': 'alert'},
        {'word': 'A benefit', 'def': 'An advantage or a helpful effect of something', 'ex': 'One benefit of studying the night before is that the class makes more sense.', 'icon': 'star'},
        {'word': 'To outweigh', 'def': 'To be more important or greater than something else', 'ex': 'For me, the benefits outweigh the drawbacks.', 'icon': 'scale'},
        {'word': 'A trade-off', 'def': 'A situation where you accept losing one thing in order to gain another', 'ex': 'Fewer classes per week is a trade-off: less pressure, but a longer course.', 'icon': 'refresh'},
        {'word': 'To be torn between', 'def': 'To find it very difficult to choose between two options', 'ex': 'I am torn between London and New York for the exchange.', 'icon': 'compass'},
        {'word': 'In the long run', 'def': 'After a long period of time, not immediately', 'ex': 'In the long run, reading every day makes the difference.', 'icon': 'clock'},
        {'word': 'A workload', 'def': 'The amount of work a person has to do', 'ex': 'My workload doubles in the exam period.', 'icon': 'layers'},
        {'word': 'To cram', 'def': 'To study a lot of information in a very short time, usually just before an exam', 'ex': 'I crammed for the test, and I forgot everything a week later.', 'icon': 'book'},
        {'word': 'Overwhelming', 'def': 'So great or so much that it is difficult to deal with', 'ex': 'The reading list was overwhelming in the first semester.', 'icon': 'zap'},
        {'word': 'Worthwhile', 'def': 'Worth the time, money or effort that you spend on it', 'ex': 'The exchange is expensive, but it is worthwhile.', 'icon': 'target'},
        {'word': 'To take for granted', 'def': 'To expect something to always be there, without appreciating it', 'ex': 'I took my school English classes for granted until I went to Scotland.', 'icon': 'hand'},
        {'word': 'A double-edged sword', 'def': 'Something that has both good and bad effects', 'ex': 'Social media is a double-edged sword for language learners.', 'icon': 'shield'},
        {'word': 'To make a case for', 'def': 'To give arguments that support an idea or a decision', 'ex': 'She made a strong case for starting the exchange earlier.', 'icon': 'message'},
    ],
    'pron_heading': "Say It in <span class='accent'>One Block</span>",
    'pron': ['A drawback', 'To outweigh', 'Overwhelming', 'Although the workload is heavy, I think the benefits outweigh the drawbacks.'],
    'vocab_fill': [
        ('The main ', 'drawback', ' of online classes is that nobody talks to you.'),
        ('Less pressure now, but a longer program: that is the ', 'trade-off', '.'),
        ('I cannot decide between two universities; I am ', 'torn between', ' them.'),
        ('I studied everything the night before the exam; I had to ', 'cram', '.'),
        ('The exchange costs a lot, but it is completely ', 'worthwhile', '.'),
        ('For me, the benefits of the program ', 'outweigh', ' the drawbacks.'),
    ],
    'ch_grammar': {'heading': "The Other Side, <span class='accent'>in One Sentence</span>",
                   'sub': 'Four ways to accept a point without giving up your opinion'},
    'grammar': {
        'heading': "Agree a Little, <span class='accent'>Then Disagree</span>",
        'examples': [
            "<span style='color:#b91c1c;font-weight:700'>Although</span> online classes are flexible, I learn more in a room with people.",
            "<span style='color:#b91c1c;font-weight:700'>Despite</span> the heavy workload, I think the Socratic method is worthwhile.",
            "My brother learned from video games, <span style='color:#1d4ed8;font-weight:700'>whereas</span> I learned from videos.",
            "Cramming works for one exam. <span style='color:#1d4ed8;font-weight:700'>However</span>, it does not work in the long run.",
        ],
        'prompt': 'Each sentence accepts one point and then moves in another direction. Look at what comes right after each red and blue word: a full sentence, or only a noun? And which one starts a new sentence after a period?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Accept a point, then disagree', 'although / even though + subject + verb', '<strong>Although</strong> online classes are flexible, I prefer the room.'),
            ('The same, with a noun', 'despite / in spite of + noun or -ing', '<strong>Despite</strong> the workload, it is worthwhile.'),
            ('Compare two facts', 'clause, whereas / while + clause', 'He learned from games, <strong>whereas</strong> I learned from videos.'),
            ('Contrast two sentences', 'Sentence. However, + sentence', 'It works for one exam. <strong>However</strong>, it does not last.'),
            ('Stronger surprise', 'even though + subject + verb', '<strong>Even though</strong> I read a lot, I still get stuck.'),
            ('Despite with a verb', 'despite + -ing', '<strong>Despite studying</strong> every night, I felt ready.'),
            ('The trap', 'never <em>despite of</em>; never <em>although but</em>', 'Not <em>Although it is hard, but I like it</em>. Say <strong>Although it is hard, I like it</strong>.'),
        ],
        'oneliner': 'Although and whereas take a full sentence, despite takes a noun or -ing, however starts a new sentence, and although never needs but.',
    },
    'grammar_practice': {
        'heading': "Concede, <span class='accent'>Then Decide</span>",
        'items': [
            ('', 'Although', ' online classes are flexible, I learn more in person. (a full sentence follows)'),
            ('', 'Despite', ' the heavy workload, the program is worthwhile. (a noun follows)'),
            ('My brother learned from games, ', 'whereas', ' I learned from videos. (compare two facts)'),
            ('Cramming helps for one test. ', 'However', ', it does not work in the long run. (a new sentence)'),
            ('', 'Despite studying', ' every night, I still felt unprepared. (a verb after despite)'),
            ('', 'Even though', ' I read a lot in English, I still stumble when I speak. (a strong surprise)'),
        ],
    },
    'ch4': {'heading': "A Practice <span class='accent'>Interview</span>",
            'sub': 'One conversation, two recordings, one feedback sheet'},
    'dialogue': {
        'heading': "Question Two, <span class='accent'>No Preparation</span>",
        'guest_name': 'Nathan', 'guest_initial': 'N',
        'lines': [
            ('n', 'Okay, Luiza, this is a practice round. I ask, you answer right away, forty-five seconds each. Ready? Do you think students should study a topic before the class, or after it?'),
            ('l', 'Before, in most cases. <span class="vocab-highlight">Although</span> it takes time, the class makes much more sense when you already know the basic ideas.'),
            ('n', 'Good start. But is there a <span class="vocab-highlight">drawback</span>? Some students say it is <span class="vocab-highlight">overwhelming</span>.'),
            ('l', 'It can be. At my university we do it every night, and the <span class="vocab-highlight">workload</span> is heavy. <span class="vocab-highlight">Despite</span> that, I think the <span class="vocab-highlight">benefits</span> <span class="vocab-highlight">outweigh</span> the drawbacks, at least <span class="vocab-highlight">in the long run</span>.'),
            ('n', 'Nice concession. Next question. Is social media good or bad for language learners?'),
            ('l', 'Honestly, it is <span class="vocab-highlight">a double-edged sword</span>. I learned most of my English from videos, <span class="vocab-highlight">whereas</span> my friends learned in a classroom. However, you can also spend three hours watching and learn nothing.'),
            ('n', 'That example is exactly what the test wants. Last one. Would you rather <span class="vocab-highlight">cram</span> for one big exam, or study a little every week?'),
            ('l', 'A little every week, even though it is less exciting. I <span class="vocab-highlight">took</span> it <span class="vocab-highlight">for granted</span> in school, but when I crammed, I forgot everything in a week.'),
            ('n', 'Good. You hesitated a bit on the second one. Were you <span class="vocab-highlight">torn between</span> the two sides?'),
            ('l', 'A little. But I think the <span class="vocab-highlight">trade-off</span> is <span class="vocab-highlight">worthwhile</span>: I lose two seconds, and I gain a better answer. How long did I take on that one?'),
        ],
        'comp': [
            ('How long does Nathan say each answer should be, and what does he say about preparation?', 'Forty-five seconds each, and she answers right away, with no preparation.'),
            ('What drawback does Nathan say some students mention?', 'That studying before the class is overwhelming.'),
            ('What does Nathan say about her social media example?', 'That it is exactly what the test wants.'),
            ('What does Nathan notice about her second answer?', 'That she hesitated a bit, and he asks whether she was torn between the two sides.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Speaking Coach', 'title': "The Sentence That <span class='accent'>Saves Your Answer</span>",
         'blurb': 'A coach on the TOEFL interview task. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'In the interview task you hear four questions, you have no time to prepare, and you get forty-five seconds for each answer. Most students panic in the first two seconds and try to find a perfect opinion. You do not need a perfect opinion. You need a clear one. Start with your position in one sentence. Give one reason and one real example, because examples are where your English sounds natural. Then, and this is the sentence most students forget, give the other side a moment. Say although, or even though, and accept the strongest point against you. It makes you sound mature, and it gives you ten easy seconds while you think. Finally, come back to your position, so your answer has an end and does not simply stop when the time runs out.',
         'qs': [
             ('How many questions are there, how long is each answer, and how much preparation time is there?', 'Four questions, forty-five seconds each, and no preparation time.'),
             ('What does the coach say you need, instead of a perfect opinion?', 'A clear one.'),
             ('What does the concession sentence do for the speaker, according to the coach?', 'It makes you sound mature and gives you ten easy seconds while you think.'),
         ]},
        {'label': 'Listening 2 &middot; A Radio Debate', 'title': "Should Law Schools <span class='accent'>Stop Cold-Calling?</span>",
         'blurb': 'Two sides of a debate on the Socratic method. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'In many law schools, professors still use the Socratic method: they call on a student without warning and ask questions until the reasoning either holds or falls apart. Supporters say it prepares students for courtrooms, where nobody waits for you to feel ready. They also point out that students who know they may be called on actually do the reading. Critics accept that it creates discipline. However, they argue that it rewards the students who are confident, whereas quieter students, who may understand the case just as well, stay silent to avoid the risk. Some schools have found a middle ground. Instead of calling on anyone at any time, they tell a small group in advance that they will be on call that week. Despite the change, most students still say the method is stressful, but worthwhile.',
         'qs': [
             ('What do supporters say the Socratic method prepares students for, and what do they point out about the reading?', 'For courtrooms, where nobody waits for you to feel ready. Students who may be called on actually do the reading.'),
             ('What do critics accept, and what is their main argument?', 'They accept it creates discipline. They argue it rewards confident students, whereas quieter students stay silent.'),
             ('What middle ground have some schools found, and what do most students still say?', 'They tell a small group in advance that they will be on call that week. Most students still say it is stressful, but worthwhile.'),
         ]},
    ],
    'artifact': {
        'heading': "The Feedback After <span class='accent'>Practice</span>",
        'title': 'MOCK INTERVIEW FEEDBACK', 'subtitle': 'Speaking practice &middot; Candidate: L. Sato Eccheli',
        'rows': [
            ('Question 1', 'Clear position; concession used well', False),
            ('Question 2', 'Strong personal example; 4 seconds of silence at the start', True),
            ('Question 3', 'Good contrast with whereas; answer ended abruptly at 45 seconds', True),
            ('Question 4', 'Complete structure: position, reason, concession, conclusion', False),
            ('Fluency', 'Two restarts in four answers &mdash; fewer than last month', False),
        ],
        'note': 'Coach note: your ideas are strong. Work on the first two seconds: say your position immediately, even before you know your example. And leave five seconds at the end to come back to your position.',
        'qs': [
            ('Which answer had a silence at the start, and how long was it?', 'Question 2, with four seconds of silence.'),
            ('What was the problem with question 3?', 'The answer ended abruptly at forty-five seconds.'),
            ('According to the coach, what should she do in the first two seconds and in the last five?', 'Say her position immediately in the first two seconds, and use the last five to come back to her position.'),
        ],
    },
    'ch5': {'heading': "Train for <span class='accent'>the Interview</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('Although online classes are flexible, but I prefer the classroom.', 'Although online classes are flexible, I prefer the classroom.'),
        ('Despite of the heavy workload, the program is worthwhile.', '<strong>Despite</strong> the heavy workload, the program is worthwhile.'),
        ('Despite it is expensive, the exchange is worthwhile.', '<strong>Although</strong> it is expensive, the exchange is worthwhile.'),
        ('Cramming works for one exam, however it does not last.', 'Cramming works for one exam. <strong>However</strong>, it does not last.'),
    ],
    'speaking': [
        ('Should students study a topic before the class or after it?', 'Before, in most cases. Although it takes time, the class makes more sense, and in the long run you remember more.'),
        ('Is social media good or bad for language learners?', 'It is a double-edged sword. I learned most of my English from videos, whereas some friends only got distracted.'),
        ('Would you rather cram for one exam or study a little every week?', 'A little every week, even though it is less exciting, because when I cram, I forget everything.'),
        ('Is it better to study abroad for one semester or for a whole year?', 'A whole year, despite the cost, because the first semester is mostly about settling in.'),
    ],
    'building': [
        ('although / online classes / flexible / I / learn more in person (a full sentence)', 'Although online classes are flexible, I learn more in person.'),
        ('despite / the heavy workload / the program / worthwhile (a noun)', 'Despite the heavy workload, the program is worthwhile.'),
        ('my brother / learn from games / whereas / I / learn from videos (compare)', 'My brother learned from games, whereas I learned from videos.'),
        ('cramming / work for one exam / however / not work in the long run (two sentences)', 'Cramming works for one exam. However, it does not work in the long run.'),
    ],
    'roleplays': {
        'heading': "The Same Interview, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Nathan Asks <span class='accent'>Again</span>",
             'scenario': 'Nathan asks the same three questions from the practice round. Answer each one in forty-five seconds, with a position, a reason, a concession with although or despite, and a return to your position.',
             'chips': ['Although', 'Despite', 'the benefits outweigh', 'in the long run']},
            {'heading': "The Socratic <span class='accent'>Debate</span>",
             'scenario': 'Your teacher defends the Socratic method used at GV. You disagree, or partly agree. Accept one of their points with a concession, compare two kinds of students with whereas, and give your own experience.',
             'chips': ['whereas', 'a drawback', 'overwhelming', 'worthwhile']},
            {'heading': "Four Questions, <span class='accent'>No Preparation</span>",
             'scenario': 'Your teacher asks four new opinion questions, one after the other, like the real interview task. You start speaking as soon as each question ends.',
             'footer': 'No notes, forty-five seconds each, and no preparation. Say your position in the first two seconds.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for <span class='accent'>Any Opinion</span>", 'sub': 'What you say in the first seconds, and in the last'},
    'survival_heading': "Five Sentences for <span class='accent'>Any Opinion</span>",
    'survival': [
        'In my opinion, students should study the topic before the class.',
        'Although it takes time, the benefits outweigh the drawbacks.',
        'Despite the heavy workload, I think it is worthwhile in the long run.',
        'I learned from videos, whereas my friends learned in a classroom.',
        'So, for all these reasons, I still believe the effort is worth it.',
    ],
    'checklist': [
        'I can answer an opinion question in forty-five seconds with no preparation.',
        'I use although and even though with a full sentence, and never add but.',
        'I use despite with a noun or -ing, and never say despite of.',
        'I use whereas to compare two facts and however to start a new sentence.',
        'I know the words: a drawback, a benefit, to outweigh, a trade-off, to be torn between, in the long run, a workload, to cram, overwhelming, worthwhile, to take for granted, a double-edged sword, to make a case for.',
    ],
    'badge': {'name': 'The Forty-Five Second Opinion', 'line': 'A position in two seconds, a concession in the middle, and an answer that ends on purpose.',
              'next': 'Next lesson: The First Draft -- planning an essay about your future, in reading and writing'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we train the new TOEFL interview task: four questions, forty-five seconds each, no preparation.\' FATO: e a tarefa Take an Interview do speaking desde janeiro de 2026. Ela disse que o metodo socratico da GV nao funciona para ela: esse tema entra no warm-up e no role-play, e ela tem opiniao forte &mdash; deixe falar. Nao corrija durante as respostas cronometradas.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta sobre estudar na vespera. Callback das aulas 7 e 8: exija uma causativa (\'I had my schedule changed\') e um modal de obrigacao (\'we must read everything\'). ANOTE se ela ja faz concessao sozinha (\'but\' ou \'although\').',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 4 movimentos. Diga que a concessao da tempo para pensar &mdash; e o truque que tira a trava dos primeiros segundos. Nao de a regra ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Cronometre 45 segundos exatos e comece a contar quando terminar de ler a pergunta. ANOTE: segundos de silencio no inicio, se houve concessao, se a resposta terminou ou foi cortada. E o benchmark do role-play livre.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words for weighing two sides.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'a drawback x a benefit\': \'Which one is a problem? (Drawback.)\' CCQ \'to outweigh\': \'If the benefits outweigh the drawbacks, is it a good idea? (Sim.)\' CCQ \'a trade-off\': \'Do you win everything? (Nao, perde uma coisa para ganhar outra.)\' CCQ \'to be torn between\': \'Easy or difficult decision? (Dificil.)\'',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'in the long run\': \'Tomorrow, or after a long time? (Longo prazo.)\' CCQ \'to cram\': \'Every week, or the night before? (Vespera.)\' CCQ \'overwhelming\': \'A little work or too much? (Demais.)\' CCQ \'worthwhile\': \'Worth the effort? (Sim.)\' Pronuncia: o-ver-WHELM-ing.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'to take for granted\': \'Do you appreciate it? (Nao.)\' CCQ \'a double-edged sword\': \'Only good, only bad, or both? (Os dois.)\' CCQ \'to make a case for\': \'Are you giving arguments for or against? (A favor.)\'',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> DRAW-back, out-WEIGH (acento na segunda), o-ver-WHELM-ing. Na frase longa, dois blocos com pausa na virgula: \'Although the workload is heavy / I think the benefits outweigh the drawbacks.\'',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ela diz a palavra ANTES de clicar, escolhendo do banco. Se fechar rapido, peca uma frase com \'a double-edged sword\' sobre redes sociais.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences that accept one point and then move on.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'What comes after although? After despite? Which one starts a new sentence?\' Espere ela ver: although + frase, despite + nome, however depois de ponto. So entao Reveal the Rule. CCQ: \'Despite it is expensive &mdash; correct? (Nao: despite + nome; although + frase.)\' CCQ: \'Although it is hard, but I like it &mdash; correct? (Nao: sem but.)\' Obstaculos do brasileiro: \'despite of\' (calco de \'apesar de\') e \'although... but\' (calco de \'embora... mas\').',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na quarta, cobre a pausa do ponto e da virgula depois de however.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now a practice interview with a coach, two recordings, and the feedback sheet.\'',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e o Nathan: coach de speaking, americano, direto e encorajador. Clique Next Line e toque o audio. Nas falas da Luiza, ela fala PRIMEIRO. PRAGMATICA: repare que todas as respostas da Luiza comecam com a posicao na primeira frase (\'Before, in most cases\', \'A little every week\') e so depois vem a concessao. E no fim ela pergunta o tempo: um candidato que se mede.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre o NATHAN, nunca sobre a Luiza (REGRA 27F). Depois pergunte qual das tres respostas dela ela acha mais forte.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Os dados do formato (quatro perguntas, 45 segundos, sem preparo) sao os da tarefa Take an Interview desde 2026.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Debate de radio sobre o metodo socratico nas faculdades de Direito &mdash; e a rotina dela. Depois das respostas, pergunte de que lado ela esta, com uma concessao.',
        'artifact': '<strong>Artefato (4 min):</strong> Folha de feedback ficticia de simulado, com o nome dela. Peca que ela comente cada linha com contraste: \'Although my example was strong, I was silent for four seconds.\' So depois as 3 perguntas.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\'',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros: although + but, despite of, despite + frase, however sem ponto. Enquadramento: \'os mais comuns\'.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca cada pergunta e cronometre 45 segundos. As respostas na tela sao sugestao. Correcao em bloco, so depois das quatro, no maximo tres pontos.',
        'building': '<strong>Sentence Building (4 min):</strong> Ela monta a frase COMPLETA em voz alta antes de clicar, marcando a pausa da virgula.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same interview, three times. The last one is four new questions, just like the test.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o Nathan. Tres perguntas, 45 segundos cada, os quatro movimentos. Corrija so although/despite, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce defende o metodo socratico. Ela discorda ou concorda em parte, com concessao e whereas. Seja um oponente de verdade: ela e reflexiva e argumenta bem quando o tema e dela.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Quatro perguntas novas de opiniao, uma atras da outra, 45 segundos cada, sem preparo (sugestoes: celular na sala de aula, estudar sozinha ou em grupo, morar sozinha ou com colega, livro ou filme). No fim, compare os segundos de silencio iniciais com o diagnostico do slide 4.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you answered one question. Now you have a structure for any question, in forty-five seconds.\'',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. A primeira e a ultima sao o inicio e o fim de qualquer resposta: peca que ela decore as duas.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 9. Item em que ela hesitar entra no warm-up da aula 10.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, you do not need a perfect opinion. You need a clear one, in the first two seconds.\' Homework (ORALMENTE, nunca escrito na tela): gravar quatro respostas de 45 segundos para quatro perguntas de opiniao que ela mesma escolher, sem preparo, e trazer a com mais silencio no inicio. Proxima aula: planejar um texto sobre o futuro, em leitura e escrita.',
    },
    'pc': {
        'title': 'Forty-Five Seconds of Opinion -- Concession and Contrast',
        'desc': 'Four questions, no preparation. Give a clear opinion, accept the other side in one sentence, and come back to your position.',
        'match_idx': [0, 2, 3, 7, 9, 11],
        'context': [
            'The strongest spoken opinions are not the most extreme ones. They are the ones that accept one point from the other side and still reach a clear conclusion. English has a small set of words for that move, and each one follows its own rule.',
            '<strong>Although</strong> and <strong>even though</strong> introduce a full sentence, with a subject and a verb: &ldquo;<strong>Although</strong> online classes are flexible, I learn more in person.&rdquo; A very common mistake is to add <em>but</em> in the second part, because many languages allow both words in one sentence. English does not: the <em>although</em> already does the job.',
            '<strong>Despite</strong> and <strong>in spite of</strong> are followed by a noun or an <em>-ing</em> form, never by a full sentence, and there is no <em>of</em> after despite: &ldquo;<strong>Despite</strong> the heavy <strong>workload</strong>, the program is <strong>worthwhile</strong>.&rdquo; To compare two facts side by side, use <strong>whereas</strong>: &ldquo;My brother learned from games, <strong>whereas</strong> I learned from videos.&rdquo;',
            '<strong>However</strong> is different: it connects two separate sentences, so it usually comes after a period and before a comma: &ldquo;<strong>Cramming</strong> works for one exam. <strong>However</strong>, it does not work <strong>in the long run</strong>.&rdquo; Used well, one concession gives your answer a mature voice, and ten extra seconds to think about what comes next.',
        ],
        'context_quiz': [
            ('According to the text, what is wrong with &ldquo;Although it is hard, but I like it&rdquo;?', ['Although needs a noun after it.', 'English does not use but after although.', 'Hard should be difficult.'], 1),
            ('What follows despite?', ['A noun or an -ing form.', 'A full sentence with a subject and a verb.', 'The word of.'], 0),
            ('Where does however usually go?', ['In the middle of one sentence, after although.', 'Before despite.', 'After a period, at the start of a new sentence.'], 2),
        ],
        'tip_title': 'Concession and Contrast',
        'tip_lead': 'Although + sentence, despite + noun or -ing, whereas to compare, however to start a new sentence.',
        'tip_rows': [
            ('Concession', 'although / even though + subject + verb', '<strong>Although</strong> it is hard, I like it.'),
            ('Concession with a noun', 'despite / in spite of + noun', '<strong>Despite</strong> the cost, it is worthwhile.'),
            ('Concession with a verb', 'despite + -ing', '<strong>Despite studying</strong> hard, I was nervous.'),
            ('Compare two facts', 'clause, whereas + clause', 'He likes games, <strong>whereas</strong> I like books.'),
            ('Contrast two sentences', 'Sentence. However, sentence.', 'It is fast. <strong>However</strong>, it is expensive.'),
            ('Strong surprise', 'even though + subject + verb', '<strong>Even though</strong> I read a lot, I get stuck.'),
        ],
        'tip_never': 'although it is hard, but I like it &middot; despite of the workload &middot; despite it is expensive &middot; it works, however it does not last',
        'blanks': [
            ('', 'Although', ' online classes are flexible, I learn more in person.', 'Hint: a full sentence follows, and no but later -- one word', None),
            ('', 'Despite', ' the heavy workload, the program is worthwhile.', 'Hint: a noun follows, and no of -- one word', None),
            ('My brother learned from games, ', 'whereas', ' I learned from videos.', 'Hint: compare two facts side by side -- one word', None),
            ('Cramming works for one exam. ', 'However', ', it does not work in the long run.', 'Hint: starts a new sentence after a period -- one word', None),
            ('For me, the benefits ', 'outweigh', ' the drawbacks.', 'Hint: are more important than -- one word', None),
            ('The exchange is expensive, but it is completely ', 'worthwhile', '.', 'Hint: worth the effort and the money -- one word', None),
        ],
        'order_title': 'Put the Answer in Order',
        'order_lead': 'An interviewer asks whether students should study a topic before the class. Put your forty-five-second answer in a logical order.',
        'order': [
            'In my opinion, students should study the topic before the class.',
            'The main reason is that the class makes much more sense.',
            'At my university, for example, we read every case the night before.',
            'Although the workload can be overwhelming, you learn more in the long run.',
            'Some students prefer to review after the class, whereas I need the preparation first.',
            'So, for all these reasons, I still believe studying before is worthwhile.',
        ],
        'quiz': [
            ('You want to accept a point and then disagree. You say:', ['Although it is expensive, but I think it is worthwhile.', 'Although it is expensive, I think it is worthwhile.', 'Despite it is expensive, I think it is worthwhile.'], 1),
            ('You want to use despite correctly. You say:', ['Despite the heavy workload, I enjoy the course.', 'Despite of the heavy workload, I enjoy the course.', 'Despite the workload is heavy, I enjoy the course.'], 0),
            ('You want to compare how you and your brother learned. You say:', ['I learned from videos, despite he learned from games.', 'I learned from videos, however he learned from games.', 'I learned from videos, whereas he learned from games.'], 2),
            ('The interviewer asks a hard question and you need a second. You start with:', ['Your position, in one clear sentence.', 'A long silence until you find a perfect example.', 'I do not know, sorry.'], 0),
        ],
        'think': 'Answer this interview question in forty-five seconds, with no preparation: &ldquo;Is it better to study abroad for one semester or for a whole year?&rdquo; Give your position in the first sentence, one reason and one example, a concession with although or despite, and a clear conclusion.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'TOEFL (ETS) &mdash; &ldquo;TOEFL iBT Speaking Question 1: Independent Speaking&rdquo; (YouTube)',
         'desc': 'From the official TOEFL channel: how to structure a spoken opinion with a clear position, reasons and examples. The task format has changed since 2026, but the structure of a good opinion has not.',
         'tip': 'Tip: pause after each tip and answer one opinion question in forty-five seconds, adding a concession with although.',
         'url': 'https://www.youtube.com/watch?v=NHPwR3En_1A', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'The Good Wife &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'A lawyer returns to work and has to argue every case, often accepting the other side&rsquo;s best point before she wins. Excellent for the language of concession in real American English.',
         'tip': 'Tip: when a lawyer says although, despite or however, pause and repeat the sentence with the same rhythm.',
         'url': 'https://www.tvmaze.com/episodes/6799/the-good-wife-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Julia Dhar &mdash; &ldquo;How to disagree productively and find common ground&rdquo; (TED)',
         'desc': 'A world debating champion on how to disagree well: find the common ground, separate the idea from the person, and accept a good point. Everything in this lesson, in eleven minutes.',
         'tip': 'Tip: summarize her three tips, and give one example from a discussion at GV.',
         'url': 'https://www.ted.com/talks/julia_dhar_how_to_disagree_productively_and_find_common_ground', 'cta': 'Watch on TED'},
    ],
}
