# -*- coding: utf-8 -*-
# Aula 6 -- How the TOEFL Reads You (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "How the TOEFL <span class='accent'>Reads You</span>",
    'hero_line': 'The answer is almost never written in the text, and the modals that let you say what must be true',
    'menu_desc': 'The new TOEFL reading section, inference, and the modals of deduction -- 35 slides',
    'grammar_point': 'modals of deduction in the present and in the past',
    'phases': ['The Clock', 'Words of the Test', 'The Text Itself', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'daniel', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch2': U + 'photo-1456513080510-7bf3a84b82f8?w=1400&q=80',
        'ch3': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_grammar': U + 'photo-1488190211105-8b0e65b80b4e?w=1400&q=80',
        'ch5': U + 'photo-1497633762265-9d179a990aa6?w=1400&q=80',
        'ch_rp': U + 'photo-1522202176988-66273c2fd55f?w=1400&q=80',
        'pc': U + 'photo-1434030216411-0b793f4b4173?w=600&q=80',
    },
    'warmup': {
        'heading': "Fiction in Minutes, Law <span class='accent'>in Hours</span>",
        'sub': 'You read novels in English easily and law texts slowly. What exactly is different when you read a law text?',
    },
    'target': {
        'heading': "Read Like the <span class='accent'>Test Reads You</span>",
        'steps': [
            'Skim for the main idea before you look for any detail.',
            'Infer: the answer is usually true because of the text, not written in it.',
            'Eliminate the distractor that repeats the text&rsquo;s words but changes its meaning.',
        ],
    },
    'diagnostic': {
        'heading': "The Library Notice on <span class='accent'>the Door</span>",
        'p1': 'A notice on the library door says: &ldquo;From Monday, the second floor will be reserved for silent study. Group rooms can be booked online only.&rdquo;',
        'p2': 'Say three things that must be true, or are probably true, even though the notice does not say them directly.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Test</span>",
            'sub': 'Thirteen words about reading under a clock, and about the traps inside the questions'},
    'vocab': [
        {'word': 'To skim', 'def': 'To read something quickly to get the general idea, without reading every word', 'ex': 'Skim the passage first, and then read the questions.', 'icon': 'eye'},
        {'word': 'To scan', 'def': 'To look quickly through a text to find one particular piece of information', 'ex': 'Scan the email for the date of the meeting.', 'icon': 'filter'},
        {'word': 'To infer', 'def': 'To reach an idea from what a text suggests, even if it does not say it directly', 'ex': 'From the last paragraph, you can infer that the author disagrees.', 'icon': 'compass'},
        {'word': 'An inference', 'def': 'An idea you reach from the information you have, not from a direct statement', 'ex': 'The question asks for an inference, not for a fact.', 'icon': 'target'},
        {'word': 'A passage', 'def': 'A short part of a text, used for reading questions in a test', 'ex': 'The academic passage is shorter in the new version of the test.', 'icon': 'doc'},
        {'word': 'A distractor', 'def': 'A wrong answer in a multiple-choice question that is designed to look right', 'ex': 'The distractor used the same words as the text, but changed the meaning.', 'icon': 'alert'},
        {'word': 'A context clue', 'def': 'A word or a phrase near an unknown word that helps you understand it', 'ex': 'Use the context clues instead of stopping on the word.', 'icon': 'key'},
        {'word': 'To eliminate', 'def': 'To remove something because it is wrong or not needed', 'ex': 'Eliminate two options first, and the choice becomes easier.', 'icon': 'shield'},
        {'word': 'Adaptive', 'def': 'Describes a test that changes its next questions based on your earlier answers', 'ex': 'The reading section is adaptive, so the second part depends on the first.', 'icon': 'refresh'},
        {'word': 'A module', 'def': 'One separate part of a test or a course', 'ex': 'Your score in the first module decides the level of the second module.', 'icon': 'layers'},
        {'word': 'To pace yourself', 'def': 'To control your speed so that you have enough time or energy until the end', 'ex': 'Pace yourself, or you will run out of time in the last passage.', 'icon': 'clock'},
        {'word': 'To second-guess', 'def': 'To doubt a decision you have already made, and change it without a good reason', 'ex': 'Do not second-guess your first answer unless the text proves it wrong.', 'icon': 'message'},
        {'word': 'A hunch', 'def': 'A feeling that something is true, without clear proof', 'ex': 'Check your hunch against the text before you choose.', 'icon': 'zap'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A distractor', 'Adaptive', 'To eliminate', 'The answer must be in the text, but it cannot be written word for word.'],
    'ch3': {'heading': "The Text About <span class='accent'>Your Test</span>",
            'sub': 'Four short paragraphs. Read once for the argument; the detail comes after.'},
    'reading': {
        'heading': "The Answer Is Not <span class='accent'>on the Page</span>",
        'rtitle': 'The Answer Is Not on the Page',
        'paras': [
            'Students who read well in their own language often struggle with the TOEFL reading section, and the reason is rarely vocabulary. They read every word, look for the sentence that contains the answer, and lose time when that sentence is not there. In most questions it is not there, because the test is not checking whether you can find words. It is checking whether you can understand what the words mean together.',
            'Since January 2026, the section has three kinds of tasks. In one, you complete missing letters in short academic paragraphs, which tests whether you recognize words from their context. In another, you read short texts from daily life, such as emails, notices and posts. In the third, you read an academic passage, which is shorter than in the old version of the test. The section is also adaptive: the first module decides how difficult the second one will be.',
            'Across all three tasks, the hardest questions ask for an inference. A notice that says the library will close at nine does not say that students cannot study there at ten, but that must be true. The wrong options are not random. A good distractor repeats words from the text and changes one small thing, so a student who scans for familiar words chooses it with confidence.',
            'The strategy that works is almost the opposite of careful reading. Skim first for the main idea, pace yourself so that the last passage gets the same attention as the first, and eliminate options that could be true but are not supported by the text. And once you have chosen, do not second-guess yourself because of a hunch. Change an answer only when a line in the text proves that you were wrong.',
        ],
        'source': 'Written for this lesson, from the publicly described format of the TOEFL iBT reading section as of 2026.',
    },
    'gist': {
        'prompt': 'What is the main argument of the text?',
        'choices': [
            ['a', 'Students fail the reading section because their vocabulary is too small.', False],
            ['b', 'The reading section tests understanding and inference, so the best strategy is to skim, pace yourself and eliminate, not to hunt for words.', True],
            ['c', 'The new reading section is much easier than the old one, so preparation is less important.', False],
        ],
    },
    'tf': [
        ['According to the text, good readers usually fail because of vocabulary.', 'f', 'The text says the reason is rarely vocabulary; they look for sentences that are not there.'],
        ['The academic passage is shorter than it was in the old test.', 't', 'The text says you read an academic passage which is shorter than in the old version.'],
        ['In the adaptive design, the difficulty of the second module depends on the first.', 't', 'The text says the first module decides how difficult the second one will be.'],
        ['A good distractor uses completely different words from the text.', 'f', 'The text says a good distractor repeats words from the text and changes one small thing.'],
        ['The author recommends changing an answer whenever you have a hunch.', 'f', 'The text says to change an answer only when a line in the text proves you were wrong.'],
    ],
    'artifact': {
        'heading': "Your Practice <span class='accent'>Report</span>",
        'title': 'READING PRACTICE REPORT', 'subtitle': 'Practice set 1 &middot; Candidate: L. Sato Eccheli',
        'rows': [
            ('Complete the Words', '9 of 10 correct', False),
            ('Read in Daily Life', '6 of 8 correct &mdash; both errors on inference questions', True),
            ('Academic Passage', '5 of 8 correct &mdash; last 3 questions left blank', True),
            ('Time used', 'Ran out of time in the final passage', False),
            ('Changed answers', '4 changed; 3 of them were right before the change', False),
        ],
        'note': 'Tutor note: your vocabulary is not the problem. You lost points on inference, you did not pace yourself, and you second-guessed answers that were correct. Next set: skim first, and do not change an answer without a line of proof.',
        'qs': [
            ('Which task had the best result, and which kind of question caused the errors in Read in Daily Life?', 'Complete the Words, 9 of 10. The errors were on inference questions.'),
            ('What happened in the academic passage, and why?', 'She got 5 of 8 and left the last 3 blank, because she ran out of time.'),
            ('According to the tutor, what are the three real problems?', 'Inference, not pacing herself, and second-guessing correct answers.'),
        ],
    },
    'ch_grammar': {'heading': "What Must Be True, <span class='accent'>What Can&rsquo;t</span>",
                   'sub': 'Four sentences about the library notice, and how sure each speaker is'},
    'grammar': {
        'heading': "How Sure <span class='accent'>Are You?</span>",
        'examples': [
            "The library closes at nine, so students <span style='color:#b91c1c;font-weight:700'>can&rsquo;t be</span> there at ten.",
            "The group rooms are booked online, so there <span style='color:#b91c1c;font-weight:700'>must be</span> a booking website.",
            "She left the last three questions blank. She <span style='color:#1d4ed8;font-weight:700'>must have run</span> out of time.",
            "He changed his answer. He <span style='color:#1d4ed8;font-weight:700'>might have had</span> a hunch, or he <span style='color:#1d4ed8;font-weight:700'>may have</span> found proof.",
        ],
        'prompt': 'Nobody in these sentences knows for sure. How certain is each speaker: almost certain yes, almost certain no, or only possible? And which two sentences are about the past?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Almost certain it is true (now)', 'must + base verb', 'There <strong>must be</strong> a booking website.'),
            ('Almost certain it is not true (now)', 'can&rsquo;t / couldn&rsquo;t + base verb', 'They <strong>can&rsquo;t be</strong> there at ten.'),
            ('Possible (now)', 'might / may / could + base verb', 'It <strong>might be</strong> a distractor.'),
            ('Almost certain (past)', 'must have + past participle', 'She <strong>must have run</strong> out of time.'),
            ('Almost certain it did not happen (past)', 'can&rsquo;t have / couldn&rsquo;t have + past participle', 'He <strong>can&rsquo;t have read</strong> the whole passage.'),
            ('Possible (past)', 'might have / may have / could have + past participle', 'He <strong>might have had</strong> a hunch.'),
            ('The trap', 'never <em>mustn&rsquo;t</em> for deduction; never <em>must to</em>', 'Not <em>He mustn&rsquo;t be there</em>. Say <strong>He can&rsquo;t be there</strong>.'),
        ],
        'oneliner': 'Must for almost yes, can&rsquo;t for almost no, might for maybe, and add have + participle for the past.',
    },
    'grammar_practice': {
        'heading': "Deduce It, <span class='accent'>Don&rsquo;t Guess It</span>",
        'items': [
            ('The notice says the second floor is silent, so group work ', 'must be', ' on another floor. (almost certain, now)'),
            ('The library closes at nine, so students ', 'can&rsquo;t be', ' inside at ten. (almost certain no, now)'),
            ('She left three questions blank, so she ', 'must have run', ' out of time. (almost certain, past)'),
            ('He finished in ten minutes, so he ', 'can&rsquo;t have read', ' the whole passage. (almost certain no, past)'),
            ('I am not sure why she changed it. She ', 'might have had', ' a hunch. (possible, past)'),
            ('That option repeats the text&rsquo;s words, so it ', 'could be', ' a distractor. (possible, now)'),
        ],
    },
    'detective': [
        ('He mustn&rsquo;t be at home; the lights are off.', 'He <strong>can&rsquo;t be</strong> at home; the lights are off.'),
        ('She must to have studied a lot for this test.', 'She <strong>must have studied</strong> a lot for this test.'),
        ('They can&rsquo;t have read it yesterday, so they read it today must.', 'They can&rsquo;t have read it yesterday, so they <strong>must have read it today</strong>.'),
        ('He might has made a mistake in the last passage.', 'He <strong>might have made</strong> a mistake in the last passage.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>",
            'sub': 'What the text says and what it means &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "What the Text Says, <span class='accent'>What It Means</span>",
    'equiv': {
        'title': 'Match each line from a notice to the inference it supports',
        'hint': 'Tap a line from the notice, then tap the inference that must be true',
        'pairs': [
            ('The library will close at 9 p.m. during the holiday week.', 'Students cannot study in the library late at night that week.'),
            ('Group rooms can be booked online only.', 'You cannot book a group room by asking at the front desk.'),
            ('The second floor is now reserved for silent study.', 'Group discussions have to happen somewhere else.'),
            ('Laptops must be connected to the new network by Friday.', 'The old network will probably stop working after Friday.'),
            ('This notice replaces the one posted in March.', 'Some of the rules from March are no longer valid.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Tutor&rsquo;s Advice</span>",
    'gap': {
        'parts': [
            'Do not read every word of the ', ['1', 'passage'], '. First ', ['2', 'skim'], ' it for the main idea, and only then ',
            ['3', 'scan'], ' for the detail that the question needs. When you meet an unknown word, use a ', ['4', 'context clue'],
            ' instead of stopping. Many questions ask you to ', ['5', 'infer'], ', so the answer will not be written word for word. ',
            ['6', 'Eliminate'], ' the options that are not supported by the text, and be careful with the ', ['7', 'distractor'],
            ' that repeats the text&rsquo;s words. Finally, ', ['8', 'pace yourself'], ', so the last passage gets the same attention as the first.',
        ],
        'bank': ['passage', 'skim', 'scan', 'context clue', 'infer', 'Eliminate', 'distractor', 'pace yourself'],
    },
    'quickfire': [
        {'situation': 'A classmate reads every word of the passage before looking at the questions. Give advice in two sentences.', 'tips': ['Skim the passage first for the main idea, and then scan for the detail each question needs. Reading every word will make you run out of time.', 'skim first, scan later.']},
        {'situation': 'A student finished the reading section in ten minutes. Say what must be true.', 'tips': ['He can&rsquo;t have read the passages carefully, so he must have skipped some questions.', 'can&rsquo;t have + participle, must have + participle.']},
        {'situation': 'Explain what a distractor is, without using the word distractor.', 'tips': ['It is a wrong answer that uses the same words as the text, so it looks right.', 'A relative clause: a wrong answer that looks right.']},
        {'situation': 'Your friend changed three correct answers at the end. Say what probably happened.', 'tips': ['She must have second-guessed herself, or she might have followed a hunch instead of the text.', 'must have / might have.']},
        {'situation': 'Describe the adaptive design of the reading section in one sentence.', 'tips': ['The section is adaptive, so the level of the second module depends on how you did in the first.', 'adaptive, a module.']},
        {'situation': 'You see an option that could be true but is not in the text. Say what you do.', 'tips': ['I eliminate it, because it might be true in real life, but the text does not support it.', 'eliminate, might be.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Tutor', 'title': "Stop Looking for <span class='accent'>the Sentence</span>",
         'blurb': 'A TOEFL tutor on inference questions. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'The students who read the most are often the slowest on the reading section, and I think I know why. They were trained to find the answer in the text. They see a question, go back to the passage, and look for the sentence that says it. On an inference question, that sentence does not exist. The text gives you two facts, and the answer is what must be true if both facts are true. So here is the exercise I give everyone. Before you look at the options, answer the question in your own words. If your answer is something the text could not possibly support, you are guessing. If it follows from two sentences, you have made an inference. Then look at the options, and choose the one that says your answer in different words.',
         'qs': [
             ('Why does the tutor think the students who read the most are often the slowest?', 'They were trained to find the sentence that contains the answer, and on inference questions that sentence does not exist.'),
             ('What is an inference, according to her?', 'What must be true if two facts in the text are both true.'),
             ('What exercise does she give everyone?', 'Answer the question in your own words before looking at the options, and then choose the option that says it in different words.'),
         ]},
        {'label': 'Listening 2 &middot; A Campus Announcement', 'title': "The Library, <span class='accent'>This Week</span>",
         'blurb': 'A short announcement, like a Read in Daily Life text, but spoken. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Good morning, everyone. A few changes at the law library this week. Because of the exam period, the second floor is now reserved for silent study, and phones must be switched off before you go up the stairs. The group rooms on the first floor are in high demand, so they can only be booked online, for a maximum of two hours. If you booked a room last week by email, please book it again on the website, because those requests were not saved. On Friday the library closes at six instead of ten, for maintenance. And finally, the printer on the ground floor is not working. The one on the first floor is.',
         'qs': [
             ('Why is the second floor now reserved for silent study?', 'Because of the exam period.'),
             ('A student booked a room by email last week. What must be true, and what should they do?', 'Their request was not saved, so they must book it again on the website.'),
             ('On Friday, can a student study in the library at eight in the evening? Where can they print?', 'No, the library closes at six on Friday. They can print on the first floor.'),
         ]},
    ],
    'roleplays': {
        'heading': "The Same Test, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Read the <span class='accent'>Report</span>",
             'scenario': 'Look at the practice report again. Tell your tutor what must have happened in each task, what cannot have been the problem, and what you will change in the next set.',
             'chips': ['must have run out of time', 'can&rsquo;t have been vocabulary', 'to pace yourself', 'to second-guess']},
            {'heading': "Teach a <span class='accent'>Classmate</span>",
             'scenario': 'A classmate at GV is taking a practice test next week and reads every word. Explain the three tasks, the adaptive design, and two strategies, and ask what their biggest problem is.',
             'chips': ['to skim', 'a distractor', 'adaptive', 'a module']},
            {'heading': "Two Minutes, <span class='accent'>No Notes</span>",
             'scenario': 'Your teacher reads a short notice out loud. Say four things that must be true, cannot be true, or might be true, even though the notice does not say them.',
             'footer': 'No notes, two minutes. Use must, can&rsquo;t and might, and add have for the past at least once.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>the Reading Section</span>",
    'survival': [
        'The answer must be supported by the text, even if it is not written word for word.',
        'That option repeats the words of the passage, so it could be a distractor.',
        'She left three questions blank, so she must have run out of time.',
        'He finished in ten minutes, so he cannot have read the whole passage.',
        'I will not change my answer unless a line in the text proves it wrong.',
    ],
    'checklist': [
        'I know the three kinds of tasks in the new TOEFL reading section.',
        'I skim for the main idea before I scan for details.',
        'I use must, can&rsquo;t and might to say how sure I am, and must have for the past.',
        'I eliminate options that the text does not support, even if they could be true.',
        'I know the words: to skim, to scan, to infer, an inference, a passage, a distractor, a context clue, to eliminate, adaptive, a module, to pace yourself, to second-guess, a hunch.',
    ],
    'badge': {'name': 'The Inference Reader', 'line': 'What must be true, what can&rsquo;t be, and the line of text that proves it.',
              'next': 'Next lesson: The Tutorial Voice -- explaining a process, in conversation'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we look at how the TOEFL reads you.\' Contexto: ela disse que le ficcao em ingles sem esforco e que o problema e a demora nos textos da faculdade. FATO para voce: desde janeiro de 2026 o reading do TOEFL tem tres tarefas (Complete the Words, Read in Daily Life, Read an Academic Passage) e e adaptativo em dois modulos. O texto de hoje e sobre isso, e e curto.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta. Callback das aulas 4 e 5: exija uma relativa (\'a text which...\') e uma condicional (\'if I had more time, I would...\'). ANOTE o que ela diz que torna o texto de Direito lento: e o diagnostico da estrategia de hoje.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Diga que e quase o contrario da leitura cuidadosa que a GV exige: no teste, ler cada palavra custa pontos. Nao de a regra dos modais ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Ela diz tres coisas que devem ser verdade pelo aviso. Aceite em qualquer forma. ANOTE se ela ja usa \'must\' para deducao ou so \'I think\'.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words about reading under a clock.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'to skim x to scan\': \'Main idea or one detail? (Skim = ideia geral; scan = detalhe.)\' CCQ \'to infer\': \'Is it written in the text? (Nao, e deduzido.)\' CCQ \'a passage\': \'Is it the whole book? (Nao, um trecho.)\'',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a distractor\': \'Right or wrong answer? (Errada que parece certa.)\' CCQ \'to eliminate\': \'Do you choose it or remove it? (Remove.)\' CCQ \'adaptive\': \'Is the second module the same for everybody? (Nao.)\' Pronuncia: dis-TRAC-tor, a-DAP-tive, e-LIM-i-nate.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'to pace yourself\': \'Fast at the start and slow at the end? (Nao, ritmo constante.)\' CCQ \'to second-guess\': \'Is there new proof? (Nao, so duvida.)\' CCQ \'a hunch\': \'Feeling or proof? (Sensacao.)\' Pergunte se ela ja trocou resposta certa numa prova da GV.',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> dis-TRAC-tor, a-DAP-tive, e-LIM-i-nate. Na frase longa, dois blocos: \'The answer must be in the text / but it cannot be written word for word.\' Cobre o can\'t americano (/ae/), diferente do britanico.',
        'matching': '<strong>Matching (3 min):</strong> Ela liga palavra e definicao. Se errar, volte ao CCQ do card.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'Four paragraphs about the test you are taking. Skim it: I will stop you after two minutes.\'',
        'reading': '<strong>Leitura (5 min):</strong> Hoje ela PRATICA o que o texto diz: dois minutos de skim, cronometrado, e voce para. Pergunte a ideia central. So depois ela le de novo para o detalhe. Compare com o tempo das aulas 2 e 4.',
        'gist': '<strong>Gist (3 min):</strong> Ela escolhe e justifica por que as outras duas estao erradas &mdash; e exatamente eliminar distrator.',
        'tf': '<strong>True or False (6 min):</strong> Ela diz TRUE ou FALSE e LE a linha que prova antes de clicar. Repare que a quarta afirmacao e um distrator classico: aponte.',
        'artifact': '<strong>Artefato (4 min):</strong> Relatorio de simulado ficticio, com o nome dela. Peca que ela deduza com modais o que aconteceu em cada linha: \'She must have run out of time.\' So depois as 3 perguntas. Pergunte se o relatorio se parece com ela.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about the library notice. Nobody knows for sure. How sure is each one?\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Almost certain yes, almost certain no, or only possible? Which are about the past?\' Espere ela ver. So entao Reveal the Rule. CCQ: \'She must have run out of time &mdash; do we know for sure? (Nao, mas quase certeza.)\' CCQ: \'He can\'t have read the whole passage &mdash; did he read it? (Quase certo que nao.)\' Obstaculo numero um do brasileiro: \'mustn\'t\' para deducao negativa (mustn\'t e proibicao; para deducao e can\'t). Obstaculo dois: \'must to\'.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na quarta, cobre can\'t have + participio.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros: mustn\'t para deducao, must to, ordem da frase com must, might has. Enquadramento: \'os mais comuns\'.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: what a notice says and what it means, advice, quick questions, and two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ela liga a linha do aviso a inferencia e EXPLICA com must ou can\'t: \'If it is booked online only, you can\'t book it at the desk.\' E a tarefa de inferencia do Read in Daily Life.',
        'gap': '<strong>Gap-fill (4 min):</strong> Ela arrasta, toca ou digita e confere com Check. Cuidado com a sexta lacuna: comeca a frase, entao a palavra vem com maiuscula.',
        'quickfire': '<strong>Quick fire (5 min):</strong> Uma pergunta por vez. Ela responde ANTES da dica. Regra: um modal de deducao por resposta. Corrija so o modal, depois que ela terminar.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Depois faca o exercicio da tutora com uma pergunta do true/false: ela responde com as proprias palavras antes de olhar as opcoes.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Anuncio falado, voz masculina. As perguntas 2 e 3 exigem inferencia: ela precisa dizer o que DEVE ser verdade, nao repetir o audio.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same test, three times. The last one is you deducing from a notice with no notes.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a tutora. Ela le o relatorio e deduz com modais o que aconteceu em cada tarefa. Corrija so mustn\'t/can\'t e o have + participio, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e um colega da GV que le cada palavra. Exija as tres tarefas, o design adaptativo, duas estrategias e uma pergunta dela de volta.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Leia em voz alta um aviso curto (invente um da GV). Ela faz quatro deducoes, com must, can\'t, might e pelo menos uma no passado. Cronometre dois minutos. No fim, dois numeros: quantas vezes recomecou e quantos modais usou.',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete em blocos. A quinta e a regra da prova dela: peca que ela diga em voz alta antes de cada simulado.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 6. Item em que ela hesitar entra no warm-up da aula 7.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the answer is almost never on the page. It is what must be true because of the page.\' Homework (ORALMENTE, nunca escrito na tela): fazer um set curto de reading no formato novo (o video dos Complementares tem exemplos), anotar quantas respostas trocou e se estavam certas antes. Proxima aula: explicar um processo, em conversa.',
    },
    'pc': {
        'title': 'How the TOEFL Reads You -- Inference and Deduction',
        'desc': 'The new TOEFL reading section rewards inference, not word hunting. Learn the modals that say what must be true.',
        'match_idx': [0, 2, 5, 7, 8, 10],
        'context': [
            'Reading tests are full of questions that ask what <strong>must</strong> be true, and the answer is rarely a sentence you can point to. It is a deduction. English has a small group of modal verbs for exactly that job, and they tell your listener how sure you are.',
            'When you are almost certain that something is true now, use <strong>must</strong>: &ldquo;The group rooms are booked online, so there <strong>must be</strong> a booking website.&rdquo; When you are almost certain it is not true, the opposite is not <em>mustn&rsquo;t</em>, which means prohibition. It is <strong>can&rsquo;t</strong>: &ldquo;The library closes at nine, so students <strong>can&rsquo;t be</strong> there at ten.&rdquo;',
            'When something is only possible, use <strong>might</strong>, <strong>may</strong> or <strong>could</strong>: &ldquo;That option <strong>could be</strong> a <strong>distractor</strong>.&rdquo; For the past, keep the modal and add <strong>have</strong> + past participle: &ldquo;She left three questions blank, so she <strong>must have run</strong> out of time,&rdquo; and &ldquo;He finished in ten minutes, so he <strong>can&rsquo;t have read</strong> the whole <strong>passage</strong>.&rdquo;',
            'This is also how you should think during the test. When you <strong>infer</strong>, you are not guessing: you are saying what must be true if the text is true. When you <strong>eliminate</strong> an option, you are saying it can&rsquo;t be supported. And when you want to change an answer because of a <strong>hunch</strong>, ask yourself whether you are deducing, or only <strong>second-guessing</strong>.',
        ],
        'context_quiz': [
            ('According to the text, what is the opposite of must for deduction?', ['mustn&rsquo;t', 'can&rsquo;t', 'shouldn&rsquo;t'], 1),
            ('How do you talk about a deduction in the past?', ['Keep the modal and add have + past participle.', 'Use the modal with a past verb, like must ran.', 'Use did before the modal.'], 0),
            ('What does the text say you should ask yourself before changing an answer?', ['Whether the option is longer.', 'Whether the tutor would agree.', 'Whether you are deducing or only second-guessing.'], 2),
        ],
        'tip_title': 'Modals of Deduction',
        'tip_lead': 'Must for almost yes, can&rsquo;t for almost no, might for maybe; add have + participle for the past.',
        'tip_rows': [
            ('Almost certain yes (now)', 'must + verb', 'There <strong>must be</strong> a website.'),
            ('Almost certain no (now)', 'can&rsquo;t + verb', 'They <strong>can&rsquo;t be</strong> there.'),
            ('Possible (now)', 'might / may / could + verb', 'It <strong>could be</strong> a distractor.'),
            ('Almost certain yes (past)', 'must have + participle', 'She <strong>must have run</strong> out of time.'),
            ('Almost certain no (past)', 'can&rsquo;t have + participle', 'He <strong>can&rsquo;t have read</strong> it.'),
            ('Possible (past)', 'might have + participle', 'He <strong>might have had</strong> a hunch.'),
        ],
        'tip_never': 'he mustn&rsquo;t be at home (for deduction) &middot; she must to have studied &middot; he might has made a mistake &middot; they must read it yesterday',
        'blanks': [
            ('The group rooms are booked online, so there ', 'must be', ' a booking website.', 'Hint: almost certain yes, now -- two words', None),
            ('The library closes at nine, so students ', 'cannot be', ' inside at ten.', 'Hint: almost certain no, now -- two words (full form)', 'can\'t be'),
            ('She left three questions blank, so she ', 'must have run', ' out of time.', 'Hint: almost certain, in the past -- three words', None),
            ('I am not sure why he changed it. He ', 'might have had', ' a hunch.', 'Hint: possible, in the past -- three words', None),
            ('Read quickly for the general idea: ', 'skim', ' the passage first.', 'Hint: read fast for the main idea -- one word', None),
            ('Remove the options the text does not support: ', 'eliminate', ' them.', 'Hint: take away wrong options -- one word', None),
        ],
        'order_title': 'Put the Strategy in Order',
        'order_lead': 'A classmate asks how to approach a reading passage. Put your advice in a logical order.',
        'order': [
            'First, skim the passage for the main idea.',
            'Then read the question and decide what it is asking for.',
            'Answer it in your own words before you look at the options.',
            'Eliminate the options the text does not support.',
            'Be careful with the distractor that repeats the text&rsquo;s words.',
            'Change your answer only if a line in the text proves you wrong.',
        ],
        'quiz': [
            ('The library closes at nine. You deduce something about ten o&rsquo;clock. You say:', ['Students mustn&rsquo;t be there at ten.', 'Students can&rsquo;t be there at ten.', 'Students don&rsquo;t must be there at ten.'], 1),
            ('Your friend left three questions blank. You say:', ['She must have run out of time.', 'She must ran out of time.', 'She must to run out of time.'], 0),
            ('An option could be true in real life, but the text does not say it. You:', ['choose it, because it is probably true.', 'second-guess the other options.', 'eliminate it, because the text does not support it.'], 2),
            ('A classmate reads every word. You advise:', ['Scan every word slowly.', 'Skim first for the main idea.', 'Second-guess every answer.'], 1),
        ],
        'think': 'Think about the last time you took a timed reading test, in any language. In ninety seconds, say what must have gone well, what can&rsquo;t have been the problem, and what might have cost you points. Then say what you will do differently on the TOEFL reading section. Use at least four modals of deduction.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'TOEFL Tutor Tatiana &mdash; &ldquo;TOEFL 2026 Complete the Words: Strategy, Tips, Examples&rdquo; (YouTube)',
         'desc': 'A clear walkthrough of the new Complete the Words task, with examples of how context clues give you the missing letters.',
         'tip': 'Tip: pause before each answer and say which context clue helped you.',
         'url': 'https://www.youtube.com/watch?v=8DCIle_flhw', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'Gilmore Girls &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'A fast-talking student who reads everything and wants a demanding school. The dialogue is famously quick, which makes it excellent listening practice.',
         'tip': 'Tip: after each scene, say one thing that must be true about a character, even if nobody says it.',
         'url': 'https://www.tvmaze.com/episodes/47487/gilmore-girls-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Carol Dweck &mdash; &ldquo;The power of believing that you can improve&rdquo; (TED)',
         'desc': 'A psychologist on why the students who improve most see a bad result as &ldquo;not yet&rdquo;. Ten minutes that change how you read a practice score.',
         'tip': 'Tip: summarize her main argument in three blocks, and say what must be true about students who say not yet.',
         'url': 'https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve', 'cta': 'Watch on TED'},
    ],
}
