# -*- coding: utf-8 -*-
# Aula 1 -- The Application Story (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "The Application <span class='accent'>Story</span>",
    'hero_line': 'Eleven years of English, and the two minutes that decide which exchange you get',
    'menu_desc': 'Telling your English story without stumbling, and the present perfect that carries it -- 34 slides',
    'grammar_point': 'present perfect simple and continuous to tell your background',
    'phases': ['The Story', 'Words of the Application', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'mark', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1541339907198-e08756dedf3f?w=1400&q=80',
        'ch2': U + 'photo-1456513080510-7bf3a84b82f8?w=1400&q=80',
        'ch_grammar': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch4': U + 'photo-1524178232363-1fb2b075b655?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1522202176988-66273c2fd55f?w=1400&q=80',
        'ch7': U + 'photo-1513635269975-59663e0ac1ad?w=1400&q=80',
        'pc': U + 'photo-1541339907198-e08756dedf3f?w=600&q=80',
    },
    'warmup': {
        'heading': "How Did You Really <span class='accent'>Learn English?</span>",
        'sub': 'Not the schools. The thing that actually worked, and how old you were when it started.',
    },
    'target': {
        'heading': "One Story, <span class='accent'>Three Moves</span>",
        'steps': [
            'Where you are now: one clear sentence about today.',
            'How long, and how: the part that started in the past and is still going on.',
            'Where you are going, and why this exchange, and not another one.',
        ],
    },
    'diagnostic': {
        'heading': "So, Tell Me About <span class='accent'>Your English</span>",
        'p1': 'An exchange coordinator from a partner university opens a video call and says: &ldquo;Before we look at your application, tell me a little about your English.&rdquo;',
        'p2': 'Answer for sixty seconds. Do not stop to find the perfect word: keep going, and fix it later.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Application</span>",
            'sub': 'Thirteen words that every exchange office uses, and that nobody translates for you'},
    'vocab': [
        {'word': 'An exchange program', 'def': 'An agreement that lets a student spend time studying at a university in another country', 'ex': 'The law school has an exchange program with universities in Europe and the United States.', 'icon': 'globe'},
        {'word': 'To apply for', 'def': 'To make a formal request for a place, a job or a program', 'ex': 'I plan to apply for the exchange in my third year.', 'icon': 'pen'},
        {'word': 'A requirement', 'def': 'Something you must have or do before you are accepted', 'ex': 'A TOEFL score is a requirement for every partner university.', 'icon': 'doc'},
        {'word': 'A deadline', 'def': 'The last day or time when something can be done or sent', 'ex': 'The deadline for the application is the first week of March.', 'icon': 'calendar'},
        {'word': 'A host university', 'def': 'The university abroad that receives an exchange student', 'ex': 'My host university will decide which courses I can take.', 'icon': 'building'},
        {'word': 'A semester abroad', 'def': 'Half an academic year spent studying in another country', 'ex': 'My brother spent a semester abroad before he moved to London.', 'icon': 'compass'},
        {'word': 'A cut-off score', 'def': 'The minimum result a candidate needs in order to be considered', 'ex': 'The best universities have a higher cut-off score.', 'icon': 'target'},
        {'word': 'Competitive', 'def': 'Describes a process where many people want the same thing and only some get it', 'ex': 'The exchange is competitive, so a good score is not enough on its own.', 'icon': 'chart'},
        {'word': 'To stand out', 'def': 'To be noticed easily because you are different or better', 'ex': 'Your interview is where you stand out from the other candidates.', 'icon': 'star'},
        {'word': 'A track record', 'def': 'All the things a person has done in the past that show what they can do', 'ex': 'She has a strong track record in her law school debates.', 'icon': 'layers'},
        {'word': 'To keep up with', 'def': 'To move or learn at the same speed as other people or things', 'ex': 'I read every day so that I can keep up with the classes.', 'icon': 'clock'},
        {'word': 'A head start', 'def': 'An advantage you get by starting something earlier than other people', 'ex': 'Starting two years before the test gives me a head start.', 'icon': 'flag'},
        {'word': 'To be shortlisted', 'def': 'To be chosen as one of the few candidates who go to the final stage', 'ex': 'Only twenty students are shortlisted for an interview.', 'icon': 'filter'},
    ],
    'pron_heading': "Say It Without <span class='accent'>Stopping</span>",
    'pron': ['A requirement', 'A cut-off score', 'Competitive', 'I have been studying English since I was seven, and I have never stopped.'],
    'vocab_fill': [
        ('You must send a TOEFL score before you are accepted: it is ', 'a requirement', ' for every partner.'),
        ('The office will not accept anything after March fifth, because that is ', 'the deadline', '.'),
        ('Two hundred students apply and only thirty get a place, so the process is very ', 'competitive', '.'),
        ('Only the best twenty candidates are ', 'shortlisted', ' for the final interview.'),
        ('Starting to prepare two years early gives me ', 'a head start', ' on the other candidates.'),
        ('The reading list is long, and I study every night to ', 'keep up with', ' the class.'),
    ],
    'ch_grammar': {'heading': "The Past That Is <span class='accent'>Still Going On</span>",
                   'sub': 'Four sentences about the same eleven years, and why none of them uses the simple past'},
    'grammar': {
        'heading': "Why Not Just <span class='accent'>I Studied?</span>",
        'examples': [
            "I <span style='color:#b91c1c;font-weight:700'>have been studying</span> English since I was seven.",
            "I <span style='color:#1d4ed8;font-weight:700'>have read</span> about forty novels in English this year.",
            "My brother <span style='color:#1d4ed8;font-weight:700'>has lived</span> in London for three years.",
            "I <span style='color:#b91c1c;font-weight:700'>have been preparing</span> for the TOEFL for two months, and I <span style='color:#1d4ed8;font-weight:700'>have finished</span> one practice test.",
        ],
        'prompt': 'All four sentences talk about the past. So why does none of them say <em>studied</em>, <em>read</em> or <em>lived</em>? Look at the red forms and the blue forms: which ones focus on the activity, and which ones focus on the result?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('An activity that started in the past and is still going on', 'have / has been + verb-ing', 'I <strong>have been studying</strong> English since I was seven.'),
            ('A result, a number, a finished amount', 'have / has + past participle', 'I <strong>have read</strong> forty novels this year.'),
            ('A state that is still true (live, know, be)', 'have / has + past participle, not -ing', 'I <strong>have known</strong> her since school.'),
            ('The starting point', 'since + a moment', 'since I was seven &middot; since 2019'),
            ('The length of time', 'for + a period', 'for eleven years &middot; for two months'),
            ('A finished time in the past', 'simple past, never present perfect', 'I <strong>went</strong> to Scotland last year.'),
            ('The trap', 'never <em>I study English since</em>; never <em>I have been knowing</em>', 'Not <em>I study since I was seven</em>. Say <strong>I have been studying</strong>.'),
        ],
        'oneliner': 'If it started in the past and is still true, use have: -ing for the activity, the past participle for the result.',
    },
    'grammar_practice': {
        'heading': "Activity or <span class='accent'>Result?</span>",
        'items': [
            ('I ', 'have been studying', ' English since I was seven. (an activity that is still going on)'),
            ('My brother ', 'has lived', ' in London for three years. (a state, not -ing)'),
            ('I ', 'have finished', ' two practice tests this month. (a result, with a number)'),
            ('I ', 'went', ' to Scotland last year for a one-month course. (a finished time)'),
            ('She ', 'has been reading', ' the treaty all afternoon, and she is tired. (the activity explains the result)'),
            ('We ', 'have known', ' about the exchange program since the first semester. (a state: know)'),
        ],
    },
    'ch4': {'heading': "The Call Before <span class='accent'>the Application</span>",
            'sub': 'One conversation, two recordings, one checklist'},
    'dialogue': {
        'heading': "Ten Minutes with the <span class='accent'>Exchange Office</span>",
        'guest_name': 'Mark', 'guest_initial': 'M',
        'lines': [
            ('m', 'Hi, Luiza, I am Mark Ellison, and I coordinate exchange students at the law school here. Before we look at your file, tell me a little about your English.'),
            ('l', 'Sure. I <span class="vocab-highlight">have been studying</span> English since I was seven, but honestly, I learned most of it online, watching American videos.'),
            ('m', 'That is more common than you think. And have you ever studied abroad?'),
            ('l', 'Only for one month, in Scotland, last year. It was short, but it gave me <span class="vocab-highlight">a head start</span>, because now I know what a class in English feels like.'),
            ('m', 'Good. You should know that our <span class="vocab-highlight">exchange program</span> is quite <span class="vocab-highlight">competitive</span>. Every year about two hundred students <span class="vocab-highlight">apply for</span> thirty places.'),
            ('l', 'I know. My brother did the same exchange, and when he applied, the <span class="vocab-highlight">cut-off score</span> for the best universities was above ninety.'),
            ('m', 'The scale has changed since then, but the idea has not. The score is the first <span class="vocab-highlight">requirement</span>, and it only gets you <span class="vocab-highlight">shortlisted</span>. What makes a student <span class="vocab-highlight">stand out</span> is the interview.'),
            ('l', 'Then that is what I want to work on. I read a lot, but when I speak about technical things, I sometimes stumble over the words.'),
            ('m', 'You have time. The <span class="vocab-highlight">deadline</span> is in two years, so if you practice every week, you will <span class="vocab-highlight">keep up with</span> the classes easily.'),
            ('l', 'That is exactly why I started now. And which <span class="vocab-highlight">host universities</span> do law students usually choose?'),
        ],
        'comp': [
            ('What is Mark&rsquo;s job at the law school?', 'He coordinates exchange students.'),
            ('According to Mark, how many students apply every year, and for how many places?', 'About two hundred students apply for thirty places.'),
            ('What does Mark say has changed, and what does he say the score does?', 'The scale has changed. The score is the first requirement and only gets you shortlisted; the interview is what makes a student stand out.'),
            ('When is the deadline, and what does Mark say will happen if she practices every week?', 'In two years. If she practices every week, she will keep up with the classes easily.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Podcast', 'title': "What the Committee <span class='accent'>Remembers</span>",
         'blurb': 'A former admissions reader on exchange interviews. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'I read exchange applications for six years, and I want to tell you what the committee actually remembers. It is not your score. By the time you reach the interview, everyone in the room has a good score, so the number stops being interesting. What we remember is whether you could explain, in two minutes, why this university and not another one. The strongest candidates did not have the most impressive track record. They had a clear story. Where they were, how long they had been working on something, and where they wanted to go next. And one more thing, because students always worry about it. Nobody on the committee cared about accent. We cared about whether we had to ask you to repeat yourself. If your sentences are clear, your accent is simply part of who you are.',
         'qs': [
             ('Why does she say the score stops being interesting in the interview?', 'Because everyone who reaches the interview already has a good score.'),
             ('What did the strongest candidates have, and what did they not necessarily have?', 'They had a clear story. They did not necessarily have the most impressive track record.'),
             ('What did the committee care about, instead of accent?', 'Whether they had to ask the candidate to repeat themselves.'),
         ]},
        {'label': 'Listening 2 &middot; Info Session', 'title': "Two Years Before <span class='accent'>You Go</span>",
         'blurb': 'An exchange office explains the timeline. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Good afternoon, and thank you for joining this session so early in your degree. Most students come to us six months before the deadline, and that is too late. The application has three parts. First, the language requirement: every partner university asks for an official test, and since the TOEFL moved to a scale from one to six, the most competitive ones expect an overall band of at least four and a half, sometimes five. Second, your grades from the first two years. And third, a short interview, in English, with two members of the committee. Here is my advice. Take a practice test this semester, not next year, so you know exactly how far you are from the cut-off score. Choose three host universities, not one. And remember that a semester abroad is not a vacation. The reading load in a law school is heavy in any language, and you will need to keep up with it from the first week.',
         'qs': [
             ('Why does he say most students come to the office too late?', 'Because they come six months before the deadline.'),
             ('What are the three parts of the application, and what band do the most competitive universities expect?', 'The language requirement, the grades from the first two years, and a short interview in English. They expect an overall band of at least four and a half, sometimes five.'),
             ('What are his two practical pieces of advice, and what does he say a semester abroad is not?', 'Take a practice test this semester and choose three host universities. He says a semester abroad is not a vacation.'),
         ]},
    ],
    'artifact': {
        'heading': "The Checklist in <span class='accent'>Your Inbox</span>",
        'title': 'EXCHANGE APPLICATION CHECKLIST', 'subtitle': 'Law School Exchange Office &middot; Candidate: L. Sato Eccheli',
        'rows': [
            ('Language requirement', 'Official TOEFL iBT &mdash; overall band 4.5 (1-6 scale) for Tier 1 partners', True),
            ('Academic record', 'Grades from semesters 1 to 4', False),
            ('Statement of purpose', '500 words, in English', False),
            ('Interview', '15 minutes, in English, only for shortlisted candidates', True),
            ('Host universities', 'Rank three, in order of preference', False),
        ],
        'note': 'Office note: scores older than two years are not accepted on the deadline date. Plan your test date so that it is still valid when you apply.',
        'qs': [
            ('What is the minimum result for Tier 1 partners, and on which scale?', 'An overall TOEFL iBT band of 4.5, on the scale from one to six.'),
            ('Who has an interview, how long is it, and in which language?', 'Only shortlisted candidates. It lasts fifteen minutes, in English.'),
            ('According to the note, why does the test date matter?', 'Scores older than two years are not accepted on the deadline date, so the score must still be valid when she applies.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Candidate</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('I study English since I was seven.', 'I <strong>have been studying</strong> English since I was seven.'),
        ('My brother lives in London since 2023.', 'My brother <strong>has lived</strong> in London since 2023.'),
        ('I have gone to Scotland last year.', 'I <strong>went</strong> to Scotland last year.'),
        ('I am preparing for the TOEFL for two months.', 'I <strong>have been preparing</strong> for the TOEFL for two months.'),
    ],
    'speaking': [
        ('Tell me a little about your English.', 'I have been studying English since I was seven, but I have learned most of it online, and that is why I understand much more than I produce.'),
        ('Have you ever studied abroad?', 'Only for one month, in Scotland, last year. It was short, but it gave me a head start.'),
        ('Why this exchange, and not another one?', 'My brother did it and it changed his career, and I have been planning it since my first semester.'),
        ('What do you still need to work on?', 'I have read a lot in English, but I still stumble over the words when I speak about technical subjects.'),
    ],
    'building': [
        ('I / study English / since I was seven (an activity that is still going on)', 'I have been studying English since I was seven.'),
        ('my brother / live in London / three years (a state)', 'My brother has lived in London for three years.'),
        ('I / finish / two practice tests / this month (a result)', 'I have finished two practice tests this month.'),
        ('I / go to Scotland / last year (a finished time)', 'I went to Scotland last year.'),
    ],
    'roleplays': {
        'heading': "The Same Call, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Mark Asks <span class='accent'>Again</span>",
             'scenario': 'Mark asks the same three questions: tell me about your English, have you ever studied abroad, and what do you want to work on. Answer each one in two sentences, with one present perfect in every answer.',
             'chips': ['since I was seven', 'for eleven years', 'a head start', 'to stand out']},
            {'heading': "Why This <span class='accent'>University?</span>",
             'scenario': 'You are shortlisted. A committee member asks why you chose your first host university and not the other two. Give two reasons, say what you have already done to prepare, and ask one question about the program.',
             'chips': ['a host university', 'I have been preparing', 'a requirement', 'a semester abroad']},
            {'heading': "Two Minutes, <span class='accent'>No Notes</span>",
             'scenario': 'The interview opens with one question: &ldquo;Tell us your story with English, and where you want it to take you.&rdquo; Where you are now, how long and how, and where you are going.',
             'footer': 'No notes, two minutes. If you stumble on a word, do not stop: rephrase and keep going.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for <span class='accent'>the Interview</span>", 'sub': 'What you take into the room'},
    'survival_heading': "Five Sentences for <span class='accent'>the Interview</span>",
    'survival': [
        'I have been studying English since I was seven, but I learned most of it online.',
        'I spent one month in Scotland, and it gave me a head start.',
        'I have read a lot in English, but I still want to speak about technical subjects more fluently.',
        'The score gets you shortlisted, but the interview is where you stand out.',
        'Sorry, let me rephrase that more clearly.',
    ],
    'checklist': [
        'I can tell my story with English in two minutes, without stopping.',
        'I use have been + -ing for an activity that is still going on, and have + past participle for a result.',
        'I use the simple past for a finished time, like last year, and never I have gone last year.',
        'When I stumble over a word, I rephrase and keep going.',
        'I know the words: an exchange program, to apply for, a requirement, a deadline, a host university, a semester abroad, a cut-off score, competitive, to stand out, a track record, to keep up with, a head start, to be shortlisted.',
    ],
    'badge': {'name': 'The Application Story', 'line': 'Where you are, how long you have been at it, and where you are going.',
              'next': 'Next lesson: The Treaty Is Not the Problem -- how international law is written, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada (REGRA 27A). Va direto: \'Luiza, today we build the story you are going to tell in your exchange interview.\' Contexto que muda a aula inteira: ela tem 18 anos, faz Direito na FGV em periodo integral e o objetivo e o TOEFL do intercambio da faculdade, em uns dois anos (ela pediu 1x por semana justamente para chegar na prova com aula recente). Ela entende e le muito (ficcao em ingles no Kindle), aprendeu ingles de verdade vendo videos de americanos. O que ela mesma disse que incomoda: NAO e o sotaque, e a fluidez &mdash; \'eu travo nas palavras, ai eu tenho que repetir\'. A aula e para ela FALAR muito. Ela ja le o dia inteiro na faculdade e disse que texto demais a irrita: nao transforme nenhum slide em leitura longa.',
        'warmup': '<strong>Warm-up (5 min):</strong> Aula 1, entao nao ha callback: e diagnostico. Deixe ela contar como aprendeu ingles de verdade (a historia do TikTok, o irmao que aprendeu com videogame e hoje mora em Londres). ANOTE em tres colunas: (1) quantas vezes ela para e recomeca a mesma palavra &mdash; e o \'travar\' que ela descreveu; (2) se usa \'I study since\' ou \'I have been studying\'; (3) palavras longas que ela evita. Zero correcao agora. Esse mapa e o material das proximas aulas.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Ligue ao que ela contou: o irmao fez o mesmo intercambio da GV, e na entrevista quem se destaca e quem tem uma historia clara. Nao de a regra gramatical ainda &mdash; ela sai por descoberta no capitulo 3.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Sessenta segundos, sem ajuda. Cronometre. Diga antes: \'if you stumble on a word, keep going.\' ANOTE a frase exata em que ela travou e quantas vezes repetiu uma palavra. Essa gravacao mental e o benchmark: o role-play livre do capitulo 6 repete o exercicio.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words that every exchange office uses.\' B2 = zero portugues na tela. Se ela ja conhecer a palavra, nao pule: peca uma frase sobre o intercambio real dela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> Leia a pista, ela arrisca a palavra, so entao revele. Clicar de novo fecha. CCQ \'to apply for\': \'Do you apply FOR the exchange or apply the exchange? (For.)\' CCQ \'a requirement\': \'Can you be accepted without it? (Nao.)\' CCQ \'a host university\': \'Is it your university or the one abroad? (A de fora.)\' Peca uma frase real dela com cada uma.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> Mesma mecanica. CCQ \'a cut-off score\': \'If you get one point less, are you in or out? (Fora.)\' CCQ \'competitive\': \'Many places and few students, or few places and many students? (Poucas vagas.)\' Pronuncia: com-PET-i-tive, acento na SEGUNDA silaba &mdash; brasileiro puxa para \'competiTIVE\'. \'A track record\': cobre que e o historico todo, nao so notas.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'to keep up with\': \'Are you in front, behind, or at the same speed? (Mesma velocidade.)\' CCQ \'a head start\': \'Did you start before or after the others? (Antes.)\' CCQ \'to be shortlisted\': \'Is it the first stage or the final stage? (Final.)\' Peca que ela diga a frase que diria ao irmao usando \'a head start\'.',
        'pron': '<strong>Pronuncia e fluidez (4 min):</strong> O pedido numero um dela: parar de travar. Trabalhe ACENTO e BLOCOS, nao sotaque (ela disse que sotaque nao incomoda). re-QUIRE-ment, CUT-off, com-PET-i-tive. Na frase longa, peca que ela diga em DOIS blocos com uma pausa so: \'I have been studying English since I was seven / and I have never stopped.\' Se ela travar no meio, peca para recomecar o BLOCO, nao a frase inteira &mdash; e a tecnica que vai usar na prova.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ela diz a palavra ANTES de clicar. As candidatas estao no banco embaixo, fora de ordem &mdash; ela escolhe, nao adivinha. Se fechar rapido, peca uma segunda frase com a mesma palavra sobre a GV.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about eleven years of English. None of them uses the simple past. Why?\' Passe ao proximo sem antecipar a regra.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Which red forms focus on the ACTIVITY, and which blue forms focus on the RESULT?\' Espere ela ver sozinha. So entao Reveal the Rule. CCQ: \'I have been studying English since I was seven &mdash; is she still studying? (Sim.)\' CCQ: \'I have read forty novels &mdash; are we talking about the activity or the number? (O numero.)\' CCQ: \'I went to Scotland last year &mdash; can we say I have gone last year? (Nao: tempo terminado.)\' Obstaculo numero um do brasileiro: \'I study English since\' (calco de \'estudo desde\'). Obstaculo dois: \'I have been knowing\' com verbo de estado.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela fala a frase INTEIRA antes de clicar, sem parar no meio. Se travar na forma, pergunte so: \'Is it still going on? Is it a result? Is the time finished?\' Na quarta (Scotland, last year), se ela usar present perfect, volte ao CCQ.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now the call with the exchange office. One conversation, two recordings and a checklist.\' Passe ao proximo.',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e o Mark: coordenador de intercambio de uma universidade parceira, americano, simpatico e objetivo. Clique Next Line e toque o audio. Nas falas da Luiza, ela fala PRIMEIRO e so depois toque o audio: compare o ritmo. PRAGMATICA para comentar no fim: repare que a Luiza admite uma fraqueza (\'I sometimes stumble over the words\') e transforma em plano (\'that is what I want to work on\'). E na ultima fala ela devolve uma pergunta &mdash; e o que faz a entrevista virar conversa.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre o MARK, nunca sobre a Luiza (REGRA 27F). Ela responde antes de revelar. Na terceira, puxe a conversa real: o irmao dela disse a mesma coisa sobre a entrevista? Deixe ela contar.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. A ultima parte fala do que ela disse na consultoria: sotaque nao importa, o que importa e nao precisar repetir. Pergunte: \'Which sentence in this recording is about you?\'',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Contexto diferente: agora e uma sessao informativa, voz masculina, com numeros. Depois das respostas pergunte qual dos dois conselhos ela ainda nao seguiu. FATO para voce saber: desde janeiro de 2026 o TOEFL iBT da nota geral de 1 a 6 (em meio ponto), nao mais de 0 a 120 &mdash; os 80-90 que o irmao dela lembra sao da escala antiga. E o speaking agora tem so duas tarefas curtas (Listen and Repeat e Take an Interview), SEM tempo de preparo: e exatamente por isso que esta aula treina falar sem nota. Os requisitos da sessao e do checklist sao ficcionais, escritos para a aula: nao apresente como regra real da GV.',
        'artifact': '<strong>Artefato (4 min):</strong> E um checklist ficticio de candidatura, com o nome dela. Peca que ela LEIA cada linha e transforme em frase completa com present perfect ou futuro: \'I have not taken the official test yet, but I have been preparing since...\'. So depois as 3 perguntas. A nota do fim (score com mais de dois anos) e a razao pratica para ela nao fazer a prova cedo demais: aponte.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\' Passe ao proximo.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica por que. Sao os quatro erros classicos do brasileiro com o present perfect: presente simples com since, verbo de estado no presente com since, present perfect com last year, e present continuous com for. Se algum apareceu no warm-up, mostre a anotacao. Enquadramento: \'os mais comuns do Brasil inteiro\', nunca \'voce errou\'.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas como o Mark faria, em velocidade normal. As respostas na tela sao so sugestao. Regra do bloco: se ela travar numa palavra, NAO espere ela achar a palavra perfeita &mdash; diga \'rephrase\' e ela diz de outro jeito. Correcao em bloco, no fim, no maximo tres pontos.',
        'building': '<strong>Sentence Building (4 min):</strong> Ela monta a frase COMPLETA em voz alta e so depois clica. Clicar de novo fecha. Cobre que a frase saia em um bloco so, sem recomecar. Se fechar as quatro sem ajuda, ganhe tempo para o role-play livre.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same call, three times. The last one is your interview, with no notes.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o Mark, sem o texto na tela. Tres perguntas, duas frases por resposta, um present perfect em cada. Corrija so o \'I study since\' e o \'have gone last year\', sempre no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e um membro do comite. Pergunte por que ela escolheu a primeira universidade (ela inventa ou escolhe uma real). Exija duas razoes, o que ela ja fez para se preparar e uma pergunta dela no fim. Se ela nao souber uma universidade, deixe escolher qualquer uma que conheca: o foco e a estrutura, nao a pesquisa.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota, sem interrupcao. Cronometre. No fim, diga dois numeros: quantas vezes ela recomecou uma palavra (compare com o diagnostico do slide 4) e quantos present perfect ela usou. Depois UMA observacao de acento. Este e o benchmark de fluidez que as proximas aulas vao comparar.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you told me about your English. Now you have the story, and five sentences to carry it.\' Passe ao proximo.',
        'survival': '<strong>Survival card (3 min):</strong> Leia cada frase e toque o audio. Ela repete em UM bloco, sem parar. A quinta (\'let me rephrase that\') e a ferramenta para quando travar: peca que ela use pelo menos uma vez nesta semana, mesmo sozinha.',
        'checklist': '<strong>Checklist (2 min):</strong> Diga: \'Click each item if you feel confident.\' Leia cada item em voz alta. Todos os 5 marcados = aula concluida e stamp 1. Nao marque por ela: item em que ela hesitar entra no warm-up da aula 2.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the committee does not need a perfect accent. It needs a clear story.\' Homework (ORALMENTE, nunca escrito na tela): gravar no celular a historia de dois minutos de hoje, ouvir, e trazer a frase em que travou. Proxima aula: como o direito internacional e escrito &mdash; um texto sobre tratados, em leitura, curto.',
    },
    'pc': {
        'title': 'The Application Story -- Telling Your Background',
        'desc': 'An exchange coordinator asks about your English, and you have two minutes to tell a clear story.',
        'match_idx': [0, 2, 3, 6, 8, 11],
        'context': [
            'Every exchange interview starts with the same kind of question: tell us about yourself. Most candidates answer with a list of schools and dates, and the list sounds the same for everybody. The candidates who <strong>stand out</strong> tell a story instead, and English has a tense that was made for stories that are not finished yet.',
            'When something started in the past and is still going on, you use <strong>have been</strong> + <em>-ing</em>: &ldquo;I <strong>have been studying</strong> English since I was seven.&rdquo; It tells the committee that the effort is still alive. When you want to show a result, a number or an achievement, you use <strong>have</strong> + past participle: &ldquo;I <strong>have read</strong> forty novels in English this year.&rdquo;',
            'Two little words decide the time. <strong>Since</strong> goes with a starting point, and <strong>for</strong> goes with a length of time: since 2019, for eleven years. Some verbs, like <em>live</em>, <em>know</em> and <em>be</em>, describe a state, so they usually take the simple form: &ldquo;My brother <strong>has lived</strong> in London for three years,&rdquo; never &ldquo;has been knowing&rdquo;.',
            'And there is one border you cannot cross. When the time is finished, like <em>last year</em> or <em>in 2024</em>, English uses the simple past: &ldquo;I <strong>went</strong> to Scotland last year.&rdquo; A candidate who says &ldquo;I have gone to Scotland last year&rdquo; is understood, but the committee notices. With a clear story and the right tense, a <strong>competitive</strong> interview becomes a conversation, and that is what gives you <strong>a head start</strong>.',
        ],
        'context_quiz': [
            ('According to the text, why do some candidates stand out?', ['They list more schools and dates.', 'They tell a story instead of a list.', 'They have a perfect accent.'], 1),
            ('Which form does the text recommend for an activity that is still going on?', ['have been + -ing, as in I have been studying.', 'the simple present, as in I study since.', 'the simple past, as in I studied.'], 0),
            ('Why is &ldquo;I have gone to Scotland last year&rdquo; wrong?', ['Because Scotland needs the article the.', 'Because gone is not a past participle.', 'Because last year is a finished time, so English uses the simple past.'], 2),
        ],
        'tip_title': 'Present Perfect Simple and Continuous',
        'tip_lead': 'Started in the past and still true: have been + -ing for the activity, have + past participle for the result.',
        'tip_rows': [
            ('An activity still going on', 'have / has been + verb-ing', 'I <strong>have been studying</strong> English since I was seven.'),
            ('A result or a number', 'have / has + past participle', 'I <strong>have read</strong> forty novels this year.'),
            ('A state (live, know, be)', 'have / has + past participle', 'She <strong>has known</strong> about it since March.'),
            ('A starting point', 'since + a moment', 'since I was seven &middot; since 2019'),
            ('A length of time', 'for + a period', 'for eleven years &middot; for two months'),
            ('A finished time', 'simple past', 'I <strong>went</strong> to Scotland last year.'),
        ],
        'tip_never': 'I study English since I was seven &middot; I have been knowing him for years &middot; I have gone to Scotland last year &middot; I am preparing for two months',
        'blanks': [
            ('I ', 'have been studying', ' English since I was seven.', 'Hint: an activity that started in the past and is still going on -- three words', None),
            ('My brother ', 'has lived', ' in London for three years.', 'Hint: a state that is still true, not -ing -- two words', None),
            ('I ', 'went', ' to Scotland last year for a one-month course.', 'Hint: last year is a finished time -- one word', None),
            ('Only twenty students ', 'are shortlisted', ' for the final interview.', 'Hint: chosen for the last stage -- two words', None),
            ('The exchange is very ', 'competitive', ', so a good score is not enough.', 'Hint: many candidates, few places -- one word', None),
            ('Starting now gives me ', 'a head start', ' on the other candidates.', 'Hint: an advantage from starting early -- three words', None),
        ],
        'order_title': 'Put the Story in Order',
        'order_lead': 'An exchange coordinator asks about your English. Put your answer in a logical order.',
        'order': [
            'I have been studying English since I was seven.',
            'But honestly, I learned most of it online, watching American videos.',
            'Last year I spent one month in Scotland, and it gave me a head start.',
            'I have read a lot in English, but I still stumble over technical words.',
            'That is why I want to work on my speaking before the interview.',
            'Which host universities do law students usually choose?',
        ],
        'quiz': [
            ('The coordinator asks how long you have studied English. You say:', ['I study English since I was seven.', 'I have been studying English since I was seven.', 'I am studying English for eleven years.'], 1),
            ('You want to talk about your trip last year. You say:', ['I went to Scotland last year for a one-month course.', 'I have gone to Scotland last year.', 'I have been going to Scotland last year.'], 0),
            ('You want to explain that the process is hard to get into. You say:', ['The exchange is very concurrent.', 'The exchange is very competitive.', 'The exchange is very disputed.'], 1),
            ('You stumble over a word in the middle of your answer. You say:', ['Sorry, I am very bad at English.', 'Wait, wait, I do not know.', 'Sorry, let me rephrase that more clearly.'], 2),
        ],
        'think': 'Imagine the first question of your exchange interview: &ldquo;Tell us your story with English, and where you want it to take you.&rdquo; In two minutes, say where you are now, how long you have been studying and how, and why this exchange matters to you. If you stumble on a word, rephrase it and keep going.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Lera Boroditsky &mdash; &ldquo;How language shapes the way we think&rdquo; (TED)',
         'desc': 'A cognitive scientist on how the languages we speak change what we notice. A good fourteen minutes for a law student who has been living between two languages since childhood.',
         'tip': 'Tip: watch with English subtitles once, then again without them. Pause after each example and say it back in one sentence.',
         'url': 'https://www.ted.com/talks/lera_boroditsky_how_language_shapes_the_way_we_think', 'cta': 'Watch on TED'},
        {'id': 'series', 'type': 'Series', 'title': 'One Tree Hill &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'The series you are already watching, so use it as listening practice. Fast, natural American conversation between students who are deciding what comes next in their lives.',
         'tip': 'Tip: choose one two-minute scene, watch it with English subtitles, then without, and repeat one line at the same speed as the character.',
         'url': 'https://www.tvmaze.com/episodes/52046/one-tree-hill-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'video', 'type': 'Video', 'title': 'TST Prep &mdash; &ldquo;TOEFL Speaking Tips for a Perfect Score, 2026 Edition&rdquo; (YouTube)',
         'desc': 'The speaking section changed in January 2026: two short tasks, Listen and Repeat and Take an Interview, and no preparation time. This free video explains both, two years before your exam.',
         'tip': 'Tip: pause after each tip and answer one interview question out loud with no preparation, the way the new test asks.',
         'url': 'https://www.youtube.com/watch?v=Gxyo1gSJFRM', 'cta': 'Watch on YouTube'},
    ],
}
