# -*- coding: utf-8 -*-
# Aula 7 -- The Tutorial Voice (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "The Tutorial <span class='accent'>Voice</span>",
    'hero_line': 'Explaining a process step by step, and asking somebody else to do it for you',
    'menu_desc': 'Explaining a process clearly, and the causative have and get something done -- 34 slides',
    'grammar_point': 'causative have and get something done',
    'phases': ['The Process', 'Words of the Service', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'marco', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1522335789203-aabd1fc54bc9?w=1400&q=80',
        'ch2': U + 'photo-1487412947147-5cebf100ffc2?w=1400&q=80',
        'ch_grammar': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch4': U + 'photo-1513635269975-59663e0ac1ad?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1529156069898-49953e39b3ac?w=1400&q=80',
        'ch7': U + 'photo-1522335789203-aabd1fc54bc9?w=1400&q=80',
        'pc': U + 'photo-1522335789203-aabd1fc54bc9?w=600&q=80',
    },
    'warmup': {
        'heading': "The Last Tutorial <span class='accent'>You Watched</span>",
        'sub': 'Makeup, hair, a recipe, anything. What did it teach, and was it easy to follow? Why, or why not?',
    },
    'target': {
        'heading': "A Process in <span class='accent'>Three Moves</span>",
        'steps': [
            'Say what the result will be before the first step.',
            'Give the steps in order, with one clear signal word for each.',
            'Say what you do yourself, and what you have somebody else do for you.',
        ],
    },
    'diagnostic': {
        'heading': "Teach Me <span class='accent'>in One Minute</span>",
        'p1': 'A friend who has never done it asks you: &ldquo;Can you explain how you do your everyday makeup, or your hair, before class?&rdquo;',
        'p2': 'Explain it in sixty seconds, step by step, as if you were recording a short tutorial.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Service</span>",
            'sub': 'Thirteen words for tutorials, salons and the documents you will need someone else to prepare'},
    'vocab': [
        {'word': 'A tutorial', 'def': 'A video or a lesson that shows you how to do something step by step', 'ex': 'I learned that hairstyle from a five-minute tutorial.', 'icon': 'eye'},
        {'word': 'A trim', 'def': 'A short haircut that only removes the ends of your hair', 'ex': 'I only want a trim, not a new style.', 'icon': 'filter'},
        {'word': 'Layers', 'def': 'A haircut where the hair is cut at different lengths', 'ex': 'Layers make long hair look lighter.', 'icon': 'layers'},
        {'word': 'Bangs', 'def': 'Hair that is cut to hang over the forehead', 'ex': 'I had bangs in high school, and I still regret it.', 'icon': 'star'},
        {'word': 'Highlights', 'def': 'Thin parts of the hair that are colored lighter than the rest', 'ex': 'She had highlights done before the summer.', 'icon': 'zap'},
        {'word': 'A shade', 'def': 'One particular variety of a color', 'ex': 'This foundation comes in thirty shades.', 'icon': 'target'},
        {'word': 'To blend', 'def': 'To mix a product into the skin so there are no clear lines', 'ex': 'Blend the concealer with your fingers, not with a brush.', 'icon': 'refresh'},
        {'word': 'To touch up', 'def': 'To make small improvements to something that is almost finished', 'ex': 'I touch up my makeup before a presentation.', 'icon': 'pen'},
        {'word': 'An appointment', 'def': 'An arrangement to see somebody at a particular time', 'ex': 'I have an appointment at the salon on Friday at three.', 'icon': 'calendar'},
        {'word': 'A walk-in', 'def': 'A customer who arrives without an appointment', 'ex': 'The salon takes walk-ins only in the morning.', 'icon': 'users'},
        {'word': 'A certified translation', 'def': 'An official translation with a statement that it is accurate, accepted by institutions', 'ex': 'The university asked for a certified translation of my grades.', 'icon': 'doc'},
        {'word': 'To notarize', 'def': 'To have a document officially checked and stamped by a notary', 'ex': 'The letter has to be notarized before you send it.', 'icon': 'shield'},
        {'word': 'A transcript', 'def': 'An official document that lists a student&rsquo;s courses and grades', 'ex': 'Request your transcript from the registrar at least a month early.', 'icon': 'book'},
    ],
    'pron_heading': "Say It in <span class='accent'>One Block</span>",
    'pron': ['A certified translation', 'To notarize', 'A transcript', 'I had my transcript translated, and then I got the letter notarized.'],
    'vocab_fill': [
        ('I learned how to do it from a five-minute ', 'tutorial', ' on YouTube.'),
        ('My hair is fine; I only want a ', 'trim', ', not a new style.'),
        ('Use your fingers to ', 'blend', ' the concealer, so there are no lines.'),
        ('The salon was full, so I made an ', 'appointment', ' for Friday.'),
        ('The university will not accept my grades in Portuguese; it needs a ', 'certified translation', '.'),
        ('Ask the registrar for your ', 'transcript', ' at least a month before the deadline.'),
    ],
    'ch_grammar': {'heading': "Who Actually <span class='accent'>Did It?</span>",
                   'sub': 'Four sentences where the speaker did not do the work, and one where she did'},
    'grammar': {
        'heading': "Did She Cut It <span class='accent'>Herself?</span>",
        'examples': [
            "I <span style='color:#b91c1c;font-weight:700'>had my hair cut</span> last Friday.",
            "She <span style='color:#b91c1c;font-weight:700'>got her transcript translated</span> by a certified translator.",
            "I need to <span style='color:#1d4ed8;font-weight:700'>have the letter notarized</span> before I apply.",
            "We <span style='color:#1d4ed8;font-weight:700'>are getting our documents checked</span> this week.",
        ],
        'prompt': 'In each sentence, who did the work: the speaker, or somebody else? Look at the order of the words after <em>had</em> and <em>got</em>. Where is the object, and what form is the verb?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Somebody does a service for you', 'have + object + past participle', 'I <strong>had my hair cut</strong>.'),
            ('The same, more informal', 'get + object + past participle', 'She <strong>got her transcript translated</strong>.'),
            ('Say who did it', 'causative + by + person', 'I had it translated <strong>by a certified translator</strong>.'),
            ('Any tense', 'the tense is on have or get', 'We <strong>are getting</strong> it checked. I <strong>will have</strong> it notarized.'),
            ('Something bad that happened to you', 'have + object + past participle', 'I <strong>had my phone stolen</strong> in the metro.'),
            ('A sequence of steps', 'first, then, once, after that, finally', '<strong>First</strong> I get it translated, <strong>then</strong> I have it notarized.'),
            ('The trap', 'never <em>I cut my hair</em> if somebody else did it; never <em>had cut my hair</em>', 'Not <em>I had cut my hair</em>. Say <strong>I had my hair cut</strong>.'),
        ],
        'oneliner': 'Have or get, then the object, then the past participle: the work was done for you, not by you.',
    },
    'grammar_practice': {
        'heading': "By You, or <span class='accent'>For You?</span>",
        'items': [
            ('I did not cut it myself. I ', 'had my hair cut', ' at a salon in Pinheiros. (a service)'),
            ('She ', 'got her transcript translated', ' by a certified translator. (informal)'),
            ('Before I apply, I need to ', 'have the letter notarized', '. (a service in the future)'),
            ('We ', 'are getting our documents checked', ' by the exchange office this week. (in progress)'),
            ('He ', 'had his phone stolen', ' on the first day in London. (something bad)'),
            ('', 'First', ' I get the grades translated, and then I have them notarized. (sequence)'),
        ],
    },
    'ch4': {'heading': "A Salon in <span class='accent'>London</span>",
            'sub': 'One conversation, two recordings, one receipt'},
    'dialogue': {
        'heading': "Just a Trim, <span class='accent'>Please</span>",
        'guest_name': 'Marco', 'guest_initial': 'M',
        'lines': [
            ('m', 'Hi there. Do you have an <span class="vocab-highlight">appointment</span>, or are you a <span class="vocab-highlight">walk-in</span>?'),
            ('l', 'I booked online for three o&rsquo;clock. Luiza. I would like to have my hair cut, but only a <span class="vocab-highlight">trim</span>.'),
            ('m', 'Of course. It is a bit long on the sides. Do you want to keep the <span class="vocab-highlight">layers</span>?'),
            ('l', 'Yes, please. And no <span class="vocab-highlight">bangs</span>. I had bangs cut once before a trip, and I spent the whole month regretting it.'),
            ('m', 'No bangs, understood. Are you here on holiday, or are you studying?'),
            ('l', 'Studying. I am on an exchange at the law school, so this week is all paperwork. I had my <span class="vocab-highlight">transcript</span> sent from Brazil, and now I need to get it checked.'),
            ('m', 'That sounds painful. Did they ask for a <span class="vocab-highlight">certified translation</span> as well?'),
            ('l', 'They did. I got it translated in S&atilde;o Paulo, but they also want one letter <span class="vocab-highlight">notarized</span> here, so first I have it stamped, and then I take it to the office.'),
            ('m', 'Well, at least your hair will look good in the photos. Some clients ask for <span class="vocab-highlight">highlights</span> before a new start. Maybe next time?'),
            ('l', 'Maybe next time. Can you show me how you <span class="vocab-highlight">blend</span> the ends? I learn everything from <span class="vocab-highlight">tutorials</span>, but I can never do it the same way.'),
        ],
        'comp': [
            ('What does Marco ask Luiza first?', 'Whether she has an appointment or is a walk-in.'),
            ('What does Marco notice about her hair, and what does he ask about the layers?', 'That it is a bit long on the sides. He asks if she wants to keep the layers.'),
            ('What does Marco ask about the paperwork?', 'Whether they asked for a certified translation as well.'),
            ('What does Marco suggest for next time, and why does he mention the photos?', 'Highlights. He jokes that at least her hair will look good in the photos.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Creator', 'title': "How I Film <span class='accent'>a Tutorial</span>",
         'blurb': 'A beauty creator explains her process. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'People always ask me how I make my tutorials look so simple, so here is my process. First, I decide the result before I touch a single brush, because if I do not know where I am going, the video wanders. Then I do the whole look once, off camera, and I write down every step on a card. Only after that do I start filming. I say what I am doing before I do it, not after, because viewers want to know why a step matters. And I do not do everything myself. I have my lighting set up by a friend who studied film, and I get my videos edited by someone else, because editing is where I used to lose a whole weekend. The best tutorial is not the one with the most steps. It is the one where every step has a reason.',
         'qs': [
             ('What does she decide before she touches a brush, and why?', 'The result, because if she does not know where she is going, the video wanders.'),
             ('What does she do before she starts filming?', 'She does the whole look once off camera and writes every step on a card.'),
             ('What does she have other people do for her, and what does she say makes the best tutorial?', 'Her lighting is set up by a friend and her videos are edited by someone else. The best tutorial is one where every step has a reason.'),
         ]},
        {'label': 'Listening 2 &middot; A Voicemail', 'title': "Your Documents, <span class='accent'>In Order</span>",
         'blurb': 'A message from an exchange office. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Hi, this is a message for incoming exchange students about the documents we need before registration. Please follow the steps in this order, because we cannot accept them any other way. First, request your official transcript from your home university. If it is not in English, you will need to have it translated by a certified translator. A simple translation made by a friend or an app will not be accepted. Once you have the translation, get the signed letter from your home coordinator notarized. Then send all three documents together in a single email. Do not send them one by one. Registration opens on the second Monday of the semester, and students whose documents are incomplete by then will have to register late, which means fewer electives to choose from.',
         'qs': [
             ('What is the first step, and what happens if the transcript is not in English?', 'Request the official transcript. If it is not in English, it must be translated by a certified translator.'),
             ('What kind of translation will not be accepted?', 'A simple translation made by a friend or an app.'),
             ('How must the documents be sent, and what happens to students whose documents are incomplete?', 'All three together in a single email. They will have to register late, with fewer electives to choose from.'),
         ]},
    ],
    'artifact': {
        'heading': "The Receipt in <span class='accent'>Your Email</span>",
        'title': 'DOCUMENT SERVICES RECEIPT', 'subtitle': 'Client: L. Sato Eccheli &middot; Order 4471',
        'rows': [
            ('Certified translation', 'Academic transcript, Portuguese to English &mdash; 4 pages', True),
            ('Notarization', 'Letter from home coordinator &mdash; 1 document', False),
            ('Delivery', 'PDF by email in 3 business days; printed copy by mail in 7', False),
            ('Status', 'Translation ready &mdash; notarization appointment on Tuesday', True),
            ('Total', 'Paid in full', False),
        ],
        'note': 'Please note: the notary stamps only original signed documents. Bring the letter with the coordinator&rsquo;s original signature to your appointment; a printed copy of an email will not be accepted.',
        'qs': [
            ('What is being translated, and into which language?', 'Her academic transcript, from Portuguese into English.'),
            ('What is ready, and what is still waiting?', 'The translation is ready. The notarization is waiting for the appointment on Tuesday.'),
            ('According to the note, what must she bring to the notary, and what will not be accepted?', 'The letter with the coordinator&rsquo;s original signature. A printed copy of an email will not be accepted.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Tutorial Star</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('I cut my hair at a salon yesterday.', 'I <strong>had my hair cut</strong> at a salon yesterday.'),
        ('She had translated her transcript by a translator.', 'She <strong>had her transcript translated</strong> by a translator.'),
        ('I need to get notarize the letter before Friday.', 'I need to <strong>get the letter notarized</strong> before Friday.'),
        ('We are having check our documents this week.', 'We are <strong>having our documents checked</strong> this week.'),
    ],
    'speaking': [
        ('How do you usually do your hair before class?', 'I do it myself most days, because I learned from tutorials, but I have it cut at a salon every three months.'),
        ('What did you have to prepare for your month in Scotland?', 'I had to get my passport renewed, and I had my documents checked by the school before I went.'),
        ('Explain how you would get your transcript ready for an exchange.', 'First, I would request it from GV. Then I would have it translated by a certified translator, and finally I would get the letter notarized.'),
        ('What is something you never do yourself?', 'I never color my hair myself. I always have it done at a salon, because I once tried at home and it was a disaster.'),
    ],
    'building': [
        ('I / cut / my hair / last Friday (a service)', 'I had my hair cut last Friday.'),
        ('she / translate / her transcript / a certified translator (informal)', 'She got her transcript translated by a certified translator.'),
        ('I / need / notarize / the letter / before I apply (future service)', 'I need to have the letter notarized before I apply.'),
        ('he / steal / his phone / on the first day (something bad)', 'He had his phone stolen on the first day.'),
    ],
    'roleplays': {
        'heading': "The Same Service, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Marco Asks <span class='accent'>Again</span>",
             'scenario': 'You are at the salon again. Tell Marco what you want done and what you do not want, explain one thing you had done before and regretted, and ask him one question about the cut.',
             'chips': ['I would like to have', 'a trim', 'layers', 'an appointment']},
            {'heading': "The Paperwork, <span class='accent'>Step by Step</span>",
             'scenario': 'A classmate going on exchange asks how to prepare the documents. Explain the process in order: what they do themselves, and what they have done by other people.',
             'chips': ['First', 'have it translated', 'get it notarized', 'a transcript']},
            {'heading': "Your Sixty-Second <span class='accent'>Tutorial</span>",
             'scenario': 'Record a sixty-second tutorial on something you know how to do: your everyday makeup, your hair, a recipe, or how you prepare for an exam. Say the result first, then the steps.',
             'footer': 'No notes, sixty seconds. One signal word per step, and no stopping to find the perfect word.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for <span class='accent'>Getting Things Done</span>", 'sub': 'At the salon and at the exchange office'},
    'survival_heading': "Five Sentences for <span class='accent'>Getting Things Done</span>",
    'survival': [
        'I would like to have my hair cut, but only a trim, please.',
        'I had my transcript translated by a certified translator.',
        'First I get the letter notarized, and then I send everything together.',
        'I do my makeup myself, because I learned from tutorials.',
        'Can you show me how you blend it, step by step?',
    ],
    'checklist': [
        'I can explain a process in order, with one signal word for each step.',
        'I use have or get + object + past participle when somebody does something for me.',
        'I put the tense on have or get, not on the main verb.',
        'I can ask for a service at a salon and explain what I do not want.',
        'I know the words: a tutorial, a trim, layers, bangs, highlights, a shade, to blend, to touch up, an appointment, a walk-in, a certified translation, to notarize, a transcript.',
    ],
    'badge': {'name': 'The Tutorial Voice', 'line': 'The result first, the steps in order, and the work you have done for you.',
              'next': 'Next lesson: The Fine Print You Already Signed -- the terms of the apps you use, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today you explain a process, and you talk about the things other people do for you.\' Contexto: ela disse que gosta de ver videos no YouTube sobre maquiagem e cabelo &mdash; e tema de energia alta, e o consultor prometeu trazer isso. A outra metade (traducao juramentada, notarizacao) e a burocracia real do intercambio. Deixe ela falar muito sobre os tutoriais antes de corrigir.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta sobre o ultimo tutorial. Callback das aulas 5 e 6: exija uma condicional (\'if I had watched it before...\') e um modal de deducao (\'she must have practiced a lot\'). ANOTE se ela ja usa \'had it done\' ou diz \'I cut my hair\' para servico de salao.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Diga que explicar um processo em ordem e uma tarefa classica de speaking, e que o resultado primeiro evita que a fala se perca. Nao de a regra da causativa ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Sessenta segundos, cronometrado. ANOTE: ela disse o resultado antes? Usou palavras de sequencia? Quantas vezes recomecou? Compare com o tutorial do role-play livre.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words: half from the salon, half from the exchange office.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'a trim\': \'Big change or only the ends? (So as pontas.)\' CCQ \'bangs\': em ingles americano; o britanico diz fringe. CCQ \'highlights\': \'The whole head, or thin parts? (Mechas.)\' Peca que ela descreva o proprio cabelo com duas palavras do slide.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a shade\': \'A new color, or a variety of one color? (Tom.)\' CCQ \'to blend\': \'Do you want a line or no line? (Sem linha.)\' CCQ \'a walk-in\': \'With or without an appointment? (Sem.)\' Pronuncia: ap-POINT-ment.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'a certified translation\': \'Can a friend do it? (Nao.)\' CCQ \'to notarize\': \'Is it a translation or an official stamp? (Carimbo oficial.)\' CCQ \'a transcript\': em contexto academico e o historico escolar, nao a transcricao de um audio. Pronuncia: NO-ta-rize.',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> CER-ti-fied trans-LA-tion, NO-ta-rize, TRAN-script. Na frase longa, dois blocos: \'I had my transcript translated / and then I got the letter notarized.\' Cobre o -ed de translated (/id/) e notarized (/d/).',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ela diz a palavra ANTES de clicar, escolhendo do banco. Se fechar rapido, peca uma frase dela com \'to touch up\'.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences. In every one, somebody did the work, and it was not the speaker.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Did she cut her hair herself? Where is the object, and what form is the verb?\' Espere ela ver a ordem have + objeto + participio. So entao Reveal the Rule. CCQ: \'I had my hair cut &mdash; who held the scissors? (O cabeleireiro.)\' CCQ: \'I had cut my hair &mdash; is it the same? (Nao: past perfect, ela mesma cortou.)\' Obstaculo numero um do brasileiro: \'I cut my hair\' para servico de salao (em portugues \'cortei o cabelo\' serve para os dois). Obstaculo dois: ordem trocada, \'had translated my transcript\'.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na quinta, explique que a mesma estrutura serve para coisa ruim que aconteceu (had my phone stolen).',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now a salon in London during your exchange, two recordings, and a receipt from a translation service.\'',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e o Marco: cabeleireiro simpatico e falante em Londres. Clique Next Line e toque o audio. Nas falas da Luiza, ela fala PRIMEIRO. PRAGMATICA: repare como a Luiza diz o que NAO quer (\'no bangs\') com uma historia curta &mdash; e mais educado e mais claro do que so dizer nao. Na ultima fala ela pede um tutorial ao vivo: e o jeito natural de pedir para alguem mostrar.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre o MARCO, nunca sobre a Luiza (REGRA 27F). Depois pergunte se ela ja teve uma experiencia ruim em salao.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Criadora de conteudo explicando o processo: e o universo que ela acompanha no YouTube. Depois pergunte qual criadora ela segue e se o processo parece o mesmo.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Recado de secretaria, voz masculina, com passos em ordem. Os requisitos sao ficticios e genericos; nao apresente como regra de uma universidade real.',
        'artifact': '<strong>Artefato (4 min):</strong> Recibo ficticio de servico de traducao, com o nome dela. Peca que ela explique cada linha com causativa: \'I had my transcript translated.\' So depois as 3 perguntas.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\'',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros: servico dito como se ela tivesse feito, ordem trocada, get notarize sem participio, having check. Enquadramento: \'os mais comuns\'.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas. A segunda e sobre a Escocia real dela. Respostas na tela sao sugestao. Correcao em bloco no fim, no maximo tres pontos.',
        'building': '<strong>Sentence Building (4 min):</strong> Ela monta a frase COMPLETA em voz alta antes de clicar, num bloco so.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same service, three times. The last one is your own tutorial.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o Marco. Ela diz o que quer, o que nao quer, uma coisa que fez antes e se arrependeu, e uma pergunta. Corrija so a causativa, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o colega que vai para o intercambio. Exija o processo em ordem com palavras de sequencia e pelo menos duas causativas. Se ela nao souber a burocracia real, deixe inventar: o foco e a estrutura.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Sessenta segundos de tutorial, sem nota, sobre o que ela quiser. Cronometre. No fim, dois numeros: quantas vezes recomecou (compare com o diagnostico) e quantas palavras de sequencia usou. Se ela topar, grave no celular dela: e o formato que ela consome.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you explained your routine. Now you can explain any process, and ask anyone to do it for you.\'',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete em um bloco so.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 7. Item em que ela hesitar entra no warm-up da aula 8.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the best tutorial is the one where every step has a reason.\' Homework (ORALMENTE, nunca escrito na tela): gravar um tutorial de sessenta segundos em ingles sobre qualquer coisa que ela sabe fazer, com o resultado primeiro, e trazer. Proxima aula: os termos dos aplicativos que ela ja aceitou, em leitura.',
    },
    'pc': {
        'title': 'The Tutorial Voice -- Getting Things Done',
        'desc': 'Explain a process step by step, and talk about what you have done for you: at the salon and at the exchange office.',
        'match_idx': [0, 1, 6, 9, 10, 11],
        'context': [
            'A good <strong>tutorial</strong> has a simple structure: the result first, then the steps in order, each one with a signal word like <em>first</em>, <em>then</em> or <em>once</em>. But real processes are rarely done by one person. Part of the work is done for you, and English has a special structure to say that.',
            'When somebody else does a service for you, use <strong>have</strong> + object + past participle: &ldquo;I <strong>had my hair cut</strong> last Friday.&rdquo; If you say &ldquo;I cut my hair&rdquo;, English understands that you held the scissors yourself. In informal speech, <strong>get</strong> works the same way: &ldquo;She <strong>got her transcript translated</strong>.&rdquo; If it matters who did the work, add <strong>by</strong>: &ldquo;by a certified translator&rdquo;.',
            'The tense goes on <em>have</em> or <em>get</em>, never on the main verb: &ldquo;We <strong>are getting</strong> our documents checked,&rdquo; &ldquo;I <strong>will have</strong> the letter <strong>notarized</strong>.&rdquo; The same structure also describes something bad that happened to you: &ldquo;He <strong>had his phone stolen</strong> on the first day.&rdquo;',
            'Be careful with the order. &ldquo;I <strong>had my hair cut</strong>&rdquo; is a service; &ldquo;I had cut my hair&rdquo; is the past perfect, and it means you did it yourself, earlier. A <strong>certified translation</strong>, a <strong>transcript</strong> sent from Brazil and a letter stamped by a notary: none of them is done by you, and all of them need the causative.',
        ],
        'context_quiz': [
            ('According to the text, what does &ldquo;I cut my hair&rdquo; mean in English?', ['That a salon cut it.', 'That you cut it yourself.', 'That you will cut it later.'], 1),
            ('Where does the tense go in a causative sentence?', ['On have or get.', 'On the main verb.', 'On the word by.'], 0),
            ('What is the difference between &ldquo;I had my hair cut&rdquo; and &ldquo;I had cut my hair&rdquo;?', ['There is no difference.', 'The first is informal and the second is formal.', 'The first is a service; the second means you did it yourself, earlier.'], 2),
        ],
        'tip_title': 'The Causative: Have and Get Something Done',
        'tip_lead': 'Have or get, then the object, then the past participle: the work was done for you.',
        'tip_rows': [
            ('A service', 'have + object + past participle', 'I <strong>had my hair cut</strong>.'),
            ('Informal', 'get + object + past participle', 'She <strong>got it translated</strong>.'),
            ('Who did it', 'causative + by + person', 'translated <strong>by a certified translator</strong>'),
            ('Future', 'will have / am going to get + object + participle', 'I <strong>will have</strong> it notarized.'),
            ('In progress', 'am / are getting + object + participle', 'We <strong>are getting</strong> it checked.'),
            ('Something bad', 'have + object + participle', 'He <strong>had his phone stolen</strong>.'),
        ],
        'tip_never': 'I cut my hair at the salon (if somebody else did it) &middot; she had translated her transcript by a translator &middot; get notarize the letter &middot; we are having check our documents',
        'blanks': [
            ('I did not do it myself: I ', 'had my hair cut', ' at a salon.', 'Hint: have + object + participle -- four words', None),
            ('She ', 'got her transcript translated', ' by a certified translator.', 'Hint: get + object + participle -- four words', None),
            ('Before I apply, I need to ', 'have the letter notarized', '.', 'Hint: a service in the future -- four words', None),
            ('He ', 'had his phone stolen', ' on his first day in London.', 'Hint: something bad that happened to him -- four words', None),
            ('Use your fingers to ', 'blend', ' the product into your skin.', 'Hint: mix it in so there are no lines -- one word', None),
            ('The salon was full, so I made an ', 'appointment', ' for Friday.', 'Hint: an arrangement to see somebody at a time -- one word', None),
        ],
        'order_title': 'Put the Process in Order',
        'order_lead': 'A classmate asks how to prepare the documents for the exchange. Put the steps in a logical order.',
        'order': [
            'First, request your official transcript from GV.',
            'Then have it translated by a certified translator.',
            'Once the translation is ready, get the coordinator&rsquo;s letter notarized.',
            'After that, check that every document has an original signature.',
            'Send all the documents together in a single email.',
            'Finally, register as soon as registration opens.',
        ],
        'quiz': [
            ('A friend asks about your new haircut. You say:', ['I cut my hair at a salon on Friday.', 'I had my hair cut at a salon on Friday.', 'I had cut my hair by a salon on Friday.'], 1),
            ('You explain that a professional translated your grades. You say:', ['I got my transcript translated by a certified translator.', 'I translated my transcript by a certified translator.', 'I got translate my transcript.'], 0),
            ('At the salon, you want only a small cut. You say:', ['I want highlights, please.', 'I want bangs, please.', 'Just a trim, please.'], 2),
            ('You arrive at a salon without an appointment. The receptionist asks:', ['Are you a walk-in?', 'Are you a trim?', 'Are you a shade?'], 0),
        ],
        'think': 'Record a ninety-second tutorial about something you know how to do: your everyday makeup, your hair, a recipe, or how you prepare for an exam at GV. Say the result first, then the steps in order, and include at least two things you have done by somebody else, with have or get.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'Nina Ubhi &mdash; &ldquo;The Best Everyday Natural Makeup Tutorial for Beginners&rdquo; (YouTube)',
         'desc': 'A step-by-step beauty tutorial with a clear structure: the result, the products, and every step explained before it happens. Watch it for the language of the process.',
         'tip': 'Tip: pause after each step and describe it in one sentence with a signal word: first, then, once, after that.',
         'url': 'https://www.youtube.com/watch?v=Kvwn93VPcv0', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'Queer Eye &mdash; Season 1, Episode 1, &ldquo;You Can&rsquo;t Fix Ugly&rdquo;',
         'desc': 'Five experts change one person&rsquo;s life in a week, and a lot of it is getting things done: a haircut, new clothes, a house redesigned. Full of causatives in real American speech.',
         'tip': 'Tip: every time somebody has something done for them, say the sentence with have or get.',
         'url': 'https://www.tvmaze.com/episodes/1397826/queer-eye-1x01-you-cant-fix-ugly', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Sal Khan &mdash; &ldquo;Let&rsquo;s use video to reinvent education&rdquo; (TED)',
         'desc': 'The founder of Khan Academy on how short video tutorials changed the way millions of people learn. A good talk for somebody who learned English from videos.',
         'tip': 'Tip: summarize his process in three steps, using first, then and finally.',
         'url': 'https://www.ted.com/talks/sal_khan_let_s_use_video_to_reinvent_education', 'cta': 'Watch on TED'},
    ],
}
