# -*- coding: utf-8 -*-
# Aula 4 -- Who Judges a State? (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "Who Judges <span class='accent'>a State?</span>",
    'hero_line': 'Three international courts, three different questions, and the relative clauses that keep them apart',
    'menu_desc': 'Which court hears which case, and the relative clauses that define it -- 35 slides',
    'grammar_point': 'defining and non-defining relative clauses with who, which, whose and where',
    'phases': ['The Question', 'Words of the Court', 'The Text Itself', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'daniel', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1589829545856-d10d557cf95f?w=1400&q=80',
        'ch2': U + 'photo-1505664194779-8beaceb93744?w=1400&q=80',
        'ch3': U + 'photo-1532012197267-da84d127e765?w=1400&q=80',
        'ch_grammar': U + 'photo-1456513080510-7bf3a84b82f8?w=1400&q=80',
        'ch5': U + 'photo-1497633762265-9d179a990aa6?w=1400&q=80',
        'ch_rp': U + 'photo-1517048676732-d65bc937f952?w=1400&q=80',
        'pc': U + 'photo-1589829545856-d10d557cf95f?w=600&q=80',
    },
    'warmup': {
        'heading': "If a Country Breaks <span class='accent'>a Treaty&hellip;</span>",
        'sub': 'Who should decide that it was a breach: another country, an international court, or nobody? Say what you think, and why.',
    },
    'target': {
        'heading': "Three Courts, <span class='accent'>Three Questions</span>",
        'steps': [
            'Who can bring the case: a state, a person, or both?',
            'Who is judged: a state, or an individual?',
            'What happens after the ruling, and who can enforce it?',
        ],
    },
    'diagnostic': {
        'heading': "The Hague, or <span class='accent'>San Jos&eacute;?</span>",
        'p1': 'A classmate says: &ldquo;A Brazilian citizen whose rights were violated by the state can go straight to an international court in The Hague.&rdquo;',
        'p2': 'Is that right? Answer in three sentences, and say which court you think your classmate is confusing.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Court</span>",
            'sub': 'Thirteen words you meet in every judgment, before the first paragraph ends'},
    'vocab': [
        {'word': 'A ruling', 'def': 'An official decision made by a court or a judge', 'ex': 'The ruling was published in English and in French.', 'icon': 'doc'},
        {'word': 'To rule on', 'def': 'To give an official decision about a case or a question', 'ex': 'The court will rule on the dispute next year.', 'icon': 'scale'},
        {'word': 'Jurisdiction', 'def': 'The official power of a court to hear and decide a particular case', 'ex': 'The court said it had no jurisdiction over the dispute.', 'icon': 'shield'},
        {'word': 'A tribunal', 'def': 'A court or a group of judges created for a special kind of case', 'ex': 'An arbitration tribunal decided the investment dispute.', 'icon': 'users'},
        {'word': 'To hear a case', 'def': 'To listen to both sides in court before making a decision', 'ex': 'Fifteen judges hear every case at the International Court of Justice.', 'icon': 'mic'},
        {'word': 'To file a complaint', 'def': 'To make a formal accusation to an official body', 'ex': 'The family filed a complaint with the Inter-American Commission.', 'icon': 'pen'},
        {'word': 'Admissible', 'def': 'Accepted by a court as valid enough to be considered', 'ex': 'The petition was not admissible, because the national courts had not decided yet.', 'icon': 'filter'},
        {'word': 'To uphold', 'def': 'To confirm that an earlier decision was correct', 'ex': 'The higher court upheld the first ruling.', 'icon': 'hand'},
        {'word': 'To overturn', 'def': 'To officially change a decision so that it is no longer valid', 'ex': 'The appeal court overturned the conviction.', 'icon': 'refresh'},
        {'word': 'An advisory opinion', 'def': 'A court&rsquo;s formal view on a legal question, given when an organization asks for it, not in a dispute', 'ex': 'The court gave an advisory opinion on the obligations of states.', 'icon': 'book'},
        {'word': 'A precedent', 'def': 'An earlier decision that is used as an example for later cases', 'ex': 'The judgment created a precedent for future cases.', 'icon': 'layers'},
        {'word': 'A member state', 'def': 'A country that belongs to an international organization', 'ex': 'Every member state of the United Nations can use the court.', 'icon': 'globe'},
        {'word': 'To consent to', 'def': 'To officially agree to something', 'ex': 'A state is judged only if it has consented to the court&rsquo;s jurisdiction.', 'icon': 'key'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['Jurisdiction', 'Admissible', 'An advisory opinion', 'The court said it had no jurisdiction, because the state had never consented.'],
    'ch3': {'heading': "The Text on <span class='accent'>Your Reading List</span>",
            'sub': 'Four short paragraphs. Read once for the argument; the detail comes after.'},
    'reading': {
        'heading': "Three Courts, <span class='accent'>Often Confused</span>",
        'rtitle': 'Three Courts, Often Confused',
        'paras': [
            'When a news report says that a case has gone to an international court, most readers imagine one building where all the world&rsquo;s disputes are decided. In reality there are several courts, which answer very different questions, and students who confuse them usually make the same mistake: they ask who was right before asking who has jurisdiction.',
            'The International Court of Justice, which sits in The Hague, is the principal court of the United Nations. It hears disputes between states, and only between states. No individual can file a complaint there. Its fifteen judges can rule on a case only when the states involved have consented to their jurisdiction, and member states of the United Nations have agreed to comply with its rulings. The court can also give advisory opinions, which are requested by United Nations bodies rather than by a party to a dispute.',
            'The International Criminal Court, whose headquarters are also in The Hague, works the other way around. It judges individuals, not states, for crimes such as genocide and war crimes. It was created by the Rome Statute, which entered into force in 2002, and it acts only when national courts are unable or unwilling to do so.',
            'For a Brazilian citizen whose rights have been violated by the state, the path is regional. A complaint is first filed with the Inter-American Commission on Human Rights, and only the Commission or a state can take the case to the Inter-American Court, which is based in San Jos&eacute;, Costa Rica. Brazil accepted that court&rsquo;s jurisdiction in 1998. Its rulings are binding, but, like every international court, it depends on the state to put them into practice.',
        ],
        'source': 'Written for this lesson, from the public descriptions of the International Court of Justice, the International Criminal Court and the Inter-American human rights system.',
    },
    'gist': {
        'prompt': 'What is the main purpose of the text?',
        'choices': [
            ['a', 'To show that international courts are more powerful than national courts.', False],
            ['b', 'To explain that different international courts judge different parties, so the first question is always jurisdiction.', True],
            ['c', 'To argue that Brazil should leave the Inter-American system.', False],
        ],
    },
    'tf': [
        ['According to the text, a person can file a complaint directly at the International Court of Justice.', 'f', 'The text says the court hears disputes only between states, and no individual can file a complaint there.'],
        ['The International Court of Justice can decide a case only if the states involved have consented to its jurisdiction.', 't', 'The text says its judges can rule on a case only when the states have consented.'],
        ['The International Criminal Court judges states for crimes such as genocide.', 'f', 'The text says it judges individuals, not states.'],
        ['A Brazilian citizen first goes to the Inter-American Commission, not directly to the Court.', 't', 'The text says a complaint is first filed with the Commission, and only the Commission or a state can take it to the Court.'],
        ['The text says the Inter-American Court can enforce its rulings without the state.', 'f', 'The text says its rulings are binding, but it depends on the state to put them into practice.'],
    ],
    'artifact': {
        'heading': "The Fact Sheet from <span class='accent'>Week Four</span>",
        'title': 'COURT COMPARISON SHEET', 'subtitle': 'Global Law &middot; Week 4 &middot; Prepared for: L. Sato Eccheli',
        'rows': [
            ('International Court of Justice', 'The Hague &mdash; states v. states, with consent', True),
            ('International Criminal Court', 'The Hague &mdash; individuals, for the gravest crimes', False),
            ('Inter-American Court of Human Rights', 'San Jos&eacute; &mdash; cases sent by the Commission or a state', True),
            ('Advisory opinions', 'Requested by an organization, not by a party to a dispute', False),
            ('Enforcement', 'Depends on the state in every case', False),
        ],
        'note': 'Seminar note: for Friday, choose one ruling from any of the three courts. Be ready to say who brought the case, whose rights or interests were at stake, and whether the ruling was put into practice.',
        'qs': [
            ('Which two courts are in The Hague, and what is the difference between them?', 'The International Court of Justice and the International Criminal Court. One judges disputes between states; the other judges individuals.'),
            ('Who can send a case to the Inter-American Court?', 'The Commission or a state.'),
            ('According to the seminar note, what three things must students be ready to say about their ruling?', 'Who brought the case, whose rights or interests were at stake, and whether the ruling was put into practice.'),
        ],
    },
    'ch_grammar': {'heading': "The Clause That Tells You <span class='accent'>Which One</span>",
                   'sub': 'Four sentences about courts, and the commas that change the meaning'},
    'grammar': {
        'heading': "Why a Comma <span class='accent'>Here?</span>",
        'examples': [
            "The court <span style='color:#b91c1c;font-weight:700'>which hears disputes between states</span> is in The Hague.",
            "The Inter-American Court<span style='color:#1d4ed8;font-weight:700'>, which is based in San Jos&eacute;,</span> hears human rights cases.",
            "A citizen <span style='color:#b91c1c;font-weight:700'>whose rights were violated</span> can file a complaint.",
            "Students <span style='color:#b91c1c;font-weight:700'>who confuse the courts</span> make the same mistake.",
        ],
        'prompt': 'Look at the red and the blue parts. If you delete the red part, do we still know WHICH court or WHICH citizen? And if you delete the blue part? Why does only the blue one have commas?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Identify which one (essential)', 'noun + who / which / that + clause, no commas', 'The court <strong>which hears disputes between states</strong> is in The Hague.'),
            ('Add extra information (not essential)', 'noun, + who / which + clause, (commas)', 'The Court<strong>, which is based in San Jos&eacute;,</strong> hears human rights cases.'),
            ('Possession', 'whose + noun', 'A citizen <strong>whose rights</strong> were violated.'),
            ('A place', 'where + clause', 'The Hague is the city <strong>where</strong> both courts sit.'),
            ('People or things in essential clauses', 'that can replace who or which', 'The judges <strong>that</strong> heard the case.'),
            ('Extra information', 'never that after a comma', 'Brazil<strong>, which</strong> accepted the court in 1998, &hellip;'),
            ('The trap', 'never <em>the court who</em>; never <em>whose its</em>', 'Not <em>a citizen whose his rights</em>. Say <strong>a citizen whose rights</strong>.'),
        ],
        'oneliner': 'No commas when the clause tells you which one; commas when it only adds information, and never that after a comma.',
    },
    'grammar_practice': {
        'heading': "Which One, or <span class='accent'>Extra Information?</span>",
        'items': [
            ('The court ', 'which', ' hears disputes between states is in The Hague. (a thing, essential)'),
            ('Judges ', 'who', ' sit on that court are elected for nine years. (people, essential)'),
            ('A citizen ', 'whose', ' rights were violated can file a complaint. (possession)'),
            ('The Hague is the city ', 'where', ' the two courts are based. (a place)'),
            ('Brazil', ', which', ' accepted the court in 1998, can be judged there. (extra information, with a comma)'),
            ('The ruling ', 'that', ' the court published last week was upheld. (essential, and that is possible)'),
        ],
    },
    'detective': [
        ('The court who hears disputes between states is in The Hague.', 'The court <strong>which</strong> hears disputes between states is in The Hague.'),
        ('A citizen whose his rights were violated can file a complaint.', 'A citizen <strong>whose rights</strong> were violated can file a complaint.'),
        ('Brazil, that accepted the court in 1998, can be judged there.', 'Brazil<strong>, which</strong> accepted the court in 1998, can be judged there.'),
        ('The Hague is the city which the two courts are based.', 'The Hague is the city <strong>where</strong> the two courts are based.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>",
            'sub': 'Court language and plain English &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Judgment in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each line of the judgment to the same idea in plain English',
        'hint': 'Tap a line from the judgment, then tap the sentence that means the same',
        'pairs': [
            ('The Court finds that it has no jurisdiction to entertain the application.', 'The court says it does not have the power to decide this case.'),
            ('The petition is declared inadmissible.', 'The court will not consider the request, because it is not valid.'),
            ('The judgment of the lower court is upheld.', 'The first decision was correct and stays as it is.'),
            ('The State shall comply with this judgment within one year.', 'The country has twelve months to do what the court ordered.'),
            ('The Court delivers the following advisory opinion.', 'This is the court&rsquo;s formal view on a question, not a decision in a dispute.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Case Summary</span>",
    'gap': {
        'parts': [
            'A family ', ['1', 'filed a complaint'], ' with the Commission, but the Commission first had to decide whether the petition was ',
            ['2', 'admissible'], '. Once it was accepted, the case went to the Court, which had ', ['3', 'jurisdiction'],
            ' because the state had ', ['4', 'consented to'], ' it years before. The judges agreed to ', ['5', 'hear the case'],
            ' in public, and a year later they issued a ', ['6', 'ruling'], ' against the state. The state asked the Court to review it, but the Court decided to ',
            ['7', 'uphold'], ' its decision, which is now cited as a ', ['8', 'precedent'], ' in similar cases.',
        ],
        'bank': ['filed a complaint', 'admissible', 'jurisdiction', 'consented to', 'hear the case', 'ruling', 'uphold', 'precedent'],
    },
    'quickfire': [
        {'situation': 'A classmate thinks any person can sue a country at the International Court of Justice. Correct them in two sentences.', 'tips': ['No: the International Court of Justice hears disputes only between states. A person whose rights were violated has to go through a regional system.', 'Use only between states and whose rights.']},
        {'situation': 'Explain what jurisdiction means, without using the word jurisdiction.', 'tips': ['It is the power that a court has to hear and decide a particular case.', 'A defining relative clause: the power that a court has.']},
        {'situation': 'Describe the International Criminal Court in one sentence with a non-defining relative clause.', 'tips': ['The International Criminal Court, which is based in The Hague, judges individuals, not states.', 'Commas around which, and never that.']},
        {'situation': 'Say that a higher court confirmed the first decision, and then say that another court cancelled one.', 'tips': ['The higher court upheld the first ruling, but a different court overturned another one.', 'uphold versus overturn.']},
        {'situation': 'Tell a friend where the Inter-American Court is, using where.', 'tips': ['San Jos&eacute;, in Costa Rica, is the city where the Inter-American Court is based.', 'the city where + clause.']},
        {'situation': 'Explain the difference between a ruling and an advisory opinion.', 'tips': ['A ruling decides a dispute between parties, while an advisory opinion is a formal view that an organization asks for.', 'Relative clause: that an organization asks for.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Lecture', 'title': "Jurisdiction <span class='accent'>First</span>",
         'blurb': 'A professor of international law on the first question of every case. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Every year I give my students a case and ask them who should win, and every year they start in the wrong place. The first question in international law is not who is right. It is whether the court has jurisdiction. National courts have jurisdiction almost automatically: if you live in a country, its courts can judge you. International courts are different. A state is judged only if it has agreed to be judged, and that consent can be given in a treaty, in a special agreement, or in a declaration made years before the dispute began. So when a court says it has no jurisdiction, it is not saying the state was innocent. It is saying that the question was never allowed into the room. Remember that distinction, because it appears in almost every exam I write.',
         'qs': [
             ('Where does the professor say her students start, and why is it the wrong place?', 'They start with who should win, but the first question is whether the court has jurisdiction.'),
             ('How is an international court different from a national court?', 'A state is judged only if it has agreed to be judged; national courts have jurisdiction almost automatically.'),
             ('When a court says it has no jurisdiction, what is it NOT saying?', 'It is not saying that the state was innocent; the question was never allowed into the room.'),
         ]},
        {'label': 'Listening 2 &middot; A Radio Explainer', 'title': "A Ruling Nobody <span class='accent'>Follows</span>",
         'blurb': 'A short radio explainer on what happens after a judgment. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Listeners often ask us a fair question. If an international court orders a country to do something, and the country simply does not do it, what happens next? The honest answer is that there is no international police that arrives at the border. Enforcement works in quieter ways. A ruling that is ignored damages the reputation of the government that ignores it, and other states remember that in their next negotiation. Some courts send the case to a political body, which can put diplomatic pressure on the state. And inside the country, lawyers and judges often use the international ruling to change national law, one case at a time. Researchers who study these courts say that full compliance is rare, but partial compliance is common, and it often arrives years after the ruling.',
         'qs': [
             ('What does the explainer say does NOT happen when a country ignores a ruling?', 'No international police arrives at the border.'),
             ('What are two quieter ways enforcement works?', 'Any two: damage to the government&rsquo;s reputation, pressure from a political body, and lawyers and judges using the ruling to change national law.'),
             ('What do researchers say about compliance?', 'Full compliance is rare, but partial compliance is common, and it often arrives years after the ruling.'),
         ]},
    ],
    'roleplays': {
        'heading': "The Same Question, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Which Court <span class='accent'>Is It?</span>",
             'scenario': 'Three short cases: two states disagree about a border; a former general is accused of war crimes; a Brazilian family says the police violated their rights. Say which court hears each one, using a relative clause in every answer.',
             'chips': ['which hears disputes between states', 'whose rights were violated', 'jurisdiction', 'to file a complaint']},
            {'heading': "The Professor <span class='accent'>Pushes Back</span>",
             'scenario': 'Your professor says: &ldquo;If states can ignore the ruling, the court is useless.&rdquo; Disagree politely, give one way rulings still have an effect, and ask the professor one question.',
             'chips': ['a ruling', 'to comply with', 'a precedent', 'a member state']},
            {'heading': "Two Minutes, <span class='accent'>No Notes</span>",
             'scenario': 'Explain to a first-year student the difference between the three courts in the text: who they judge, who can bring a case, and where they are.',
             'footer': 'No notes, two minutes. One court per block, with a relative clause in each.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>the Seminar</span>",
    'survival': [
        'The first question is not who is right, but whether the court has jurisdiction.',
        'The International Court of Justice, which sits in The Hague, hears disputes only between states.',
        'A citizen whose rights were violated first goes to the Inter-American Commission.',
        'The higher court upheld the ruling, so the first decision stays as it is.',
        'Rulings are binding, but compliance depends on the state.',
    ],
    'checklist': [
        'I can say which international court hears which kind of case.',
        'I use who for people, which for things, whose for possession and where for places.',
        'I put commas around extra information, and I never use that after a comma.',
        'I can read a line from a judgment and say it in plain English.',
        'I know the words: a ruling, to rule on, jurisdiction, a tribunal, to hear a case, to file a complaint, admissible, to uphold, to overturn, an advisory opinion, a precedent, a member state, to consent to.',
    ],
    'badge': {'name': 'The Court Map', 'line': 'Who judges whom, where, and the commas that tell you which one.',
              'next': 'Next lesson: A Semester Abroad -- the choices of an exchange year, in conversation'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we read about the courts that judge states, and we read it faster than last time.\' Contexto: e o assunto da disciplina de Direito Global dela, onde toda a leitura e em ingles. Lembre: texto curto, objetivo de velocidade. Compare o tempo da leitura de hoje com o da aula 2.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta. Callback das aulas 2 e 3: exija uma palavra de tratados (a breach, to enforce, sovereignty) e um verbo de relato (\'my professor argued that...\'). Deixe ela opinar livremente; opiniao em ingles e o que o TOEFL novo pede no Take an Interview. ANOTE onde travou.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre as 3 perguntas. Ligue a aula 2: tratado so obriga quem ratificou; tribunal so julga quem aceitou a jurisdicao. Nao de a regra das relativas ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> A frase do colega mistura a Corte Internacional de Justica (Haia, so Estados) com o sistema interamericano. Deixe ela argumentar em tres frases. Se ela souber a resposta pelo curso, otimo: cobre o ingles, nao o conteudo.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words from every judgment.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'a ruling\': \'Is it the argument of a lawyer or the decision of the court? (A decisao.)\' CCQ \'jurisdiction\': \'Is it about who is right, or about who has the power to decide? (O poder.)\' CCQ \'to hear a case\': \'Do the judges only listen, or also decide later? (Ouvem antes de decidir.)\' Pronuncia: jur-is-DIC-tion, acento na terceira.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'admissible\': \'Is it the final decision or the first filter? (O primeiro filtro.)\' CCQ \'to uphold x to overturn\': \'Which one keeps the first decision? (Uphold.)\' CCQ \'an advisory opinion\': \'Is there a dispute between two parties? (Nao.)\' Pronuncia: ad-MIS-si-ble, ad-VI-so-ry.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'a precedent\': \'Is it a future case or an earlier one? (Anterior.)\' CCQ \'to consent to\': \'Did the state agree, or was it forced? (Concordou.)\' Cobre a preposicao: consent TO.',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> jur-is-DIC-tion, ad-MIS-si-ble, ad-VI-so-ry O-pin-ion. Na frase longa, dois blocos: \'The court said it had no jurisdiction / because the state had never consented.\' Se travar, recomeca o bloco.',
        'matching': '<strong>Matching (3 min):</strong> Ela liga palavra e definicao. Se errar, volte ao CCQ do card, sem dar a resposta.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'Four paragraphs, three courts. Read once, and do not stop on any word.\'',
        'reading': '<strong>Leitura (6 min):</strong> Primeira passada em silencio com cronometro, SEM dicionario. Anote o tempo e compare com a aula 2: se caiu, diga o numero a ela &mdash; e o progresso que ela quer ver (\'em ingles eu demoro muito pra entender\'). Depois UMA frase de resumo em voz alta.',
        'gist': '<strong>Gist (3 min):</strong> Ela escolhe e justifica por que as outras duas estao erradas.',
        'tf': '<strong>True or False (6 min):</strong> Ela diz TRUE ou FALSE e LE a linha que prova antes de clicar. Sem a linha, nao vale.',
        'artifact': '<strong>Artefato (4 min):</strong> Folha comparativa ficticia de seminario, com o nome dela. Peca que transforme cada linha em frase com relativa: \'The International Court of Justice, which sits in The Hague, hears disputes between states.\' So depois as 3 perguntas. Os fatos da folha (sedes, quem julga, Brasil desde 1998) sao reais; a nota do seminario e ficticia.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about courts. Some parts have commas, and some do not.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'If you delete the red part, do we know which court? If you delete the blue part?\' Espere ela concluir: sem virgula = identifica; com virgula = informacao extra. So entao Reveal the Rule. CCQ: \'The Inter-American Court, which is based in San Jose &mdash; is there more than one Inter-American Court? (Nao, por isso a virgula.)\' CCQ: \'A citizen whose rights were violated &mdash; whose rights? (Do cidadao.)\' Obstaculos do brasileiro: \'the court who\' (who so para pessoas), \'whose his\' (duplica o possessivo, calco de \'cujos seus\') e \'that\' depois de virgula.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar, marcando a pausa da virgula na quinta. A pausa na fala e a virgula na escrita: aponte.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros classicos: who para coisa, whose his, that depois de virgula e which no lugar de where. Enquadramento: \'os mais comuns\'.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: the judgment in plain English, a case summary, quick questions, and two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ela liga a linha da sentenca ao ingles simples e EXPLICA a ligacao. E paráfrase de registro alto, exatamente o que o reading do TOEFL cobra. Se fechar rapido, peca que reescreva \'The petition is declared inadmissible\' com as proprias palavras.',
        'gap': '<strong>Gap-fill (4 min):</strong> Ela arrasta, toca ou digita a palavra do banco e confere com Check. Se errar, aponte a palavra ao redor da lacuna (\'consented ___\', \'hear ___\').',
        'quickfire': '<strong>Quick fire (5 min):</strong> Uma pergunta por vez, em velocidade normal. Ela responde ANTES da dica. Regra: cada resposta com uma relativa. Corrija so a relativa, depois que ela terminar.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Depois peca que ela resuma em trinta segundos com os tres blocos da aula 3 e um verbo de relato.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Radio, voz masculina. Depois das respostas, ligue ao warm-up: ela mudou de opiniao sobre quem deve decidir?',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same question, three times. The last one is you explaining it to a first-year student.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Leia os tres casos. Ela diz qual tribunal para cada um, com relativa. Corrija so a relativa, no fim. Se ela confundir os tribunais, volte a folha comparativa, nao explique de novo.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o professor provocador. Exija discordancia educada (\'I see your point, but...\'), um efeito real das decisoes e uma pergunta de volta. Opiniao com razao, sem roteiro: e o Take an Interview do TOEFL novo.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota. Cronometre. No fim, dois numeros: quantas vezes recomecou uma frase e quantas relativas usou. Compare com as aulas 1 e 3.',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete em blocos, marcando a pausa das virgulas na segunda.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 4. Item em que ela hesitar entra no warm-up da aula 5.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, before you ask who is right, ask who has jurisdiction.\' Homework (ORALMENTE, nunca escrito na tela): escolher UMA decisao de qualquer um dos tres tribunais e explicar em ingles, em noventa segundos, quem levou o caso e se a decisao foi cumprida. Proxima aula: as escolhas de um semestre fora, em conversa.',
    },
    'pc': {
        'title': 'Who Judges a State? -- Relative Clauses in Legal English',
        'desc': 'Three international courts, three different jobs. Read which court hears which case, and the relative clauses that keep them apart.',
        'match_idx': [0, 2, 5, 6, 7, 12],
        'context': [
            'Legal writing loves long noun phrases, and most of them are held together by relative clauses. &ldquo;The court <strong>which</strong> hears disputes between states&rdquo; is not the same as &ldquo;the court <strong>which</strong> judges individuals&rdquo;, and the clause is the only thing that tells the reader which <strong>tribunal</strong> the text means.',
            'A <strong>defining</strong> clause identifies the noun, so it has no commas: &ldquo;Students <strong>who</strong> confuse the courts make the same mistake.&rdquo; Without it, the sentence would say that all students make the mistake. Use <strong>who</strong> for people, <strong>which</strong> for things, and <strong>that</strong> for either, but only in this kind of clause.',
            'A <strong>non-defining</strong> clause only adds information about a noun we already know, so it goes between commas: &ldquo;The Inter-American Court<strong>, which</strong> is based in San Jos&eacute;, hears human rights cases.&rdquo; There is only one Inter-American Court, so the clause is extra. After a comma, English never uses <em>that</em>.',
            'Two more words complete the set. <strong>Whose</strong> shows possession, and it replaces the possessive completely: &ldquo;a citizen <strong>whose</strong> rights were violated&rdquo;, never &ldquo;whose his rights&rdquo;. <strong>Where</strong> introduces a place: &ldquo;The Hague is the city <strong>where</strong> both courts sit.&rdquo; Once you see these clauses, a <strong>ruling</strong> that looked impossible to read becomes a list of simple facts about who, which and where.',
        ],
        'context_quiz': [
            ('According to the text, what does a defining relative clause do?', ['It adds extra information between commas.', 'It identifies which person or thing the sentence means.', 'It always uses whose.'], 1),
            ('Why does &ldquo;The Inter-American Court, which is based in San Jos&eacute;&rdquo; have commas?', ['Because there is only one such court, so the clause only adds information.', 'Because which always needs commas.', 'Because it is a place.'], 0),
            ('Which sentence does the text say is wrong?', ['The Hague is the city where both courts sit.', 'A citizen whose rights were violated.', 'A citizen whose his rights were violated.'], 2),
        ],
        'tip_title': 'Relative Clauses',
        'tip_lead': 'No commas when the clause tells you which one; commas when it only adds information.',
        'tip_rows': [
            ('People (defining)', 'who / that + clause', 'Judges <strong>who</strong> sit on the court.'),
            ('Things (defining)', 'which / that + clause', 'The court <strong>which</strong> hears disputes.'),
            ('Extra information', ', which / , who + clause,', 'The Court<strong>, which</strong> is in San Jos&eacute;, &hellip;'),
            ('Possession', 'whose + noun', 'A citizen <strong>whose</strong> rights were violated.'),
            ('A place', 'where + clause', 'The city <strong>where</strong> both courts sit.'),
            ('After a comma', 'never that', 'Brazil<strong>, which</strong> accepted it in 1998, &hellip;'),
        ],
        'tip_never': 'the court who hears disputes &middot; a citizen whose his rights &middot; Brazil, that accepted the court &middot; the city which the courts are based',
        'blanks': [
            ('The court ', 'which', ' hears disputes between states is in The Hague.', 'Hint: a thing, and the clause says which one -- one word', 'that'),
            ('A citizen ', 'whose', ' rights were violated can file a complaint.', 'Hint: possession -- one word', None),
            ('The Hague is the city ', 'where', ' both courts are based.', 'Hint: a place -- one word', None),
            ('In 1998, Brazil accepted the ', 'jurisdiction', ' of the Inter-American Court.', 'Hint: the power of a court to decide a case -- one word', None),
            ('The higher court decided to ', 'uphold', ' the first ruling.', 'Hint: confirm that a decision was correct -- one word', None),
            ('The petition was not ', 'admissible', ', so the court did not consider it.', 'Hint: accepted as valid enough to be considered -- one word', None),
        ],
        'order_title': 'Put the Path in Order',
        'order_lead': 'A Brazilian family says the police violated their rights. Put the path of their case in a logical order.',
        'order': [
            'First, the family goes through the national courts.',
            'Then they file a complaint with the Inter-American Commission.',
            'The Commission decides whether the petition is admissible.',
            'The Commission sends the case to the Inter-American Court.',
            'The Court hears the case and issues a ruling.',
            'The state has to put the ruling into practice.',
        ],
        'quiz': [
            ('A classmate says a person can sue a country at the International Court of Justice. You say:', ['Yes, anybody can file a complaint there.', 'No, that court hears disputes only between states.', 'No, that court judges only criminals.'], 1),
            ('You want to describe the Inter-American Court with extra information. You write:', ['The Inter-American Court, which is based in San Jos&eacute;, hears human rights cases.', 'The Inter-American Court, that is based in San Jos&eacute;, hears human rights cases.', 'The Inter-American Court who is based in San Jos&eacute; hears human rights cases.'], 0),
            ('The higher court confirmed the first decision. You say:', ['The higher court overturned the ruling.', 'The higher court consented the ruling.', 'The higher court upheld the ruling.'], 2),
            ('You want to talk about a citizen and her rights. You say:', ['A citizen whose her rights were violated.', 'A citizen whose rights were violated.', 'A citizen who her rights were violated.'], 1),
        ],
        'think': 'A first-year law student asks: &ldquo;Can international courts really judge a country?&rdquo; In ninety seconds, explain which courts judge states and which judge individuals, what jurisdiction has to do with it, and what happens when a state ignores a ruling. Use at least three relative clauses.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'United Nations &mdash; &ldquo;What is the International Court of Justice? The Role and Activities of the ICJ&rdquo; (YouTube)',
         'desc': 'The official United Nations video about the court in today&rsquo;s reading: who can use it, how the judges are chosen and what an advisory opinion is.',
         'tip': 'Tip: watch once and write down every relative clause you hear, like the court which or states that.',
         'url': 'https://www.youtube.com/watch?v=DME-wfbt08c', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'The Good Fight &mdash; Season 1, Episode 1, &ldquo;Inauguration&rdquo;',
         'desc': 'A Chicago law firm, courtrooms, rulings and appeals, in fast, natural American English. Not international law, but the vocabulary of today&rsquo;s lesson is in almost every scene.',
         'tip': 'Tip: when a judge speaks, pause and say the decision again in plain English.',
         'url': 'https://www.tvmaze.com/episodes/1008862/the-good-fight-1x01-inauguration', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Bryan Stevenson &mdash; &ldquo;We need to talk about an injustice&rdquo; (TED)',
         'desc': 'A lawyer who has spent his career in courtrooms on what justice means when the system fails the people it should protect. One of the most watched TED talks about law.',
         'tip': 'Tip: listen for how he uses stories to back up his argument, and summarize one story in three blocks.',
         'url': 'https://www.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice', 'cta': 'Watch on TED'},
    ],
}
