# -*- coding: utf-8 -*-
# Aula 10 -- The First Draft (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The First <span class='accent'>Draft</span>",
    'hero_line': 'The new TOEFL writing tasks, a plan for the next two years, and the future forms that describe it',
    'menu_desc': 'The TOEFL writing tasks, planning under a clock, and the future perfect and future continuous -- 35 slides',
    'grammar_point': 'future perfect and future continuous for plans and timelines',
    'phases': ['The Plan', 'Words of the Draft', 'The Text Itself', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'daniel', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1488190211105-8b0e65b80b4e?w=1400&q=80',
        'ch2': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch3': U + 'photo-1486312338219-ce68d2c6f44d?w=1400&q=80',
        'ch_grammar': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch5': U + 'photo-1454165804606-c3d57bc86b40?w=1400&q=80',
        'ch_rp': U + 'photo-1513635269975-59663e0ac1ad?w=1400&q=80',
        'pc': U + 'photo-1488190211105-8b0e65b80b4e?w=600&q=80',
    },
    'warmup': {
        'heading': "Ten Lessons <span class='accent'>Later</span>",
        'sub': 'Look back at the first ten lessons. What is easier now than in lesson one, and what is still hard? Answer without stopping.',
    },
    'target': {
        'heading': "Write It Like the <span class='accent'>Clock Is Real</span>",
        'steps': [
            'Plan for one minute: the point, two reasons, one example.',
            'Write the draft without stopping to make it perfect.',
            'Keep the last minute to proofread what you wrote.',
        ],
    },
    'diagnostic': {
        'heading': "This Time <span class='accent'>in Two Years</span>",
        'p1': 'Your exchange coordinator asks: &ldquo;Where do you think you will be, and what will you be doing, this time in two years?&rdquo;',
        'p2': 'Answer in sixty seconds. Say one thing you will be doing then, and two things you will have done before that.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Draft</span>",
            'sub': 'Thirteen words for planning, writing and checking a text under a clock'},
    'vocab': [
        {'word': 'An outline', 'def': 'A short plan that shows the main points of a text before you write it', 'ex': 'Make an outline before you write a single sentence.', 'icon': 'layers'},
        {'word': 'A draft', 'def': 'A first version of a text that you will improve later', 'ex': 'My first draft was too long, so I cut it in half.', 'icon': 'pen'},
        {'word': 'To proofread', 'def': 'To read a text carefully to find and correct small mistakes', 'ex': 'Always proofread your email before you send it.', 'icon': 'eye'},
        {'word': 'A thesis statement', 'def': 'The sentence that gives the main argument of an essay', 'ex': 'Her thesis statement was clear from the first line.', 'icon': 'target'},
        {'word': 'A topic sentence', 'def': 'The sentence that gives the main idea of one paragraph', 'ex': 'Every paragraph needs a topic sentence.', 'icon': 'doc'},
        {'word': 'Concise', 'def': 'Short and clear, with no words that are not needed', 'ex': 'A concise answer is better than a long one that wanders.', 'icon': 'filter'},
        {'word': 'Coherent', 'def': 'Logical and easy to follow, with ideas that connect well', 'ex': 'The ideas were good, but the paragraph was not coherent.', 'icon': 'link'},
        {'word': 'To elaborate', 'def': 'To give more details or explanation about an idea', 'ex': 'Could you elaborate on your second reason?', 'icon': 'message'},
        {'word': 'A word count', 'def': 'The number of words in a piece of writing', 'ex': 'There is no minimum word count, but a very short answer loses points.', 'icon': 'chart'},
        {'word': 'A milestone', 'def': 'An important stage or event in a process', 'ex': 'Taking the first practice test is a real milestone.', 'icon': 'flag'},
        {'word': 'A timeline', 'def': 'A plan that shows when each step of a process will happen', 'ex': 'We made a timeline for the next two years.', 'icon': 'calendar'},
        {'word': 'To be on track', 'def': 'To be making the right progress to reach a goal on time', 'ex': 'If you study every week, you will be on track for the exam.', 'icon': 'compass'},
        {'word': 'To revise', 'def': 'To change a piece of writing to improve it', 'ex': 'I revised the email three times before I sent it.', 'icon': 'refresh'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A thesis statement', 'Coherent', 'To elaborate', 'By the time I apply, I will have taken two official practice tests.'],
    'ch3': {'heading': "The Text About <span class='accent'>Your Writing Section</span>",
            'sub': 'Four short paragraphs. Read once for the argument; the detail comes after.'},
    'reading': {
        'heading': "The Essay Is Gone, <span class='accent'>the Clock Is Not</span>",
        'rtitle': 'The Essay Is Gone, the Clock Is Not',
        'paras': [
            'For years, students preparing for the TOEFL practiced one kind of writing above all: the long essay. Since January 2026, the writing section looks very different. It has three kinds of tasks, and none of them is a traditional essay. The change sounds like good news, but it has a trap: shorter tasks leave less time to fix a bad start.',
            'In the first task, you build sentences by putting words in the correct order, and every word has to be in the right place. In the second, you write an email for a practical situation, such as asking a professor for an extension, in about seven minutes. In the third, you join an academic discussion: you read what a professor and two students have posted, and you add your own opinion in about ten minutes.',
            'Students who do well in the email and discussion tasks rarely write faster than others. They plan better. They spend the first minute on a quick outline: the point they want to make, two reasons and one example. They write the draft without stopping to make each sentence perfect, and they keep the last minute to proofread. A concise, coherent answer with one clear example usually does better than a long one that tries to say everything.',
            'The same logic works for the exam date itself. A student who starts two years early does not need to study more hours. She needs a timeline with milestones, so that by the time she applies, she will have taken several practice tests and will already be writing under real time limits. The first draft of that plan is the most important piece of writing she will do.',
        ],
        'source': 'Written for this lesson, from the publicly described format of the TOEFL iBT writing section as of 2026.',
    },
    'gist': {
        'prompt': 'What is the main argument of the text?',
        'choices': [
            ['a', 'The new writing section is easier, so students need less preparation.', False],
            ['b', 'The new writing tasks are shorter, so planning and proofreading matter more than writing fast.', True],
            ['c', 'Students should keep practicing long essays, because the old format will return.', False],
        ],
    },
    'tf': [
        ['According to the text, the new writing section still includes a traditional essay.', 'f', 'The text says none of the three tasks is a traditional essay.'],
        ['In the email task, you write for a practical situation in about seven minutes.', 't', 'The text gives the example of asking a professor for an extension, in about seven minutes.'],
        ['In the academic discussion, you respond to posts from a professor and two students.', 't', 'The text says you read what a professor and two students have posted and add your opinion.'],
        ['The text says successful students usually write faster than others.', 'f', 'The text says they rarely write faster; they plan better.'],
        ['The author believes a long answer that says everything usually does better.', 'f', 'The text says a concise, coherent answer with one example usually does better.'],
    ],
    'artifact': {
        'heading': "The Plan on <span class='accent'>One Page</span>",
        'title': 'TWO-YEAR TOEFL TIMELINE', 'subtitle': 'Draft 1 &middot; Candidate: L. Sato Eccheli',
        'rows': [
            ('Month 3', 'First official practice test &mdash; full, timed', True),
            ('Month 8', 'Writing tasks under real time limits, every week', False),
            ('Month 14', 'Second practice test; compare every section', True),
            ('Month 20', 'Official TOEFL iBT, with time to retake if needed', False),
            ('Month 24', 'Exchange application deadline', False),
        ],
        'note': 'Advisor note: plan the official test for month 20, not month 23. By then you will have had time to retake it if the score is below the requirement, and the result will still be valid on the deadline.',
        'qs': [
            ('What milestone happens in month 3, and which one in month 14?', 'The first official practice test in month 3, and the second practice test in month 14.'),
            ('When will she be writing under real time limits every week?', 'From month 8.'),
            ('According to the advisor, why is the official test in month 20 and not month 23?', 'Because she will have had time to retake it if the score is too low, and the result will still be valid on the deadline.'),
        ],
    },
    'ch_grammar': {'heading': "Two Years <span class='accent'>From Now</span>",
                   'sub': 'Four sentences about the future: one finished before a moment, one in progress at that moment'},
    'grammar': {
        'heading': "Finished by Then, or <span class='accent'>Happening Then?</span>",
        'examples': [
            "By the time I apply, I <span style='color:#b91c1c;font-weight:700'>will have taken</span> two practice tests.",
            "This time in two years, I <span style='color:#1d4ed8;font-weight:700'>will be studying</span> in London.",
            "By December, she <span style='color:#b91c1c;font-weight:700'>will have finished</span> her third semester.",
            "Do not call me at ten on Friday; I <span style='color:#1d4ed8;font-weight:700'>will be taking</span> the test.",
        ],
        'prompt': 'All four sentences are about the future. Which ones describe something that will already be finished before a moment, and which ones describe something that will be in progress at that moment? Look at the red and blue forms.',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Finished before a future moment', 'will have + past participle', 'By then I <strong>will have taken</strong> two tests.'),
            ('In progress at a future moment', 'will be + -ing', 'This time next year I <strong>will be studying</strong> abroad.'),
            ('The future moment', 'by + time / by the time + present simple', '<strong>By the time I apply</strong> &middot; <strong>by December</strong>'),
            ('A plan that is already arranged', 'will be + -ing (neutral, polite)', '<strong>Will you be using</strong> the room this afternoon?'),
            ('Negative', 'will not have + participle / will not be + -ing', 'I <strong>will not have finished</strong> by Friday.'),
            ('After by the time', 'present simple, never will', 'By the time I <strong>apply</strong>, not <em>will apply</em>.'),
            ('The trap', 'never <em>will have took</em>; never <em>by the time I will</em>', 'Not <em>I will have took</em>. Say <strong>I will have taken</strong>.'),
        ],
        'oneliner': 'Will have + participle for what is done before the moment, will be + -ing for what is happening at the moment, and present simple after by the time.',
    },
    'grammar_practice': {
        'heading': "Done Before, or <span class='accent'>Happening Then?</span>",
        'items': [
            ('By the time I apply, I ', 'will have taken', ' two practice tests. (finished before)'),
            ('This time in two years, I ', 'will be studying', ' in London. (in progress then)'),
            ('By the time she ', 'applies', ', her score will still be valid. (present simple after by the time)'),
            ('By December, we ', 'will have finished', ' the first block of lessons. (finished before)'),
            ('At ten on Friday, I ', 'will be writing', ' the academic discussion task. (in progress then)'),
            ('I ', 'will not have finished', ' the outline by tonight. (negative, finished before)'),
        ],
    },
    'detective': [
        ('By the time I will apply, I will have taken two tests.', 'By the time I <strong>apply</strong>, I will have taken two tests.'),
        ('By December, I will have took my first practice test.', 'By December, I will have <strong>taken</strong> my first practice test.'),
        ('This time next year I will study in London right now.', 'This time next year I <strong>will be studying</strong> in London.'),
        ('Do not call at ten; I will have taken the test then.', 'Do not call at ten; I <strong>will be taking</strong> the test then.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>",
            'sub': 'Advice and plain English &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Advice in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each piece of writing advice to what it means in practice',
        'hint': 'Tap a piece of advice, then tap what you actually do',
        'pairs': [
            ('Spend the first minute on an outline.', 'Decide your point, two reasons and an example before you write.'),
            ('Keep your answer concise.', 'Remove every sentence that does not help your main point.'),
            ('Make your paragraph coherent.', 'Connect the ideas so the reader can follow them easily.'),
            ('Elaborate on one reason.', 'Give more detail or an example for that reason.'),
            ('Leave time to proofread.', 'Use the last minute to find and fix small mistakes.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Advisor&rsquo;s Email</span>",
    'gap': {
        'parts': [
            'Dear Luiza, thank you for sending the first ', ['1', 'draft'], ' of your plan. The ', ['2', 'timeline'],
            ' looks realistic, and the first practice test is a good ', ['3', 'milestone'], '. For the writing tasks, always start with a quick ',
            ['4', 'outline'], ', keep your answers ', ['5', 'concise'], ', and leave one minute to ',
            ['6', 'proofread'], '. If you follow this plan every week, you will ', ['7', 'be on track'],
            ' for the exam. Please ', ['8', 'revise'], ' the dates for month 20 and send it back. Best, Daniel.',
        ],
        'bank': ['draft', 'timeline', 'milestone', 'outline', 'concise', 'proofread', 'be on track', 'revise'],
    },
    'quickfire': [
        {'situation': 'Your coordinator asks what you will be doing this time next year. Answer in two sentences.', 'tips': ['This time next year I will be studying for the TOEFL every week, and I will be writing under real time limits.', 'will be + -ing for an action in progress.']},
        {'situation': 'Say two things you will have done by the time you apply.', 'tips': ['By the time I apply, I will have taken two practice tests and I will have finished my fourth semester.', 'Present simple after by the time; will have + participle.']},
        {'situation': 'Explain the three writing tasks in one sentence each.', 'tips': ['First, you put words in order to build sentences. Then you write a practical email, and finally you add your opinion to an academic discussion.', 'Sequence words, and no essay.']},
        {'situation': 'A friend writes a very long answer with no plan. Give advice in two sentences.', 'tips': ['Spend the first minute on an outline. A concise, coherent answer with one example is better than a long one.', 'outline, concise, coherent.']},
        {'situation': 'Ask a classmate politely if they are using the study room this afternoon.', 'tips': ['Will you be using the study room this afternoon?', 'will be + -ing for a polite question about plans.']},
        {'situation': 'Say that you will not have finished the outline by tonight, and when you will.', 'tips': ['I will not have finished the outline by tonight, but I will have done it by tomorrow morning.', 'will not have + participle.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Writing Coach', 'title': "Ten Minutes, <span class='accent'>Three Parts</span>",
         'blurb': 'A coach on the academic discussion task. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'In the academic discussion task you have about ten minutes, and I want you to divide them into three parts before you even read the question. The first minute is for the outline. Read the professor&rsquo;s question and the two student posts, decide your position, and write down two reasons and one example, in single words, not sentences. The next eight minutes are for the draft. Do not repeat what the other students said; respond to one of them, and then add something new. And the last minute is sacred: you proofread. Look for the mistakes you always make, not every possible mistake. Most students skip the outline because it feels like wasted time. It is the opposite. The outline is what keeps your answer coherent when the clock starts to feel loud.',
         'qs': [
             ('How does the coach divide the ten minutes?', 'One minute for the outline, eight minutes for the draft, and the last minute to proofread.'),
             ('What should students do with the other students&rsquo; posts?', 'Not repeat them: respond to one of them, and then add something new.'),
             ('Why does she say the outline is not wasted time?', 'Because it keeps your answer coherent when the clock starts to feel loud.'),
         ]},
        {'label': 'Listening 2 &middot; An Advisor', 'title': "Where You Will Be <span class='accent'>in Two Years</span>",
         'blurb': 'An exchange advisor on planning backwards from the deadline. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'I always ask students to plan backwards. Start with the deadline and ask where you will be one week before it. By then, you will have sent your documents, and you will be waiting for an answer. Two months before that, you will have received your official score. And for that to happen, you will be taking the test about four months before the deadline, so that there is still time to retake it. Now go back further. A year before the deadline, you will be writing under real time limits every week, and by that point you will have taken at least one full practice test. When you see it like this, two years is not a long time. It is a timeline with five or six milestones, and the most important one is the first practice test, because it tells you how far you really are from the requirement.',
         'qs': [
             ('What does the advisor mean by planning backwards?', 'Starting with the deadline and asking where you will be at each point before it.'),
             ('About how long before the deadline will the student be taking the official test, and why?', 'About four months before, so that there is still time to retake it.'),
             ('Which milestone does he say is the most important, and why?', 'The first practice test, because it tells you how far you really are from the requirement.'),
         ]},
    ],
    'roleplays': {
        'heading': "The Same Plan, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Present Your <span class='accent'>Timeline</span>",
             'scenario': 'Present your two-year timeline to your advisor: what you will have done by month 14, what you will be doing in month 20, and one milestone you are worried about.',
             'chips': ['By the time I apply', 'I will have taken', 'I will be writing', 'a milestone']},
            {'heading': "The Academic <span class='accent'>Discussion</span>",
             'scenario': 'The professor asks: &ldquo;Should universities require all exchange students to take a writing course before they leave?&rdquo; Plan your answer out loud in one minute, then give it: your position, two reasons, one example, and a response to a classmate who disagrees.',
             'chips': ['an outline', 'concise', 'to elaborate', 'Although']},
            {'heading': "Ten Lessons, <span class='accent'>Two Minutes</span>",
             'scenario': 'Look back at the first ten lessons and forward to the next two years. Say what you have learned, what you will have done by the time you take the TOEFL, and what you will be doing on your first day of the exchange.',
             'footer': 'No notes, two minutes. Use the present perfect, the future perfect and the future continuous at least once each.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>the Next Two Years</span>",
    'survival': [
        'By the time I apply, I will have taken two practice tests.',
        'This time in two years, I will be studying abroad.',
        'I always spend the first minute on a quick outline.',
        'A concise, coherent answer is better than a long one that wanders.',
        'If I study every week, I will be on track for the exam.',
    ],
    'checklist': [
        'I know the three kinds of tasks in the new TOEFL writing section.',
        'I plan, write and proofread, even when the clock is short.',
        'I use will have + participle for something finished before a future moment.',
        'I use will be + -ing for something in progress at a future moment, and the present simple after by the time.',
        'I know the words: an outline, a draft, to proofread, a thesis statement, a topic sentence, concise, coherent, to elaborate, a word count, a milestone, a timeline, to be on track, to revise.',
    ],
    'badge': {'name': 'The First Draft', 'line': 'Ten lessons done, a plan on one page, and two years that are now a timeline.',
              'next': 'Next block: longer texts, faster answers, and the writing tasks under a real clock'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, this is lesson ten. Today we look back, and we write the first draft of the next two years.\' Esta aula fecha o bloco 1. FATO: desde janeiro de 2026 o writing do TOEFL tem Build a Sentence, Write an Email (cerca de 7 min) e Write for an Academic Discussion (cerca de 10 min); nao ha mais redacao longa. Texto curto, e o foco e planejamento.',
        'warmup': '<strong>Warm-up + callback do bloco (5 min):</strong> Faca a pergunta das dez aulas. Exija pelo menos TRES estruturas do bloco na resposta: present perfect (aula 1), reported speech (aula 3), condicional (aula 5), modal de deducao (aula 6) ou concessao (aula 9). ANOTE quais ela usa sozinha: e o diagnostico do fim do bloco. Compare o numero de recomecos com o diagnostico da aula 1 e DIGA o numero a ela.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Ligue a aula 9: a mesma estrutura de opiniao serve para a academic discussion escrita. Nao de a regra dos futuros ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Sessenta segundos. ANOTE se ela usa \'will be studying\' e \'will have done\' ou so \'will\'. Aceite tudo sem corrigir.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words for planning, writing and checking a text.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'an outline x a draft\': \'Which one comes first? (Outline.)\' CCQ \'to proofread\': \'Is it writing new ideas or checking mistakes? (Checar.)\' CCQ \'a thesis statement x a topic sentence\': \'The whole text or one paragraph? (Texto inteiro x um paragrafo.)\' Pronuncia: PROOF-read, THE-sis.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'concise\': \'Long or short and clear? (Curto e claro.)\' CCQ \'coherent\': \'Can the reader follow the ideas? (Sim.)\' CCQ \'to elaborate\': \'More detail or less? (Mais.)\' Pronuncia: co-HER-ent, e-LAB-o-rate (verbo, final /eit/).',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'a milestone\': \'Every small step or an important stage? (Etapa importante.)\' CCQ \'to be on track\': \'Late, or making the right progress? (No caminho certo.)\' CCQ \'to revise\': em ingles americano e reescrever para melhorar, nao so revisar para prova.',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> THE-sis STATE-ment, co-HER-ent, e-LAB-o-rate. Na frase longa, dois blocos: \'By the time I apply / I will have taken two official practice tests.\' Cobre a contracao natural I\'ll have.',
        'matching': '<strong>Matching (3 min):</strong> Ela liga palavra e definicao. Se errar, volte ao CCQ.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'Four paragraphs about your writing section. Skim first: two minutes.\'',
        'reading': '<strong>Leitura (5 min):</strong> Dois minutos de skim cronometrado, ideia central, depois segunda leitura. Compare o tempo com as aulas 2, 4, 6 e 8 e diga a evolucao a ela: e o fim do bloco.',
        'gist': '<strong>Gist (3 min):</strong> Ela escolhe e elimina as outras duas em voz alta.',
        'tf': '<strong>True or False (6 min):</strong> Ela diz TRUE ou FALSE e LE a linha que prova antes de clicar.',
        'artifact': '<strong>Artefato (4 min):</strong> Cronograma ficticio de dois anos, com o nome dela. Peca que ela leia cada linha com future perfect ou continuous: \'By month 14, I will have taken my second practice test.\' So depois as 3 perguntas. As datas sao ficticias; se ela tiver a data real do intercambio, adapte a conversa.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about the future. Some things will be finished, some will be happening.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Finished before a moment, or in progress at that moment?\' Espere ela ver. So entao Reveal the Rule. CCQ: \'By the time I apply, I will have taken two tests &mdash; when do I take the tests, before or after I apply? (Antes.)\' CCQ: \'This time in two years I will be studying in London &mdash; is the studying finished? (Nao, em andamento.)\' Obstaculos do brasileiro: \'by the time I will apply\' (will depois de by the time) e \'will have took\' (participio errado).',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela diz a frase INTEIRA antes de clicar. Na terceira, cobre o presente depois de by the time.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Quatro erros: will depois de by the time, will have took, futuro simples com this time next year, future perfect no lugar de continuous. Enquadramento: \'os mais comuns\'.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: the advice in practice, an email, quick questions, and two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ela liga o conselho a pratica e EXPLICA. Se fechar rapido, peca que ela aplique um dos conselhos a resposta do diagnostico.',
        'gap': '<strong>Gap-fill (4 min):</strong> Ela arrasta, toca ou digita e confere com Check. E um e-mail: repare com ela no registro formal (Dear, Best) &mdash; e o formato da tarefa Write an Email.',
        'quickfire': '<strong>Quick fire (5 min):</strong> Uma pergunta por vez. Ela responde ANTES da dica. Regra: um futuro perfeito ou continuo por resposta. Corrija so o futuro, no fim.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Depois peca que ela faca um outline de UM minuto para a pergunta do role-play 2, em palavras soltas.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Orientador falando de planejamento de tras para frente, cheio de will have e will be. Depois pergunte qual marco ela ainda nao colocou no plano dela.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same plan, three times. The last one closes the first ten lessons.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e o orientador. Ela apresenta o cronograma com future perfect e continuous. Corrija so by the time e o participio, no fim.',
        'rp2': '<strong>Role-play semi-livre (6 min):</strong> Um minuto de outline em voz alta, cronometrado, depois a resposta. Voce faz o colega que discorda. Ela usa concessao da aula 9. E a academic discussion falada, antes de ser escrita.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota: o que aprendeu, o que tera feito ate o TOEFL, o que estara fazendo no primeiro dia do intercambio. Cronometre. No fim, dois numeros: quantas vezes recomecou (compare com a aula 1 e diga a diferenca) e quantas estruturas do bloco usou. Registre os numeros no controle de aulas: sao o fechamento do bloco 1.',
        'survival': '<strong>Survival card (3 min):</strong> Leia e toque cada frase. Ela repete em blocos.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 marcados = aula concluida e stamp 10, fechando o bloco 1. Itens em que ela hesitar entram no warm-up da aula 11.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, ten lessons ago you told me your story. Today you wrote the plan for the next two years.\' Homework (ORALMENTE, nunca escrito na tela): escrever em ingles o primeiro rascunho do cronograma real dela ate o TOEFL, com cinco marcos, e um e-mail curto para o orientador pedindo feedback (formato Write an Email), com um minuto de outline e um de revisao. Proxima aula: comeca o bloco 2.',
    },
    'pc': {
        'title': 'The First Draft -- Plans, Timelines and the Future',
        'desc': 'The new TOEFL writing tasks reward planning. Write the first draft of your next two years, with the future forms that describe it.',
        'match_idx': [0, 2, 5, 6, 9, 11],
        'context': [
            'Planning the next two years is a writing task in itself, and it needs two future forms that Portuguese speakers often mix up. Both use <strong>will</strong>, but they describe the future from different angles: what will already be finished, and what will be happening.',
            'When something will be complete before a moment in the future, use <strong>will have</strong> + past participle: &ldquo;By the time I apply, I <strong>will have taken</strong> two practice tests.&rdquo; The key phrase is <strong>by</strong>: by December, by month 14, by the time I apply. After <strong>by the time</strong>, English uses the present simple, never <em>will</em>.',
            'When something will be in progress at a moment in the future, use <strong>will be</strong> + <em>-ing</em>: &ldquo;This time in two years, I <strong>will be studying</strong> in London.&rdquo; The same form also makes polite questions about plans: &ldquo;<strong>Will you be using</strong> the study room this afternoon?&rdquo;',
            'A good <strong>timeline</strong> uses both. Each <strong>milestone</strong> is something you <strong>will have done</strong> by a date, and each stage between them is something you <strong>will be doing</strong>. Write the first <strong>draft</strong>, keep it <strong>concise</strong>, and <strong>revise</strong> it every few months. If you do, you <strong>will be on track</strong> long before the deadline arrives.',
        ],
        'context_quiz': [
            ('According to the text, what does will have + past participle describe?', ['Something happening right now.', 'Something complete before a moment in the future.', 'A habit in the past.'], 1),
            ('What comes after by the time?', ['The present simple.', 'will + base verb.', 'will have + participle.'], 0),
            ('Which sentence describes something in progress at a future moment?', ['By December, I will have finished.', 'I have finished my outline.', 'This time in two years, I will be studying in London.'], 2),
        ],
        'tip_title': 'Future Perfect and Future Continuous',
        'tip_lead': 'Will have + participle for what is done before the moment; will be + -ing for what is happening at the moment.',
        'tip_rows': [
            ('Finished before a moment', 'will have + participle', 'I <strong>will have taken</strong> two tests.'),
            ('In progress at a moment', 'will be + -ing', 'I <strong>will be studying</strong> abroad.'),
            ('The moment', 'by + time / by the time + present', '<strong>By the time I apply</strong>'),
            ('Polite question about plans', 'Will you be + -ing?', '<strong>Will you be using</strong> the room?'),
            ('Negative', 'will not have + participle', 'I <strong>will not have finished</strong> by then.'),
            ('Time phrase', 'this time next year / in two years', '<strong>This time next year</strong> I will be writing.'),
        ],
        'tip_never': 'by the time I will apply &middot; I will have took the test &middot; this time next year I will study right now &middot; I will be taken the test',
        'blanks': [
            ('By the time I apply, I ', 'will have taken', ' two practice tests.', 'Hint: finished before a future moment -- three words', None),
            ('This time in two years, I ', 'will be studying', ' in London.', 'Hint: in progress at a future moment -- three words', None),
            ('By the time she ', 'applies', ', her score will still be valid.', 'Hint: present simple after by the time -- one word', None),
            ('Spend the first minute on a quick ', 'outline', ' of your answer.', 'Hint: a short plan of the main points -- one word', None),
            ('Use the last minute to ', 'proofread', ' what you wrote.', 'Hint: read carefully to fix small mistakes -- one word', None),
            ('If you study every week, you will ', 'be on track', ' for the exam.', 'Hint: making the right progress on time -- three words', None),
        ],
        'order_title': 'Put the Writing Process in Order',
        'order_lead': 'You have about ten minutes for the academic discussion task. Put your steps in a logical order.',
        'order': [
            'Read the professor&rsquo;s question and the two student posts.',
            'Spend one minute on an outline: your position, two reasons and an example.',
            'Start your draft by responding to one of the students.',
            'Add something new, and elaborate on one reason.',
            'Finish with a clear sentence that returns to your position.',
            'Use the last minute to proofread for your usual mistakes.',
        ],
        'quiz': [
            ('Your advisor asks about your plans. You say:', ['By the time I will apply, I will take two tests.', 'By the time I apply, I will have taken two tests.', 'By the time I apply, I have taken two tests.'], 1),
            ('You want to describe what you will be doing this time next year. You say:', ['This time next year, I will be studying for the TOEFL.', 'This time next year, I will have study for the TOEFL.', 'This time next year, I am studying right now.'], 0),
            ('A classmate writes a long answer with no plan. You advise:', ['Write faster and skip the outline.', 'Make the answer longer to show more vocabulary.', 'Spend the first minute on an outline and keep it concise.'], 2),
            ('You want to ask politely about a classmate&rsquo;s plans. You say:', ['Will you be using the study room this afternoon?', 'Will you have used the study room this afternoon?', 'Are you use the study room this afternoon?'], 0),
        ],
        'think': 'Write the first draft of your plan out loud. In ninety seconds, say where you will be this time in two years and what you will be doing, three milestones you will have reached by the time you apply, and one thing you will do every week to stay on track.',
    },
    'media': [
        {'id': 'video', 'type': 'Video', 'title': 'Magoosh TOEFL &mdash; &ldquo;How to Write a Perfect TOEFL Email in 7 Minutes (2026)&rdquo; (YouTube)',
         'desc': 'A step-by-step guide to the new Write an Email task: how to plan in one minute, organize the email, and keep time to check it.',
         'tip': 'Tip: pause before the sample answer and make your own one-minute outline for the same prompt.',
         'url': 'https://www.youtube.com/watch?v=uhBrQOJLOvk', 'cta': 'Watch on YouTube'},
        {'id': 'series', 'type': 'Series', 'title': 'Ted Lasso &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'An American coach moves to London with no plan and a lot of optimism. Funny, warm, and a good preview of American and British English side by side, in the city you may study in.',
         'tip': 'Tip: after the episode, say what Ted will have learned by the end of the season, and what he will be doing in his first month.',
         'url': 'https://www.tvmaze.com/episodes/1874762/ted-lasso-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Tim Urban &mdash; &ldquo;Inside the mind of a master procrastinator&rdquo; (TED)',
         'desc': 'A very funny talk about deadlines, and about the goals that have no deadline at all. Perfect for a plan that lasts two years.',
         'tip': 'Tip: summarize his idea of the Panic Monster in three blocks, and say how a timeline with milestones solves it.',
         'url': 'https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator', 'cta': 'Watch on TED'},
    ],
}
