# -*- coding: utf-8 -*-
# Aula 2 -- The Treaty Is Not the Problem (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The Treaty Is Not <span class='accent'>the Problem</span>",
    'hero_line': 'Why a signature is not a promise, and the passive voice that every treaty is written in',
    'menu_desc': 'How a treaty becomes binding, and the passive voice of legal English -- 35 slides',
    'grammar_point': 'the passive voice in legal and institutional texts',
    'phases': ['The Reading List', 'Words of the Treaty', 'The Text Itself', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'daniel', 'guest_voice': 'arthur',
    'imgs': {
        'hero': U + 'photo-1505664194779-8beaceb93744?w=1400&q=80',
        'ch2': U + 'photo-1532012197267-da84d127e765?w=1400&q=80',
        'ch3': U + 'photo-1497633762265-9d179a990aa6?w=1400&q=80',
        'ch_grammar': U + 'photo-1434030216411-0b793f4b4173?w=1400&q=80',
        'ch5': U + 'photo-1498243691581-b145c3f54a5a?w=1400&q=80',
        'ch_rp': U + 'photo-1517048676732-d65bc937f952?w=1400&q=80',
        'pc': U + 'photo-1505664194779-8beaceb93744?w=600&q=80',
    },
    'warmup': {
        'heading': "The Longest Reading on <span class='accent'>Your List</span>",
        'sub': 'Which text for Global Law took you the longest this semester, and what made it slow: the words, the sentences, or the topic?',
    },
    'target': {
        'heading': "Read It Like a <span class='accent'>Lawyer</span>",
        'steps': [
            'Find who acts. Legal English often hides the person who does the action.',
            'Find the moment. Signed, ratified and in force are three different moments.',
            'Say it back in plain English, in one sentence, without the dictionary.',
        ],
    },
    'diagnostic': {
        'heading': "Signed or <span class='accent'>Ratified?</span>",
        'p1': 'A classmate says: &ldquo;Brazil signed the treaty last week, so now it has to follow every rule in it.&rdquo;',
        'p2': 'Do you agree? Explain in three sentences, and say what you think is missing from your classmate&rsquo;s reasoning.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Treaty</span>",
            'sub': 'Thirteen words you meet in every Global Law reading, before the first footnote'},
    'vocab': [
        {'word': 'A treaty', 'def': 'A formal written agreement between two or more states', 'ex': 'The treaty was negotiated for six years before anyone signed it.', 'icon': 'doc'},
        {'word': 'A signatory', 'def': 'A state or a person that has signed an agreement', 'ex': 'Every signatory received a copy of the final text.', 'icon': 'pen'},
        {'word': 'To ratify', 'def': 'To make an agreement officially valid, usually after a national parliament approves it', 'ex': 'The treaty must be ratified by the national congress.', 'icon': 'shield'},
        {'word': 'Binding', 'def': 'Describes an obligation that must be followed by law', 'ex': 'A signature alone does not make the treaty binding.', 'icon': 'lock'},
        {'word': 'A provision', 'def': 'One specific rule or condition inside a legal document', 'ex': 'Article 12 contains the provision on the protection of refugees.', 'icon': 'layers'},
        {'word': 'To enter into force', 'def': 'To start having legal effect from a certain date', 'ex': 'The agreement entered into force thirty days after the last ratification.', 'icon': 'calendar'},
        {'word': 'A party', 'def': 'A state or organization that has formally accepted an agreement and is bound by it', 'ex': 'Only a party to the treaty can bring a complaint under it.', 'icon': 'users'},
        {'word': 'A reservation', 'def': 'A formal statement that a state will not be bound by a particular part of a treaty', 'ex': 'Some states ratified the convention with a reservation on article 9.', 'icon': 'filter'},
        {'word': 'To comply with', 'def': 'To act according to a rule, a law or an order', 'ex': 'States are expected to comply with the treaties they have ratified.', 'icon': 'scale'},
        {'word': 'A breach', 'def': 'An action that breaks a law, a rule or an agreement', 'ex': 'Closing the border was a breach of the agreement.', 'icon': 'alert'},
        {'word': 'To enforce', 'def': 'To make people or states obey a law or a rule', 'ex': 'There is no international police force to enforce the decision.', 'icon': 'hand'},
        {'word': 'Sovereignty', 'def': 'The power of a state to govern itself without control from outside', 'ex': 'Some politicians say the court is a threat to national sovereignty.', 'icon': 'flag'},
        {'word': 'To withdraw from', 'def': 'To officially stop being part of an agreement or an organization', 'ex': 'A state can withdraw from the treaty, but only after giving notice.', 'icon': 'refresh'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A signatory', 'To ratify', 'Sovereignty', 'The treaty was signed in March, but it has not been ratified yet.'],
    'ch3': {'heading': "The Text on <span class='accent'>Your Reading List</span>",
            'sub': 'Four short paragraphs. Read once for the argument; the detail comes after.'},
    'reading': {
        'heading': "A Signature Is Not <span class='accent'>a Promise</span>",
        'rtitle': 'A Signature Is Not a Promise',
        'paras': [
            'Every year, photographs of heads of state signing a treaty are published around the world, and every year the same mistake is made in the headlines. A signature is treated as the end of the story. In most cases it is only the beginning. When a treaty is signed, a state shows that it agrees with the text, but it is not yet bound by it.',
            'The obligation starts later. In most countries, a treaty has to be approved by the national parliament and then ratified by the government. Only after ratification does a state become a party, and only then is it legally required to comply with every provision it has accepted. Many treaties also say that they will enter into force only when a minimum number of states have ratified them, so a text can be signed by dozens of countries and still have no legal effect for years.',
            'Even then, a state is allowed some room. A reservation can be made at the moment of ratification, stating that one particular article will not be applied. Reservations are not unlimited: one that goes against the object and purpose of the treaty is not accepted. And a state that no longer wants to be bound can withdraw, usually after formal notice has been given.',
            'This is why students of Global Law are often told that the treaty is not the problem. The text is usually clear. The difficult question is what happens after a breach, because in international law there is no police force, and sovereignty is protected by the same system that is supposed to enforce the rules. Most treaties are respected, but they are respected because states choose to, not because anyone can force them.',
        ],
        'source': 'Written for this lesson, from the general rules of treaty law (1969 Vienna Convention on the Law of Treaties).',
    },
    'gist': {
        'prompt': 'What is the main argument of the text?',
        'choices': [
            ['a', 'Most treaties are badly written, and that is why states break them.', False],
            ['b', 'Signing a treaty is only the first step, and the real difficulty is what happens when a state breaks it.', True],
            ['c', 'International courts can easily force states to respect the treaties they sign.', False],
        ],
    },
    'tf': [
        ['According to the text, a state is bound by a treaty from the moment it signs it.', 'f', 'The text says that when a treaty is signed, a state agrees with the text but is not yet bound by it.'],
        ['A treaty can be signed by many countries and still have no legal effect.', 't', 'The text says a treaty may enter into force only after a minimum number of ratifications, so it can have no effect for years.'],
        ['A state can make any reservation it wants when it ratifies a treaty.', 'f', 'The text says a reservation that goes against the object and purpose of the treaty is not accepted.'],
        ['A state that wants to leave a treaty usually has to give formal notice first.', 't', 'The text says a state can withdraw, usually after formal notice has been given.'],
        ['The author believes most treaties are respected because of international police.', 'f', 'The text says there is no police force, and that treaties are respected because states choose to.'],
    ],
    'artifact': {
        'heading': "The Handout from <span class='accent'>Week Three</span>",
        'title': 'TREATY SUMMARY CARD', 'subtitle': 'Global Law &middot; Week 3 &middot; Prepared for: L. Sato Eccheli',
        'rows': [
            ('Adopted', 'The final text is agreed by the negotiating states', False),
            ('Signed', 'A state shows it agrees &mdash; not yet bound', True),
            ('Ratified', 'Approved by parliament and confirmed by the government', False),
            ('Entry into force', 'After the minimum number of ratifications is reached', True),
            ('Withdrawal', 'Possible after formal notice, according to the treaty&rsquo;s own rules', False),
        ],
        'note': 'Seminar note: for Friday, bring one treaty that has been signed by Brazil but not ratified, and one that has been ratified with a reservation. Do not bring a definition; bring an example.',
        'qs': [
            ('At which stage is a state only showing that it agrees, without being bound?', 'When the treaty is signed.'),
            ('What has to happen before a treaty enters into force?', 'The minimum number of ratifications has to be reached.'),
            ('According to the seminar note, what must the students bring, and what must they not bring?', 'One treaty signed by Brazil but not ratified, and one ratified with a reservation. They must not bring a definition.'),
        ],
    },
    'ch_grammar': {'heading': "The Sentence That Hides <span class='accent'>Who Acts</span>",
                   'sub': 'Four lines from the text, and the person who is never mentioned'},
    'grammar': {
        'heading': "Who Signed, Who <span class='accent'>Ratified?</span>",
        'examples': [
            "The treaty <span style='color:#b91c1c;font-weight:700'>was signed</span> in March.",
            "A reservation <span style='color:#b91c1c;font-weight:700'>can be made</span> at the moment of ratification.",
            "The text <span style='color:#1d4ed8;font-weight:700'>has been ratified</span> by forty states.",
            "Students <span style='color:#1d4ed8;font-weight:700'>are often told</span> that the treaty is not the problem.",
        ],
        'prompt': 'In each sentence, who did the action? Is that person mentioned? Why would a legal text choose to hide the person, or to mention it only with <em>by</em>?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('The action matters more than who did it', 'be + past participle', 'The treaty <strong>was signed</strong> in March.'),
            ('Say who did it, when it matters', 'passive + by + agent', 'It <strong>was ratified by the congress</strong>.'),
            ('A result that is still true', 'has / have been + past participle', 'It <strong>has been ratified</strong> by forty states.'),
            ('Possibility or obligation', 'modal + be + past participle', 'A reservation <strong>can be made</strong>. The text <strong>must be approved</strong>.'),
            ('Something in progress', 'is / are being + past participle', 'The case <strong>is being heard</strong> this week.'),
            ('A general belief', 'it is said / believed that + clause', '<strong>It is often said that</strong> treaties are weak.'),
            ('The trap', 'never <em>was ratify</em>; never <em>was ratified from</em>', 'Not <em>ratified from the congress</em>. Say <strong>ratified by the congress</strong>.'),
        ],
        'oneliner': 'Legal English puts the action first: be + past participle, and by only when the actor matters.',
    },
    'grammar_practice': {
        'heading': "Put the Action <span class='accent'>First</span>",
        'items': [
            ('The treaty ', 'was signed', ' in Geneva in 2019. (a finished moment, the signers are not important)'),
            ('The convention ', 'has been ratified', ' by more than one hundred states. (a result still true)'),
            ('A reservation ', 'cannot be made', ' against the purpose of the treaty. (impossibility)'),
            ('The agreement must ', 'be approved', ' by the national congress first. (obligation)'),
            ('The complaint ', 'is being analyzed', ' by the committee this month. (in progress)'),
            ('', 'It is often said that', ' international law has no teeth. (a general belief)'),
        ],
    },
    'detective': [
        ('The treaty was ratify by the congress.', 'The treaty was <strong>ratified</strong> by the congress.'),
        ('The agreement was signed from forty states.', 'The agreement was signed <strong>by</strong> forty states.'),
        ('A reservation can make at the moment of ratification.', 'A reservation can <strong>be made</strong> at the moment of ratification.'),
        ('The new rules are applied since 2020.', 'The new rules <strong>have been applied</strong> since 2020.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>",
            'sub': 'Legal English and plain English &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Treaty in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each line of the treaty to the same idea in plain English',
        'hint': 'Tap a line from the treaty, then tap the sentence that means the same',
        'pairs': [
            ('This Convention shall enter into force on the thirtieth day after the deposit of the twentieth instrument of ratification.', 'The rules start to apply one month after the twentieth country ratifies.'),
            ('No reservation may be made to Article 1.', 'Countries cannot refuse to follow the first article.'),
            ('Each State Party shall take the necessary measures to comply with this Convention.', 'Every country that accepted the treaty has to act to follow it.'),
            ('A State Party may withdraw by written notification to the Secretary-General.', 'A country can leave if it sends a formal letter.'),
            ('The provisions of this Convention are without prejudice to national sovereignty.', 'Nothing in these rules takes away a country&rsquo;s power to govern itself.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Seminar Summary</span>",
    'gap': {
        'parts': [
            'A ', ['1', 'treaty'], ' is not binding on a state just because its president has signed it. Being a ',
            ['2', 'signatory'], ' only shows agreement with the text. The obligation begins when the parliament approves it and the government decides to ',
            ['3', 'ratify'], ' it. From that moment, the state becomes a ', ['4', 'party'],
            ' and has to ', ['5', 'comply with'], ' every ', ['6', 'provision'],
            ' it accepted, unless it made a ', ['7', 'reservation'],
            '. If it does not, the other states can say there has been a ', ['8', 'breach'], '.',
        ],
        'bank': ['treaty', 'signatory', 'ratify', 'party', 'comply with', 'provision', 'reservation', 'breach'],
    },
    'quickfire': [
        {'situation': 'A classmate says that a signed treaty is already binding. Correct them in two sentences.', 'tips': ['Not yet. A treaty is only binding after it has been ratified, and signing only shows agreement with the text.', 'Use the passive: has been ratified, is signed.']},
        {'situation': 'Explain what a reservation is, without using the word reservation.', 'tips': ['It is a statement, made when a country ratifies, saying that one article will not be applied to it.', 'Relative clause plus passive: will not be applied.']},
        {'situation': 'Say that the treaty was approved by the congress last year, and that it entered into force in May.', 'tips': ['The treaty was approved by the congress last year, and it entered into force in May.', 'Passive for approved; active for entered into force.']},
        {'situation': 'Your professor asks why international decisions are hard to enforce. Answer in one sentence.', 'tips': ['Because there is no international police, and sovereignty is protected by the same system that is supposed to enforce the rules.', 'Keep it to one sentence, and land on enforce.']},
        {'situation': 'Tell a friend that a country can leave a treaty, and what it has to do first.', 'tips': ['A country can withdraw from a treaty, but formal notice has to be given first.', 'withdraw from, and notice has to be given.']},
        {'situation': 'Report a general belief you have heard about international law, without saying who believes it.', 'tips': ['It is often said that international law works only when states choose to respect it.', 'It is often said that + clause.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Lecture', 'title': "Three Moments, <span class='accent'>One Treaty</span>",
         'blurb': 'A law professor opens a class on treaty law. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Before we open the reading, I want to clear up the mistake that appears in almost every first essay in this course. Students write that a country signed a treaty and is therefore bound by it. That is not how it works. There are three different moments, and they are often years apart. First, the text is adopted, which means the negotiators agree on the words. Second, it is signed, which shows that a state supports the text. And third, it is ratified, usually after a parliament approves it. Only the third moment creates a legal obligation for that state. And even then, many treaties only enter into force after a minimum number of ratifications. So when you read a headline that says a treaty was signed today, ask yourself one question: signed, or ratified? The answer changes the whole article.',
         'qs': [
             ('What mistake does the professor say appears in almost every first essay?', 'Students write that a country that signed a treaty is bound by it.'),
             ('What are the three moments she describes, in order?', 'The text is adopted, then signed, then ratified.'),
             ('Which moment creates a legal obligation, and what question should students ask when they read a headline?', 'Ratification creates the obligation. They should ask: signed, or ratified?'),
         ]},
        {'label': 'Listening 2 &middot; A Radio Explainer', 'title': "Can a Country Just <span class='accent'>Leave?</span>",
         'blurb': 'A short radio explainer on withdrawal from a treaty. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Every time a government threatens to leave an international agreement, our listeners send us the same question: can a country just walk out? The short answer is yes, but not overnight. Most treaties contain their own exit rules, and those rules are usually slower than politicians would like. A written notice has to be sent, and the withdrawal only takes effect after a waiting period, often one year. During that year, the country is still a party, and it is still expected to comply with every provision. Some agreements go further and say that no one can withdraw during the first few years after the treaty enters into force. So when you hear that a country has left an agreement, check the date the notice was given. The country may still be bound for months.',
         'qs': [
             ('What is the short answer to the question, and what does he mean by not overnight?', 'Yes, a country can leave, but withdrawal only takes effect after a waiting period, often one year.'),
             ('What is the country still expected to do during the waiting period?', 'To comply with every provision, because it is still a party.'),
             ('What do some agreements say about the first years, and what should listeners check?', 'That no one can withdraw during the first years after entry into force. Listeners should check the date the notice was given.'),
         ]},
    ],
    'roleplays': {
        'heading': "The Same Seminar, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Correct the <span class='accent'>Headline</span>",
             'scenario': 'A newspaper headline says: &ldquo;Brazil now bound by new climate treaty after signing ceremony.&rdquo; Explain to your seminar group what is wrong with it, in three sentences, using the passive at least twice.',
             'chips': ['has not been ratified', 'a signatory', 'to enter into force', 'binding']},
            {'heading': "The Professor <span class='accent'>Pushes Back</span>",
             'scenario': 'Your professor says: &ldquo;If a treaty cannot be enforced, why should anyone respect it?&rdquo; Give one reason why states comply with treaties, one example of a breach, and ask the professor one question.',
             'chips': ['to comply with', 'a breach', 'sovereignty', 'It is often said that']},
            {'heading': "Two Minutes, <span class='accent'>No Notes</span>",
             'scenario': 'Explain to a first-year student how a treaty goes from a negotiation table to a legal obligation, and what a state can still do after that: make a reservation, or withdraw.',
             'footer': 'No notes, two minutes. Say it in blocks: one moment per sentence, and a pause between them.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>the Seminar</span>",
    'survival': [
        'The treaty was signed in March, but it has not been ratified yet.',
        'A signature shows agreement with the text, but it is not binding.',
        'The agreement will only enter into force after twenty ratifications.',
        'A reservation can be made, but not against the purpose of the treaty.',
        'It is often said that treaties are respected because states choose to respect them.',
    ],
    'checklist': [
        'I can explain the difference between signing and ratifying a treaty.',
        'I use the passive to put the action first: was signed, has been ratified, can be made.',
        'I use by only when the person who acts matters, and never from.',
        'I can read a legal sentence and say it back in plain English.',
        'I know the words: a treaty, a signatory, to ratify, binding, a provision, to enter into force, a party, a reservation, to comply with, a breach, to enforce, sovereignty, to withdraw from.',
    ],
    'badge': {'name': 'The Treaty Reader', 'line': 'Signed, ratified, in force: three moments, and the passive that describes all of them.',
              'next': 'Next lesson: Say It Once, Clearly -- summarizing what somebody said, without stumbling'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada. Va direto: \'Luiza, today we read the kind of text you read for Global Law, and we make it faster.\' Contexto: ela disse que livro de ficcao em ingles e tranquilo, mas que \'quando pega livro da faculdade mesmo\' demora muito, e citou tratado como exemplo. Ela tambem disse que texto demais a irrita: o texto de hoje e CURTO (quatro paragrafos) e o objetivo e velocidade e vocabulario, nao volume.',
        'warmup': '<strong>Warm-up + callback (4 min):</strong> Faca a pergunta da tela e deixe falar. Callback da aula 1: exija pelo menos duas palavras da aula passada na resposta (a requirement, a deadline, to keep up with, a head start, competitive). Se ela usar \'I have been reading\' sozinha, ANOTE: e o present perfect da aula 1 em uso real. ANOTE tambem o que ela diz que torna a leitura lenta &mdash; e o diagnostico desta aula.',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Ligue ao Direito: advogado le para achar QUEM age e QUANDO a obrigacao comeca. Nao de a regra da passiva ainda.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> A frase do colega tem o erro classico: assinar = estar obrigado. Deixe ela argumentar. Se ela ja souber a diferenca (e aluna de Direito), otimo: peca que explique em ingles, em tres frases, e ANOTE onde travou &mdash; provavelmente em palavras como \'ratify\' e \'binding\', que o capitulo 2 traz.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Thirteen words from every Global Law reading.\' B2 = zero portugues na tela. Ela provavelmente conhece o conceito em portugues: cobre a palavra em ingles e a pronuncia, nao a definicao juridica.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> Leia a pista, ela diz a palavra, so entao revele. CCQ \'a signatory\': \'Did it sign or ratify? (Assinou.)\' CCQ \'to ratify\': \'Does it come before or after the signature? (Depois.)\' CCQ \'binding\': \'Can the state ignore it? (Nao.)\' Peca um exemplo real do curso de Direito Global dela.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'to enter into force\': \'Is it the day it is signed or the day it starts to apply? (Quando passa a valer.)\' CCQ \'a party\': \'Is a signatory always a party? (Nao.)\' CCQ \'a reservation\': \'Does it cancel the whole treaty or one part? (Uma parte.)\' Cobre \'comply WITH\' e \'a breach OF\'.',
        'vocab3': '<strong>Vocab reveal 11-13 (4 min):</strong> CCQ \'to enforce\': \'Is it writing the rule or making people obey it? (Fazer obedecer.)\' CCQ \'sovereignty\': pronuncia SOV-rin-ty, duas silabas no inicio, sem o \'reign\' soletrado. CCQ \'to withdraw from\': \'Is it joining or leaving? (Sair.)\'',
        'pron': '<strong>Pronuncia e blocos (4 min):</strong> SIG-na-to-ry (acento na primeira, o portugues puxa para \'signaTOry\'), RAT-i-fy, SOV-rin-ty. Na frase longa, dois blocos com uma pausa: \'The treaty was signed in March / but it has not been ratified yet.\' Se ela travar, recomeca o BLOCO, nao a frase.',
        'matching': '<strong>Matching (3 min):</strong> Ela toca a palavra e a definicao. Se errar, NAO de a resposta: pergunte o CCQ do slide de vocab. Em B2 isso deve ir rapido.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'Four paragraphs. Read once for the argument, and do not stop on any word.\' Ligue a queixa dela: o objetivo aqui e nao parar.',
        'reading': '<strong>Leitura (6 min):</strong> Primeira passada em silencio, com cronometro: meta de 3 minutos, SEM dicionario. Se ela parar numa palavra, diga \'keep going, guess it from the sentence\'. Anote o tempo &mdash; e o numero que as proximas aulas de leitura vao comparar. Depois peca UMA frase de resumo em voz alta. O detalhe fica para o true/false.',
        'gist': '<strong>Gist (3 min):</strong> Ela escolhe e JUSTIFICA em voz alta por que as outras duas estao erradas. A justificativa oral e o exercicio.',
        'tf': '<strong>True or False (6 min):</strong> REGRA DA CASA: ela diz TRUE ou FALSE e LE EM VOZ ALTA a linha do texto que prova. So entao clique. Sem a linha, o acerto nao vale &mdash; e o habito que o reading do TOEFL cobra.',
        'artifact': '<strong>Artefato (4 min):</strong> E um cartao-resumo de seminario, ficticio, com o nome dela. Peca que ela transforme cada linha em frase completa na passiva: \'The text is adopted by the negotiators\', \'The treaty is ratified by the government\'. So depois as 3 perguntas. A nota do seminario pede EXEMPLO, nao definicao: se ela souber um tratado real assinado e nao ratificado pelo Brasil, deixe contar.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four lines from the text. In every one, somebody did something, and nobody is named.\' Passe ao proximo sem antecipar a regra.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Who signed? Who can make a reservation? Why is that person hidden?\' Espere ela concluir que o texto juridico coloca a ACAO em primeiro plano. So entao Reveal the Rule. CCQ: \'The treaty was signed in March &mdash; do we know who signed? Does it matter here? (Nao.)\' CCQ: \'It has been ratified by forty states &mdash; is it still true now? (Sim.)\' Obstaculos do brasileiro: \'was ratify\' (esquece o participio) e \'ratified from\' (calco de \'ratificado pelo\' com preposicao errada).',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ela fala a frase INTEIRA antes de clicar. Na quinta (is being analyzed), cobre a forma continua. Na sexta, peca uma segunda frase dela com \'It is often said that\' sobre a GV.',
        'detective': '<strong>Detective (4 min):</strong> Ela corrige ANTES de clicar e explica. Sao os quatro erros classicos da passiva: participio faltando, from no lugar de by, be faltando depois do modal, e presente no lugar de present perfect com since. Enquadramento: \'os mais comuns\', nunca \'voce errou\'.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: the treaty in plain English, a summary, quick questions, and two recordings.\' Passe ao proximo.',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ela liga a linha do tratado ao ingles simples e EXPLICA a ligacao em voz alta. E o treino de paráfrase do TOEFL reading, com o texto que ela realmente le. Se fechar rapido, peca que ela reescreva uma das linhas do tratado com as proprias palavras.',
        'gap': '<strong>Gap-fill (4 min):</strong> Ela arrasta, toca ou digita a palavra do banco e confere com Check. Se errar, nao explique: aponte a palavra antes ou depois da lacuna (\'comply ___\', \'a ___ of\').',
        'quickfire': '<strong>Quick fire (5 min):</strong> Uma pergunta por vez, em velocidade normal. Ela responde em voz alta ANTES de voce mostrar a dica. Regra: resposta em blocos, sem recomecar a frase. Corrija so a forma da passiva, sempre depois que ela terminar.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELA ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. E uma professora de Direito abrindo uma aula: o registro que ela vai ouvir no intercambio. Depois pergunte se algum professor da GV ja fez essa mesma correcao.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Contexto diferente: radio, voz masculina, explicacao para leigos. Os prazos citados (aviso, periodo de espera de um ano) sao a regra geral de muitos tratados, nao de um tratado especifico: nao apresente como regra universal.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same seminar, three times. The last one is you teaching it.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Ela corrige a manchete em tres frases, com a passiva duas vezes. Voce faz o colega que discorda (\'But it was signed!\'). Corrija so a passiva, no fim.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e a professora que provoca. Exija uma razao, um exemplo de breach (real ou hipotetico) e uma pergunta de volta. E o formato de discussao que ela vai viver no intercambio &mdash; e que ela disse nao gostar quando e so leitura previa: aqui e so fala.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Dois minutos, sem nota, sem interrupcao. Cronometre. No fim, dois numeros: quantas vezes ela recomecou uma frase (compare com a aula 1) e quantas passivas usou. Depois UMA observacao de acento.',
        'survival': '<strong>Survival card (3 min):</strong> Leia cada frase e toque o audio. Ela repete em blocos. Peca que escolha UMA para usar no proximo seminario de Direito Global, mesmo que a aula la seja em portugues &mdash; ela diz a frase em ingles para si mesma antes.',
        'checklist': '<strong>Checklist (2 min):</strong> Diga: \'Click each item if you feel confident.\' Todos os 5 marcados = aula concluida e stamp 2. Item em que ela hesitar entra no warm-up da aula 3.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Luiza, the treaty is rarely the hard part. The hard part is reading it fast enough.\' Homework (ORALMENTE, nunca escrito na tela): pegar UM artigo de um tratado da leitura de Direito Global, sublinhar todas as passivas e dizer o artigo em ingles simples em voz alta. Proxima aula: resumir o que alguem disse, sem travar.',
    },
    'pc': {
        'title': 'The Treaty Is Not the Problem -- The Passive in Legal English',
        'desc': 'A signature is not a promise. Read how a treaty becomes binding, and the passive voice that describes every step.',
        'match_idx': [0, 2, 3, 5, 8, 11],
        'context': [
            'Legal English has a favorite structure, and you see it in every article of every <strong>treaty</strong>: the passive voice. Instead of saying who acts, the text puts the action first. &ldquo;The treaty <strong>was signed</strong> in Geneva&rdquo; tells you what happened and when. Who held the pen is not important, so it is not mentioned.',
            'The passive is built with <strong>be</strong> + past participle, and the verb <em>be</em> carries the time. &ldquo;The convention <strong>has been ratified</strong> by forty states&rdquo; describes a result that is still true. &ldquo;The case <strong>is being heard</strong> this week&rdquo; describes something in progress. When the person who acts matters, it comes after <strong>by</strong>, never after <em>from</em>: &ldquo;It <strong>was approved by</strong> the congress.&rdquo;',
            'Modal verbs work the same way. A <strong>reservation</strong> <strong>can be made</strong> at the moment of ratification, and the text <strong>must be approved</strong> before it becomes <strong>binding</strong>. The most common mistake is to forget <em>be</em> after the modal, as in &ldquo;a reservation can make&rdquo;, which means something completely different.',
            'Finally, legal and academic texts often report a general belief without saying who holds it: &ldquo;<strong>It is often said that</strong> international law has no teeth.&rdquo; Once you recognize the passive, a long legal sentence becomes much easier to read, because you stop looking for a subject that was never there.',
        ],
        'context_quiz': [
            ('According to the text, why does legal English use the passive so often?', ['Because it sounds more polite.', 'Because it puts the action first when the person who acts is not important.', 'Because English has no other way to talk about treaties.'], 1),
            ('Which sentence does the text say is wrong?', ['A reservation can make at the moment of ratification.', 'It was approved by the congress.', 'The case is being heard this week.'], 0),
            ('What does &ldquo;It is often said that&rdquo; allow a writer to do?', ['Mention exactly who said something.', 'Give a personal opinion strongly.', 'Report a general belief without saying who holds it.'], 2),
        ],
        'tip_title': 'The Passive Voice in Legal English',
        'tip_lead': 'Be + past participle puts the action first; add by only when the actor matters.',
        'tip_rows': [
            ('A finished action', 'was / were + past participle', 'The treaty <strong>was signed</strong> in 2019.'),
            ('A result still true', 'has / have been + past participle', 'It <strong>has been ratified</strong> by forty states.'),
            ('Something in progress', 'is / are being + past participle', 'The case <strong>is being heard</strong> this week.'),
            ('Possibility or obligation', 'modal + be + past participle', 'It <strong>must be approved</strong> first.'),
            ('Naming the actor', 'passive + by + agent', 'It was ratified <strong>by the congress</strong>.'),
            ('A general belief', 'it is said / believed that', '<strong>It is said that</strong> treaties are weak.'),
        ],
        'tip_never': 'the treaty was ratify &middot; signed from forty states &middot; a reservation can make &middot; the rules are applied since 2020',
        'blanks': [
            ('The treaty ', 'was signed', ' in Geneva in 2019.', 'Hint: a finished action, and the signers are not important -- two words', None),
            ('The convention ', 'has been ratified', ' by more than one hundred states.', 'Hint: a result that is still true -- three words', None),
            ('A reservation ', 'can be made', ' at the moment of ratification.', 'Hint: possibility, in the passive -- three words', None),
            ('It was approved ', 'by', ' the national congress last year.', 'Hint: the word that introduces who did it -- one word', None),
            ('A signature alone does not make the treaty ', 'binding', '.', 'Hint: legally obligatory -- one word', None),
            ('A state can ', 'withdraw from', ' the agreement after giving notice.', 'Hint: officially leave -- two words', None),
        ],
        'order_title': 'Put the Steps in Order',
        'order_lead': 'A first-year student asks how a treaty becomes binding. Put your explanation in a logical order.',
        'order': [
            'First, the text is negotiated and adopted by the states.',
            'Then it is signed, which shows agreement with the text.',
            'After that, it has to be approved by the national parliament.',
            'Once it is ratified, the state becomes a party.',
            'The treaty enters into force when enough states have ratified it.',
            'From then on, every provision has to be complied with.',
        ],
        'quiz': [
            ('A classmate says a signed treaty is already binding. You correct them:', ['It is binding, because the president signed it.', 'Not yet: it only becomes binding after it has been ratified.', 'Not yet: it has to be signed from the congress first.'], 1),
            ('You want to say the congress approved the treaty. You write:', ['The treaty was approved by the congress.', 'The treaty was approve by the congress.', 'The treaty approved from the congress.'], 0),
            ('You want to explain that one article will not apply to a state. You say:', ['The state made a breach on that article.', 'The state withdrew that article.', 'The state made a reservation on that article.'], 2),
            ('You want to report a general belief without naming anyone. You say:', ['It is often said that treaties are weak.', 'They say me that treaties are weak.', 'Is said that treaties are weak.'], 0),
        ],
        'think': 'A first-year law student asks you: &ldquo;If nobody can force a country to follow a treaty, why do treaties matter?&rdquo; In ninety seconds, explain how a treaty becomes binding, what a state can still do after that, and why most treaties are respected anyway. Use the passive at least three times.',
    },
    'media': [
        {'id': 'series', 'type': 'Series', 'title': 'Suits &mdash; Season 1, Episode 1, &ldquo;Pilot&rdquo;',
         'desc': 'A New York law firm, a lot of fast legal English and a hero who reads faster than anyone in the room. It is corporate law, not international law, but the vocabulary of obligations, agreements and breaches is everywhere.',
         'tip': 'Tip: every time a character says signed, binding or breach, pause and say the sentence again in the passive.',
         'url': 'https://www.tvmaze.com/episodes/12493/suits-1x01-pilot', 'cta': 'See the episode on TVmaze'},
        {'id': 'video', 'type': 'Video', 'title': 'BBC Learning English &mdash; &ldquo;Where do international laws come from?&rdquo; (YouTube)',
         'desc': 'A short animated explainer on where international law comes from and why countries follow it. Clear British English, and exactly the argument of today&rsquo;s reading.',
         'tip': 'Tip: watch once without subtitles and write down three passive sentences you hear. Then check with subtitles on.',
         'url': 'https://www.youtube.com/watch?v=kE137_iMwqw', 'cta': 'Watch on YouTube'},
        {'id': 'talk', 'type': 'Talk', 'title': 'TED-Ed &mdash; &ldquo;Why do we need international law? An animated explainer&rdquo;',
         'desc': 'A TED-Ed lesson with the video, extra questions and a short reading, on how international law bridges the gap between sovereign states. Short, and useful for your Global Law course.',
         'tip': 'Tip: answer the questions on the page out loud before you read the answers.',
         'url': 'https://ed.ted.com/best_of_web/why-do-we-need-international-law-an-animated-explainer', 'cta': 'Open on TED-Ed'},
    ],
}
