# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1400&q=80"
BG5 = "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1400&q=80"
BG6 = "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1400&q=80"

D = {
    'n': 13,
    'reading': True,
    'partner_name': 'viktor',
    'grammar_point_pt': "as oracoes relativas (relative clauses): who para pessoas, which/that para coisas, where para lugares; defining (sem virgulas, informacao essencial) vs non-defining (com virgulas, informacao extra, nunca 'that')",
    'chapter_tag': 'Presenting at the Fair',
    'title_h1': 'Presenting Your Company at a <span class="accent">Trade Fair</span>',
    'title_sub': 'Give a confident pitch, showcase your portfolio, and describe exactly what makes your company stand out.',
    'short_title': 'Presenting at the Fair',
    'menu_title': 'Presenting Your Company at a Trade Fair',
    'menu_desc': 'Pitch your company and describe it with relative clauses',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80",
    'stamp_label': 'Star Presenter',
    'stamp_img': "https://images.unsplash.com/photo-1559223607-a43c990c692c?w=200&q=80",
    'phases': ['The Pitch', 'Words That Sell', 'The Company Story',
               'Relative Clauses', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From the Deal Table to the <span class="accent">Spotlight</span>',
    'warm_p': "Last time you closed a partnership and confirmed every point with reported speech: 'He said the rate would be fixed.' Today the spotlight is on you. A prospect stops at your stand, and you have thirty seconds to explain who you are, what you do, and why your company is the one that stands out on the whole floor.",
    'warm_prompt': 'In one sentence: if a stranger asked you at a fair, what does Escape Turismo do?',
    'missions': [
        'Learn the language of pitching and presenting a company.',
        'Master relative clauses to describe your company and its portfolio.',
        'Give a full pitch, from the elevator opener to the follow-up.',
    ],

    'vocab_trans_h2': 'Words That <span class="accent">Sell</span>',
    'vocab': [
        ("To showcase", "to present something proudly to an audience (mostrar, exibir com orgulho)", "At the fair, we showcase our best destinations."),
        ("Elevator pitch", "a short, persuasive summary of your business (discurso rapido de venda)", "Her elevator pitch lasts thirty seconds."),
        ("To stand out", "to be clearly better or different from others (destacar-se)", "Great service is what makes us stand out."),
        ("Flagship", "the most important, best product or brand (carro-chefe)", "Patagonia is our flagship destination."),
        ("Track record", "a history of past results and achievements (historico de resultados)", "We have a strong track record with groups."),
        ("Selling point", "a feature that makes people want to choose you (diferencial, ponto forte)", "Flexibility is our main selling point."),
        ("To specialize in", "to focus on one particular area (especializar-se em)", "We specialize in luxury group travel."),
        ("Cutting-edge", "very modern and advanced (de ponta, de ultima geracao)", "We use cutting-edge booking technology."),
        ("Established", "existing for a long time and well respected (consolidado, estabelecido)", "We are a well-established agency."),
        ("Brochure", "a printed booklet with information about a company (folheto, catalogo)", "Take a brochure from our stand."),
        ("Prospect", "a possible future client (cliente em potencial)", "Every prospect who visits gets a demo."),
        ("Turnover", "the total amount of business a company does in a period (faturamento)", "Our turnover grew last year."),
    ],

    'gram_trans_h2': 'Relative <span class="accent">Clauses</span>',
    'gram_trans_sub': 'who &middot; which / that &middot; where &middot; defining vs non-defining',
    'gram_examples': [
        ("", "We are an agency that specializes in luxury travel.", '"We are an agency <span style="color:#15803d;font-weight:700">that</span> specializes in luxury travel."'),
        ("", "The prospects who visit our stand get a free brochure.", '"The prospects <span style="color:#15803d;font-weight:700">who</span> visit our stand get a free brochure."'),
        ("", "Patagonia, which is our flagship, attracts thousands of visitors.", '"Patagonia, <span class="accent" style="font-weight:700">which</span> is our flagship, attracts thousands of visitors."'),
    ],
    'gram_disc_q': 'Which word connects to a person, which to a thing, and which to a place? And why does one sentence use commas while the others do not?',
    'gram_table': [
        ("who / that (people)", "essential info, no commas", "The team <strong>that</strong> runs our groups is here."),
        ("which / that (things)", "essential info, no commas", "A package <strong>that</strong> includes flights sells fast."),
        ("where (places)", "for locations", "This is the region <strong>where</strong> we specialize."),
        (", which / , who (extra info)", "non-defining: commas, never 'that'", "Our turnover, <strong>which</strong> grew last year, is strong."),
    ],
    'gram_rule_foot': "Relative clauses: use who for people, which/that for things, where for places. Defining clauses give essential information (no commas); non-defining clauses add extra information (with commas, and never 'that').",

    'lf_h2': 'Describe the <span class="accent">Company</span>',
    'lf_title': 'Complete the relative clause',
    'lf_items': [
        ["A", "We are an agency ", "that", " specializes in group travel.", "strong"],
        ["B", "The prospects ", "who", " visit our stand get a brochure.", "soft"],
        ["C", "Patagonia, ", "which", " is our flagship, sells out fast.", "soft"],
        ["D", "This is the region ", "where", " we have the best rates.", "strong"],
    ],
    'lf_followup': "Use who for people, which/that for things, where for places. Defining clauses (no commas) identify; non-defining clauses (commas, never 'that') just add extra detail.",

    'mistakes': [
        ("We are a company who specializes in tourism.", 'We are a company <strong>that</strong> specializes in tourism.'),
        ("Patagonia, that is our flagship, is popular.", 'Patagonia, <strong>which</strong> is our flagship, is popular.'),
    ],
    'mistake_note': "Use who for people and which/that for things. In a non-defining clause (the one with commas that just adds extra detail), you can never use 'that' -- use which for things and who for people.",

    'read_trans_h2': 'Read the <span class="accent">Pitch</span>',
    'reading_h2': 'The Thirty Seconds That <span class="accent">Matter</span>',
    'read_block': {
        'rtitle': 'The Thirty Seconds That Matter',
        'paras': [
            "A trade fair floor is loud and crowded. Hundreds of companies compete for the same prospects, and every visitor who walks past your stand is deciding, in seconds, whether to stop. This is why the elevator pitch matters. It is the short, confident answer to the one question everyone asks: 'So, what does your company do?'",
            "A great pitch is not a list of everything you offer. It is a story that shows what makes you stand out. The best presenters name one clear selling point -- the thing that only they do well -- and back it up with a track record. 'We are the agency that specializes in luxury group travel in South America,' one director says, 'and Patagonia, which is our flagship destination, sells out every season.' In two sentences, the prospect knows exactly who she is and why she is worth remembering.",
            "The stand itself does the rest. A well-established company showcases its portfolio with a clean brochure, a cutting-edge screen, and a team who can answer any question. But the technology is never the point. The point is the human moment: a warm hello, a sharp pitch, and a follow-up that turns a curious visitor into a real client. Fairs are won not by the biggest stands, but by the companies that make every prospect feel seen.",
        ],
        'source': 'Adapted from a business communication guide',
        'link': 'https://hbr.org/2013/06/how-to-give-a-killer-presentation',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "The company with the biggest and most expensive stand always wins at a fair.", False],
            ["b", "A sharp elevator pitch and one clear selling point make a company stand out and win prospects.", True],
            ["c", "A good pitch is a complete list of every service the company offers.", False],
        ],
        'tf': [
            ["The text says a trade fair floor is quiet and empty.", "f", "It says the floor is loud and crowded, with hundreds of companies competing."],
            ["A great pitch names one clear selling point rather than listing everything.", "t", "The second paragraph says the best presenters name one clear selling point, not a list of everything."],
            ["The text says the technology on the stand is the most important thing.", "f", "It says the technology is never the point -- the human moment is."],
            ["Fairs are won by the companies that make every prospect feel seen.", "t", "The last sentence says fairs are won by the companies that make every prospect feel seen."],
        ],
    },

    'dialogue_h2': 'A Prospect at the <span class="accent">Stand</span>',
    'dialogue': [
        ('viktor', 'arthur', "Hi, I saw your screen from across the hall. So, what does your company do?",
         "Hi, I saw your screen from across the hall. So, what does your company do?"),
        ('andrea', 'ellen', "Great question. We are Escape Turismo, an agency that specializes in luxury group travel in South America. Our flagship, which is Patagonia, sells out every season.",
         "Great question. We are Escape Turismo, an agency that <span class=\"vocab-highlight\">specializes in</span> luxury group travel in South America. Our <span class=\"vocab-highlight\">flagship</span>, which is Patagonia, sells out every season."),
        ('viktor', 'arthur', "Impressive. There are many agencies here. What makes you stand out?",
         "Impressive. There are many agencies here. What makes you <span class=\"vocab-highlight\">stand out</span>?"),
        ('andrea', 'ellen', "Our selling point is service. We are a well-established company that has a strong track record with corporate groups. Every prospect who books with us gets a dedicated manager.",
         "Our <span class=\"vocab-highlight\">selling point</span> is service. We are a well-<span class=\"vocab-highlight\">established</span> company that has a strong <span class=\"vocab-highlight\">track record</span> with corporate groups. Every <span class=\"vocab-highlight\">prospect</span> who books with us gets a dedicated manager."),
        ('viktor', 'arthur', "And the technology? I noticed the screen.",
         "And the technology? I noticed the screen."),
        ('andrea', 'ellen', "That is our cutting-edge booking platform, where a client can compare packages in real time. Let me showcase it for you. Here is a brochure too.",
         "That is our <span class=\"vocab-highlight\">cutting-edge</span> booking platform, where a client can compare packages in real time. Let me <span class=\"vocab-highlight\">showcase</span> it for you. Here is a <span class=\"vocab-highlight\">brochure</span> too."),
        ('viktor', 'arthur', "This is exactly the kind of partner we look for. Our turnover doubled last year, and we need someone reliable.",
         "This is exactly the kind of partner we look for. Our <span class=\"vocab-highlight\">turnover</span> doubled last year, and we need someone reliable."),
        ('andrea', 'ellen', "Then let us talk properly. Take my card, and I will send you the full portfolio, which covers forty destinations, this afternoon.",
         "Then let us talk properly. Take my card, and I will send you the full portfolio, which covers forty destinations, this afternoon."),
    ],
    'comprehension': [
        ("1. What does Viktor ask first when he stops at the stand?", "What the company does -- he asks for the pitch."),
        ("2. Why does Viktor think Escape Turismo could be a good partner?", "Their service, track record, and cutting-edge platform -- and he needs someone reliable."),
        ("3. What happened to Viktor's turnover last year?", "It doubled."),
    ],

    'listen1_h2': 'The <span class="accent">Elevator Pitch</span>',
    'listen1_sub': 'A director gives her thirty-second pitch to a prospect at a fair. Sound first -- no text.',
    'listen1_qs': [
        ("1. What does the agency specialize in?", "Luxury group travel in South America."),
        ("2. What is the flagship destination, and how does it sell?", "Patagonia, which sells out every season."),
        ("3. What is named as the main selling point?", "Service -- a dedicated manager for every group."),
    ],
    'listen2_h2': 'How to Build a <span class="accent">Pitch</span>',
    'listen2_sub': 'A short business tip on describing your company with relative clauses. Sound first -- no text.',
    'listen2_qs': [
        ("1. Which relative word do we use for people, and which for things?", "Who for people; which or that for things."),
        ("2. When do we use commas in a relative clause?", "In non-defining clauses -- when the information is extra, not essential."),
        ("3. What can you never use in a non-defining clause?", "The word 'that' -- use which or who instead."),
    ],
    'listenings': [
        {'file': 'a13_listening_pitch.mp3', 'voice': 'ellen',
         'text': "Hi, thanks for stopping by. Let me give you the short version. We are Escape Turismo, an agency that specializes in luxury group travel across South America. Our flagship destination, which is Patagonia, sells out every single season. What makes us stand out is service. We are a well-established company that has handled corporate groups for over fifteen years, and every prospect who books with us gets a dedicated manager, someone who is available around the clock. If you like what you hear, take a brochure, and I will send you the full portfolio, which covers forty destinations. It would be great to work together."},
        {'file': 'a13_listening_pitchtip.mp3', 'voice': 'arthur',
         'text': "Welcome to this short segment on presenting your company. When you describe what you do, relative clauses are your best friend. They let you add detail without starting a new sentence. Use who for people: the team who runs our groups. Use which or that for things: a platform that compares prices. Use where for places: the region where we specialize. Now, here is the key point for a polished pitch. There are two types. A defining clause gives essential information, and it takes no commas: the agency that books your trip. A non-defining clause just adds extra detail, and it takes commas, like this: our flagship, which is Patagonia, sells out fast. And remember, in that second type, never use the word that. Master this, and your pitch will sound clear, confident, and professional."},
    ],

    'gapfill_parts': [
        "At the fair, Andrea meets a prospect ", ["1"],
        " stops at her stand. She explains that Escape Turismo is an agency ",
        ["2"], " specializes in luxury group travel. Their flagship destination, ",
        ["3"], " is Patagonia, sells out every season. She shows the platform ",
        ["4"], " clients compare packages, and hands over a ", ["5"], ".",
    ],
    'gapfill_bank': ["who", "that", "which", "where", "brochure"],
    'vocabnote': "Relative clauses: use who for people, which/that for things, where for places. A defining clause has no commas (essential info); a non-defining clause has commas and never uses 'that' -- use which or who instead.",

    'bank_label_top': 'Pitch',
    'bank_label': 'Useful language for pitching and describing your company',
    'bank_items': [
        "We are an agency that specializes in luxury travel.",
        "Our flagship destination, which is Patagonia, sells out fast.",
        "What makes us stand out is our service.",
        "Every prospect who visits our stand gets a brochure.",
        "This is the platform where clients compare packages.",
        "We have a strong track record with corporate groups.",
        "Our main selling point is flexibility.",
        "Let me showcase our portfolio for you.",
    ],

    'scenarios_h2': 'Give Your <span class="accent">Pitch</span>',
    'scenario_items': [
        ["Scenario 1", "A prospect stops and asks what you do. Give a one-sentence pitch: 'We are an agency that...'."],
        ["Scenario 2", "Describe your flagship destination using a non-defining clause: 'Patagonia, which...'."],
        ["Scenario 3", "A prospect asks what makes you different. Name one selling point and back it with your track record."],
        ["Scenario 4", "Invite the prospect to follow up: showcase the brochure and offer the full portfolio."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = who, 2 = that, 3 = which, 4 = where, 5 = brochure.",
        "Defining clause (no commas): 'the agency that books your trip'.",
        "Non-defining clause (commas, never 'that'): 'our flagship, which is Patagonia, sells out'.",
        "who = people, which/that = things, where = places.",
    ],
    'answerkey_note': "Relative clauses: who for people, which/that for things, where for places; defining = no commas, non-defining = commas and never 'that'.",

    'roleplays': [
        {'h2': 'The <span class="accent">Opener</span>',
         'scenario': "A prospect stops at your stand and asks 'What does your company do?'. Give your thirty-second elevator pitch using a defining relative clause.",
         'keywords': ["We are an agency that...", "we specialize in...", "our flagship..."]},
        {'h2': 'Stand <span class="accent">Out</span>',
         'scenario': "The prospect says there are many agencies at the fair. Explain your selling point and describe your portfolio using relative clauses.",
         'keywords': ["what makes us stand out...", "which is...", "a track record that..."]},
        {'h2': 'Win the <span class="accent">Prospect</span>',
         'scenario': "Give your full pitch from start to finish: open, showcase the flagship, name your selling point, and invite the prospect to follow up.",
         'keywords': []},
    ],

    'survival_h2': 'Pitch Like a <span class="accent">Pro</span>',
    'survival': [
        ("We are an agency that specializes in luxury travel.", "Somos uma agencia que se especializa em viagens de luxo."),
        ("Our flagship, which is Patagonia, sells out every season.", "Nosso carro-chefe, que e a Patagonia, esgota toda temporada."),
        ("What makes us stand out is our service.", "O que nos faz se destacar e o nosso servico."),
        ("Every prospect who visits our stand gets a brochure.", "Todo cliente em potencial que visita nosso stand recebe um folheto."),
        ("Let me showcase our portfolio for you.", "Deixe-me mostrar o nosso portfolio para voce."),
    ],
    'learned': [
        "I can describe people with 'who' and things with 'which' or 'that'.",
        "I can use 'where' to describe a place in a relative clause.",
        "I can tell a defining clause (no commas) from a non-defining one (commas, never 'that').",
        "I can give a clear elevator pitch and name one selling point.",
        "I know the words: to showcase, elevator pitch, to stand out, flagship, track record, selling point, to specialize in, cutting-edge, established, brochure, prospect, turnover.",
    ],
    'badge_name': 'Star Presenter Badge',
    'badge_p': 'You can pitch your company at a fair with confidence -- describing exactly what makes you stand out using clear relative clauses, Andrea.',
    'next_lesson': 'Talking About Trends and the Future of Tourism',

    # ----- new B2 slides (pipeline v2) -----
    'spot_errors': [
        ("We are a company who specializes in tourism.", "We are a company that specializes in tourism."),
        ("Patagonia, that is our flagship, is popular.", "Patagonia, which is our flagship, is popular."),
        ("This is the platform who clients compare prices.", "This is the platform where clients compare prices."),
        ("Every prospect which visits gets a brochure.", "Every prospect who visits gets a brochure."),
    ],
    'bridge5': {
        'h2': 'Voices on the <span class="accent">Fair Floor</span>',
        'sub': 'Listen to a real pitch, then present your own company out loud.',
        'bg': BG5,
    },
    'register': [
        ("We are the best. Just trust me.", "We have a track record that speaks for itself."),
        ("Everyone else here is worse.", "What makes us stand out is our service."),
        ("Buy from us now.", "Take a brochure, and let us follow up after the fair."),
        ("Our stuff is very modern.", "We use a cutting-edge booking platform."),
    ],
    'artifact': {
        'label': 'The One-Pager',
        'h2': 'Company <span class="accent">Fact Sheet</span>',
        'meta': [
            ("Company:", "Escape Turismo -- Luxury Group Travel"),
            ("Founded:", "A well-established agency, operating since 2008"),
            ("Contact:", "Andrea Aggio -- Commercial Director"),
        ],
        'paras': [
            "Who we are: Escape Turismo is an agency that specializes in luxury group travel across South America. Our flagship destination, which is Patagonia, sells out every season.",
            "Why we stand out: a track record that includes over 500 corporate groups, a cutting-edge booking platform where clients compare packages in real time, and a dedicated manager for every prospect who books with us.",
            "The numbers: a portfolio that covers forty destinations, and a turnover that grew thirty percent last year. Take a brochure, and let us showcase the full portfolio for you.",
        ],
    },
    'artifact_qs': [
        ("1. What does the company specialize in, and since when?", "Luxury group travel; it has been established since 2008."),
        ("2. What does the platform let clients do?", "Compare packages in real time -- it is described as cutting-edge."),
        ("3. What two numbers does the fact sheet give?", "A portfolio of forty destinations and a turnover that grew thirty percent."),
    ],
    'pron_lines': [
        ("An agency that specializes in travel.", "'agency that' links -- a-jen-see-that; stress speh-shuh-lai-zes."),
        ("What makes us stand out.", "'stand out' links -- stan-dout; stress OUT."),
        ("Our flagship, which is Patagonia.", "pause at the comma -- flagship / which; keep 'which' soft."),
        ("The platform where clients compare packages.", "'where clients' links -- wair-cly-ents; keep it smooth."),
    ],
    'bridge6': {
        'h2': 'Now You <span class="accent">Present</span>',
        'sub': 'Your turn: pitch your company and describe it out loud, one scenario at a time.',
        'bg': BG6,
    },
    'quickfire': [
        {'situation': "A prospect stops and asks, 'What does your company do?'",
         'tips': ["'We are an agency that specializes in...'", "Name one clear focus.", "Keep it to one sentence."]},
        {'situation': "You want to describe your flagship destination with extra detail.",
         'tips': ["Use a non-defining clause: 'which is...'", "Remember the commas.", "'Patagonia, which is our flagship, sells out.'"]},
        {'situation': "A prospect asks what makes you different from the stand next door.",
         'tips': ["'What makes us stand out is...'", "Name one selling point.", "Back it with a track record."]},
        {'situation': "You want to describe your booking platform to a tech-curious visitor.",
         'tips': ["Use 'where': 'the platform where...'", "'...clients compare packages in real time.'", "Call it cutting-edge."]},
        {'situation': "A prospect is interested and you want to follow up after the fair.",
         'tips': ["'Take a brochure...'", "'I will send you the full portfolio, which covers...'", "Offer your card."]},
    ],

    'preclass_title': 'Presenting Your Company at a Trade Fair',
    'preclass_desc': "How to pitch your company and describe it with relative clauses. Key words: to showcase, elevator pitch, to stand out, flagship, track record, selling point, to specialize in, cutting-edge, established, brochure, prospect, turnover. Structure: relative clauses (who / which / that / where; defining vs non-defining).",
    'context': ("At the fair, a <strong>prospect</strong> stops at Andrea's stand. 'We are an agency <strong>that</strong> "
                "<strong>specializes in</strong> luxury group travel,' she says. 'Our <strong>flagship</strong>, "
                "<strong>which</strong> is Patagonia, <strong>stands out</strong> every season.' She points to the "
                "<strong>cutting-edge</strong> platform <strong>where</strong> clients compare packages in real time. "
                "'We are a well-<strong>established</strong> company <strong>that</strong> has a strong <strong>track "
                "record</strong>,' she adds, handing him a <strong>brochure</strong>. Every prospect <strong>who</strong> "
                "visits gets a demo -- and that is exactly why Escape Turismo's <strong>turnover</strong> keeps growing."),
    'context_quiz': [
        ("1. 'An agency that specializes in travel' -- 'that' refers to:",
         [("A", "a thing (the agency).", True),
          ("B", "a place.", False),
          ("C", "a person.", False)]),
        ("2. Which sentence uses commas correctly (non-defining clause)?",
         [("A", "Patagonia which is our flagship sells out.", False),
          ("B", "Patagonia, which is our flagship, sells out.", True),
          ("C", "Patagonia, that is our flagship, sells out.", False)]),
        ("3. Which relative word describes a place?",
         [("A", "who", False),
          ("B", "which", False),
          ("C", "where", True)]),
    ],
    'tip_title': 'Relative Clauses',
    'tip_sub': "Como descrever pessoas, coisas e lugares numa mesma frase (explicacao em ingles e portugues).",
    'tip_rows': [
        ("who / that (pessoas)", "para pessoas; info essencial, sem virgulas. for people.", "The team <strong>that</strong> runs our groups."),
        ("which / that (coisas)", "para coisas; info essencial, sem virgulas. for things.", "A package <strong>that</strong> includes flights."),
        ("where (lugares)", "para lugares. for places.", "The region <strong>where</strong> we specialize."),
        ("Non-defining / info extra", "com virgulas; nunca use 'that'. commas, never 'that'.", "Patagonia, <strong>which</strong> is our flagship, sells out."),
    ],
    'fill': [
        ('"We are an agency ', "that", "Dica: coisa (a agencia), info essencial", "We are an agency that specializes in luxury travel.", ' specializes in luxury travel."'),
        ('"Every prospect ', "who", "Dica: pessoa", "Every prospect who visits our stand gets a brochure.", ' visits our stand gets a brochure."'),
        ('"Patagonia, ', "which", "Dica: coisa, info extra (virgulas, nunca that)", "Patagonia, which is our flagship, sells out.", ' is our flagship, sells out."'),
        ('"This is the region ', "where", "Dica: lugar", "This is the region where we specialize.", ' we specialize."'),
        ('"What makes us ', "stand", "Dica: destacar-se (___ out)", "What makes us stand out is our service.", ' out is our service."'),
        ('"Let me ', "showcase", "Dica: mostrar com orgulho", "Let me showcase our portfolio for you.", ' our portfolio for you."'),
    ],
    'order_intro': "Coloque os passos de um bom pitch de empresa na ordem correta.",
    'order': [
        "Greet the prospect and open with a one-sentence pitch.",
        "Say what your company specializes in.",
        "Name the selling point that makes you stand out.",
        "Showcase your flagship and your track record.",
        "Hand over a brochure and offer to follow up.",
    ],
    'speech': [
        ("We are an agency that specializes in luxury travel.", "Somos uma agencia que se especializa em viagens de luxo."),
        ("Our flagship, which is Patagonia, sells out every season.", "Nosso carro-chefe, que e a Patagonia, esgota toda temporada."),
        ("What makes us stand out is our service.", "O que nos faz se destacar e o nosso servico."),
        ("This is the platform where clients compare packages.", "Esta e a plataforma onde os clientes comparam pacotes."),
        ("Let me showcase our portfolio for you.", "Deixe-me mostrar o nosso portfolio para voce."),
    ],
    'quiz': [
        ("A prospect asks what your company does. You say:",
         [("A", "We are an agency that specializes in group travel.", True),
          ("B", "We are an agency who specializes in group travel.", False),
          ("C", "We are an agency where specializes in group travel.", False)]),
        ("You describe your flagship with extra information. You say:",
         [("A", "Patagonia, which is our flagship, sells out fast.", True),
          ("B", "Patagonia, that is our flagship, sells out fast.", False),
          ("C", "Patagonia which is our flagship sells out fast.", False)]),
        ("You describe the people who book with you. You say:",
         [("A", "Every prospect who books gets a manager.", True),
          ("B", "Every prospect which books gets a manager.", False),
          ("C", "Every prospect where books gets a manager.", False)]),
        ("You describe the place where clients compare packages. You say:",
         [("A", "This is the platform where clients compare packages.", True),
          ("B", "This is the platform who clients compare packages.", False),
          ("C", "This is the platform which clients compare there.", False)]),
    ],
    'think': "Imagine a prospect has just stopped at your stand at a trade fair. Record your thirty-second elevator pitch for Escape Turismo. Describe your company and portfolio using relative clauses ('We are an agency that...', 'Our flagship, which is...', 'the platform where...'), name one clear selling point, and invite the prospect to follow up. Take your time.",

    'media': [
        ('series', "Shark Tank (ABC / streaming) -- any season",
         "Founders pitch their companies to investors in minutes, using exactly the language of this lesson: what they do, what makes them stand out, and their track record. Connection to Lesson 13: presenting a company and describing it with relative clauses.",
         'Tip: pick one pitch and note every relative clause the founder uses ("a product that...", "a market where...").',
         'https://www.imdb.com/title/tt1442437/'),
        ('podcast', 'How I Built This with Guy Raz (NPR)',
         "Founders tell the story of the company they built -- how they describe it, position it, and explain what makes it different. Rich, natural business English. Connection to Lesson 13: pitching and describing your company with confidence.",
         'Tip: after an episode, write a one-sentence pitch for that company using a relative clause.',
         'https://www.npr.org/series/490248027/how-i-built-this'),
        ('youtube', '"Defining relative clauses" -- 6 Minute Grammar, BBC Learning English',
         "A clear lesson on the exact grammar of this class: who, which, that, where, and the difference between defining and non-defining clauses. Connection to Lesson 13: describing your company with 'an agency that...' and 'Patagonia, which is...'.",
         'Tip: after each example, describe one part of Escape Turismo using the same structure.',
         'https://www.youtube.com/watch?v=1iC_rULeuZc'),
    ],
}
