{
  goals:'<strong>To read a news article with numbers from different sources and brief a director who has not read it, saying each figure in full, where it comes from, and whether it is measured or estimated.</strong><ul>'+
        '<li>To read the article once for the story before working on the numbers.</li>'+
        '<li>To attribute each figure to the source that gives it, going back to the line.</li>'+
        '<li>To tell a measured figure from an estimate and from an expectation, by the words around it.</li>'+
        '<li>To compare two percentages in percentage points, not in percent.</li>'+
        '<li>To answer an interruption and a question the article does not answer, and to ask one back.</li></ul>',
  product:'The briefing on screen 9, said live to the director she chose (you), with the sentence starters closed: what the article is about, the figures that matter to that director with their sources, the estimates marked as estimates, and her own reading marked as hers. Then, on screen 10, her answers to two questions from the director and one question of her own.',
  criteria:'<ul><li>Each figure comes with its source in the same sentence.</li>'+
           '<li>The consultancy figures are marked as estimates, without being asked.</li>'+
           '<li>The change from 9.2% to 14.6% is said as the two figures or as 5.4 percentage points.</li>'+
           '<li>After the interruption on screen 9 she goes back to the point she had left.</li></ul>',
  prep:'<ul><li>Read the article before the lesson. The figures and their sources: overtime up 18.4% between April and June (the company); turnover at the largest site from 9.2% to 14.6% (company figures); about $4,870 to replace one worker (the consultancy&rsquo;s estimate); roughly $233,800 for the 48 people who left (a calculation on that estimate &mdash; the company has not published a cost); nine to twelve extra days per trip and a reopening expected by the end of the year (the carriers).</li>'+
       '<li>Screen 1 asks for news she read this week. She asked for current events as material, and her answer is the only real news in the lesson. The article is a sample with an invented company; if she asks, say so.</li>'+
       '<li>The interruption on screen 9 and the two questions on screen 10 are written in the notes on those screens, for both options.</li>'+
       '<li>In an earlier lesson she said she could not see the point of a task that had no context. On screens 2 and 9, read who is asking and what they need with her before she starts.</li></ul>',
  language:'<strong>Saying the source:</strong> <em>According to the company,&hellip;</em> &middot; <em>Company figures show&hellip;</em> &middot; <em>That comes from&hellip;, not from&hellip;</em><br><strong>Marking an estimate:</strong> <em>A consultancy estimates about&hellip;</em> &middot; <em>That would be roughly&hellip;</em> &middot; <em>That is an estimate, not a company figure.</em><br><strong>Comparing percentages:</strong> <em>from 9.2 to 14.6 percent</em> &middot; <em>a rise of 5.4 percentage points</em> &middot; <em>up by more than half</em><br>Numbers in full: <em>eighteen point four percent</em> &middot; <em>one thousand three hundred twelve</em> &middot; <em>four thousand eight hundred seventy dollars</em> &middot; <em>two hundred thirty-three thousand eight hundred dollars</em>.',
  transcript:'The audio in this lesson is the five model sentences on screen 8. The model briefing on the same screen is written, behind a button: open it after she has given the three figures herself.',
  difficulties:'<ul><li><strong>The broken number may get rounded.</strong> She has said that a round figure is easy and a broken one is where she gets lost. She may say &ldquo;around five thousand&rdquo; to avoid <em>four thousand eight hundred seventy</em>. Note which numbers she rounds.</li>'+
       '<li><strong>5.4 may come out as percent.</strong> In an earlier lesson she was unsure whether to say <em>points</em> or <em>percent</em>. Screen 7 works on it.</li>'+
       '<li><strong>The total may sound like a company figure.</strong> The $233,800 is the one number in the article that sounds exact and is not a company figure.</li>'+
       '<li><strong>Portuguese may appear under pressure.</strong> In recent lessons it appeared when she was unsure what a task was for, more than when a word was missing.</li></ul>',
  scaffolding:'The article is on screen 4 and behind the <em>Show the article</em> button on screen 5. On screens 9 and 10 the sentence starters are behind a closed button: open them only if she stops, let her look, and close them again.<br><br>'+
    'If a number stalls on screen 8, say the first half of it (<em>four thousand&hellip;</em>) and let her finish. If the briefing is clean on the first attempt, the challenge on screen 9 asks her which figure she would check before repeating it in a meeting.',
  feedback:'One point on screen 11, taken from a sentence with a number that she said on screen 9, and then the replay: the same briefing to the director from the other option, who needs something different first.<br><br>'+
    'Leave corrections for screen 11. Interrupting the briefing for language costs the sentences that were still coming.',
  evidence:'<ul><li><strong>Which figures came out in full and correct, and which she rounded or swapped.</strong> It is the main record of the lesson.</li>'+
    '<li>Whether the estimates were marked without prompting on screen 9.</li>'+
    '<li>Whether 5.4 was said as percentage points after screen 7.</li>'+
    '<li>What she did after the interruption: back to the point, a new start, or Portuguese.</li>'+
    '<li>The news she brought on screen 1, in her words. It can come back in later lessons.</li></ul>',
  prepost:'The pre-class reads a different, shorter news item about absenteeism in a hot quarter, asks who gives each piece of information and how the numbers are said, and ends with four sentences that put the source in the sentence. It does not touch the article of the lesson, the words that mark an estimate, or percentage points. The post-class has an optional recording, an optional written note, an article and a talk about numbers in the news, and a language reference.',
  key:'<strong>Screen 4:</strong> a closed shipping route has pushed overtime and turnover up at a logistics company in S&atilde;o Paulo state; the company has not published what the departures cost and has not decided about temporary staff. <strong>Screen 5:</strong> the company &mdash; overtime up 18.4%, turnover 14.6%; the carriers &mdash; nine to twelve extra days, reopening by the end of the year; the consultancy &mdash; $4,870 per worker; nobody &mdash; the departures cost $233,800. <strong>Screen 6:</strong> who it comes from &mdash; <em>the company says</em>, <em>according to two of the largest carriers</em>; not exact &mdash; <em>roughly</em>, <em>would represent</em>; not happened yet &mdash; <em>expect the route to reopen</em>, <em>has not decided whether</em>. <strong>Screen 7:</strong> &ldquo;Turnover rose 5.4 percent.&rdquo; is the different one.'
}
