# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 15,
 'phases': ["Bigger or Better", "Measure Words", "Comparative Forms", "The Comparison", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1551288049-bebda4e38f71?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1460925895917-afdab827c52f?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "Bigger, Better,", 'title_b': "Different",
 'subtitle1': "Comparing HR data across global teams",
 'hook_a': "Bigger or", 'hook_b': "Better?",
 'hook_prompt': "Two regions, two sets of numbers. Which one is stronger, and how do you say why?",
 'recall_a': "From Offers to", 'recall_b': "Comparisons",
 'recall_text': "Last class you made offers and promises with will. Today you compare results and data across teams and regions.",
 'recall_chips': ["bigger than", "more efficient than", "better than"],
 'vocab_sub': "The words for comparing HR data",
 'vocab_head1': ("Measure and", "Compare"),
 'vocab_head2': ("Gaps and", "Ratios"),
 'vocab': [
   ("Significant", "meaningful or large enough to matter", "significativo", "The gap between the two teams is significant."),
   ("Slightly", "by a small amount", "levemente / um pouco", "Turnover is slightly lower than last year."),
   ("Considerably", "by a large amount", "consideravelmente", "The branch is considerably more efficient."),
   ("Roughly", "approximately, about", "aproximadamente", "The costs are roughly the same in both regions."),
   ("Margin", "the difference between two amounts", "margem", "The margin between our best and worst teams is wide."),
   ("Disparity", "a big and unfair difference", "disparidade", "There is a disparity between the two departments."),
   ("Comparable", "similar enough to be compared", "comparável", "The two regions are comparable in size."),
   ("Ratio", "a relationship between two numbers", "proporção / razão", "The attrition ratio is higher in Sales."),
   ("Competitive", "as good as or better than others", "competitivo", "Our salaries are more competitive than before."),
   ("Narrow", "small in difference or width", "estreito / pequeno", "The gap between them is very narrow."),
   ("Outweigh", "to be more important than", "superar / pesar mais que", "The benefits outweigh the costs."),
   ("Discrepancy", "a difference that should not be there", "discrepância", "There is a discrepancy between the target and the result."),
 ],
 'concept_label': "Comparatives at a Glance",
 'concept_a': "Short vs", 'concept_b': "Long",
 'concept_sub': "The length of the adjective tells you the form",
 'concept_cols': [
   ("SHORT ADJ (+er than)", "big &rarr; bigger, high &rarr; higher, low &rarr; lower"),
   ("LONG ADJ (more ... than)", "efficient &rarr; more efficient, competitive &rarr; more competitive"),
 ],
 'concept_drill': [
   ("Compare two team sizes.", "Our team is bigger than theirs."),
   ("Compare efficiency.", "The North is more efficient than the South."),
   ("Compare results to last year (irregular).", "Results are better than last year."),
   ("Say two numbers are equal.", "It is as high as last year."),
 ],
 'pron': [
   "Our turnover is lower than last year.",
   "This market is more competitive than ours.",
   "Our results are better than the forecast.",
   "The gap is as wide as last quarter.",
 ],
 'gram_title_a': "Comparative", 'gram_title_b': "Adjectives",
 'gram_title_sub': "Short, long, and irregular forms",
 'discovery': [
   ('"Our turnover rate is <span class="accent" style="font-weight:700">lower than</span> last year."', "Our turnover rate is lower than last year."),
   ('"This region is <span class="accent" style="font-weight:700">more competitive than</span> the others."', "This region is more competitive than the others."),
   ('"Our results are <span class="accent" style="font-weight:700">better than</span> the forecast."', "Our results are better than the forecast."),
   ('"The gap is <span class="accent" style="font-weight:700">as wide as</span> last quarter."', "The gap is as wide as last quarter."),
 ],
 'rule_head': ["Type", "Form", "Example"],
 'rule_rows': [
   ("Short adjective", "adj + -er + than", "higher than, lower than"),
   ("Long adjective", "more + adj + than", "more efficient than"),
   ("Irregular", "good&rarr;better, bad&rarr;worse", "better than, worse than"),
   ("Equality", "as + adj + as", "as high as last year"),
 ],
 'mistakes': [
   ("This region is more bigger than the North.", "This region is <strong>bigger</strong> than the North."),
   ("Our results are gooder than last year.", "Our results are <strong>better</strong> than last year."),
   ("Turnover is more high this quarter.", "Turnover is <strong>higher</strong> this quarter."),
   ("The gap is as wider as before.", "The gap is <strong>as wide as</strong> before."),
 ],
 'mistake_note': "Short adjectives add -er; never use more with them. Long adjectives use more. Good and bad are irregular: better, worse. Use as + base adjective + as for equality.",
 'gpr_a': "Complete the", 'gpr_b': "Comparison",
 'gpractice': [
   ('"Our turnover rate is ', "lower than", ' last year. (short adj)"'),
   ('"This market is ', "more competitive than", ' ours. (long adj)"'),
   ('"Our results are ', "better than", ' the forecast. (irregular)"'),
   ('"The gap is ', "as wide as", ' last quarter. (equality)"'),
   ('"Attrition is ', "slightly higher", ' in that region. (short adj)"'),
 ],
 'build1_label': "Build the Comparison",
 'build1_a': "Compare the", 'build1_b': "Data",
 'build1': [
   ("our team / big / than / the London team", "Our team is bigger than the London team."),
   ("this quarter / competitive / than / last quarter", "This quarter is more competitive than last quarter."),
   ("attrition / high / this year / than / last year", "Attrition is higher this year than last year."),
   ("our results / good / than / the forecast", "Our results are better than the forecast."),
   ("the gap / narrow / as / last month", "The gap is as narrow as last month."),
 ],
 'context_sub': "Comparing regions before a global meeting",
 'dlg_title_a': "Two", 'dlg_title_b': "Regions",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, I have the turnover numbers for both regions. Which one looks stronger?",
    "Murielle, I have the turnover numbers for both regions. Which one looks stronger?"),
   ("M", "#86198F", "murielle", "ellen",
    "Let me see. The South region is bigger than the North, but its turnover is higher.",
    "Let me see. The South region is bigger than the North, but its turnover is higher."),
   ("E", "#1b4965", "ethan", "arthur",
    "Interesting. So the North is more efficient, even though it is smaller.",
    "Interesting. So the North is more efficient, even though it is smaller."),
   ("M", "#86198F", "murielle", "ellen",
    'Exactly. The <span class="vocab-highlight">disparity</span> is <span class="vocab-highlight">significant</span>. The North retains staff far better than the South.',
    "Exactly. The disparity is significant. The North retains staff far better than the South."),
   ("E", "#1b4965", "ethan", "arthur",
    "And costs? Is the North more expensive to run?",
    "And costs? Is the North more expensive to run?"),
   ("M", "#86198F", "murielle", "ellen",
    'No, it is <span class="vocab-highlight">roughly</span> the same. The <span class="vocab-highlight">margin</span> in results is wider than the margin in cost.',
    "No, it is roughly the same. The margin in results is wider than the margin in cost."),
   ("E", "#1b4965", "ethan", "arthur",
    "So our recommendation is clear. The North model is better than the South model.",
    "So our recommendation is clear. The North model is better than the South model."),
   ("M", "#86198F", "murielle", "ellen",
    'Yes. I will present it as the more <span class="vocab-highlight">competitive</span> option for the whole company.',
    "Yes. I will present it as the more competitive option for the whole company."),
 ],
 'dlg_comp': [
   ("Which region is bigger, the South or the North?", "The South region is bigger than the North."),
   ("Why is the North the better model?", "It is more efficient and retains staff far better, at roughly the same cost."),
   ("How will Murielle present the North model?", "As the more competitive option for the whole company."),
 ],
 'listenings': [
   {"title_a": "Two", "title_b": "Sites", "file": "a15_listening_sites.mp3", "voice": "arthur",
    "text": ("Hello team. Here is a quick comparison of our two sites. The head office is larger than the branch, "
             "but its turnover is considerably higher. The branch is smaller, yet it performs better on almost "
             "every metric. The gap in engagement is significant. The branch is also more cost-effective, because "
             "its overtime is lower. The difference in results is much wider than the difference in size. In short, "
             "the smaller site is more competitive than the bigger one. I think the branch is the stronger model, "
             "and we should learn from it."),
    "qs": [
      ("Which site is larger?", "The head office is larger than the branch."),
      ("Why is the branch the stronger model?", "It performs better on almost every metric and is more cost-effective, with lower overtime."),
      ("What is bigger: the difference in results or the difference in size?", "The difference in results is much wider than the difference in size."),
    ]},
   {"title_a": "This", "title_b": "Year", "file": "a15_listening_year.mp3", "voice": "ellen",
    "text": ("Good morning. Let me compare this year with last year. Our turnover is slightly lower, which is good "
             "news. The disparity between departments, however, is bigger than before. Sales has a much higher "
             "attrition ratio than Finance. The margin between our best and worst teams is wider this year. There "
             "is also a clear discrepancy between our targets and our results. Still, overall we are more efficient "
             "than last year, and our costs are more comparable across regions. I am confident that next year will "
             "be even stronger."),
    "qs": [
      ("Is turnover higher or lower than last year?", "It is slightly lower than last year."),
      ("What is bigger than before?", "The disparity between departments is bigger than before."),
      ("How does this year compare overall?", "Overall we are more efficient than last year, with costs more comparable across regions."),
    ]},
 ],
 'art_title_a': "Comparison", 'art_title_b': "Summary",
 'art_kicker': "HR Benchmark &middot; Minerva Foods",
 'art_subtitle': "Regional Comparison -- Q3",
 'art_lines': [
   "The North region is more efficient than the South.",
   "Turnover in the South is higher than in the North.",
   "The engagement gap is wider than last quarter.",
   "The North is the more competitive model overall.",
 ],
 'art_sign': "Prepared by: Murielle Xavier",
 'art_note': "Read each line aloud: The North region is more efficient than the South.",
 'quickfire': [
   ("Compare two regions by turnover (South is higher).", "The South has higher turnover than the North."),
   ("Say the branch is more efficient.", "The branch is more efficient than the head office."),
   ("Say results are better than the forecast.", "Our results are better than the forecast."),
   ("Say the costs are equal to last year.", "The costs are as high as last year."),
   ("Give an opinion: this model is the more competitive one.", "This model is more competitive than the other."),
 ],
 'spot': [
   ("This region is more bigger than the North.", "This region is bigger than the North. (no more with short adjectives)"),
   ("Our results are gooder than last year.", "Our results are better than last year. (good is irregular: better)"),
   ("Turnover is more high this quarter.", "Turnover is higher this quarter. (short adjective + -er)"),
   ("The gap is as wider as before.", "The gap is as wide as before. (as + base adjective + as)"),
 ],
 'build2': [
   ("our turnover / low / than / last year", "Our turnover is lower than last year."),
   ("this region / competitive / than / the others", "This region is more competitive than the others."),
   ("the North / efficient / than / the South", "The North is more efficient than the South."),
   ("our results / good / than / the forecast", "Our results are better than the forecast."),
   ("the gap / wide / as / last quarter", "The gap is as wide as last quarter."),
 ],
 'production_sub': "From guided to free. Compare and recommend.",
 'roleplays': {
   'guided': {'h': ("Compare Two", "Regions"),
     'scenario': "Ethan asks: Which region performs better this quarter? Compare the two regions using turnover, cost, and engagement. Make at least three comparisons.",
     'chips': ["bigger / smaller than", "more efficient than", "better / worse than", "significant"]},
   'semi': {'h': ("Present the", "Benchmark"),
     'scenario': "Present your regional benchmark to Ethan. Compare this year with last year, then say which model is the more competitive one and why.",
     'chips': ["disparity", "margin", "comparable"]},
   'free': {'h': ("Your Own", "Comparison"),
     'scenario': "Compare two real teams, regions, or years from your own HR work. Make at least four comparisons and give your opinion on which is stronger. Use comparatives and the new words.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "Our turnover is lower than last year.",
   "This region is more competitive than the others.",
   "Our results are better than the forecast.",
   "The gap is as wide as last quarter.",
   "The difference is significant.",
 ],
 'checklist': [
   "I can compare with short adjectives: bigger, higher, lower than.",
   "I can compare with long adjectives: more efficient than, more competitive than.",
   "I can use irregular comparatives: better and worse than.",
   "I can express equality with as ... as: as wide as last quarter.",
   "I can use the new words: significant, slightly, considerably, roughly, margin, disparity, comparable, ratio, competitive, narrow, outweigh, discrepancy.",
 ],
 'badge_a': "Comparing Data",
 'badge_text': "You can now compare HR data and teams with confidence, Murielle.",
 'next_lesson': "The Best in the Room -- Superlatives",
 # ----- Pre-class -----
 'pc_title': "Bigger, Better, Different -- Comparatives in Global HR",
 'pc_desc': "Comparing HR data and teams with comparative adjectives: short (bigger than), long (more efficient than), irregular (better/worse), and equality (as ... as). New words: significant, slightly, considerably, roughly, margin, disparity, comparable, ratio, competitive, narrow, outweigh, discrepancy.",
 'gic_text': ("Our two regions look very different this quarter. The South region is <strong>bigger than</strong> the North, "
              "but its turnover is <strong>higher</strong>. The North is <strong>more efficient</strong> and retains staff "
              "<strong>better than</strong> the South. The <strong>disparity</strong> between them is <strong>significant</strong>. "
              "Costs are <strong>roughly</strong> the same, so the <strong>margin</strong> in results is <strong>wider than</strong> "
              "the margin in cost. Overall, the North is the <strong>more competitive</strong> model."),
 'gic_quiz': [
   ('1. In "The South region is bigger than the North", what kind of comparison is "bigger"?',
    [("An equality with as ... as.", False), ("A comparative of a short adjective (adj + -er + than).", True), ("A superlative.", False)]),
   ('2. Which phrase uses an irregular comparative?',
    [('"retains staff better than the South"', True), ('"the disparity is significant"', False), ('"roughly the same"', False)]),
   ('3. Why is "more efficient" formed with "more"?',
    [("Because efficient is a long adjective.", True), ("Because it is irregular.", False), ("Because it is plural.", False)]),
 ],
 'gt_title': "Comparative Adjectives",
 'gt_intro': ("Use <strong>comparativos</strong> para comparar duas coisas. Adjetivo <strong>curto</strong>: adjetivo + "
              "<strong>-er + than</strong> (bigger than). Adjetivo <strong>longo</strong>: <strong>more</strong> + adjetivo + "
              "<strong>than</strong> (more efficient than). Irregulares: good &rarr; <strong>better</strong>, bad &rarr; "
              "<strong>worse</strong>. Igualdade: <strong>as</strong> + adjetivo + <strong>as</strong> (as high as)."),
 'gt_head': ["Tipo", "Forma", "Exemplo"],
 'gt_rows': [
   ("Adjetivo curto", "adj + -er + than", "Turnover is higher than last year."),
   ("Adjetivo longo", "more + adj + than", "It is more efficient than before."),
   ("Irregular", "good&rarr;better, bad&rarr;worse", "Results are better than the forecast."),
   ("Igualdade", "as + adj + as", "It is as high as last year."),
 ],
 'gt_note': "Atenção: adjetivos curtos NÃO usam more (não diga more bigger). Adjetivos longos usam more, nunca -er. Better e worse são irregulares.",
 'fill': [
   ('"Our turnover is ', "lower than", "Hint: short adj = adj + -er + than", "Our turnover is lower than last year.", ' last year. (short adj)"'),
   ('"This market is ', "more competitive than", "Hint: long adj = more + adj + than", "This market is more competitive than ours.", ' ours. (long adj)"'),
   ('"Our results are ', "better than", "Hint: good is irregular", "Our results are better than the forecast.", ' the forecast. (irregular)"'),
   ('"The gap is ', "as wide as", "Hint: equality = as + adj + as", "The gap is as wide as last quarter.", ' last quarter. (equality)"'),
   ('"Attrition is ', "slightly higher", "Hint: slightly + comparative", "Attrition is slightly higher this year.", ' this year. (short adj)"'),
   ('"The North is ', "more efficient than", "Hint: long adj = more + adj + than", "The North is more efficient than the South.", ' the South. (long adj)"'),
 ],
 'order_title': "Put the Comparison in Order",
 'order_instr': "Coloque os passos de apresentar uma comparação na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Open: Here is a comparison of our two regions.", 1),
   ("Compare size: The South is bigger than the North.", 2),
   ("Compare results: But the North is more efficient than the South.", 3),
   ("Highlight the gap: The disparity is significant.", 4),
   ("Recommend: The North is the more competitive model.", 5),
 ],
 'speech': [
   ("Our turnover is lower than last year.", "Nossa rotatividade é menor que no ano passado."),
   ("This region is more competitive than the others.", "Esta região é mais competitiva que as outras."),
   ("Our results are better than the forecast.", "Nossos resultados são melhores que a previsão."),
   ("The gap is as wide as last quarter.", "A diferença é tão grande quanto no trimestre passado."),
   ("The disparity between teams is significant.", "A disparidade entre as equipes é significativa."),
 ],
 'sit_quiz': [
   ("You compare two team sizes. You say:",
    [('"Our team is more bigger than theirs."', False), ('"Our team is bigger than theirs."', True), ('"Our team is the biggest than theirs."', False)]),
   ("You compare efficiency. You say:",
    [('"The North is more efficient than the South."', True), ('"The North is efficienter than the South."', False), ('"The North is as efficient than the South."', False)]),
   ("You compare to last year (irregular). You say:",
    [('"Results are gooder than last year."', False), ('"Results are more good than last year."', False), ('"Results are better than last year."', True)]),
   ("You say two numbers are equal. You say:",
    [('"It is as high as last year."', True), ('"It is as higher as last year."', False), ('"It is more high as last year."', False)]),
 ],
 'think': ("Compare two real parts of your HR work: two regions, two teams, or this year versus last year. Make at least "
           "four comparisons and say which one is stronger and why. Use comparatives and at least four new words. Take your time."),
 'survival': [
   ("Our turnover is lower than last year.", "Nossa rotatividade é menor que no ano passado."),
   ("This region is more competitive than the others.", "Esta região é mais competitiva que as outras."),
   ("Our results are better than the forecast.", "Nossos resultados são melhores que a previsão."),
   ("The gap is as wide as last quarter.", "A diferença é tão grande quanto no trimestre passado."),
   ("The difference is significant.", "A diferença é significativa."),
 ],
 'comp_heading': "Bigger, Better, Different -- Comparatives in Global HR",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode comparing teams and organizations",
    "Adam Grant compares how different teams and companies perform. You will hear comparatives used to weigh options and results. Direct connection to Lesson 15: comparing HR data.",
    "write 5 sentences comparing two teams with -er than and more ... than.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene where two cases or offers are compared",
    "Watch a scene where characters weigh two options and argue which is better. Notice comparatives in fast professional speech. Connection to Lesson 15: comparing and recommending.",
    "pause and say: This option is better than the other.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"Comparative Adjectives" -- BBC Learning English',
    "A clear lesson on short, long, and irregular comparatives, and how to use as ... as for equality. Connection to Lesson 15: comparing at work.",
    "pause and build comparisons with bigger, more efficient, and better.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 15. Tema: comparar dados e equipes de RH. Foco B1: comparativos &mdash; adjetivo curto (bigger than), adjetivo longo (more efficient than), irregulares (better/worse) e igualdade (as ... as) + 12 palavras novas. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: dois numeros, duas regioes &mdash; qual e mais forte e por que? Deixe a Murielle responder. NAO corrija ainda; anote se ela usa comparativos.",
   's3': "<strong>Recall da aula 14 (3 min):</strong> Callback do will (ofertas e promessas). Ponte: na aula passada voce ofereceu ajuda; hoje voce compara resultados entre times e regioes.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para comparar dados de RH voce precisa das palavras de medida e diferenca. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: sig-NI-fi-cant, SLIGHT-ly, con-SI-de-ra-bly, ROUGH-ly, MAR-gin, dis-PA-ri-ty. Pergunte: is the gap significant?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: COM-pa-ra-ble, RA-tio, com-PE-ti-tive, NA-rrow, out-WEIGH, dis-CRE-pan-cy. Peca uma frase com cada palavra.",
   's7': "<strong>Comparativos num relance (5 min):</strong> Duas colunas: adjetivo CURTO (+er than) e adjetivo LONGO (more ... than). Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco no som de than e no ritmo de as ... as.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a gramatica &mdash; comparativos curtos, longos e irregulares, mais igualdade com as ... as.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: what do the orange words have in common? CCQ 1: comparing two things? Yes. CCQ 2: short adj adds -er? Yes. CCQ 3: long adj uses more? Yes. So clique Reveal the Rule.",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Erros: (1) more + short adj, (2) gooder em vez de better, (3) more high em vez de higher, (4) as wider as em vez de as wide as.",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz o tipo (short/long/irregular/equality).",
   's13': "<strong>Build the Comparison (3 min):</strong> Peca a frase comparativa completa em voz alta. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan comparando duas regioes antes da reuniao global.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan comparando os numeros de duas regioes. Clique Next Line um de cada vez. Reforce cada comparativo. OBSTACULO: -er than vs more ... than.",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; a manager compares two sites. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora compara este ano com o anterior. OBSTACULO: separar disparity, margin, ratio e discrepancy.",
   's19': "<strong>Artefato (3 min):</strong> Mostre o resumo de comparacao e peca a Murielle para ler cada linha em voz alta usando comparativos.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, as formas e um resumo real. Agora juntamos tudo.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca a comparacao em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Dicas: short or long adjective? irregular? as ... as?",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase comparativa completa em voz alta. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. Compare e recomende.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e Ethan pedindo a comparacao das duas regioes. A Murielle usa os chips. Se travar, de a primeira comparacao. FOCO: comparativos.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle apresenta o benchmark, compara este ano com o anterior e recomenda o modelo mais competitivo.",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle compara dois times, regioes ou anos reais. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros. OBSTACULO: forma do comparativo.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Alterne comparativo curto, longo, irregular e igualdade.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula. Homework: gravar 8-10 frases comparando dois times reais (curto, longo, irregular, as ... as) usando 5 palavras novas. Preview: Next class &mdash; Superlatives.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: great work, Murielle! You can now compare HR data with confidence. Celebre. Preview: Next class &mdash; The Best in the Room, superlatives for executive HR.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
