# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 16,
 'phases': ["Who Is Best", "Top Words", "Superlative Forms", "The Ranking", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1552664730-d307ca884978?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1517245386807-bb43f82c33c4?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "The Best in the", 'title_b': "Room",
 'subtitle1': "Superlatives for executive HR",
 'hook_a': "Who Is the", 'hook_b': "Best?",
 'hook_prompt': "One ranking, one team, one leader stands out. Who is the very best, and how do you say it?",
 'recall_a': "From Comparing to", 'recall_b': "Ranking",
 'recall_text': "Last class you compared two things with comparatives. Today you name the single best of a whole group with superlatives.",
 'recall_chips': ["the biggest", "the most efficient", "the best"],
 'vocab_sub': "The words for the very best in HR",
 'vocab_head1': ("Top and", "Best"),
 'vocab_head2': ("Leading and", "Prestigious"),
 'vocab': [
   ("Outstanding", "extremely good; much better than others", "excepcional / notável", "She is our most outstanding manager."),
   ("Exceptional", "unusually good", "excepcional", "This was an exceptional quarter for the team."),
   ("Leading", "most important or most successful", "líder / principal", "We are the leading employer in the region."),
   ("Remarkable", "so good it deserves attention", "notável / impressionante", "The team made remarkable progress."),
   ("Unmatched", "better than anything else; with no equal", "inigualável / sem igual", "Her track record is unmatched."),
   ("Foremost", "the most important; the best-known", "principal / mais importante", "He is our foremost expert on compliance."),
   ("Prominent", "important and well-known", "proeminente / de destaque", "She is a prominent leader in the company."),
   ("Prestigious", "respected and admired", "prestigioso / de prestígio", "It is the most prestigious award in the sector."),
   ("Flagship", "the best and most important of a group", "carro-chefe / principal", "This is our flagship program."),
   ("Standout", "clearly the best", "destaque", "She was the standout candidate."),
   ("Peak", "the highest point or level", "pico / auge", "Engagement reached its peak this year."),
   ("Utmost", "the greatest possible", "máximo / maior possível", "We treat safety with the utmost care."),
 ],
 'concept_label': "Superlatives at a Glance",
 'concept_a': "Short vs", 'concept_b': "Long",
 'concept_sub': "Use the before every superlative",
 'concept_cols': [
   ("SHORT ADJ (the ...-est)", "high &rarr; the highest, big &rarr; the biggest"),
   ("LONG ADJ (the most ...)", "efficient &rarr; the most efficient, outstanding &rarr; the most outstanding"),
 ],
 'concept_drill': [
   ("Name the region with the highest retention.", "The North has the highest retention."),
   ("Name your most efficient team.", "This is our most efficient team."),
   ("Name the best result (irregular).", "It was the best result of the year."),
   ("Highlight one of the top managers.", "She is one of the most reliable managers."),
 ],
 'pron': [
   "The North is the best region this year.",
   "She is our most outstanding manager.",
   "It has the highest retention rate.",
   "She is one of the most reliable leaders.",
 ],
 'gram_title_a': "Superlative", 'gram_title_b': "Adjectives",
 'gram_title_sub': "The highest, the most efficient, the best",
 'discovery': [
   ('"This is our <span class="accent" style="font-weight:700">most efficient</span> region."', "This is our most efficient region."),
   ('"She has the <span class="accent" style="font-weight:700">highest</span> retention rate."', "She has the highest retention rate."),
   ('"It was the <span class="accent" style="font-weight:700">best</span> quarter of the year."', "It was the best quarter of the year."),
   ('"He is one of the <span class="accent" style="font-weight:700">most reliable</span> managers."', "He is one of the most reliable managers."),
 ],
 'rule_head': ["Type", "Form", "Example"],
 'rule_rows': [
   ("Short adjective", "the + adj + -est", "the highest, the biggest"),
   ("Long adjective", "the most + adj", "the most efficient"),
   ("Irregular", "the best, the worst", "the best result"),
   ("One of the...", "one of the + superlative + plural", "one of the most reliable teams"),
 ],
 'mistakes': [
   ("This is the most biggest region.", "This is the <strong>biggest</strong> region."),
   ("She has the highest-est rate.", "She has the <strong>highest</strong> rate."),
   ("It was the goodest quarter.", "It was the <strong>best</strong> quarter."),
   ("He is most efficient manager.", "He is <strong>the most efficient</strong> manager."),
 ],
 'mistake_note': "Short adjectives take the ...-est. Long adjectives take the most ... Good and bad are irregular: the best, the worst. Always use the before a superlative.",
 'gpr_a': "Complete the", 'gpr_b': "Superlative",
 'gpractice': [
   ('"This is our ', "most efficient", ' region. (long adj)"'),
   ('"She has the ', "highest", ' retention rate. (short adj)"'),
   ('"It was the ', "best", ' quarter of the year. (irregular)"'),
   ('"He is one of the ', "most reliable", ' managers. (one of the...)"'),
   ('"This is the ', "biggest", ' team in the company. (short adj)"'),
 ],
 'build1_label': "Build the Superlative",
 'build1_a': "Name the", 'build1_b': "Best",
 'build1': [
   ("this / be / efficient / region", "This is the most efficient region."),
   ("she / have / high / retention rate", "She has the highest retention rate."),
   ("it / be / good / quarter / of the year", "It was the best quarter of the year."),
   ("he / be / one of / reliable / managers", "He is one of the most reliable managers."),
   ("this / be / big / team / in the company", "This is the biggest team in the company."),
 ],
 'context_sub': "Reviewing a ranking to name the best",
 'dlg_title_a': "The", 'dlg_title_b': "Ranking",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, here is the ranking. Which region is the strongest this year?",
    "Murielle, here is the ranking. Which region is the strongest this year?"),
   ("M", "#86198F", "murielle", "ellen",
    "The North is our best region by far. It has the highest retention and the lowest turnover.",
    "The North is our best region by far. It has the highest retention and the lowest turnover."),
   ("E", "#1b4965", "ethan", "arthur",
    "And the weakest?",
    "And the weakest?"),
   ("M", "#86198F", "murielle", "ellen",
    'The South is the weakest, but it made the most <span class="vocab-highlight">remarkable</span> progress of all.',
    "The South is the weakest, but it made the most remarkable progress of all."),
   ("E", "#1b4965", "ethan", "arthur",
    'Good point. Who is your <span class="vocab-highlight">standout</span> manager?',
    "Good point. Who is your standout manager?"),
   ("M", "#86198F", "murielle", "ellen",
    'Diana. She is our most <span class="vocab-highlight">outstanding</span> leader, and her track record is <span class="vocab-highlight">unmatched</span>.',
    "Diana. She is our most outstanding leader, and her track record is unmatched."),
   ("E", "#1b4965", "ethan", "arthur",
    'So Diana wins the most <span class="vocab-highlight">prestigious</span> award this year?',
    "So Diana wins the most prestigious award this year?"),
   ("M", "#86198F", "murielle", "ellen",
    'Yes. She is the <span class="vocab-highlight">foremost</span> example of what our best teams can do.',
    "Yes. She is the foremost example of what our best teams can do."),
 ],
 'dlg_comp': [
   ("Which region is the strongest, and why?", "The North; it has the highest retention and the lowest turnover."),
   ("Which region made the most remarkable progress?", "The South, even though it is the weakest."),
   ("Why does Diana win the award?", "She is the most outstanding leader and her track record is unmatched."),
 ],
 'listenings': [
   {"title_a": "The", "title_b": "Results", "file": "a16_listening_results.mp3", "voice": "arthur",
    "text": ("Good afternoon. Let me share this year's ranking. The North is our strongest region, with the highest "
             "retention and the lowest turnover in the whole company. It is also our most cost-effective site. The "
             "South is the weakest region overall, but it made the most remarkable progress of all. Our most "
             "outstanding manager this year is Diana; her results are simply unmatched. She leads our flagship "
             "program and sets the highest standard. In short, the North is the best model, and Diana is the "
             "standout leader. Congratulations to everyone."),
    "qs": [
      ("Which is the strongest region?", "The North, with the highest retention and the lowest turnover."),
      ("What is special about the South?", "It is the weakest overall but made the most remarkable progress."),
      ("Why is Diana the standout leader?", "Her results are unmatched; she leads the flagship program and sets the highest standard."),
    ]},
   {"title_a": "The", "title_b": "Award", "file": "a16_listening_award.mp3", "voice": "ellen",
    "text": ("Hello everyone. It is my great honour to present the most prestigious award of the year. This award "
             "goes to the most outstanding leader in our company. This year, the winner set the highest standard in "
             "engagement and delivered the best results of any team. Her department is the leading example of what "
             "we can achieve, and her commitment is unmatched. She is one of the most reliable and most respected "
             "managers we have. She is, without doubt, our foremost talent. Please join me in congratulating this "
             "remarkable leader."),
    "qs": [
      ("What kind of award is it?", "The most prestigious award of the year."),
      ("What did the winner achieve?", "She set the highest standard in engagement and delivered the best results of any team."),
      ("How is the winner described?", "As one of the most reliable and respected managers, and the foremost talent."),
    ]},
 ],
 'art_title_a': "Award", 'art_title_b': "Certificate",
 'art_kicker': "Recognition &middot; Minerva Foods HR",
 'art_subtitle': "Employee of the Year -- Recognition",
 'art_lines': [
   "The North is the strongest region this year.",
   "Diana is our most outstanding manager.",
   "Her track record is unmatched.",
   "She leads our most prestigious program.",
 ],
 'art_sign': "Approved by: Murielle Xavier",
 'art_note': "Read each line aloud: The North is the strongest region this year.",
 'quickfire': [
   ("Say which region is the best.", "The North is the best region this year."),
   ("Say which manager is the most outstanding.", "Diana is our most outstanding manager."),
   ("Say who has the highest retention.", "The North has the highest retention rate."),
   ("Give an opinion using one of the...", "She is one of the most reliable managers we have."),
   ("Name the most prestigious award.", "This is the most prestigious award of the year."),
 ],
 'spot': [
   ("This is the most biggest region.", "This is the biggest region. (no most with short adjectives)"),
   ("She has the highest-est rate.", "She has the highest rate. (add -est only once)"),
   ("It was the goodest quarter.", "It was the best quarter. (good is irregular: the best)"),
   ("He is most efficient manager.", "He is the most efficient manager. (use the before a superlative)"),
 ],
 'build2': [
   ("the North / be / strong / region", "The North is the strongest region."),
   ("Diana / be / outstanding / manager", "Diana is the most outstanding manager."),
   ("this / be / good / result / of the year", "This is the best result of the year."),
   ("she / have / high / retention rate", "She has the highest retention rate."),
   ("he / be / one of / reliable / leaders", "He is one of the most reliable leaders."),
 ],
 'production_sub': "From guided to free. Name the best and celebrate.",
 'roleplays': {
   'guided': {'h': ("Present the", "Ranking"),
     'scenario': "Ethan asks: Who is the best this year? Present the ranking. Name the strongest region, the highest retention, and your most outstanding manager. Use at least three superlatives.",
     'chips': ["the best / the strongest", "the most outstanding", "one of the...", "unmatched"]},
   'semi': {'h': ("Give the", "Award"),
     'scenario': "Present the employee of the year award to your team. Say why the winner is the most outstanding leader, and describe her most prestigious achievements.",
     'chips': ["prestigious", "leading", "standout"]},
   'free': {'h': ("Your Own", "Rankings"),
     'scenario': "Talk about the best in your own HR world: the best team, the top performer, or the most successful project. Use at least four superlatives and say why each one is the best.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "The North is the best region this year.",
   "Diana is our most outstanding manager.",
   "She has the highest retention rate.",
   "She is one of the most reliable leaders.",
   "This is the most prestigious award.",
 ],
 'checklist': [
   "I can form superlatives with short adjectives: the highest, the biggest.",
   "I can form superlatives with long adjectives: the most efficient, the most outstanding.",
   "I can use irregular superlatives: the best and the worst.",
   "I can use one of the + superlative + plural noun: one of the most reliable leaders.",
   "I can use the new words: outstanding, exceptional, leading, remarkable, unmatched, foremost, prominent, prestigious, flagship, standout, peak, utmost.",
 ],
 'badge_a': "The Best in the Room",
 'badge_text': "You can now describe the very best in HR with confidence, Murielle.",
 'next_lesson': "How Much, How Many -- Quantifiers",
 # ----- Pre-class -----
 'pc_title': "The Best in the Room -- Superlatives for Executive HR",
 'pc_desc': "Naming the very best of a group with superlative adjectives: short (the highest), long (the most efficient), irregular (the best/the worst), and one of the + superlative. New words: outstanding, exceptional, leading, remarkable, unmatched, foremost, prominent, prestigious, flagship, standout, peak, utmost.",
 'gic_text': ("This year's ranking is clear. The North is our <strong>best</strong> region, with the <strong>highest</strong> "
              "retention and the <strong>lowest</strong> turnover. It is also our <strong>most efficient</strong> site. The "
              "South is the <strong>weakest</strong> region, but it made the <strong>most remarkable</strong> progress of all. "
              "Diana is our <strong>most outstanding</strong> manager; her track record is <strong>unmatched</strong>. She "
              "leads our <strong>most prestigious</strong> program and is one of the <strong>most reliable</strong> leaders we have."),
 'gic_quiz': [
   ('1. In "the highest retention rate", what form is "highest"?',
    [("A comparative.", False), ("A superlative of a short adjective (the + adj + -est).", True), ("An equality.", False)]),
   ('2. Which phrase uses an irregular superlative?',
    [('"the North is our best region"', True), ('"the most remarkable progress"', False), ('"the lowest turnover"', False)]),
   ('3. Why is "most outstanding" formed with "most"?',
    [("Because outstanding is a long adjective.", True), ("Because it is irregular.", False), ("Because it is plural.", False)]),
 ],
 'gt_title': "Superlative Adjectives",
 'gt_intro': ("Use <strong>superlativos</strong> para o melhor ou o pior de um grupo. Adjetivo <strong>curto</strong>: "
              "<strong>the</strong> + adjetivo + <strong>-est</strong> (the highest). Adjetivo <strong>longo</strong>: "
              "<strong>the most</strong> + adjetivo (the most efficient). Irregulares: good &rarr; <strong>the best</strong>, "
              "bad &rarr; <strong>the worst</strong>. Use sempre <strong>the</strong> antes do superlativo."),
 'gt_head': ["Tipo", "Forma", "Exemplo"],
 'gt_rows': [
   ("Adjetivo curto", "the + adj + -est", "The North has the highest retention."),
   ("Adjetivo longo", "the most + adj", "She is the most efficient manager."),
   ("Irregular", "the best / the worst", "It was the best quarter of the year."),
   ("Um dos melhores", "one of the + superlative + plural", "She is one of the most reliable leaders."),
 ],
 'gt_note': "Atenção: adjetivos curtos usam -est (não the most big). Adjetivos longos usam the most, nunca -est. Sempre use the antes do superlativo.",
 'fill': [
   ('"The North is our ', "best", "Hint: good is irregular: the best", "The North is our best region.", ' region. (irregular)"'),
   ('"She has the ', "highest", "Hint: short adj = the + adj + -est", "She has the highest retention rate.", ' retention rate. (short adj)"'),
   ('"He is the ', "most efficient", "Hint: long adj = the most + adj", "He is the most efficient manager.", ' manager. (long adj)"'),
   ('"It was the ', "worst", "Hint: bad is irregular: the worst", "It was the worst month of the year.", ' month of the year. (irregular)"'),
   ('"She is one of the ', "most reliable", "Hint: one of the + superlative", "She is one of the most reliable leaders.", ' leaders. (one of the...)"'),
   ('"This is the ', "biggest", "Hint: short adj + -est", "This is the biggest team in the company.", ' team in the company. (short adj)"'),
 ],
 'order_title': "Put the Ranking in Order",
 'order_instr': "Coloque os passos de apresentar um ranking na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Open: Here is this year's ranking.", 1),
   ("Name the best region: The North is our best region.", 2),
   ("Give the top metric: It has the highest retention.", 3),
   ("Name the standout manager: Diana is our most outstanding leader.", 4),
   ("Announce the award: She wins the most prestigious award.", 5),
 ],
 'speech': [
   ("The North is the best region this year.", "A região Norte é a melhor região este ano."),
   ("She is our most outstanding manager.", "Ela é a nossa gerente mais excepcional."),
   ("It has the highest retention rate.", "Tem a maior taxa de retenção."),
   ("She is one of the most reliable leaders.", "Ela é uma das líderes mais confiáveis."),
   ("This is the most prestigious award.", "Este é o prêmio mais prestigioso."),
 ],
 'sit_quiz': [
   ("You name the top region (short adjective). You say:",
    [('"This is the most biggest region."', False), ('"This is the biggest region."', True), ('"This is a bigger region."', False)]),
   ("You name your top manager (long adjective). You say:",
    [('"She is the most outstanding manager."', True), ('"She is the outstandingest manager."', False), ('"She is more outstanding manager."', False)]),
   ("You name the top result (irregular). You say:",
    [('"It was the goodest result."', False), ('"It was the most good result."', False), ('"It was the best result."', True)]),
   ("You highlight one top leader. You say:",
    [('"She is one of the most reliable leaders."', True), ('"She is one of the most reliablest leaders."', False), ('"She is one the most reliable leader."', False)]),
 ],
 'think': ("Talk about the best in your own HR world: your best team, your top performer, and your most successful "
           "project. Use at least four superlatives and say why each one is the best. Use at least four new words. Take your time."),
 'survival': [
   ("The North is the best region this year.", "A região Norte é a melhor região este ano."),
   ("She is our most outstanding manager.", "Ela é a nossa gerente mais excepcional."),
   ("It has the highest retention rate.", "Tem a maior taxa de retenção."),
   ("She is one of the most reliable leaders.", "Ela é uma das líderes mais confiáveis."),
   ("This is the most prestigious award.", "Este é o prêmio mais prestigioso."),
 ],
 'comp_heading': "The Best in the Room -- Superlatives for Executive HR",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode on top performers and the best teams",
    "Adam Grant explores what makes the best teams and the most outstanding people stand out. You will hear superlatives used to describe the very best. Direct connection to Lesson 16: naming the best in HR.",
    "write 5 sentences with the best, the highest, and the most outstanding.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene where the best lawyer or the top firm is named",
    "Watch a scene where a character is called the best in the business. Notice superlatives in confident professional speech. Connection to Lesson 16: naming the standout performer.",
    "pause and say: She is the most outstanding leader here.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"Superlative Adjectives" -- BBC Learning English',
    "A clear lesson on short, long, and irregular superlatives, and how to use one of the + superlative. Connection to Lesson 16: describing the very best at work.",
    "pause and build superlatives with the highest, the most efficient, and the best.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 16. Tema: nomear o melhor de um grupo em RH. Foco B1: superlativos &mdash; adjetivo curto (the highest), longo (the most efficient), irregulares (the best/the worst) e one of the + superlativo + 12 palavras novas. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: num ranking, quem se destaca como o melhor de todos? Deixe a Murielle responder. NAO corrija ainda; anote se ela usa the + superlativo.",
   's3': "<strong>Recall da aula 15 (3 min):</strong> Callback dos comparativos (bigger than, more efficient than). Ponte: na aula passada voce comparou DUAS coisas; hoje voce nomeia O MELHOR de um grupo inteiro.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para falar do melhor de todos voce precisa das palavras de destaque e excelencia. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: out-STAN-ding, ex-CEP-tio-nal, LEA-ding, re-MAR-ka-ble, un-MATCHED, FORE-most. Pergunte: who is our most outstanding manager?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: PRO-mi-nent, pres-TI-gious, FLAG-ship, STAND-out, PEAK, UT-most. Peca uma frase com cada palavra.",
   's7': "<strong>Superlativos num relance (5 min):</strong> Duas colunas: adjetivo CURTO (the ...-est) e adjetivo LONGO (the most ...). Sempre THE. Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco no the antes do superlativo e no som de -est.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a gramatica &mdash; superlativos curtos, longos e irregulares, sempre com the.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: what do the orange words have in common? CCQ 1: best of a group? Yes. CCQ 2: short adj adds -est? Yes. CCQ 3: is there always the? Yes. So clique Reveal the Rule.",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Erros: (1) most + short adj, (2) -est duplicado, (3) goodest em vez de the best, (4) faltou the antes do superlativo.",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz o tipo (short/long/irregular/one of the).",
   's13': "<strong>Build the Superlative (3 min):</strong> Peca a frase superlativa completa em voz alta. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan revisando o ranking do ano para nomear os melhores.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan revisando o ranking. Clique Next Line um de cada vez. Reforce cada superlativo. OBSTACULO: the antes do superlativo e formas irregulares.",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; a manager announces the ranking. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora anuncia o premio mais prestigioso do ano. OBSTACULO: separar os varios superlativos.",
   's19': "<strong>Artefato (3 min):</strong> Mostre o certificado e peca a Murielle para ler cada linha em voz alta usando superlativos.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, as formas e um certificado real. Agora juntamos tudo.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca o superlativo em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Dicas: short or long adjective? irregular? is there the?",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase superlativa completa em voz alta. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. Nomeie os melhores e celebre.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e Ethan pedindo o ranking do ano. A Murielle usa os chips. Se travar, de o primeiro superlativo. FOCO: the + superlativo.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle entrega o premio de funcionario do ano e explica por que a vencedora e a mais excepcional.",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle fala dos melhores do proprio mundo de RH. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros. OBSTACULO: forma do superlativo.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Alterne superlativo curto, longo, irregular e one of the.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula. Homework: gravar 8-10 frases nomeando os melhores de um grupo real (curto, longo, irregular, one of the) usando 5 palavras novas. Preview: Next class &mdash; Quantifiers.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: great work, Murielle! You can now name the very best with confidence. Celebre. Preview: Next class &mdash; How Much, How Many, quantifiers for HR data.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
