# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 17,
 'phases': ["How Much How Many", "Amount Words", "Quantifier Forms", "The Numbers", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1554224155-6726b3ff858f?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1543286386-713bdd548da4?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "How Much,", 'title_b': "How Many",
 'subtitle1': "Talking about HR data with quantifiers",
 'hook_a': "How Much,", 'hook_b': "How Many?",
 'hook_prompt': "Roles, budget, candidates, time. How do you say what you have too much of and not enough of?",
 'recall_a': "From the Best to", 'recall_b': "How Many",
 'recall_text': "Last class you named the best of a group with superlatives. Today you talk about amounts and numbers: how much and how many.",
 'recall_chips': ["many roles", "much budget", "a few candidates"],
 'vocab_sub': "The words for amounts and quantities",
 'vocab_head1': ("Plenty and", "Scarce"),
 'vocab_head2': ("Bulk and", "Enough"),
 'vocab': [
   ("Plenty", "more than enough", "de sobra / bastante", "We have plenty of candidates for the role."),
   ("Scarce", "not enough; hard to find", "escasso", "Skilled staff is scarce this year."),
   ("Abundant", "existing in large quantities", "abundante", "Feedback was abundant after the survey."),
   ("Numerous", "many; a large number", "numerosos / diversos", "We received numerous applications."),
   ("Minimal", "very small in amount", "mínimo", "The budget increase was minimal."),
   ("Ample", "more than enough; plenty", "amplo / suficiente", "We have ample time to prepare."),
   ("Surplus", "an extra amount left over", "excedente / sobra", "There is a surplus of applications."),
   ("Insufficient", "not enough", "insuficiente", "The staff is insufficient for the workload."),
   ("Countless", "too many to count", "incontáveis", "We answered countless questions."),
   ("Handful", "a small number", "punhado / poucos", "Only a handful of candidates applied."),
   ("Bulk", "the largest part of something", "maior parte / grosso", "The bulk of the budget goes to salaries."),
   ("Sufficient", "enough for a purpose", "suficiente", "We have sufficient data to decide."),
 ],
 'concept_label': "Countable vs Uncountable",
 'concept_a': "Much vs", 'concept_b': "Many",
 'concept_sub': "Can you count it? That tells you the word",
 'concept_cols': [
   ("COUNTABLE (many, a few)", "candidates, roles, meetings, teams"),
   ("UNCOUNTABLE (much, a little)", "data, budget, time, feedback, overtime"),
 ],
 'concept_drill': [
   ("Talk about the number of open roles.", "We have many open roles."),
   ("Talk about the amount of budget.", "We do not have much budget."),
   ("Talk about a small number of candidates.", "We have a few candidates."),
   ("Talk about a small amount of time.", "We have a little time."),
 ],
 'pron': [
   "We have many open roles this quarter.",
   "We do not have much budget.",
   "We have a few qualified candidates.",
   "There is too much overtime this month.",
 ],
 'gram_title_a': "How Much,", 'gram_title_b': "How Many",
 'gram_title_sub': "Much, many, a little, a few",
 'discovery': [
   ('"We have <span class="accent" style="font-weight:700">many</span> vacancies but <span class="accent" style="font-weight:700">little</span> budget."', "We have many vacancies but little budget."),
   ('"There is <span class="accent" style="font-weight:700">too much</span> overtime this month."', "There is too much overtime this month."),
   ('"We have <span class="accent" style="font-weight:700">a few</span> candidates and <span class="accent" style="font-weight:700">not enough</span> time."', "We have a few candidates and not enough time."),
   ('"We received <span class="accent" style="font-weight:700">a lot of</span> feedback."', "We received a lot of feedback."),
 ],
 'rule_head': ["Noun type", "Quantifiers", "Example"],
 'rule_rows': [
   ("Countable (plural)", "many / a few / few", "many candidates, a few roles"),
   ("Uncountable", "much / a little / little", "much data, a little time"),
   ("Both", "a lot of / plenty of", "a lot of feedback"),
   ("Excess / lack", "too much / too many / not enough", "too many meetings, not enough staff"),
 ],
 'mistakes': [
   ("We have much vacancies.", "We have <strong>many</strong> vacancies."),
   ("There is many overtime.", "There is <strong>much</strong> overtime."),
   ("We have a few budget.", "We have <strong>a little</strong> budget."),
   ("We do not have enough of staff.", "We do not have <strong>enough staff</strong>."),
 ],
 'mistake_note': "Use many / a few with countable nouns (candidates). Use much / a little with uncountable nouns (budget, time). Enough goes before the noun, with no of: enough staff.",
 'gpr_a': "Complete the", 'gpr_b': "Quantity",
 'gpractice': [
   ('"We have ', "many", ' open roles this quarter. (countable)"'),
   ('"We do not have ', "much", ' budget. (uncountable)"'),
   ('"We have ', "a few", ' qualified candidates. (countable)"'),
   ('"We have ', "a little", ' time before the deadline. (uncountable)"'),
   ('"There is ', "too much", ' overtime this month. (excess)"'),
 ],
 'build1_label': "Build the Quantity",
 'build1_a': "Count or", 'build1_b': "Measure",
 'build1': [
   ("we / have / many / open roles", "We have many open roles."),
   ("we / not have / much / budget", "We do not have much budget."),
   ("we / have / a few / qualified candidates", "We have a few qualified candidates."),
   ("there / be / too much / overtime", "There is too much overtime."),
   ("we / have / plenty of / data", "We have plenty of data."),
 ],
 'context_sub': "Reviewing staffing quantities with the team",
 'dlg_title_a': "The", 'dlg_title_b': "Numbers",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, how many vacancies do we have this quarter?",
    "Murielle, how many vacancies do we have this quarter?"),
   ("M", "#86198F", "murielle", "ellen",
    "We have many vacancies, but we do not have much budget to fill them.",
    "We have many vacancies, but we do not have much budget to fill them."),
   ("E", "#1b4965", "ethan", "arthur",
    "How much time do we have before the deadline?",
    "How much time do we have before the deadline?"),
   ("M", "#86198F", "murielle", "ellen",
    "Only a little time. We have a few weeks, not enough for a full search.",
    "Only a little time. We have a few weeks, not enough for a full search."),
   ("E", "#1b4965", "ethan", "arthur",
    "Do we have enough candidates in the pipeline?",
    "Do we have enough candidates in the pipeline?"),
   ("M", "#86198F", "murielle", "ellen",
    'We have <span class="vocab-highlight">plenty</span> of candidates, but only a <span class="vocab-highlight">handful</span> are qualified.',
    "We have plenty of candidates, but only a handful are qualified."),
   ("E", "#1b4965", "ethan", "arthur",
    "And feedback from the managers?",
    "And feedback from the managers?"),
   ("M", "#86198F", "murielle", "ellen",
    'We received <span class="vocab-highlight">numerous</span> comments. The <span class="vocab-highlight">bulk</span> of them ask for more staff.',
    "We received numerous comments. The bulk of them ask for more staff."),
 ],
 'dlg_comp': [
   ("How much budget does the team have?", "Not much; they do not have much budget to fill the vacancies."),
   ("How much time is left before the deadline?", "Only a little; a few weeks, not enough for a full search."),
   ("What do most of the manager comments ask for?", "The bulk of them ask for more staff."),
 ],
 'listenings': [
   {"title_a": "The", "title_b": "Staffing", "file": "a17_listening_staffing.mp3", "voice": "arthur",
    "text": ("Good morning. Let me review our staffing numbers. We have many open roles this quarter, but not "
             "enough recruiters to fill them. There is too much overtime, and morale is low. We received numerous "
             "applications, yet only a handful are qualified. Skilled talent is scarce, and our budget is minimal. "
             "Still, we have plenty of internal candidates, and we have sufficient data to plan well. The bulk of "
             "our effort will go to the busiest teams. With a little patience, I am confident we will close most of "
             "the roles."),
    "qs": [
      ("Why is there too much overtime?", "Because there are many open roles but not enough recruiters."),
      ("How many applicants are qualified?", "Only a handful, even though there were numerous applications."),
      ("What will the bulk of the effort go to?", "The busiest teams."),
    ]},
   {"title_a": "The", "title_b": "Budget", "file": "a17_listening_budget.mp3", "voice": "ellen",
    "text": ("Hello team. Let me talk about the budget. We do not have much money this year; the increase was "
             "minimal. We have a few priorities, so we must spend carefully. There is a surplus of low-priority "
             "requests, but insufficient funds for all of them. The bulk of the budget goes to salaries, and only a "
             "little is left for training. We have ample data to guide our choices, and plenty of good ideas. If we "
             "focus on a few key areas, we will have enough to make a real difference. Thank you."),
    "qs": [
      ("How big was the budget increase?", "Minimal; there is not much money this year."),
      ("Where does the bulk of the budget go?", "To salaries, with only a little left for training."),
      ("What is the advice for the money?", "Focus on a few key areas so there is enough to make a difference."),
    ]},
 ],
 'art_title_a': "Headcount", 'art_title_b': "Snapshot",
 'art_kicker': "HR Snapshot &middot; Minerva Foods",
 'art_subtitle': "Q3 Headcount and Budget",
 'art_lines': [
   "We have many open roles and few recruiters.",
   "There is too much overtime this quarter.",
   "We have a little budget and plenty of candidates.",
   "We have sufficient data to plan the next hires.",
 ],
 'art_sign': "Prepared by: Murielle Xavier",
 'art_note': "Read each line aloud: We have many open roles and few recruiters.",
 'quickfire': [
   ("Say you have many open roles.", "We have many open roles this quarter."),
   ("Say you do not have much budget.", "We do not have much budget."),
   ("Say there are a few qualified candidates.", "We have a few qualified candidates."),
   ("Say there is too much overtime.", "There is too much overtime this month."),
   ("Say you have enough data to decide.", "We have enough data to decide."),
 ],
 'spot': [
   ("We have much vacancies.", "We have many vacancies. (vacancies is countable: many)"),
   ("There is many overtime.", "There is much overtime. (overtime is uncountable: much)"),
   ("We have a few budget.", "We have a little budget. (budget is uncountable: a little)"),
   ("We do not have enough of staff.", "We do not have enough staff. (enough + noun, no of)"),
 ],
 'build2': [
   ("we / have / many / open roles", "We have many open roles."),
   ("there / be / not much / budget", "There is not much budget."),
   ("we / have / a few / qualified candidates", "We have a few qualified candidates."),
   ("there / be / too much / overtime", "There is too much overtime."),
   ("we / have / plenty of / data", "We have plenty of data."),
 ],
 'production_sub': "From guided to free. Report the numbers.",
 'roleplays': {
   'guided': {'h': ("Report the", "Numbers"),
     'scenario': "Ethan asks: How many roles and how much budget do we have? Report the quantities: open roles, budget, candidates, and overtime. Use many, much, a few, and a little.",
     'chips': ["many / much", "a few / a little", "not enough", "plenty of"]},
   'semi': {'h': ("Talk About the", "Budget"),
     'scenario': "Present the budget to Ethan. Say how much money you have, how many priorities there are, and where the bulk of the budget goes.",
     'chips': ["surplus", "insufficient", "sufficient"]},
   'free': {'h': ("Your Own", "Quantities"),
     'scenario': "Talk about the quantities in your own HR work: headcount, budget, applications, or workload. Use many, much, a few, a little, and the new words to describe what you have too much of and not enough of.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "We have many open roles this quarter.",
   "We do not have much budget.",
   "We have a few qualified candidates.",
   "There is too much overtime.",
   "We have enough data to decide.",
 ],
 'checklist': [
   "I can use many and a few with countable nouns: many roles, a few candidates.",
   "I can use much and a little with uncountable nouns: much budget, a little time.",
   "I can use a lot of and plenty of with both countable and uncountable nouns.",
   "I can talk about excess and lack: too much, too many, not enough.",
   "I can use the new words: plenty, scarce, abundant, numerous, minimal, ample, surplus, insufficient, countless, handful, bulk, sufficient.",
 ],
 'badge_a': "How Much, How Many",
 'badge_text': "You can now talk about HR quantities with confidence, Murielle.",
 'next_lesson': "Something Was Happening -- Past Continuous",
 # ----- Pre-class -----
 'pc_title': "How Much, How Many -- Quantifiers for HR Data",
 'pc_desc': "Talking about amounts and numbers with quantifiers: many / a few (countable), much / a little (uncountable), a lot of / plenty of (both), and too much / too many / not enough. New words: plenty, scarce, abundant, numerous, minimal, ample, surplus, insufficient, countless, handful, bulk, sufficient.",
 'gic_text': ("This quarter we have <strong>many</strong> open roles but not <strong>much</strong> budget. We have "
              "<strong>a few</strong> recruiters and <strong>a little</strong> time before the deadline. There is "
              "<strong>too much</strong> overtime, and morale is low. We received <strong>numerous</strong> applications, "
              "but only a <strong>handful</strong> are qualified. Skilled talent is <strong>scarce</strong>. Still, we have "
              "<strong>plenty of</strong> internal candidates and <strong>sufficient</strong> data to plan. The "
              "<strong>bulk</strong> of our effort will go to the busiest teams."),
 'gic_quiz': [
   ('1. Why do we say "many open roles" and not "much open roles"?',
    [("Because roles are countable.", True), ("Because roles are uncountable.", False), ("Because roles are a plural verb.", False)]),
   ('2. Which noun is uncountable?',
    [("budget", True), ("recruiters", False), ("applications", False)]),
   ('3. What does "a handful" mean here?',
    [("A large number.", False), ("A small number.", True), ("Zero.", False)]),
 ],
 'gt_title': "Quantifiers (Much / Many)",
 'gt_intro': ("Use quantifiers para falar de quantidade. Substantivos <strong>contáveis</strong> (plural): "
              "<strong>many, a few, few</strong> (many roles). Substantivos <strong>incontáveis</strong>: "
              "<strong>much, a little, little</strong> (much data). Para ambos: <strong>a lot of, plenty of</strong>. "
              "Excesso ou falta: <strong>too much / too many / not enough</strong>."),
 'gt_head': ["Tipo de substantivo", "Quantifiers", "Exemplo"],
 'gt_rows': [
   ("Contável (plural)", "many / a few / few", "We have many candidates."),
   ("Incontável", "much / a little / little", "We have a little time."),
   ("Ambos", "a lot of / plenty of", "We have plenty of feedback."),
   ("Excesso / falta", "too much / too many / not enough", "There is too much overtime."),
 ],
 'gt_note': "Atenção: many/a few para o que se conta (candidates); much/a little para o que não se conta (budget, time). Enough vem antes do substantivo, sem of: enough staff.",
 'fill': [
   ('"We have ', "many", "Hint: countable = many", "We have many open roles this quarter.", ' open roles this quarter. (countable)"'),
   ('"We do not have ', "much", "Hint: uncountable = much", "We do not have much budget.", ' budget. (uncountable)"'),
   ('"We have ', "a few", "Hint: small number, countable", "We have a few qualified candidates.", ' qualified candidates. (countable)"'),
   ('"We have ', "a little", "Hint: small amount, uncountable", "We have a little time before the deadline.", ' time before the deadline. (uncountable)"'),
   ('"There is ', "too much", "Hint: excess, uncountable", "There is too much overtime this month.", ' overtime this month. (excess)"'),
   ('"We do not have ', "enough", "Hint: enough + noun, no of", "We do not have enough staff.", ' staff. (lack)"'),
 ],
 'order_title': "Put the Report in Order",
 'order_instr': "Coloque os passos de reportar as quantidades na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Open: Here are our staffing numbers.", 1),
   ("Report roles: We have many open roles.", 2),
   ("Report budget: But we do not have much budget.", 3),
   ("Report candidates: We have plenty of candidates, but only a handful are qualified.", 4),
   ("Conclude: We have sufficient data to plan the next hires.", 5),
 ],
 'speech': [
   ("We have many open roles this quarter.", "Temos muitas vagas abertas neste trimestre."),
   ("We do not have much budget.", "Não temos muito orçamento."),
   ("We have a few qualified candidates.", "Temos alguns candidatos qualificados."),
   ("There is too much overtime.", "Há hora extra demais."),
   ("We have enough data to decide.", "Temos dados suficientes para decidir."),
 ],
 'sit_quiz': [
   ("You talk about the number of roles. You say:",
    [('"We have much roles."', False), ('"We have many roles."', True), ('"We have a little roles."', False)]),
   ("You talk about the amount of budget. You say:",
    [('"We have many budget."', False), ('"We have much budget."', True), ('"We have a few budget."', False)]),
   ("You talk about a small number of candidates. You say:",
    [('"We have a little candidates."', False), ('"We have a few candidates."', True), ('"We have much candidates."', False)]),
   ("You talk about a lack of staff. You say:",
    [('"We do not have enough staff."', True), ('"We do not have enough of staff."', False), ('"We do not have many enough staff."', False)]),
 ],
 'think': ("Talk about the quantities in your own HR work: your headcount, budget, applications, or workload. Say what "
           "you have too much of and not enough of. Use many, much, a few, a little, and at least four new words. Take your time."),
 'survival': [
   ("We have many open roles this quarter.", "Temos muitas vagas abertas neste trimestre."),
   ("We do not have much budget.", "Não temos muito orçamento."),
   ("We have a few qualified candidates.", "Temos alguns candidatos qualificados."),
   ("There is too much overtime.", "Há hora extra demais."),
   ("We have enough data to decide.", "Temos dados suficientes para decidir."),
 ],
 'comp_heading': "How Much, How Many -- Quantifiers for HR Data",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode on workload and doing too much",
    "Adam Grant discusses having too much work and not enough time. You will hear quantifiers used to talk about amounts. Direct connection to Lesson 17: talking about HR quantities.",
    "write 5 sentences with many, much, a few, and a little about your workload.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene about too many cases and not enough time",
    "Watch a scene where the team has too much work and too few people. Notice quantifiers in fast professional speech. Connection to Lesson 17: talking about workload and resources.",
    "pause and say: We have too many cases and not enough time.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"Much, Many, A Lot Of" -- BBC Learning English',
    "A clear lesson on countable and uncountable nouns and how to use much, many, a little, and a few. Connection to Lesson 17: talking about data and quantities at work.",
    "pause and build sentences with many roles and much budget.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 17. Tema: falar de quantidades em RH. Foco B1: quantifiers &mdash; many/a few (contaveis), much/a little (incontaveis), a lot of/plenty of, too much/too many/not enough + 12 palavras novas. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: vagas, orcamento, candidatos, tempo &mdash; do que voce tem demais e do que falta? Deixe a Murielle responder. NAO corrija ainda; anote se ela usa much/many corretamente.",
   's3': "<strong>Recall da aula 16 (3 min):</strong> Callback dos superlativos (the best, the highest). Ponte: na aula passada voce nomeou o melhor; hoje voce fala de QUANTIDADE: quanto e quantos.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para falar de quantidades voce precisa das palavras de muito, pouco e o suficiente. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: PLEN-ty, SCARCE, a-BUN-dant, NU-me-rous, MI-ni-mal, AM-ple. Pergunte: do we have plenty of candidates?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: SUR-plus, in-su-FFI-cient, COUNT-less, HAND-ful, BULK, su-FFI-cient. Peca uma frase com cada palavra.",
   's7': "<strong>Contavel vs Incontavel (5 min):</strong> Duas colunas: CONTAVEL (many, a few) e INCONTAVEL (much, a little). Pergunta-chave: can you count it? Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco na diferenca much/many e no ritmo de too much / not enough.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a gramatica &mdash; quantifiers para contaveis e incontaveis, e para excesso e falta.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: why many here but much there? CCQ 1: can you count roles? Yes -> many. CCQ 2: can you count budget? No -> much. CCQ 3: enough needs of? No. So clique Reveal the Rule.",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Erros: (1) much com contavel, (2) many com incontavel, (3) a few com incontavel, (4) enough of + substantivo.",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz contavel/incontavel/excesso.",
   's13': "<strong>Build the Quantity (3 min):</strong> Peca a frase completa em voz alta com o quantifier certo. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan revisando as quantidades de staffing do trimestre.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan revisando os numeros. Clique Next Line um de cada vez. Reforce cada quantifier. OBSTACULO: much vs many e a little vs a few.",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; a manager reviews staffing numbers. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora fala do orcamento. OBSTACULO: separar surplus, insufficient e sufficient.",
   's19': "<strong>Artefato (3 min):</strong> Mostre o snapshot de headcount e peca a Murielle para ler cada linha em voz alta usando quantifiers.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, as regras e um snapshot real. Agora juntamos tudo.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca a frase com quantifier em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Dicas: countable or uncountable? much or many? enough + noun?",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase completa em voz alta com o quantifier certo. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. Reporte os numeros.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e Ethan pedindo o relatorio de quantidades. A Murielle usa os chips. Se travar, de o primeiro quantifier. FOCO: much/many e a little/a few.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle apresenta o orcamento: quanto tem, quantas prioridades e para onde vai o grosso do dinheiro.",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle fala das quantidades do proprio RH. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros. OBSTACULO: much vs many.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Alterne much, many, a few, a little e enough.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula. Homework: gravar 8-10 frases sobre quantidades reais de RH (much, many, a few, a little, too much, not enough) usando 5 palavras novas. Preview: Next class &mdash; Past Continuous.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: great work, Murielle! You can now talk about quantities with confidence. Celebre. Preview: Next class &mdash; Something Was Happening, past continuous for storytelling.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
