# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 18,
 'phases': ["What Was Happening", "Story Words", "Past Continuous Forms", "The Story", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1521791136064-7986c2920216?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1434030216411-0b793f4b4173?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "Something Was", 'title_b': "Happening",
 'subtitle1': "Past continuous for HR storytelling",
 'hook_a': "What Was", 'hook_b': "Happening?",
 'hook_prompt': "Picture a hectic morning at the office. What were you doing when everything changed?",
 'recall_a': "From Quantities to", 'recall_b': "Stories",
 'recall_text': "Last class you talked about amounts with quantifiers. Today you tell a story about the past: what was happening while events unfolded.",
 'recall_chips': ["I was preparing", "the team were working", "while I was calling"],
 'vocab_sub': "The words for telling a past story",
 'vocab_head1': ("Timing and", "Speed"),
 'vocab_head2': ("Chaos and", "Interruptions"),
 'vocab': [
   ("Meanwhile", "at the same time", "enquanto isso", "Meanwhile, the team was finishing the report."),
   ("Suddenly", "quickly and unexpectedly", "de repente", "Suddenly, the system crashed."),
   ("Unfold", "to happen or develop", "se desenrolar / acontecer", "The crisis was unfolding fast."),
   ("Simultaneously", "at the same time", "simultaneamente", "Two meetings were running simultaneously."),
   ("Gradually", "slowly, little by little", "gradualmente", "The team was gradually calming down."),
   ("Hectic", "very busy and chaotic", "agitado / caótico", "It was a hectic morning at the office."),
   ("Underway", "already happening", "em andamento", "The audit was already underway."),
   ("Midway", "in the middle", "no meio / na metade", "The call dropped midway through the meeting."),
   ("Unexpectedly", "in a surprising way", "inesperadamente", "The director arrived unexpectedly."),
   ("Interruption", "something that stops an activity", "interrupção", "There was a sudden interruption."),
   ("Commotion", "noisy confusion", "tumulto / confusão", "There was a commotion in the corridor."),
   ("Chaos", "complete disorder", "caos", "The office was in chaos during the audit."),
 ],
 'concept_label': "Past Continuous at a Glance",
 'concept_a': "Background vs", 'concept_b': "Interruption",
 'concept_sub': "The long action sets the scene; the short one cuts in",
 'concept_cols': [
   ("BACKGROUND (was/were + -ing)", "the longer action in progress"),
   ("INTERRUPTION (past simple + when)", "the short action that cuts in"),
 ],
 'concept_drill': [
   ("Say what you were doing at 3 p.m.", "I was reviewing the turnover data."),
   ("Combine a long action and a short one.", "I was presenting when the system crashed."),
   ("Say two things happening at once.", "While I was talking, Ethan was taking notes."),
   ("Ask what someone was doing.", "What were you doing this morning?"),
 ],
 'pron': [
   "I was preparing the audit report.",
   "I was presenting when the system crashed.",
   "While I was talking, Ethan was taking notes.",
   "What were you doing this morning?",
 ],
 'gram_title_a': "Past", 'gram_title_b': "Continuous",
 'gram_title_sub': "Was/were + verb-ing",
 'discovery': [
   ('"I <span class="accent" style="font-weight:700">was reviewing</span> the data when Ethan called."', "I was reviewing the data when Ethan called."),
   ('"The team <span class="accent" style="font-weight:700">were preparing</span> the report all morning."', "The team were preparing the report all morning."),
   ('"While I <span class="accent" style="font-weight:700">was presenting</span>, the system crashed."', "While I was presenting, the system crashed."),
   ('"We <span class="accent" style="font-weight:700">were not expecting</span> so many questions."', "We were not expecting so many questions."),
 ],
 'rule_head': ["Use", "Form", "Example"],
 'rule_rows': [
   ("Action in progress", "was/were + verb-ing", "I was reviewing the data"),
   ("Interrupted action", "past continuous + when + past simple", "I was talking when he arrived"),
   ("Two actions (while)", "while + past continuous", "while I was presenting"),
   ("Negative / Question", "was not / were not; Was/Were...?", "We were not expecting that"),
 ],
 'mistakes': [
   ("I was review the data.", "I was <strong>reviewing</strong> the data."),
   ("They was preparing the report.", "They <strong>were</strong> preparing the report."),
   ("We was not expecting so many questions.", "We <strong>were not</strong> expecting so many questions."),
   ("What you were doing at 3 p.m.?", "<strong>What were you</strong> doing at 3 p.m.?"),
 ],
 'mistake_note': "Use was with I/he/she/it and were with you/we/they. After was/were, the verb takes -ing. For questions, invert: Was/Were + subject + verb-ing?",
 'gpr_a': "Complete the", 'gpr_b': "Story",
 'gpractice': [
   ('"At nine, I ', "was preparing", ' the audit report. (action in progress)"'),
   ('"The team ', "were interviewing", ' candidates all morning. (plural)"'),
   ('"While I ', "was calling", ' IT, the auditors arrived. (background)"'),
   ('"We ', "were not expecting", ' so many questions. (negative)"'),
   ('"What ', "were you doing", ' at 3 p.m.? (question)"'),
 ],
 'build1_label': "Build the Sentence",
 'build1_a': "Tell the", 'build1_b': "Moment",
 'build1': [
   ("I / prepare / the report / when / the system / crash", "I was preparing the report when the system crashed."),
   ("the team / interview / candidates / all morning", "The team were interviewing candidates all morning."),
   ("while / I / present / Ethan / take notes", "While I was presenting, Ethan was taking notes."),
   ("we / not / expect / so many questions", "We were not expecting so many questions."),
   ("what / you / do / at 3 p.m.", "What were you doing at 3 p.m.?"),
 ],
 'context_sub': "Recounting a chaotic audit morning",
 'dlg_title_a': "The Hectic", 'dlg_title_b': "Morning",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, you look tired. What was happening this morning?",
    "Murielle, you look tired. What was happening this morning?"),
   ("M", "#86198F", "murielle", "ellen",
    'It was <span class="vocab-highlight">hectic</span>. I was preparing the audit report when the system <span class="vocab-highlight">suddenly</span> crashed.',
    "It was hectic. I was preparing the audit report when the system suddenly crashed."),
   ("E", "#1b4965", "ethan", "arthur",
    "Oh no. What were the others doing?",
    "Oh no. What were the others doing?"),
   ("M", "#86198F", "murielle", "ellen",
    'The team was calling IT, and <span class="vocab-highlight">meanwhile</span> Diana was calming the auditors.',
    "The team was calling IT, and meanwhile Diana was calming the auditors."),
   ("E", "#1b4965", "ethan", "arthur",
    "Did you finish on time?",
    "Did you finish on time?"),
   ("M", "#86198F", "murielle", "ellen",
    'Almost. The crisis was <span class="vocab-highlight">unfolding</span> fast, but <span class="vocab-highlight">gradually</span> things got back to normal.',
    "Almost. The crisis was unfolding fast, but gradually things got back to normal."),
   ("E", "#1b4965", "ethan", "arthur",
    "And the auditors?",
    "And the auditors?"),
   ("M", "#86198F", "murielle", "ellen",
    'They arrived <span class="vocab-highlight">unexpectedly</span>, <span class="vocab-highlight">midway</span> through the chaos. But we were still smiling.',
    "They arrived unexpectedly, midway through the chaos. But we were still smiling."),
 ],
 'dlg_comp': [
   ("What was Murielle doing when the system crashed?", "She was preparing the audit report."),
   ("What were the team and Diana doing?", "The team was calling IT, and Diana was calming the auditors."),
   ("When did the auditors arrive?", "Unexpectedly, midway through the chaos."),
 ],
 'listenings': [
   {"title_a": "The", "title_b": "Morning", "file": "a18_listening_morning.mp3", "voice": "arthur",
    "text": ("Let me tell you about yesterday morning. It was completely hectic. At nine, I was preparing the audit "
             "report when the system suddenly crashed. Meanwhile, the recruiters were interviewing candidates in the "
             "next room, and two meetings were running simultaneously. While I was calling IT, the auditors arrived "
             "unexpectedly. There was a real commotion in the corridor. Gradually, though, things were calming down. "
             "By eleven, the crisis was no longer unfolding, and everyone was smiling again. It was chaos, but we "
             "handled it as a team."),
    "qs": [
      ("What was he doing when the system crashed?", "He was preparing the audit report."),
      ("What was happening in the next room?", "The recruiters were interviewing candidates, and two meetings were running simultaneously."),
      ("What was happening by eleven?", "Things were calming down and everyone was smiling again."),
    ]},
   {"title_a": "The", "title_b": "Incident", "file": "a18_listening_incident.mp3", "voice": "ellen",
    "text": ("Good afternoon. I want to describe what was happening during the incident last week. It was a hectic "
             "day. While the team was running the onboarding session, a fire alarm went off unexpectedly. People "
             "were leaving the building, and meanwhile I was checking that everyone was safe. The situation was "
             "unfolding very fast. A few staff were still working when the alarm rang, so I was guiding them out. "
             "Gradually, the commotion was fading, and the auditors, who were visiting that day, stayed calm. Nobody "
             "was hurt, and by the afternoon we were back to normal."),
    "qs": [
      ("What was the team doing when the alarm went off?", "They were running the onboarding session."),
      ("What was Murielle doing while people were leaving?", "She was checking that everyone was safe and guiding staff out."),
      ("Was anyone hurt?", "No; by the afternoon they were back to normal."),
    ]},
 ],
 'art_title_a': "Incident", 'art_title_b': "Timeline",
 'art_kicker': "Incident Log &middot; Minerva Foods HR",
 'art_subtitle': "Audit Morning -- Timeline",
 'art_lines': [
   "At 9:00 I was preparing the audit report.",
   "The team was calling IT when the auditors arrived.",
   "Meanwhile, Diana was calming the visitors.",
   "By 11:00 things were gradually returning to normal.",
 ],
 'art_sign': "Logged by: Murielle Xavier",
 'art_note': "Read each line aloud: At 9:00 I was preparing the audit report.",
 'quickfire': [
   ("Say what you were doing at 9 a.m.", "I was preparing the audit report."),
   ("Combine a long action and an interruption.", "I was presenting when the system crashed."),
   ("Say two things happening at once.", "While I was talking, Ethan was taking notes."),
   ("Say the team was not expecting something.", "We were not expecting so many questions."),
   ("Ask what someone was doing.", "What were you doing this morning?"),
 ],
 'spot': [
   ("I was review the data.", "I was reviewing the data. (was + verb-ing)"),
   ("They was preparing the report.", "They were preparing the report. (they = were)"),
   ("We was not expecting so many questions.", "We were not expecting so many questions. (we = were)"),
   ("What you were doing at 3 p.m.?", "What were you doing at 3 p.m.? (invert for a question)"),
 ],
 'build2': [
   ("I / prepare / the report / when / the system / crash", "I was preparing the report when the system crashed."),
   ("the team / interview / candidates / all morning", "The team were interviewing candidates all morning."),
   ("while / I / present / Ethan / take notes", "While I was presenting, Ethan was taking notes."),
   ("we / not / expect / so many questions", "We were not expecting so many questions."),
   ("what / you / do / at 3 p.m.", "What were you doing at 3 p.m.?"),
 ],
 'production_sub': "From guided to free. Tell the story.",
 'roleplays': {
   'guided': {'h': ("Tell the", "Story"),
     'scenario': "Ethan asks: What was happening during the audit this morning? Tell the story. Say what you were doing, what the team was doing, and what suddenly interrupted you. Use was/were + verb-ing.",
     'chips': ["I was ...-ing", "while", "when ... crashed", "meanwhile"]},
   'semi': {'h': ("Describe the", "Incident"),
     'scenario': "Describe a hectic incident to Ethan. Say what was happening, what interrupted it, and how things gradually calmed down.",
     'chips': ["suddenly", "unexpectedly", "gradually"]},
   'free': {'h': ("Your Own", "Story"),
     'scenario': "Tell the story of a real busy or chaotic day at work. Say what you and your team were doing, what suddenly happened, and how it unfolded. Use the past continuous and the new words.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "I was preparing the audit report.",
   "I was presenting when the system crashed.",
   "While I was talking, Ethan was taking notes.",
   "We were not expecting so many questions.",
   "What were you doing this morning?",
 ],
 'checklist': [
   "I can describe an action in progress in the past: I was preparing the report.",
   "I can combine a background action and an interruption: I was talking when he arrived.",
   "I can describe two actions at once with while: while I was presenting, Ethan was writing.",
   "I can form negatives and questions: We were not expecting that; What were you doing?",
   "I can use the new words: meanwhile, suddenly, unfold, simultaneously, gradually, hectic, underway, midway, unexpectedly, interruption, commotion, chaos.",
 ],
 'badge_a': "Past in Progress",
 'badge_text': "You can now tell HR stories in the past with confidence, Murielle.",
 'next_lesson': "You Should, You Could, You Might -- Modal Verbs",
 # ----- Pre-class -----
 'pc_title': "Something Was Happening -- Past Continuous for Storytelling",
 'pc_desc': "Describing actions in progress in the past with the past continuous (was/were + verb-ing), interruptions with when/while, and negatives and questions. New words: meanwhile, suddenly, unfold, simultaneously, gradually, hectic, underway, midway, unexpectedly, interruption, commotion, chaos.",
 'gic_text': ("Yesterday morning was completely <strong>hectic</strong>. At nine, I <strong>was preparing</strong> the audit "
              "report when the system <strong>suddenly</strong> crashed. <strong>Meanwhile</strong>, the recruiters "
              "<strong>were interviewing</strong> candidates, and two meetings <strong>were running</strong> "
              "<strong>simultaneously</strong>. While I <strong>was calling</strong> IT, the auditors arrived "
              "<strong>unexpectedly</strong>. There was a real <strong>commotion</strong> in the corridor. "
              "<strong>Gradually</strong>, things <strong>were calming</strong> down, and by eleven the crisis was no "
              "longer <strong>unfolding</strong>."),
 'gic_quiz': [
   ('1. In "I was preparing the report when the system crashed", which action was longer and in progress?',
    [("preparing the report", True), ("the system crashed", False), ("both were short", False)]),
   ('2. Why do we say "the recruiters were interviewing" and not "was interviewing"?',
    [("Because recruiters is plural (were).", True), ("Because it is a question.", False), ("Because it is negative.", False)]),
   ('3. What does "meanwhile" show here?',
    [("Two things happening at the same time.", True), ("One thing after another.", False), ("A future plan.", False)]),
 ],
 'gt_title': "Past Continuous",
 'gt_intro': ("Use o <strong>past continuous</strong> (was/were + verbo-ing) para uma ação em andamento no passado. "
              "Uma ação longa de fundo pode ser interrompida por uma ação curta no past simple, com "
              "<strong>while/when</strong>. Negativo: <strong>was not / were not</strong> + -ing. Pergunta: "
              "<strong>Was/Were</strong> + sujeito + -ing?"),
 'gt_head': ["Uso", "Forma", "Exemplo"],
 'gt_rows': [
   ("Ação em andamento", "was/were + verbo-ing", "I was preparing the report."),
   ("Interrupção", "past continuous + when + past simple", "I was talking when he arrived."),
   ("Duas ações (while)", "while + past continuous", "While I was presenting, Ethan was writing."),
   ("Negativa / Pergunta", "was not / were not; Was/Were...?", "What were you doing?"),
 ],
 'gt_note': "Atenção: I/he/she/it usam was; you/we/they usam were. Depois de was/were vem o verbo com -ing, não a forma base.",
 'fill': [
   ('"At nine, I ', "was preparing", "Hint: I = was + verb-ing", "At nine, I was preparing the audit report.", ' the audit report. (in progress)"'),
   ('"The team ', "were interviewing", "Hint: team members = were + verb-ing", "The team were interviewing candidates.", ' candidates all morning. (plural)"'),
   ('"While I ', "was calling", "Hint: while + was + verb-ing", "While I was calling IT, the auditors arrived.", ' IT, the auditors arrived. (background)"'),
   ('"We ', "were not expecting", "Hint: negative = were not + verb-ing", "We were not expecting so many questions.", ' so many questions. (negative)"'),
   ('"What ', "were you doing", "Hint: question = Were + you + verb-ing", "What were you doing at three p.m.?", ' at 3 p.m.? (question)"'),
   ('"Suddenly, the system ', "crashed", "Hint: short interrupting action = past simple", "Suddenly, the system crashed.", '. (interruption)"'),
 ],
 'order_title': "Put the Story in Order",
 'order_instr': "Coloque os passos de contar a história na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Set the scene: At nine, I was preparing the audit report.", 1),
   ("Add background: Meanwhile, the team was interviewing candidates.", 2),
   ("The interruption: Suddenly, the system crashed.", 3),
   ("The reaction: While I was calling IT, the auditors arrived.", 4),
   ("The resolution: Gradually, things were calming down.", 5),
 ],
 'speech': [
   ("I was preparing the audit report.", "Eu estava preparando o relatório da auditoria."),
   ("I was presenting when the system crashed.", "Eu estava apresentando quando o sistema caiu."),
   ("While I was talking, Ethan was taking notes.", "Enquanto eu falava, o Ethan anotava."),
   ("We were not expecting so many questions.", "Não estávamos esperando tantas perguntas."),
   ("What were you doing this morning?", "O que você estava fazendo esta manhã?"),
 ],
 'sit_quiz': [
   ("You describe an action in progress in the past. You say:",
    [('"I was review the report."', False), ('"I was reviewing the report."', True), ('"I reviewing the report."', False)]),
   ("The recruiters were busy. You say:",
    [('"The recruiters was interviewing candidates."', False), ('"The recruiters were interviewing candidates."', True), ('"The recruiters were interview candidates."', False)]),
   ("You combine a background action and an interruption. You say:",
    [('"I was presenting when the system crashed."', True), ('"I presented when the system was crashing."', False), ('"I present when the system crashed."', False)]),
   ("You ask about a past action. You say:",
    [('"What you were doing at 3 p.m.?"', False), ('"What were you doing at 3 p.m.?"', True), ('"What was you doing at 3 p.m.?"', False)]),
 ],
 'think': ("Tell the story of a real busy or chaotic day at work. Say what you and your team were doing, what suddenly "
           "happened, and how the situation unfolded. Use the past continuous (was/were + verb-ing) and at least four new words. Take your time."),
 'survival': [
   ("I was preparing the audit report.", "Eu estava preparando o relatório da auditoria."),
   ("I was presenting when the system crashed.", "Eu estava apresentando quando o sistema caiu."),
   ("While I was talking, Ethan was taking notes.", "Enquanto eu falava, o Ethan anotava."),
   ("We were not expecting so many questions.", "Não estávamos esperando tantas perguntas."),
   ("What were you doing this morning?", "O que você estava fazendo esta manhã?"),
 ],
 'comp_heading': "Something Was Happening -- Past Continuous for HR Storytelling",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode on handling a crisis as it unfolds",
    "Adam Grant and his guests describe what was happening during difficult moments at work. You will hear the past continuous used to set the scene. Direct connection to Lesson 18: telling HR stories.",
    "write 5 sentences with was/were + verb-ing about a busy day.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene describing what was happening during a chaotic day",
    "Watch a scene where a character tells what everyone was doing when a problem hit. Notice the past continuous in fast professional speech. Connection to Lesson 18: narrating an incident.",
    "pause and say: I was presenting when the system crashed.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"Past Continuous" -- BBC Learning English',
    "A clear lesson on was/were + verb-ing and how to combine it with the past simple for interruptions. Connection to Lesson 18: telling stories about the past at work.",
    "pause and build sentences with while and when.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 18. Tema: contar historias de RH no passado. Foco B1: past continuous (was/were + verbo-ing) para acao em andamento, interrupcao com when/while, negativa e pergunta + 12 palavras novas. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: imagine uma manha agitada no escritorio. O que voce estava fazendo quando tudo mudou? Deixe a Murielle responder. NAO corrija ainda; anote se ela usa was/were + -ing.",
   's3': "<strong>Recall da aula 17 (3 min):</strong> Callback dos quantifiers (many, much, a few). Ponte: na aula passada voce falou de quantidades; hoje voce conta o que ESTAVA acontecendo enquanto os eventos se desenrolavam.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para contar uma historia voce precisa das palavras de tempo, velocidade e caos. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: MEAN-while, SU-ddenly, un-FOLD, si-mul-TA-neous-ly, GRA-dually, HEC-tic. Pergunte: what was happening meanwhile?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: UN-der-way, MID-way, un-ex-PEC-ted-ly, in-ter-RUP-tion, co-MMO-tion, CHA-os. Peca uma frase com cada palavra.",
   's7': "<strong>Past Continuous num relance (5 min):</strong> Duas colunas: FUNDO (was/were + -ing, acao longa) e INTERRUPCAO (past simple + when, acao curta). Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco no was/were + -ing e no ritmo de while/when.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a gramatica &mdash; past continuous para acao em andamento, e como combinar com o past simple.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: what do the orange words show? CCQ 1: was the action in progress? Yes. CCQ 2: was + -ing? Yes. CCQ 3: I/she use was, you/they use were? Yes. So clique Reveal the Rule.",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Erros: (1) was + verbo base, (2) they was, (3) we was not, (4) pergunta sem inversao.",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz o tipo (in progress/background/negative/question).",
   's13': "<strong>Build the Sentence (3 min):</strong> Peca a frase completa em voz alta com was/were + -ing. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan, e a Murielle conta a manha caotica da auditoria.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan perguntando sobre a manha. Clique Next Line um de cada vez. Reforce cada was/were + -ing. OBSTACULO: was vs were e verbo com -ing.",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; a narrator describes a hectic morning. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora descreve um incidente. OBSTACULO: separar acao de fundo (was/were + -ing) da interrupcao (past simple).",
   's19': "<strong>Artefato (3 min):</strong> Mostre a timeline do incidente e peca a Murielle para ler cada linha em voz alta usando o past continuous.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, as formas e uma timeline real. Agora juntamos tudo.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca a frase no past continuous em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Dicas: was or were? verb + -ing? question inversion?",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase completa em voz alta no past continuous. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. Conte a historia.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e Ethan pedindo a historia da auditoria. A Murielle usa os chips. Se travar, de o comeco (I was ...). FOCO: was/were + -ing.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle descreve um incidente agitado: o que estava acontecendo, o que interrompeu e como se acalmou.",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle conta um dia agitado real. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros. OBSTACULO: was/were e o -ing.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Alterne acao em andamento, interrupcao, while, negativa e pergunta.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula. Homework: gravar uma historia de 8-10 frases sobre um dia agitado real (was/were + -ing, when, while) usando 5 palavras novas. Preview: Next class &mdash; Modal Verbs.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: great work, Murielle! You can now tell past stories with confidence. Celebre. Preview: Next class &mdash; You Should, You Could, You Might, modal verbs for HR advice.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
