# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 19,
 'phases': ["What Should We Do", "Advice Words", "Modal Forms", "The Advice", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1450101499163-c8848c66ca85?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1507925921958-8a62f3d1a50d?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "You Should, You Could,", 'title_b': "You Might",
 'subtitle1': "Modal verbs for HR advice",
 'hook_a': "What Should", 'hook_b': "We Do?",
 'hook_prompt': "A tricky HR dilemma lands on your desk. What is your advice, and how sure are you?",
 'recall_a': "From Stories to", 'recall_b': "Advice",
 'recall_text': "Last class you told past stories with the past continuous. Today you give advice and weigh options with should, could, and might.",
 'recall_chips': ["you should", "we could", "they might"],
 'vocab_sub': "The words for advising and weighing choices",
 'vocab_head1': ("Advice and", "Options"),
 'vocab_head2': ("Risks and", "Trade-offs"),
 'vocab': [
   ("Advisable", "sensible; a good idea", "aconselhável / recomendável", "It is advisable to talk to HR first."),
   ("Alternative", "another option", "alternativa", "We could try an alternative approach."),
   ("Cautious", "careful to avoid risk", "cauteloso / cuidadoso", "We should be cautious with this decision."),
   ("Potential", "possible in the future", "potencial", "She has great potential as a leader."),
   ("Likelihood", "the chance that something happens", "probabilidade", "The likelihood of success is high."),
   ("Dilemma", "a difficult choice", "dilema", "We are facing a real HR dilemma."),
   ("Weigh up", "to consider carefully", "ponderar / avaliar", "You should weigh up both options."),
   ("Drawback", "a disadvantage", "desvantagem", "The main drawback is the cost."),
   ("Worthwhile", "worth the time or effort", "que vale a pena", "The training is worthwhile."),
   ("Feasible", "possible to do", "viável / factível", "The plan is feasible with more time."),
   ("Tentative", "not final; uncertain", "provisório / preliminar", "We made a tentative decision."),
   ("Downside", "the negative part", "lado negativo", "The downside is the extra workload."),
 ],
 'concept_label': "Modals at a Glance",
 'concept_a': "Advice vs", 'concept_b': "Possibility",
 'concept_sub': "should = advice; could / might = options and maybes",
 'concept_cols': [
   ("ADVICE (should)", "the best thing to do"),
   ("POSSIBILITY (could / might)", "an option or a maybe"),
 ],
 'concept_drill': [
   ("Give strong advice.", "You should talk to the manager."),
   ("Suggest an option.", "We could offer a flexible schedule."),
   ("Say something is possible.", "They might accept the offer."),
   ("Give advice against something.", "You should not ignore the feedback."),
 ],
 'pron': [
   "You should talk to her first.",
   "We could offer a flexible schedule.",
   "They might accept the new policy.",
   "You should not ignore the feedback.",
 ],
 'gram_title_a': "Modal", 'gram_title_b': "Verbs",
 'gram_title_sub': "Should, could, might + base verb",
 'discovery': [
   ('"You <span class="accent" style="font-weight:700">should</span> talk to the manager first."', "You should talk to the manager first."),
   ('"We <span class="accent" style="font-weight:700">could</span> offer a flexible schedule."', "We could offer a flexible schedule."),
   ('"They <span class="accent" style="font-weight:700">might</span> accept the new policy."', "They might accept the new policy."),
   ('"You <span class="accent" style="font-weight:700">should not</span> ignore the feedback."', "You should not ignore the feedback."),
 ],
 'rule_head': ["Use", "Form", "Example"],
 'rule_rows': [
   ("Advice (recommend)", "should / should not + base verb", "you should talk to HR"),
   ("Option (possibility)", "could + base verb", "we could offer training"),
   ("Possibility (less sure)", "might + base verb", "they might agree"),
   ("All modals", "modal + base verb (no to, no -s)", "she should decide"),
 ],
 'mistakes': [
   ("You should to talk to HR.", "You should <strong>talk</strong> to HR."),
   ("She should decides now.", "She should <strong>decide</strong> now."),
   ("We could to offer training.", "We could <strong>offer</strong> training."),
   ("You not should ignore it.", "You <strong>should not</strong> ignore it."),
 ],
 'mistake_note': "After should, could, and might, use the base verb: no to and no -s. The most common negative advice is should not (shouldn't).",
 'gpr_a': "Complete the", 'gpr_b': "Advice",
 'gpractice': [
   ('"You ', "should", ' talk to her first. (advice)"'),
   ('"We ', "could", ' offer a flexible schedule. (option)"'),
   ('"She ', "might", ' stay if we act quickly. (possibility)"'),
   ('"You ', "should not", ' ignore the feedback. (negative advice)"'),
   ('"We ', "should", ' weigh up both options. (advice)"'),
 ],
 'build1_label': "Build the Advice",
 'build1_a': "Say the", 'build1_b': "Recommendation",
 'build1': [
   ("you / should / talk / to the manager", "You should talk to the manager."),
   ("we / could / offer / a flexible schedule", "We could offer a flexible schedule."),
   ("they / might / accept / the new policy", "They might accept the new policy."),
   ("you / should not / ignore / the feedback", "You should not ignore the feedback."),
   ("we / should / weigh up / both options", "We should weigh up both options."),
 ],
 'context_sub': "Advising on a retention dilemma",
 'dlg_title_a': "The", 'dlg_title_b': "Dilemma",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, one of our best analysts wants to leave. What should we do?",
    "Murielle, one of our best analysts wants to leave. What should we do?"),
   ("M", "#86198F", "murielle", "ellen",
    'We should talk to her first and understand why. It is <span class="vocab-highlight">advisable</span> to listen before we act.',
    "We should talk to her first and understand why. It is advisable to listen before we act."),
   ("E", "#1b4965", "ethan", "arthur",
    "And if it is about money?",
    "And if it is about money?"),
   ("M", "#86198F", "murielle", "ellen",
    'We could offer a raise, or we could propose a new role. Both are <span class="vocab-highlight">worthwhile</span> options.',
    "We could offer a raise, or we could propose a new role. Both are worthwhile options."),
   ("E", "#1b4965", "ethan", "arthur",
    "What are the drawbacks?",
    "What are the drawbacks?"),
   ("M", "#86198F", "murielle", "ellen",
    'The main <span class="vocab-highlight">drawback</span> is cost, but the <span class="vocab-highlight">downside</span> of losing her is worse.',
    "The main drawback is cost, but the downside of losing her is worse."),
   ("E", "#1b4965", "ethan", "arthur",
    "So what is your recommendation?",
    "So what is your recommendation?"),
   ("M", "#86198F", "murielle", "ellen",
    'We should <span class="vocab-highlight">weigh up</span> both options. She might stay if we act quickly and are <span class="vocab-highlight">cautious</span>.',
    "We should weigh up both options. She might stay if we act quickly and are cautious."),
 ],
 'dlg_comp': [
   ("What should they do first, according to Murielle?", "They should talk to the analyst and understand why she wants to leave."),
   ("What two options could they offer?", "They could offer a raise or propose a new role."),
   ("What might happen if they act quickly?", "The analyst might stay."),
 ],
 'listenings': [
   {"title_a": "The", "title_b": "Advice", "file": "a19_listening_advice.mp3", "voice": "arthur",
    "text": ("Hello. Let me share some advice on our staffing dilemma. First, you should not panic. It is advisable to "
             "look at all the options calmly. You could offer flexible hours, or you might introduce a mentoring "
             "program. Both are feasible and worthwhile. Of course, every option has a drawback, so you should weigh "
             "up the costs and benefits. I would be cautious about a quick decision. The likelihood of keeping our "
             "best people is much higher if we listen first. In short, you should act, but you should act carefully."),
    "qs": [
      ("What should you not do first?", "You should not panic."),
      ("What two options could you try?", "You could offer flexible hours or introduce a mentoring program."),
      ("Why should you be cautious?", "Because every option has a drawback, so you should weigh up the costs and benefits."),
    ]},
   {"title_a": "The", "title_b": "Options", "file": "a19_listening_options.mp3", "voice": "ellen",
    "text": ("Good morning. Let me talk through our options for the new policy. We could introduce it immediately, but "
             "that might cause resistance. Alternatively, we could test it with one team first. That is a more "
             "cautious and feasible approach. The main downside is that it takes longer. However, the likelihood of "
             "success is higher, and the drawback is small. It is advisable to weigh up both paths. I think a "
             "tentative rollout is worthwhile. We should decide this week, but we should not rush the details. Thank you."),
    "qs": [
      ("What might happen if they introduce the policy immediately?", "It might cause resistance."),
      ("What is the more cautious option?", "To test the policy with one team first."),
      ("What does she recommend?", "A tentative rollout; they should decide this week but not rush the details."),
    ]},
 ],
 'art_title_a': "Advisory", 'art_title_b': "Note",
 'art_kicker': "Advisory Note &middot; Minerva Foods HR",
 'art_subtitle': "Retention Dilemma -- Recommendations",
 'art_lines': [
   "You should talk to the analyst first.",
   "We could offer a raise or a new role.",
   "We should weigh up the drawbacks.",
   "She might stay if we act quickly.",
 ],
 'art_sign': "Advised by: Murielle Xavier",
 'art_note': "Read each line aloud: You should talk to the analyst first.",
 'quickfire': [
   ("Give strong advice about a resignation.", "You should talk to her first."),
   ("Suggest an option.", "We could offer a flexible schedule."),
   ("Say something is possible.", "She might stay if we act quickly."),
   ("Give advice against something.", "You should not ignore the feedback."),
   ("Recommend weighing the options.", "You should weigh up both options."),
 ],
 'spot': [
   ("You should to talk to HR.", "You should talk to HR. (no to after should)"),
   ("She should decides now.", "She should decide now. (base verb, no -s)"),
   ("We could to offer training.", "We could offer training. (no to after could)"),
   ("You not should ignore it.", "You should not ignore it. (should not)"),
 ],
 'build2': [
   ("you / should / talk / to the manager", "You should talk to the manager."),
   ("we / could / offer / a flexible schedule", "We could offer a flexible schedule."),
   ("they / might / accept / the new policy", "They might accept the new policy."),
   ("you / should not / ignore / the feedback", "You should not ignore the feedback."),
   ("we / should / weigh up / both options", "We should weigh up both options."),
 ],
 'production_sub': "From guided to free. Give your advice.",
 'roleplays': {
   'guided': {'h': ("Advise on the", "Dilemma"),
     'scenario': "Ethan asks: Our best analyst wants to leave. What should we do? Give advice: what they should do, what they could offer, and what might happen. Use should, could, and might.",
     'chips': ["you should ...", "we could ...", "she might ...", "advisable"]},
   'semi': {'h': ("Weigh the", "Options"),
     'scenario': "Advise Ethan on a new policy. Give one recommendation with should, one option with could, and one possibility with might. Mention a drawback.",
     'chips': ["weigh up", "feasible", "cautious"]},
   'free': {'h': ("Your Own", "Advice"),
     'scenario': "Advise on a real HR dilemma from your own work. Say what the person should and should not do, what they could try, and what might happen. Use should, could, might, and the new words.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "You should talk to her first.",
   "We could offer a flexible schedule.",
   "She might stay if we act quickly.",
   "You should not ignore the feedback.",
   "We should weigh up both options.",
 ],
 'checklist': [
   "I can give advice with should and should not: You should talk to HR.",
   "I can suggest options with could: We could offer training.",
   "I can express possibility with might: They might agree.",
   "I can use modal + base verb correctly (no to, no -s): She should decide.",
   "I can use the new words: advisable, alternative, cautious, potential, likelihood, dilemma, weigh up, drawback, worthwhile, feasible, tentative, downside.",
 ],
 'badge_a': "Sound Judgment",
 'badge_text': "You can now give clear HR advice with confidence, Murielle.",
 'next_lesson': "Block 2 Milestone -- Fluency Review",
 # ----- Pre-class -----
 'pc_title': "You Should, You Could, You Might -- Modal Verbs for HR Advice",
 'pc_desc': "Giving advice and weighing options with modal verbs: should / should not (advice), could (option), and might (possibility), all with the base verb. New words: advisable, alternative, cautious, potential, likelihood, dilemma, weigh up, drawback, worthwhile, feasible, tentative, downside.",
 'gic_text': ("We have a real <strong>dilemma</strong>: our best analyst wants to leave. First, you <strong>should</strong> "
              "talk to her, and you <strong>should not</strong> panic. It is <strong>advisable</strong> to listen before you "
              "act. We <strong>could</strong> offer a raise, or we <strong>could</strong> propose an <strong>alternative</strong> "
              "role. She <strong>might</strong> stay if we are <strong>cautious</strong> and quick. Every option has a "
              "<strong>drawback</strong>, so we should <strong>weigh up</strong> the costs. The <strong>likelihood</strong> of "
              "keeping her is higher if we act well; a good plan is <strong>worthwhile</strong>."),
 'gic_quiz': [
   ('1. What does "should" express in "you should talk to her"?',
    [("Advice or a recommendation.", True), ("A past action.", False), ("An obligation with a fine.", False)]),
   ('2. Which sentence expresses possibility (a maybe)?',
    [('"She might stay."', True), ('"You should talk to her."', False), ('"It is advisable."', False)]),
   ('3. What form of the verb comes after should, could, and might?',
    [("The base form (no to, no -s).", True), ("The -ing form.", False), ("The -s form.", False)]),
 ],
 'gt_title': "Modal Verbs (Should / Could / Might)",
 'gt_intro': ("Use <strong>should</strong> para conselho ou recomendação (you should...), <strong>could</strong> para opção "
              "ou possibilidade (we could...) e <strong>might</strong> para possibilidade menos certa (they might...). "
              "Estrutura: <strong>modal + verbo base</strong> (sem to, sem -s). Negativo: <strong>should not (shouldn't)</strong>."),
 'gt_head': ["Uso", "Estrutura", "Exemplo"],
 'gt_rows': [
   ("Conselho", "should / should not + base verb", "You should talk to HR."),
   ("Opção", "could + base verb", "We could offer training."),
   ("Possibilidade", "might + base verb", "They might agree."),
   ("Regra geral", "modal + verbo base (sem to, sem -s)", "She should decide now."),
 ],
 'gt_note': "Atenção: depois de should/could/might vem o verbo base, sem to e sem -s. O negativo mais comum de conselho é should not (shouldn't).",
 'fill': [
   ('"You ', "should", "Hint: advice = should + base verb", "You should talk to her first.", ' talk to her first. (advice)"'),
   ('"We ', "could", "Hint: option = could + base verb", "We could offer a flexible schedule.", ' offer a flexible schedule. (option)"'),
   ('"She ', "might", "Hint: possibility = might + base verb", "She might stay if we act quickly.", ' stay if we act quickly. (possibility)"'),
   ('"You ', "should not", "Hint: negative advice = should not", "You should not ignore the feedback.", ' ignore the feedback. (negative advice)"'),
   ('"We ', "should", "Hint: advice = should + base verb", "We should weigh up both options.", ' weigh up both options. (advice)"'),
   ('"They ', "could", "Hint: option = could + base verb", "They could test the policy first.", ' test the policy first. (option)"'),
 ],
 'order_title': "Put the Advice in Order",
 'order_instr': "Coloque os passos de dar um conselho estruturado na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Understand the problem: You should talk to her first.", 1),
   ("Give the recommendation: It is advisable to listen before you act.", 2),
   ("Offer an option: We could offer a raise or a new role.", 3),
   ("Name the risk: But we should weigh up the drawbacks.", 4),
   ("Predict the outcome: She might stay if we act quickly.", 5),
 ],
 'speech': [
   ("You should talk to her first.", "Você deveria falar com ela primeiro."),
   ("We could offer a flexible schedule.", "Poderíamos oferecer um horário flexível."),
   ("She might stay if we act quickly.", "Ela pode ficar se agirmos rápido."),
   ("You should not ignore the feedback.", "Você não deveria ignorar o feedback."),
   ("We should weigh up both options.", "Deveríamos ponderar as duas opções."),
 ],
 'sit_quiz': [
   ("You give strong advice. You say:",
    [('"You should to talk to her."', False), ('"You should talk to her."', True), ('"You should talking to her."', False)]),
   ("You suggest an option. You say:",
    [('"We could offer a raise."', True), ('"We could to offer a raise."', False), ('"We could offers a raise."', False)]),
   ("You express a possibility. You say:",
    [('"She might stays."', False), ('"She might to stay."', False), ('"She might stay."', True)]),
   ("You advise against something. You say:",
    [('"You not should ignore it."', False), ('"You should not ignore it."', True), ('"You should not to ignore it."', False)]),
 ],
 'think': ("Advise on a real HR dilemma from your own work. Say what the person should and should not do, what they "
           "could try, and what might happen. Use should, could, might, and at least four new words. Take your time."),
 'survival': [
   ("You should talk to her first.", "Você deveria falar com ela primeiro."),
   ("We could offer a flexible schedule.", "Poderíamos oferecer um horário flexível."),
   ("She might stay if we act quickly.", "Ela pode ficar se agirmos rápido."),
   ("You should not ignore the feedback.", "Você não deveria ignorar o feedback."),
   ("We should weigh up both options.", "Deveríamos ponderar as duas opções."),
 ],
 'comp_heading': "You Should, You Could, You Might -- Modal Verbs for HR Advice",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode on making tough decisions",
    "Adam Grant explores how to weigh options and give advice on hard choices. You will hear should, could, and might used to recommend and suggest. Direct connection to Lesson 19: giving HR advice.",
    "write 5 sentences with should, could, and might about a work decision.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene where someone gives advice on a difficult choice",
    "Watch a scene where a character advises a colleague on a hard decision. Notice should, could, and might in fast professional speech. Connection to Lesson 19: advising on a dilemma.",
    "pause and say: You should talk to them first.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"Should, Could, Might" -- BBC Learning English',
    "A clear lesson on modal verbs for advice and possibility, and how to use them with the base verb. Connection to Lesson 19: recommending HR actions.",
    "pause and build advice with should, could, and might.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 19. Tema: dar conselhos de RH. Foco B1: modais should (conselho), could (opcao) e might (possibilidade) + verbo base, negativa should not + 12 palavras novas. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: um dilema de RH chega na sua mesa &mdash; qual e seu conselho, e quao certo voce esta? Deixe a Murielle responder. NAO corrija ainda; anote se ela usa should/could/might.",
   's3': "<strong>Recall da aula 18 (3 min):</strong> Callback do past continuous (I was preparing, suddenly). Ponte: na aula passada voce contou o que aconteceu; hoje voce ACONSELHA o que fazer.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para aconselhar voce precisa das palavras de opcao, risco e vale-a-pena. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: ad-VI-sable, al-TER-na-tive, CAU-tious, po-TEN-tial, LIKE-li-hood, di-LE-mma. Pergunte: is it advisable to wait?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: WEIGH up, DRAW-back, WORTH-while, FEA-sible, TEN-ta-tive, DOWN-side. Peca uma frase com cada palavra.",
   's7': "<strong>Modais num relance (5 min):</strong> Duas colunas: CONSELHO (should) e POSSIBILIDADE (could/might). Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco no modal + verbo base e no ritmo de should not.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a gramatica &mdash; should para conselho, could para opcao, might para possibilidade, sempre com verbo base.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: what comes after the orange word? CCQ 1: base verb? Yes. CCQ 2: any to? No. CCQ 3: any -s? No. So clique Reveal the Rule.",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Erros: (1) should to, (2) should + -s, (3) could to, (4) not should.",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz o tipo (advice/option/possibility).",
   's13': "<strong>Build the Advice (3 min):</strong> Peca a frase completa em voz alta com o modal certo. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan, e a Murielle aconselha sobre um analista que quer sair.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan pedindo conselho. Clique Next Line um de cada vez. Reforce cada modal. OBSTACULO: modal + verbo base (sem to, sem -s).",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; a manager gives advice on a dilemma. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora pesa as opcoes de uma nova politica. OBSTACULO: separar should (conselho) de could/might (opcao/possibilidade).",
   's19': "<strong>Artefato (3 min):</strong> Mostre o parecer de RH e peca a Murielle para ler cada linha em voz alta usando should/could/might.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, os modais e um parecer real. Agora juntamos tudo.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca o conselho em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Dicas: any to? any -s? negative position?",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase completa em voz alta com o modal certo. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. De o seu conselho.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e Ethan pedindo conselho sobre o analista. A Murielle usa os chips. Se travar, de o comeco (You should ...). FOCO: modal + verbo base.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle aconselha sobre uma nova politica: uma recomendacao com should, uma opcao com could e uma possibilidade com might.",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle aconselha sobre um dilema real de RH. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros. OBSTACULO: modal + verbo base.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Alterne should, could, might, negativa e conselho.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula. Homework: gravar 8-10 frases de conselho sobre um dilema real de RH (should, could, might, should not) usando 5 palavras novas. Preview: Next class &mdash; Block 2 Milestone, revisao de fluencia.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: great work, Murielle! You can now give clear advice with confidence. Celebre. Preview: Next class &mdash; Block 2 Milestone, a fluency review from data to decisions.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
