# -*- coding: utf-8 -*-
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import genlib

IMG = "https://images.unsplash.com/"
D = {
 'n': 20,
 'phases': ["From Data to Decisions", "Summary Words", "Block 2 Review", "The Presentation", "Practice", "Your Turn", "Wrap-up"],
 'bg': {
   'title': IMG + "photo-1507003211169-0a1dd7228f2d?w=1200&q=80",
   'vocab': IMG + "photo-1454165804606-c3d57bc86b40?w=1200&q=80",
   'grammar': IMG + "photo-1517245386807-bb43f82c33c4?w=1200&q=80",
   'context': IMG + "photo-1542744173-8e7e53415bb0?w=1200&q=80",
   'practice': IMG + "photo-1600880292203-757bb62b4baf?w=1200&q=80",
   'production': IMG + "photo-1475721027785-f74eccf877e2?w=1200&q=80",
 },
 'title_a': "Block 2", 'title_b': "Milestone",
 'subtitle1': "Fluency review: from data to decisions",
 'hook_a': "From Data to", 'hook_b': "Decisions",
 'hook_prompt': "You present to the board tomorrow. In one sentence, what is your biggest message?",
 'recall_a': "Everything from", 'recall_b': "Block 2",
 'recall_text': "Last class you gave advice with modals. Today you bring together the whole block: comparatives, superlatives, quantifiers, past continuous, and modal verbs.",
 'recall_chips': ["better than", "the best", "should decide"],
 'vocab_sub': "The words for a clear, persuasive summary",
 'vocab_head1': ("Summarize and", "Highlight"),
 'vocab_head2': ("Clear and", "Persuasive"),
 'vocab': [
   ("Summarize", "to give the main points briefly", "resumir", "Let me summarize the key results."),
   ("Conclude", "to end with a final point", "concluir", "I conclude that the North is our best region."),
   ("Highlight", "to draw attention to something", "destacar", "I want to highlight one important trend."),
   ("Emphasize", "to give special importance to", "enfatizar / ressaltar", "I emphasize that we should act quickly."),
   ("Articulate", "to express ideas clearly", "articular / expressar bem", "She can articulate her ideas clearly."),
   ("Coherent", "clear and logical", "coerente", "The report is clear and coherent."),
   ("Concise", "short and clear", "conciso", "Keep the summary concise."),
   ("Persuasive", "able to convince others", "persuasivo / convincente", "Her argument was very persuasive."),
   ("Takeaway", "the main message to remember", "conclusão / mensagem principal", "The main takeaway is that turnover fell."),
   ("Standpoint", "a point of view", "ponto de vista", "From an HR standpoint, this is good news."),
   ("Overall", "considering everything", "no geral / de modo geral", "Overall, our results improved."),
   ("Clarity", "the quality of being clear", "clareza", "I present the data with clarity."),
 ],
 'concept_label': "Block 2 at a Glance",
 'concept_a': "Five", 'concept_b': "Structures",
 'concept_sub': "Everything you learned, in one place",
 'concept_cols': [
   ("COMPARE & RANK", "comparatives + superlatives"),
   ("QUANTIFY, NARRATE, ADVISE", "quantifiers + past continuous + modals"),
 ],
 'concept_drill': [
   ("Compare two years.", "Turnover is lower than last year."),
   ("Name the best region.", "The North is our best region."),
   ("Quantify your teams.", "We have many strong teams."),
   ("Recommend an action.", "We should invest in the North."),
 ],
 'pron': [
   "Overall, turnover is lower than last year.",
   "The North is our best region.",
   "We have many strong teams but little budget.",
   "We should invest in the North.",
 ],
 'gram_title_a': "Block 2", 'gram_title_b': "Review",
 'gram_title_sub': "Compare, rank, quantify, narrate, advise",
 'discovery': [
   ('"Turnover is <span class="accent" style="font-weight:700">lower than</span> last year."', "Turnover is lower than last year."),
   ('"The North is our <span class="accent" style="font-weight:700">best</span> region."', "The North is our best region."),
   ('"We have <span class="accent" style="font-weight:700">many</span> teams but <span class="accent" style="font-weight:700">little</span> budget."', "We have many teams but little budget."),
   ('"We <span class="accent" style="font-weight:700">should</span> act quickly."', "We should act quickly."),
 ],
 'rule_head': ["Structure", "Form", "Example"],
 'rule_rows': [
   ("Comparatives", "-er than / more ... than", "lower than, more efficient than"),
   ("Superlatives", "the ...-est / the most", "the highest, the most efficient"),
   ("Quantifiers", "many/much, a few/a little", "many roles, much data"),
   ("Past continuous", "was/were + verb-ing", "we were preparing the report"),
   ("Modals", "should / could / might + base verb", "we should decide now"),
 ],
 'mistakes': [
   ("Turnover is more lower than last year.", "Turnover is <strong>lower</strong> than last year."),
   ("It is the most best result.", "It is the <strong>best</strong> result."),
   ("We have much vacancies.", "We have <strong>many</strong> vacancies."),
   ("We should to decide now.", "We should <strong>decide</strong> now."),
 ],
 'mistake_note': "Block 2 in one glance: -er than (compare), the best (rank), many/much (quantify), was/were + -ing (narrate), should + base verb (advise).",
 'gpr_a': "Complete the", 'gpr_b': "Summary",
 'gpractice': [
   ('"Overall, turnover is ', "lower than", ' last year. (comparative)"'),
   ('"The North is our ', "best", ' region. (superlative)"'),
   ('"We have ', "many", ' strong teams. (quantifier)"'),
   ('"Last quarter, we ', "were losing", ' staff. (past continuous)"'),
   ('"We ', "should", ' invest in the North. (modal)"'),
 ],
 'build1_label': "Build the Summary",
 'build1_a': "From Data to", 'build1_b': "Words",
 'build1': [
   ("turnover / low / than / last year", "Turnover is lower than last year."),
   ("the North / be / good / region", "The North is the best region."),
   ("we / have / many / strong teams", "We have many strong teams."),
   ("last quarter / we / lose / staff", "Last quarter we were losing staff."),
   ("we / should / invest / in the North", "We should invest in the North."),
 ],
 'context_sub': "Rehearsing the board presentation",
 'dlg_title_a': "The", 'dlg_title_b': "Rehearsal",
 'dialogue': [
   ("E", "#1b4965", "ethan", "arthur",
    "Murielle, you present to the board tomorrow. Give me your summary.",
    "Murielle, you present to the board tomorrow. Give me your summary."),
   ("M", "#86198F", "murielle", "ellen",
    '<span class="vocab-highlight">Overall</span>, turnover is lower than last year, and the North is our best region.',
    "Overall, turnover is lower than last year, and the North is our best region."),
   ("E", "#1b4965", "ethan", "arthur",
    "Good. What about the numbers?",
    "Good. What about the numbers?"),
   ("M", "#86198F", "murielle", "ellen",
    "We have many strong teams but little budget. Last quarter we were losing staff fast.",
    "We have many strong teams but little budget. Last quarter we were losing staff fast."),
   ("E", "#1b4965", "ethan", "arthur",
    "And your recommendation?",
    "And your recommendation?"),
   ("M", "#86198F", "murielle", "ellen",
    "We should invest in the North, and we could expand the mentoring program.",
    "We should invest in the North, and we could expand the mentoring program."),
   ("E", "#1b4965", "ethan", "arthur",
    "Nice. Can you make it more persuasive?",
    "Nice. Can you make it more persuasive?"),
   ("M", "#86198F", "murielle", "ellen",
    'Yes. My main <span class="vocab-highlight">takeaway</span> is clear: from a data <span class="vocab-highlight">standpoint</span>, we should act now.',
    "Yes. My main takeaway is clear: from a data standpoint, we should act now."),
 ],
 'dlg_comp': [
   ("How does turnover compare to last year?", "It is lower than last year."),
   ("What is the budget situation?", "They have many strong teams but little budget."),
   ("What is Murielle's main recommendation?", "They should invest in the North and could expand the mentoring program."),
 ],
 'listenings': [
   {"title_a": "The", "title_b": "Summary", "file": "a20_listening_summary.mp3", "voice": "arthur",
    "text": ("Good morning, board members. Let me summarize this year's HR results. Overall, our turnover is lower than "
             "last year, and the North is our strongest region. We have many talented teams, but our budget is "
             "minimal. Last quarter, we were losing our best analysts, which was our biggest risk. From an HR "
             "standpoint, the message is clear. I want to highlight two decisions. First, we should invest more in "
             "the North. Second, we could expand the mentoring program. My main takeaway is simple: we should act "
             "now, and I am confident the results will be better next year. Thank you."),
    "qs": [
      ("How does turnover compare to last year?", "It is lower than last year."),
      ("What was happening last quarter?", "They were losing their best analysts, which was their biggest risk."),
      ("What are the two decisions?", "They should invest more in the North, and they could expand the mentoring program."),
    ]},
   {"title_a": "The", "title_b": "Decision", "file": "a20_listening_decision.mp3", "voice": "ellen",
    "text": ("Hello everyone. I want to present our decision clearly and concisely. This year was our most "
             "challenging, but also our most successful. We had far more applications than last year, yet fewer "
             "recruiters. While we were struggling with the workload, our engagement scores were rising. That is "
             "remarkable. Overall, the North performed best, and the South made the most progress. From a strategic "
             "standpoint, we should keep our current plan, but we could add one more recruiter. My final takeaway is "
             "coherent and simple: our people are our greatest strength, and we should invest in them. Thank you for "
             "listening."),
    "qs": [
      ("How does the manager describe this year?", "As the most challenging but also the most successful year."),
      ("What was happening while they struggled with the workload?", "Their engagement scores were rising."),
      ("What is her final takeaway?", "Their people are their greatest strength, and they should invest in them."),
    ]},
 ],
 'art_title_a': "Executive", 'art_title_b': "Summary",
 'art_kicker': "Executive Summary &middot; Minerva Foods HR",
 'art_subtitle': "Block 2 -- From Data to Decisions",
 'art_lines': [
   "Overall, turnover is lower than last year.",
   "The North is our best region; the South made the most progress.",
   "We have many strong teams but little budget.",
   "We should invest in the North and could expand mentoring.",
 ],
 'art_sign': "Presented by: Murielle Xavier",
 'art_note': "Read each line aloud: Overall, turnover is lower than last year.",
 'quickfire': [
   ("Compare this year with last year.", "Turnover is lower than last year."),
   ("Name your best region.", "The North is our best region."),
   ("Talk about the budget and the teams.", "We have many strong teams but little budget."),
   ("Describe what was happening last quarter.", "We were losing our best analysts."),
   ("Give your recommendation.", "We should invest in the North."),
 ],
 'spot': [
   ("Turnover is more lower than last year.", "Turnover is lower than last year. (comparative: -er than)"),
   ("It is the most best result.", "It is the best result. (superlative: the best is irregular)"),
   ("We have much vacancies.", "We have many vacancies. (quantifier: countable = many)"),
   ("We should to decide now.", "We should decide now. (modal + base verb, no to)"),
 ],
 'build2': [
   ("turnover / low / than / last year", "Turnover is lower than last year."),
   ("the North / be / good / region", "The North is the best region."),
   ("we / have / many / strong teams", "We have many strong teams."),
   ("last quarter / we / lose / staff", "Last quarter we were losing staff."),
   ("we / should / invest / in the North", "We should invest in the North."),
 ],
 'production_sub': "From guided to free. Present and recommend.",
 'roleplays': {
   'guided': {'h': ("Present the", "Data"),
     'scenario': "Ethan is a board member. Present your HR data: compare this year with last year, name the best region, and describe the quantities. Use comparatives, superlatives, and quantifiers.",
     'chips': ["lower than", "the best", "many / much", "overall"]},
   'semi': {'h': ("Make the", "Decision"),
     'scenario': "Present your recommendation to the board. Describe what was happening last quarter, then say what you should and could do next. Use the past continuous and modals.",
     'chips': ["we were ...-ing", "we should", "we could"]},
   'free': {'h': ("Your Full", "Presentation"),
     'scenario': "Give a full data-to-decisions presentation about your own HR work. Compare, rank, quantify, tell what was happening, and recommend what to do. Use all five Block 2 structures and the new words.",
     'note': "No keywords. The stage is yours, Murielle!"},
 },
 'keyphrases': [
   "Overall, turnover is lower than last year.",
   "The North is our best region.",
   "We have many strong teams but little budget.",
   "Last quarter we were losing our best analysts.",
   "We should invest in the North.",
 ],
 'checklist': [
   "I can compare and rank HR data: lower than, the best region.",
   "I can talk about quantities: many teams, little budget.",
   "I can describe what was happening: we were losing staff.",
   "I can recommend actions with modals: we should invest, we could expand.",
   "I can use the new words: summarize, conclude, highlight, emphasize, articulate, coherent, concise, persuasive, takeaway, standpoint, overall, clarity.",
 ],
 'badge_a': "Block 2 Milestone",
 'badge_text': "You can now present HR data and decisions with fluency, Murielle. Block 2 complete!",
 'next_lesson': "What Was Happening -- Storytelling in HR",
 # ----- Pre-class -----
 'pc_title': "Block 2 Milestone -- Fluency Review: From Data to Decisions",
 'pc_desc': "A milestone review of Block 2, bringing together comparatives, superlatives, quantifiers, past continuous, and modal verbs in a data-to-decisions HR presentation. New words: summarize, conclude, highlight, emphasize, articulate, coherent, concise, persuasive, takeaway, standpoint, overall, clarity.",
 'gic_text': ("This year was our <strong>most successful</strong> yet. Overall, turnover is <strong>lower than</strong> last "
              "year, and the North is our <strong>best</strong> region. We have <strong>many</strong> strong teams but "
              "<strong>little</strong> budget. Last quarter, we <strong>were losing</strong> our best analysts, which was our "
              "biggest risk. From an HR <strong>standpoint</strong>, the message is clear. We <strong>should</strong> invest "
              "in the North, and we <strong>could</strong> expand the mentoring program. My main <strong>takeaway</strong> is "
              "<strong>concise</strong>: we should act now."),
 'gic_quiz': [
   ('1. "Turnover is lower than last year" is an example of:',
    [("a comparative.", True), ("a superlative.", False), ("a modal verb.", False)]),
   ('2. "We were losing our best analysts" uses:',
    [("the past continuous.", True), ("a quantifier.", False), ("a comparative.", False)]),
   ('3. "We should invest in the North" uses:',
    [("a modal verb for advice.", True), ("a superlative.", False), ("the past continuous.", False)]),
 ],
 'gt_title': "Block 2 Review (5 Structures)",
 'gt_intro': ("Esta é uma aula de <strong>revisão</strong> (milestone). Você junta as 5 estruturas do Bloco 2: "
              "<strong>comparativos</strong> (lower than), <strong>superlativos</strong> (the best), "
              "<strong>quantifiers</strong> (many/much), <strong>past continuous</strong> (was/were + -ing) e "
              "<strong>modais</strong> (should/could/might). Use todas para apresentar dados e recomendar decisões."),
 'gt_head': ["Estrutura", "Forma", "Exemplo"],
 'gt_rows': [
   ("Comparativo", "-er than / more ... than", "Turnover is lower than last year."),
   ("Superlativo", "the ...-est / the most", "The North is the best region."),
   ("Quantifiers", "many/much, a few/a little", "We have many teams and little budget."),
   ("Past continuous", "was/were + verbo-ing", "We were losing staff last quarter."),
   ("Modais", "should/could/might + verbo base", "We should invest now."),
 ],
 'gt_note': "Atenção: numa apresentação, misture as estruturas com naturalidade: compare, ranqueie, quantifique, conte o que estava acontecendo e recomende a decisão.",
 'fill': [
   ('"Overall, turnover is ', "lower than", "Hint: comparative = -er than", "Overall, turnover is lower than last year.", ' last year. (comparative)"'),
   ('"The North is our ', "best", "Hint: superlative, irregular", "The North is our best region.", ' region. (superlative)"'),
   ('"We have ', "many", "Hint: quantifier, countable", "We have many strong teams.", ' strong teams. (quantifier)"'),
   ('"Last quarter, we ', "were losing", "Hint: past continuous = were + verb-ing", "Last quarter, we were losing staff.", ' staff. (past continuous)"'),
   ('"We ', "should", "Hint: modal for advice", "We should invest in the North.", ' invest in the North. (modal)"'),
   ('"We ', "could", "Hint: modal for an option", "We could expand the mentoring program.", ' expand the mentoring program. (option)"'),
 ],
 'order_title': "Put the Presentation in Order",
 'order_instr': "Coloque os passos de uma apresentação de dados a decisões na ordem correta. (Put the steps in the correct order.)",
 'order': [
   ("Summarize: Overall, turnover is lower than last year.", 1),
   ("Rank: The North is our best region.", 2),
   ("Quantify: We have many teams but little budget.", 3),
   ("Narrate: Last quarter, we were losing our best analysts.", 4),
   ("Recommend: We should invest in the North.", 5),
 ],
 'speech': [
   ("Overall, turnover is lower than last year.", "No geral, a rotatividade está menor que no ano passado."),
   ("The North is our best region.", "O Norte é a nossa melhor região."),
   ("We have many strong teams but little budget.", "Temos muitas equipes fortes, mas pouco orçamento."),
   ("Last quarter we were losing our best analysts.", "No trimestre passado estávamos perdendo nossos melhores analistas."),
   ("We should invest in the North.", "Deveríamos investir no Norte."),
 ],
 'sit_quiz': [
   ("You compare this year with last year. You say:",
    [('"Turnover is more lower than last year."', False), ('"Turnover is lower than last year."', True), ('"Turnover is the lower than last year."', False)]),
   ("You name your top region. You say:",
    [('"The North is the most best region."', False), ('"The North is the best region."', True), ('"The North is a better region."', False)]),
   ("You describe what was happening last quarter. You say:",
    [('"Last quarter we were losing staff."', True), ('"Last quarter we was losing staff."', False), ('"Last quarter we losing staff."', False)]),
   ("You recommend a decision. You say:",
    [('"We should to invest in the North."', False), ('"We should invest in the North."', True), ('"We should invests in the North."', False)]),
 ],
 'think': ("Give a full data-to-decisions presentation about your own HR work. Compare this year with last year, name "
           "your best and weakest teams, quantify your resources, describe what was happening recently, and recommend "
           "what you should and could do next. Use all five Block 2 structures and at least four new words. Take your time."),
 'survival': [
   ("Overall, turnover is lower than last year.", "No geral, a rotatividade está menor que no ano passado."),
   ("The North is our best region.", "O Norte é a nossa melhor região."),
   ("We have many strong teams but little budget.", "Temos muitas equipes fortes, mas pouco orçamento."),
   ("Last quarter we were losing our best analysts.", "No trimestre passado estávamos perdendo nossos melhores analistas."),
   ("We should invest in the North.", "Deveríamos investir no Norte."),
 ],
 'comp_heading': "Block 2 Milestone -- Fluency Review: From Data to Decisions",
 'media': [
   ("podcast", "Podcast", "WorkLife with Adam Grant -- an episode on presenting data and making decisions",
    "Adam Grant discusses how leaders turn data into clear, persuasive decisions. You will hear comparisons, quantities, and recommendations woven together. Direct connection to Lesson 20: presenting from data to decisions.",
    "record a 60-second summary of your own HR data using all five Block 2 structures.", "Listen on TED", "https://www.ted.com/podcasts/worklife"),
   ("series", "Series", "Suits -- a scene where a lawyer presents a persuasive summary to win",
    "Watch a scene where a character delivers a clear, persuasive summary under pressure. Notice how comparisons, superlatives, and recommendations combine. Connection to Lesson 20: a persuasive data-to-decisions pitch.",
    "pause and say: Overall, this is our best option, and we should act now.", "View on IMDb", "https://www.imdb.com/title/tt1632701/"),
   ("youtube", "YouTube", '"How to Give a Clear Presentation" -- BBC Learning English',
    "A clear lesson on structuring a short, persuasive presentation, from summary to conclusion. Connection to Lesson 20: presenting HR data with clarity.",
    "pause and build a summary with overall, the best, and we should.", "Watch on BBC", "https://www.bbc.co.uk/learningenglish"),
 ],
 't': {
   's1': "<strong>Abertura (2 min):</strong> Aula 20 &mdash; Milestone do Bloco 2. Revisao de fluencia: comparativos, superlativos, quantifiers, past continuous e modais, aplicados a uma apresentacao de dados a decisoes + 12 palavras novas de sintese. Zero portugues na tela.",
   's2': "<strong>Hook (3 min):</strong> Pergunte: voce apresenta ao board amanha &mdash; em uma frase, qual e sua maior mensagem? Deixe a Murielle responder. NAO corrija ainda; anote quais estruturas do Bloco 2 ela usa.",
   's3': "<strong>Recall do Bloco 2 (3 min):</strong> Callback rapido das 5 estruturas: comparativo, superlativo, quantifier, past continuous, modal. Ponte: hoje voce junta TUDO numa apresentacao.",
   's4': "<strong>Transicao (1 min):</strong> Diga: para uma apresentacao clara e persuasiva voce precisa das palavras de sintese. Vamos construi-las.",
   'vocab1': "<strong>Vocabulario 1-6 (5 min):</strong> Drilling de cada card. PRONUNCIA: SUM-ma-rize, con-CLUDE, HIGH-light, EM-pha-size, ar-TI-cu-late, co-HE-rent. Pergunte: can you summarize the results?",
   'vocab2': "<strong>Vocabulario 7-12 (5 min):</strong> Mesmo processo. PRONUNCIA: con-CISE, per-SUA-sive, TAKE-away, STAND-point, o-ver-ALL, CLA-ri-ty. Peca uma frase com cada palavra.",
   's7': "<strong>Bloco 2 num relance (5 min):</strong> Duas colunas: COMPARAR e RANQUEAR (comparativos + superlativos) e QUANTIFICAR, NARRAR, ACONSELHAR (quantifiers + past continuous + modais). Leia a situacao e peca a frase ANTES de clicar Show.",
   's8': "<strong>Pronuncia (4 min):</strong> A Murielle e auditiva. Toque, ela ouve, repete 2-3x. Foco em ligar as estruturas numa fala fluida.",
   's9': "<strong>Transicao (1 min):</strong> Diga: agora a revisao &mdash; as cinco estruturas do Bloco 2 juntas.",
   's10': "<strong>Grammar Discovery (5 min):</strong> Leia cada exemplo e pergunte: which Block 2 structure is this? CCQ 1: lower than = comparative. CCQ 2: the best = superlative. CCQ 3: many/little = quantifier. CCQ 4: should = modal. So clique Reveal the Rule (tabela das 5 estruturas).",
   's11': "<strong>Common Mistake (3 min):</strong> Peca a correcao ANTES do verde. Um erro por area: (1) more lower (comparativo), (2) most best (superlativo), (3) much vacancies (quantifier), (4) should to decide (modal).",
   's12': "<strong>Grammar Practice (3 min):</strong> Peca a resposta em voz alta ANTES de clicar. A pista entre parenteses diz a estrutura (comparative/superlative/quantifier/past continuous/modal).",
   's13': "<strong>Build the Summary (3 min):</strong> Peca a frase completa em voz alta, uma por estrutura. So clique para comparar depois que ela tentar.",
   's14': "<strong>Transicao (1 min):</strong> Diga: hora de usar de verdade. Voce e Ethan, e a Murielle ensaia a apresentacao ao board.",
   's15': "<strong>Dialogo (6 min):</strong> Voce e Ethan treinando a Murielle. Clique Next Line um de cada vez. Reforce cada estrutura do Bloco 2. OBSTACULO: encadear comparativo, superlativo, quantifier, past continuous e modal.",
   's16': "<strong>Compreensao (3 min):</strong> Pergunte cada questao sobre a conversa. Espere a resposta ANTES de revelar.",
   'listen1': "<strong>Listening 1 (5 min):</strong> Treino de sotaque (voz masculina). Diga: listen without reading &mdash; an executive summarizes data and decisions. Toque 1x completo, depois 0.75x se precisar. So entao revele as perguntas.",
   'listen2': "<strong>Listening 2 (4 min):</strong> Voz feminina, diferente da listening 1. Uma gestora apresenta uma decisao de forma persuasiva. OBSTACULO: identificar as cinco estruturas do Bloco 2 numa fala fluida.",
   's19': "<strong>Artefato (3 min):</strong> Mostre o executive summary e peca a Murielle para ler cada linha em voz alta, identificando a estrutura do Bloco 2 em cada uma.",
   's20': "<strong>Transicao (1 min):</strong> Diga: voce tem as palavras, as cinco estruturas e um sumario real. Agora juntamos tudo numa apresentacao.",
   's21': "<strong>Quick Fire (4 min):</strong> Leia cada situacao e peca a frase (uma por estrutura) em voz alta ANTES de revelar. Ritmo rapido, maximo 30 segundos.",
   's22': "<strong>Detective (4 min):</strong> Peca a Murielle para achar o erro ANTES de clicar. Um erro por estrutura do Bloco 2.",
   's23': "<strong>Sentence Building (4 min):</strong> Mostre as palavras-chave e peca a frase completa em voz alta, uma por estrutura. Aceite variacoes corretas.",
   's24': "<strong>Transicao (1 min):</strong> Diga: agora o palco e seu, Murielle. Guiado, semi-livre e livre. Apresente e recomende.",
   's25': "<strong>Role-Play Guided (5 min):</strong> Voce e um membro do board. A Murielle apresenta os dados: compara, ranqueia e quantifica. Usa os chips. FOCO: comparativos, superlativos e quantifiers.",
   's26': "<strong>Role-Play Semi-Free (5 min):</strong> Menos apoio. A Murielle apresenta a recomendacao: conta o que estava acontecendo (past continuous) e o que deveria/poderia fazer (modais).",
   's27': "<strong>Free Practice (5 min):</strong> Sem script. A Murielle faz uma apresentacao completa de dados a decisoes do proprio RH, usando as 5 estruturas. NAO corrija durante a fala (delayed feedback). Anote 3-5 erros.",
   's28': "<strong>Delayed Feedback (5 min):</strong> Compartilhe 3-5 erros do role-play livre. Para cada: diga o que ela falou, peca a correcao, de a versao correta se preciso, peca 2x. Use o campo editavel.",
   's29': "<strong>Key Phrases (3 min):</strong> Leia cada frase e peca repeticao. Uma frase por estrutura do Bloco 2.",
   's30': "<strong>Checklist + Encerramento (3 min):</strong> Leia cada item: can you do this? Marque os confirmados. 5/5 conclui a aula E o Bloco 2. Homework: gravar uma apresentacao de 10-12 frases de dados a decisoes usando as 5 estruturas e 5 palavras novas. Preview: Next class &mdash; Block 3, storytelling in HR.",
   's31': "<strong>Encerramento (1 min):</strong> Diga: fantastic work, Murielle! You finished Block 2 &mdash; you can now present HR data and decisions with fluency. Celebre. Preview: Next class &mdash; What Was Happening, storytelling in HR.",
 },
}

if __name__ == '__main__':
    genlib.build(D)
