# -*- coding: utf-8 -*-
"""Curriculo AUTORAL de 96 aulas — Ricardo de Sales Coutinho (A0, 2x/semana, 12 meses).

O endpoint /api/gerar-temas nao respondeu em 40 min (falha conhecida), entao o programa
foi escrito a mao, em blocos, com progressao A0 -> B1 funcional ancorada no evento-alvo:
a abertura da operacao do Banco BS2 na Florida entre o 2o sem/2027 e o 1o sem/2028.

REGRA 29: aula IMPAR = FALA (dialogo + role-play) · aula PAR = LEITURA (ic-reading + T/F).
VARIEDADE DE DOMINIO: cada aula tem UM territorio distinto da vida/trabalho dele.
Marcos (checkpoint) em 5, 10, 20, 30, 40, 50, 60, 70, 80, 90 e 96.

Cada tupla: (tema, foco linguistico, atividade principal, homework oral/passivo)
"""

CURRICULO = [
    # ============ BLOCO 1 (1-10) — A0: o chao. O que ele e, quem esta ao redor. ============
    ("Who You Are at the Bank &mdash; nome, cargo, banco e escrit&oacute;rio",
     "Verb to be afirmativo (am / is / are) + artigo a/an",
     "Di&aacute;logo de primeira call com o escrit&oacute;rio de Miami + role-play de apresenta&ccedil;&atilde;o",
     "Ouvir o &aacute;udio da Diane no metr&ocirc; + ler a letra de uma m&uacute;sica de rock antes da tradu&ccedil;&atilde;o"),
    ("My Team &mdash; as 25 pessoas da &aacute;rea comercial",
     "There is / there are + n&uacute;meros de 1 a 100 + plural de substantivos",
     "Leitura de uma ficha da equipe do banco + true/false sobre a estrutura",
     "Contar em ingl&ecirc;s quantos andares tem o pr&eacute;dio, no elevador"),
    ("My Morning &mdash; academia, banho e caf&eacute; antes das sete",
     "Present simple com I e you + horas (at six o'clock, at half past six)",
     "Di&aacute;logo sobre a rotina da manh&atilde; + role-play com um colega americano",
     "&Aacute;udio de 30 segundos narrando a pr&oacute;pria manh&atilde;"),
    ("The Ride &mdash; de Santana &agrave; Vila Ol&iacute;mpia, de metr&ocirc; e trem",
     "Preposi&ccedil;&otilde;es de lugar e movimento (from, to, by, at, on, near)",
     "Leitura de um aviso de esta&ccedil;&atilde;o + true/false sobre o trajeto",
     "Descrever o trajeto em voz alta, dentro do trem"),
    ("My Family &mdash; a esposa e a filha na escola bil&iacute;ngue",
     "Present simple na 3&ordf; pessoa (-s) + possessivos my, his, her",
     "Di&aacute;logo sobre a fam&iacute;lia + role-play de conversa informal",
     "&Aacute;udio de 5 frases sobre a filha e a esposa"),
    ("Rock in English &mdash; a banda, a m&uacute;sica e a letra",
     "Present simple negativo (don't / doesn't) com like e love",
     "Leitura de um texto curto sobre uma banda + true/false",
     "Ler a letra de uma m&uacute;sica em ingl&ecirc;s ANTES de abrir o tradutor"),
    ("Dollars and Reais &mdash; comprar e vender c&acirc;mbio para o cliente",
     "Perguntas com do / does + short answers (Yes, I do / No, he doesn't)",
     "Di&aacute;logo com um cliente + role-play de atendimento comercial",
     "&Aacute;udio de 60 segundos explicando o que a &aacute;rea dele faz"),
    ("The New Office &mdash; como &eacute; o escrit&oacute;rio da Fl&oacute;rida",
     "Adjetivos com to be (big, small, new, near) + very",
     "Leitura de um e-mail do diretor + true/false sobre o novo escrit&oacute;rio",
     "Descrever o pr&oacute;prio escrit&oacute;rio em quatro frases"),
    ("Sorry, Can You Repeat? &mdash; o que dizer quando n&atilde;o entende",
     "can / can't &mdash; habilidade e pedido educado (Can you repeat, please?)",
     "Di&aacute;logo de call com ru&iacute;do + role-play de pedido de repeti&ccedil;&atilde;o",
     "Dizer 'Can you repeat, please?' uma vez em voz alta, sozinho"),
    ("Miami, Gate 12 &mdash; aeroporto e imigra&ccedil;&atilde;o na chegada",
     "Question words: What, Where, Who, How long",
     "Leitura de um cart&atilde;o de embarque e de um formul&aacute;rio de imigra&ccedil;&atilde;o + true/false",
     "Ouvir o &aacute;udio do oficial de imigra&ccedil;&atilde;o duas vezes"),

    # ============ BLOCO 2 (11-20) — A0/A1: o entorno. Agenda, casa, comida, pre&ccedil;o. ============
    ("Coffee Break &mdash; os primeiros trinta segundos com um colega",
     "Verb to be em pergunta e negativa (Are you...? / I am not)",
     "Di&aacute;logo de corredor + role-play de small talk curt&iacute;ssimo",
     "&Aacute;udio de 30 segundos respondendo tr&ecirc;s perguntas de small talk"),
    ("Monday and Wednesday &mdash; a semana do banco no calend&aacute;rio",
     "Dias, meses e datas + preposi&ccedil;&otilde;es on / in",
     "Leitura de uma agenda semanal + true/false sobre compromissos",
     "Dizer a agenda da semana em voz alta, na segunda de manh&atilde;"),
    ("The Weekend &mdash; parque, shopping e a viagem curta",
     "Present simple em pergunta (What do you...? Where do you...?)",
     "Di&aacute;logo sobre o fim de semana + role-play de convite",
     "&Aacute;udio de 60 segundos sobre o pr&oacute;ximo s&aacute;bado"),
    ("The People I Work With &mdash; descrever quem est&aacute; na mesa ao lado",
     "Adjetivos de pessoa (tall, quiet, new, experienced) + word order",
     "Leitura de tr&ecirc;s perfis curtos da equipe + true/false",
     "Descrever tr&ecirc;s colegas em ingl&ecirc;s, mentalmente, no metr&ocirc;"),
    ("First Month Done &mdash; primeiro marco de confian&ccedil;a",
     "Revis&atilde;o integrada das aulas 1-14 (to be, there is/are, present simple)",
     "Simula&ccedil;&atilde;o de 10 minutos: apresentar-se e apresentar a &aacute;rea",
     "&Aacute;udio-marco de 90 segundos: quem sou eu e o que minha &aacute;rea faz"),
    ("Home in Santana &mdash; a casa, o bairro e a Zona Norte",
     "Genitivo com 's + this / that / these / those",
     "Leitura de um an&uacute;ncio de im&oacute;vel + true/false sobre o apartamento",
     "Descrever a pr&oacute;pria casa em cinco frases"),
    ("Nine to Six &mdash; os hor&aacute;rios do banco e o fuso de Miami",
     "Preposi&ccedil;&otilde;es de tempo (at / in / on) + time zones",
     "Di&aacute;logo de agendamento entre S&atilde;o Paulo e Miami + role-play",
     "Converter tr&ecirc;s hor&aacute;rios de reuni&atilde;o para o fuso de Miami, em voz alta"),
    ("Lunch Near the Office &mdash; pedir comida sem apontar para o card&aacute;pio",
     "I'd like / Can I have + contaveis e incont&aacute;veis (a, some, any)",
     "Leitura de um card&aacute;pio americano + true/false sobre pre&ccedil;os e pratos",
     "Fazer o pedido do almo&ccedil;o mentalmente em ingl&ecirc;s, na fila"),
    ("How Much Is It? &mdash; compras e pre&ccedil;os em d&oacute;lar",
     "How much / How many + n&uacute;meros altos e centavos",
     "Di&aacute;logo de compra + role-play de pagamento com cart&atilde;o",
     "Ler cinco pre&ccedil;os em d&oacute;lar em voz alta"),
    ("Your First Week in Miami &mdash; simula&ccedil;&atilde;o completa (marco)",
     "Marco do bloco: tudo das aulas 1-19 integrado, sem apoio na tela",
     "Cinco cenas seguidas: aeroporto, hotel, escrit&oacute;rio, almo&ccedil;o e call",
     "&Aacute;udio-marco de 2 minutos contando a primeira semana imagin&aacute;ria"),

    # ============ BLOCO 3 (21-30) — A1: o passado. Contar a pr&oacute;pria hist&oacute;ria. ============
    ("Florida, Three Times &mdash; as viagens que ele j&aacute; fez aos EUA",
     "Simple past do verbo to be: was / were (afirmativo, negativo, pergunta)",
     "Di&aacute;logo sobre viagens passadas + role-play de conversa de aeroporto",
     "&Aacute;udio de 90 segundos sobre a viagem a Nova York"),
    ("New York, 2016 &mdash; o que aconteceu naquela viagem",
     "Simple past regular (-ed): pron&uacute;ncia dos tr&ecirc;s finais (/t/, /d/, /id/)",
     "Leitura de um di&aacute;rio de viagem + true/false sobre o que aconteceu",
     "Ler o pr&oacute;prio hist&oacute;rico de viagens e marcar tr&ecirc;s verbos no passado"),
    ("Since 1998 &mdash; a carreira no c&acirc;mbio, do come&ccedil;o at&eacute; hoje",
     "Simple past irregular de alta frequ&ecirc;ncia (went, had, made, got, took, began)",
     "Di&aacute;logo de entrevista informal + role-play de contar a trajet&oacute;ria",
     "&Aacute;udio de 2 minutos com a linha do tempo da carreira"),
    ("The School I Left &mdash; a Cultura Inglesa e o que deu errado",
     "Passado negativo e interrogativo (didn't / Did you...?)",
     "Di&aacute;logo sobre experi&ecirc;ncias de estudo + role-play de conselho a um colega",
     "&Aacute;udio de 60 segundos com tr&ecirc;s frases sobre o que n&atilde;o funcionou antes"),
    ("Yesterday at the Bank &mdash; o dia de ontem, hora a hora",
     "Express&otilde;es de tempo do passado (yesterday, last week, two years ago)",
     "Di&aacute;logo de retrospectiva de dia + role-play de reporte ao diretor",
     "&Aacute;udio de 90 segundos narrando o dia anterior"),
    ("The Trade That Went Wrong &mdash; uma opera&ccedil;&atilde;o que n&atilde;o fechou",
     "Conectores de narrativa (and, but, because, then, so)",
     "Leitura de um relato curto de incidente + true/false sobre o que houve",
     "Contar mentalmente, em ingl&ecirc;s, um problema real da semana"),
    ("MBA and After &mdash; os cursos que ele escolheu no lugar do ingl&ecirc;s",
     "There was / there were + past of to be no plural",
     "Di&aacute;logo sobre forma&ccedil;&atilde;o + role-play de apresenta&ccedil;&atilde;o de curr&iacute;culo oral",
     "&Aacute;udio de 60 segundos sobre a pr&oacute;pria forma&ccedil;&atilde;o"),
    ("Maple Bear &mdash; a filha de dez anos e a escola bil&iacute;ngue",
     "Comparativos (bigger, better, easier) + than",
     "Leitura de uma comunica&ccedil;&atilde;o da escola + true/false sobre o calend&aacute;rio",
     "Comparar em ingl&ecirc;s a escola da filha com a escola dele, em tr&ecirc;s frases"),
    ("Car or Subway &mdash; duas horas de carro contra uma de metr&ocirc;",
     "Comparativos e superlativos (the fastest, the best, the worst)",
     "Di&aacute;logo de compara&ccedil;&atilde;o de op&ccedil;&otilde;es + role-play de recomenda&ccedil;&atilde;o",
     "&Aacute;udio de 60 segundos comparando carro, metr&ocirc; e trem"),
    ("This Is My Story &mdash; a trajet&oacute;ria em dois minutos (marco)",
     "Marco do bloco: passado integrado, narrativa aut&ocirc;noma sem apoio",
     "Produ&ccedil;&atilde;o livre de 2 minutos: de 1998 at&eacute; o convite para a Fl&oacute;rida",
     "&Aacute;udio-marco de 2 minutos comparado com a grava&ccedil;&atilde;o do Dia 1"),

    # ============ BLOCO 4 (31-40) — A1/A2: o futuro. O plano e a agenda. ============
    ("Eighteen Months &mdash; o plano at&eacute; a autoriza&ccedil;&atilde;o sair",
     "be going to (afirmativo, negativo, interrogativo) para planos",
     "Di&aacute;logo de planejamento com o diretor + role-play de compromisso",
     "&Aacute;udio de 90 segundos com o plano dos pr&oacute;ximos seis meses"),
    ("The Quarter Ahead &mdash; o calend&aacute;rio do trimestre",
     "Futuro em agenda (present continuous com valor de futuro)",
     "Leitura de um calend&aacute;rio corporativo + true/false sobre prazos",
     "Ler a pr&oacute;pria agenda do m&ecirc;s em ingl&ecirc;s, uma vez"),
    ("Shall We Meet? &mdash; marcar reuni&atilde;o com Miami",
     "will para decis&otilde;es do momento + ofertas e sugest&otilde;es",
     "Di&aacute;logo de agendamento + role-play de remarcar uma reuni&atilde;o",
     "&Aacute;udio de 60 segundos propondo tr&ecirc;s hor&aacute;rios"),
    ("Time Zones &mdash; nove da manh&atilde; aqui, oito l&aacute;",
     "Express&otilde;es de tempo relativas (in two hours, the day after tomorrow)",
     "Leitura de um convite de reuni&atilde;o com fuso + true/false",
     "Calcular tr&ecirc;s hor&aacute;rios entre S&atilde;o Paulo e Miami, em ingl&ecirc;s"),
    ("Halfway to A2 &mdash; segundo marco de confian&ccedil;a",
     "Revis&atilde;o integrada 21-34: passado e futuro na mesma conversa",
     "Simula&ccedil;&atilde;o de 10 minutos: contar o passado e apresentar o plano",
     "&Aacute;udio-marco de 2 minutos: onde eu estava, onde eu estou, onde eu vou"),
    ("The Business Plan &mdash; o documento que vai ao Banco Central americano",
     "Vocabul&aacute;rio de projeto (deadline, approval, budget, stage) + futuro",
     "Leitura de um resumo executivo + true/false sobre etapas e prazos",
     "Ler em voz alta cinco termos do projeto e dizer o que cada um significa"),
    ("Could You, Please? &mdash; pedir e oferecer sem soar seco",
     "Can / Could / Would you mind + registro formal e informal",
     "Di&aacute;logo de pedido a um par nos EUA + role-play de tr&ecirc;s pedidos",
     "&Aacute;udio de 60 segundos com tr&ecirc;s pedidos educados"),
    ("The Short Email &mdash; tr&ecirc;s linhas que resolvem",
     "Estrutura de e-mail curto: abertura, pedido, fechamento",
     "Leitura de tr&ecirc;s e-mails reais de trabalho + true/false sobre a inten&ccedil;&atilde;o",
     "Escrever mentalmente um e-mail de tr&ecirc;s linhas para a Diane"),
    ("On the Phone &mdash; atender, entender o nome e transferir",
     "Linguagem de telefone (Speaking, hold on, put you through) + soletrar",
     "Di&aacute;logo telef&ocirc;nico com ru&iacute;do + role-play de recado",
     "Soletrar o pr&oacute;prio nome e o do banco em voz alta"),
    ("Forty Down &mdash; a metade do caminho (marco)",
     "Marco do bloco: produ&ccedil;&atilde;o aut&ocirc;noma com passado, presente e futuro",
     "Simula&ccedil;&atilde;o de 15 minutos: uma call inteira com o escrit&oacute;rio de Miami",
     "&Aacute;udio-marco de 3 minutos: relat&oacute;rio oral do trimestre"),

    # ============ BLOCO 5 (41-50) — A2: o trabalho ao vivo. Reuni&atilde;o e processo. ============
    ("Right Now on the Desk &mdash; o que est&aacute; acontecendo neste minuto",
     "Present continuous x present simple (agora x sempre)",
     "Di&aacute;logo de status r&aacute;pido + role-play de reporte ao vivo",
     "&Aacute;udio de 60 segundos narrando o que est&aacute; acontecendo na mesa"),
    ("The Daily Report &mdash; o n&uacute;mero do dia em uma p&aacute;gina",
     "Ler n&uacute;meros, varia&ccedil;&otilde;es e percentuais (up, down, by, from... to)",
     "Leitura de um relat&oacute;rio di&aacute;rio + true/false sobre os n&uacute;meros",
     "Ler os n&uacute;meros do dia em voz alta, em ingl&ecirc;s"),
    ("I Agree, I Don't &mdash; concordar e discordar numa reuni&atilde;o",
     "Express&otilde;es de concord&acirc;ncia e discord&acirc;ncia + softening (I think, maybe)",
     "Di&aacute;logo de reuni&atilde;o com duas posi&ccedil;&otilde;es + role-play de posicionamento",
     "&Aacute;udio de 60 segundos discordando de uma proposta, com educa&ccedil;&atilde;o"),
    ("Who Reports to Whom &mdash; o organograma do banco novo",
     "Voz ativa em descri&ccedil;&atilde;o de estrutura + report to / be responsible for",
     "Leitura de um organograma comentado + true/false sobre a hierarquia",
     "Descrever mentalmente o pr&oacute;prio organograma em ingl&ecirc;s"),
    ("Meeting Ready &mdash; terceiro marco de confian&ccedil;a",
     "Revis&atilde;o integrada 41-44: presente, n&uacute;meros e posicionamento",
     "Simula&ccedil;&atilde;o de reuni&atilde;o de 15 minutos com tr&ecirc;s pontos de pauta",
     "&Aacute;udio-marco de 2 minutos: abrir e fechar uma reuni&atilde;o"),
    ("How It Works &mdash; explicar uma opera&ccedil;&atilde;o de c&acirc;mbio passo a passo",
     "Sequenciadores (first, then, after that, finally) + present simple de processo",
     "Di&aacute;logo de explica&ccedil;&atilde;o a um par americano + role-play de treinamento",
     "&Aacute;udio de 2 minutos explicando uma opera&ccedil;&atilde;o do in&iacute;cio ao fim"),
    ("Do This, Not That &mdash; dar instru&ccedil;&atilde;o clara &agrave; equipe",
     "Imperativo + should / need to em instru&ccedil;&atilde;o de trabalho",
     "Di&aacute;logo de delega&ccedil;&atilde;o + role-play de instru&ccedil;&atilde;o a um analista novo",
     "&Aacute;udio de 60 segundos instruindo um colega imagin&aacute;rio"),
    ("The Policy &mdash; a norma interna que ningu&eacute;m l&ecirc;",
     "Linguagem normativa (must, must not, is required to) na leitura",
     "Leitura de uma pol&iacute;tica de compliance + true/false sobre o que &eacute; permitido",
     "Ler uma norma real do banco e achar tr&ecirc;s obriga&ccedil;&otilde;es"),
    ("The Client Is Not Happy &mdash; resolver um problema ao telefone",
     "Linguagem de desculpa e solu&ccedil;&atilde;o (I'm sorry, let me check, I'll get back to you)",
     "Di&aacute;logo de atendimento dif&iacute;cil + role-play de recupera&ccedil;&atilde;o de cliente",
     "&Aacute;udio de 90 segundos resolvendo uma reclama&ccedil;&atilde;o"),
    ("Fifty &mdash; metade do programa (marco)",
     "Marco: 50 aulas. Produ&ccedil;&atilde;o aut&ocirc;noma em contexto profissional real",
     "Simula&ccedil;&atilde;o de 20 minutos: reuni&atilde;o de status com Miami, sem apoio",
     "&Aacute;udio-marco de 3 minutos comparado com a grava&ccedil;&atilde;o da aula 30"),

    # ============ BLOCO 6 (51-60) — A2: regra, obriga&ccedil;&atilde;o e a mudan&ccedil;a de vida. ============
    ("What the Bank Must Do &mdash; obriga&ccedil;&otilde;es de uma institui&ccedil;&atilde;o",
     "have to / must / don't have to &mdash; obriga&ccedil;&atilde;o e aus&ecirc;ncia de obriga&ccedil;&atilde;o",
     "Di&aacute;logo sobre regras do banco + role-play de explica&ccedil;&atilde;o a um cliente",
     "&Aacute;udio de 90 segundos com cinco obriga&ccedil;&otilde;es da &aacute;rea dele"),
    ("The System Manual &mdash; a tela do sistema em ingl&ecirc;s",
     "Vocabul&aacute;rio de interface (enter, submit, approve, cancel, log in)",
     "Leitura de um passo a passo de sistema + true/false sobre a sequ&ecirc;ncia",
     "Trocar o idioma do celular para ingl&ecirc;s por um dia"),
    ("Allowed or Not &mdash; permiss&atilde;o e proibi&ccedil;&atilde;o no ambiente americano",
     "can / can't / be allowed to em contexto regulat&oacute;rio e social",
     "Di&aacute;logo sobre o que pode e o que n&atilde;o pode + role-play de esclarecimento",
     "&Aacute;udio de 60 segundos com tr&ecirc;s coisas permitidas e tr&ecirc;s proibidas"),
    ("The Lease &mdash; o contrato do escrit&oacute;rio em Miami",
     "Vocabul&aacute;rio de contrato (term, deposit, notice, renew) + n&uacute;meros e datas",
     "Leitura de um contrato simplificado + true/false sobre prazos e valores",
     "Ler um contrato curto em ingl&ecirc;s e achar a data de vencimento"),
    ("Rules and Reality &mdash; quarto marco de confian&ccedil;a",
     "Revis&atilde;o integrada 51-54: modais de obriga&ccedil;&atilde;o e permiss&atilde;o",
     "Simula&ccedil;&atilde;o de 15 minutos: explicar as regras da &aacute;rea a um novo gerente",
     "&Aacute;udio-marco de 2 minutos sobre o que o banco pode e n&atilde;o pode fazer"),
    ("A Word of Advice &mdash; orientar um colega rec&eacute;m-chegado",
     "should / shouldn't + why em conselho profissional",
     "Di&aacute;logo de mentoria + role-play de conselho a um trainee",
     "&Aacute;udio de 90 segundos com tr&ecirc;s conselhos a quem chega ao banco"),
    ("Health Plan and Insurance &mdash; o que muda ao morar nos EUA",
     "Vocabul&aacute;rio de sa&uacute;de e seguro (coverage, deductible, claim, provider)",
     "Leitura de um resumo de plano de sa&uacute;de + true/false sobre cobertura",
     "Ler o pr&oacute;prio plano de sa&uacute;de e achar tr&ecirc;s palavras conhecidas"),
    ("Opening an Account &mdash; do outro lado do balc&atilde;o, nos EUA",
     "Linguagem banc&aacute;ria pessoal (checking, savings, routing number, statement)",
     "Di&aacute;logo de abertura de conta + role-play como CLIENTE, n&atilde;o como gerente",
     "&Aacute;udio de 90 segundos abrindo uma conta imagin&aacute;ria"),
    ("Moving the Family &mdash; casa, escola e carro na Fl&oacute;rida",
     "Futuro e obriga&ccedil;&atilde;o combinados (we will have to, we are going to need)",
     "Di&aacute;logo com um corretor + role-play de decis&atilde;o em fam&iacute;lia",
     "&Aacute;udio de 2 minutos sobre a mudan&ccedil;a da fam&iacute;lia"),
    ("Relocation &mdash; a mudan&ccedil;a inteira, em uma simula&ccedil;&atilde;o (marco)",
     "Marco do bloco: modais, futuro e vocabul&aacute;rio de vida real integrados",
     "Simula&ccedil;&atilde;o de 20 minutos: seis cenas da mudan&ccedil;a para a Fl&oacute;rida",
     "&Aacute;udio-marco de 3 minutos: o plano de mudan&ccedil;a da fam&iacute;lia"),

    # ============ BLOCO 7 (61-70) — A2/B1: experi&ecirc;ncia, carreira e negocia&ccedil;&atilde;o. ============
    ("Twenty-Seven Years in FX &mdash; experi&ecirc;ncia que n&atilde;o cabe no passado simples",
     "Present perfect (have worked, have been) + since / for",
     "Di&aacute;logo de apresenta&ccedil;&atilde;o profissional + role-play de networking",
     "&Aacute;udio de 90 segundos come&ccedil;ando com 'I have worked in FX since 1998'"),
    ("The Resume &mdash; o curr&iacute;culo dele em ingl&ecirc;s",
     "Verbos de a&ccedil;&atilde;o de curr&iacute;culo (led, built, managed, delivered)",
     "Leitura de dois curr&iacute;culos + true/false sobre trajet&oacute;ria e resultados",
     "Ler o pr&oacute;prio curr&iacute;culo e traduzir tr&ecirc;s linhas mentalmente"),
    ("Tell Me About Yourself &mdash; a pergunta que abre toda entrevista",
     "Estrutura de resposta em tr&ecirc;s partes (now / then / next)",
     "Di&aacute;logo de entrevista + role-play com perguntas fora de ordem",
     "&Aacute;udio de 2 minutos respondendo 'tell me about yourself'"),
    ("The LinkedIn Profile &mdash; como um americano l&ecirc; o perfil dele",
     "Linguagem de perfil profissional + adjetivos de senioridade",
     "Leitura de dois perfis + true/false sobre senioridade e escopo",
     "Reescrever mentalmente o pr&oacute;prio headline em ingl&ecirc;s"),
    ("Ready to Be Asked &mdash; quinto marco de confian&ccedil;a",
     "Revis&atilde;o integrada 61-64: present perfect e narrativa de carreira",
     "Simula&ccedil;&atilde;o de entrevista de 15 minutos, sem apoio na tela",
     "&Aacute;udio-marco de 3 minutos: entrevista completa"),
    ("Have You Ever? &mdash; o que ele j&aacute; fez e o que nunca fez",
     "ever / never / already / yet com present perfect",
     "Di&aacute;logo de troca de experi&ecirc;ncias + role-play de conversa de evento",
     "&Aacute;udio de 90 segundos com tr&ecirc;s 'I have never' verdadeiros"),
    ("The Economy in English &mdash; a not&iacute;cia que ele j&aacute; l&ecirc; em portugu&ecirc;s",
     "Vocabul&aacute;rio macro (inflation, interest rate, exchange rate, growth)",
     "Leitura de uma not&iacute;cia curta de economia + true/false sobre a manchete",
     "Assistir a um v&iacute;deo de economia em ingl&ecirc;s com legenda em ingl&ecirc;s"),
    ("Price and Deadline &mdash; negociar sem perder a rela&ccedil;&atilde;o",
     "Linguagem de negocia&ccedil;&atilde;o (if you..., we could..., that works for us)",
     "Di&aacute;logo de negocia&ccedil;&atilde;o + role-play de fechamento de spread",
     "&Aacute;udio de 90 segundos negociando um prazo"),
    ("I See Your Point, But &mdash; discordar de quem est&aacute; acima",
     "Discord&acirc;ncia diplom&aacute;tica + hedging (it seems, perhaps, I'd say)",
     "Di&aacute;logo com o diretor + role-play de posi&ccedil;&atilde;o contr&aacute;ria",
     "&Aacute;udio de 90 segundos discordando do pr&oacute;prio chefe, com respeito"),
    ("Meeting the Board &mdash; a conversa que decide a Fl&oacute;rida (marco)",
     "Marco do bloco: present perfect, negocia&ccedil;&atilde;o e posicionamento integrados",
     "Simula&ccedil;&atilde;o de 20 minutos: apresentar-se e defender o projeto ao board",
     "&Aacute;udio-marco de 3 minutos: pitch de carreira e de projeto"),

    # ============ BLOCO 8 (71-80) — B1: hip&oacute;tese, risco e n&uacute;mero. ============
    ("If the Fed Approves &mdash; o que acontece quando sair a autoriza&ccedil;&atilde;o",
     "First conditional (if + present, will) para cen&aacute;rios reais",
     "Di&aacute;logo de planejamento condicional + role-play de contingente",
     "&Aacute;udio de 90 segundos com tr&ecirc;s cen&aacute;rios reais do projeto"),
    ("The Regulator's Letter &mdash; o parecer que chega em ingl&ecirc;s formal",
     "Registro formal escrito + linguagem regulat&oacute;ria (pursuant to, subject to)",
     "Leitura de uma carta regulat&oacute;ria simplificada + true/false sobre exig&ecirc;ncias",
     "Ler uma comunica&ccedil;&atilde;o oficial em ingl&ecirc;s e achar a exig&ecirc;ncia principal"),
    ("What If &mdash; cen&aacute;rios que ainda n&atilde;o existem",
     "Second conditional (if + past, would) para hip&oacute;tese",
     "Di&aacute;logo de an&aacute;lise de cen&aacute;rio + role-play de comit&ecirc; de risco",
     "&Aacute;udio de 90 segundos com dois cen&aacute;rios hipot&eacute;ticos"),
    ("Currency Risk &mdash; o risco que ele conhece de cor, agora em ingl&ecirc;s",
     "Vocabul&aacute;rio de risco (exposure, hedge, volatility, mitigate)",
     "Leitura de um memorando de risco + true/false sobre exposi&ccedil;&atilde;o",
     "Explicar mentalmente, em ingl&ecirc;s, o risco de uma opera&ccedil;&atilde;o real"),
    ("Thinking in Scenarios &mdash; sexto marco de confian&ccedil;a",
     "Revis&atilde;o integrada 71-74: condicionais e linguagem de risco",
     "Simula&ccedil;&atilde;o de comit&ecirc; de 15 minutos com tr&ecirc;s cen&aacute;rios",
     "&Aacute;udio-marco de 3 minutos: an&aacute;lise de cen&aacute;rio em ingl&ecirc;s"),
    ("Reading the Chart &mdash; apresentar n&uacute;mero sem ler slide",
     "Linguagem de gr&aacute;fico (rose, fell, peaked, remained stable) + tend&ecirc;ncia",
     "Di&aacute;logo de apresenta&ccedil;&atilde;o + role-play de leitura de gr&aacute;fico ao vivo",
     "&Aacute;udio de 2 minutos apresentando um gr&aacute;fico real da &aacute;rea dele"),
    ("The Quarterly Report &mdash; vinte p&aacute;ginas, tr&ecirc;s informa&ccedil;&otilde;es",
     "Leitura seletiva (skimming e scanning) em texto financeiro",
     "Leitura de um relat&oacute;rio trimestral + true/false sobre resultado e risco",
     "Achar tr&ecirc;s n&uacute;meros em um relat&oacute;rio real em ingl&ecirc;s, em cinco minutos"),
    ("The Hard Question &mdash; responder o que ele n&atilde;o esperava",
     "Ganhar tempo (that's a good question, let me think) + resposta parcial",
     "Di&aacute;logo com perguntas imprevistas + role-play de press&atilde;o",
     "&Aacute;udio de 90 segundos respondendo tr&ecirc;s perguntas dif&iacute;ceis"),
    ("Holding Your Ground &mdash; sustentar uma posi&ccedil;&atilde;o t&eacute;cnica",
     "Argumenta&ccedil;&atilde;o (the reason is, based on, according to) + evid&ecirc;ncia",
     "Di&aacute;logo de defesa t&eacute;cnica + role-play de discuss&atilde;o com o regulador",
     "&Aacute;udio de 2 minutos defendendo uma decis&atilde;o t&eacute;cnica"),
    ("Presenting the Business Plan &mdash; a apresenta&ccedil;&atilde;o que vale a opera&ccedil;&atilde;o (marco)",
     "Marco do bloco: condicionais, n&uacute;meros e argumenta&ccedil;&atilde;o integrados",
     "Simula&ccedil;&atilde;o de 25 minutos: apresentar o business plan e responder perguntas",
     "&Aacute;udio-marco de 4 minutos: apresenta&ccedil;&atilde;o completa"),

    # ============ BLOCO 9 (81-90) — B1: liderar gente em ingl&ecirc;s. ============
    ("He Said, She Said &mdash; relatar o que o diretor decidiu",
     "Reported speech (said that, told me to) + mudan&ccedil;a de tempo verbal",
     "Di&aacute;logo de repasse de decis&atilde;o + role-play de alinhamento com a equipe",
     "&Aacute;udio de 90 segundos relatando uma conversa real"),
    ("The Minutes &mdash; a ata que resume duas horas em uma p&aacute;gina",
     "Linguagem de ata (it was agreed, action items, owner, due date)",
     "Leitura de uma ata de reuni&atilde;o + true/false sobre respons&aacute;veis e prazos",
     "Ler uma ata em ingl&ecirc;s e achar as tr&ecirc;s a&ccedil;&otilde;es dele"),
    ("The Process Is Approved &mdash; quando o autor da a&ccedil;&atilde;o n&atilde;o importa",
     "Voz passiva (is approved, was sent, will be reviewed) em processo e norma",
     "Di&aacute;logo de descri&ccedil;&atilde;o de fluxo + role-play de explica&ccedil;&atilde;o de processo",
     "&Aacute;udio de 90 segundos descrevendo um fluxo do banco na passiva"),
    ("The Job Description &mdash; a vaga que ele vai abrir em Miami",
     "Vocabul&aacute;rio de recrutamento (requirements, background, reporting line)",
     "Leitura de duas job descriptions + true/false sobre requisitos",
     "Escrever mentalmente tr&ecirc;s requisitos da vaga que ele vai abrir"),
    ("Leading in English &mdash; s&eacute;timo marco de confian&ccedil;a",
     "Revis&atilde;o integrada 81-84: reported speech, passiva e linguagem de gest&atilde;o",
     "Simula&ccedil;&atilde;o de 20 minutos: repassar uma decis&atilde;o e abrir uma vaga",
     "&Aacute;udio-marco de 3 minutos: comunicado de decis&atilde;o &agrave; equipe"),
    ("The Interview &mdash; do outro lado da mesa, escolhendo gente",
     "Perguntas de entrevista + follow-up questions + avaliar resposta",
     "Di&aacute;logo de entrevista conduzida por ele + role-play de dois candidatos",
     "&Aacute;udio de 2 minutos com cinco perguntas de entrevista"),
    ("Written Feedback &mdash; a avalia&ccedil;&atilde;o que fica registrada",
     "Linguagem de avalia&ccedil;&atilde;o (strengths, areas for development, next steps)",
     "Leitura de duas avalia&ccedil;&otilde;es de desempenho + true/false sobre o julgamento",
     "Ler uma avalia&ccedil;&atilde;o em ingl&ecirc;s e identificar elogio e cr&iacute;tica"),
    ("The Difficult Conversation &mdash; performance abaixo do esperado",
     "Cr&iacute;tica construtiva + softening + acordo de a&ccedil;&atilde;o",
     "Di&aacute;logo de conversa dif&iacute;cil + role-play de feedback a um gerente",
     "&Aacute;udio de 2 minutos dando um feedback dif&iacute;cil"),
    ("Running the Room &mdash; conduzir uma reuni&atilde;o do come&ccedil;o ao fim",
     "Linguagem de condu&ccedil;&atilde;o (let's move on, to sum up, any questions)",
     "Di&aacute;logo de reuni&atilde;o inteira + role-play de facilita&ccedil;&atilde;o",
     "&Aacute;udio de 3 minutos abrindo, conduzindo e fechando uma reuni&atilde;o"),
    ("Building the Team &mdash; montar a equipe americana (marco)",
     "Marco do bloco: gest&atilde;o de pessoas em ingl&ecirc;s, sem apoio",
     "Simula&ccedil;&atilde;o de 25 minutos: entrevista, decis&atilde;o e comunicado &agrave; equipe",
     "&Aacute;udio-marco de 4 minutos: plano de time para Miami"),

    # ============ BLOCO 10 (91-96) — B1: a Fl&oacute;rida, ao vivo. ============
    ("Day One in Miami &mdash; a primeira manh&atilde; no escrit&oacute;rio novo",
     "Integra&ccedil;&atilde;o oral: apresenta&ccedil;&atilde;o, small talk e alinhamento no mesmo bloco",
     "Di&aacute;logo de primeiro dia + role-play com tr&ecirc;s pessoas diferentes",
     "&Aacute;udio de 2 minutos: as primeiras tr&ecirc;s conversas do primeiro dia"),
    ("The Official Filing &mdash; a comunica&ccedil;&atilde;o formal ao regulador",
     "Registro formal escrito de alto n&iacute;vel + precis&atilde;o de termos",
     "Leitura de um filing simplificado + true/false sobre compromissos assumidos",
     "Ler um documento oficial em ingl&ecirc;s e resumi-lo em tr&ecirc;s frases"),
    ("The Kickoff &mdash; a primeira reuni&atilde;o com o time americano",
     "Discurso de abertura + vis&atilde;o, prioridades e pr&oacute;ximos passos",
     "Di&aacute;logo de kickoff + role-play de fala de abertura de dois minutos",
     "&Aacute;udio de 3 minutos: discurso de abertura da opera&ccedil;&atilde;o"),
    ("Life Outside Work &mdash; a Fl&oacute;rida fora do banco",
     "Ingl&ecirc;s social e de servi&ccedil;o (escola, m&eacute;dico, vizinhan&ccedil;a, academia)",
     "Leitura de tr&ecirc;s textos do dia a dia americano + true/false",
     "Assistir a um v&iacute;deo sobre morar na Fl&oacute;rida, sem legenda em portugu&ecirc;s"),
    ("When It Goes Wrong &mdash; resolver uma crise ao vivo, em ingl&ecirc;s",
     "Integra&ccedil;&atilde;o sob press&atilde;o: explicar, negociar, decidir e comunicar",
     "Simula&ccedil;&atilde;o de crise de 20 minutos, sem apoio e sem pausa",
     "&Aacute;udio de 3 minutos: relato de crise e de solu&ccedil;&atilde;o"),
    ("Ninety-Six Lessons Later &mdash; o Dia 1 e o dia de hoje, lado a lado (marco final)",
     "Marco final: produ&ccedil;&atilde;o livre integrada, tudo do programa",
     "Escuta da grava&ccedil;&atilde;o da aula 1 seguida de nova grava&ccedil;&atilde;o, sem apoio",
     "&Aacute;udio final de 5 minutos: quem eu era, quem eu sou, e o que vem agora"),
]

assert len(CURRICULO) == 96, f'esperado 96 aulas, tem {len(CURRICULO)}'
