# -*- coding: utf-8 -*-
# Aula 1 -- The Executive Voice (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "The Executive <span class='accent'>Voice</span>",
    'hero_line': 'Two sentences at a New York dinner, and the key word where the room can hear it',
    'menu_desc': 'Framing an idea for a C-level table, and the clefts that put the key word last -- 34 slides',
    'grammar_point': 'wh-clefts and opinion frames to put the key idea last',
    'phases': ['The Dinner', 'Words of the Deal', 'The Code', 'Real Speed', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'claire', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1477959858617-67f85cf4f1df?w=1400&q=80',
        'ch2': U + 'photo-1554224155-6726b3ff858f?w=1400&q=80',
        'ch_grammar': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch4': U + 'photo-1511578314322-379afb476865?w=1400&q=80',
        'ch5': U + 'photo-1497366216548-37526070297c?w=1400&q=80',
        'ch_rp': U + 'photo-1540575467063-178a50c2df87?w=1400&q=80',
        'ch7': U + 'photo-1486406146926-c627a92ad1ab?w=1400&q=80',
        'pc': U + 'photo-1477959858617-67f85cf4f1df?w=600&q=80',
    },
    'warmup': {
        'heading': "Your Week, for a Colleague from <span class='accent'>London</span>",
        'sub': 'A new colleague starts on Monday and knows nothing about GRI. Brief them on your week in ninety seconds, with no notes.',
    },
    'target': {
        'heading': "One Idea, <span class='accent'>Said Once</span>",
        'steps': [
            'Frame it. Tell the room what kind of idea is coming before you say it.',
            'Hold the key word for the end of the sentence, where your voice falls and the room is listening.',
            'Hand the floor on. Bring somebody in, so the conversation does not depend on you.',
        ],
    },
    'diagnostic': {
        'heading': "So, What Exactly <span class='accent'>Do You Do?</span>",
        'p1': 'A managing director from a Canadian pension fund sits next to you at a dinner in New York and asks: &ldquo;So, what exactly do you do at GRI?&rdquo;',
        'p2': 'Answer as you would tonight. Then answer again, in two sentences, as if she had only thirty seconds.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Deal</span>",
            'sub': 'Fifteen words you use in Portuguese every day, and the moderator verbs that go with them'},
    'vocab': [
        {'word': 'Project finance', 'def': 'Paying for a large project with the money the project itself will earn, not with the owner&rsquo;s balance sheet', 'ex': 'The toll road was built with project finance, so the lenders look only at the traffic.', 'icon': 'coin'},
        {'word': 'A concession', 'def': 'A contract that lets a private company build and run a public asset for a fixed number of years', 'ex': 'The concession runs for thirty years, and then the airport goes back to the state.', 'icon': 'key'},
        {'word': 'Greenfield', 'def': 'Describes a project built from nothing, on a site where there was nothing before', 'ex': 'A greenfield port carries construction risk that a pension fund rarely wants.', 'icon': 'compass'},
        {'word': 'Brownfield', 'def': 'Describes a project that expands or upgrades an asset that already exists and already earns money', 'ex': 'Brownfield assets pay from day one, and that is why the funds like them.', 'icon': 'building'},
        {'word': 'A toll road', 'def': 'A highway where drivers pay every time they use it', 'ex': 'The toll road carries forty thousand cars a day.', 'icon': 'road'},
        {'word': 'A public-private partnership', 'def': 'A long-term deal in which the government and a private company share the risks of a public project', 'ex': 'The hospital was delivered as a public-private partnership, and the state pays for its availability.', 'icon': 'link'},
        {'word': 'A sovereign wealth fund', 'def': 'An investment fund owned by the government of a country', 'ex': 'A sovereign wealth fund from Abu Dhabi took twenty percent of the port.', 'icon': 'globe'},
        {'word': 'A pension fund', 'def': 'A fund that invests workers&rsquo; savings so that it can pay their retirement', 'ex': 'A pension fund needs income for decades, not a quick profit.', 'icon': 'users'},
        {'word': 'A regulatory framework', 'def': 'The whole set of rules and agencies that control how a sector works', 'ex': 'Investors will wait until the regulatory framework is stable.', 'icon': 'scale'},
        {'word': 'The pipeline', 'def': 'The list of projects that are planned and expected to come to market', 'ex': 'The pipeline for rail is thin, but the pipeline for roads is full.', 'icon': 'layers'},
        {'word': 'To bring in', 'def': 'To invite another person to join a discussion that is already happening', 'ex': 'I would like to bring in the regulator on this point.', 'icon': 'hand'},
        {'word': 'To unpack', 'def': 'To explain a complex idea by taking it apart, one piece at a time', 'ex': 'Let me unpack that before we move on.', 'icon': 'filter'},
        {'word': 'To connect the dots', 'def': 'To show how facts that look separate are actually related', 'ex': 'Nobody had connected the dots between the election and the delay.', 'icon': 'target'},
        {'word': 'To move the needle', 'def': 'To make a real, visible difference to a result', 'ex': 'Another roadshow will not move the needle; a stable contract will.', 'icon': 'chart'},
        {'word': 'A takeaway', 'def': 'The main point that people remember after a meeting or a talk', 'ex': 'The key takeaway from tonight is that the rules matter more than the rates.', 'icon': 'star'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A concession', 'A sovereign wealth fund', 'A regulatory framework', 'The key takeaway from tonight is that the rules matter more than the rates.'],
    'vocab_fill': [
        ('The road is paid for by the tolls it will collect, not by the company&rsquo;s balance sheet: that is ', 'project finance', '.'),
        ('They are not building on a new site; they are expanding an airport that already exists, so it is a ', 'brownfield', ' project.'),
        ('The fund is owned by the government and invests the country&rsquo;s oil revenue: it is ', 'a sovereign wealth fund', '.'),
        ('Before we move on, I would like to ', 'bring in', ' the fund director from Toronto.'),
        ('That answer had four ideas in it, so let me ', 'unpack', ' it for the room.'),
        ('One more conference will not ', 'move the needle', '; a contract that survives an election will.'),
    ],
    'ch_grammar': {'heading': "Hold the Key Word <span class='accent'>for Last</span>",
                   'sub': 'Four ways to frame an idea so the room hears the part that matters'},
    'grammar': {
        'heading': "Why Do These Sentences Start <span class='accent'>So Far Away?</span>",
        'examples': [
            "<span style='color:#b91c1c;font-weight:700'>What</span> investors want <span style='color:#b91c1c;font-weight:700'>is</span> a framework that outlives the government.",
            "<span style='color:#b91c1c;font-weight:700'>What I have come to realize is that</span> the pipeline is rarely the problem.",
            "<span style='color:#1d4ed8;font-weight:700'>The way I see it</span>, a concession is a thirty-year promise.",
            "<span style='color:#b91c1c;font-weight:700'>All</span> we need from the regulator <span style='color:#b91c1c;font-weight:700'>is</span> a date.",
        ],
        'prompt': 'Each idea could be said in fewer words: <em>Investors want a stable framework.</em> So why do the speakers make the room wait? Where does the most important word land, and what does the speaker gain?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Move the key idea to the end', 'What + clause + is + key idea', 'What investors want <strong>is stability</strong>.'),
            ('Signal a considered view', 'What I have come to realize is that + clause', 'What I have come to realize is that <strong>the rules matter more</strong>.'),
            ('Give your lens, not a verdict', 'The way I see it, + clause', 'The way I see it, <strong>greenfield is still early</strong>.'),
            ('Narrow the request', 'All (that) + subject + need is + noun', 'All we need <strong>is a date</strong>.'),
            ('Put an action in focus', 'What + subject + did was + base verb', 'What the ministry did <strong>was delay the auction</strong>.'),
            ('A softer frame', 'My sense is that + clause', 'My sense is that <strong>the funds are waiting</strong>.'),
            ('The trap', 'never <em>the way how</em>; never <em>is that is</em>', 'Not <em>The way how I see it</em>. Say <strong>The way I see it</strong>.'),
        ],
        'oneliner': 'Open with what or the way, hold the key idea for the end, and let your voice fall on it.',
    },
    'grammar_practice': {
        'heading': "Frame It, Then <span class='accent'>Land It</span>",
        'items': [
            ('', 'What', ' investors want is a framework that outlives the government. (open the frame)'),
            ('What I have come to realize ', 'is that', ' the hardest part is not the money. (link the frame to the idea)'),
            ('', 'The way I see it', ', greenfield is still where the risk sits. (your lens, three words and a comma)'),
            ('All we need from the regulator ', 'is', ' a date. (one word)'),
            ('What the ministry did ', 'was postpone', ' the auction. (the action in focus)'),
            ('', 'My sense is that', ' the pension funds are waiting for the election. (a softer frame)'),
        ],
    },
    'ch4': {'heading': "The Dinner Before <span class='accent'>the Panel</span>",
            'sub': 'One conversation, two recordings, one run of show'},
    'dialogue': {
        'heading': "A Seat Next to <span class='accent'>Toronto</span>",
        'guest_name': 'Claire', 'guest_initial': 'C',
        'lines': [
            ('c', 'Guilherme, right? Claire Tremblay. I run the infrastructure book at a pension fund in Toronto. So, what exactly do you do at GRI?'),
            ('g', 'The short version: I run the infrastructure vertical for Latin America. What we do is put investors, operators and regulators in the same room, before the money moves.'),
            ('c', 'And do they actually talk in those rooms? In my experience, a regulator and a <span class="vocab-highlight">pension fund</span> mostly exchange business cards.'),
            ('g', 'They talk when somebody makes them. That is my job at the table: I <span class="vocab-highlight">bring in</span> the ministry, I <span class="vocab-highlight">unpack</span> what the operator just said, and I <span class="vocab-highlight">connect the dots</span> for the funds.'),
            ('c', 'So where is the opportunity right now? Everyone in Toronto is asking me about Brazilian <span class="vocab-highlight">toll roads</span>.'),
            ('g', 'The way I see it, <span class="vocab-highlight">the pipeline</span> is strong, but <span class="vocab-highlight">greenfield</span> is still where the risk sits. The <span class="vocab-highlight">brownfield</span> <span class="vocab-highlight">concessions</span> are the ones that are ready now.'),
            ('c', 'And the rules? We were in <span class="vocab-highlight">a public-private partnership</span> in another market, and the government rewrote the contract after two years.'),
            ('g', 'That is the right question. What I have come to realize is that <span class="vocab-highlight">project finance</span> is rarely the problem. What moves the needle is whether the contract survives an election.'),
            ('c', 'Then I want that conversation on stage. Are you moderating the Thursday panel?'),
            ('g', 'I am opening it. And if you are willing, I would like to bring you in on the second question.'),
        ],
        'comp': [
            ('Where does Claire work, and what does she run there?', 'At a pension fund in Toronto. She runs the infrastructure book.'),
            ('According to Claire, what do a regulator and a pension fund usually do in those rooms?', 'They mostly exchange business cards.'),
            ('What does she say everyone in Toronto is asking her about?', 'Brazilian toll roads.'),
            ('What happened in the public-private partnership she mentions, and what does she ask Guilherme at the end?', 'The government rewrote the contract after two years. At the end she asks whether he is moderating the Thursday panel.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Podcast', 'title': "The Word the Room Is <span class='accent'>Looking For</span>",
         'blurb': 'A communication coach on accent, stress and intelligibility. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Here is something most executives get wrong about accent. The people in the room are not judging where you are from. They are trying to find the important word in your sentence, and they find it by listening for stress. In a room with investors from Toronto, Madrid, Abu Dhabi and Shanghai, English is almost everyone\'s second language, so the risk is not your accent. The risk is a flat sentence, where every syllable weighs the same and the key word disappears. Three habits fix most of it. Slow down on the numbers and the names. Put the stress where the dictionary puts it, especially on the long words of your industry. And pause before the idea you want people to remember, not after it. Nobody in that room needs you to sound American. They need to know which word matters.',
         'qs': [
             ('According to the coach, what are the people in the room really trying to do while you speak?', 'Find the important word in your sentence, by listening for stress.'),
             ('If the risk is not the accent, what is it?', 'A flat sentence, where every syllable weighs the same and the key word disappears.'),
             ('What are the three habits she recommends?', 'Slow down on numbers and names, put the stress where the dictionary puts it, and pause before the idea you want people to remember.'),
         ]},
        {'label': 'Listening 2 &middot; The Opening', 'title': "Good Evening, <span class='accent'>New York</span>",
         'blurb': 'A host opens an infrastructure dinner. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Good evening, and thank you for staying after a long day. There are about a hundred and forty people in this room tonight, and roughly a third of you manage somebody else\'s retirement, so I will keep this short. Tomorrow morning we will talk about numbers. Tonight I want to talk about trust. In the next hour you will hear from two toll road operators, one regulator and a sovereign wealth fund, and I have asked each of them to answer one question only: what would make you sign a thirty-year contract in this region? All I ask from the rest of you is simple. When you disagree, say so on stage, not in the corridor. That is the conversation this dinner exists for.',
         'qs': [
             ('How many people are in the room, and what does roughly a third of them do?', 'About a hundred and forty, and roughly a third manage somebody else\'s retirement.'),
             ('Who will the audience hear from, and what single question will each speaker answer?', 'Two toll road operators, one regulator and a sovereign wealth fund. The question is what would make them sign a thirty-year contract in the region.'),
             ('What does the host ask from the audience?', 'To disagree on stage, not in the corridor.'),
         ]},
    ],
    'artifact': {
        'heading': "The Run of Show in Your <span class='accent'>Inbox</span>",
        'title': 'RUN OF SHOW', 'subtitle': 'Infrastructure Dinner &middot; New York &middot; Thursday',
        'rows': [
            ('19:00', 'Opening remarks &mdash; G. Caneli (3 min)', True),
            ('19:05', 'Panel 1: &ldquo;Brownfield concessions: ready now?&rdquo;', False),
            ('Panelists', 'Canadian pension fund &middot; Brazilian toll road operator &middot; regulatory agency', False),
            ('Co-moderation', 'G. Caneli brings in the floor after question 2', True),
            ('19:45', 'Q&amp;A, then dinner', False),
        ],
        'note': 'Host note: keep the opening under three minutes. Speakers from four countries &mdash; slow down on numbers, and give every panelist the question before you give the floor.',
        'qs': [
            ('How long is Guilherme&rsquo;s opening, and what comes straight after it?', 'Three minutes, and then Panel 1 on brownfield concessions.'),
            ('Which three voices are on the first panel?', 'A Canadian pension fund, a Brazilian toll road operator and a regulatory agency.'),
            ('What does the host note ask him to do, and when does he bring in the floor?', 'Keep the opening under three minutes, slow down on numbers and give each panelist the question first. He brings in the floor after question 2.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Moderator</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('What I have come to realize is the pipeline it is strong.', 'What I have come to realize is <strong>that</strong> the pipeline is strong.'),
        ('The way how I see it, greenfield is riskier.', '<strong>The way I see it</strong>, greenfield is riskier.'),
        ('I would like to bring the minister in this discussion.', 'I would like to <strong>bring in the minister</strong> on this point.'),
        ('It is a project of greenfield in the north.', 'It is a <strong>greenfield project</strong> in the north.'),
    ],
    'speaking': [
        ('So, what exactly do you do at GRI?', 'The short version is that I put investors, operators and regulators in the same room, and what I do at the table is connect the dots.'),
        ('Is Brazil ready for foreign capital?', 'The way I see it, the pipeline is ready. What the market still needs is a regulatory framework that survives an election.'),
        ('Greenfield or brownfield: where would you put pension money first?', 'Brownfield, for now. What a pension fund needs is income from day one, and greenfield cannot give it that.'),
        ('What would really move the needle for investors?', 'What would move the needle is predictability: the same rules in year twenty as in year one.'),
    ],
    'building': [
        ('investors / want / a framework that outlives the government (open with what)', 'What investors want is a framework that outlives the government.'),
        ('I / come to realize / the pipeline / not be / the problem (a considered view)', 'What I have come to realize is that the pipeline is not the problem.'),
        ('the way / I / see / greenfield / carry most of the risk (your lens)', 'The way I see it, greenfield carries most of the risk.'),
        ('the ministry / do / postpone the auction (the action in focus)', 'What the ministry did was postpone the auction.'),
    ],
    'roleplays': {
        'heading': "The Same Dinner, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Claire Asks <span class='accent'>Again</span>",
             'scenario': 'Claire asks her three questions again: what you do, where the opportunity is, and what worries investors. Answer each one in two sentences, and put one frame from today in every answer.',
             'chips': ['What we do is', 'The way I see it', 'a concession', 'the pipeline']},
            {'heading': "Bring Somebody <span class='accent'>In</span>",
             'scenario': 'You are co-moderating. A toll road operator has just given a long, dense answer about traffic risk. Unpack it for the funds in the room, connect it to the contract, and bring in the regulator with one question.',
             'chips': ['Let me unpack that', 'I would like to bring in', 'to connect the dots', 'a regulatory framework']},
            {'heading': "Ninety Seconds, <span class='accent'>No Script</span>",
             'scenario': 'Open the Thursday panel. Say who is in the room, why this conversation matters now, and ask the first question to the pension fund.',
             'footer': 'No notes, ninety seconds. Choose one word in each sentence that the room must remember, and land on it.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for the <span class='accent'>Next Dinner</span>", 'sub': 'What you walk into the room with'},
    'survival_heading': "Five Sentences for the <span class='accent'>Next Dinner</span>",
    'survival': [
        'The short version is that I put investors, operators and regulators in the same room.',
        'What I have come to realize is that the pipeline is rarely the problem.',
        'The way I see it, brownfield concessions are the ones that are ready now.',
        'Let me unpack that for a second, and then I would like to bring in the regulator.',
        'What would really move the needle is a framework that survives an election.',
    ],
    'checklist': [
        'I can say what I do at GRI in two sentences, without preparing.',
        'I use What ... is and What I have come to realize is that to put the key idea at the end.',
        'I say The way I see it, and never the way how.',
        'I can unpack a long answer for the room and bring in the next speaker.',
        'I know the words: project finance, a concession, greenfield, brownfield, a toll road, a public-private partnership, a sovereign wealth fund, a pension fund, a regulatory framework, the pipeline, to bring in, to unpack, to connect the dots, to move the needle, a takeaway.',
    ],
    'badge': {'name': 'The Executive Voice', 'line': 'One idea per sentence, and the key word at the end, where the room can hear it.',
              'next': 'Next lesson: The Language of Capital -- risk, returns and the words the funds use, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Sem saudacao scriptada (REGRA 27A). Va direto: \'Guilherme, today we listen to your English the way a room of investors would.\' Contexto que muda a aula inteira: ele NAO e um aluno inseguro. Co-modera debates e abre conferencias do GRI Institute em ingles ha anos, trabalhou no consulado dos EUA com o ingles como lingua do dia a dia. Ele pediu tres coisas: feedback depois de 10-12 anos sem aula, vocabulario financeiro de infraestrutura (onde se sente \'um pouco falho\') e um ingles mais neutro, que indianos e chineses entendam. Tolerancia ao erro altissima (\'dou risada\'): pode corrigir direto, mas em BLOCO, no fim de cada atividade, para nao quebrar o fluxo. Ele pediu aula \'muito mais conversada\': trate a tela como roteiro de conversa, nao como lista de exercicios.',
        'warmup': '<strong>Warm-up (5 min):</strong> Aula 1, entao nao ha callback de vocabulario: e diagnostico puro. Deixe falar 90 segundos sem interromper. ANOTE em tres colunas: (1) palavras de financas/infraestrutura que ele usou e as que contornou com perifrase; (2) onde o acento tonico caiu errado em palavra longa (infraSTRUCture, conCESsion, REGulatory); (3) frases planas, em que nada ganha destaque. Esse mapa e o material das proximas oito aulas. Depois, UMA pergunta de acompanhamento em velocidade normal: \'And what was the hardest conversation this week?\'',
        'target': '<strong>Enquadramento (3 min):</strong> Mostre os 3 movimentos. Nao de a regra ainda: ela sai por descoberta no capitulo 3. Ligue ao que ele disse na consultoria: quer \'sair falando\' sem preparar muito antes. Os tres movimentos sao o esqueleto que permite improvisar: enquadrar, guardar a palavra-chave para o fim, passar a palavra. Pergunte qual dos tres ele ja faz sem pensar.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Primeira resposta livre, depois a versao de trinta segundos. ANOTE a diferenca de tamanho e se a palavra-chave aparece no fim ou se perde no meio. Nao corrija ainda. A versao curta volta no role-play guiado do capitulo 6 para comparar.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fifteen words you use in Portuguese every day. Let us check which ones you own in English.\' B2+ = zero portugues na tela. Se ele ja souber uma palavra, NAO pule: peca uma frase do trabalho real dele com ela e cobre a pronuncia.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> Leia a pista, ele diz a palavra, so entao revele. Clicar de novo fecha. CCQ \'project finance\': \'Do the lenders look at the company or at the project\'s future cash? (O caixa futuro do projeto.)\' CCQ \'a concession\': \'Who owns the airport at the end of the contract? (O Estado.)\' CCQ \'greenfield x brownfield\': \'Which one already earns money on day one? (Brownfield.)\' Peca um exemplo brasileiro real para cada um.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> Mesma mecanica. CCQ \'a public-private partnership\': \'Who carries the risk, only the company? (Os dois dividem.)\' CCQ \'a sovereign wealth fund x a pension fund\': \'Whose money is it? (Do governo x dos trabalhadores.)\' Pronuncia: SOV-rin, com duas silabas, sem o \'reign\' soletrado. \'The pipeline\': cobre o artigo definido, e \'the pipeline\', nao \'pipeline\'.',
        'vocab3': '<strong>Vocab reveal 11-15 (5 min):</strong> Estes cinco sao os VERBOS DO MODERADOR, e sao o que ele mais vai usar em palco. Para cada um, peca que ele diga a frase exata que usaria numa mesa do GRI. CCQ \'to move the needle\': \'Small change or visible change? (Visivel.)\' Atencao ao phrasal: \'bring in the regulator\' ou \'bring the regulator in\', nunca \'bring the regulator\' sozinho.',
        'pron': '<strong>Pronuncia e inteligibilidade (4 min):</strong> Este e o pedido numero um dele: ingles neutro. Trabalhe ACENTO e RITMO, nao sotaque. con-CES-sion (acento na segunda), SOV-rin, REG-yu-la-to-ry (acento na primeira, o portugues puxa para \'regulaTOry\'). Na frase longa, peca que ele marque as tres palavras que carregam o sentido (takeaway, rules, rates) e deixe o resto mais leve. Grave dele no celular se ele topar: ouvir a propria frase plana e o feedback que ele pediu.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Ele diz a palavra ANTES de clicar. As candidatas estao no banco embaixo, fora de ordem. Em C1+ isso vai rapido: se fechar em menos de um minuto, peca uma segunda frase dele com a mesma palavra, sobre um projeto real do GRI.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences that could be shorter. Look at how long each one takes to reach the point.\' Passe ao proximo sem antecipar a regra.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Each one could be said in fewer words. Why does the speaker make the room wait?\' Espere ele perceber sozinho que a estrutura empurra a informacao nova para o FIM da frase, onde cai a entonacao. So entao Reveal the Rule. CCQ: \'What investors want is stability &mdash; what is the most important word? (Stability.)\' CCQ: \'The way I see it &mdash; is this a fact or a personal view? (Visao pessoal.)\' Obstaculo classico do brasileiro avancado: \'The way how I see it\' (calco de \'o jeito como\'). Segundo obstaculo: dobrar o verbo, \'What I think is that is...\'. Ligue a pronuncia: a frase clivada so funciona se a voz cair na palavra final.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Ele fala a frase INTEIRA antes de clicar, com a voz caindo na palavra-chave. Nao aceite so a lacuna. Na quinta, cobre o verbo sem \'to\' depois de \'was\' (\'was postpone\', forma natural na fala). Se ele fechar tudo rapido, peca uma frase clivada sobre a semana real dele.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Now the dinner before the panel. One conversation, two recordings and the run of show your team sent you.\' Passe ao proximo.',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e a Claire: diretora de uma pension fund canadense, direta, simpatica, cetica com o mercado brasileiro. Clique Next Line e toque o audio de cada fala. Nas falas do Guilherme, ele fala PRIMEIRO e so depois toca o audio: compare o ritmo dele com o da gravacao. PRAGMATICA para comentar no fim: repare que ele responde a pergunta dificil (\'And the rules?\') com \'That is the right question\' antes de responder &mdash; ganha tempo sem parecer que foge. E na ultima fala ele ja prepara a co-moderacao (\'bring you in\').',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre a CLAIRE, nunca sobre o Guilherme (REGRA 27F). Ele responde antes de revelar. Na quarta, puxe a discussao real: ja aconteceu com investidor dele de o contrato mudar no meio? Deixe ele contar &mdash; e conversa com intencao, que e o formato que ele pediu.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar &mdash; elas ja estao na tela. Toque duas vezes. Esta gravacao e sobre o pedido dele: ingles neutro. Depois das respostas, pergunte: \'Which of the three habits do you already have, and which one would the Shanghai investor notice first?\' Ligue ao exercicio de pronuncia do capitulo 2.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Contexto diferente: agora e uma abertura de jantar, voz masculina, ritmo de palco. Ele FAZ isto no trabalho, entao depois das perguntas pergunte: \'What would you keep, and what would you change, if you were opening this dinner?\' Repare na frase \'All I ask from the rest of you is simple\': e a estrutura do capitulo 3 em uso real.',
        'artifact': '<strong>Artefato (4 min):</strong> E o run of show do jantar, com o nome dele. Peca que ele LEIA cada linha e a transforme em frase de palco: \'At seven o\'clock I will open, and what I want to do in three minutes is...\'. So depois as 3 perguntas. A nota do host repete o que o Listening 1 disse sobre numeros: aponte.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\' Passe ao proximo.',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige ANTES de clicar e explica por que. Sao os erros tipicos do brasileiro AVANCADO, que passam despercebidos porque a frase \'funciona\': o \'that\' que some depois do frame, o \'the way how\', o phrasal verb incompleto e a ordem \'project of greenfield\'. Se algum deles apareceu no warm-up, mostre a anotacao &mdash; e o feedback especifico que ele pediu.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas como a Claire faria, em velocidade normal. Ele responde por completo; as respostas na tela sao so sugestao e a producao dele vale mais. Regra do bloco: cada resposta com UM frame do capitulo 3. Correcao em bloco, no fim, no maximo tres pontos &mdash; um de vocabulario, um de estrutura, um de acento.',
        'building': '<strong>Sentence Building (4 min):</strong> Ele monta a frase COMPLETA em voz alta e so depois clica. Clicar de novo fecha. Cobre a entonacao descendo na ultima palavra. Se fechar as quatro sem ajuda, a estrutura esta consolidada e voce ganha tempo para o role-play livre.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The same dinner, three times. The last one is you on stage, with no script.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a Claire, sem o texto na tela. Tres perguntas, duas frases por resposta, um frame em cada. Compare com a versao de trinta segundos do slide 4: ficou mais curta e mais clara? Diga isso a ele &mdash; e o feedback que ele veio buscar.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o operador de rodovia e da uma resposta LONGA e confusa sobre risco de trafego (invente com numeros). Ele precisa: resumir para os fundos com \'Let me unpack that\', ligar ao contrato e trazer o regulador com uma pergunta. Isto e o dia a dia dele como co-moderador. Avalie se o resumo foi mais curto que a sua fala.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Noventa segundos, sem nota, sem interrupcao. Cronometre. No fim, diga dois numeros: quantas frases tiveram a palavra-chave no fim, e quantas palavras do vocabulario de hoje ele usou. Depois, UMA observacao de acento. Este e o benchmark da aula 1: a aula 8 repete o mesmo exercicio para comparar.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'An hour ago you described your week. Now you have five sentences you can take to the next dinner.\' Passe ao proximo.',
        'survival': '<strong>Survival card (3 min):</strong> Leia cada frase e toque o audio. Ele repete marcando a palavra que carrega o sentido. Peca que escolha UMA para usar em ingles no trabalho antes da proxima aula e conte como foi.',
        'checklist': '<strong>Checklist (2 min):</strong> Diga: \'Click each item if you feel confident.\' Leia cada item em voz alta. Todos os 5 marcados = aula concluida e stamp 1. Nao marque por ele: item que ele hesitar entra no warm-up da aula 2.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Guilherme, the room does not need you to sound American. It needs to hear the key word.\' Homework (ORALMENTE, nunca escrito na tela): gravar no celular a abertura de noventa segundos de hoje, ouvir, e trazer UMA frase em que a palavra-chave se perdeu. Proxima aula: a linguagem do capital &mdash; risco, retorno e as palavras dos fundos, em leitura.',
    },
    'pc': {
        'title': 'The Executive Voice -- Putting the Key Idea Last',
        'desc': 'At a dinner in New York, a pension fund director asks what you do, and you have two sentences to make them count.',
        'match_idx': [0, 1, 3, 6, 8, 12],
        'context': [
            'Most executives believe the problem at a dinner table is vocabulary. It rarely is. The problem is where the important word lands. In a room where English is everyone&rsquo;s second language, people listen for the end of the sentence, because that is where the voice falls. If the key idea is buried in the middle, it disappears.',
            'English has a family of structures that solve this. The first is the <strong>wh-cleft</strong>: instead of &ldquo;Investors want stability,&rdquo; you say &ldquo;<strong>What</strong> investors want <strong>is</strong> stability.&rdquo; The sentence takes longer, and that is the point: the room waits for the last word. A variation signals that you have thought about it: &ldquo;<strong>What I have come to realize is that</strong> <strong>the pipeline</strong> is rarely the problem.&rdquo; Notice the word <strong>that</strong>. It cannot disappear.',
            'When you want to give a personal view without sounding weak, use &ldquo;<strong>The way I see it</strong>, <strong>greenfield</strong> is still where the risk sits.&rdquo; Never &ldquo;the way how I see it&rdquo; &mdash; that is Portuguese in English clothes. When you want to make a request smaller and harder to refuse, use <strong>All</strong>: &ldquo;<strong>All</strong> we need from the <strong>regulatory framework</strong> <strong>is</strong> a date.&rdquo;',
            'Finally, when the action is the news, put it in focus with <strong>do</strong>: &ldquo;<strong>What</strong> the ministry <strong>did was</strong> postpone the auction for the <strong>concession</strong>.&rdquo; None of these structures is decoration. Each one decides which word the investor from Abu Dhabi will remember when the dinner is over.',
        ],
        'context_quiz': [
            ('According to the text, what is usually the real problem at a dinner table?', ['A lack of financial vocabulary.', 'Where the important word lands in the sentence.', 'Speaking too slowly.'], 1),
            ('Why does the text say a wh-cleft sentence is useful, even though it is longer?', ['The room waits for the last word, where the key idea is.', 'It sounds more polite to a regulator.', 'It avoids technical words.'], 0),
            ('Which sentence does the text say you should never use?', ['The way I see it, greenfield is risky.', 'All we need is a date.', 'The way how I see it, greenfield is risky.'], 2),
        ],
        'tip_title': 'Clefts and Opinion Frames',
        'tip_lead': 'Frame the idea first, hold the key word for the end, and let your voice fall on it.',
        'tip_rows': [
            ('Move the key idea to the end', 'What + clause + is + key idea', 'What investors want <strong>is stability</strong>.'),
            ('Signal a considered view', 'What I have come to realize is that + clause', 'What I have come to realize is that <strong>the rules matter more</strong>.'),
            ('Give your lens', 'The way I see it, + clause', 'The way I see it, <strong>greenfield is still early</strong>.'),
            ('Narrow a request', 'All + subject + need is + noun', 'All we need <strong>is a date</strong>.'),
            ('Put an action in focus', 'What + subject + did was + base verb', 'What the ministry did <strong>was delay the auction</strong>.'),
            ('A softer frame', 'My sense is that + clause', 'My sense is that <strong>the funds are waiting</strong>.'),
        ],
        'tip_never': 'the way how I see it &middot; what I have come to realize is the pipeline it is strong &middot; I would like to bring the minister &middot; a project of greenfield',
        'blanks': [
            ('', 'What', ' investors want is a framework that outlives the government.', 'Hint: one word opens the frame and makes the room wait', None),
            ('What I have come to realize ', 'is that', ' the pipeline is rarely the problem.', 'Hint: two words link the frame to the idea, and the second one cannot disappear', None),
            ('', 'The way I see it', ', greenfield is still where the risk sits.', 'Hint: your personal lens, five words, and no how', None),
            ('Let me ', 'unpack', ' that before we move on.', 'Hint: explain a complex answer piece by piece -- one word', None),
            ('I would like to ', 'bring in', ' the regulator on this point.', 'Hint: invite somebody into the discussion -- two words', None),
            ('The road was paid for with ', 'project finance', ', so the lenders only look at the traffic.', 'Hint: the project pays for itself -- two words', None),
        ],
        'order_title': 'Put the Answer in Order',
        'order_lead': 'A pension fund director asks what you do. Put your answer in a logical order.',
        'order': [
            'The short version is that I run the infrastructure vertical for Latin America.',
            'What we do is put investors, operators and regulators in the same room.',
            'The way I see it, the pipeline is strong, but greenfield is still early.',
            'What moves the needle is whether the contract survives an election.',
            'That is exactly what we will unpack on the panel on Thursday.',
            'And you, which markets is your fund looking at this year?',
        ],
        'quiz': [
            ('A director asks what you do, and you want the key idea to land. You say:', ['I put investors, operators and regulators in the same room, this is what I do.', 'What I do is put investors, operators and regulators in the same room.', 'What I do it is to put investors and regulators together.'], 1),
            ('You want to give a personal view without sounding weak. You say:', ['The way I see it, brownfield is ready now.', 'The way how I see it, brownfield is ready now.', 'In my see, brownfield is ready now.'], 0),
            ('A panelist gave a long, dense answer. You say:', ['Let me explain you that.', 'Let me unpack that for the room.', 'Let me open this for the room.'], 1),
            ('You want the regulator to join the discussion. You say:', ['I would like to bring the regulator.', 'I would like to call the regulator to here.', 'I would like to bring in the regulator on this point.'], 2),
        ],
        'think': 'A new colleague from London joins GRI tomorrow. In ninety seconds, explain what you do, where you see the opportunity in Latin American infrastructure, and one thing that worries investors. Use at least two frames from today, and make sure the key word of each sentence comes last.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Julian Treasure &mdash; &ldquo;How to speak so that people want to listen&rdquo; (TED)',
         'desc': 'Ten minutes on register, pace, pitch and silence &mdash; the tools behind a voice that a room of international investors can follow. It is the practical side of today&rsquo;s first recording.',
         'tip': 'Tip: watch once with English subtitles. Then choose one of his vocal exercises and try it before your next opening.',
         'url': 'https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen', 'cta': 'Watch on TED'},
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;How to Have Great Conversations&rdquo;',
         'desc': 'An hour on what makes a conversation work, including why people remember how a conversation ended and how the best talkers hand the floor back. Useful for the dinner before every panel.',
         'tip': 'Tip: the transcript is on the same page. Listen once without it, then find the three sentences you would steal for a GRI dinner.',
         'url': 'https://freakonomics.com/podcast/how-to-have-great-conversations/', 'cta': 'Listen on Freakonomics'},
        {'id': 'video', 'type': 'Video', 'title': 'Patrick Winston &mdash; &ldquo;How to Speak&rdquo; (MIT, YouTube)',
         'desc': 'A legendary MIT lecture on how to start a talk, how to end it, and why the last slide matters more than the first. Everything in it applies to a conference opening.',
         'tip': 'Tip: watch the first fifteen minutes on how to start. Compare his advice with the way you opened your last event.',
         'url': 'https://www.youtube.com/watch?v=Unzc731iCUY', 'cta': 'Watch on YouTube'},
    ],
}
