# -*- coding: utf-8 -*-
# Aula 4 -- The Rules of the Game (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The Rules of the <span class='accent'>Game</span>",
    'hero_line': 'What the agency actually said, and how sure it was when it said it',
    'menu_desc': 'Reading a regulatory statement, and the reporting verbs that measure a promise -- 36 slides',
    'grammar_point': 'reported speech and reporting verbs in regulatory communication',
    'phases': ['The Statement', 'Words of the Rules', 'The News Brief', 'The Code', 'Same Rule, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'dana', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1589829545856-d10d557cf95f?w=1400&q=80',
        'ch2': U + 'photo-1541872703-74c5e44368f9?w=1400&q=80',
        'ch3': U + 'photo-1504384308090-c894fdcc538d?w=1400&q=80',
        'ch_grammar': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch5': U + 'photo-1552664730-d307ca884978?w=1400&q=80',
        'ch_rp': U + 'photo-1556761175-5973dc0f32e7?w=1400&q=80',
        'pc': U + 'photo-1589829545856-d10d557cf95f?w=600&q=80',
    },
    'warmup': {
        'heading': "Your English in <span class='accent'>Three Words</span>",
        'sub': 'Not as it was in Lesson 1, but as it is today. Then open the last panel you moderated in thirty seconds, with one inversion and one word from last lesson: an inflection point, a show of hands, to set the tone, to hand over to.',
    },
    'target': {
        'heading': "Read the Statement Like <span class='accent'>a Lawyer</span>",
        'steps': [
            'Separate what was decided from what was only signaled.',
            'Check whether the reported fact is still true today, or only was.',
            'Retell it to an investor without making the promise stronger or weaker.',
        ],
    },
    'diagnostic': {
        'heading': "What Did the Agency <span class='accent'>Say?</span>",
        'p1': 'A fund manager in Toronto missed yesterday&rsquo;s press conference and calls you: &ldquo;What did the agency say about the tariff review?&rdquo;',
        'p2': 'Report it in three sentences. Invent the details if you need to, but make it clear which parts were a decision and which were only a signal.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Rules</span>",
            'sub': 'Fourteen terms from contracts, regulators and the lawyers who read them'},
    'vocab': [
        {'word': 'A regulatory sandbox', 'def': 'A controlled space where companies can test a new model under relaxed rules for a limited time', 'ex': 'The agency created a regulatory sandbox for electric bus concessions.', 'icon': 'layers'},
        {'word': 'A tariff review', 'def': 'The official process of recalculating what users pay for a public service', 'ex': 'The tariff review for the third batch of highways starts in October.', 'icon': 'coin'},
        {'word': 'A contingent liability', 'def': 'A cost that may have to be paid in the future if a specific event happens', 'ex': 'The guarantee is a contingent liability on the state&rsquo;s balance sheet.', 'icon': 'alert'},
        {'word': 'Environmental licensing', 'def': 'The process of getting official permission to build a project that affects the environment', 'ex': 'Environmental licensing took longer than construction.', 'icon': 'shield'},
        {'word': 'A fiscal framework', 'def': 'The rules that limit how much a government can spend and borrow', 'ex': 'The new fiscal framework leaves little room for public guarantees.', 'icon': 'scale'},
        {'word': 'Administrative discretion', 'def': 'The freedom officials have to decide how a rule is applied', 'ex': 'Investors dislike administrative discretion when it has no clear limits.', 'icon': 'key'},
        {'word': 'Due diligence', 'def': 'The detailed investigation an investor does before signing a deal', 'ex': 'The fund&rsquo;s due diligence found three problems in the contract.', 'icon': 'eye'},
        {'word': 'A material breach', 'def': 'A failure to meet a contract that is serious enough to allow the other side to act', 'ex': 'Missing the investment schedule twice is a material breach.', 'icon': 'zap'},
        {'word': 'Force majeure', 'def': 'An event nobody could control or prevent, such as a flood, that excuses a party from its obligations', 'ex': 'The operator declared force majeure after the bridge collapsed in the flood.', 'icon': 'refresh'},
        {'word': 'A grandfathering clause', 'def': 'A rule that allows existing contracts to continue under the old conditions', 'ex': 'Thanks to a grandfathering clause, the new rule does not touch contracts signed before 2025.', 'icon': 'lock'},
        {'word': 'A rebalancing claim', 'def': 'A request by an operator to restore the financial balance of a contract after an event it did not cause', 'ex': 'The floods led to a rebalancing claim of two hundred million reais.', 'icon': 'filter'},
        {'word': 'A public consultation', 'def': 'A period when anyone can send comments on a proposed rule before it is final', 'ex': 'The public consultation received more than four hundred contributions.', 'icon': 'message'},
        {'word': 'A step-in right', 'def': 'The right of lenders to take control of a project if the operator fails', 'ex': 'The banks used their step-in right to replace the operator.', 'icon': 'hand'},
        {'word': 'A termination payment', 'def': 'The money a government must pay an operator if it ends a concession early', 'ex': 'The termination payment would cost more than the road itself.', 'icon': 'doc'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A contingent liability', 'Administrative discretion', 'Force majeure', 'The agency clarified that operators were not expected to cut investment.'],
    'ch3': {'heading': "The News Brief the Fund <span class='accent'>Forwarded</span>", 'sub': 'Read it once for what was decided. The detail comes after.'},
    'reading': {
        'heading': "What the Agency <span class='accent'>Actually Said</span>",
        'rtitle': 'What the Agency Actually Said',
        'paras': [
            'By the time yesterday&rsquo;s press conference ended, three different headlines were already circulating. One said the government would cut toll road tariffs. Another said the concessions would be renegotiated. A third said nothing would change. All three came from the same forty minutes, and none of them was exactly what the agency said.',
            'The director opened by confirming that the tariff review for the third batch of highways would begin in October, after a public consultation of forty-five days. That part was a decision. She then indicated that the review could lead to lower tariffs on some stretches of road, which is a signal, not a promise. When a journalist asked whether contracts would be renegotiated, she clarified that the review followed the formula already written in each contract, and that operators were not expected to cut investment during the consultation period.',
            'The more important news came in answer to a question about the floods in the south. The director acknowledged that several operators had filed rebalancing claims, and said that each claim would be assessed case by case. She did not say whether the floods would be treated as force majeure, and a senior official later suggested that the agency had not yet reached a view. She also confirmed that contracts signed before 2025 are protected by a grandfathering clause, which means the new rules do not apply to them.',
            'For investors doing due diligence, the useful lesson is not the headline. It is the verbs. Confirmed means you can build a model on it. Indicated and suggested mean you should build two. And when a statement is reported without a person &mdash; the operator is said to be preparing a claim &mdash; it means somebody wanted the information out without having to own it.',
        ],
        'source': 'Written for this lesson, from the typical structure of a regulatory press conference and its coverage.',
    },
    'gist': {
        'prompt': 'What is the main point of the news brief?',
        'choices': [
            ['a', 'The government has decided to cut toll road tariffs in October.', False],
            ['b', 'Reporting verbs show which parts of a statement were decisions and which were only signals.', True],
            ['c', 'All concession contracts will be renegotiated after the floods.', False],
        ],
    },
    'tf': [
        ['The three headlines accurately reported what the agency said.', 'f', 'The text says none of the headlines was exactly what the agency said.'],
        ['The start of the tariff review in October was presented as a decision.', 't', 'The text says the director confirmed it, and calls that part a decision.'],
        ['The director promised that tariffs would fall on every stretch of road.', 'f', 'She only indicated that the review could lead to lower tariffs on some stretches, which the text calls a signal, not a promise.'],
        ['The agency has already decided to treat the floods as force majeure.', 'f', 'She did not say, and an official later suggested the agency had not reached a view.'],
        ['Contracts signed before 2025 will not be affected by the new rules.', 't', 'The director confirmed they are protected by a grandfathering clause.'],
    ],
    'artifact': {
        'heading': "The Press Release in <span class='accent'>Your Inbox</span>",
        'title': 'PRESS RELEASE', 'subtitle': 'Federal Land Transport Agency &middot; Highway Concessions &middot; Batch 3',
        'rows': [
            ('Decision', 'Tariff review opens with a 45-day public consultation on 2 October', True),
            ('Rebalancing claims', 'To be assessed case by case; no deadline announced', False),
            ('Force majeure', 'Under analysis &mdash; no position taken', False),
            ('Existing contracts', 'Signed before 2025: protected by a grandfathering clause', True),
            ('Investment', 'Operators are not expected to reduce investment during the consultation', False),
        ],
        'note': 'Media contact: questions about individual contracts will not be answered during the consultation period.',
        'qs': [
            ('What exactly was decided, and when does it start?', 'The tariff review opens with a forty-five-day public consultation on the second of October.'),
            ('Which two points are still open?', 'The deadline for assessing rebalancing claims, and whether the floods count as force majeure.'),
            ('What does the release say about investment, and what questions will not be answered?', 'Operators are not expected to reduce investment during the consultation. Questions about individual contracts will not be answered in that period.'),
        ],
    },
    'ch_grammar': {'heading': "How Sure Was <span class='accent'>the Speaker?</span>",
                   'sub': 'The reporting verb measures the promise; the tense says whether it is still true'},
    'grammar': {
        'heading': "Three Verbs Step Back in Time. <span class='accent'>One Does Not.</span>",
        'examples': [
            "The minister <span style='color:#b91c1c;font-weight:700'>indicated that</span> the framework <span style='color:#b91c1c;font-weight:700'>would be</span> revised by the fourth quarter.",
            "The agency <span style='color:#b91c1c;font-weight:700'>clarified that</span> operators <span style='color:#b91c1c;font-weight:700'>were not expected</span> to cut investment.",
            "Sources <span style='color:#b91c1c;font-weight:700'>suggested that</span> the fund <span style='color:#b91c1c;font-weight:700'>had already committed</span>.",
            "The regulator <span style='color:#1d4ed8;font-weight:700'>confirmed that</span> the auction <span style='color:#1d4ed8;font-weight:700'>is</span> still scheduled for March.",
        ],
        'prompt': 'In the red sentences, the verb moves one step back in time. Why is the blue sentence allowed to stay in the present? And look at the reporting verbs: which one would you build a financial model on, and which would make you build two?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Report a statement', 'reporting verb + that + one step back in time', 'She said that the review <strong>would start</strong> in May.'),
            ('Keep what is still true', 'no backshift when it is still true today', 'The agency confirmed that the auction <strong>is</strong> in March.'),
            ('A firm statement', 'confirmed, announced, stated', 'The ministry <strong>confirmed</strong> the date.'),
            ('A signal, not a promise', 'indicated, suggested, signaled', 'The minister <strong>indicated</strong> tariffs could fall.'),
            ('A correction, warning or admission', 'clarified, warned, acknowledged', 'She <strong>acknowledged</strong> that claims had been filed.'),
            ('Report without a person', 'subject + is said to / is expected to + verb', 'The operator <strong>is said to be</strong> preparing a claim.'),
            ('The trap', 'never <em>said me</em>, never <em>explained me</em>', 'Not <em>She explained me the rule</em>. Say <strong>She explained the rule to me</strong>.'),
        ],
        'oneliner': 'The reporting verb tells the investor how firm the promise was; the tense tells them whether it is still true.',
    },
    'grammar_practice': {
        'heading': "Report It Without <span class='accent'>Changing It</span>",
        'items': [
            ('The minister ', 'indicated', ' that the framework would be revised by the fourth quarter. (a signal, not a promise)'),
            ('The agency ', 'clarified', ' that operators were not expected to cut investment. (correcting a misunderstanding)'),
            ('The regulator confirmed that the auction ', 'is still scheduled', ' for March. (still true today)'),
            ('Sources suggested that the fund ', 'had already committed', ' before the announcement. (an earlier past)'),
            ('The operator ', 'acknowledged', ' that the rebalancing claim would take months. (admitting something)'),
            ('The fund ', 'is said to have signed', ', but nobody has confirmed it. (report without a person)'),
        ],
    },
    'detective': [
        ('The minister said us that the review would start in May.', 'The minister <strong>told us</strong> that the review would start in May.'),
        ('The agency explained me the new rules.', 'The agency <strong>explained the new rules to me</strong>.'),
        ('She suggested to delay the auction.', 'She <strong>suggested delaying</strong> the auction.'),
        ('It is said that the fund to have signed.', 'The fund <strong>is said to have signed</strong>.'),
    ],
    'ch5': {'heading': "Same Rule, <span class='accent'>Other Words</span>", 'sub': 'Equivalence &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Official Line in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each official sentence to the same idea in plain English',
        'hint': 'Tap a line from the statement, then tap the sentence that means the same',
        'pairs': [
            ('The Agency will open a public consultation for 45 days.', 'Anyone can send comments on the proposal for a month and a half.'),
            ('Rebalancing claims will be assessed case by case.', 'Each operator&rsquo;s request for compensation will be judged separately.'),
            ('The measure is subject to administrative discretion.', 'Officials have room to decide how to apply the rule.'),
            ('Existing contracts will be grandfathered.', 'The new rule will not apply to contracts that already exist.'),
            ('The event constitutes force majeure.', 'Nobody could have prevented it, so the contract excuses the delay.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Roundtable Summary</span>",
    'gap': {
        'parts': [
            'At the roundtable, the agency&rsquo;s director confirmed that the ', ['1', 'tariff review'],
            ' for the third batch of highways would begin in October, after a forty-five-day ', ['2', 'public consultation'],
            '. Asked about operators that had lost traffic during the floods, she indicated that each ', ['3', 'rebalancing claim'],
            ' would be assessed separately. A lawyer on the panel warned that investors doing ', ['4', 'due diligence'],
            ' should read the contracts closely, because a ', ['5', 'material breach'],
            ' by the operator could give the lenders a ', ['6', 'step-in right'],
            '. If the state ended a concession early, he added, the ', ['7', 'termination payment'],
            ' would sit on the government&rsquo;s books as a ', ['8', 'contingent liability'], '.',
        ],
        'bank': ['tariff review', 'public consultation', 'rebalancing claim', 'due diligence', 'material breach', 'step-in right', 'termination payment', 'contingent liability'],
    },
    'quickfire': [
        {'situation': 'A fund manager asks what the agency decided yesterday. Report the one decision, without making it stronger.', 'tips': ['The director confirmed that the tariff review would begin in October, after a forty-five-day public consultation.', 'Confirmed for the decision; would begin, one step back in time.']},
        {'situation': 'The same manager asks whether tariffs will fall. Report the signal as a signal.', 'tips': ['She indicated that tariffs could fall on some stretches, but that was a signal, not a promise.', 'Indicated, not confirmed. Could, not will.']},
        {'situation': 'An investor says he heard all concessions will be renegotiated. Correct him politely.', 'tips': ['That is not what was said. The agency clarified that the review follows the formula already in each contract.', 'Clarified is the verb for correcting a misunderstanding.']},
        {'situation': 'Explain to a CFO from Singapore what a grandfathering clause means for her contract signed in 2023.', 'tips': ['Her contract is protected by a grandfathering clause, so the new rules do not apply to it.', 'Protected by, not protected for.']},
        {'situation': 'Report a rumor you cannot confirm about an operator preparing a large claim.', 'tips': ['The operator is said to be preparing a rebalancing claim, but nobody has confirmed it.', 'is said to + be + -ing for something happening now.']},
        {'situation': 'A lender asks what happens if the operator fails to invest for two years.', 'tips': ['That would be a material breach, and the lenders could use their step-in right to replace the operator.', 'Material breach first, then the consequence.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; The News', 'title': "The Agency <span class='accent'>Responds</span>",
         'blurb': 'A business news report on a regulator&rsquo;s statement. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'The federal transport agency moved this afternoon to calm investors after a week of speculation about toll road contracts. In a statement, the agency confirmed that the tariff review for highway concessions will go ahead in October, but clarified that it would follow the formula written into each contract. The agency\'s director acknowledged that seven operators had filed rebalancing claims after the floods, and said the claims would be assessed individually. She declined to say whether the floods would be treated as force majeure. Market reaction was cautious. One analyst told us that investors had expected a clearer answer on the floods, and warned that uncertainty over the claims could delay two auctions planned for the first half of next year.',
         'qs': [
             ('What did the agency confirm, and what did it clarify?', 'It confirmed that the tariff review will go ahead in October, and clarified that it would follow the formula written into each contract.'),
             ('How many operators had filed rebalancing claims, and how will the claims be assessed?', 'Seven operators, and the claims will be assessed individually.'),
             ('What did the director decline to say, and what did the analyst warn?', 'Whether the floods would be treated as force majeure. The analyst warned that the uncertainty could delay two auctions planned for the first half of next year.'),
         ]},
        {'label': 'Listening 2 &middot; The Lawyer', 'title': "Two Clauses Investors <span class='accent'>Skip</span>",
         'blurb': 'A contracts lawyer speaks at an investor roundtable. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Most investors read the tariff clause and the investment schedule, and then they stop. I want to talk about the two clauses they skip. The first is force majeure. People think it is a formality, but in a country with floods and droughts it decides who pays when the road is under water. Read the list of events, and read who has to prove what. The second is the grandfathering clause. When a government changes the rules, this is the sentence that says whether your contract is protected or not. I have seen a fund lose a year of returns because its lawyers assumed the old rules would continue, and the clause said otherwise. None of this is exciting. All of it belongs in your due diligence.',
         'qs': [
             ('Which two clauses does the lawyer say investors skip?', 'The force majeure clause and the grandfathering clause.'),
             ('Why does he say force majeure is not a formality, and what should investors read in it?', 'Because in a country with floods and droughts it decides who pays when the road is under water. Investors should read the list of events and who has to prove what.'),
             ('What happened to the fund he mentions?', 'It lost a year of returns because its lawyers assumed the old rules would continue, and the grandfathering clause said otherwise.'),
         ]},
    ],
    'roleplays': {
        'heading': "Retell It <span class='accent'>Exactly</span>",
        'items': [
            {'heading': "Brief the Fund That <span class='accent'>Missed It</span>",
             'scenario': 'Claire from the Toronto pension fund missed the press conference. In two minutes, tell her what was decided, what was only signaled and what is still open. Do not make any promise stronger than it was.',
             'chips': ['The director confirmed that', 'she indicated that', 'a tariff review', 'a public consultation']},
            {'heading': "The Investor Heard <span class='accent'>a Rumor</span>",
             'scenario': 'An investor from Madrid is sure the agency will cancel contracts after the floods. Correct the rumor using what was actually said, and explain what a rebalancing claim and a grandfathering clause mean for him.',
             'chips': ['That is not what was said', 'she clarified that', 'a rebalancing claim', 'a grandfathering clause']},
            {'heading': "Force Majeure for <span class='accent'>Singapore</span>",
             'scenario': 'A C-level from Southeast Asia with no legal background is considering a Brazilian highway. In ninety seconds, explain force majeure and grandfathering in plain executive English.',
             'footer': 'No notes, ninety seconds, no term left undefined.'},
        ],
    },
    'survival_heading': "Five Sentences for <span class='accent'>Regulatory News</span>",
    'survival': [
        'The agency confirmed that the tariff review will begin in October.',
        'The minister indicated that the framework would change, but that was a signal, not a promise.',
        'Contracts signed before 2025 are protected by a grandfathering clause.',
        'Before you sign, your due diligence should cover force majeure and the step-in rights.',
        'Each rebalancing claim will be assessed case by case.',
    ],
    'checklist': [
        'I can report a regulatory statement without making the promise stronger or weaker.',
        'I choose the reporting verb that matches how sure the speaker was.',
        'I keep the present tense when a reported fact is still true.',
        'I can explain force majeure and grandfathering to a non-legal executive.',
        'I know the words: a regulatory sandbox, a tariff review, a contingent liability, environmental licensing, a fiscal framework, administrative discretion, due diligence, a material breach, force majeure, a grandfathering clause, a rebalancing claim, a public consultation, a step-in right, a termination payment.',
    ],
    'badge': {'name': 'The Rules of the Game', 'line': 'Confirmed means build the model. Indicated means build two.',
              'next': 'Next lesson: Holding the Room -- debate, pushback and diplomatic precision, in speech'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Va direto: \'Guilherme, today we read what regulators say, and how sure they were.\' Aula 4 e ponto de revisao do bloco 1 (curriculo): o warm-up mede o progresso das aulas 1-3. Tema de leitura (aula par). Ele lida com ANTT, ANEEL, ministerios e investidores o tempo todo: o conteudo e o dia a dia dele, a novidade e a precisao em ingles.',
        'warmup': '<strong>Warm-up de progresso + callback (6 min):</strong> Primeiro, \'three words for your English today\' &mdash; deixe ele se avaliar sem comentar. Depois, trinta segundos de abertura com UMA inversao (aula 3) e uma palavra da aula passada (an inflection point, a show of hands, to set the tone, to hand over to). ANOTE: a inversao saiu com o auxiliar? houve pausa? Esse e o dado de progresso do bloco.',
        'target': '<strong>Enquadramento (2 min):</strong> Tres movimentos de quem le comunicado regulatorio para investidor. Pergunte quando foi a ultima vez que uma manchete disse mais do que o regulador disse.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Ele relata a coletiva em tres frases. ANOTE os verbos de relato (quase todo mundo usa so said) e se houve backshift. Nao corrija: o capitulo de gramatica usa essa anotacao.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fourteen terms from contracts and regulators.\' Varios sao latinismos que ele conhece em portugues (reequilibrio, forca maior): o foco e registro e pronuncia em ingles.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'a contingent liability\': \'Has the state already paid it? (Nao, pode ter que pagar.)\' CCQ \'a regulatory sandbox\': \'Permanent or temporary? (Temporario.)\' CCQ \'a fiscal framework\': \'Does it limit spending or increase it? (Limita.)\' Peca um exemplo brasileiro real para cada um.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a material breach\': \'A small delay or a serious failure? (Falha seria.)\' CCQ \'force majeure\': \'Could anyone prevent it? (Nao.)\' Pronuncia: force ma-ZHUR, sem o \'je\' frances. CCQ \'a grandfathering clause\': \'Does the new rule apply to the old contract? (Nao.)\'',
        'vocab3': '<strong>Vocab reveal 11-14 (4 min):</strong> CCQ \'a rebalancing claim\': \'Who asks for it, the operator or the state? (O operador.)\' CCQ \'a step-in right\': \'Who takes control, the government or the lenders? (Os credores.)\' Ligue a \'termination payment\' e \'contingent liability\': o pagamento de encerramento vira passivo contingente.',
        'pron': '<strong>Pronuncia (4 min):</strong> con-TIN-gent li-a-BIL-i-ty, ad-MIN-is-tra-tive dis-CRE-tion, force ma-JEUR. Na frase longa, a palavra que carrega sentido e \'NOT expected\' &mdash; o not precisa de peso, senao o investidor ouve o contrario.',
        'matching': '<strong>Matching (4 min):</strong> Pares em voz alta antes de clicar. Se fechar rapido, peca a diferenca entre a material breach e force majeure: quem e culpado em cada caso?',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'A news brief a fund forwarded to you. Read it for what was decided.\' Os verbos de relato aparecem no texto antes da regra.',
        'reading': '<strong>Leitura (7 min):</strong> Silenciosa, ritmo real. Depois peca UMA frase: o que foi DECIDIDO? Pergunte se ja viu isso acontecer com uma coletiva da ANTT ou da ANEEL. Deixe virar conversa.',
        'gist': '<strong>Gist (3 min):</strong> Ele escolhe e justifica por que nao a e nao c. As duas erradas sao exatamente as manchetes erradas do texto.',
        'tf': '<strong>True or False (6 min):</strong> TRUE ou FALSE, e a linha que prova, em voz alta. Nas falsas, peca que ele diga a versao correta com o verbo de relato certo.',
        'artifact': '<strong>Artefato (4 min):</strong> Press release ficticio. Peca que ele LEIA e relate cada linha com um verbo de relato: \'The agency announced that...\', \'It indicated that...\'. Atencao na linha de force majeure: nao ha posicao, entao nenhum verbo forte cabe.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four reported sentences. Three verbs step back in time.\' Passe ao proximo.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Why does the blue sentence stay in the present?\' (Porque ainda e verdade.) Depois: \'Which verb would you build a financial model on?\' (confirmed.) So entao Reveal the Rule. CCQ: \'indicated &mdash; promise or signal? (Sinal.)\' CCQ: \'is said to have signed &mdash; do we know who said it? (Nao.)\' Obstaculos do brasileiro avancado: \'said me\' e \'explained me\' (calco de \'me disse\', \'me explicou\') e \'suggested to delay\'. Pragmatica: para investidor, o verbo de relato e informacao financeira.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Frase inteira antes de clicar. Na terceira, cobre por que nao ha backshift. Se fechar rapido, peca que ele relate uma declaracao real de um regulador brasileiro desta semana.',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige antes de clicar e explica. Quatro erros tipicos do avancado: said us, explained me, suggested to, e a construcao hibrida com is said. Correcao direta.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same rule, other words: the official line in plain English, the roundtable summary, one question at a time, and two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ele fecha o par e explica. E o que ele faz como moderador quando um regulador fala em juridiques: traduzir para o fundo. Se fechar rapido, peca uma versao para um ministro.',
        'gap': '<strong>Gap-fill (5 min):</strong> Banco embaixo; ele pode arrastar, tocar ou digitar, e o Check confere. No fim, peca que ele leia o resumo completo em voz alta como se fosse o rapporteur da mesa.',
        'quickfire': '<strong>Quick fire (6 min):</strong> Uma por vez, velocidade normal. Ele responde antes das dicas. Cobre o verbo de relato: se ele trocar indicated por confirmed, pare e pergunte se o investidor pode construir um modelo com aquilo.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar. Noticiario, voz feminina, verbos de relato em sequencia (confirmed, clarified, acknowledged, declined, warned). Toque duas vezes. Depois peca que ele liste os verbos que ouviu e o grau de certeza de cada um.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Advogado numa mesa redonda, voz masculina. Depois das perguntas: \'Which clause do investors in your events ask about least?\' Deixe ele contar.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'Now you retell it. Three times, and the last one has no help.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a Claire, da aula 1. Ele relata a coletiva em dois minutos. Avalie UMA coisa acima de tudo: algum sinal virou promessa? Se virou, mostre.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o investidor de Madri, convencido e um pouco irritado. Ele corrige com diplomacia (\'That is not what was said\') e explica os dois termos. Isto prepara a aula 5, de pushback.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Noventa segundos para um C-level sem formacao juridica. No fim: algum termo ficou sem definicao? quantas palavras de hoje? uma observacao de acento.',
        'survival': '<strong>Survival card (3 min):</strong> Audio e repeticao. Peca que ele use uma frase ao relatar uma noticia regulatoria real a um investidor esta semana.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 = aula concluida e stamp 4. Fim do bloco 1: item em que ele hesitar entra no warm-up da aula 5.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Confirmed means build the model. Indicated means build two.\' Homework (ORALMENTE, nunca escrito na tela): escrever um resumo executivo de 250 palavras de uma mesa ficticia sobre tariff review, atribuindo cada posicao a um papel (the fund director, the regulator), e gravar 2 minutos explicando force majeure e grandfathering para um C-level do Sudeste Asiatico. Proxima aula: segurar a sala &mdash; debate, pushback e precisao diplomatica, em fala.',
    },
    'pc': {
        'title': 'The Rules of the Game -- How Sure Was the Speaker?',
        'desc': 'Three headlines, one press conference, and none of them said what the agency actually said.',
        'match_idx': [1, 2, 6, 8, 9, 12],
        'context': [
            'When you tell an investor what a regulator said, you are doing more than repeating words. You are telling them how firm the promise was, and whether it is still true. English does both jobs with two tools: the <strong>reporting verb</strong> and the <strong>tense</strong>.',
            'The reporting verb measures certainty. If the director <strong>confirmed</strong> that the <strong>tariff review</strong> would begin in October, that is a decision. If she <strong>indicated</strong> or <strong>suggested</strong> that tariffs could fall, that is a signal. If she <strong>clarified</strong> something, she was correcting a misunderstanding, and if she <strong>acknowledged</strong> that operators had filed a <strong>rebalancing claim</strong>, she was admitting a problem.',
            'The tense usually moves one step back: &ldquo;The review <strong>will</strong> begin&rdquo; becomes &ldquo;She confirmed that the review <strong>would</strong> begin.&rdquo; But when the fact is still true today, you can keep the present: &ldquo;She confirmed that contracts signed before 2025 <strong>are</strong> protected by a <strong>grandfathering clause</strong>.&rdquo;',
            'Sometimes nobody wants to own the information. Then English reports it without a person: &ldquo;The operator <strong>is said to be</strong> preparing a claim.&rdquo; For anyone doing <strong>due diligence</strong>, that structure is a warning. And two Portuguese habits never work here: &ldquo;she said me&rdquo; and &ldquo;she explained me.&rdquo; Say <strong>she told me</strong> and <strong>she explained it to me</strong>.',
        ],
        'context_quiz': [
            ('According to the text, what does the reporting verb tell the investor?', ['How firm the promise was.', 'When the press conference happened.', 'Who wrote the headline.'], 0),
            ('When can you keep the present tense in reported speech?', ['Never, the tense always moves back.', 'When the reported fact is still true today.', 'Only with the verb said.'], 1),
            ('What does &ldquo;The operator is said to be preparing a claim&rdquo; signal?', ['That the operator confirmed it publicly.', 'That the claim has been approved.', 'That nobody wants to own the information.'], 2),
        ],
        'tip_title': 'Reported Speech and Reporting Verbs',
        'tip_lead': 'The verb measures the promise; the tense says whether it is still true.',
        'tip_rows': [
            ('A decision', 'confirmed, announced, stated + that', 'She <strong>confirmed that</strong> the review would begin in October.'),
            ('A signal', 'indicated, suggested, signaled + that', 'She <strong>indicated that</strong> tariffs could fall.'),
            ('A correction or admission', 'clarified, acknowledged + that', 'She <strong>acknowledged that</strong> claims had been filed.'),
            ('Backshift', 'will &rarr; would, is &rarr; was, has &rarr; had', 'The review <strong>would</strong> begin in October.'),
            ('Still true', 'keep the present', 'Old contracts <strong>are</strong> protected.'),
            ('No person', 'subject + is said to + verb', 'The operator <strong>is said to be</strong> preparing a claim.'),
        ],
        'tip_never': 'she said me that &middot; she explained me the rules &middot; she suggested to delay the auction &middot; it is said that the fund to have signed',
        'blanks': [
            ('The director ', 'confirmed', ' that the tariff review would begin in October.', 'Hint: a firm decision -- one reporting verb', None),
            ('The minister ', 'indicated', ' that tariffs could fall on some stretches.', 'Hint: a signal, not a promise -- one reporting verb', None),
            ('She confirmed that the review ', 'would begin', ' after the consultation.', 'Hint: will, one step back in time -- two words', None),
            ('Contracts signed before 2025 are protected by a ', 'grandfathering clause', '.', 'Hint: old contracts keep the old rules -- two words', None),
            ('The operator declared ', 'force majeure', ' after the bridge collapsed.', 'Hint: an event nobody could prevent -- two words', None),
            ('Missing the investment schedule twice is a ', 'material breach', ' of the contract.', 'Hint: a serious failure to meet the contract -- two words', None),
        ],
        'order_title': 'Put the Briefing in Order',
        'order_lead': 'A fund in Toronto missed the press conference. Put your report in a logical order.',
        'order': [
            'The one decision was that the tariff review will begin in October.',
            'The director confirmed that there will be a forty-five-day public consultation first.',
            'She indicated that tariffs could fall on some stretches, but that was only a signal.',
            'She acknowledged that seven operators had filed rebalancing claims after the floods.',
            'She did not say whether the floods would be treated as force majeure.',
            'So my advice is to build two scenarios until the agency takes a position.',
        ],
        'quiz': [
            ('The minister only hinted that rules might change. You report:', ['The minister confirmed the rules will change.', 'The minister indicated that the rules could change.', 'The minister said us the rules change.'], 1),
            ('A regulator corrected a false headline. You report:', ['The regulator clarified that contracts would not be renegotiated.', 'The regulator suggested to not renegotiate.', 'The regulator explained me no renegotiation.'], 0),
            ('You cannot confirm a rumor about an operator. You say:', ['The operator confirmed it is preparing a claim.', 'It is said that the operator to prepare a claim.', 'The operator is said to be preparing a claim.'], 2),
            ('An investor asks if the new rule affects a contract signed in 2023. You say:', ['No, it is protected by a grandfathering clause.', 'No, it is force majeure.', 'No, it is a material breach.'], 0),
        ],
        'think': 'A C-level from Singapore is considering a Brazilian highway concession. In ninety seconds, report what the regulator said this week, making clear what was decided and what was only signaled, and explain force majeure and grandfathering without legal jargon.',
    },
    'media': [
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;Regulate This!&rdquo;',
         'desc': 'What regulation really does to an economy, from people who have written and fought rules for a living. Natural-speed English on the exact tension your investors worry about.',
         'tip': 'Tip: open the transcript on the same page and mark every reporting verb. Which ones signal certainty, and which ones doubt?',
         'url': 'https://freakonomics.com/podcast/regulate-this/', 'cta': 'Listen on Freakonomics'},
        {'id': 'talk', 'type': 'Talk', 'title': 'Rachel Botsman &mdash; &ldquo;We&rsquo;ve stopped trusting institutions and started trusting strangers&rdquo; (TED)',
         'desc': 'How trust moves between institutions, markets and people &mdash; the same question behind every regulatory framework and every investor who asks whether a contract will survive.',
         'tip': 'Tip: retell her main argument to yourself in reported speech, using three different reporting verbs.',
         'url': 'https://www.ted.com/talks/rachel_botsman_we_ve_stopped_trusting_institutions_and_started_trusting_strangers', 'cta': 'Watch on TED'},
        {'id': 'video', 'type': 'Talk', 'title': 'Tim Harford &mdash; &ldquo;Trial, error and the God complex&rdquo; (TED)',
         'desc': 'An economist on why complex systems, from markets to public policy, work better when rules can be tested and corrected &mdash; the thinking behind every regulatory sandbox.',
         'tip': 'Tip: listen for the examples he uses and note one you could bring to a panel on regulation.',
         'url': 'https://www.ted.com/talks/tim_harford_trial_error_and_the_god_complex', 'cta': 'Watch on TED'},
    ],
}
