# -*- coding: utf-8 -*-
# Aula 6 -- The Executive Pen (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The Executive <span class='accent'>Pen</span>",
    'hero_line': 'Twenty minutes after the panel, the press statement has to say exactly what happened',
    'menu_desc': 'Reading a press statement, and the connectors that tell the reader what is coming',
    'grammar_point': 'formal linking devices and be to, be supposed to and have to in executive writing',
    'phases': ['The Draft', 'Words of the Press Room', 'The Guide', 'The Code', 'Same Fact, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'nadia', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch2': U + 'photo-1504384308090-c894fdcc538d?w=1400&q=80',
        'ch3': U + 'photo-1496442226666-8d4d0e62e6e9?w=1400&q=80',
        'ch_grammar': U + 'photo-1541872703-74c5e44368f9?w=1400&q=80',
        'ch5': U + 'photo-1552664730-d307ca884978?w=1400&q=80',
        'ch_rp': U + 'photo-1590283603385-17ffb3a7f29f?w=1400&q=80',
        'pc': U + 'photo-1455390582262-044cdead277a?w=600&q=80',
    },
    'warmup': {
        'heading': "Strong Paragraph, <span class='accent'>Weak Paragraph</span>",
        'sub': 'Think of the last press release you read about an infrastructure deal. What made you stop reading? Answer with two words from last lesson: to push back, common ground, a red line, to reframe.',
    },
    'target': {
        'heading': "Write So the Investor <span class='accent'>Reads to the End</span>",
        'steps': [
            'Put the most important fact in the first sentence, not the third paragraph.',
            'Tell the reader the relationship between two ideas before the second idea arrives.',
            'Say exactly how firm each commitment is: a plan, an obligation, or a promise that already failed.',
        ],
    },
    'diagnostic': {
        'heading': "The First Sentence of <span class='accent'>Tonight&rsquo;s Release</span>",
        'p1': 'The roundtable just ended. The ministry and the sovereign funds agreed to study international arbitration, but no date was set.',
        'p2': 'Dictate the first two sentences of the press statement. Then say which word connects them.',
    },
    'ch2': {'heading': "The Words of the <span class='accent'>Press Room</span>",
            'sub': 'Fourteen terms for anyone who writes for journalists and investors'},
    'vocab': [
        {'word': 'A joint statement', 'def': 'An official statement released together by several organizations at the end of a meeting', 'ex': 'The joint statement listed three commitments and no dates.', 'icon': 'doc'},
        {'word': 'A press statement', 'def': 'A short official text an organization gives to journalists', 'ex': 'The press statement went out twenty minutes after the panel.', 'icon': 'message'},
        {'word': 'A holding statement', 'def': 'A short first statement released while the full facts are still being checked', 'ex': 'We sent a holding statement and promised details by noon.', 'icon': 'clock'},
        {'word': 'An embargo', 'def': 'A request that journalists do not publish information before a set time', 'ex': 'The release is under embargo until six o&rsquo;clock.', 'icon': 'lock'},
        {'word': 'On background', 'def': 'Describes information a journalist may use but not attribute to the speaker by name', 'ex': 'The details of the deal were shared on background.', 'icon': 'eye'},
        {'word': 'On the record', 'def': 'Describes information a journalist may publish and attribute to the speaker by name', 'ex': 'The minister&rsquo;s quote was on the record.', 'icon': 'mic'},
        {'word': 'Material information', 'def': 'Information that could change an investor&rsquo;s decision', 'ex': 'A delay in the auction is material information for the funds.', 'icon': 'alert'},
        {'word': 'Disclosure obligations', 'def': 'The legal duty to make certain information public', 'ex': 'Listed operators have strict disclosure obligations.', 'icon': 'scale'},
        {'word': 'Forward guidance', 'def': 'What an organization says publicly about what it expects to do in the future', 'ex': 'The ministry gave no forward guidance on the timeline.', 'icon': 'compass'},
        {'word': 'Boilerplate', 'def': 'Standard text repeated at the end of every release, such as the paragraph about the organization', 'ex': 'Nobody reads the boilerplate, but it has to be there.', 'icon': 'layers'},
        {'word': 'A key message', 'def': 'The one idea that every sentence of a communication should support', 'ex': 'The key message was that the funds and the ministry are still talking.', 'icon': 'target'},
        {'word': 'Stakeholder alignment', 'def': 'The situation in which the main parties agree on the same direction', 'ex': 'Stakeholder alignment took longer than the engineering.', 'icon': 'users'},
        {'word': 'A spokesperson', 'def': 'The person officially chosen to speak for an organization', 'ex': 'The fund&rsquo;s spokesperson declined to comment.', 'icon': 'flag'},
        {'word': 'A lede', 'def': 'The first sentence of a news story or press release, which gives the most important fact', 'ex': 'The lede should tell the investor what changed today.', 'icon': 'pen'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['A joint statement', 'Disclosure obligations', 'A spokesperson', 'In light of today\'s discussion, the ministry is to publish a draft by March.'],
    'ch3': {'heading': "The Guide Your Comms Team <span class='accent'>Sent</span>", 'sub': 'Read it for the principle. The detail comes after.'},
    'reading': {
        'heading': "Four Drafts of the <span class='accent'>Same Release</span>",
        'rtitle': 'Four Drafts of the Same Release',
        'paras': [
            'The first draft of almost every press statement begins with the organization: who hosted the event, where it took place, and how many distinguished participants attended. It is accurate, and it is useless. An investor in Toronto opening the email at six in the morning wants to know one thing: what changed today. That answer belongs in the lede, the first sentence, and it should be the only fact the reader needs if they stop there.',
            'The second draft usually fixes the lede but loses the key message. Every paragraph adds something true, whereas none of them points in the same direction. By contrast, a good release chooses one idea and makes each sentence support it. If the key message is that the ministry and the funds have found common ground, a paragraph about the venue does not help, albeit pleasing to the sponsor.',
            'The third draft is where the lawyers arrive, and for good reason. Anything that could change an investor&rsquo;s decision is material information, and listed companies in the room have disclosure obligations. Consequently, the words that describe commitments matter more than the adjectives. A ministry that is to publish rules by March has a plan. A report that was supposed to come out in June is a promise that failed. Operators that have to comply within ninety days face an obligation. Mixing the three is the fastest way to lose credibility.',
            'The fourth draft is the one that goes out. It is shorter than the first, the quote from the spokesperson is clearly on the record, and anything shared on background has been removed. It carries an embargo until the markets close, and the boilerplate sits quietly at the bottom. Notwithstanding all this work, the best test is simple: read the first sentence aloud to somebody who was not in the room. If they can repeat it, the release is ready.',
        ],
        'source': 'Written for this lesson, from standard practice in corporate and institutional communications.',
    },
    'gist': {
        'prompt': 'What is the main point of the guide?',
        'choices': [
            ['a', 'A press statement should list the organization, the venue and the participants first.', False],
            ['b', 'A good release puts what changed first, supports one message and describes commitments precisely.', True],
            ['c', 'Lawyers make press releases longer and less useful.', False],
        ],
    },
    'tf': [
        ['According to the guide, the first draft usually starts with what changed today.', 'f', 'The text says the first draft begins with the organization, the venue and the participants.'],
        ['A good release makes every sentence support one idea.', 't', 'The text says a good release chooses one idea and makes each sentence support it.'],
        ['The guide says a report that was supposed to come out in June was published on time.', 'f', 'The text calls it a promise that failed.'],
        ['Information shared on background stays in the final release.', 'f', 'The text says anything shared on background has been removed from the final draft.'],
        ['The final test is whether someone who was not in the room can repeat the first sentence.', 't', 'The text says to read the first sentence aloud to somebody who was not there; if they can repeat it, the release is ready.'],
    ],
    'artifact': {
        'heading': "The Statement Before It <span class='accent'>Goes Out</span>",
        'title': 'PRESS STATEMENT &mdash; EMBARGOED UNTIL 18:00', 'subtitle': 'Infrastructure Roundtable &middot; Contracts That Survive Elections',
        'rows': [
            ('Lede', 'Sovereign funds and the ministry agreed today to study international arbitration for new concessions.', True),
            ('Next step', 'The ministry is to present a draft model by March, albeit without a fixed date for the auction.', False),
            ('Quote (on the record)', '&ldquo;We found common ground on the guarantee.&rdquo; &mdash; Ministry spokesperson', False),
            ('Status of earlier report', 'The concession review was supposed to be published in June; it is now expected in the first quarter.', True),
            ('Boilerplate', 'About the roundtable: a closed-door forum for investors, operators and government.', False),
        ],
        'note': 'Comms note: remove the figures on arbitration costs &mdash; they were shared on background. Legal has checked disclosure obligations for the two listed operators.',
        'qs': [
            ('What is the lede, and until when is the statement embargoed?', 'Sovereign funds and the ministry agreed to study international arbitration for new concessions. It is embargoed until six p.m.'),
            ('What is the ministry to do, and what is still missing?', 'Present a draft model by March. There is still no fixed date for the auction.'),
            ('What does the comms note ask the team to remove, and why?', 'The figures on arbitration costs, because they were shared on background.'),
        ],
    },
    'ch_grammar': {'heading': "The Word Before <span class='accent'>the Idea</span>",
                   'sub': 'Formal connectors, and three ways to say how firm a commitment is'},
    'grammar': {
        'heading': "What Does Each Red Word <span class='accent'>Promise the Reader?</span>",
        'examples': [
            "Investment rose sharply, <span style='color:#b91c1c;font-weight:700'>albeit</span> from a very low base.",
            "Funds want arbitration abroad, <span style='color:#b91c1c;font-weight:700'>whereas</span> the ministry prefers local courts.",
            "<span style='color:#b91c1c;font-weight:700'>In light of</span> the floods, the agency <span style='color:#1d4ed8;font-weight:700'>is to</span> publish new rules by March.",
            "The concession review <span style='color:#1d4ed8;font-weight:700'>was supposed to</span> come out in June, but it was delayed.",
        ],
        'prompt': 'The red words connect ideas. Which one introduces a contrast, which one limits what was just said, and which one gives a cause? Now the blue words: which describes an official plan, and which a plan that did not happen?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Contrast two positions', 'whereas + clause; by contrast,', 'Funds want arbitration abroad, <strong>whereas</strong> the ministry prefers local courts.'),
            ('Limit what you just said', 'albeit + short phrase; that said,', 'Investment rose, <strong>albeit</strong> from a low base.'),
            ('Concede, then continue', 'notwithstanding + noun / this', '<strong>Notwithstanding</strong> the delay, the auction will proceed.'),
            ('Give a cause', 'in light of / as a result of + noun; consequently,', '<strong>In light of</strong> the floods, the dates were revised.'),
            ('An official plan', 'be to + verb', 'The agency <strong>is to publish</strong> the rules by March.'),
            ('A plan that failed', 'was / were supposed to + verb', 'The report <strong>was supposed to come out</strong> in June.'),
            ('An obligation', 'have to + verb', 'Operators <strong>have to comply</strong> within ninety days.'),
        ],
        'oneliner': 'The connector tells the reader the relationship before the idea arrives; be to announces a plan, and was supposed to reports one that failed.',
    },
    'grammar_practice': {
        'heading': "Connect It, and Say <span class='accent'>How Firm It Is</span>",
        'items': [
            ('Funds want arbitration abroad, ', 'whereas', ' the ministry prefers local courts. (contrast)'),
            ('Investment rose sharply, ', 'albeit', ' from a very low base. (limit what you just said)'),
            ('', 'In light of', ' the floods, the agency postponed the auction. (a cause, and a noun follows)'),
            ('The agency ', 'is to publish', ' the new rules by March. (an official plan)'),
            ('The report ', 'was supposed to come out', ' in June, but it was delayed. (a plan that failed)'),
            ('Operators ', 'have to comply', ' within ninety days of publication. (an obligation)'),
        ],
    },
    'detective': [
        ('In light of that the floods happened, the auction was delayed.', '<strong>In light of the floods</strong>, the auction was delayed.'),
        ('Notwithstanding of the delay, the auction will proceed.', '<strong>Notwithstanding the delay</strong>, the auction will proceed.'),
        ('The report was supposed to came out in June.', 'The report was supposed to <strong>come out</strong> in June.'),
        ('The minister gave a declaration to the press.', 'The minister <strong>made a statement</strong> to the press.'),
    ],
    'ch5': {'heading': "Same Fact, <span class='accent'>Other Words</span>", 'sub': 'Equivalence &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Release in <span class='accent'>Spoken English</span>",
    'equiv': {
        'title': 'Match each sentence from the release to the same idea in spoken English',
        'hint': 'Tap a written sentence, then tap the spoken version that means the same',
        'pairs': [
            ('Notwithstanding the delay, the auction will proceed.', 'The auction is still going ahead, even though it was delayed.'),
            ('Investment rose, albeit from a low base.', 'Investment went up, but it started from very little.'),
            ('In light of the floods, the timeline has been revised.', 'Because of the floods, the dates have changed.'),
            ('The agency is to publish the rules by March.', 'The plan is for the agency to publish the rules by March.'),
            ('The report was supposed to be released in June.', 'Everyone expected the report in June, and it did not come.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Story Behind the Release</span>",
    'gap': {
        'parts': [
            'Twenty minutes after the roundtable, the team had a draft ', ['1', 'press statement'],
            ' ready, under an ', ['2', 'embargo'],
            ' until six o&rsquo;clock. Its first sentence, the ', ['3', 'lede'],
            ', gave the single most important fact, and every paragraph supported one ', ['4', 'key message'],
            ': the ministry and the funds had found common ground. The minister&rsquo;s quote was ', ['5', 'on the record'],
            ', but the figures on arbitration had been shared ', ['6', 'on background'],
            ', so they could not appear. The night before, when the rumors started, the team had released only a short ', ['7', 'holding statement'],
            '. And at the bottom, as always, sat the ', ['8', 'boilerplate'], '.',
        ],
        'bank': ['press statement', 'embargo', 'lede', 'key message', 'on the record', 'on background', 'holding statement', 'boilerplate'],
    },
    'quickfire': [
        {'situation': 'Your comms team wrote a first sentence about the venue and the number of participants. Tell them what the lede should say instead.', 'tips': ['The lede has to say what changed today: that the funds and the ministry agreed to study international arbitration.', 'has to for an obligation; what changed today is the test.']},
        {'situation': 'Say that investment grew, but from a very low starting point, in one written-style sentence.', 'tips': ['Investment grew sharply, albeit from a very low base.', 'albeit + a short phrase, never a full sentence.']},
        {'situation': 'A journalist asks whether the concession review is late. Answer precisely.', 'tips': ['It was supposed to be published in June, and it is now expected in the first quarter.', 'was supposed to reports a plan that did not happen.']},
        {'situation': 'Contrast the fund&rsquo;s position and the ministry&rsquo;s position in one sentence.', 'tips': ['The funds want arbitration abroad, whereas the ministry prefers local courts.', 'whereas joins two clauses that contrast.']},
        {'situation': 'A journalist wants to quote the arbitration figures a fund manager mentioned privately. Say no, politely.', 'tips': ['Those figures were shared on background, so we cannot put them on the record.', 'on background = use it, do not name the source.']},
        {'situation': 'Announce the ministry&rsquo;s next step as an official plan.', 'tips': ['In light of today&rsquo;s discussion, the ministry is to present a draft model by March.', 'be to + verb sounds official and planned.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; A Communications Director', 'title': "The Six O&rsquo;Clock <span class='accent'>Reader</span>",
         'blurb': 'A communications director on writing for international investors. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'I ask every writer on my team to picture one reader: an investor in another time zone, opening our release at six in the morning, on a phone, in her second language. She will read the first sentence. She may read the second. After that, we have to earn every line. That is why I cut adjectives before anything else. Distinguished, historic and landmark tell her nothing she can use. What she needs are the relationships between facts, and English gives us small words to show them before the fact arrives. Whereas tells her a contrast is coming. Albeit tells her we are about to limit what we just said. In light of tells her the cause. Get those right, and a reader in her second language can follow a complex argument without effort.',
         'qs': [
             ('Who is the one reader the director asks her team to picture?', 'An investor in another time zone, reading the release at six in the morning, on a phone, in her second language.'),
             ('What does she cut first, and why?', 'Adjectives such as distinguished, historic and landmark, because they tell the reader nothing she can use.'),
             ('What do whereas, albeit and in light of tell the reader?', 'Whereas signals a contrast, albeit signals a limit on what was just said, and in light of gives the cause.'),
         ]},
        {'label': 'Listening 2 &middot; A Journalist', 'title': "What You Can <span class='accent'>Print</span>",
         'blurb': 'A financial journalist explains the rules to a room of executives. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Let me make your life easier by explaining how journalists like me actually work. If you tell me something on the record, I can print it and put your name on it. If you tell me something on background, I can use the information, but I will describe you only as a person familiar with the matter. If you want nothing printed at all, you have to say so before you tell me, not after. And if your release is under embargo until six, I will respect that, but only if the embargo is on the email itself. A final piece of advice. When something goes wrong, send a short holding statement early. Silence is what makes a small story big.',
         'qs': [
             ('What is the difference between on the record and on background, according to the journalist?', 'On the record, he can print it with the person&rsquo;s name. On background, he can use the information but describes the source only as a person familiar with the matter.'),
             ('When must an executive say they want nothing printed?', 'Before telling the journalist, not after.'),
             ('What does he advise when something goes wrong, and why?', 'To send a short holding statement early, because silence makes a small story big.'),
         ]},
    ],
    'roleplays': {
        'heading': "Twenty Minutes to <span class='accent'>Deadline</span>",
        'items': [
            {'heading': "Dictate the <span class='accent'>Lede</span>",
             'scenario': 'Your communications manager is typing. Dictate the lede and the next two sentences of tonight&rsquo;s statement: what changed, what the ministry is to do next, and what is still open.',
             'chips': ['In light of', 'whereas', 'is to', 'a key message']},
            {'heading': "A Journalist <span class='accent'>Calls</span>",
             'scenario': 'A financial journalist calls before the embargo lifts and asks for the arbitration figures a fund manager mentioned privately. Decide what is on the record, what is on background, and give a clean answer.',
             'chips': ['on background', 'on the record', 'a holding statement', 'That said']},
            {'heading': "The Rapporteur <span class='accent'>Summary</span>",
             'scenario': 'Give a spoken ninety-second summary of today&rsquo;s panel for the post-event brief, as if you were writing it: the outcome, the two positions, the next step and what was supposed to happen but did not.',
             'footer': 'No notes, ninety seconds. Use at least four connectors from today.'},
        ],
    },
    'survival_heading': "Five Sentences for the <span class='accent'>Press Room</span>",
    'survival': [
        'In light of today\'s discussion, the ministry is to publish a draft by March.',
        'Investment has risen, albeit from a very low base.',
        'That part is on the record; the arbitration figures are on background.',
        'The report was supposed to come out in June, but it has been delayed.',
        'Every paragraph has to support one key message.',
    ],
    'checklist': [
        'I can write a lede that says what changed today.',
        'I use whereas, albeit, notwithstanding and in light of correctly.',
        'I can say whether a commitment is a plan, an obligation or a plan that failed.',
        'I know what can go on the record and what stays on background.',
        'I know the words: a joint statement, a press statement, a holding statement, an embargo, on background, on the record, material information, disclosure obligations, forward guidance, boilerplate, a key message, stakeholder alignment, a spokesperson, a lede.',
    ],
    'badge': {'name': 'The Executive Pen', 'line': 'What changed goes first, and every connector tells the reader what is coming.',
              'next': 'Next lesson: The Full Room -- moderating a multilateral panel, in speech'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Va direto: \'Guilherme, today we write the way the release will be read.\' Aula de leitura (par) com foco em ESCRITA executiva, que ele pediu no curriculo e que o time dele produz (\'tenho uma equipe que faz os conteudos\'). Ele revisa e aprova esses textos: trate a aula como revisao de um diretor, nao como redacao escolar.',
        'warmup': '<strong>Warm-up com callback (5 min):</strong> Callback da aula 5: duas palavras (to push back, common ground, a red line, to reframe). Depois deixe ele diagnosticar o que faz uma press release perder o leitor. ANOTE a metalinguagem que ele ja tem (register, framing device, pivot).',
        'target': '<strong>Enquadramento (2 min):</strong> Tres regras de texto executivo. Pergunte qual delas o time dele mais quebra.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Ele dita duas frases. ANOTE: o fato principal veio primeiro? Que conectivo ele usou? Quase sempre sai \'and\' ou \'but\'. O capitulo de gramatica amplia isso.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fourteen terms from the press room.\' Varios ele conhece de ouvido: foco em uso preciso (on background x on the record).',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'a holding statement\': \'Complete or partial? (Parcial, provisoria.)\' CCQ \'an embargo\': \'Can the journalist publish at five? (Nao.)\' CCQ \'on background\': \'Can the journalist use your name? (Nao.)\' Pronuncia: com-MU-ni-que, acento na segunda.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'material information\': \'Would it change an investor\'s decision? (Sim.)\' CCQ \'forward guidance\': \'About the past or the future? (Futuro.)\' CCQ \'boilerplate\': \'Different in every release? (Nao, sempre igual.)\'',
        'vocab3': '<strong>Vocab reveal 11-14 (4 min):</strong> CCQ \'a lede\': \'First or last sentence? (Primeira.)\' Grafia jornalistica americana, lede e nao lead. CCQ \'stakeholder alignment\': \'Do they agree on direction? (Sim.)\' Peca a key message real do ultimo evento do GRI.',
        'pron': '<strong>Pronuncia (4 min):</strong> JOINT STATE-ment (as duas palavras com peso), dis-CLO-sure, SPOKES-per-son. Na frase longa, \'is to publish\' tem o \'to\' reduzido; a palavra-chave e March.',
        'matching': '<strong>Matching (4 min):</strong> Pares em voz alta antes de clicar. Se fechar rapido, peca a diferenca entre a joint statement e a press statement.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'A guide your comms team sent you. Read it for the principle.\' Os conectivos e o be to aparecem no texto antes da regra.',
        'reading': '<strong>Leitura (7 min):</strong> Silenciosa, ritmo real. Depois peca UMA frase de resumo e pergunte em qual dos quatro rascunhos os textos do time dele costumam parar. Deixe virar conversa.',
        'gist': '<strong>Gist (3 min):</strong> Ele escolhe e justifica. A alternativa c e uma leitura apressada do terceiro paragrafo: se ele hesitar, peca que releia.',
        'tf': '<strong>True or False (6 min):</strong> TRUE ou FALSE, com a linha que prova lida em voz alta. Na terceira, cobre a diferenca entre is to e was supposed to.',
        'artifact': '<strong>Artefato (4 min):</strong> Press statement antes de sair. Peca que ele revise como diretor: o lede esta bom? a nota de comms esta certa? So depois as perguntas. Aponte albeit e was supposed to no texto.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences. Each red word promises the reader something.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte o que cada palavra vermelha anuncia (contraste, limite, causa). Depois as azuis: plano oficial x plano que falhou. So entao Reveal the Rule. CCQ: \'albeit &mdash; does it make the first idea stronger or weaker? (Mais fraca, limita.)\' CCQ: \'The agency is to publish &mdash; has it published? (Nao, e o plano oficial.)\' CCQ: \'was supposed to &mdash; did it happen? (Nao.)\' Obstaculos do brasileiro avancado: \'in light of that + frase\', \'notwithstanding of\', e \'supposed to came\'. Pragmatica: em comunicado, trocar is to por will ou was supposed to por was expected to muda a responsabilidade juridica.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Frase inteira antes de clicar. Se fechar rapido, peca que ele reescreva a frase de abertura do slide 4 com um conectivo e um be to.',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige antes de clicar. Tres erros de conectivo e forma verbal, e um calco classico: \'give a declaration\' (dar uma declaracao) em vez de make a statement. Correcao direta.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same fact, other words: written and spoken English, the story behind the release, one question at a time, two recordings.\'',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ele fecha o par e explica. O ponto: o texto escrito e o falado dizem o mesmo com registros diferentes, e ele precisa dos dois &mdash; escreve de manha e fala no palco a tarde.',
        'gap': '<strong>Gap-fill (5 min):</strong> Banco embaixo; arrastar, tocar ou digitar, e Check. No fim, ele le o paragrafo inteiro em voz alta.',
        'quickfire': '<strong>Quick fire (6 min):</strong> Uma por vez. Ele responde antes das dicas. Cobre registro escrito nas situacoes de texto e falado nas de telefone. Correcao em bloco.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar. Diretora de comunicacao. Toque duas vezes. Depois: \'Which adjectives would she cut from the last GRI release?\'',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Jornalista explicando as regras. Pergunte se ele ja teve uma informacao de bastidor publicada com nome.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'Twenty minutes to deadline. Three times.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a gerente de comunicacao, digitando. Ele dita. Leia de volta exatamente o que ele disse: ele ouve se o lede ficou claro. Corrija em bloco.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o jornalista, insistente e simpatico. Tente arrancar os numeros. Ele decide o que e on the record e o que fica on background, sem ser grosso.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Noventa segundos de resumo falado com cara de texto escrito. No fim: quantos conectivos de hoje? houve um be to e um was supposed to? uma observacao de ritmo.',
        'survival': '<strong>Survival card (3 min):</strong> Audio e repeticao. Peca que ele use uma frase ao revisar o proximo texto real do time.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 = aula concluida e stamp 6. Item em que ele hesitar entra no warm-up da aula 7.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'What changed goes first. Every connector tells the reader what is coming.\' Homework (ORALMENTE, nunca escrito na tela): escrever uma press statement de 200 palavras sobre a mesa ficticia de hoje, com cinco conectivos e dois usos de be to ou be supposed to; e achar um comunicado real de um organismo multilateral e sublinhar tres conectivos. Proxima aula: a sala cheia &mdash; moderar um painel multilateral, em fala.',
    },
    'pc': {
        'title': 'The Executive Pen -- The Word Before the Idea',
        'desc': 'Twenty minutes after the roundtable, the press statement has to say exactly what changed, and exactly how firm every commitment is.',
        'match_idx': [2, 3, 4, 6, 10, 13],
        'context': [
            'An investor reading your release in her second language needs two things from every sentence: the fact, and its relationship to the fact before it. Good executive writing gives her the relationship first, with a small word that arrives before the idea.',
            '<strong>Whereas</strong> announces a contrast between two positions: &ldquo;The funds want arbitration abroad, <strong>whereas</strong> the ministry prefers local courts.&rdquo; <strong>Albeit</strong> limits what you have just said, and it takes a short phrase, not a full sentence: &ldquo;Investment rose, <strong>albeit</strong> from a low base.&rdquo; <strong>Notwithstanding</strong> concedes a problem and moves on: &ldquo;<strong>Notwithstanding</strong> the delay, the auction will proceed.&rdquo; <strong>In light of</strong> gives a cause, and a noun must follow it: &ldquo;<strong>In light of</strong> the floods, the dates were revised.&rdquo;',
            'The second job is to describe commitments precisely, because a commitment in a <strong>press statement</strong> can become <strong>material information</strong>. <strong>Be to</strong> announces an official plan: &ldquo;The ministry <strong>is to</strong> present a draft by March.&rdquo; <strong>Was supposed to</strong> reports a plan that did not happen: &ldquo;The review <strong>was supposed to</strong> come out in June.&rdquo; <strong>Have to</strong> states an obligation: &ldquo;Operators <strong>have to</strong> comply within ninety days.&rdquo;',
            'Put the three together and a reader who was not in the room can follow the whole story from the <strong>lede</strong> to the <strong>boilerplate</strong>. Mix them up, and the same reader will call your <strong>spokesperson</strong> to ask what you really meant.',
        ],
        'context_quiz': [
            ('According to the text, what should good executive writing give the reader first?', ['The name of the organization.', 'The relationship between the facts, with a small word before the idea.', 'A list of all the participants.'], 1),
            ('What must follow in light of?', ['A noun.', 'A full sentence with that.', 'An adjective.'], 0),
            ('What does was supposed to report?', ['An official plan for the future.', 'A legal obligation.', 'A plan that did not happen.'], 2),
        ],
        'tip_title': 'Formal Connectors and Commitments',
        'tip_lead': 'The connector tells the reader what is coming; be to, was supposed to and have to say how firm the commitment is.',
        'tip_rows': [
            ('Contrast', 'whereas + clause', 'Funds want arbitration abroad, <strong>whereas</strong> the ministry does not.'),
            ('Limit', 'albeit + short phrase', 'Investment rose, <strong>albeit</strong> from a low base.'),
            ('Concede and continue', 'notwithstanding + noun', '<strong>Notwithstanding the delay</strong>, the auction will proceed.'),
            ('Cause', 'in light of + noun', '<strong>In light of the floods</strong>, the dates changed.'),
            ('Official plan', 'be to + verb', 'The ministry <strong>is to present</strong> a draft by March.'),
            ('Plan that failed / obligation', 'was supposed to + verb / have to + verb', 'It <strong>was supposed to come out</strong> in June. Operators <strong>have to comply</strong>.'),
        ],
        'tip_never': 'in light of that the floods happened &middot; notwithstanding of the delay &middot; was supposed to came out &middot; gave a declaration to the press',
        'blanks': [
            ('Funds want arbitration abroad, ', 'whereas', ' the ministry prefers local courts.', 'Hint: introduces a contrast between two clauses -- one word', None),
            ('Investment rose sharply, ', 'albeit', ' from a very low base.', 'Hint: limits what you just said, and a short phrase follows -- one word', None),
            ('The ministry ', 'is to', ' present a draft model by March.', 'Hint: an official plan -- two words', None),
            ('The review ', 'was supposed to', ' come out in June, but it was delayed.', 'Hint: a plan that did not happen -- three words', None),
            ('The release is under ', 'embargo', ' until six o\'clock.', 'Hint: journalists cannot publish before this time -- one word', None),
            ('The minister\'s quote was ', 'on the record', ', so the journalist used his name.', 'Hint: can be published with the speaker\'s name -- three words', None),
        ],
        'order_title': 'Put the Press Statement in Order',
        'order_lead': 'Put the sentences of tonight&rsquo;s press statement in a logical order, from the lede to the boilerplate.',
        'order': [
            'Sovereign funds and the ministry agreed today to study international arbitration for new concessions.',
            'In light of the discussion, the ministry is to present a draft model by March.',
            'The funds want arbitration abroad, whereas the ministry prefers a hybrid model.',
            'The concession review was supposed to be published in June, and it is now expected in the first quarter.',
            'We found common ground on the guarantee, said the ministry spokesperson.',
            'About the roundtable: a closed-door forum for investors, operators and government.',
        ],
        'quiz': [
            ('Your first sentence should tell the investor:', ['Where the event took place.', 'What changed today.', 'How many people attended.'], 1),
            ('You want to limit a positive fact in writing. You write:', ['Investment rose, albeit from a low base.', 'Investment rose, albeit it was low before.', 'Investment rose, albeit of a low base.'], 0),
            ('A report did not come out on the date everyone expected. You write:', ['The report is to come out in June.', 'The report has to come out in June.', 'The report was supposed to come out in June.'], 2),
            ('A journalist asks for figures a fund shared privately. You say:', ['Those were shared on background, so we cannot put them on the record.', 'Those are on the record, sorry.', 'Those figures are boilerplate.'], 0),
        ],
        'think': 'The roundtable just ended. Record a ninety-second version of tonight&rsquo;s press statement as you would dictate it to your team: the lede, the two positions, the ministry&rsquo;s next step, one plan that did not happen, and the quote on the record. Use at least four connectors from today.',
    },
    'media': [
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;Why Is Academic Writing So Bad?&rdquo;',
         'desc': 'Why experts write in a way nobody wants to read, and what clear writers do differently. Every point applies to briefing notes and press statements.',
         'tip': 'Tip: after listening, take the last text your team sent you and cut three adjectives from the first paragraph.',
         'url': 'https://freakonomics.com/podcast/why-is-academic-writing-so-bad/', 'cta': 'Listen on Freakonomics'},
        {'id': 'talk', 'type': 'Talk', 'title': 'David McCandless &mdash; &ldquo;The beauty of data visualization&rdquo; (TED)',
         'desc': 'How to turn a mass of numbers into one clear message &mdash; the same discipline as choosing the key message of a release about a multi-billion infrastructure deal.',
         'tip': 'Tip: note how he states the point of each chart in one sentence before he explains it. That sentence is a lede.',
         'url': 'https://www.ted.com/talks/david_mccandless_the_beauty_of_data_visualization', 'cta': 'Watch on TED'},
        {'id': 'video', 'type': 'Talk', 'title': 'Hans Rosling &mdash; &ldquo;The best stats you&rsquo;ve ever seen&rdquo; (TED)',
         'desc': 'A master class in making complex data understandable to a room of non-specialists, with the relationships between facts made visible at every step.',
         'tip': 'Tip: listen for the connectors he uses between facts. Write down three and use them in your next briefing note.',
         'url': 'https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen', 'cta': 'Watch on TED'},
    ],
}
