# -*- coding: utf-8 -*-
# Aula 3 -- The Art of the Opening (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "The Art of the <span class='accent'>Opening</span>",
    'hero_line': 'Four minutes, three hundred people, and no script in your hand',
    'menu_desc': 'Setting the tone of a summit, and the inversion that makes a room sit up -- 34 slides',
    'grammar_point': 'negative and limiting inversion for emphasis in a conference opening',
    'phases': ['The Stage', 'Words of the Room', 'The Code', 'The Rehearsal', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'dana', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1475721027785-f74eccf877e2?w=1400&q=80',
        'ch2': U + 'photo-1540575467063-178a50c2df87?w=1400&q=80',
        'ch_grammar': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch4': U + 'photo-1511578314322-379afb476865?w=1400&q=80',
        'ch5': U + 'photo-1517245386807-bb43f82c33c4?w=1400&q=80',
        'ch_rp': U + 'photo-1515169067868-5387ec356754?w=1400&q=80',
        'ch7': U + 'photo-1449824913935-59a10b8d2000?w=1400&q=80',
        'pc': U + 'photo-1475721027785-f74eccf877e2?w=600&q=80',
    },
    'warmup': {
        'heading': "The Best Opening You <span class='accent'>Ever Heard</span>",
        'sub': 'Who gave it, what did they do in the first thirty seconds, and why did it work? Bring in two words from last lesson: an anchor investor, blended finance, a risk-adjusted return, a currency hedge.',
    },
    'target': {
        'heading': "Thirty Seconds That <span class='accent'>Decide the Room</span>",
        'steps': [
            'Skip what the screen already says: your name, the agenda, the sponsors.',
            'Give the room one idea, and make the key sentence impossible to ignore.',
            'Plan the turn and the handover before you walk on stage.',
        ],
    },
    'diagnostic': {
        'heading': "Open the Summit <span class='accent'>Now</span>",
        'p1': 'The producer gives you the microphone: &ldquo;Doors open in two minutes. Give me your first thirty seconds, exactly as you would say them.&rdquo;',
        'p2': 'Do it now, with no preparation. Then say what you would change.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>the Room</span>",
            'sub': 'Fourteen words for running a stage, from the first sentence to the handover'},
    'vocab': [
        {'word': 'To convene', 'def': 'To bring people together for a formal meeting', 'ex': 'GRI convenes people who rarely sit at the same table.', 'icon': 'users'},
        {'word': 'To coalesce around', 'def': 'To come together and agree on one idea or position', 'ex': 'By the end of the session, the panel had coalesced around one proposal.', 'icon': 'target'},
        {'word': 'An inflection point', 'def': 'A moment when a trend changes direction', 'ex': 'This auction is an inflection point for rail in the region.', 'icon': 'chart'},
        {'word': 'Agenda-setting', 'def': 'Deciding which questions a discussion will focus on', 'ex': 'The first five minutes of a panel are agenda-setting.', 'icon': 'calendar'},
        {'word': 'A framing device', 'def': 'A story, image or question used to shape how the audience sees a topic', 'ex': 'The empty highway was the framing device for the whole opening.', 'icon': 'eye'},
        {'word': 'A rhetorical pivot', 'def': 'A planned turn in a speech from one idea to another', 'ex': 'But that is not the whole story was the rhetorical pivot of her talk.', 'icon': 'refresh'},
        {'word': 'A keynote', 'def': 'The main speech that opens or defines an event', 'ex': 'The minister&rsquo;s keynote set expectations too high.', 'icon': 'mic'},
        {'word': 'A fireside chat', 'def': 'An informal on-stage interview between a moderator and one guest', 'ex': 'The CEO preferred a fireside chat to a formal presentation.', 'icon': 'message'},
        {'word': 'To open the floor', 'def': 'To invite questions or comments from the audience', 'ex': 'After two questions from me, I will open the floor.', 'icon': 'hand'},
        {'word': 'A housekeeping note', 'def': 'Practical information for the audience, such as timing, exits or microphones', 'ex': 'One housekeeping note: the session ends at six sharp.', 'icon': 'clock'},
        {'word': 'A show of hands', 'def': 'Asking the audience to raise their hands to answer a question', 'ex': 'A quick show of hands: who here has invested in Brazil before?', 'icon': 'flag'},
        {'word': 'To set the tone', 'def': 'To establish the mood or style of an event from the start', 'ex': 'The first sentence sets the tone for the whole summit.', 'icon': 'compass'},
        {'word': 'A curtain-raiser', 'def': 'A short event or remark that comes before the main one', 'ex': 'The dinner was a curtain-raiser for the roundtable the next morning.', 'icon': 'star'},
        {'word': 'To hand over to', 'def': 'To give the stage or the discussion to another person', 'ex': 'With that, let me hand over to our first panelist.', 'icon': 'link'},
    ],
    'pron_heading': "The Pause Is Part of the <span class='accent'>Sentence</span>",
    'pron': ['To coalesce around', 'An inflection point', 'A rhetorical pivot', 'Rarely do we have every stakeholder in the same room.'],
    'vocab_fill': [
        ('Before the minister speaks, I would like a quick ', 'show of hands', ': who has waited more than a year for a license?'),
        ('The auction this year is ', 'an inflection point', ': after it, the region will look different to investors.'),
        ('We have ten minutes left, so I will ', 'open the floor', ' for questions.'),
        ('One ', 'housekeeping note', ': the session ends at eleven because the minister has a flight.'),
        ('The first thirty seconds ', 'set the tone', ' for the next ninety minutes.'),
        ('With that, let me ', 'hand over to', ' our first panelist from Toronto.'),
    ],
    'ch_grammar': {'heading': "The Sentence That Makes the Room <span class='accent'>Sit Up</span>",
                   'sub': 'Word order you almost never use, and exactly when to use it'},
    'grammar': {
        'heading': "What Happened to the <span class='accent'>Word Order?</span>",
        'examples': [
            "<span style='color:#b91c1c;font-weight:700'>Not since</span> 2008 <span style='color:#b91c1c;font-weight:700'>has</span> infrastructure capital been this cautious.",
            "<span style='color:#b91c1c;font-weight:700'>Only by</span> aligning the regulator and the investor <span style='color:#b91c1c;font-weight:700'>can</span> we unlock long-term money.",
            "<span style='color:#b91c1c;font-weight:700'>Rarely do</span> we see every stakeholder at the same table.",
            "<span style='color:#b91c1c;font-weight:700'>Never before have</span> so many sovereign funds asked about the region.",
        ],
        'prompt': 'Say each one in normal word order first. What moved, and what came before the subject? Why would a speaker choose the harder version in the first minute of an opening, and why only once?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Stress a long gap in time', 'Not since + time + auxiliary + subject', 'Not since 2008 <strong>has capital been</strong> this cautious.'),
            ('Stress a single condition', 'Only by + -ing + auxiliary + subject', 'Only by working together <strong>can we</strong> close the gap.'),
            ('Stress how unusual it is', 'Rarely / Seldom + do/does + subject + verb', 'Rarely <strong>do we see</strong> all stakeholders together.'),
            ('Stress a first time', 'Never before + have + subject + past participle', 'Never before <strong>have so many funds</strong> asked.'),
            ('Stress two facts at once', 'Not only + auxiliary + subject + verb, but', 'Not only <strong>did the auction close</strong>, but it closed early.'),
            ('Use it once', 'one inversion per opening', 'Two in a row sounds like a sermon, not a summit.'),
            ('The trap', 'never skip the auxiliary', 'Not <em>Rarely we see</em>. Say <strong>Rarely do we see</strong>.'),
        ],
        'oneliner': 'Limiting word first, then the auxiliary, then the subject -- once, exactly where the room needs to sit up.',
    },
    'grammar_practice': {
        'heading': "Invert It, <span class='accent'>Once</span>",
        'items': [
            ('', 'Not since', ' 2008 has infrastructure capital been this cautious. (a long gap in time)'),
            ('Only by aligning the regulator and the investor ', 'can we', ' unlock long-term money. (auxiliary, then subject)'),
            ('', 'Rarely do', ' we see every stakeholder at the same table. (how unusual it is)'),
            ('Never before ', 'have so many', ' sovereign funds asked about the region. (a first time)'),
            ('Not only ', 'did the auction close', ', but it closed a month early. (past, with did)'),
            ('Seldom ', 'does a regulator', ' agree to speak first. (present, one regulator)'),
        ],
    },
    'ch4': {'heading': "Twenty Minutes Before <span class='accent'>the Doors Open</span>",
            'sub': 'A rehearsal, two recordings and the speaker brief'},
    'dialogue': {
        'heading': "The <span class='accent'>Rehearsal</span>",
        'guest_name': 'Dana', 'guest_initial': 'D',
        'lines': [
            ('d', 'Guilherme, we have twenty minutes before the doors open. Run the first thirty seconds for me, exactly as you will say them.'),
            ('g', 'Good morning. My name is Guilherme Caneli, and it is a pleasure to welcome you to the summit on behalf of the whole team...'),
            ('d', 'Stop. Your name is already on the screen behind you. What is the one idea you want them to walk out with?'),
            ('g', 'That this is <span class="vocab-highlight">an inflection point</span>. Not since the last decade has so much capital been looking at the region.'),
            ('d', 'Better. Say it again, and pause after the word region. Now, how do you <span class="vocab-highlight">set the tone</span> without sounding like <span class="vocab-highlight">a keynote</span>?'),
            ('g', 'I use <span class="vocab-highlight">a framing device</span>: <span class="vocab-highlight">a show of hands</span>. Who here has signed a thirty-year contract in Latin America? Then I say that rarely do we have the people who signed it and the people who regulate it in one room.'),
            ('d', 'I like it. And <span class="vocab-highlight">the rhetorical pivot</span>? You cannot stay optimistic for four minutes.'),
            ('g', 'The pivot is the rules. Only by fixing the contracts can we move the money that has been waiting for years.'),
            ('d', 'Good. Keep one <span class="vocab-highlight">housekeeping note</span> for the very end, and do not <span class="vocab-highlight">open the floor</span> until after the second question.'),
            ('g', 'Agreed. Then I <span class="vocab-highlight">hand over to</span> the first panelist, and we begin.'),
        ],
        'comp': [
            ('How long do they have before the doors open, and what does Dana ask him to do?', 'Twenty minutes. She asks him to run the first thirty seconds exactly as he will say them.'),
            ('Why does Dana stop him, and what does she want instead?', 'Because his name is already on the screen. She wants the one idea the audience should walk out with.'),
            ('What does she tell him to do after the word region?', 'Pause.'),
            ('What are her two instructions at the end?', 'Keep one housekeeping note for the very end, and do not open the floor until after the second question.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Speaking Coach', 'title': "The Thirty Seconds Nobody <span class='accent'>Plans</span>",
         'blurb': 'A coach on why most conference openings fail. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Most conference openings waste their first thirty seconds, and they waste them in the same way. The speaker thanks the organizers, thanks the sponsors, reads the agenda and says his own name, which is already on the screen behind him. By the time he reaches an idea, half the room is reading email. The first thirty seconds are the only moment when every person in the hall is listening at the same time, so spend them on the one thing you want remembered. Then plan two more moments before you walk on stage: the turn, where you move from the good news to the hard question, and the handover, where you give the stage away cleanly. Thank the sponsors at the end. They will survive, and your audience will still be awake.',
         'qs': [
             ('According to the coach, what do most speakers do in the first thirty seconds?', 'They thank the organizers and sponsors, read the agenda and say their own name, which is already on the screen.'),
             ('Why does he say the first thirty seconds are special?', 'It is the only moment when every person in the hall is listening at the same time.'),
             ('What two other moments should a speaker plan, and when should the sponsors be thanked?', 'The turn from good news to the hard question, and the handover. The sponsors should be thanked at the end.'),
         ]},
        {'label': 'Listening 2 &middot; The Summit', 'title': "Keep Your Hands <span class='accent'>Up</span>",
         'blurb': 'A moderator opens a morning session. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Good morning, and welcome. I am not going to read you the agenda; it is already in your hands. Instead, I would like a quick show of hands. How many of you have waited more than a year for a regulator to publish a date? Keep your hands up if that delay changed your investment decision. Now look around the room. Rarely do we have the people who waited and the people who made them wait in the same place, and this morning we do. Over the next ninety minutes we will talk about three things: contracts, currency and courage. One housekeeping note before we begin: the session ends at eleven sharp, because the minister has a flight to catch. With that, let me hand over to our first panelist.',
         'qs': [
             ('What does the moderator refuse to do, and why?', 'She refuses to read the agenda, because the audience already has it in their hands.'),
             ('What is the show of hands about, and what does she ask people to do next?', 'Who has waited more than a year for a regulator to publish a date. Then to keep their hands up if the delay changed their investment decision.'),
             ('What three things will the session cover, and why does it end at eleven?', 'Contracts, currency and courage. It ends at eleven because the minister has a flight to catch.'),
         ]},
    ],
    'artifact': {
        'heading': "The Speaker Brief from <span class='accent'>Production</span>",
        'title': 'SPEAKER BRIEF &mdash; OPENING REMARKS', 'subtitle': 'Infrastructure Americas Summit &middot; New York &middot; 09:00',
        'rows': [
            ('Speaker', 'G. Caneli &mdash; 4 minutes, no lectern', True),
            ('Audience', 'About 300: investors 45% &middot; operators 30% &middot; government 25%', False),
            ('Goal', 'Set the tone for Panel 1 on contract stability', True),
            ('Please avoid', 'Reading the agenda &middot; listing sponsors &middot; slides', False),
            ('Hand over to', 'Panel 1 moderator, after one housekeeping note', False),
        ],
        'note': 'Producer note: one show of hands maximum &mdash; house lights go up on the audience for it. Sponsors are thanked by the closing speaker.',
        'qs': [
            ('How long is the opening, and what should it set the tone for?', 'Four minutes, and it should set the tone for Panel 1 on contract stability.'),
            ('What three things does the brief ask him to avoid?', 'Reading the agenda, listing sponsors and using slides.'),
            ('What happens during the show of hands, and who thanks the sponsors?', 'The house lights go up on the audience. The closing speaker thanks the sponsors.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Host</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('Rarely we see all the stakeholders together.', 'Rarely <strong>do we see</strong> all the stakeholders together.'),
        ('Not since 2008 capital has been this cautious.', 'Not since 2008 <strong>has capital been</strong> this cautious.'),
        ('Only by working together we can close the gap.', 'Only by working together <strong>can we</strong> close the gap.'),
        ('Now I will pass the word to the minister.', 'Now I will <strong>hand over to</strong> the minister.'),
    ],
    'speaking': [
        ('How do you open a panel when the audience is tired?', 'I skip the agenda and ask for a show of hands. Rarely does a room stay tired once it has to answer a question.'),
        ('What is the one idea for this summit?', 'That this is an inflection point. Not since the last decade has so much capital been looking at the region.'),
        ('How do you move from optimism to the hard part?', 'I plan a rhetorical pivot: the rules. Only by fixing the contracts can we move the money that is waiting.'),
        ('When do you open the floor?', 'After the second question. Until then, the agenda-setting belongs to the panel.'),
    ],
    'building': [
        ('not since / 2008 / capital / be / this cautious (a long gap in time)', 'Not since 2008 has capital been this cautious.'),
        ('rarely / we / see / every stakeholder at the same table (how unusual)', 'Rarely do we see every stakeholder at the same table.'),
        ('only by / fix the contracts / we / can / move the money (one condition)', 'Only by fixing the contracts can we move the money.'),
        ('never before / so many funds / ask about the region (a first time)', 'Never before have so many funds asked about the region.'),
    ],
    'roleplays': {
        'heading': "The Opening, <span class='accent'>Three Times</span>",
        'items': [
            {'heading': "Dana Asks <span class='accent'>Again</span>",
             'scenario': 'Dana wants the first thirty seconds one more time: one idea, one inversion, one pause in the right place, and no name, no agenda, no sponsors.',
             'chips': ['Not since', 'an inflection point', 'to set the tone', 'a show of hands']},
            {'heading': "The Minister Is <span class='accent'>Late</span>",
             'scenario': 'The minister&rsquo;s flight is delayed and the first panelist is not ready. Fill two minutes without a script, change the order of the session and hand over to the pension fund instead.',
             'chips': ['One housekeeping note', 'a rhetorical pivot', 'to hand over to', 'Only by']},
            {'heading': "Four Minutes, <span class='accent'>No Script</span>",
             'scenario': 'Open the Infrastructure Americas Summit in New York. The theme is &ldquo;Capital, Concessions and the Road to 2030.&rdquo;',
             'footer': 'No script. One inversion only, one show of hands, one pivot, and a clean handover.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for the <span class='accent'>Next Stage</span>", 'sub': 'What you walk on stage with'},
    'survival_heading': "Five Sentences for the <span class='accent'>Next Stage</span>",
    'survival': [
        'Rather than read you the agenda, let me ask for a quick show of hands.',
        'Not since the last decade has so much capital been looking at this region.',
        'Rarely do we have the people who sign the contracts and the people who regulate them in the same room.',
        'Only by fixing the rules can we move the money that has been waiting.',
        'With that, let me hand over to our first panelist.',
    ],
    'checklist': [
        'I can open a session without my name, the agenda or the sponsors.',
        'I use one inversion, with the auxiliary before the subject, where the room needs to sit up.',
        'I can plan a rhetorical pivot from good news to the hard question.',
        'I can use a show of hands, a housekeeping note and a clean handover.',
        'I know the words: to convene, to coalesce around, an inflection point, agenda-setting, a framing device, a rhetorical pivot, a keynote, a fireside chat, to open the floor, a housekeeping note, a show of hands, to set the tone, a curtain-raiser, to hand over to.',
    ],
    'badge': {'name': 'The Art of the Opening', 'line': 'One idea, one inversion, one pause, and a clean handover.',
              'next': 'Next lesson: The Rules of the Game -- regulatory language and reported speech, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Va direto: \'Guilherme, today you open a summit with no script.\' Esta aula e o coracao do que ele pediu: oratoria sem precisar se preparar muito antes. Ele JA faz aberturas de conferencia, inclusive em Nova York: trate como coaching de palco entre profissionais, nao como aula de apresentacao.',
        'warmup': '<strong>Warm-up com callback (5 min):</strong> Callback da aula 2: duas palavras da aula passada na resposta (an anchor investor, blended finance, a risk-adjusted return, a currency hedge). ANOTE se aparecem naturalmente. Depois deixe ele analisar a melhor abertura que ja viu: e conversa entre pares, com opiniao.',
        'target': '<strong>Enquadramento (2 min):</strong> Tres regras de palco. Pergunte quais ele ja segue e qual quebra por habito (quase todo mundo diz o proprio nome e agradece patrocinador no inicio).',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Trinta segundos, sem preparacao. Cronometre e ANOTE: a primeira frase, se ha uma ideia central, onde ele pausa. Nao corrija. O role-play guiado repete o mesmo pedido para comparar.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fourteen words for running a stage.\' Ele provavelmente conhece varias passivamente: o objetivo e usa-las ativamente e com o acento certo.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'to convene\': \'Do you convene a meeting or attend it? (Convoca/reune.)\' CCQ \'to coalesce around\': \'Do people start together or end together? (Terminam juntos.)\' CCQ \'an inflection point\': \'Does the trend continue or change? (Muda.)\' Peca o exemplo de um inflection point real no setor dele.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a fireside chat\': \'One guest or a panel? (Um convidado.)\' CCQ \'to open the floor\': \'Who speaks after you open the floor? (A plateia.)\' CCQ \'a housekeeping note\': \'Is it about the content or about practical things? (Praticas.)\' Obstaculo: \'give the word to\' (calco de \'passar a palavra\') &mdash; guarde para o Detective.',
        'vocab3': '<strong>Vocab reveal 11-14 (4 min):</strong> CCQ \'a curtain-raiser\': \'Before or after the main event? (Antes.)\' CCQ \'to hand over to\': \'Are you keeping the stage or giving it away? (Entregando.)\' Peca que ele monte a frase de handover que usaria amanha.',
        'pron': '<strong>Pronuncia e pausa (4 min):</strong> co-a-LESCE (tres silabas, acento na ultima), in-FLEC-tion, rhe-TOR-i-cal. Na frase longa, a inversao so funciona com PAUSA curta depois de \'room\' e voz descendo. Grave e ouca com ele se ele topar: e o feedback de palco que ele pediu.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Palavras no banco embaixo. Ele diz a palavra antes de clicar. Em C1+ vai rapido: se fechar logo, peca que ele encadeie as seis frases numa abertura de verdade, na ordem que fizer sentido.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences with strange word order. Say them the normal way first.\' Passe ao proximo.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Peca que ele diga cada frase na ordem normal (\'Capital has not been this cautious since 2008\'). Pergunte: \'What moved to the front, and what came before the subject?\' Espere ele ver o auxiliar antes do sujeito. So entao Reveal the Rule. CCQ: \'Rarely do we see &mdash; is it common or unusual? (Incomum.)\' CCQ: \'Why do, and not nothing? (A inversao exige auxiliar.)\' Pragmatica decisiva: UMA inversao por abertura. Duas seguidas soam como sermao &mdash; ele e extrovertido e pode exagerar no efeito.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Frase inteira, com a pausa e a voz descendo, antes de clicar. Nas duas ultimas cobre o auxiliar no tempo certo (did no passado, does no presente singular).',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Twenty minutes before the doors open. A rehearsal, two recordings and the speaker brief.\' Passe ao proximo.',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e a Dana, head of content do summit: direta, experiente, sem paciencia para abertura burocratica. Next Line e audio a cada fala. Nas falas do Guilherme, ele fala PRIMEIRO. PRAGMATICA para o fim: a primeira fala dele e exatamente o que o coach do Listening 1 critica, e a Dana corta. Pergunte se ele ja abriu assim.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre a DANA (REGRA 27F). Ele responde antes de revelar. Na terceira, faca ele DIZER a frase com a pausa que ela pediu.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar. Coach falando dos trinta segundos. Toque duas vezes. Depois: \'Which of these mistakes did you make in the diagnostic?\' &mdash; compare com a anotacao do slide 4.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Agora e uma abertura real, voz feminina: show of hands, uma inversao (\'Rarely do we have\'), housekeeping note e handover. Peca que ele identifique os quatro movimentos na ordem.',
        'artifact': '<strong>Artefato (4 min):</strong> O speaker brief da producao, com o nome dele. Peca que ele transforme o brief numa frase de planejamento: \'What I need to do in four minutes is...\'. So depois as perguntas. Aponte o que o brief proibe: e o mesmo que o coach criticou.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\' Passe ao proximo.',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige antes de clicar. Tres erros de inversao sem auxiliar (o erro tipico de quem conhece a estrutura so de leitura) e um calco: \'pass the word\' (passar a palavra). Correcao direta.',
        'speaking': '<strong>Speaking (5 min):</strong> Perguntas em velocidade normal, como a Dana faria. Ele responde por completo; a tela e so sugestao. Uma inversao por resposta, no maximo. Correcao em bloco no fim: vocabulario, estrutura, pausa.',
        'building': '<strong>Sentence Building (4 min):</strong> Frase completa em voz alta antes de clicar, com pausa. Se fechar as quatro sem ajuda, ganhe tempo para o role-play livre, que e o mais importante desta aula.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The opening, three times. The last one is four minutes with no script.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a Dana. Mesmo pedido do slide 4. Compare explicitamente com o diagnostico: menos burocracia, uma ideia, uma inversao, pausa no lugar certo? Diga a ele o que mudou.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Imprevisto de palco: ministro atrasado. Ele precisa improvisar dois minutos, reordenar a sessao e fazer handover para o fundo. E exatamente a \'desenvoltura de sair falando\' que ele quer. Nao ajude.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Quatro minutos, sem roteiro, sem interrupcao. Cronometre. No fim, quatro checagens: uma ideia central? uma inversao? um pivot? handover limpo? Depois UMA observacao de pausa ou acento.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'Five sentences you can take to the next stage.\' Passe ao proximo.',
        'survival': '<strong>Survival card (3 min):</strong> Audio e repeticao, com pausa e voz descendo. Peca que ele use pelo menos uma na proxima abertura ou reuniao real e conte na aula 4.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 = aula concluida e stamp 3. Item em que ele hesitar entra no warm-up da aula 4.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Your name is on the screen. Your idea is what they take home.\' Homework (ORALMENTE, nunca escrito na tela): escrever um roteiro de abertura de 300 palavras para o Infrastructure Americas Summit, e depois gravar a abertura SEM ler, so com notas. Proxima aula: as regras do jogo &mdash; linguagem regulatoria e reported speech, em leitura.',
    },
    'pc': {
        'title': 'The Art of the Opening -- The Sentence That Makes the Room Sit Up',
        'desc': 'Doors open in twenty minutes. You have four minutes on stage, three hundred people and no script.',
        'match_idx': [0, 2, 5, 8, 10, 13],
        'context': [
            'Speakers who open conferences for a living use one structure that most people only ever meet in writing. It is called <strong>inversion</strong>, and it works like a spotlight: it takes a limiting word, puts it at the front of the sentence, and forces the room to wait for the rest.',
            'Compare &ldquo;Capital has not been this cautious since 2008&rdquo; with &ldquo;<strong>Not since</strong> 2008 <strong>has</strong> capital been this cautious.&rdquo; The facts are the same. The second version marks <strong>an inflection point</strong>. Notice what happens after the limiting phrase: the <strong>auxiliary</strong> comes before the subject, exactly as in a question. &ldquo;<strong>Rarely do</strong> we see every stakeholder at the same table.&rdquo; &ldquo;<strong>Only by</strong> fixing the contracts <strong>can</strong> we move the money.&rdquo;',
            'If the verb has no auxiliary, English lends it one: <strong>do</strong>, <strong>does</strong> or <strong>did</strong>. &ldquo;Not only <strong>did</strong> the auction close, but it closed early.&rdquo; Forgetting the auxiliary is the most common mistake: &ldquo;Rarely we see&rdquo; sounds like a sentence that stopped halfway.',
            'The last rule is about taste, not grammar. One inversion <strong>sets the tone</strong>. Two in a row sound like a sermon. Use it once, in the sentence you want remembered, pause after it, and move on to <strong>a show of hands</strong>, the <strong>rhetorical pivot</strong> or the moment you <strong>hand over to</strong> the first panelist.',
        ],
        'context_quiz': [
            ('According to the text, what does an inversion do?', ['It makes a sentence more polite.', 'It puts a limiting word first and makes the room wait for the rest.', 'It turns a statement into a question.'], 1),
            ('What comes before the subject after a limiting phrase?', ['The auxiliary, as in a question.', 'The main verb.', 'Nothing changes.'], 0),
            ('What does the text say about using inversion?', ['Use it in every sentence of an opening.', 'Never use it in speech.', 'Use it once, in the sentence you want remembered.'], 2),
        ],
        'tip_title': 'Inversion for Emphasis',
        'tip_lead': 'Limiting word first, then the auxiliary, then the subject -- and only once per opening.',
        'tip_rows': [
            ('A long gap in time', 'Not since + time + auxiliary + subject', 'Not since 2008 <strong>has capital been</strong> this cautious.'),
            ('One condition', 'Only by + -ing + auxiliary + subject', 'Only by working together <strong>can we</strong> close the gap.'),
            ('How unusual', 'Rarely / Seldom + do + subject + verb', 'Rarely <strong>do we see</strong> every stakeholder together.'),
            ('A first time', 'Never before + have + subject + participle', 'Never before <strong>have so many funds</strong> asked.'),
            ('Two facts at once', 'Not only + did + subject + verb, but', 'Not only <strong>did the auction close</strong>, but it closed early.'),
            ('Taste', 'one per opening, then pause', 'Two in a row sound like a sermon.'),
        ],
        'tip_never': 'rarely we see &middot; not since 2008 capital has been &middot; only by working together we can &middot; I will pass the word to the minister',
        'blanks': [
            ('Not since 2008 ', 'has', ' infrastructure capital been this cautious.', 'Hint: the auxiliary comes before the subject -- one word', None),
            ('Rarely ', 'do', ' we see every stakeholder at the same table.', 'Hint: English lends the verb an auxiliary -- one word', None),
            ('Only by fixing the contracts ', 'can we', ' move the money that has been waiting.', 'Hint: auxiliary, then subject -- two words', None),
            ('A quick ', 'show of hands', ': who here has invested in Brazil before?', 'Hint: the audience raises them -- three words', None),
            ('One ', 'housekeeping note', ': the session ends at eleven sharp.', 'Hint: practical information for the audience -- two words', None),
            ('With that, let me ', 'hand over to', ' our first panelist.', 'Hint: give the stage away -- three words', None),
        ],
        'order_title': 'Put the Opening in Order',
        'order_lead': 'You have four minutes. Put the moves of your opening in a logical order.',
        'order': [
            'Rather than read you the agenda, let me ask for a quick show of hands.',
            'Who here has waited more than a year for a regulator to publish a date?',
            'Rarely do we have the people who waited and the people who regulate in the same room.',
            'But optimism is not the whole story: only by fixing the contracts can we move the money.',
            'One housekeeping note: we finish at eleven sharp.',
            'With that, let me hand over to our first panelist.',
        ],
        'quiz': [
            ('You want the key sentence of your opening to stand out. You say:', ['Rarely we have every stakeholder in one room.', 'Rarely do we have every stakeholder in one room.', 'Rarely have we every stakeholder in one room.'], 1),
            ('You want the audience to answer a question without speaking. You say:', ['A quick show of hands: who has invested in Brazil before?', 'Please raise the hands if invested.', 'Everybody vote now with the hand.'], 0),
            ('You want to give the stage to the first panelist. You say:', ['Now I pass the word to our first panelist.', 'Now our first panelist has the word.', 'With that, let me hand over to our first panelist.'], 2),
            ('You want to invite questions from the audience. You say:', ['Now I will open the floor for questions.', 'Now the floor is opened by me.', 'Now you can make questions.'], 0),
        ],
        'think': 'You are opening the Infrastructure Americas Summit in New York tomorrow. The theme is &ldquo;Capital, Concessions and the Road to 2030.&rdquo; Record your first sixty seconds: no name, no agenda, one idea, one inversion, one show of hands and a handover.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Nancy Duarte &mdash; &ldquo;The secret structure of great talks&rdquo; (TED)',
         'desc': 'A presentation designer shows the shape that great speeches share: the constant movement between what is and what could be. It is the rhetorical pivot, drawn as a map.',
         'tip': 'Tip: after watching, draw the shape of your last opening. Where was your pivot?',
         'url': 'https://www.ted.com/talks/nancy_duarte_the_secret_structure_of_great_talks', 'cta': 'Watch on TED'},
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;If Everyone Hates Meetings, Why Do We Have So Many of Them?&rdquo;',
         'desc': 'Why so many meetings fail, and what the good ones do differently in the first minutes. Everything that applies to a meeting applies twice to a panel.',
         'tip': 'Tip: listen for one idea you could use in the first two minutes of your next panel.',
         'url': 'https://freakonomics.com/podcast/if-everyone-hates-meetings-why-do-we-have-so-many-of-them/', 'cta': 'Listen on Freakonomics'},
        {'id': 'video', 'type': 'Talk', 'title': 'Chris Anderson &mdash; &ldquo;TED&rsquo;s secret to great public speaking&rdquo; (TED)',
         'desc': 'The head of TED on the one thing every great talk has in common: a single idea, built carefully in the audience&rsquo;s mind. Seven minutes, and a perfect model of a clean opening.',
         'tip': 'Tip: listen to his first thirty seconds twice. Note what he does not say.',
         'url': 'https://www.ted.com/talks/chris_anderson_ted_s_secret_to_great_public_speaking', 'cta': 'Watch on TED'},
    ],
}
