# -*- coding: utf-8 -*-
# Aula 2 -- The Language of Capital (modelo LEITURA: texto central + gist + true/false)
U = 'https://images.unsplash.com/'

L = {
    'model': 'reading',
    'title_html': "The Language of <span class='accent'>Capital</span>",
    'hero_line': 'Risk, returns and the words a sovereign fund uses before it says yes',
    'menu_desc': 'Reading an investor briefing, and the causative that tells you who made it happen -- 35 slides',
    'grammar_point': 'causative have and get versus the passive in investment language',
    'phases': ['Money Talks', 'Words of Capital', 'The Briefing', 'The Code', 'Same Deal, Other Words', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'claire', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1554224155-6726b3ff858f?w=1400&q=80',
        'ch2': U + 'photo-1560179707-f14e90ef3623?w=1400&q=80',
        'ch3': U + 'photo-1504384308090-c894fdcc538d?w=1400&q=80',
        'ch_grammar': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch5': U + 'photo-1552664730-d307ca884978?w=1400&q=80',
        'ch_rp': U + 'photo-1507679799987-c73779587ccf?w=1400&q=80',
        'pc': U + 'photo-1554224155-6726b3ff858f?w=600&q=80',
    },
    'warmup': {
        'heading': "The Last Investor Who <span class='accent'>Asked You Something Hard</span>",
        'sub': 'Where was the investor from, what did they ask, and which word did you reach for and not find? Use two words from last lesson: the pipeline, a concession, to unpack, to move the needle.',
    },
    'target': {
        'heading': "Read Like the <span class='accent'>Fund Reads</span>",
        'steps': [
            'Find the money: who puts it in, who gets paid first, and who waits.',
            'Find the protection: what makes the risk small enough for a pension fund to sign.',
            'Find the agent: who made each thing happen, and who the sentence is hiding.',
        ],
    },
    'diagnostic': {
        'heading': "Why Is Pension Money <span class='accent'>Still Waiting?</span>",
        'p1': 'A sovereign wealth fund manager asks you: &ldquo;Your region has the projects. Why are the pension funds still on the sidelines?&rdquo;',
        'p2': 'Answer in three sentences. Then say which financial word you wanted and did not use.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>Capital</span>",
            'sub': 'Fourteen terms that decide whether a fund says yes'},
    'vocab': [
        {'word': 'A risk-adjusted return', 'def': 'The profit an investment makes, measured against how much risk it carries', 'ex': 'On a risk-adjusted return, the brownfield road beats the new port.', 'icon': 'chart'},
        {'word': 'A leverage ratio', 'def': 'How much of a project is paid for with debt compared with equity', 'ex': 'A leverage ratio of seventy to thirty is normal for a transmission line.', 'icon': 'scale'},
        {'word': 'Subordinated debt', 'def': 'A loan that is repaid only after the main lenders have been paid', 'ex': 'Subordinated debt pays more because it waits in line.', 'icon': 'layers'},
        {'word': 'An equity stake', 'def': 'The share of a company that an investor owns', 'ex': 'The fund took a twenty-five percent equity stake in the operator.', 'icon': 'key'},
        {'word': 'Blended finance', 'def': 'Mixing public or philanthropic money with private money so that a project becomes investable', 'ex': 'Blended finance made the water project possible.', 'icon': 'link'},
        {'word': 'A de-risking mechanism', 'def': 'Any tool, such as a guarantee or insurance, that reduces the risk an investor carries', 'ex': 'The currency guarantee was the de-risking mechanism the fund needed.', 'icon': 'shield'},
        {'word': 'An off-take agreement', 'def': 'A long contract in which a buyer agrees in advance to purchase what a project will produce', 'ex': 'The solar farm signed a twenty-year off-take agreement before construction started.', 'icon': 'doc'},
        {'word': 'Credit enhancement', 'def': 'Support, such as a guarantee, that makes a loan look safer to lenders', 'ex': 'The development bank guarantee worked as credit enhancement for the bond.', 'icon': 'star'},
        {'word': 'Concessional lending', 'def': 'Loans offered on better terms than the market, usually by development banks', 'ex': 'Concessional lending covered the first ten years of the project.', 'icon': 'hand'},
        {'word': 'Yield compression', 'def': 'The fall in returns that happens when too many investors want the same kind of asset', 'ex': 'Yield compression has made brownfield toll roads expensive.', 'icon': 'filter'},
        {'word': 'Fiduciary duty', 'def': 'The legal obligation to act in the best interest of the people whose money you manage', 'ex': 'Her fiduciary duty is to the teachers who will retire on this fund.', 'icon': 'lock'},
        {'word': 'Capital deployment', 'def': 'The process of actually investing the money a fund has raised', 'ex': 'Capital deployment in Latin America was slower than the fund promised.', 'icon': 'zap'},
        {'word': 'A currency hedge', 'def': 'A contract that protects an investor from losses when exchange rates move', 'ex': 'Without a currency hedge, a strong dollar can erase the whole return.', 'icon': 'refresh'},
        {'word': 'An anchor investor', 'def': 'The first large investor whose commitment convinces others to join', 'ex': 'Once the pension fund signed as anchor investor, three more funds followed.', 'icon': 'anchor'},
    ],
    'pron_heading': "Where the Stress <span class='accent'>Falls</span>",
    'pron': ['Subordinated debt', 'Concessional lending', 'Fiduciary duty', 'What a pension fund needs is a risk-adjusted return, not the highest number on the page.'],
    'ch3': {'heading': "The Briefing on <span class='accent'>Your Desk</span>", 'sub': 'Read it once for the argument. The detail comes after.'},
    'reading': {
        'heading': "Why Pension Money <span class='accent'>Waits</span>",
        'rtitle': 'Why Pension Money Waits',
        'paras': [
            'Every year the same number appears in conference slides: the region needs hundreds of billions of dollars of infrastructure, and the world&rsquo;s pension and sovereign wealth funds are sitting on trillions. The obvious question is why the two do not meet. The answer is rarely the projects. It is the shape of the risk, and the language investors use to describe it.',
            'A pension fund does not chase the highest return. It has a fiduciary duty to the people who will retire on its money, so it looks for a risk-adjusted return that it can defend to its board. A greenfield port in a new market may promise fifteen percent, but if construction, currency and politics can each destroy that number, the fund will choose a brownfield road that pays nine percent from day one. That preference has a side effect: so many funds now want the same safe assets that yield compression has pushed returns down.',
            'This is where structure matters. A sponsor who wants a fund on board rarely changes the project; it changes the capital around it. Developers now have their financial models audited before the first meeting, and many get a development bank to provide credit enhancement, so that the senior loan looks safer. Concessional lending can carry the riskiest early years, and subordinated debt can sit between the bank and the equity. When public and private money are combined on purpose in this way, the result is called blended finance.',
            'The last piece is the one foreign investors ask about first. A toll road earns reais, but a Canadian pension fund reports in dollars. Without a currency hedge, a bad year for the exchange rate can wipe out a good year on the road. Funds are not waiting for better projects. They are waiting for somebody to take the currency and the construction risk off the table &mdash; and for the first anchor investor to go in, so that the rest can follow.',
        ],
        'source': 'Written for this lesson, from the standard arguments of infrastructure investment briefings.',
    },
    'gist': {
        'prompt': 'What is the main argument of the briefing?',
        'choices': [
            ['a', 'The region does not have enough good infrastructure projects to attract pension funds.', False],
            ['b', 'Funds invest when the risk is structured and protected, not simply when the promised return is high.', True],
            ['c', 'Pension funds should accept higher risk in order to earn fifteen percent.', False],
        ],
    },
    'tf': [
        ['According to the text, the main obstacle is a shortage of projects.', 'f', 'The text says the answer is rarely the projects; it is the shape of the risk.'],
        ['A pension fund may prefer a lower return that starts immediately to a higher return with several risks.', 't', 'The text compares a fifteen percent greenfield port with a nine percent brownfield road that pays from day one.'],
        ['Sponsors usually redesign the project itself to attract a fund.', 'f', 'The text says a sponsor rarely changes the project; it changes the capital around it.'],
        ['A guarantee from a development bank can make the senior loan look safer.', 't', 'The text says developers get a development bank to provide credit enhancement so that the senior loan looks safer.'],
        ['Foreign funds are mainly worried about the quality of the roads.', 'f', 'The text says the first question is currency: the road earns reais, but the fund reports in dollars.'],
    ],
    'artifact': {
        'heading': "The Term Sheet the Fund <span class='accent'>Received</span>",
        'title': 'TERM SHEET SUMMARY', 'subtitle': 'Northeast Solar Cluster &middot; prepared for investor roundtable',
        'rows': [
            ('Equity offered', '25% equity stake to one anchor investor', True),
            ('Leverage ratio', '70% debt / 30% equity', False),
            ('Debt structure', 'Senior loan (development bank) + subordinated debt tranche', False),
            ('Revenue', '20-year off-take agreement with a regional distributor', True),
            ('Protection', 'Partial guarantee as credit enhancement; currency hedge required for USD investors', False),
        ],
        'note': 'Note to participants: the sponsor had the financial model audited by an independent firm in June. Target risk-adjusted return and hedge costs will be discussed at the roundtable, not in writing.',
        'qs': [
            ('What is the sponsor offering, and to whom?', 'A twenty-five percent equity stake, to one anchor investor.'),
            ('How is the revenue secured, and for how long?', 'By an off-take agreement with a regional distributor, for twenty years.'),
            ('What did the sponsor have done in June, and what will not be put in writing?', 'It had the financial model audited by an independent firm. The target return and the hedge costs will only be discussed at the roundtable.'),
        ],
    },
    'ch_grammar': {'heading': "Who Made It <span class='accent'>Happen?</span>",
                   'sub': 'The difference between a sentence that names the agent and one that hides it'},
    'grammar': {
        'heading': "Three Sentences Name the Agent. <span class='accent'>One Hides It.</span>",
        'examples': [
            "The fund <span style='color:#b91c1c;font-weight:700'>had</span> its exposure <span style='color:#b91c1c;font-weight:700'>reviewed</span> by an outside adviser.",
            "The operator <span style='color:#b91c1c;font-weight:700'>got</span> the concession <span style='color:#b91c1c;font-weight:700'>extended</span> for ten years.",
            "The concession <span style='color:#1d4ed8;font-weight:700'>was extended</span> for ten years.",
            "We <span style='color:#b91c1c;font-weight:700'>had</span> the project <span style='color:#b91c1c;font-weight:700'>structured</span> as blended finance.",
        ],
        'prompt': 'The red sentences tell you who caused the action, even when somebody else did the work. The blue one does not. Why would an investor reading the blue sentence want to ask a question?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('You arranged a service', 'have + object + past participle', 'We <strong>had the model audited</strong>.'),
            ('You pushed to make it happen', 'get + object + past participle', 'They <strong>got the tariff approved</strong>.'),
            ('Name the expert who did the work', '... + by + agent', 'We had the project structured <strong>by a local bank</strong>.'),
            ('Stay silent about the agent', 'be + past participle', 'The tariff <strong>was approved</strong> in May.'),
            ('Something happened to you', 'have + object + past participle', 'The fund <strong>had its rating downgraded</strong>.'),
            ('Ask or persuade a person', 'have + person + verb / get + person + to + verb', 'We <strong>had the bank run</strong> the numbers. We <strong>got the ministry to publish</strong> the date.'),
            ('The trap', 'never <em>make + object + to be</em>', 'Not <em>We made the contract to be reviewed</em>. Say <strong>We had the contract reviewed</strong>.'),
        ],
        'oneliner': 'Have and get tell the room who made it happen; the passive lets you stay silent about it.',
    },
    'grammar_practice': {
        'heading': "Name the Agent, or <span class='accent'>Hide It</span>",
        'items': [
            ('Before the roadshow, we ', 'had the model audited', ' by an independent firm. (you arranged a service)'),
            ('After months of meetings, the operator finally ', 'got the tariff approved', '. (it pushed to make it happen)'),
            ('The concession ', 'was extended', ' in May, and nobody said who asked for it. (hide the agent)'),
            ('Last year the fund ', 'had its rating downgraded', ', and the board was not happy. (something happened to it)'),
            ('We ', 'had the bank run', ' the numbers again before the committee. (a person does it, base verb)'),
            ('It took a year, but we ', 'got the ministry to publish', ' the auction date. (persuade a person, to + verb)'),
        ],
    },
    'detective': [
        ('We made the contract to be reviewed by our lawyers.', 'We <strong>had the contract reviewed</strong> by our lawyers.'),
        ('The fund had reviewed its exposure by an adviser.', 'The fund <strong>had its exposure reviewed</strong> by an adviser.'),
        ('We got the ministry publish the date.', 'We got the ministry <strong>to publish</strong> the date.'),
        ('Investors want a return adjusted to the risk.', 'Investors want a <strong>risk-adjusted return</strong>.'),
    ],
    'ch5': {'heading': "Same Deal, <span class='accent'>Other Words</span>", 'sub': 'Equivalence &middot; Gap &middot; Quick fire &middot; Two recordings'},
    'equiv_heading': "The Term Sheet in <span class='accent'>Plain English</span>",
    'equiv': {
        'title': 'Match each line of the term sheet to the same idea in plain English',
        'hint': 'Tap a line from the term sheet, then tap the sentence that means the same',
        'pairs': [
            ('The fund will take a 25 percent equity stake.', 'The fund will own a quarter of the company.'),
            ('The subordinated debt is repaid after the senior loan.', 'This lender only gets its money back once the main bank has been paid.'),
            ('A partial guarantee provides credit enhancement.', 'A development bank promises to cover part of the losses, so the loan looks safer.'),
            ('Revenue is secured by a twenty-year off-take agreement.', 'A buyer has already agreed to purchase the output for two decades.'),
            ('Yield compression has reduced returns on brownfield assets.', 'So many investors want these assets that the profit on them has fallen.'),
        ],
    },
    'gap_heading': "Complete the <span class='accent'>Briefing Note</span>",
    'gap': {
        'parts': [
            'A pension fund cannot simply chase the highest number, because it has a ', ['1', 'fiduciary duty'],
            ' to its members. So when a sponsor offers it an ', ['2', 'equity stake'],
            ' in a solar cluster, the first question is how much debt sits above that money. A ', ['3', 'leverage ratio'],
            ' of seventy to thirty is normal when a twenty-year ', ['4', 'off-take agreement'],
            ' has already sold the power. The ', ['5', 'subordinated debt'],
            ' is paid after the senior loan, so it earns more and carries more risk. A guarantee from a development bank works as ', ['6', 'credit enhancement'],
            ', and when public and private money are combined on purpose, the structure is called ', ['7', 'blended finance'],
            '. None of it matters if the fund has already finished its ', ['8', 'capital deployment'], ' for the year.',
        ],
        'bank': ['fiduciary duty', 'equity stake', 'leverage ratio', 'off-take agreement', 'subordinated debt', 'credit enhancement', 'blended finance', 'capital deployment'],
    },
    'quickfire': [
        {'situation': 'A Canadian fund manager asks why a nine percent road can beat a fifteen percent port. Answer in two sentences.', 'tips': ['What matters is the risk-adjusted return: the road pays from day one, and the port can lose that fifteen percent to construction and currency.', 'Frame it with What matters is, and land on risk-adjusted return.']},
        {'situation': 'Say that your team arranged an independent audit of the model before the roadshow.', 'tips': ['We had the financial model audited by an independent firm before the roadshow.', 'have + object + past participle, never made the model to be audited.']},
        {'situation': 'An investor asks who got the tariff approved. Say it was the operator, after a long negotiation.', 'tips': ['The operator got the tariff approved after nine months of negotiation.', 'get + object + past participle shows effort.']},
        {'situation': 'Explain blended finance to a CFO who has never heard the term, in one sentence and without jargon.', 'tips': ['It means mixing public money that accepts more risk with private money that accepts less, so that the project becomes investable.', 'Define it without using the word finance twice.']},
        {'situation': 'A fund in Abu Dhabi asks what protects it if the real falls against the dollar.', 'tips': ['The term sheet requires a currency hedge, so a bad year for the exchange rate does not erase the return.', 'Name the tool, then say what it prevents.']},
        {'situation': 'Say why the second and third funds are waiting for the pension fund to sign.', 'tips': ['They are waiting for an anchor investor. Once one serious fund goes in, the others follow.', 'Anchor investor, stress on AN-chor.']},
    ],
    'listenings': [
        {'label': 'Listening 1 &middot; Business Radio', 'title': "The Price of <span class='accent'>Safety</span>",
         'blurb': 'A markets segment on brownfield assets in Latin America. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'Five years ago a brownfield toll road in Latin America could offer an investor a double-digit return. Today the same asset struggles to promise nine percent, and the reason is not the traffic. It is demand. Pension funds and sovereign wealth funds have decided that operating assets, the ones that already earn money, are the safest way into the region, and so many of them are bidding for the same concessions that prices have gone up and returns have come down. Analysts call it yield compression. The result is a strange market. The safe assets are now expensive, and the greenfield projects that the region actually needs are still short of money. Several development banks are trying to close that gap with guarantees, so that a new project looks more like an old one to a cautious fund.',
         'qs': [
             ('What return could a brownfield toll road offer five years ago, and what can it promise today?', 'A double-digit return five years ago; today it struggles to promise nine percent.'),
             ('According to the segment, why have returns come down?', 'Because so many pension and sovereign wealth funds are bidding for the same operating assets that prices went up. It is yield compression, not traffic.'),
             ('What are development banks doing to close the gap?', 'Offering guarantees, so that a new greenfield project looks more like an old one to a cautious fund.'),
         ]},
        {'label': 'Listening 2 &middot; The Roundtable', 'title': "What the Fund <span class='accent'>Needs to Hear</span>",
         'blurb': 'A sovereign fund investment director speaks at a roundtable. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Let me be direct about how we look at your region. We do not start with the return. We start with what can go wrong, and in what order. Construction risk is the first thing we want somebody else to carry, which is why we like projects where a development bank has taken the early years. Currency is the second. Our investors are paid in dirhams and dollars, so if a deal does not come with a credible currency hedge, it does not reach our committee. The third is the contract itself. We have had concessions renegotiated in other markets after an election, and my board has a long memory. None of this means we will not come. It means the first deal has to be structured so carefully that we can defend it, and after that, capital deployment becomes much easier.',
         'qs': [
             ('What does the director say her fund starts with, if not the return?', 'With what can go wrong, and in what order.'),
             ('What are the three risks she lists, in order?', 'Construction risk first, then currency, then the contract itself.'),
             ('What has happened to her fund in other markets, and what does she say about the first deal?', 'It has had concessions renegotiated after an election. The first deal has to be structured carefully enough to defend; after that, capital deployment becomes much easier.'),
         ]},
    ],
    'roleplays': {
        'heading': "In Front of <span class='accent'>the Fund</span>",
        'items': [
            {'heading': "Brief the Fund in <span class='accent'>Two Minutes</span>",
             'scenario': 'A sovereign wealth fund manager has the term sheet in front of her and two minutes before her next meeting. Walk her through what is offered, how the revenue is secured and what protects her money.',
             'chips': ['an equity stake', 'subordinated debt', 'an off-take agreement', 'we had ... audited']},
            {'heading': "Blended Finance, <span class='accent'>No Jargon</span>",
             'scenario': 'A CFO from a construction group has never worked with development banks. Explain what blended finance is, why concessional lending comes first, and why that brings private money in behind it.',
             'chips': ['blended finance', 'concessional lending', 'credit enhancement', 'What it does is']},
            {'heading': "Ninety Seconds on <span class='accent'>Why Money Waits</span>",
             'scenario': 'Open a roundtable session. Say why pension money is still waiting for Latin American infrastructure and what would unlock the first deal.',
             'footer': 'No notes, ninety seconds. Use at least one causative and three words from today.'},
        ],
    },
    'survival_heading': "Five Sentences for the <span class='accent'>Investor Table</span>",
    'survival': [
        'What a pension fund needs is a risk-adjusted return, not the highest number on the page.',
        'We had the financial model audited by an independent firm before the roadshow.',
        'The operator got the tariff approved, and that changed the risk profile overnight.',
        'Without a currency hedge, a bad year for the exchange rate can erase a good year on the road.',
        'The other funds are waiting for an anchor investor to go in first.',
    ],
    'checklist': [
        'I can explain why a lower return can be the better investment, using risk-adjusted return.',
        'I use have and get with a past participle to say who made something happen.',
        'I know when the passive hides the agent, and I can ask who did it.',
        'I can explain blended finance to a CFO in one sentence, without jargon.',
        'I know the words: a risk-adjusted return, a leverage ratio, subordinated debt, an equity stake, blended finance, a de-risking mechanism, an off-take agreement, credit enhancement, concessional lending, yield compression, fiduciary duty, capital deployment, a currency hedge, an anchor investor.',
    ],
    'badge': {'name': 'The Language of Capital', 'line': 'Who puts the money in, who gets paid first, and who made it happen.',
              'next': 'Next lesson: The Art of the Opening -- commanding the room without a script, in speech'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Va direto: \'Guilherme, today we read the way a fund reads.\' O recorte da aula 2 e o gap que ele mesmo nomeou: \'quando eu estou com um cliente, falando de assuntos financeiros, o meu vocabulario e um pouco falho\'. A aula e de LEITURA (aula par, REGRA 29.2), mas com ele toda leitura vira conversa: pergunte, a cada bloco, se aquilo aparece nas mesas do GRI e como ele diria.',
        'warmup': '<strong>Warm-up com callback (5 min):</strong> Callback da aula 1: ele precisa usar duas palavras da aula passada (the pipeline, a concession, to unpack, to move the needle). ANOTE se ele reusa espontaneamente ou precisa olhar a tela. Depois pergunte qual palavra de financas ele queria e nao encontrou &mdash; ela provavelmente esta nos cards de hoje. Zero correcao aqui.',
        'target': '<strong>Enquadramento (2 min):</strong> Os tres movimentos sao a leitura de um comite de investimento: o dinheiro, a protecao, o agente. Pergunte qual deles ele observa primeiro quando le um term sheet de verdade.',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Resposta livre em tres frases. ANOTE as palavras que ele usou e as que contornou (\'aquele tipo de divida que recebe depois\' = subordinated debt). Essa lista e o que voce confere no fim da aula.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fourteen terms. You know most of them in Portuguese; let us see how many you own in English.\' Zero portugues na tela.',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> Leia a pista, ele arrisca, revele. CCQ \'risk-adjusted return\': \'Is fifteen percent always better than nine? (Nao, depende do risco.)\' CCQ \'subordinated debt\': \'Who gets paid first, this lender or the bank? (O banco.)\' CCQ \'leverage ratio\': \'Seventy to thirty &mdash; seventy is debt or equity? (Divida.)\' Para cada um, peca um exemplo de projeto real que ele conhece.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'an off-take agreement\': \'Is the buyer found before or after the plant is built? (Antes.)\' CCQ \'concessional lending\': \'Better or worse than market terms? (Melhores.)\' CCQ \'yield compression\': \'More investors wanting an asset &mdash; do returns go up or down? (Descem.)\' Diferenca que costuma confundir: credit enhancement protege o EMPRESTIMO; de-risking mechanism e qualquer ferramenta de reduzir risco.',
        'vocab3': '<strong>Vocab reveal 11-14 (4 min):</strong> CCQ \'fiduciary duty\': \'To whom is the pension fund responsible? (Aos participantes, nao a si mesmo.)\' CCQ \'an anchor investor\': \'First or last to sign? (Primeiro.)\' Peca que ele explique \'a currency hedge\' como explicaria a um CFO asiatico: e o risco numero um que os investidores estrangeiros citam.',
        'pron': '<strong>Pronuncia e inteligibilidade (4 min):</strong> sub-OR-di-nated (acento na segunda), con-CES-sion-al, fi-DU-ci-a-ry (o portugues tende a \'fiduCIAry\'). Na frase longa, ele marca as palavras que carregam sentido (needs, risk-adjusted, highest) e deixa o resto leve. Callback da aula 1: a frase comeca com \'What\' e a palavra-chave vem no fim.',
        'matching': '<strong>Matching (4 min):</strong> Ele fecha os pares em voz alta antes de clicar. Se fechar rapido, peca a diferenca entre dois pares proximos (credit enhancement x de-risking mechanism). Toggle: clicar de novo fecha.',
        'ch3': '<strong>Transicao leitura (1 min):</strong> Diga: \'A briefing on your desk. Read it once for the argument.\' A leitura vem antes da gramatica de proposito: o causativo aparece no texto (\'have their financial models audited\', \'get a development bank to provide\') antes de alguem apontar.',
        'reading': '<strong>Leitura (7 min):</strong> Primeira passada em silencio, SEM parar para vocabulario. Ele le todo dia, entao pode ler em ritmo real: 3 minutos. Depois peca UMA frase de resumo e pergunte se ele concorda com o argumento &mdash; ele conhece esse mercado melhor do que o texto. Deixe a discordancia virar conversa: e o formato que ele pediu.',
        'gist': '<strong>Gist (3 min):</strong> Ele escolhe e JUSTIFICA: \'Why not a? Why not c?\'. A justificativa oral e o exercicio.',
        'tf': '<strong>True or False (6 min):</strong> Ele diz TRUE ou FALSE e LE EM VOZ ALTA a linha do texto que prova. Repare que as afirmacoes parafraseiam o texto: e exatamente como um investidor resume o que voce disse.',
        'artifact': '<strong>Artefato (4 min):</strong> Um term sheet ficticio de um cluster solar. Peca que ele LEIA cada linha e a transforme em frase de apresentacao para um fundo: \'What we are offering is a twenty-five percent equity stake to one anchor investor.\' So depois as perguntas. A nota final tem um causativo (\'had the financial model audited\'): aponte.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Four sentences about the same kind of deal. Three of them name the agent.\' Passe ao proximo.',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Pergunte: \'Who did the work in the first sentence? And who made it happen?\' Ele deve perceber que o adviser fez o trabalho, mas o fundo causou a acao. Depois: \'In the blue sentence, who extended the concession?\' (Ninguem sabe.) So entao Reveal the Rule. CCQ: \'The operator got the tariff approved &mdash; did the operator approve it? (Nao, conseguiu que aprovassem.)\' CCQ: \'had its rating downgraded &mdash; did the fund want that? (Nao, aconteceu com ele.)\' Obstaculo do brasileiro avancado: \'We made the contract to be reviewed\' (calco de \'fizemos o contrato ser revisado\'). Pragmatica: num comunicado regulatorio, a passiva esconde QUEM decidiu &mdash; o investidor sempre pergunta.',
        'grammar_practice': '<strong>Practice (4 min):</strong> Frase inteira antes de clicar. Nas duas ultimas, cobre a diferenca: have + pessoa + verbo sem \'to\'; get + pessoa + \'to\' + verbo. Se fechar rapido, peca um causativo sobre algo que o GRI realmente fez este ano.',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige ANTES de clicar e explica. Os tres primeiros sao os erros de causativo do brasileiro avancado; o quarto e ordem de palavras (\'return adjusted to the risk\'). Correcao direta: ele pediu feedback especifico.',
        'ch5': '<strong>Transicao (1 min):</strong> Diga: \'Same deal, other words: the term sheet in plain English, the briefing note, one question at a time, and two recordings.\' Passe ao proximo.',
        'equiv': '<strong>Equivalencia (5 min):</strong> Ele fecha o par e EXPLICA por que dizem o mesmo. Esse e o trabalho dele como moderador: traduzir o jargao do term sheet para quem nao e de financas. Se fechar rapido, peca uma terceira versao, para um ministro.',
        'gap': '<strong>Gap-fill (5 min):</strong> Palavras no banco embaixo, embaralhadas. Com o gap-fill interativo ele pode arrastar, tocar ou digitar, e o Check confere. Peca que ele leia o paragrafo completo em voz alta no fim, com a entonacao descendo nas palavras do banco.',
        'quickfire': '<strong>Quick fire (6 min):</strong> Uma situacao por vez, em velocidade normal. Ele responde ANTES de ver as dicas. Na quarta (blended finance sem jargao) cobre clareza: se precisou de mais de uma frase, peca de novo. Correcao em bloco no fim.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar. Segmento de radio sobre yield compression. Toque duas vezes. Depois pergunte se ele ve isso acontecendo nas concessoes brasileiras &mdash; ele tem opiniao informada, deixe falar.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Contexto diferente: uma diretora de fundo soberano numa mesa redonda, voz feminina, registro direto. E exatamente o tipo de interlocutor dele. Depois das perguntas: \'If she said this at your roundtable, what would you ask her next?\'',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'Now you are in front of the fund. Three times, and the last one has no help.\' Passe ao proximo.',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a gestora do fundo soberano, sem pressa de ser simpatica. Cronometre dois minutos. Ele usa o term sheet do slide do artefato. Corrija em bloco no fim: um ponto de vocabulario, um de estrutura, um de acento.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o CFO de uma construtora, sem nenhuma familiaridade com banco de desenvolvimento. Interrompa com \'Sorry, what does concessional mean?\'. Ele precisa explicar sem jargao. Avalie se a explicacao ficou mais curta que a pergunta.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Noventa segundos, sem nota, sem interrupcao. No fim, dois numeros: quantas palavras de hoje ele usou, e se houve pelo menos um causativo. Depois, UMA observacao de acento.',
        'survival': '<strong>Survival card (3 min):</strong> Leia cada frase e toque o audio. Ele repete marcando a palavra-chave. Peca que escolha UMA para usar numa conversa real com investidor ate a proxima aula.',
        'checklist': '<strong>Checklist (2 min):</strong> Diga: \'Click each item if you feel confident.\' Todos os 5 = aula concluida e stamp 2. Item que ele hesitar entra no warm-up da aula 3.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Today you read like a fund. Next time you open the room.\' Homework (ORALMENTE, nunca escrito na tela): gravar 90 segundos explicando a diferenca entre blended finance e concessional lending para um CFO sem formacao em financas, e trazer a gravacao. Proxima aula: a arte da abertura &mdash; inversao retorica e como comandar a sala sem roteiro, em fala.',
    },
    'pc': {
        'title': 'The Language of Capital -- Who Made It Happen',
        'desc': 'A sovereign fund reads your term sheet. Every sentence either names the agent or hides it, and the fund notices.',
        'match_idx': [0, 2, 3, 6, 9, 12],
        'context': [
            'Read any investor briefing carefully and you will notice two kinds of sentences. The first kind tells you who made something happen. The second kind lets the writer stay silent about it. Investors read both, and they always ask about the second.',
            'The first kind uses the <strong>causative</strong>. When you arrange for an expert to do something, you use <strong>have</strong> + object + past participle: &ldquo;We <strong>had</strong> the financial model <strong>audited</strong>.&rdquo; When you push, negotiate or persuade to make it happen, <strong>get</strong> is more natural: &ldquo;The operator <strong>got</strong> the tariff <strong>approved</strong> after nine months.&rdquo; If you want to name the expert, add <strong>by</strong>: &ldquo;We had the deal structured <strong>by</strong> a local bank as <strong>blended finance</strong>.&rdquo;',
            'The same structure describes something that happens <em>to</em> you: &ldquo;The fund <strong>had</strong> its rating <strong>downgraded</strong>,&rdquo; which no fund wants. And when a person does the work, the verb changes shape: <strong>have</strong> + person + base verb (&ldquo;We had the bank <strong>run</strong> the numbers&rdquo;) but <strong>get</strong> + person + <strong>to</strong> + verb (&ldquo;We got a development bank <strong>to provide</strong> <strong>credit enhancement</strong>&rdquo;).',
            'The second kind is the <strong>passive</strong>: &ldquo;The concession <strong>was extended</strong>.&rdquo; It is correct, and it is useful when the agent does not matter. But in a room full of people with a <strong>fiduciary duty</strong>, the agent usually matters. The sentence that hides who decided is the sentence that gets the question. And one form does not exist at all: &ldquo;We made the contract to be reviewed&rdquo; is Portuguese wearing an English suit.',
        ],
        'context_quiz': [
            ('According to the text, which kind of sentence do investors always ask about?', ['The sentence that names the agent.', 'The sentence that hides who made it happen.', 'The sentence with the most numbers.'], 1),
            ('When is get more natural than have, according to the text?', ['When you push, negotiate or persuade to make something happen.', 'When something bad happens to you.', 'When you want to hide the agent.'], 0),
            ('Which sentence does the text say does not exist in English?', ['We had the bank run the numbers.', 'We got a development bank to provide credit enhancement.', 'We made the contract to be reviewed.'], 2),
        ],
        'tip_title': 'The Causative and the Passive',
        'tip_lead': 'Have and get tell the room who made it happen; the passive lets you stay silent about it.',
        'tip_rows': [
            ('You arranged a service', 'have + object + past participle', 'We <strong>had the model audited</strong>.'),
            ('You pushed to make it happen', 'get + object + past participle', 'They <strong>got the tariff approved</strong>.'),
            ('Name the expert', '... + by + agent', 'We had it structured <strong>by a local bank</strong>.'),
            ('Stay silent about the agent', 'be + past participle', 'The tariff <strong>was approved</strong> in May.'),
            ('A person does it (have)', 'have + person + base verb', 'We <strong>had the bank run</strong> the numbers.'),
            ('A person does it (get)', 'get + person + to + verb', 'We <strong>got the ministry to publish</strong> the date.'),
        ],
        'tip_never': 'we made the contract to be reviewed &middot; the fund had reviewed its exposure by an adviser &middot; we got the ministry publish the date &middot; a return adjusted to the risk',
        'blanks': [
            ('Before the roadshow, we had the financial model ', 'audited', ' by an independent firm.', 'Hint: past participle of the verb for an expert checking the accounts', None),
            ('After nine months, the operator finally got the tariff ', 'approved', '.', 'Hint: past participle -- the regulator said yes', None),
            ('We got a development bank ', 'to provide', ' a partial guarantee.', 'Hint: after get + person, use to + verb -- two words', None),
            ('On a ', 'risk-adjusted return', ', the brownfield road beats the new port.', 'Hint: profit measured against risk -- two words joined by a hyphen, then one more', None),
            ('The lender with ', 'subordinated debt', ' is paid only after the senior bank.', 'Hint: the loan that waits in line -- two words', None),
            ('Without ', 'a currency hedge', ', a strong dollar can erase the whole return.', 'Hint: protection against exchange rates -- three words', None),
        ],
        'order_title': 'Put the Briefing in Order',
        'order_lead': 'A sovereign wealth fund manager has two minutes. Put your briefing in a logical order.',
        'order': [
            'What we are offering is a twenty-five percent equity stake to one anchor investor.',
            'The revenue is secured by a twenty-year off-take agreement.',
            'The debt is seventy percent: a senior loan and a subordinated tranche.',
            'We got a development bank to provide a partial guarantee as credit enhancement.',
            'And we had the financial model audited by an independent firm in June.',
            'The one open point is the cost of the currency hedge, which we would like to discuss with you.',
        ],
        'quiz': [
            ('You want to say your team arranged an independent audit. You say:', ['We made the model to be audited.', 'We had the model audited by an independent firm.', 'We audited the model by an independent firm.'], 1),
            ('A fund asks why you prefer a nine percent brownfield road. You say:', ['Because it pays from day one, so the risk-adjusted return is better.', 'Because nine is a safer number than fifteen.', 'Because greenfield is always illegal for pension funds.'], 0),
            ('You want to say the operator worked hard to get the tariff approved. You say:', ['The operator made approve the tariff.', 'The tariff got approved the operator.', 'The operator got the tariff approved after months of negotiation.'], 2),
            ('A CFO asks what blended finance is. You say:', ['It is finance that is blended.', 'It mixes public money that accepts more risk with private money, so the project becomes investable.', 'It is a loan from a pension fund.'], 1),
        ],
        'think': 'A sovereign wealth fund from Abu Dhabi is attending its first Brazilian infrastructure roundtable. In ninety seconds, explain what would make the fund comfortable investing: what protects its money, who made those protections happen, and what is still open. Use at least two causatives and four words from today.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Mariana Mazzucato &mdash; &ldquo;What is economic value, and who creates it?&rdquo; (TED)',
         'desc': 'An economist on how public and private money actually create value together &mdash; the argument underneath every blended finance deal and every conversation about who should carry the risk.',
         'tip': 'Tip: turn on English subtitles and note three phrases she uses to describe risk and reward. Use one at your next roundtable.',
         'url': 'https://www.ted.com/talks/mariana_mazzucato_what_is_economic_value_and_who_creates_it', 'cta': 'Watch on TED'},
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;Are E.S.G. Investors Actually Helping the Environment?&rdquo;',
         'desc': 'How large funds decide where capital goes, and why labels and returns do not always point the same way. The vocabulary of fund managers, spoken at natural speed.',
         'tip': 'Tip: listen once, then open the transcript on the same page and underline every causative or passive you find.',
         'url': 'https://freakonomics.com/podcast/are-e-s-g-investors-actually-helping-the-environment/', 'cta': 'Listen on Freakonomics'},
        {'id': 'video', 'type': 'Talk', 'title': 'Ray Dalio &mdash; &ldquo;How to build a company where the best ideas win&rdquo; (TED)',
         'desc': 'The founder of one of the largest investment firms on how decisions get made when money is on the line &mdash; a close look at how investors think before they say yes.',
         'tip': 'Tip: listen for how he explains a complex idea in plain English. Borrow one move for your next briefing.',
         'url': 'https://www.ted.com/talks/ray_dalio_how_to_build_a_company_where_the_best_ideas_win', 'cta': 'Watch on TED'},
    ],
}
