# -*- coding: utf-8 -*-
# Aula 5 -- Holding the Room (modelo FALA: dialogo line-by-line + 3 role-plays)
U = 'https://images.unsplash.com/'

L = {
    'model': 'speaking',
    'title_html': "Holding the <span class='accent'>Room</span>",
    'hero_line': 'A panelist pushes back hard, the room goes quiet, and every eye turns to the moderator',
    'menu_desc': 'Pushback, diplomatic paraphrase and the conditional without if',
    'grammar_point': 'inverted conditionals and diplomatic paraphrase under pressure',
    'phases': ['The Heat', 'Words of Debate', 'The Code', 'The Panel', 'Practice', 'Your Turn', 'Wrap-Up'],
    'guest_key': 'nadia', 'guest_voice': 'ellen',
    'imgs': {
        'hero': U + 'photo-1515169067868-5387ec356754?w=1400&q=80',
        'ch2': U + 'photo-1591115765373-5207764f72e7?w=1400&q=80',
        'ch_grammar': U + 'photo-1455390582262-044cdead277a?w=1400&q=80',
        'ch4': U + 'photo-1540575467063-178a50c2df87?w=1400&q=80',
        'ch5': U + 'photo-1497366216548-37526070297c?w=1400&q=80',
        'ch_rp': U + 'photo-1543269865-cbf427effbad?w=1400&q=80',
        'ch7': U + 'photo-1486406146926-c627a92ad1ab?w=1400&q=80',
        'pc': U + 'photo-1515169067868-5387ec356754?w=600&q=80',
    },
    'warmup': {
        'heading': "Brazil Is <span class='accent'>Not Investable</span>",
        'sub': '&ldquo;Brazil&rsquo;s regulatory framework is fundamentally incompatible with the risk models of global sovereign wealth funds.&rdquo; Respond now, as yourself. Use two words from last lesson: force majeure, due diligence, a grandfathering clause, a rebalancing claim.',
    },
    'target': {
        'heading': "Pressure Without <span class='accent'>Losing the Room</span>",
        'steps': [
            'Restate the attack in fair words before you answer it, so everyone knows what is being debated.',
            'Concede what is true, and push back on what is not, in the same breath.',
            'Move the argument from blame to a hypothesis the room can actually discuss.',
        ],
    },
    'diagnostic': {
        'heading': "A Panelist Has Been Talking for <span class='accent'>Four Minutes</span>",
        'p1': 'The toll road operator is on his fourth minute, repeating the same point, and the fund manager next to him is visibly irritated.',
        'p2': 'Stop him politely, summarize what he said in one sentence and hand the floor to the fund. Do it now.',
    },
    'ch2': {'heading': "The Words of <span class='accent'>Debate</span>",
            'sub': 'Fourteen words for disagreeing in public without starting a fight'},
    'vocab': [
        {'word': 'To push back', 'def': 'To disagree with or resist an idea, politely but firmly', 'ex': 'The fund pushed back on the idea that the risk was only political.', 'icon': 'hand'},
        {'word': 'A talking point', 'def': 'A prepared sentence that a speaker repeats to promote a position', 'ex': 'The minister stayed on his talking points for twenty minutes.', 'icon': 'message'},
        {'word': 'To sidestep a question', 'def': 'To avoid answering a question directly', 'ex': 'He sidestepped the question about the auction date.', 'icon': 'refresh'},
        {'word': 'To rein in', 'def': 'To control a speaker who is taking too much time or going off topic', 'ex': 'A good moderator reins in a speaker without embarrassing him.', 'icon': 'filter'},
        {'word': 'To steer the discussion', 'def': 'To guide a conversation in the direction you choose', 'ex': 'She steered the discussion back to the contracts.', 'icon': 'compass'},
        {'word': 'A straw man', 'def': 'A weak version of the other side&rsquo;s argument, invented so it is easy to attack', 'ex': 'Nobody said foreign funds want zero risk; that is a straw man.', 'icon': 'alert'},
        {'word': 'Common ground', 'def': 'The points on which people who disagree still agree', 'ex': 'The only common ground was that the current model is not working.', 'icon': 'link'},
        {'word': 'A red line', 'def': 'A limit that one side will not accept crossing', 'ex': 'International arbitration is the fund&rsquo;s red line.', 'icon': 'flag'},
        {'word': 'To concede a point', 'def': 'To admit that the other person is right about something', 'ex': 'I will concede the point on 2014, but not on today.', 'icon': 'scale'},
        {'word': 'A caveat', 'def': 'A warning or condition added to a statement', 'ex': 'The forecast came with one caveat: no change in the exchange rate.', 'icon': 'doc'},
        {'word': 'To reframe', 'def': 'To present a problem in a different way so that it can be discussed productively', 'ex': 'Let me reframe the question: what would you sign this year?', 'icon': 'eye'},
        {'word': 'To play devil\'s advocate', 'def': 'To argue against an idea, even one you may support, in order to test it', 'ex': 'Let me play devil\'s advocate for a moment.', 'icon': 'zap'},
        {'word': 'A non-answer', 'def': 'A reply that sounds like an answer but gives no real information', 'ex': 'We will look into it carefully is a non-answer.', 'icon': 'lock'},
        {'word': 'To take the heat out of', 'def': 'To make a tense situation or discussion calmer', 'ex': 'A short summary took the heat out of the exchange.', 'icon': 'target'},
    ],
    'pron_heading': "Firm, Not <span class='accent'>Loud</span>",
    'pron': ['A caveat', 'To concede a point', 'To play devil\'s advocate', 'Had the framework been clearer in 2019, we would have seen far more foreign capital.'],
    'vocab_fill': [
        ('The fund manager did not accept the idea, so she decided to ', 'push back', ' in front of the whole panel.'),
        ('Arbitration outside the country is the one thing the fund will not give up: it is their ', 'red line', '.'),
        ('Nobody argued that foreign funds want zero risk, so attacking that idea is ', 'a straw man', '.'),
        ('The minister spoke for three minutes and said nothing concrete: it was ', 'a non-answer', '.'),
        ('The operator is on his fourth minute, so the moderator has to ', 'rein in', ' the discussion.'),
        ('They disagree on the guarantee, but the ', 'common ground', ' is that the current model is not working.'),
    ],
    'ch_grammar': {'heading': "The Hypothesis That <span class='accent'>Sounds Considered</span>",
                   'sub': 'Conditionals without if, and the sentence you say before you argue'},
    'grammar': {
        'heading': "Where Did <span class='accent'>If</span> Go?",
        'examples': [
            "<span style='color:#b91c1c;font-weight:700'>Had</span> the framework <span style='color:#b91c1c;font-weight:700'>been</span> clearer in 2019, we would have seen more foreign capital.",
            "<span style='color:#b91c1c;font-weight:700'>Were</span> the agency <span style='color:#b91c1c;font-weight:700'>to revise</span> the concession model, the risk profile would shift.",
            "<span style='color:#b91c1c;font-weight:700'>Should</span> the ministry <span style='color:#b91c1c;font-weight:700'>accelerate</span> licensing, the pipeline would look very different.",
            "<span style='color:#1d4ed8;font-weight:700'>If I understand you correctly, what you are saying is that</span> the contract, not the country, is the risk.",
        ],
        'prompt': 'The red sentences are conditionals, but none of them has if. What took its place, and what happened to the word order? Why would a moderator choose this form when a panel is getting heated? And what does the blue sentence do before anybody argues?',
        'rule_head': ['Job', 'Form', 'Example'],
        'rule_rows': [
            ('Something that did not happen', 'Had + subject + past participle, would have + participle', '<strong>Had the rules been</strong> clearer, more capital <strong>would have come</strong>.'),
            ('A hypothesis about now or later', 'Were + subject + to + verb, would + verb', '<strong>Were the agency to revise</strong> the model, the risk <strong>would shift</strong>.'),
            ('A possible future event', 'Should + subject + base verb, would/will + verb', '<strong>Should the ministry act</strong>, the pipeline <strong>would change</strong>.'),
            ('The negative', 'Had + subject + not + past participle', '<strong>Had the auction not been</strong> delayed, three funds would have bid.'),
            ('Restate before you answer', 'If I understand you correctly, what you are saying is that + clause', 'If I understand you correctly, <strong>the contract is the risk</strong>.'),
            ('Concede, then push back', 'That is a fair point, and yet + clause', 'That is a fair point, <strong>and yet the numbers disagree</strong>.'),
            ('The trap', 'never <em>if</em> and inversion together; no contraction', 'Not <em>If had the rules been</em>, not <em>Hadn&rsquo;t the rules been</em>.'),
        ],
        'oneliner': 'Drop if, move the auxiliary to the front, and the hypothesis sounds considered instead of emotional.',
    },
    'grammar_practice': {
        'heading': "Say It Under <span class='accent'>Pressure</span>",
        'items': [
            ('', 'Had', ' the framework been clearer in 2019, we would have seen more foreign capital. (past, did not happen)'),
            ('', 'Were', ' the agency to revise the model, the risk profile would shift. (a hypothesis)'),
            ('', 'Should', ' the ministry accelerate licensing, the pipeline would look different. (a possible future)'),
            ('Had the auction not been delayed, three funds ', 'would have bid', '. (the result in the past)'),
            ('If I understand you correctly, ', 'what you are saying is that', ' the contract is the risk, not the country. (restate first)'),
            ('That is a fair point, ', 'and yet', ' the numbers tell a different story. (concede, then push back)'),
        ],
    },
    'ch4': {'heading': "Panel 2: Contracts That <span class='accent'>Survive Elections</span>",
            'sub': 'A live exchange, two recordings and your moderator notes'},
    'dialogue': {
        'heading': "The Moment the Room <span class='accent'>Goes Quiet</span>",
        'guest_name': 'Nadia', 'guest_initial': 'N',
        'lines': [
            ('n', 'With respect, Guilherme, Brazil\'s framework is simply incompatible with how a sovereign fund models risk. We have heard the <span class="vocab-highlight">talking points</span> for ten years.'),
            ('g', 'That is a strong claim, and I want to give it room. If I understand you correctly, what you are saying is that the contract, not the country, is the risk?'),
            ('n', 'Exactly. Had the concessions from 2014 been honored, my fund would already have billions in the region. They were not.'),
            ('g', 'I will <span class="vocab-highlight">concede the point</span> on 2014. But let me <span class="vocab-highlight">play devil\'s advocate</span>: were the agency to publish every rebalancing rule in advance, would that change your model?'),
            ('n', 'It would help. But I have heard that promise before, and a promise is not a clause in a contract.'),
            ('g', 'Then let me <span class="vocab-highlight">reframe</span> the question. Is there <span class="vocab-highlight">common ground</span> between what you need and what the ministry can sign this year?'),
            ('n', 'Arbitration outside the country. That is our <span class="vocab-highlight">red line</span>, and nobody on this stage has answered it yet.'),
            ('g', 'Then that is where I want to <span class="vocab-highlight">steer the discussion</span>. Should the ministry accept international arbitration, what would you put on the table in return?'),
            ('n', 'A twenty-year commitment and an anchor ticket. But I want that in writing, not in a speech.'),
            ('g', 'Noted. Let me <span class="vocab-highlight">take the heat out of</span> this for a second: we agree on the goal and disagree on the guarantee. That is a negotiation, not a stalemate.'),
        ],
        'comp': [
            ('What does Nadia claim about Brazil&rsquo;s framework?', 'That it is simply incompatible with how a sovereign fund models risk.'),
            ('According to Nadia, what would have happened if the 2014 concessions had been honored?', 'Her fund would already have billions in the region.'),
            ('What is her red line?', 'Arbitration outside the country.'),
            ('What would she offer in return, and in what form does she want it?', 'A twenty-year commitment and an anchor ticket, in writing, not in a speech.'),
        ],
    },
    'listenings': [
        {'label': 'Listening 1 &middot; A Negotiation Coach', 'title': "Restate Before You <span class='accent'>Respond</span>",
         'blurb': 'A negotiation coach on staying in control of a hostile exchange. Sound first &mdash; no text.',
         'voice': 'arthur',
         'text': 'When somebody attacks your position in public, your instinct is to defend it immediately. Resist that for five seconds. The most powerful move in a hostile exchange is to restate the other person\'s argument so fairly that they say, yes, exactly. It does three things. It shows the room you were listening. It forces the other person to agree with you about what the disagreement actually is. And it gives you time to think. Only then should you concede what is true, and there is almost always something true. After that, push back on the one point that matters, and turn it into a hypothesis the room can discuss. People can argue with a hypothesis for an hour without anybody losing face. They cannot do that with an accusation.',
         'qs': [
             ('What does the coach say your instinct is, and what should you do instead?', 'Your instinct is to defend your position immediately. Instead, wait five seconds and restate the other person&rsquo;s argument fairly.'),
             ('What three things does restating the argument do?', 'It shows the room you were listening, it makes the other person agree on what the disagreement is, and it gives you time to think.'),
             ('Why does he recommend turning the point into a hypothesis?', 'Because people can argue with a hypothesis for an hour without anybody losing face, but not with an accusation.'),
         ]},
        {'label': 'Listening 2 &middot; The Moderator', 'title': "I Am Going to <span class='accent'>Stop You There</span>",
         'blurb': 'A moderator takes back control of a panel. Sound first &mdash; no text.',
         'voice': 'ellen',
         'text': 'Thank you, David, and I am going to stop you there, because I want to make sure the room has your main point before we lose it. If I understand you correctly, what you are saying is that the auction calendar, not the tariff, is what keeps investors away. Is that fair? Good. Now, that is a claim the fund side will want to test, so let me bring in Maria. Maria, you have been shaking your head for two minutes. Should the calendar be fixed by law, as David suggests, would your fund bid in the first round, or would you still wait? And a caveat for everyone: we have eleven minutes left, so I will ask you to keep your answers under ninety seconds.',
         'qs': [
             ('Why does the moderator stop David?', 'To make sure the room has his main point before they lose it.'),
             ('How does she summarize David&rsquo;s point?', 'That the auction calendar, not the tariff, is what keeps investors away.'),
             ('What does she ask Maria, and what caveat does she give everyone?', 'Whether her fund would bid in the first round if the calendar were fixed by law. The caveat is that there are eleven minutes left, so answers must be under ninety seconds.'),
         ]},
    ],
    'artifact': {
        'heading': "Your Moderator <span class='accent'>Notes</span>",
        'title': 'MODERATOR NOTES &mdash; PANEL 2', 'subtitle': 'Contracts That Survive Elections &middot; 45 minutes',
        'rows': [
            ('Panelists', 'Sovereign fund (N. Haddad) &middot; Ministry &middot; Toll road operator', False),
            ('Known red lines', 'Fund: international arbitration &middot; Ministry: no currency guarantee from the Treasury', True),
            ('Likely non-answer', 'Ministry, on the timeline for the new concession model', False),
            ('Planned pivot', 'Question 3 &mdash; from blame to common ground', True),
            ('Open the floor', 'At minute 30', False),
        ],
        'note': 'If a panelist goes over two minutes, rein them in with a summary, not an interruption. Do not let a talking point stand as an answer.',
        'qs': [
            ('What are the two known red lines?', 'The fund&rsquo;s is international arbitration; the ministry&rsquo;s is no currency guarantee from the Treasury.'),
            ('Where does he expect a non-answer, and what is the planned pivot?', 'From the ministry, on the timeline for the new concession model. The pivot, at question 3, goes from blame to common ground.'),
            ('What should he do if a panelist goes over two minutes?', 'Rein them in with a summary, not an interruption.'),
        ],
    },
    'ch5': {'heading': "Train Like a <span class='accent'>Chair</span>", 'sub': 'Detective &middot; Speaking &middot; Building'},
    'detective': [
        ('If had the rules been clearer, more capital would come.', '<strong>Had the rules been</strong> clearer, more capital <strong>would have come</strong>.'),
        ('Were the agency revise the model, the risk would shift.', 'Were the agency <strong>to revise</strong> the model, the risk would shift.'),
        ('Let me do the devil\'s advocate for a moment.', 'Let me <strong>play devil\'s advocate</strong> for a moment.'),
        ('We need to find a common point between the fund and the ministry.', 'We need to find <strong>common ground</strong> between the fund and the ministry.'),
    ],
    'speaking': [
        ('Brazil is simply not investable for sovereign funds. Do you disagree?', 'I want to give that room. If I understand you correctly, the contracts are the risk. Had they been honored in 2014, I think we would be having a different conversation.'),
        ('What if the ministry offered international arbitration?', 'Should the ministry offer it, I think two funds in this room would move within a year. The question is what the ministry gets in return.'),
        ('A panelist has been talking for five minutes. What do you do?', 'I rein him in with a summary: so what you are saying is that the auction calendar is the risk. Then I bring in the fund on exactly that point.'),
        ('How do you calm a panel that is getting personal?', 'I take the heat out of it by naming the common ground: we agree on the goal, and we disagree on the guarantee.'),
    ],
    'building': [
        ('had / the framework / be clearer / we / see more capital (past, did not happen)', 'Had the framework been clearer, we would have seen more capital.'),
        ('were / the agency / revise the model / the risk profile / shift (a hypothesis)', 'Were the agency to revise the model, the risk profile would shift.'),
        ('should / the ministry / accelerate licensing / the pipeline / look different (possible future)', 'Should the ministry accelerate licensing, the pipeline would look different.'),
        ('if I understand you correctly / you / say / the contract / be / the risk (restate)', 'If I understand you correctly, what you are saying is that the contract is the risk.'),
    ],
    'roleplays': {
        'heading': "The Panel Gets <span class='accent'>Hot</span>",
        'items': [
            {'heading': "Nadia Pushes <span class='accent'>Back</span>",
             'scenario': 'Nadia repeats her claim that the framework is incompatible with sovereign risk models. Restate it fairly, concede one point, and push back with one conditional without if.',
             'chips': ['If I understand you correctly', 'to concede a point', 'Had', 'common ground']},
            {'heading': "Rein In <span class='accent'>the Ministry</span>",
             'scenario': 'The ministry&rsquo;s representative gives a long non-answer about the timeline for the new concession model. Rein him in, reframe the question and get either a concrete date or a clear red line.',
             'chips': ['to rein in', 'a non-answer', 'to reframe', 'Should']},
            {'heading': "Two Minutes, <span class='accent'>Flash Debate</span>",
             'scenario': 'Moderate a flash debate between the sovereign fund and the ministry on international arbitration. Give each side twenty seconds, reframe once, and close with a question that looks forward.',
             'footer': 'No notes, two minutes. One restatement, one concession, one hypothesis, one close.'},
        ],
    },
    'ch7': {'heading': "Five Sentences for the <span class='accent'>Next Hot Panel</span>", 'sub': 'What you say when the room goes quiet'},
    'survival_heading': "Five Sentences for the <span class='accent'>Next Hot Panel</span>",
    'survival': [
        'If I understand you correctly, what you are saying is that the contract, not the country, is the risk.',
        'That is a fair point, and yet the numbers tell a different story.',
        'Had the framework been clearer in 2019, we would have seen far more foreign capital.',
        'Should the ministry accept international arbitration, what would you put on the table?',
        'Let me take the heat out of this: we agree on the goal and disagree on the guarantee.',
    ],
    'checklist': [
        'I can restate an attack fairly before I answer it.',
        'I can concede a point and push back in the same sentence.',
        'I use conditionals without if: Had, Were ... to, Should.',
        'I can rein in a speaker and turn a non-answer into a concrete question.',
        'I know the words: to push back, a talking point, to sidestep a question, to rein in, to steer the discussion, a straw man, common ground, a red line, to concede a point, a caveat, to reframe, to play devil\'s advocate, a non-answer, to take the heat out of.',
    ],
    'badge': {'name': 'Holding the Room', 'line': 'Restate it, concede what is true, and turn the fight into a hypothesis.',
              'next': 'Next lesson: The Executive Pen -- press releases, briefing notes and linking devices, in reading'},
    'teacher': {
        'opening': '<strong>Abertura (2 min):</strong> Va direto: \'Guilherme, today the panel gets hot.\' Esta aula treina o que ele disse na consultoria: \'poder contornar situacoes de maneira muito mais facil\'. Ele e extrovertido e confiante (mapa de personalidade): o risco aqui NAO e travar, e ser rapido demais e responder antes de reformular. O ritmo da aula e desacelerar a resposta.',
        'warmup': '<strong>Warm-up de pressao + callback (5 min):</strong> A frase provocativa na tela e de proposito. Ele responde de imediato, como ele mesmo; voce NAO interrompe. Callback da aula 4: duas palavras (force majeure, due diligence, a grandfathering clause, a rebalancing claim). ANOTE: ele reformulou antes de discordar? Concedeu algo? Esse e o baseline da aula.',
        'target': '<strong>Enquadramento (2 min):</strong> Tres movimentos. Pergunte qual ele faz naturalmente em portugues e qual some em ingles sob pressao (costuma ser o primeiro: reformular).',
        'diagnostic': '<strong>Pergunta-gatilho (3 min):</strong> Situacao de palco real. Cronometre. ANOTE a frase exata que ele usa para interromper &mdash; brasileiro costuma dizer \'Sorry, but...\' e parar sem resumir. O Listening 2 mostra a versao profissional.',
        'ch2': '<strong>Transicao vocab (1 min):</strong> Diga: \'Fourteen words for disagreeing in public without starting a fight.\'',
        'vocab1': '<strong>Vocab reveal 1-5 (5 min):</strong> CCQ \'to push back\': \'Rude or firm? (Firme, educado.)\' CCQ \'to sidestep a question\': \'Did he answer? (Nao.)\' CCQ \'to rein in\': \'Do you stop the speaker completely? (Nao, controla.)\' Peca a frase exata que ele usaria para cada um no proximo painel.',
        'vocab2': '<strong>Vocab reveal 6-10 (5 min):</strong> CCQ \'a straw man\': \'Did the other person really say that? (Nao.)\' CCQ \'a red line\': \'Can it be negotiated? (Nao.)\' CCQ \'to concede a point\': \'Are you losing the argument? (Nao necessariamente, e estrategia.)\' Pronuncia: CAV-e-at, tres silabas.',
        'vocab3': '<strong>Vocab reveal 11-14 (4 min):</strong> CCQ \'to reframe\': \'Same problem or different problem? (Mesmo, contado de outro jeito.)\' CCQ \'a non-answer\': \'Long or short? (Pode ser longo, e sem informacao.)\' Peca exemplos de non-answers classicos de ministro e de CEO.',
        'pron': '<strong>Pronuncia (4 min):</strong> Firme, nao alto. CAV-e-at, con-CEDE (acento na segunda), DEV-il\'s AD-vo-cate. Na frase longa, a inversao \'Had the framework been\' pede voz descendo em \'capital\' e pausa leve depois de \'2019\'. Sob pressao, o brasileiro acelera: treine desacelerar.',
        'vocab_fill': '<strong>Vocab in context (3 min):</strong> Banco embaixo. Ele diz antes de clicar. Se fechar rapido, peca que ele use \'a straw man\' numa frase sobre um debate real que ja moderou.',
        'ch_grammar': '<strong>Transicao gramatica (1 min):</strong> Diga: \'Three conditionals with no if. Find out where it went.\'',
        'grammar': '<strong>Grammar discovery (7 min):</strong> Peca que ele diga cada frase com if (\'If the framework had been clearer...\'). Pergunte: \'What replaced if, and what moved?\' So entao Reveal the Rule. CCQ: \'Had the framework been clearer &mdash; was it clear? (Nao.)\' CCQ: \'Were the agency to revise &mdash; has it revised? (Nao, hipotese.)\' CCQ: \'Should the ministry accelerate &mdash; likely or possible? (Possivel.)\' Pragmatica: a forma sem if soa ponderada; em debate acalorado, tira emocao da frase. Obstaculo: misturar if com inversao, e contrair (Hadn\'t the rules been...).',
        'grammar_practice': '<strong>Practice (4 min):</strong> Frase inteira antes de clicar. Nas duas ultimas, que sao frases de moderador, cobre o tom: calmo, voz descendo, sem pressa.',
        'ch4': '<strong>Transicao (1 min):</strong> Diga: \'Panel 2. A live exchange, two recordings and your own moderator notes.\'',
        'dialogue': '<strong>Dialogo (7 min):</strong> Voce e a Nadia Haddad, gestora de fundo soberano: educada, dura, sem medo de constranger o ministerio. Next Line e audio. Nas falas do Guilherme, ele fala PRIMEIRO. PRAGMATICA para o fim: repare que ele nunca discorda de cara &mdash; reformula, concede 2014, e so entao transforma o ataque em hipotese (\'were the agency to publish...\'). E o roteiro do Listening 1.',
        'dialogue_comp': '<strong>Comprehension (3 min):</strong> Perguntas sobre a NADIA (REGRA 27F). Na quarta, pergunte se ja viu um fundo pedir compromisso por escrito numa mesa do GRI.',
        'listening1': '<strong>Listening 1 (5 min):</strong> LEIA AS PERGUNTAS EM VOZ ALTA COM ELE ANTES de tocar. Coach de negociacao. Toque duas vezes. Depois compare com o warm-up: ele reformulou antes de responder a frase provocativa? Mostre a anotacao.',
        'listening2': '<strong>Listening 2 (5 min):</strong> LEIA AS PERGUNTAS ANTES de tocar. Moderadora retomando o controle. Depois das perguntas, peca que ele liste os movimentos na ordem: parar, resumir, confirmar, trazer outra pessoa, hipotese, aviso de tempo. Compare com a frase dele no slide 4.',
        'artifact': '<strong>Artefato (4 min):</strong> As notas de moderador dele. Peca que ele transforme cada linha numa frase de planejamento em voz alta (\'Should the ministry give a non-answer on the timeline, I will...\'). Depois as perguntas.',
        'ch5': '<strong>Transicao practice (1 min):</strong> Diga: \'Now we train: detective, your own answers, and building.\'',
        'detective': '<strong>Detective (4 min):</strong> Ele corrige antes de clicar. Dois erros de condicional invertida e dois calcos (\'do the devil\'s advocate\', \'a common point\'). Correcao direta.',
        'speaking': '<strong>Speaking (5 min):</strong> Faca as perguntas com tom de ataque, como a Nadia faria. Regra do bloco: toda resposta comeca reformulando ou concedendo, nunca discordando de cara. Correcao em bloco no fim.',
        'building': '<strong>Sentence Building (4 min):</strong> Frase completa, calma, antes de clicar. Se fechar as quatro sem ajuda, ganhe tempo para o flash debate.',
        'ch_rp': '<strong>Transicao role-play (1 min):</strong> Diga: \'The panel gets hot. Three times, and the last one is a flash debate.\'',
        'rp1': '<strong>Role-play guiado (4 min):</strong> Voce e a Nadia, mais agressiva que no dialogo. Ele reformula, concede, empurra de volta com uma inversao. Avalie: a reformulacao foi justa o suficiente para voce dizer \'yes, exactly\'? Se nao, repita.',
        'rp2': '<strong>Role-play semi-livre (5 min):</strong> Voce e o representante do ministerio e da um non-answer longo e redondo sobre prazo. Nao pare sozinho. Ele precisa conter, reformular e conseguir data ou red line. E o que ele faz de verdade no GRI.',
        'rp3': '<strong>Role-play livre (6 min):</strong> Voce faz os dois lados (fundo e ministerio), trocando a voz. Dois minutos cronometrados. No fim, quatro checagens: reformulou? concedeu? hipotese sem if? fechamento para frente? E UMA observacao de ritmo.',
        'ch7': '<strong>Transicao wrap-up (1 min):</strong> Diga: \'Five sentences for the next hot panel.\'',
        'survival': '<strong>Survival card (3 min):</strong> Audio e repeticao, tom calmo. Peca que ele use a primeira ou a ultima numa reuniao tensa real antes da aula 6.',
        'checklist': '<strong>Checklist (2 min):</strong> Todos os 5 = aula concluida e stamp 5. Item em que ele hesitar entra no warm-up da aula 6.',
        'complete': '<strong>Encerramento (2 min):</strong> Diga: \'Restate it, concede what is true, turn the fight into a hypothesis.\' Homework (ORALMENTE, nunca escrito na tela): escrever um artigo de opiniao de 300 palavras para a newsletter do GRI sobre por que capital estrangeiro precisa mais de coerencia regulatoria que de incentivo fiscal, com tres condicionais invertidas; e gravar 2 minutos moderando um flash debate fazendo os tres papeis. Proxima aula: a caneta executiva &mdash; press release, briefing note e conectivos, em leitura.',
    },
    'pc': {
        'title': 'Holding the Room -- The Conditional Without If',
        'desc': 'A sovereign fund manager attacks the framework in front of three hundred people, and the room waits for the moderator.',
        'match_idx': [0, 3, 6, 7, 10, 12],
        'context': [
            'When a panel gets heated, the moderator has two jobs at once: keep the argument alive and keep it from becoming personal. The language that does both is surprisingly calm.',
            'The first move is to <strong>restate</strong> the attack before answering it: &ldquo;<strong>If I understand you correctly, what you are saying is that</strong> the contract, not the country, is the risk.&rdquo; The second is to <strong>concede a point</strong> without giving up the argument: &ldquo;That is a fair point, <strong>and yet</strong> the numbers tell a different story.&rdquo; Neither sentence is weak. Both show the room that you heard the <strong>pushback</strong> and are not afraid of it.',
            'The third move turns blame into a hypothesis, and English has a formal way to do it: the conditional without <strong>if</strong>. &ldquo;<strong>Had</strong> the framework <strong>been</strong> clearer in 2019, we would have seen more capital&rdquo; talks about a past that did not happen. &ldquo;<strong>Were</strong> the agency <strong>to revise</strong> the model, the risk would shift&rdquo; imagines the present or future. &ldquo;<strong>Should</strong> the ministry <strong>accept</strong> international arbitration, the fund would move&rdquo; describes a possible event.',
            'In all three, <strong>if</strong> disappears and the auxiliary moves to the front. Never use both at once (&ldquo;If had the rules been&rdquo;), and never contract (&ldquo;Hadn&rsquo;t the rules been&rdquo;). Used calmly, the structure does something useful: it moves a <strong>red line</strong> from an accusation to a proposal, and people can discuss a proposal without losing face.',
        ],
        'context_quiz': [
            ('According to the text, what is the first move when a panel gets heated?', ['Disagree immediately and firmly.', 'Restate the attack before answering it.', 'Change the subject.'], 1),
            ('What does &ldquo;Were the agency to revise the model&rdquo; describe?', ['A hypothesis about the present or future.', 'Something that already happened.', 'A decision the agency announced.'], 0),
            ('Which sentence does the text say is wrong?', ['Had the framework been clearer, we would have seen more capital.', 'Should the ministry accept arbitration, the fund would move.', 'If had the rules been clearer, the fund would have stayed.'], 2),
        ],
        'tip_title': 'Inverted Conditionals and Diplomatic Frames',
        'tip_lead': 'Drop if, move the auxiliary to the front, and the hypothesis sounds considered instead of emotional.',
        'tip_rows': [
            ('Past, did not happen', 'Had + subject + past participle', '<strong>Had the rules been</strong> clearer, capital would have come.'),
            ('A hypothesis', 'Were + subject + to + verb', '<strong>Were the agency to revise</strong> the model, the risk would shift.'),
            ('A possible future', 'Should + subject + base verb', '<strong>Should the ministry act</strong>, the pipeline would change.'),
            ('Negative', 'Had + subject + not + participle', '<strong>Had the auction not been</strong> delayed, three funds would have bid.'),
            ('Restate first', 'If I understand you correctly, what you are saying is that', '... <strong>the contract is the risk</strong>.'),
            ('Concede, then push back', 'That is a fair point, and yet', '... <strong>the numbers disagree</strong>.'),
        ],
        'tip_never': 'if had the rules been clearer &middot; hadn&rsquo;t the rules been clearer &middot; were the agency revise the model &middot; let me do the devil\'s advocate &middot; a common point',
        'blanks': [
            ('', 'Had', ' the framework been clearer in 2019, we would have seen more foreign capital.', 'Hint: a past that did not happen, and no if -- one word', None),
            ('Were the agency ', 'to revise', ' the model, the risk profile would shift.', 'Hint: after Were + subject comes to + verb -- two words', None),
            ('', 'Should', ' the ministry accept international arbitration, the fund would move.', 'Hint: a possible future event, and no if -- one word', None),
            ('Arbitration outside the country is the fund\'s ', 'red line', '.', 'Hint: the limit they will not cross -- two words', None),
            ('Let me ', 'play devil\'s advocate', ' for a moment.', 'Hint: argue the other side to test an idea -- three words', 'play devils advocate'),
            ('That was ', 'a non-answer', ': he spoke for three minutes and said nothing.', 'Hint: sounds like an answer, gives no information -- two words', None),
        ],
        'order_title': 'Put the Response in Order',
        'order_lead': 'A fund manager has just attacked the framework on stage. Put your response in a logical order.',
        'order': [
            'That is a strong claim, and I want to give it room.',
            'If I understand you correctly, what you are saying is that the contract, not the country, is the risk.',
            'I will concede the point on 2014.',
            'Had those contracts been honored, we would be having a different conversation.',
            'So let me reframe it: should the ministry accept international arbitration, what would you put on the table?',
            'Minister, I would like to bring you in on exactly that question.',
        ],
        'quiz': [
            ('A panelist attacks your position. Before you answer, you say:', ['You are wrong about that.', 'If I understand you correctly, what you are saying is that the contract is the risk.', 'This is not true, sorry.'], 1),
            ('You want a calm hypothesis about something that did not happen. You say:', ['Had the rules been clearer, more capital would have come.', 'If had the rules been clearer, more capital came.', 'The rules were clearer, more capital would come.'], 0),
            ('A speaker has talked for five minutes. You say:', ['Stop, please, you talk too much.', 'OK, next.', 'I am going to stop you there so the room has your main point: the calendar is the risk.'], 2),
            ('You want to admit the other person is right about one thing. You say:', ['I will concede the point on 2014.', 'I concord with you in parts.', 'You have the reason on 2014.'], 0),
        ],
        'think': 'You are moderating a flash debate: a sovereign fund says Brazil&rsquo;s framework is not investable, and the ministry says the framework is stable. In two minutes, restate both positions fairly, concede one point to each, turn the disagreement into a hypothesis without if, and close with a forward-looking question.',
    },
    'media': [
        {'id': 'talk', 'type': 'Talk', 'title': 'Julia Dhar &mdash; &ldquo;How to disagree productively and find common ground&rdquo; (TED)',
         'desc': 'A world debating champion on how to disagree without making it personal: start from common ground, separate the idea from the person, and stay curious. Everything a moderator needs when a panel gets hot.',
         'tip': 'Tip: note the three steps she proposes and test one of them in your next tense meeting.',
         'url': 'https://www.ted.com/talks/julia_dhar_how_to_disagree_productively_and_find_common_ground', 'cta': 'Watch on TED'},
        {'id': 'podcast', 'type': 'Podcast', 'title': 'Freakonomics Radio &mdash; &ldquo;Can We Disagree Better?&rdquo;',
         'desc': 'Why public disagreement has become so hostile, and what researchers have learned about arguing in a way that actually moves people.',
         'tip': 'Tip: listen for the phrases people use to concede a point. Write down two you would use on stage.',
         'url': 'https://freakonomics.com/podcast/can-we-disagree-better/', 'cta': 'Listen on Freakonomics'},
        {'id': 'video', 'type': 'Talk', 'title': 'Margaret Heffernan &mdash; &ldquo;Dare to disagree&rdquo; (TED)',
         'desc': 'A former CEO on why the best organizations need people who push back, and how productive conflict protects everyone from bad decisions.',
         'tip': 'Tip: retell her main story in reported speech, and add one conditional without if about what would have happened.',
         'url': 'https://www.ted.com/talks/margaret_heffernan_dare_to_disagree', 'cta': 'Watch on TED'},
    ],
}
