# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1400&q=80"

D = {
    'n': 8,
    'reading': True,
    'partner_name': 'daniel',
    'grammar_point_pt': "os tempos verbais juntos: passado simples, presente contínuo e futuro (going to / will)",
    'chapter_tag': 'Midpoint Review',
    'title_h1': 'Midpoint <span class="accent">Review</span>',
    'title_sub': 'How far have you come -- and where are you going next?',
    'short_title': 'Midpoint Review',
    'menu_title': 'Midpoint Review -- How Far You Have Come',
    'menu_desc': 'A midpoint review of your journey: past, present, and future together',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&q=80",
    'stamp_label': 'Halfway There',
    'stamp_img': "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=200&q=80",
    'phases': ['Halfway There', 'The Words of Progress', 'Your Story So Far',
               'The Code', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From the Fair Floor to the <span class="accent">Halfway Point</span>',
    'warm_p': 'Last time you learned to listen and clarify with fast speakers. Today we pause and take stock: this is the halfway point of your program, and it is time to see how far you have come.',
    'warm_prompt': 'In one sentence: what can you do in English now that you could not do six months ago?',
    'missions': [
        'Review the words of progress and self-assessment.',
        'Use past, present, and future together to tell your story.',
        'Give a confident three-minute talk about your English journey.',
    ],

    'vocab_trans_h2': 'The Language of <span class="accent">Progress</span>',
    'vocab': [
        ("Progress", "steady improvement over time (progresso)", "I can see real progress in my speaking."),
        ("Milestone", "an important point you reach (marco)", "This class is an important milestone."),
        ("Confidence", "the feeling of being sure of yourself (confiança)", "My confidence has grown a lot."),
        ("Fluency", "speaking smoothly and easily (fluência)", "Fluency matters more than perfection."),
        ("Comfort zone", "the easy, familiar situation (zona de conforto)", "Speaking English pushes me out of my comfort zone."),
        ("To keep up with", "to stay at the same level as something (acompanhar)", "I can keep up with fast conversations now."),
        ("Strength", "something you are good at (ponto forte)", "Small talk is now a real strength."),
        ("Area for improvement", "something you still need to work on (ponto a melhorar)", "Pronunciation is my main area for improvement."),
        ("Breakthrough", "a sudden, important step forward (avanço)", "Last week I had a real breakthrough."),
        ("To take stock", "to review your situation carefully (fazer um balanço)", "It is a good moment to take stock."),
        ("Self-assessment", "evaluating your own work honestly (autoavaliação)", "This lesson is a self-assessment."),
        ("Halfway point", "the middle of a journey (meio do caminho)", "We are at the halfway point of the program."),
    ],

    'gram_trans_h2': 'Past, Present, <span class="accent">Future</span>',
    'gram_trans_sub': 'started &middot; am improving &middot; am going to present',
    'gram_examples': [
        ("", "Six months ago, I started this program.", '"Six months ago, I <span class="accent" style="font-weight:700">started</span> this program."'),
        ("", "Right now, I am improving my fluency.", '"Right now, I <span style="color:#15803d;font-weight:700">am improving</span> my fluency."'),
        ("", "Next month, I am going to present in Berlin.", '"Next month, I <span style="color:#1d4ed8;font-weight:700">am going to</span> present in Berlin."'),
    ],
    'gram_disc_q': 'Past, present, or future -- which time does each sentence talk about?',
    'gram_table': [
        ("Past simple", "A finished action in the past", "Six months ago, I <strong>started</strong>."),
        ("Present continuous", "An action in progress now", "Right now, I <strong>am improving</strong>."),
        ("going to / will", "A plan or prediction for the future", "Next month, I <strong>am going to</strong> present."),
    ],
    'gram_rule_foot': "The time word chooses the tense: 'ago' -> past simple, 'right now' -> present continuous, 'next' -> future.",

    'lf_h2': 'Past, Present, or <span class="accent">Future?</span>',
    'lf_title': 'Past, present, or future?',
    'lf_items': [
        ["A", "Six months ago, I ", "started", " to network in English.", "strong"],
        ["B", "Right now, I ", "am improving", " my fluency.", "soft"],
        ["C", "Next month, I ", "am going to", " present in Berlin.", "soft"],
        ["D", "Today, I ", "am taking stock", " of my progress.", "soft"],
    ],
    'lf_followup': "Match the time to the tense: 'six months ago' -> past simple (started); 'right now' / 'today' -> present continuous (am improving, am taking); 'next month' -> future (am going to present).",

    'mistakes': [
        ("Yesterday I am starting the course.", 'Yesterday I <strong>started</strong> the course.'),
        ("Right now I improve my accent.", 'Right now I <strong>am improving</strong> my accent.'),
    ],
    'mistake_note': "Use the past simple for finished past actions, and the present continuous (am/is/are + -ing) for what is happening right now.",

    'read_trans_h2': 'Read Your <span class="accent">Story</span>',
    'reading_h2': 'The Power of the <span class="accent">Midpoint</span>',
    'read_block': {
        'rtitle': 'The Power of the Midpoint',
        'paras': [
            "Every long journey has a halfway point, and it is one of the most valuable moments of all. At the start, everything is new and progress feels fast. Near the end, the goal is clear and motivation returns. But in the middle, many learners lose energy. They stop noticing how far they have come. The secret of successful people is simple: at the midpoint, they stop and take stock.",
            "Taking stock means looking honestly at three things. First, the past: what could you not do before that you can do now? Six months ago, a fast phone call felt impossible; today, you keep up with native speakers. Second, the present: what are you working on right now? Maybe your fluency is growing while your pronunciation still needs work. Third, the future: what is your next milestone?",
            "This honest self-assessment does something powerful. It turns a vague feeling of 'I am not good enough' into a clear map of real progress and specific areas for improvement. Confidence does not come from being perfect. It comes from seeing, with your own eyes, how much you have already achieved -- and knowing exactly where you are going next.",
        ],
        'source': 'Adapted from a language-learning guide, The Confident Speaker',
        'link': 'https://www.theconfidentspeaker.com',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "Most learners give up at the halfway point and should stop studying.", False],
            ["b", "At the midpoint, taking honest stock of your progress builds real confidence.", True],
            ["c", "Confidence only comes from speaking perfectly, with no mistakes.", False],
        ],
        'tf': [
            ["According to the text, the halfway point is one of the most valuable moments.", "t", "The first paragraph says it is one of the most valuable moments of all."],
            ["The text says most learners gain energy in the middle of a journey.", "f", "It says many learners lose energy in the middle and stop noticing their progress."],
            ["Taking stock means looking at the past, the present, and the future.", "t", "The second paragraph describes these three things."],
            ["The text says confidence comes from being perfect.", "f", "It says confidence comes from seeing how much you have already achieved, not from being perfect."],
        ],
    },

    'dialogue_h2': 'The Midpoint <span class="accent">Interview</span>',
    'dialogue': [
        ('daniel', 'arthur', "Andrea, we are at the halfway point of your program, lesson eight of fifteen. How do you feel about your progress?",
         "Andrea, we are at the halfway point of your program, lesson eight of fifteen. How do you feel about your <span class=\"vocab-highlight\">progress</span>?"),
        ('andrea', 'ellen', "Honestly, I feel much more confident. Six months ago, I froze in every English meeting.",
         "Honestly, I feel much more confident. Six months ago, I froze in every English meeting."),
        ('daniel', 'arthur', "That is a real breakthrough. What are you working on right now?",
         "That is a real <span class=\"vocab-highlight\">breakthrough</span>. What are you working on right now?"),
        ('andrea', 'ellen', "Right now, I am improving my fluency and learning to keep up with fast speakers.",
         "Right now, I am improving my <span class=\"vocab-highlight\">fluency</span> and learning to <span class=\"vocab-highlight\">keep up with</span> fast speakers."),
        ('daniel', 'arthur', "Excellent. And what are your plans for the second half?",
         "Excellent. And what are your plans for the second half?"),
        ('andrea', 'ellen', "Next month, I am going to present Escape Turismo at a fair in Berlin, all in English.",
         "Next month, I am going to present Escape Turismo at a fair in Berlin, all in English."),
        ('daniel', 'arthur', "Wonderful. What is still your main area for improvement?",
         "Wonderful. What is still your main <span class=\"vocab-highlight\">area for improvement</span>?"),
        ('andrea', 'ellen', "My pronunciation. But I am taking stock today, and I can see real progress.",
         "My pronunciation. But I am <span class=\"vocab-highlight\">taking stock</span> today, and I can see real progress."),
    ],
    'comprehension': [
        ("1. What point of the program are they at?", "The halfway point -- lesson eight of fifteen."),
        ("2. What does Andrea say she is working on right now?", "Improving her fluency and keeping up with fast speakers."),
        ("3. Where is she going to present next month?", "At a fair in Berlin."),
    ],

    'listen1_h2': 'A Message from Your <span class="accent">Teacher</span>',
    'listen1_sub': 'An encouraging note about your progress. Sound first -- no text.',
    'listen1_qs': [
        ("1. What is the teacher proud of?", "Andrea's progress."),
        ("2. What could Andrea not do six months ago?", "She was nervous in every meeting."),
        ("3. What will they do together in the next class?", "Take stock and set goals for the second half."),
    ],
    'listen2_h2': 'Why <span class="accent">Review</span> Matters',
    'listen2_sub': 'A webinar on midpoint self-assessment. Sound first -- no text.',
    'listen2_qs': [
        ("1. What question should every learner ask at the middle of a course?", "How far have I come?"),
        ("2. What do people who review their progress do?", "They stay motivated far longer."),
        ("3. What should you set for the next stage?", "One clear goal."),
    ],
    'listenings': [
        {'file': 'a8_listening_teacher.mp3', 'voice': 'arthur',
         'text': "Hi Andrea, it is your teacher. I wanted to leave you a quick note before our midpoint class. I am really proud of your progress. Six months ago, you were nervous in every meeting. Now you make small talk, you follow fast speakers, and you handle a whole negotiation in English. That is a real breakthrough. In our next class, we are going to take stock together and set your goals for the second half. Come ready to talk about your strengths and one area you want to improve. See you soon, and keep up the great work."},
        {'file': 'a8_listening_review.mp3', 'voice': 'ellen',
         'text': "Welcome to today's short segment on learning. Here is a question every learner should ask at the middle of a course: how far have I come? Research shows that people who pause to review their progress stay motivated far longer than those who do not. This is called self-assessment, and it is a powerful tool. The method is simple. Write down three things you can do now that you could not do at the start. Then name one strength and one area for improvement. Finally, set one clear goal for the next stage. Do not wait until the end of your journey to celebrate. Take stock at the halfway point, and you will finish stronger."},
    ],

    'gapfill_parts': [
        "At the ", ["1"], " of the program, it is smart to ", ["2"],
        " and review your journey. Andrea can see clear ", ["3"], ": small talk is now a ", ["4"],
        ", and her ", ["5"], " has grown.",
    ],
    'gapfill_bank': ["halfway point", "take stock", "progress", "strength", "confidence"],
    'vocabnote': "Notice the time signals: 'six months ago' needs the past simple (started), 'right now' needs the present continuous (am improving), and 'next month' needs a future form (am going to present).",

    'bank_label_top': 'Reflect',
    'bank_label': 'Useful language for reflecting on progress',
    'bank_items': [
        "Six months ago, I could not do this.",
        "Right now, I am working on my fluency.",
        "I have made real progress this year.",
        "My main strength is small talk.",
        "My main area for improvement is pronunciation.",
        "Next, I am going to present at a fair.",
        "This is an important milestone for me.",
        "I am taking stock of my journey.",
    ],

    'scenarios_h2': 'Tell Your <span class="accent">Story</span>',
    'scenario_items': [
        ["Scenario 1", "Describe one thing you could NOT do six months ago but can do now. Use the past simple and the present."],
        ["Scenario 2", "Say what you are working on right now, using the present continuous."],
        ["Scenario 3", "Explain your plan for the second half of the program, using 'going to'."],
        ["Scenario 4", "Take stock: name one strength and one area for improvement in full sentences."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = halfway point, 2 = take stock, 3 = progress, 4 = strength, 5 = confidence.",
        "Past: 'Six months ago, I started to network in English.'",
        "Present: 'Right now, I am improving my fluency.'",
        "Future: 'Next month, I am going to present at a fair in Berlin.'",
    ],
    'answerkey_note': "The time word tells you the tense: ago -> past simple; right now -> present continuous; next -> going to.",

    'roleplays': [
        {'h2': 'Look <span class="accent">Back</span>',
         'scenario': "Tell your teacher three things you have learned since Lesson 1. Use the past simple.",
         'keywords': ["Six months ago...", "I learned...", "milestone"]},
        {'h2': 'The Present and the <span class="accent">Plan</span>',
         'scenario': "Describe what you are working on now and your plan for the second half of the program.",
         'keywords': ["Right now I am...", "Next, I am going to...", "fluency"]},
        {'h2': 'Your Three-Minute <span class="accent">Journey</span>',
         'scenario': "Give a short, uninterrupted talk about your English journey: where you started, where you are now, and where you are going. Use past, present, and future.",
         'keywords': []},
    ],

    'survival_h2': 'Speak About Your <span class="accent">Journey</span>',
    'survival': [
        ("Six months ago, I could not speak in meetings.", "Há seis meses, eu não conseguia falar em reuniões."),
        ("Right now, I am improving my fluency.", "Agora, estou melhorando minha fluência."),
        ("I have made real progress this year.", "Eu fiz um progresso real este ano."),
        ("My main area for improvement is pronunciation.", "Meu principal ponto a melhorar é a pronúncia."),
        ("Next month, I am going to present at a fair.", "No próximo mês, vou apresentar em uma feira."),
    ],
    'learned': [
        "I can talk about my past progress using the past simple.",
        "I can describe what I am doing now using the present continuous.",
        "I can explain my future plans using 'going to' and 'will'.",
        "I can take stock of my strengths and areas for improvement.",
        "I know the words: progress, milestone, confidence, fluency, comfort zone, keep up with, strength, breakthrough, take stock, self-assessment.",
    ],
    'badge_name': 'Midpoint Badge',
    'badge_p': 'You can see how far you have come -- and speak about your whole journey with confidence, Andrea.',
    'next_lesson': 'Talking Prices, Packages, and Deals',

    'preclass_title': 'Midpoint Review -- How Far Have You Come?',
    'preclass_desc': "A midpoint review of your English journey. Key words: progress, milestone, confidence, fluency, comfort zone, to keep up with, strength, area for improvement, breakthrough, to take stock, self-assessment, halfway point. Structures: past simple, present continuous, and future forms (going to / will) used together to describe your journey.",
    'context': ("Today is a special class: the <strong>halfway point</strong> of the program. Andrea decides to <strong>take "
                "stock</strong>. Six months ago, she <strong>started</strong> the course and could barely speak in a meeting. "
                "Right now, she <strong>is improving</strong> her <strong>fluency</strong> every week and can <strong>keep up "
                "with</strong> fast speakers. Her <strong>confidence</strong> has grown, and small talk is now a real "
                "<strong>strength</strong>. She still has one <strong>area for improvement</strong>: pronunciation. But she can "
                "see clear <strong>progress</strong> and a real <strong>breakthrough</strong>. Next month, she <strong>is going "
                "to</strong> present Escape Turismo at a fair in Berlin, all in English."),
    'context_quiz': [
        ("1. 'Six months ago, she started the course' uses the past simple because:",
         [("A", "it describes a finished action in the past.", True),
          ("B", "it is happening right now.", False),
          ("C", "it is a future plan.", False)]),
        ("2. 'Right now, she is improving her fluency' is in the present continuous because:",
         [("A", "it is a finished past action.", False),
          ("B", "it describes something in progress now.", True),
          ("C", "it is a prediction.", False)]),
        ("3. Which sentence correctly talks about a future plan?",
         [("A", "Next month, she is going to present in Berlin.", True),
          ("B", "Next month, she presented in Berlin.", False),
          ("C", "Next month, she is present in Berlin.", False)]),
    ],
    'tip_title': 'Past, Present, and Future Together',
    'tip_sub': "Como falar do passado, do presente e do futuro na mesma conversa (explicação em inglês e português).",
    'tip_rows': [
        ("Past simple", "Ação terminada no passado. A finished past action.", "Six months ago, I <strong>started</strong>."),
        ("Present continuous", "Ação em progresso agora. An action in progress now.", "Right now, I <strong>am improving</strong>."),
        ("going to / will", "Plano ou previsão para o futuro. A plan or prediction.", "Next month, I <strong>am going to</strong> present."),
        ("Regra de ouro / Golden rule", "A palavra de tempo escolhe o tempo verbal: 'ago' -> passado; 'right now' -> presente contínuo; 'next' -> futuro.", "ago -> started; now -> am improving; next -> am going to"),
    ],
    'fill': [
        ('"Six months ago, I ', "started", "Dica: passado simples de 'start'", "Six months ago, I started this program.", ' this program."'),
        ('"Right now, I ', "am", "Dica: presente contínuo, 'am improving'", "Right now, I am improving my fluency.", ' improving my fluency."'),
        ('"Next month, I am ', "going", "Dica: plano futuro, 'am going to'", "Next month, I am going to present at a fair.", ' to present at a fair."'),
        ('"I can see real ', "progress", "Dica: melhora ao longo do tempo", "I can see real progress this year.", ' this year."'),
        ('"It is a good moment to take ', "stock", "Dica: fazer um balanço, 'take stock'", "It is a good moment to take stock.", '."'),
        ('"My main ', "strength", "Dica: ponto forte", "My main strength is small talk.", ' is small talk."'),
    ],
    'order_intro': "Coloque os passos de uma boa autoavaliação na ordem correta.",
    'order': [
        "Look back: say where you started.",
        "Describe what you are working on right now.",
        "Name one clear strength.",
        "Name one area for improvement.",
        "Share your plan for the future.",
    ],
    'speech': [
        ("Six months ago, I could not speak in meetings.", "Há seis meses, eu não conseguia falar em reuniões."),
        ("Right now, I am improving my fluency.", "Agora, estou melhorando minha fluência."),
        ("I have made real progress this year.", "Eu fiz um progresso real este ano."),
        ("My main area for improvement is pronunciation.", "Meu principal ponto a melhorar é a pronúncia."),
        ("Next month, I am going to present at a fair.", "No próximo mês, vou apresentar em uma feira."),
    ],
    'quiz': [
        ("You want to describe a finished past action. You say:",
         [("A", "Six months ago, I started this course.", True),
          ("B", "Six months ago, I am starting this course.", False),
          ("C", "Six months ago, I start this course.", False)]),
        ("You want to describe what you are doing now. You say:",
         [("A", "Right now, I improve my fluency.", False),
          ("B", "Right now, I am improving my fluency.", True),
          ("C", "Right now, I improved my fluency.", False)]),
        ("You want to talk about a future plan. You say:",
         [("A", "Next month, I am going to present in Berlin.", True),
          ("B", "Next month, I present in Berlin yesterday.", False),
          ("C", "Next month, I am present in Berlin.", False)]),
        ("You want to take stock honestly. You say:",
         [("A", "My strength is small talk, and my area for improvement is pronunciation.", True),
          ("B", "My strength small talk, my improvement pronunciation.", False),
          ("C", "I am strength small talk.", False)]),
    ],
    'think': "Take stock of your English journey. Record a short reflection: what could you not do six months ago, what are you working on right now, and what are you going to do in the second half of the program? Use past, present, and future. Take your time.",

    'media': [
        ('series', 'The Last Dance -- Episode 1 (Netflix)',
         'A documentary about looking back on a long journey and taking stock of progress, milestones, and setbacks at the highest level. Watch how the athletes and coaches reflect on the past, the present, and what is coming next. Connection to Lesson 8: describing a journey using past, present, and future.',
         'Tip: watch with English subtitles. Note 3 sentences that talk about the past and 3 that talk about future plans.',
         'https://www.netflix.com/title/80203144'),
        ('podcast', '6 Minute English -- "Talking About Progress and Goals" (BBC)',
         'A short, learner-friendly podcast where the hosts discuss progress, motivation, and setting goals. Perfect for hearing the past, present, and future tenses used naturally together. Connection to Lesson 8: the language of self-assessment and your journey.',
         'Tip: listen twice. Write down one sentence about the past, one about the present, and one about the future.',
         'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'),
        ('youtube', '"Past, Present and Future -- English Tenses Review" -- BBC Learning English',
         'A clear review of the exact grammar of this lesson: past simple for finished actions, present continuous for now, and going to / will for the future. Connection to Lesson 8: telling your story across all three time frames.',
         'Tip: pause after each example and make your own sentence about your English journey in that tense.',
         'https://www.youtube.com/results?search_query=past+present+future+tenses+review+bbc+learning+english'),
    ],
}
