# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80"
BG5 = "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1400&q=80"
BG6 = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1400&q=80"

D = {
    'n': 18,
    'reading': True,
    'partner_name': 'oskar',
    'grammar_point_pt': "estruturas causativas (causative have / get): 'have + pessoa + verbo base' (I had her lead the call = fiz/pedi que ela liderasse) e 'get + pessoa + to + verbo' (I got him to take ownership = consegui que ele assumisse) para delegar a alguem; 'have / get + objeto + participio' (I had the report reviewed / I got the slides redesigned = mandei revisar / mandei redesenhar) para providenciar que algo seja feito por outra pessoa -- essenciais para delegar, empoderar e desenvolver a equipe",
    'chapter_tag': 'From Doing to Developing',
    'title_h1': 'Coaching and Developing Your <span class="accent">Team</span>',
    'title_sub': 'Stop doing everything yourself. Delegate, empower, and get the work done through the people you are growing.',
    'short_title': 'Developing Your Team',
    'menu_title': 'Coaching and Developing Your Team',
    'menu_desc': 'Delegate and empower your team using causative have and get',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=600&q=80",
    'stamp_label': 'Team Developer',
    'stamp_img': "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&q=80",
    'phases': ['From Doing to Developing', 'Coaching Words', 'The Delegation',
               'Have &amp; Get Done', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From the Feedback to the <span class="accent">Growth</span>',
    'warm_p': "Last time you gave feedback that was candid, kind, and clear -- praising one strength and pinpointing one thing to change. But feedback is only the start. The real job of a leader is not to do everything herself; it is to develop the people who will. Today you step back from the doing and into the coaching. You will delegate a real responsibility, empower a colleague to own it, and get the work done through someone you are growing -- even if that means letting them make a small mistake along the way. By the end of this hour, you will coach and develop your team with confidence.",
    'warm_prompt': 'In one sentence: what is one task you still do yourself that someone on your team could grow by owning?',
    'missions': [
        'Learn the language of delegation, ownership, and developing people.',
        'Use causative have and get -- have her lead, get him to own it, have the report reviewed.',
        'Coach a colleague to take on a real responsibility, hands-off but supported.',
    ],

    'vocab_trans_h2': 'Words for <span class="accent">Coaching</span>',
    'vocab': [
        ("To delegate", "to give a task or responsibility to someone else (delegar)", "A good leader learns to delegate, not to do it all."),
        ("To empower", "to give someone the authority and confidence to act (empoderar, dar autonomia)", "I want to empower my team to make their own calls."),
        ("To mentor", "to guide and advise a less experienced colleague (orientar, ser mentor de)", "She mentored me through my first big negotiation."),
        ("Ownership", "the feeling of being responsible for a task or result (senso de dono, responsabilidade)", "Give people ownership and they rise to it."),
        ("Potential", "ability that has not yet been fully developed (potencial)", "He has the potential to lead the whole account."),
        ("To nurture", "to care for someone and help them grow (cultivar, desenvolver)", "You nurture talent by trusting it with real work."),
        ("Hands-off", "giving people freedom to work without close control (nao intervencionista)", "My style is hands-off once I trust the person."),
        ("To step up", "to take on more responsibility when it is needed (assumir o desafio, dar um passo a frente)", "She stepped up the moment I gave her the chance."),
        ("Accountability", "being responsible for results and answerable for them (responsabilizacao, prestacao de contas)", "Ownership means accountability, not just credit."),
        ("To micromanage", "to control every small detail of someone's work (microgerenciar)", "If you micromanage, people never learn."),
        ("Autonomy", "the freedom to make your own decisions (autonomia)", "Autonomy is how people grow into leaders."),
        ("Learning curve", "how quickly someone must learn something new (curva de aprendizado)", "It's a steep learning curve, but I'll support him."),
    ],

    'gram_trans_h2': 'Get It Done Through <span class="accent">Others</span>',
    'gram_trans_sub': 'have + person + verb &middot; get + person + to + verb &middot; have / get + object + past participle',
    'gram_examples': [
        ("", "This quarter, I'm going to have Oskar lead the negotiations.", '"This quarter, I\'m going to <span class="accent" style="font-weight:700">have Oskar lead</span> the negotiations."'),
        ("", "I got him to take ownership of the whole account.", '"I <span class="accent" style="font-weight:700">got him to take</span> ownership of the whole account."'),
        ("", "I had the rate sheets reviewed before the meeting.", '"I <span style="color:#15803d;font-weight:700">had the rate sheets reviewed</span> before the meeting."'),
    ],
    'gram_disc_q': 'In none of these does the speaker do the action herself -- she causes someone else to do it. Two sentences are about a PERSON doing something; one is about a THING being done. How does the verb form change between them?',
    'gram_table': [
        ("have + person + base verb", "delegate: arrange for someone to do something", "I <strong>had her present</strong> the results."),
        ("get + person + to + verb", "persuade or arrange for someone to do it", "I <strong>got him to take</strong> ownership."),
        ("have / get + object + past participle", "arrange for something to be done (by someone else)", "I <strong>had the report reviewed</strong>. / I <strong>got the slides redesigned</strong>."),
    ],
    'gram_rule_foot': "Causatives let you talk about getting things done through other people. For a PERSON doing something, use 'have + person + base verb' or 'get + person + to + verb'. For a THING that is done for you, use 'have / get + object + past participle'. Notice: 'have' takes no 'to' before the person's verb, but 'get' does. This is the grammar of delegation.",

    'lf_h2': 'Delegate the <span class="accent">Work</span>',
    'lf_title': 'Read each line and complete the causative structure',
    'lf_items': [
        ["A", "", "I had Oskar lead", " the supplier call this week.", "strong"],
        ["B", "", "I got the team to take", " ownership of the numbers.", "strong"],
        ["C", "", "I had the proposal reviewed", " before I sent it out.", "soft"],
        ["D", "", "I'll get the slides redesigned", " by the marketing team.", "soft"],
    ],
    'lf_followup': "'Have + person + base verb' and 'get + person + to + verb' delegate a task to a person; 'have / get + object + past participle' arranges for a thing to be done. Remember: 'have' = no 'to', 'get' = 'to' before the person's verb.",

    'mistakes': [
        ("I had her to present the results.", 'I had her <strong>present</strong> the results.'),
        ("I had the report review before the meeting.", 'I had the report <strong>reviewed</strong> before the meeting.'),
    ],
    'mistake_note': "With 'have + person', use the base verb and NO 'to': 'I had her present', not 'I had her to present'. When the object is a THING that is done for you, use the past participle: 'I had the report reviewed', not 'I had the report review'. (Only 'get + person' takes 'to': 'I got her to present'.)",

    'read_trans_h2': 'Read the <span class="accent">Delegation</span>',
    'reading_h2': 'The Leader Who Does <span class="accent">Less</span>',
    'read_block': {
        'rtitle': 'The Leader Who Does Less',
        'paras': [
            "There is a moment in every manager's career when doing more stops working. You are good at the job -- that is why you were promoted -- so your instinct is to keep doing it, only faster and for longer. But a team does not grow around a leader who does everything. It grows around a leader who does less, and develops the people who do the rest. The shift from doing to developing is the hardest one most managers ever make, because it means letting go of the very work that made you successful.",
            "The tool for that shift is delegation, and delegation is not dumping. When you delegate well, you give a person real ownership, not just a task -- you have them run the process, you get them to make the decisions, and you stay hands-off enough that they feel the weight of it. You will be tempted to micromanage, to hover, to fix every small thing. Resist. Autonomy is uncomfortable, but it is the only thing that turns potential into skill. The people you nurture with real responsibility are the ones who step up when it matters.",
            "None of this means abandoning them. A good coach mentors from beside, not above: available for the hard questions, clear about accountability, and honest that there will be a learning curve. You had the junior lead the call; it did not go perfectly; you debrief and go again. That is not a failure of delegation -- it is delegation working. The leaders who build the strongest teams are simply the ones who were brave enough to get the work done through others, and patient enough to let those others learn.",
        ],
        'source': 'Adapted from a leadership development guide',
        'link': 'https://podcasts.apple.com/us/podcast/coaching-for-leaders/id458827716',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "A good leader grows a team by doing all the important work personally and quickly.", False],
            ["b", "Teams grow when a leader shifts from doing to developing -- delegating real ownership, staying hands-off, and coaching through the learning curve.", True],
            ["c", "Delegation means giving people tasks but keeping all the decisions and control yourself.", False],
        ],
        'tf': [
            ["The text says the shift from doing to developing is easy for most managers.", "f", "It calls it the hardest shift most managers ever make, because it means letting go of the work that made them successful."],
            ["According to the text, delegating well means giving real ownership, not just a task.", "t", "The second paragraph says delegation is not dumping -- you give a person real ownership, have them run the process, and stay hands-off."],
            ["The text recommends micromanaging to make sure delegation succeeds.", "f", "It says resist the temptation to micromanage; autonomy is what turns potential into skill."],
            ["The text says a call that does not go perfectly can still mean delegation is working.", "t", "The last paragraph says you debrief and go again -- that is not a failure of delegation, it is delegation working."],
        ],
    },

    'dialogue_h2': 'Andrea Coaches <span class="accent">Oskar</span> to Step Up',
    'dialogue': [
        ('oskar', 'arthur', "You wanted to talk about the supplier negotiations this quarter?",
         "You wanted to talk about the supplier negotiations this quarter?"),
        ('andrea', 'ellen', "I did. This time, I'm not going to lead them. I'm going to have you run the whole process.",
         "I did. This time, I'm not going to lead them. I'm going to <span class=\"vocab-highlight\">have</span> you run the whole process."),
        ('oskar', 'arthur', "Me? I've sat in on them, but I've never led one myself. That's a steep learning curve.",
         "Me? I've sat in on them, but I've never led one myself. That's a steep <span class=\"vocab-highlight\">learning curve</span>."),
        ('andrea', 'ellen', "That's exactly why. You have the potential; you just need the ownership. I'll mentor you, but I'll stay hands-off.",
         "That's exactly why. You have the <span class=\"vocab-highlight\">potential</span>; you just need the <span class=\"vocab-highlight\">ownership</span>. I'll <span class=\"vocab-highlight\">mentor</span> you, but I'll stay <span class=\"vocab-highlight\">hands-off</span>."),
        ('oskar', 'arthur', "What if I get a rate wrong? These deals are big.",
         "What if I get a rate wrong? These deals are big."),
        ('andrea', 'ellen', "Then we fix it together. I'd rather get you to make one small mistake now than micromanage you forever. Autonomy is how you grow.",
         "Then we fix it together. I'd rather <span class=\"vocab-highlight\">get</span> you to make one small mistake now than <span class=\"vocab-highlight\">micromanage</span> you forever. <span class=\"vocab-highlight\">Autonomy</span> is how you grow."),
        ('oskar', 'arthur', "Okay, I'll take it on. Could you have the last rate sheets sent to me so I can prepare?",
         "Okay, I'll take it on. Could you <span class=\"vocab-highlight\">have</span> the last rate sheets sent to me so I can prepare?"),
        ('andrea', 'ellen', "Already done -- I had them forwarded this morning. Step up, and I'll be right behind you.",
         "Already done -- I had them forwarded this morning. <span class=\"vocab-highlight\">Step up</span>, and I'll be right behind you."),
    ],
    'comprehension': [
        ("1. What experience does Oskar have with the supplier negotiations?", "He has sat in on them, but he has never led one himself."),
        ("2. What is Oskar worried about?", "Getting a rate wrong, because the deals are big."),
        ("3. What does Oskar ask Andrea to have sent to him?", "The last rate sheets, so he can prepare."),
    ],

    'listen1_h2': 'The <span class="accent">Delegation Talk</span>',
    'listen1_sub': 'A director explains how she develops her team. Sound first -- no text.',
    'listen1_qs': [
        ("1. What does the director say she used to do that no longer works?", "Do everything herself, only faster."),
        ("2. What does she now have her team do?", "Run the processes and make the decisions themselves -- she gives them ownership."),
        ("3. How does she respond when a delegated task does not go perfectly?", "They debrief and go again -- she treats it as delegation working, not failing."),
    ],
    'listen2_h2': 'Have and Get <span class="accent">Something Done</span>',
    'listen2_sub': 'A short tip on the causative structures. Sound first -- no text.',
    'listen2_qs': [
        ("1. After 'have + a person', which verb form do you use?", "The base verb, with no 'to' -- 'I had her present'."),
        ("2. What does 'get + person' need that 'have + person' does not?", "The word 'to' -- 'I got her to present'."),
        ("3. Which form do you use for a thing that is done for you?", "Have or get + object + past participle -- 'I had the report reviewed'."),
    ],
    'listenings': [
        {'file': 'a18_listening_delegation.mp3', 'voice': 'arthur',
         'text': "When I was first promoted, I did what most new managers do. I kept doing the work myself, only faster, because I was good at it. And for a while it looked like it was working. But my team wasn't growing, and I was exhausted. The change came when I stopped doing and started developing. Now, instead of leading every negotiation, I have my best people run them. I get them to make the real decisions, not just carry my bag. I give them ownership, and yes, I stay hands-off, even when it's uncomfortable. Of course they make mistakes. Last month I had a junior lead a supplier call, and it didn't go perfectly. So we debriefed, and this week she's leading it again. People think that's a failure of delegation. It isn't. That is delegation working. The strongest teams are built by leaders who are brave enough to get the work done through others, and patient enough to let them learn."},
        {'file': 'a18_listening_causativetip.mp3', 'voice': 'ellen',
         'text': "Welcome to this short segment on the causative, the grammar of getting things done through other people. There are two situations to keep apart. First, when a person does something for you. Use have plus the person plus the base verb, with no to. I had her present the results. Or use get plus the person plus to plus the verb. I got him to take ownership. Same idea, but get needs the little word to, and have does not. Second, when a thing is done for you, and it doesn't matter who does it. Use have or get plus the object plus the past participle. I had the report reviewed. I got the slides redesigned. The trick is to notice whether you are talking about a person doing something or a thing being done, and then choose the right form. Master this, and you can talk about delegation like a leader."},
    ],

    'gapfill_parts': [
        "Andrea coaches Oskar to step up. This quarter she will not lead the negotiations herself -- she will ",
        ["1"], " Oskar run the whole process, to give him real ",
        ["2"], ". She promises to mentor him but stay ",
        ["3"], ", because she would rather ",
        ["4"], " him make a small mistake than micromanage him. To help him prepare, she ",
        ["5"], " the rate sheets forwarded to him that morning.",
    ],
    'gapfill_bank': ["have", "ownership", "hands-off", "get", "had"],
    'vocabnote': "Causative forms: 'have + person + base verb' ('have Oskar run it') and 'get + person + to + verb' ('get him to make the call') delegate to a person; 'have / get + object + past participle' ('had the sheets forwarded') arranges for a thing to be done. 'have' takes no 'to'; 'get + person' does.",

    'bank_label_top': 'The Delegation',
    'bank_label': 'Useful language for coaching and delegating',
    'bank_items': [
        "This time, I'm going to have you run the whole process.",
        "I want to get you to take ownership of this.",
        "I'll mentor you, but I'll stay hands-off.",
        "You have the potential; you just need the reps.",
        "I'd rather you learn than have me micromanage you.",
        "I had the rate sheets forwarded to you this morning.",
        "Autonomy is how you grow into the role.",
        "Step up on this one, and I'll be right behind you.",
    ],

    'scenarios_h2': 'Coach the <span class="accent">Handover</span>',
    'scenario_items': [
        ["Scenario 1", "Delegate a task to a team member using 'have + person + verb' (e.g. 'I'll have you lead...')."],
        ["Scenario 2", "Empower someone to own a decision, using 'get + person + to + verb'."],
        ["Scenario 3", "Arrange for a document to be prepared by someone else, using 'have / get + object + past participle'."],
        ["Scenario 4", "A colleague is nervous about a stretch task. Coach them: name their potential, promise support, and stay hands-off."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = have, 2 = ownership, 3 = hands-off, 4 = get, 5 = had.",
        "Delegate to a person: 'I'm going to have you run the process.'",
        "Empower with get: 'I want to get you to take ownership.'",
        "Thing done for you: 'I had the rate sheets forwarded.'",
    ],
    'answerkey_note': "have + person + base verb (no 'to'); get + person + to + verb; have / get + object + past participle for a thing done for you.",

    'roleplays': [
        {'h2': 'The <span class="accent">Handover</span>',
         'scenario': "Hand a real responsibility to a team member. Use 'I'm going to have you...' to delegate it, and explain what ownership they will have.",
         'keywords': ["I'm going to have you...", "you'll own...", "I'll stay hands-off"]},
        {'h2': 'The <span class="accent">Nudge</span>',
         'scenario': "A colleague has the potential but is hesitating. Use 'get + person + to + verb' to encourage them to take the lead, and arrange for something to be prepared for them ('I'll have it sent to you').",
         'keywords': ["I want to get you to...", "I'll have the... sent", "you've got this"]},
        {'h2': 'The Coaching <span class="accent">Debrief</span>',
         'scenario': "A delegated task did not go perfectly. Debrief a team member: acknowledge the learning curve, keep them accountable, and set them up to lead it again -- all without micromanaging.",
         'keywords': []},
    ],

    'survival_h2': 'Delegate Like a <span class="accent">Leader</span>',
    'survival': [
        ("I'm going to have you run the whole process.", "Vou fazer voce conduzir todo o processo."),
        ("I want to get you to take ownership of this.", "Quero que voce assuma a responsabilidade por isto."),
        ("I'll mentor you, but I'll stay hands-off.", "Vou te orientar, mas nao vou interferir."),
        ("I had the rate sheets forwarded to you.", "Mandei encaminhar as tabelas de tarifas para voce."),
        ("Step up on this one, and I'll be right behind you.", "Assuma este desafio, e estarei logo atras de voce."),
    ],
    'learned': [
        "I can delegate a task to a person with 'have + person + base verb' (no 'to').",
        "I can empower someone with 'get + person + to + verb'.",
        "I can arrange for a thing to be done with 'have / get + object + past participle'.",
        "I can coach a colleague to take ownership -- giving autonomy while staying supportive.",
        "I know the words: to delegate, to empower, to mentor, ownership, potential, to nurture, hands-off, to step up, accountability, to micromanage, autonomy, learning curve.",
    ],
    'badge_name': 'Team Developer Badge',
    'badge_p': 'You can coach and develop your team -- delegating real ownership and getting the work done through the people you are growing, Andrea.',
    'next_lesson': 'Handling High-Stakes Conversations',

    # ----- new B2 slides (pipeline v2) -----
    'spot_errors': [
        ("I had her to present the results.", "I had her present the results."),
        ("I had the report review before the meeting.", "I had the report reviewed before the meeting."),
        ("I got him take ownership of the account.", "I got him to take ownership of the account."),
        ("I'll get the slides redesign by marketing.", "I'll get the slides redesigned by marketing."),
    ],
    'bridge5': {
        'h2': 'Voices on <span class="accent">Delegation</span>',
        'sub': 'Listen to a director develop her team, then coach a handover out loud.',
        'bg': BG5,
    },
    'register': [
        ("Just do it the way I told you.", "I'm going to have you run this your way -- I'll stay hands-off and mentor if you need me."),
        ("You're not ready to lead this.", "It's a steep learning curve, but you have the potential; I'll get you the support to step up."),
        ("Send me everything so I can check it all.", "Take ownership of it -- I'd rather trust you than micromanage every detail."),
        ("I'll just fix the slides myself.", "I'll have the slides redesigned by marketing, so you can focus on the negotiation."),
    ],
    'artifact': {
        'label': 'The Development Plan',
        'h2': 'Team Development <span class="accent">Plan</span>',
        'meta': [
            ("For:", "Oskar -- Account Executive"),
            ("Coach:", "Andrea Aggio -- Commercial Director"),
            ("Goal:", "Grow into lead on supplier negotiations this quarter"),
        ],
        'paras': [
            "The stretch: this quarter, I will have Oskar lead the full supplier negotiation, end to end. He has sat in before but never led, so this is real ownership, not a rehearsal.",
            "My role: I'll mentor from beside, not above -- available for the hard questions, hands-off on the day-to-day. I've had the last rate sheets forwarded to him, and I'll get the finance team to review his final numbers before he signs anything.",
            "Accountability: Oskar owns the outcome and answers for it, good or bad. We expect a learning curve, and a small mistake is fine. We debrief after each round and adjust. The aim is not a perfect quarter; it is a leader who can do this without me next time.",
        ],
    },
    'artifact_qs': [
        ("1. According to the plan, what will Andrea have Oskar do this quarter?", "Lead the full supplier negotiation, end to end."),
        ("2. What has Andrea already had forwarded to Oskar?", "The last rate sheets."),
        ("3. Who will Andrea get to review Oskar's final numbers before he signs?", "The finance team."),
    ],
    'pron_lines': [
        ("I'm going to have you run it.", "'have you' links -- ha-vyoo; 'going to' reduces to gonna in speech; stress RUN."),
        ("I got him to take ownership.", "'got him to' links -- go-tim-tuh; stress OWNERSHIP."),
        ("I had the report reviewed.", "'had the' links -- had-thuh; stress reVIEWED, the past participle."),
        ("I'll have the sheets forwarded.", "'have the' links -- hav-thuh; light stress on FORwarded."),
    ],
    'bridge6': {
        'h2': 'Now You <span class="accent">Delegate</span>',
        'sub': 'Your turn: hand over a real task and coach someone to own it.',
        'bg': BG6,
    },
    'quickfire': [
        {'situation': "Delegate the client call to a team member.",
         'tips': ["Use 'have + person + base verb'.", "'I'll have you lead the call.'", "No 'to' after 'have'."]},
        {'situation': "Encourage a hesitant colleague to take the decision.",
         'tips': ["Use 'get + person + to + verb'.", "'I want to get you to decide this.'", "'get' needs 'to'."]},
        {'situation': "Arrange for a proposal to be reviewed by someone else.",
         'tips': ["Use 'have/get + object + past participle'.", "'I'll have the proposal reviewed.'", "Object, then past participle."]},
        {'situation': "A colleague fears a stretch task. Reassure and empower them.",
         'tips': ["Name their potential.", "'I'll stay hands-off, but I've got you.'", "Offer support, not control."]},
        {'situation': "A delegated task went wrong. Coach, don't take it back.",
         'tips': ["'Let's debrief and go again.'", "Keep them accountable.", "Treat it as the learning curve."]},
    ],

    'preclass_title': 'Coaching and Developing Your Team',
    'preclass_desc': "How to delegate, empower, and develop your team using causative have and get. Key words: to delegate, to empower, to mentor, ownership, potential, to nurture, hands-off, to step up, accountability, to micromanage, autonomy, learning curve. Structure: have + person + base verb; get + person + to + verb; have / get + object + past participle.",
    'context': ("Andrea decides to <strong>delegate</strong> the supplier negotiations to Oskar. Instead of leading "
                "them herself, she will <strong>have</strong> him run the whole process, to give him real "
                "<strong>ownership</strong>. 'You have the <strong>potential</strong>,' she tells him, 'I just need to "
                "<strong>empower</strong> you to use it.' She promises to <strong>mentor</strong> him but stay "
                "<strong>hands-off</strong>: 'I'd rather <strong>get</strong> you to make one small mistake than "
                "<strong>micromanage</strong> you.' To help him prepare, she <strong>had</strong> the rate sheets "
                "forwarded that morning. Oskar knows it's a steep <strong>learning curve</strong>, but with "
                "<strong>autonomy</strong> and support, he's ready to <strong>step up</strong>."),
    'context_quiz': [
        ("1. In 'I'll have you run the process', the verb after 'have you' is:",
         [("A", "the base verb (run), with no 'to'.", True),
          ("B", "the past participle (run/ran).", False),
          ("C", "'to run'.", False)]),
        ("2. Which sentence uses the causative for a THING done for you?",
         [("A", "I had the rate sheets forwarded.", True),
          ("B", "I had him lead the call.", False),
          ("C", "I got her to sign it.", False)]),
        ("3. Which sentence is correct?",
         [("A", "I got him to take ownership.", True),
          ("B", "I got him take ownership.", False),
          ("C", "I had him to take ownership.", False)]),
    ],
    'tip_title': 'Causative: Have &amp; Get',
    'tip_sub': "Como falar de mandar/fazer alguem fazer algo, e providenciar que algo seja feito (em ingles e portugues).",
    'tip_rows': [
        ("have + person + base verb", "delegar a alguem (sem 'to'). delegate to a person (no 'to').", "I <strong>had her present</strong> it."),
        ("get + person + to + verb", "convencer/pedir a alguem (com 'to'). persuade a person (with 'to').", "I <strong>got him to lead</strong> it."),
        ("have / get + object + participio", "providenciar que algo seja feito. arrange for a thing to be done.", "I <strong>had the report reviewed</strong>."),
        ("Regra de ouro / Golden rule", "'have' nao usa 'to' antes da pessoa; 'get' usa. have = no 'to'; get = 'to'.", "have her <strong>go</strong> / get her <strong>to go</strong>."),
    ],
    'fill': [
        ('"This quarter, I''ll have you ', "run", "Dica: verbo base apos 'have + pessoa' (sem 'to')", "This quarter, I'll have you run the whole process.", ' the whole process."'),
        ('"I want to get you ', "to take", "Dica: 'get + pessoa' precisa de 'to' + verbo", "I want to get you to take ownership of this.", ' ownership of this."'),
        ('"I had the rate sheets ', "forwarded", "Dica: participio -- algo feito por outra pessoa", "I had the rate sheets forwarded this morning.", ' this morning."'),
        ('"A good leader learns to ', "delegate", "Dica: passar tarefa/responsabilidade a alguem", "A good leader learns to delegate.", '."'),
        ('"I''ll stay ', "hands-off", "Dica: dar liberdade sem controlar de perto", "I'll mentor you, but I'll stay hands-off.", ' and let you decide."'),
        ('"Give people ', "ownership", "Dica: o senso de ser dono/responsavel pela tarefa", "Give people ownership and they rise to it.", ' and they rise to it."'),
    ],
    'order_intro': "Coloque os passos de uma boa delegacao na ordem correta.",
    'order': [
        "Choose a task that will stretch and grow the person.",
        "Hand over real ownership, not just the task.",
        "Have them run the process and make the decisions.",
        "Stay hands-off, but be available for the hard questions.",
        "Debrief the learning curve and set them up to do it again.",
    ],
    'speech': [
        ("I'm going to have you run the whole process.", "Vou fazer voce conduzir todo o processo."),
        ("I want to get you to take ownership of this.", "Quero que voce assuma a responsabilidade por isto."),
        ("I had the rate sheets forwarded to you.", "Mandei encaminhar as tabelas de tarifas para voce."),
        ("I'll mentor you, but I'll stay hands-off.", "Vou te orientar, mas nao vou interferir."),
        ("Step up on this one, and I'll be right behind you.", "Assuma este desafio, e estarei logo atras de voce."),
    ],
    'quiz': [
        ("You delegate a task to a person on your team. You say:",
         [("A", "I'll have you lead the call.", True),
          ("B", "I'll have you to lead the call.", False),
          ("C", "I'll have you led the call.", False)]),
        ("You persuade a colleague to take a decision. You say:",
         [("A", "I want to get you to decide this.", True),
          ("B", "I want to get you decide this.", False),
          ("C", "I want to have you to decide this.", False)]),
        ("You arrange for a report to be reviewed by someone else. You say:",
         [("A", "I'll have the report reviewed.", True),
          ("B", "I'll have the report review.", False),
          ("C", "I'll have reviewed the report.", False)]),
        ("You describe controlling every small detail of someone's work. You call it:",
         [("A", "to micromanage.", True),
          ("B", "to empower.", False),
          ("C", "to delegate.", False)]),
    ],
    'think': "Imagine there is one responsibility you currently handle yourself at Escape Turismo that a member of your team could grow into -- a negotiation, a client account, a report. Record a one-minute coaching plan. Say who you will have take it on, using 'have + person + verb'; how you will empower them with 'get + person + to + verb'; and one thing you will have done for them ('have / get + object + past participle'). Explain how you'll stay hands-off but supportive. Take your time.",

    'media': [
        ('series', "The Office (U.S., NBC)",
         "A mockumentary about a paper-company branch and its well-meaning but often terrible manager. It is a masterclass -- by counter-example -- in micromanaging, false empowerment, and how NOT to delegate, alongside genuine moments of mentoring and people stepping up. Natural workplace English throughout. Connection to Lesson 18: coaching, delegating, and developing a team.",
         'Tip: pick a scene where Michael delegates something and note whether he truly gives ownership or just micromanages.',
         'https://www.imdb.com/title/tt0386676/'),
        ('podcast', 'Coaching for Leaders',
         "A long-running leadership podcast by Dr. Dave Stachowiak, focused on the exact skills of this lesson: delegating well, empowering people, giving autonomy, and developing a team. Practical, guest-driven, and rich in real management language. Connection to Lesson 18: coaching and developing your team.",
         'Tip: after an episode, write two delegation sentences -- one with have + person, one with get + person + to.',
         'https://podcasts.apple.com/us/podcast/coaching-for-leaders/id458827716'),
        ('youtube', '"HAVE/GET something DONE (Causatives)" -- English Grammar for B2 First',
         "A clear, B2-level lesson on the exact grammar of this class: causative have and get, including have/get something done. Connection to Lesson 18: 'I had the report reviewed' and 'I got him to take ownership'.",
         'Tip: after each example, build your own causative about delegating a task to your team.',
         'https://www.youtube.com/watch?v=uP3WhQejoxU'),
    ],
}
