# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80"

D = {
    'n': 9,
    'reading': True,
    'partner_name': 'miguel',
    'grammar_point_pt': "o primeiro condicional (first conditional): if + presente simples, will + verbo, para trocar uma condição por uma oferta",
    'chapter_tag': 'Prices & Deals',
    'title_h1': 'Talking Prices, Packages, and <span class="accent">Deals</span>',
    'title_sub': 'Quote a price, build a package, and close the deal with confidence.',
    'short_title': 'Prices, Packages & Deals',
    'menu_title': 'Talking Prices, Packages, and Deals',
    'menu_desc': 'Quote prices, build packages, and negotiate deals using the first conditional',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
    'stamp_label': 'Deal Maker',
    'stamp_img': "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=200&q=80",
    'phases': ['The Price Behind the Price', 'The Words of Money', 'The Deal in Writing',
               'The First Conditional', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From the Midpoint to the <span class="accent">Money Talk</span>',
    'warm_p': 'Last time you took stock at the halfway point and told your English story across past, present, and future. Today we talk numbers: prices, packages, and the deals that keep Escape Turismo growing.',
    'warm_prompt': 'In one sentence: when a client says your price is too high, what do you usually say?',
    'missions': [
        'Learn the words of prices, rates, and packages.',
        'Master the first conditional to trade a condition for an offer.',
        'Run a full price negotiation and close the deal in English.',
    ],

    'vocab_trans_h2': 'The Language of <span class="accent">Money</span>',
    'vocab': [
        ("Net rate", "the base price before any markup is added (tarifa líquida)", "The hotel gave me a good net rate."),
        ("Markup", "the extra amount added to the base price to make a profit (margem)", "We add a small markup to the net rate."),
        ("Group rate", "a special reduced price for a large number of people (tarifa de grupo)", "Can you offer a group rate for forty guests?"),
        ("Deposit", "money paid in advance to hold a booking (depósito, sinal)", "We ask for a twenty percent deposit."),
        ("Cancellation policy", "the rules for changing or cancelling a booking (política de cancelamento)", "What is your cancellation policy?"),
        ("Peak season", "the busiest and most expensive time of the year (alta temporada)", "Prices rise in peak season."),
        ("Low season", "the quietest and cheapest time of the year (baixa temporada)", "The same room costs less in the low season."),
        ("Package", "several services combined and sold at one price (pacote)", "This package includes hotel and transfers."),
        ("Surcharge", "an extra charge added to the basic price (taxa extra)", "A small surcharge applies at the weekend."),
        ("To quote", "to state the price for a service (cotar, orçar)", "Could you quote me a rate for October?"),
        ("Complimentary", "free, included at no extra cost (cortesia, grátis)", "Breakfast is complimentary."),
        ("Discount", "a reduction in the normal price (desconto)", "If you book early, I will offer a discount."),
    ],

    'gram_trans_h2': 'The First <span class="accent">Conditional</span>',
    'gram_trans_sub': 'if + present &middot; will + verb',
    'gram_examples': [
        ("", "If you book forty rooms, I will hold the rate.", '"If you <span style="color:#15803d;font-weight:700">book</span> forty rooms, I <span class="accent" style="font-weight:700">will hold</span> the rate."'),
        ("", "If you pay the deposit today, breakfast will be complimentary.", '"If you <span style="color:#15803d;font-weight:700">pay</span> the deposit today, breakfast <span class="accent" style="font-weight:700">will be</span> complimentary."'),
        ("", "If we travel in the low season, the price will drop.", '"If we <span style="color:#15803d;font-weight:700">travel</span> in the low season, the price <span class="accent" style="font-weight:700">will drop</span>."'),
    ],
    'gram_disc_q': 'Which part is the condition, and which part is the result? What tense follows "if"?',
    'gram_table': [
        ("If + present simple", "The condition -- what must happen first", "If you <strong>book</strong> early,"),
        ("will + verb", "The result -- what I promise", "I <strong>will</strong> give you a discount."),
        ("Never 'will' after if", "Keep the present simple in the if-part", "If you <strong>pay</strong> (not 'will pay')..."),
    ],
    'gram_rule_foot': "First conditional = a real future possibility. Structure: If + present simple, ... will + verb.",

    'lf_h2': 'Condition or <span class="accent">Result?</span>',
    'lf_title': 'Complete the first conditional',
    'lf_items': [
        ["A", "If you ", "book", " early, I will offer a discount.", "strong"],
        ["B", "If you confirm today, I ", "will hold", " the rate.", "soft"],
        ["C", "If you pay the deposit, breakfast ", "will be", " complimentary.", "soft"],
        ["D", "If we ", "travel", " in the low season, prices fall.", "strong"],
    ],
    'lf_followup': "The 'if' part uses the present simple (book, confirm, travel); the result part uses 'will' + verb (will hold, will be).",

    'mistakes': [
        ("If you will book early, I give you a discount.", 'If you <strong>book</strong> early, I <strong>will</strong> give you a discount.'),
        ("If you paid the deposit today, breakfast is complimentary.", 'If you <strong>pay</strong> the deposit today, breakfast <strong>will be</strong> complimentary.'),
    ],
    'mistake_note': "In the first conditional, never use 'will' after 'if'. Use the present simple in the 'if' part and 'will' in the result part.",

    'read_trans_h2': 'Read the <span class="accent">Deal</span>',
    'reading_h2': 'The Art of the <span class="accent">Deal</span>',
    'read_block': {
        'rtitle': 'The Art of the Deal in Tourism',
        'paras': [
            "In the travel business, a price is never just a number. Behind every quote there is a story. The hotel gives the travel company a net rate -- the base price. The company then adds a markup and sells it to the client at a higher, gross price. The difference is how the business survives. A good commercial director knows these numbers by heart and can build a package that is attractive to the client and still profitable for the company.",
            "Prices also change with the calendar. In peak season, when everyone wants to travel, hotels are full and rates rise; a small surcharge may even apply on busy weekends. In the low season, the same room can cost far less, and a smart buyer books early to lock in the best rate. This is why timing is everything: the same package can have two very different prices, depending only on the month.",
            "The real skill, though, is in the conversation. Experienced negotiators rarely give a discount for free. Instead, they trade: 'If you book forty rooms, I will hold the low-season rate.' 'If you pay the deposit today, breakfast will be complimentary.' This is the first conditional, and it is the natural language of every deal. It turns a flat price into a flexible agreement, and it leaves both sides feeling they have won.",
        ],
        'source': 'Adapted from a hospitality business guide, The Commercial Edge',
        'link': 'https://www.thecommercialedge.com',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "Hotel prices in tourism never change and are the same all year.", False],
            ["b", "In tourism, prices depend on markup and season, and negotiators use the first conditional to trade offers.", True],
            ["c", "Good negotiators always give discounts for free to keep clients happy.", False],
        ],
        'tf': [
            ["The net rate is the base price the hotel gives the travel company.", "t", "The first paragraph says the hotel gives the company a net rate -- the base price."],
            ["Prices in tourism stay the same in every season.", "f", "In peak season rates rise; in the low season the same room can cost far less."],
            ["Experienced negotiators often give discounts for free.", "f", "The text says they rarely give a discount for free; instead they trade a condition for an offer."],
            ["'If you book forty rooms, I will hold the rate' is an example of the first conditional.", "t", "The third paragraph gives this exact sentence as an example of the first conditional."],
        ],
    },

    'dialogue_h2': 'Negotiating a <span class="accent">Group Rate</span>',
    'dialogue': [
        ('miguel', 'arthur', "Hi Andrea, thanks for the proposal. Could you quote me a group rate for forty guests in October?",
         "Hi Andrea, thanks for the proposal. Could you <span class=\"vocab-highlight\">quote</span> me a <span class=\"vocab-highlight\">group rate</span> for forty guests in October?"),
        ('andrea', 'ellen', "Of course, Miguel. If you confirm forty guests, I will give you our best net rate.",
         "Of course, Miguel. If you confirm forty guests, I will give you our best <span class=\"vocab-highlight\">net rate</span>."),
        ('miguel', 'arthur', "That sounds fair. And what happens if we need to cancel some rooms?",
         "That sounds fair. And what happens if we need to cancel some rooms?"),
        ('andrea', 'ellen', "If you cancel thirty days before arrival, there will be no surcharge at all.",
         "If you cancel thirty days before arrival, there will be no <span class=\"vocab-highlight\">surcharge</span> at all."),
        ('miguel', 'arthur', "Good to know. October is peak season, so I expected a higher price.",
         "Good to know. October is <span class=\"vocab-highlight\">peak season</span>, so I expected a higher price."),
        ('andrea', 'ellen', "If you book before the end of the month, I will hold the low-season rate for you.",
         "If you book before the end of the month, I will hold the <span class=\"vocab-highlight\">low season</span> rate for you."),
        ('miguel', 'arthur', "Excellent. And is breakfast included in the package?",
         "Excellent. And is breakfast included in the <span class=\"vocab-highlight\">package</span>?"),
        ('andrea', 'ellen', "Yes, breakfast is complimentary. If you sign today, I will add a welcome dinner for your group.",
         "Yes, breakfast is <span class=\"vocab-highlight\">complimentary</span>. If you sign today, I will add a welcome dinner for your group."),
    ],
    'comprehension': [
        ("1. What does Miguel ask Andrea to quote?", "A group rate for forty guests in October."),
        ("2. Why did Miguel expect a higher price?", "Because October is peak season."),
        ("3. What does Andrea offer if Miguel signs today?", "A welcome dinner for his group."),
    ],

    'listen1_h2': 'A Voicemail from the <span class="accent">Hotel</span>',
    'listen1_sub': 'A supplier explains his group rates. Sound first -- no text.',
    'listen1_qs': [
        ("1. How many rooms must you book to get the best net rate?", "More than thirty rooms."),
        ("2. When does the weekend surcharge disappear?", "In the low season."),
        ("3. What is the cancellation policy?", "If you cancel thirty days in advance, you pay nothing."),
    ],
    'listen2_h2': 'The Rule of Smart <span class="accent">Negotiating</span>',
    'listen2_sub': 'A short business tip on trading conditions. Sound first -- no text.',
    'listen2_qs': [
        ("1. What should you never do, according to the speaker?", "Give a discount for nothing."),
        ("2. Which structure do we use to negotiate?", "The first conditional: if + present, will + verb."),
        ("3. What should you state first?", "Your condition, and then your offer."),
    ],
    'listenings': [
        {'file': 'a9_listening_miguel.mp3', 'voice': 'arthur',
         'text': "Hi Andrea, this is Miguel from the Grand Coast Hotel. Thank you for your enquiry about our group rates for next season. Here is a quick summary. If you book more than thirty rooms, we will offer you our best net rate, with a ten percent markup instead of the usual fifteen. During peak season, a small surcharge applies at the weekend, but if you travel in the low season, that surcharge disappears completely. We ask for a twenty percent deposit to confirm any group, and our cancellation policy is flexible: if you cancel thirty days in advance, you pay nothing. Breakfast is always complimentary. Call me back and we will finalise the package."},
        {'file': 'a9_listening_tip.mp3', 'voice': 'ellen',
         'text': "Welcome to this short segment on smart negotiating. Here is one simple rule that every good salesperson knows: never give a discount for nothing. Always ask for something in return. In English, we do this with the first conditional. You say, if you book early, I will offer a better rate, or if you commit to thirty rooms, we will waive the surcharge. Notice the pattern: if plus the present simple for the condition, and will plus the verb for the result. This little structure protects your prices and makes the client feel they have earned the deal. So next time you talk numbers, remember: state your condition first, then your offer."},
    ],

    'gapfill_parts': [
        "A hotel gives the company a ", ["1"], " rate, and the company adds a ", ["2"],
        " before selling it. In ", ["3"], " season, prices rise and a ", ["4"],
        " may apply. A good negotiator uses the first conditional to ", ["5"], " an offer for a condition.",
    ],
    'gapfill_bank': ["net", "markup", "peak", "surcharge", "trade"],
    'vocabnote': "Remember the first conditional: 'if' + present simple (the condition), then 'will' + verb (the result). 'If you book early, I will offer a discount.'",

    'bank_label_top': 'Deal Talk',
    'bank_label': 'Useful language for prices and deals',
    'bank_items': [
        "Could you quote me a group rate?",
        "If you book early, I will offer a discount.",
        "The net rate is our base price.",
        "A small surcharge applies in peak season.",
        "We ask for a twenty percent deposit.",
        "Breakfast is complimentary.",
        "If you confirm today, I will hold this rate.",
        "What is your cancellation policy?",
    ],

    'scenarios_h2': 'Make the <span class="accent">Deal</span>',
    'scenario_items': [
        ["Scenario 1", "A client wants a discount. Offer one using the first conditional: 'If you..., I will...'."],
        ["Scenario 2", "The client asks about cancellations. Explain your policy with an 'if' sentence."],
        ["Scenario 3", "It is peak season. Negotiate a better rate by trading a condition for an offer."],
        ["Scenario 4", "Quote a full package (rate, deposit, what is included) and close the deal."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = net, 2 = markup, 3 = peak, 4 = surcharge, 5 = trade.",
        "Condition: 'If you book forty rooms...' (present simple after 'if').",
        "Result: '...I will hold the low-season rate.' (will + verb).",
        "Never say 'If you will book'. Say 'If you book, I will...'.",
    ],
    'answerkey_note': "First conditional: if + present simple, then will + verb. The 'if' part never takes 'will'.",

    'roleplays': [
        {'h2': 'Quote a <span class="accent">Group Rate</span>',
         'scenario': "A tour operator asks for a group rate for fifty guests. Offer your best net rate on a condition, using the first conditional.",
         'keywords': ["If you book...", "net rate", "I will offer..."]},
        {'h2': 'Handle the <span class="accent">Details</span>',
         'scenario': "The client asks about the deposit, the surcharge, and the cancellation policy. Answer each question and trade one condition for one offer.",
         'keywords': ["deposit", "surcharge", "If you..., I will..."]},
        {'h2': 'Close the <span class="accent">Deal</span>',
         'scenario': "Run a full price negotiation from the first quote to the final agreement. Use the first conditional to trade conditions for offers until you both agree.",
         'keywords': []},
    ],

    'survival_h2': 'Talk Numbers with <span class="accent">Confidence</span>',
    'survival': [
        ("Could you quote me a group rate?", "Você poderia me passar uma tarifa de grupo?"),
        ("If you book early, I will offer a discount.", "Se você reservar cedo, eu ofereço um desconto."),
        ("A small surcharge applies in peak season.", "Uma pequena taxa extra se aplica na alta temporada."),
        ("Breakfast is complimentary.", "O café da manhã é cortesia."),
        ("What is your cancellation policy?", "Qual é a sua política de cancelamento?"),
    ],
    'learned': [
        "I can quote prices, rates, and packages in English.",
        "I can use the first conditional to trade a condition for an offer.",
        "I can explain deposits, surcharges, and cancellation policies.",
        "I can talk about peak-season and low-season prices.",
        "I know the words: net rate, markup, group rate, deposit, cancellation policy, peak season, low season, package, surcharge, to quote, complimentary, discount.",
    ],
    'badge_name': 'Deal Maker Badge',
    'badge_p': 'You can talk numbers with confidence -- quoting prices, building packages, and closing deals in English, Andrea.',
    'next_lesson': 'Advising Clients and Handling Tricky Requests',

    'preclass_title': 'Talking Prices, Packages, and Deals',
    'preclass_desc': "How to quote prices and negotiate deals in tourism. Key words: net rate, markup, group rate, deposit, cancellation policy, peak season, low season, package, surcharge, to quote, complimentary, discount. Structure: the first conditional (if + present simple, will + verb) to trade a condition for an offer.",
    'context': ("Andrea is preparing a <strong>quote</strong> for an important client. The hotel gave her a <strong>net "
                "rate</strong>, and she adds a small <strong>markup</strong> before sending the <strong>package</strong> to the "
                "client. Because the trip is in <strong>peak season</strong>, a weekend <strong>surcharge</strong> applies, but "
                "Andrea knows how to negotiate. 'If you book more than forty rooms, I <strong>will</strong> hold the "
                "<strong>low-season</strong> rate,' she says. She also explains the <strong>deposit</strong> and the "
                "<strong>cancellation policy</strong> clearly. To close the deal, she adds that breakfast is "
                "<strong>complimentary</strong>. The client is happy, and both sides feel they have won."),
    'context_quiz': [
        ("1. 'If you book more than forty rooms, I will hold the rate.' The 'if' part uses:",
         [("A", "the present simple (book).", True),
          ("B", "will + verb.", False),
          ("C", "the past simple.", False)]),
        ("2. Which sentence is correct?",
         [("A", "If you will pay the deposit, breakfast is free.", False),
          ("B", "If you pay the deposit, breakfast will be free.", True),
          ("C", "If you paying the deposit, breakfast free.", False)]),
        ("3. We use the first conditional to talk about:",
         [("A", "a real future possibility and its result.", True),
          ("B", "something that already happened.", False),
          ("C", "an impossible dream.", False)]),
    ],
    'tip_title': 'The First Conditional',
    'tip_sub': "Como negociar em inglês: 'se... então...' (explicação em inglês e português).",
    'tip_rows': [
        ("If + present simple", "A condição. The condition -- o que precisa acontecer primeiro.", "If you <strong>book</strong> early,"),
        ("will + verb", "O resultado. The result -- o que você promete.", "I <strong>will</strong> give a discount."),
        ("Nunca 'will' depois de 'if' / Never 'will' after if", "Mantenha o presente simples na parte do 'if'.", "If you <strong>pay</strong> (não 'will pay')"),
        ("Regra de ouro / Golden rule", "if + presente simples, vírgula, will + verbo.", "If you book, I will offer a rate."),
    ],
    'fill': [
        ('"If you ', "book", "Dica: presente simples depois de 'if'", "If you book early, I will offer a discount.", ' early, I will offer a discount."'),
        ('"If you pay the deposit, breakfast ', "will", "Dica: resultado com 'will'", "If you pay the deposit, breakfast will be complimentary.", ' be complimentary."'),
        ('"Could you ', "quote", "Dica: passar/informar um preço", "Could you quote me a group rate?", ' me a group rate?"'),
        ('"A small ', "surcharge", "Dica: taxa extra", "A small surcharge applies in peak season.", ' applies in peak season."'),
        ('"What is your cancellation ', "policy", "Dica: as regras de cancelamento", "What is your cancellation policy?", '?"'),
        ('"Breakfast is ', "complimentary", "Dica: grátis, incluído", "Breakfast is complimentary.", '."'),
    ],
    'order_intro': "Coloque as etapas de uma boa negociação de preço na ordem correta.",
    'order': [
        "Ask about the client's needs (group size and dates).",
        "Quote the net rate and the package.",
        "Trade a condition for an offer using 'if... I will...'.",
        "Explain the deposit and the cancellation policy.",
        "Confirm the deal and thank the client.",
    ],
    'speech': [
        ("Could you quote me a group rate?", "Você poderia me passar uma tarifa de grupo?"),
        ("If you book early, I will offer a discount.", "Se você reservar cedo, eu ofereço um desconto."),
        ("A small surcharge applies in peak season.", "Uma pequena taxa extra se aplica na alta temporada."),
        ("Breakfast is complimentary.", "O café da manhã é cortesia."),
        ("What is your cancellation policy?", "Qual é a sua política de cancelamento?"),
    ],
    'quiz': [
        ("A client asks for a discount. You say:",
         [("A", "If you book forty rooms, I will offer a better rate.", True),
          ("B", "If you will book forty rooms, I offer a better rate.", False),
          ("C", "You book forty rooms, discount.", False)]),
        ("You want to explain the deposit. You say:",
         [("A", "We ask for a twenty percent deposit to confirm.", True),
          ("B", "We ask a deposit twenty percent confirm.", False),
          ("C", "Deposit twenty for confirm percent.", False)]),
        ("It is peak season and a surcharge applies. You say:",
         [("A", "A small surcharge applies at the weekend in peak season.", True),
          ("B", "A small surcharge apply weekend peak.", False),
          ("C", "Peak season is surcharge always applying.", False)]),
        ("You want to close the deal warmly. You say:",
         [("A", "If you sign today, breakfast will be complimentary.", True),
          ("B", "If you signing today, breakfast complimentary.", False),
          ("C", "You sign today breakfast free will.", False)]),
    ],
    'think': "Imagine a client wants a group package for peak season but says your price is too high. Record a short negotiation: quote your rate, then use the first conditional to trade at least two conditions for offers (for example, 'If you book early, I will...'). Explain the deposit and what is included. Take your time.",

    'media': [
        ('series', 'Selling Sunset -- Season 1, Episode 1 (Netflix)',
         'A reality series about high-end agents negotiating big deals. Watch how they quote prices, discuss terms, and trade conditions to close a sale. Connection to Lesson 9: quoting prices and negotiating packages and deals.',
         'Tip: watch one negotiation scene twice. Write down two sentences where someone offers something in exchange for a condition.',
         'https://www.netflix.com/title/80202013'),
        ('podcast', '6 Minute English -- "The Language of Negotiation" (BBC)',
         'A short, learner-friendly podcast about how English speakers bargain and make deals. Perfect for hearing conditional sentences and price language used naturally. Connection to Lesson 9: the first conditional and the vocabulary of prices and deals.',
         'Tip: listen twice. Note one first-conditional sentence you could use with a real client.',
         'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'),
        ('youtube', '"First Conditional -- If + Present, Will + Verb" -- BBC Learning English',
         'A clear lesson on the exact grammar of this class: the first conditional for real future possibilities. Connection to Lesson 9: trading a condition for an offer in a price negotiation.',
         'Tip: after each example, make your own sentence about a deal at Escape Turismo using the first conditional.',
         'https://www.youtube.com/watch?v=8VETylIxyhw'),
    ],
}
