{
  identity:'Lesson 01 &middot; Block 1 (Build) &middot; Reading into Speaking &middot; receptive level B1, productive level B1 &middot; online, 60 minutes &middot; first lesson of the first cycle (lessons 1&ndash;20). Assessment model in force: <strong>continuous teacher-led assessment</strong>. This lesson does not create, prepare or presuppose a test.',
  goals:'<strong>To read two documents against each other and report what they do not agree on, saying where each claim comes from.</strong><ul>'+
        '<li>To identify the purpose of each document before comparing them.</li>'+
        '<li>To locate a divergence and point to the line that shows it.</li>'+
        '<li>To separate what a document states from what the reader inferred from it.</li>'+
        '<li>To attribute a claim to its source while speaking, not afterwards.</li>'+
        '<li>To deliver a three-minute briefing to someone who has read neither document.</li></ul>',
  product:'A three-minute briefing to the course coordinator, who has read neither document. The learner names the three points where the plan and the syllabus stop agreeing, attributes each claim to the document it came from, and closes with one thing she needs decided. You play the coordinator and interrupt twice, with the questions written out in the note on that screen &mdash; neither of them asks for information the documents do not contain.',
  criteria:'<ol><li>Names all three divergences without reading from a script.</li>'+
           '<li>Attributes each claim to its document, in the sentence where the claim is made.</li>'+
           '<li>Marks as inference what is inference &mdash; the third column of stage 5.</li>'+
           '<li>Answers both interruptions and returns to the point she had left.</li></ol>'+
           '<p>Criterion 3 is the one this lesson exists for. She is precise in Portuguese and, in English, tends to state everything at the same level of certainty because the language for anything else is not available yet.</p>',
  prep:'<ul><li>Read both documents before the lesson. The three divergences are: the number of teaching hours (18 vs 20), who corrects the written work (teacher vs peer), and the assessment week (7 vs 8).</li>'+
       '<li><strong>The fourth difference is a trap and it is deliberate:</strong> the plan mentions a listening task the syllabus does not. It is not a divergence &mdash; the syllabus never claims to list every task. If she brings it as a fourth, that is the discovery of stage 5 arriving early; take it, do not correct it as an error.</li>'+
       '<li>Decide before the lesson which of the two interruptions you will use first. Both are written out; using both in the same order every time makes the second one predictable.</li>'+
       '<li>The documents stay visible during the briefing. This is attribution, not memory (Doc 03, Reading: the text remains available when the task requires precision).</li>'+
       '<li><strong>Pacing.</strong> Stage 4 is the long reading block. Keep stages 1&ndash;3 tight: the record shows her performance dropping when a single mode runs long.</li></ul>',
  language:'<strong>Attribution:</strong> <em>The syllabus says&hellip;, but the plan has&hellip;</em> &middot; <em>According to the plan,&hellip;</em> &middot; <em>That comes from the syllabus, not the plan.</em><br><strong>Divergence:</strong> <em>These two do not line up on&hellip;</em> &middot; <em>They disagree about&hellip;</em> &middot; <em>One says X, the other says Y.</em><br><strong>Marking an inference:</strong> <em>My reading is that&hellip;</em> &middot; <em>Neither of them actually says it, but&hellip;</em> &middot; <em>Putting the two together,&hellip;</em><br>Pronunciation: the contrast in <em>says</em> /sez/ against <em>say</em> &mdash; she produces /se&#618;z/ under load, and it costs intelligibility in the one word this lesson repeats most.',
  transcript:'The audio in this lesson is the model briefing in stage 6, and it has a transcript. <strong>Keep it closed until she has produced her own version.</strong> Opened before, it stops being a model and becomes a script to read &mdash; which is exactly the strategy this cycle is trying to replace. After her attempt, open it and compare where the attribution lands in each version.',
  difficulties:'<ul><li><strong>Attribution arrives late.</strong> She says the fact and then, after a pause, adds where it came from. The briefing is still correct and much harder to follow. Stage 6 practises attaching the source inside the sentence, which is the point of the chunk drill.</li>'+
       '<li><strong>Everything at the same level of certainty.</strong> Inference sounds exactly like quotation. This is the target of stage 5, and it is a repertoire gap, not carelessness.</li>'+
       '<li><strong>The trap in stage 4.</strong> The listening task in the plan looks like a divergence. Getting caught by it is useful: it is the cleanest way into the difference between what a document says and what its silence means.</li></ul>',
  scaffolding:'<strong>If the learner needs support:</strong> in stage 7, let her keep the three-line note from stage 6 in view &mdash; it holds the structure, not the sentences. If attribution keeps arriving late, stop her at the first sentence and rebuild that one sentence with her, out loud, before letting the briefing run.<br><strong>Challenge:</strong> if the briefing comes out clean on the first attempt, add the coordinator&rsquo;s third question &mdash; <em>which of the two should we change?</em> &mdash; which forces a recommendation the documents do not contain, and therefore a marked inference.',
  feedback:'Take the feedback from her own formulation, not from a list. Two points at most: one that worked, one to develop. The likely one to develop is the position of the attribution inside the sentence. The retask is a single sentence, not the whole briefing &mdash; the one where the source arrived late.',
  evidence:'Record: whether all three divergences were named without a script; where the attribution landed in the sentence (inside / after / absent); whether inference was marked as inference; and how she came back after each interruption. Separate observation from hypothesis: the mitigation gap (H1) is <strong>not</strong> decided here &mdash; this lesson only shows whether the language for degrees of certainty exists at all.',
  prepost:'The pre-class opens the two documents and asks what each one is for &mdash; it does not point out a single divergence. That is deliberate: if the pre-class solved it, the first attempt in class would no longer show how she reads. The post-class offers a short reading on lesson-plan design and a listening on giving feedback, both optional and neither required for the next lesson.',
  key:'<strong>Stage 3 (gist):</strong> the plan is an instrument for one lesson; the syllabus is a commitment across the course. <strong>Stage 4:</strong> true &mdash; 1, 3, 5; false &mdash; 2, 4; unsupported &mdash; 6 (the listening task is only in the plan, and the syllabus does not claim completeness). <strong>Stage 5:</strong> quoted &mdash; the hours, the corrector, the week; inferred &mdash; that the course got shorter, that peer correction was a cost decision. <strong>Stage 6:</strong> any answer where the source is attached inside the sentence is acceptable, including forms not on the list.'
}
