# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1400&q=80"

D = {
    'n': 10,
    'reading': True,
    'partner_name': 'stefan',
    'grammar_point_pt': "o segundo condicional (second conditional): if + passado simples, would/could + verbo, para dar conselhos e falar de situações hipotéticas",
    'chapter_tag': 'Advising Clients',
    'title_h1': 'Advising Clients and Handling <span class="accent">Tricky Requests</span>',
    'title_sub': 'Offer smart alternatives, weigh the trade-offs, and advise with confidence.',
    'short_title': 'Advising Clients',
    'menu_title': 'Advising Clients and Handling Tricky Requests',
    'menu_desc': 'Advise clients and handle difficult requests using the second conditional',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&q=80",
    'stamp_label': 'Trusted Advisor',
    'stamp_img': "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=200&q=80",
    'phases': ['The Impossible Request', 'The Words of Advice', 'The Advisor\'s Story',
               'The Second Conditional', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From the Deal to the <span class="accent">Difficult Client</span>',
    'warm_p': 'Last time you learned to quote prices and close deals with the first conditional. Today the client is trickier: the request is almost impossible, and instead of saying no, you will learn to advise, offer alternatives, and guide them to a smart decision.',
    'warm_prompt': 'In one sentence: what do you say when a client asks for something you cannot fully give them?',
    'missions': [
        'Learn the words of advice, alternatives, and trade-offs.',
        'Master the second conditional to give hypothetical advice.',
        'Handle a tricky client request without ever simply saying no.',
    ],

    'vocab_trans_h2': 'The Language of <span class="accent">Advice</span>',
    'vocab': [
        ("Alternative", "another option you can choose instead (alternativa)", "Let me suggest a smart alternative."),
        ("To recommend", "to suggest something is a good choice (recomendar)", "I would recommend the inland hotel."),
        ("Upgrade", "a better room or service than the one booked (upgrade, melhoria)", "I could offer a free upgrade."),
        ("Flexible", "able to change or adapt easily (flexível)", "The tailor-made package is very flexible."),
        ("Trade-off", "a balance between two things you cannot both have fully (contrapartida)", "There is a trade-off: cheaper, but further away."),
        ("Downside", "the negative side of something (desvantagem)", "The downside is the longer transfer."),
        ("To weigh up", "to consider the good and bad points carefully (ponderar)", "Let us weigh up the two options."),
        ("Peace of mind", "a calm feeling from knowing nothing will go wrong (tranquilidade)", "The insurance gives you peace of mind."),
        ("Tailor-made", "specially designed for one client's needs (feito sob medida)", "We offer tailor-made itineraries."),
        ("Worthwhile", "good enough to be worth the time or money (que vale a pena)", "The extra cost is worthwhile."),
        ("To reconsider", "to think about a decision again (reconsiderar)", "You might want to reconsider the dates."),
        ("Second thoughts", "new doubts about a decision (dúvidas, hesitação)", "I am having second thoughts about August."),
    ],

    'gram_trans_h2': 'The Second <span class="accent">Conditional</span>',
    'gram_trans_sub': 'if + past simple &middot; would / could + verb',
    'gram_examples': [
        ("", "If I were you, I would book the low season.", '"If I <span style="color:#15803d;font-weight:700">were</span> you, I <span class="accent" style="font-weight:700">would book</span> the low season."'),
        ("", "If you had more time, you could visit both cities.", '"If you <span style="color:#15803d;font-weight:700">had</span> more time, you <span class="accent" style="font-weight:700">could visit</span> both cities."'),
        ("", "If the budget allowed it, I would upgrade the rooms.", '"If the budget <span style="color:#15803d;font-weight:700">allowed</span> it, I <span class="accent" style="font-weight:700">would upgrade</span> the rooms."'),
    ],
    'gram_disc_q': 'Are these situations real or imaginary? What tense follows "if", and what follows "would"?',
    'gram_table': [
        ("If + past simple", "An unreal or hypothetical condition", "If I <strong>were</strong> you,"),
        ("would / could + verb", "The imagined result or advice", "I <strong>would</strong> recommend it."),
        ("Always 'were'", "Use 'were' for I / he / she in this structure", "If she <strong>were</strong> here (not 'was')"),
    ],
    'gram_rule_foot': "Second conditional = an imaginary situation. If + past simple, ... would/could + verb. Use 'were' for all persons.",

    'lf_h2': 'Complete the <span class="accent">Advice</span>',
    'lf_title': 'Complete the second conditional',
    'lf_items': [
        ["A", "If I ", "were", " you, I would book early.", "strong"],
        ["B", "If you had more time, you ", "could", " visit both cities.", "soft"],
        ["C", "If you chose the inland hotel, you ", "would", " save money.", "soft"],
        ["D", "If the budget ", "allowed", " it, I would upgrade the rooms.", "strong"],
    ],
    'lf_followup': "The 'if' part uses the past simple (were, had, chose, allowed); the result uses 'would' or 'could' + verb. Use 'were' for all persons: If I were you...",

    'mistakes': [
        ("If I was you, I will recommend the inland hotel.", 'If I <strong>were</strong> you, I <strong>would</strong> recommend the inland hotel.'),
        ("If you had more time, you can visit both cities.", 'If you had more time, you <strong>could</strong> visit both cities.'),
    ],
    'mistake_note': "In the second conditional, use the past simple after 'if' (and 'were' for all persons), and 'would' or 'could' -- never 'will' or 'can' -- in the result.",

    'read_trans_h2': 'Read the <span class="accent">Advice</span>',
    'reading_h2': 'The Art of Giving <span class="accent">Advice</span>',
    'read_block': {
        'rtitle': 'The Art of Giving Advice',
        'paras': [
            "In tourism, clients do not always want what is best for them. One asks for a beach in the rainy season; another wants five-star luxury on a three-star budget. A weak salesperson simply says yes and creates a problem later, or says no and loses the sale. A skilled advisor does something different: they offer a smart alternative and let the client decide.",
            "The secret is in how the advice is given. Nobody likes to be told what to do. So experienced professionals soften their advice with a hypothetical: 'If I were you, I would travel in June instead.' 'If you chose the tailor-made package, you would have more flexibility.' This is the second conditional, and it turns an order into a friendly suggestion. The client keeps control of the decision, which makes them far more likely to say yes.",
            "Good advice also makes the trade-offs visible. Every choice has an upside and a downside, and the client deserves to weigh them up honestly. 'The inland hotel is cheaper, but it is twenty minutes from the beach.' When you present the options this way, the client trusts you more, not less. In the end, the best advisors are not the ones who always say yes -- they are the ones who help the client make a decision they will not regret.",
        ],
        'source': 'Adapted from a hospitality business guide, The Trusted Advisor',
        'link': 'https://www.thetrustedadvisor.com',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "In tourism, you should always give clients exactly what they ask for.", False],
            ["b", "Skilled advisors offer smart alternatives, soften advice with the second conditional, and make trade-offs clear.", True],
            ["c", "The best salespeople never let the client make the final decision.", False],
        ],
        'tf': [
            ["A skilled advisor offers a smart alternative instead of just saying yes or no.", "t", "The first paragraph says a skilled advisor offers a smart alternative and lets the client decide."],
            ["The text says the second conditional turns advice into an order.", "f", "It says the second conditional turns an order into a friendly suggestion."],
            ["Good advice makes the trade-offs of each choice visible to the client.", "t", "The third paragraph says good advice makes the trade-offs visible and lets the client weigh them up honestly."],
            ["'If I were you, I would travel in June' is an example of the second conditional.", "t", "The second paragraph gives this exact sentence as an example of the second conditional."],
        ],
    },

    'dialogue_h2': 'The Tricky <span class="accent">Request</span>',
    'dialogue': [
        ('stefan', 'arthur', "Hi Andrea. My group wants a beach resort in August, but the budget is really tight. What would you do?",
         "Hi Andrea. My group wants a beach resort in August, but the budget is really tight. What would you do?"),
        ('andrea', 'ellen', "If I were you, I would look at the low season instead. The same resort would cost much less.",
         "If I were you, I would look at the low season instead. The same resort would cost much less."),
        ('stefan', 'arthur', "But the group insists on August. Is there any alternative?",
         "But the group insists on August. Is there any <span class=\"vocab-highlight\">alternative</span>?"),
        ('andrea', 'ellen', "If you booked a resort slightly inland, you would get the beach nearby and a better rate. It is a good trade-off.",
         "If you booked a resort slightly inland, you would get the beach nearby and a better rate. It is a good <span class=\"vocab-highlight\">trade-off</span>."),
        ('stefan', 'arthur', "Interesting. And what if they want everything included?",
         "Interesting. And what if they want everything included?"),
        ('andrea', 'ellen', "If they chose a tailor-made package, I could add transfers and dinners. It would give them peace of mind.",
         "If they chose a <span class=\"vocab-highlight\">tailor-made</span> package, I could add transfers and dinners. It would give them <span class=\"vocab-highlight\">peace of mind</span>."),
        ('stefan', 'arthur', "That sounds worthwhile. Honestly, I am having second thoughts about the beach idea now.",
         "That sounds <span class=\"vocab-highlight\">worthwhile</span>. Honestly, I am having <span class=\"vocab-highlight\">second thoughts</span> about the beach idea now."),
        ('andrea', 'ellen', "If I were in your position, I would recommend the inland option. It is flexible, and your group would still be happy.",
         "If I were in your position, I would <span class=\"vocab-highlight\">recommend</span> the inland option. It is <span class=\"vocab-highlight\">flexible</span>, and your group would still be happy."),
    ],
    'comprehension': [
        ("1. What does Stefan's group want?", "A beach resort in August, on a tight budget."),
        ("2. What alternative does Andrea suggest for the same budget?", "A resort slightly inland, near the beach but at a better rate."),
        ("3. What is Stefan having second thoughts about?", "The beach idea / booking a beach resort in August."),
    ],

    'listen1_h2': 'A Tricky <span class="accent">Voicemail</span>',
    'listen1_sub': 'A client asks for advice on an almost impossible request. Sound first -- no text.',
    'listen1_qs': [
        ("1. What does Stefan's client want?", "A luxury trip to Italy for eight people, with private guides."),
        ("2. What is the problem with the budget?", "He only has the budget for four-star hotels."),
        ("3. What does Stefan ask Andrea for?", "A recommendation, or a smart alternative."),
    ],
    'listen2_h2': 'The Art of <span class="accent">Advice</span>',
    'listen2_sub': 'A short business tip on advising with the second conditional. Sound first -- no text.',
    'listen2_qs': [
        ("1. What should you never do when you cannot meet a request?", "Just say no."),
        ("2. Which structure makes advice sound polite?", "The second conditional: if + past simple, would/could."),
        ("3. What does the second conditional help the client see?", "The trade-offs clearly."),
    ],
    'listenings': [
        {'file': 'a10_listening_stefan.mp3', 'voice': 'arthur',
         'text': "Hi Andrea, it is Stefan again. I have a tricky one for you. My most important client wants a luxury trip to Italy for eight people, but he only has the budget for four-star hotels. He also wants a private guide in every city. Honestly, if I promised all of that at this price, I would lose money. But I do not want to say no. If you were in my shoes, what would you do? Maybe there is a smart alternative. Could you call me back with a recommendation? I trust your judgement. Thanks a lot, and talk soon."},
        {'file': 'a10_listening_advice.mp3', 'voice': 'ellen',
         'text': "Welcome to this short segment on the art of advice. When a client makes a request you cannot fully meet, never just say no. Instead, offer a smart alternative, and soften your advice with the second conditional. In English, we say, if I were you, I would choose the inland hotel, or if you had a little more time, you could visit both cities. Notice the pattern: if plus the past simple, and would or could plus the verb. This structure sounds polite and professional, because it presents your idea as a friendly suggestion, not an order. It also helps the client see the trade-offs clearly. So the next time you give advice, remember: if I were you, I would use the second conditional."},
    ],

    'gapfill_parts': [
        "A good advisor never just says yes. Instead, they offer a smart ", ["1"],
        " and give advice with the second conditional: 'If I ", ["2"],
        " you, I would...'. They make the ", ["3"], " clear so the client can ", ["4"],
        " them up, which builds ", ["5"], ".",
    ],
    'gapfill_bank': ["alternative", "were", "trade-offs", "weigh", "trust"],
    'vocabnote': "Second conditional = 'if' + past simple, then would/could + verb. Note: with I/he/she, use 'were' (If I were you), not 'was'. It talks about an unreal or hypothetical situation.",

    'bank_label_top': 'Advise',
    'bank_label': 'Useful language for advising clients',
    'bank_items': [
        "If I were you, I would choose the low season.",
        "If you booked earlier, you would get a better rate.",
        "I would recommend the tailor-made package.",
        "There is a trade-off: cheaper, but further away.",
        "It would give your group peace of mind.",
        "If you had more time, you could visit both cities.",
        "Honestly, I would reconsider that option.",
        "That option is more flexible and worthwhile.",
    ],

    'scenarios_h2': 'Advise the <span class="accent">Client</span>',
    'scenario_items': [
        ["Scenario 1", "A client wants a beach in the rainy season. Advise an alternative using 'If I were you, I would...'."],
        ["Scenario 2", "The client's budget is too low for their dream trip. Suggest a trade-off with the second conditional."],
        ["Scenario 3", "A client cannot decide between two hotels. Give a recommendation and make the trade-offs clear."],
        ["Scenario 4", "A client has a tricky, almost impossible request. Advise them honestly without simply saying no."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = alternative, 2 = were, 3 = trade-offs, 4 = weigh, 5 = trust.",
        "Advice: 'If I were you, I would book the low season.' (were + would).",
        "Option: 'If you had more time, you could visit both cities.' (had + could).",
        "Never say 'If I was you, I will'. Say 'If I were you, I would'.",
    ],
    'answerkey_note': "Second conditional: if + past simple (were for all persons), then would/could + verb. Never 'will' or 'can' in the result.",

    'roleplays': [
        {'h2': 'The Tricky <span class="accent">Request</span>',
         'scenario': "A client wants a luxury trip on a small budget. Advise a smart alternative using 'If I were you, I would...'.",
         'keywords': ["If I were you...", "alternative", "I would recommend..."]},
        {'h2': 'Weigh the <span class="accent">Trade-Offs</span>',
         'scenario': "The client is stuck between two options. Present the upside and the downside of each, and give your recommendation with the second conditional.",
         'keywords': ["trade-off", "If you chose...", "downside"]},
        {'h2': 'Advise with <span class="accent">Confidence</span>',
         'scenario': "Handle a full advising conversation with a difficult client. Never simply say no: offer alternatives, make the trade-offs clear, and guide them to a decision they will not regret.",
         'keywords': []},
    ],

    'survival_h2': 'Advise Like a <span class="accent">Pro</span>',
    'survival': [
        ("If I were you, I would book earlier.", "Se eu fosse você, eu reservaria mais cedo."),
        ("I would recommend the tailor-made package.", "Eu recomendaria o pacote sob medida."),
        ("There is a trade-off to consider.", "Há uma contrapartida a considerar."),
        ("If you had more time, you could see both cities.", "Se você tivesse mais tempo, poderia ver as duas cidades."),
        ("Let me suggest a smart alternative.", "Deixe-me sugerir uma alternativa inteligente."),
    ],
    'learned': [
        "I can advise clients using the second conditional (if + past, would/could).",
        "I can offer smart alternatives instead of simply saying no.",
        "I can make the trade-offs of each option clear.",
        "I can soften my advice to sound polite and professional.",
        "I know the words: alternative, to recommend, upgrade, flexible, trade-off, downside, to weigh up, peace of mind, tailor-made, worthwhile, to reconsider, second thoughts.",
    ],
    'badge_name': 'Trusted Advisor Badge',
    'badge_p': 'You can guide any client through a tricky request -- offering alternatives, weighing trade-offs, and advising with confidence, Andrea.',
    'next_lesson': 'Handling Complaints and Difficult Situations',

    'preclass_title': 'Advising Clients and Handling Tricky Requests',
    'preclass_desc': "How to advise clients and handle difficult requests in tourism. Key words: alternative, to recommend, upgrade, flexible, trade-off, downside, to weigh up, peace of mind, tailor-made, worthwhile, to reconsider, second thoughts. Structure: the second conditional (if + past simple, would/could + verb) to give hypothetical advice.",
    'context': ("Andrea's client, Stefan, has a <strong>tricky</strong> request: a luxury trip on a small budget. Andrea never "
                "simply says no. Instead, she offers a smart <strong>alternative</strong>. 'If I <strong>were</strong> you, I "
                "<strong>would</strong> travel in the low season,' she says. She explains the <strong>trade-off</strong> clearly: "
                "the inland hotel is cheaper, but the <strong>downside</strong> is that it is further from the beach. She helps "
                "Stefan <strong>weigh up</strong> the options and <strong>recommends</strong> a <strong>tailor-made</strong> package "
                "for <strong>peace of mind</strong>. In the end, Stefan agrees it is <strong>worthwhile</strong> -- and he trusts "
                "Andrea even more."),
    'context_quiz': [
        ("1. 'If I were you, I would travel in the low season' uses:",
         [("A", "the second conditional for hypothetical advice.", True),
          ("B", "the first conditional for a real plan.", False),
          ("C", "the past simple for a finished action.", False)]),
        ("2. In the second conditional, after 'I' we use:",
         [("A", "was.", False),
          ("B", "were (If I were you).", True),
          ("C", "am.", False)]),
        ("3. Which sentence gives polite, hypothetical advice?",
         [("A", "If you had more time, you could visit both cities.", True),
          ("B", "If you have more time, you will visit both cities.", False),
          ("C", "You must visit both cities.", False)]),
    ],
    'tip_title': 'The Second Conditional',
    'tip_sub': "Como dar conselhos e falar de situações hipotéticas em inglês (explicação em inglês e português).",
    'tip_rows': [
        ("If + past simple", "A condição imaginária. An unreal condition.", "If I <strong>were</strong> you,"),
        ("would / could + verb", "O resultado imaginado ou conselho. The imagined result.", "I <strong>would</strong> recommend it."),
        ("Sempre 'were' / Always 'were'", "Use 'were' para I/he/she nesta estrutura.", "If she <strong>were</strong> here (não 'was')"),
        ("Regra de ouro / Golden rule", "if + passado simples, would/could + verbo (situação irreal).", "If I were you, I would wait."),
    ],
    'fill': [
        ('"If I ', "were", "Dica: use 'were' para todas as pessoas", "If I were you, I would book earlier.", ' you, I would book earlier."'),
        ('"If you had more time, you ', "could", "Dica: resultado com 'could'", "If you had more time, you could visit both cities.", ' visit both cities."'),
        ('"I would ', "recommend", "Dica: sugerir como boa escolha", "I would recommend the tailor-made package.", ' the tailor-made package."'),
        ('"There is a ', "trade-off", "Dica: uma contrapartida", "There is a trade-off to consider.", ' to consider."'),
        ('"It would give them peace of ', "mind", "Dica: tranquilidade", "It would give them peace of mind.", '."'),
        ('"Let me suggest an ', "alternative", "Dica: outra opção", "Let me suggest an alternative.", '."'),
    ],
    'order_intro': "Coloque as etapas de um bom conselho ao cliente na ordem correta.",
    'order': [
        "Listen carefully to the client's request.",
        "Acknowledge it without saying no.",
        "Offer a smart alternative with 'If I were you...'.",
        "Explain the trade-offs of each option.",
        "Let the client make the final decision.",
    ],
    'speech': [
        ("If I were you, I would book earlier.", "Se eu fosse você, eu reservaria mais cedo."),
        ("I would recommend the tailor-made package.", "Eu recomendaria o pacote sob medida."),
        ("There is a trade-off to consider.", "Há uma contrapartida a considerar."),
        ("If you had more time, you could see both cities.", "Se você tivesse mais tempo, poderia ver as duas cidades."),
        ("Let me suggest a smart alternative.", "Deixe-me sugerir uma alternativa inteligente."),
    ],
    'quiz': [
        ("A client's request is too expensive. You advise:",
         [("A", "If I were you, I would travel in the low season.", True),
          ("B", "If I was you, I will travel in the low season.", False),
          ("C", "You travel low season must.", False)]),
        ("You want to present a trade-off. You say:",
         [("A", "The inland hotel is cheaper, but it is further from the beach.", True),
          ("B", "Inland hotel cheaper but far beach is.", False),
          ("C", "Cheaper hotel beach no problem.", False)]),
        ("You want to give hypothetical advice politely. You say:",
         [("A", "If you had more time, you could see both cities.", True),
          ("B", "If you have time, you can see both cities now.", False),
          ("C", "You see both cities if time.", False)]),
        ("A client is unsure. You reassure them. You say:",
         [("A", "The tailor-made package would give you peace of mind.", True),
          ("B", "Tailor package peace mind give you.", False),
          ("C", "You peace mind package tailor.", False)]),
    ],
    'think': "Imagine a client asks you for something almost impossible -- a luxury trip on a very small budget. Record a short piece of advice: acknowledge the request, offer a smart alternative using the second conditional ('If I were you, I would...'), and explain one trade-off clearly. Do not simply say no. Take your time.",

    'media': [
        ('series', "Chef's Table (Netflix) -- any episode",
         'A beautifully filmed series where top chefs explain the choices and trade-offs behind their craft. Listen for how they weigh options and justify their decisions. Connection to Lesson 10: weighing trade-offs and explaining hypothetical choices.',
         'Tip: pick one decision a chef describes. Write a second-conditional sentence about what you would do in their place.',
         'https://www.netflix.com/title/80007945'),
        ('podcast', '6 Minute English -- "Giving Advice" (BBC)',
         'A short, learner-friendly podcast about how English speakers give advice politely. Perfect for hearing the second conditional and softened suggestions used naturally. Connection to Lesson 10: advising clients with "If I were you, I would...".',
         'Tip: listen twice. Write one piece of advice for a client using the second conditional.',
         'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'),
        ('youtube', '"The Second Conditional -- 6 Minute Grammar" -- BBC Learning English',
         'A clear lesson on the exact grammar of this class: the second conditional for unreal and hypothetical situations. Connection to Lesson 10: giving advice with "If I were you, I would...".',
         'Tip: after each example, make your own sentence advising a client at Escape Turismo using the second conditional.',
         'https://www.youtube.com/watch?v=3OuqzHxlrHc'),
    ],
}
