# -*- coding: utf-8 -*-
BG1 = "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1400&q=80"
BG2 = "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1400&q=80"
BG3 = "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80"
BG4 = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1400&q=80"
BG5 = "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1400&q=80"
BG6 = "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1400&q=80"

D = {
    'n': 12,
    'reading': True,
    'partner_name': 'anders',
    'grammar_point_pt': "o discurso indireto (reported speech): recuar o tempo verbal um passo (will->would, is->was, has->had), tell + pessoa vs say, e perguntas reportadas com if/whether",
    'chapter_tag': 'Negotiating Partnerships',
    'title_h1': 'Negotiating Partnerships and <span class="accent">Contracts</span>',
    'title_sub': 'Confirm what was said, agree clear terms, and close a partnership that lasts.',
    'short_title': 'Negotiating Partnerships',
    'menu_title': 'Negotiating Partnerships and Contracts',
    'menu_desc': 'Negotiate terms and report what was agreed using reported speech',
    'bg_title': BG1, 'bg_vocab': BG2, 'bg_read': BG3, 'bg_gram': BG4,
    'bg_lesson_card': "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=600&q=80",
    'stamp_label': 'Deal Maker',
    'stamp_img': "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&q=80",
    'phases': ['The Handshake', 'The Language of Deals', 'The Negotiator\'s Story',
               'Reported Speech', 'Voices', 'Your Turn', 'Wrap-Up'],

    'warm_h2': 'From Complaints to the <span class="accent">Deal Table</span>',
    'warm_p': "Last time you handled complaints and stayed calm with the passive voice: 'The problem is being handled.' Today you sit at the deal table. You will negotiate a partnership, confirm exactly what was said, and turn a friendly conversation into a clear, binding contract.",
    'warm_prompt': 'In one sentence: after a meeting, how do you make sure both sides agreed to the same thing?',
    'missions': [
        'Learn the language of contracts, terms, and negotiation.',
        'Master reported speech to confirm what was said and agreed.',
        'Negotiate a partnership from the first offer to a signed contract.',
    ],

    'vocab_trans_h2': 'The Language of <span class="accent">Deals</span>',
    'vocab': [
        ("Contract", "a formal written agreement between two sides (contrato)", "We signed the contract last week."),
        ("Terms", "the conditions of an agreement (termos, condicoes)", "The terms are good for both companies."),
        ("Clause", "one specific section of a contract (clausula)", "There is a clause about cancellations."),
        ("To negotiate", "to discuss in order to reach an agreement (negociar)", "We negotiated a better rate."),
        ("Partnership", "a business relationship between two companies (parceria)", "This partnership will grow every year."),
        ("To sign off on", "to give final approval to something (aprovar formalmente)", "My director signed off on the deal."),
        ("Deadline", "the latest time by which something must be done (prazo)", "The deadline for the draft is Friday."),
        ("Draft", "an early version of a document (rascunho, minuta)", "I will send you the first draft today."),
        ("To renew", "to extend an agreement for more time (renovar)", "We renewed the contract for two years."),
        ("Binding", "legally forcing you to do something (vinculante, obrigatorio)", "Once signed, the contract is binding."),
        ("To meet halfway", "to compromise so both sides win a little (chegar a um meio-termo)", "Let us meet halfway on the price."),
        ("Leverage", "an advantage that gives you power in a negotiation (poder de barganha)", "Volume gives us leverage in the deal."),
    ],

    'gram_trans_h2': 'Reported <span class="accent">Speech</span>',
    'gram_trans_sub': 'backshift the tense &middot; tell + person &middot; if / whether',
    'gram_examples': [
        ("", "He said the rates would stay fixed.", '"He said the rates <span style="color:#15803d;font-weight:700">would</span> stay fixed."'),
        ("", "She told me the contract had been signed.", '"She <span class="accent" style="font-weight:700">told me</span> the contract <span style="color:#15803d;font-weight:700">had been</span> signed."'),
        ("", "They asked if we could meet halfway.", '"They asked <span style="color:#15803d;font-weight:700">if</span> we <span class="accent" style="font-weight:700">could</span> meet halfway."'),
    ],
    'gram_disc_q': 'What happens to the tense when we report what someone said? And how is a reported question different from a direct one?',
    'gram_table': [
        ("Backshift one step", "will -> would, is -> was, has -> had", "He said it <strong>would</strong> start Monday."),
        ("tell vs say", "tell needs a person (told me); say does not", "She <strong>told me</strong> / She <strong>said</strong> that..."),
        ("Reported questions", "no inversion; use if / whether or wh-", "He asked <strong>if</strong> we could meet halfway."),
    ],
    'gram_rule_foot': "Reported speech: move the tense back one step, use tell + person but say without one, and report questions with if/whether and no inversion.",

    'lf_h2': 'Report the <span class="accent">Deal</span>',
    'lf_title': 'Complete the reported sentence',
    'lf_items': [
        ["A", "He said the rate ", "would", " be fixed for two years.", "strong"],
        ["B", "She ", "told", " me the deadline was Friday.", "soft"],
        ["C", "They asked ", "if", " we could meet halfway.", "soft"],
        ["D", "My director said the discount ", "had", " been approved.", "strong"],
    ],
    'lf_followup': "Report a statement by backshifting the tense (will -> would, has -> had); use tell + person (told me); report a question with if and no inversion (asked if we could).",

    'mistakes': [
        ("He said the rate will be fixed.", 'He said the rate <strong>would</strong> be fixed.'),
        ("She told that the deal was ready.", 'She <strong>told me</strong> that the deal was ready.'),
    ],
    'mistake_note': "In reported speech, backshift the tense one step (will -> would), and remember: tell needs a person (told me), while say does not (said that). Reported questions use if/whether with no inversion.",

    'read_trans_h2': 'Read the <span class="accent">Deal</span>',
    'reading_h2': 'The Deal Behind the <span class="accent">Handshake</span>',
    'read_block': {
        'rtitle': 'The Deal Behind the Handshake',
        'paras': [
            "In business, a handshake is only the beginning. Two partners can leave the same meeting smiling, each completely certain they agreed to something different. That is why the words matter -- and why professionals report and record exactly what was said before anyone signs anything.",
            "A good negotiator listens more than they talk. They ask what the other side really needs, and then they repeat it back to confirm: 'So you said the rates would be fixed for two years, and you told me the deadline was the end of March.' This is reported speech, and it does two things at once. It shows the other side you were truly listening, and it turns a vague, friendly conversation into clear, shared terms that both sides recognise.",
            "Then comes the draft. Every point that was agreed is written into a clause, and both sides sign off. Until it is signed, nothing is binding -- a promise is still just a promise. The best partnerships are built on this simple habit: agree clearly, report it back, put it in writing, and meet halfway when it matters. Deals made this way are the ones that get renewed, year after year.",
        ],
        'source': 'Adapted from a negotiation guide, Getting to Yes',
        'link': 'https://www.pon.harvard.edu/tag/getting-to-yes/',
        'gist_prompt': 'What is the main idea of the text?',
        'gist_choices': [
            ["a", "A handshake is always enough to make a business deal final.", False],
            ["b", "Good negotiators confirm what was said with reported speech, write clear terms into a contract, and sign.", True],
            ["c", "The best strategy in a negotiation is to talk more than the other side does.", False],
        ],
        'tf': [
            ["The text says a handshake is only the beginning of a deal.", "t", "The first sentence says a handshake is only the beginning."],
            ["A good negotiator talks more than they listen.", "f", "It says a good negotiator listens more than they talk."],
            ["Repeating back what was said shows you were listening and clarifies the terms.", "t", "The second paragraph says it shows you were listening and turns a vague conversation into clear terms."],
            ["A promise is binding even before the contract is signed.", "f", "The text says that until it is signed, nothing is binding -- a promise is still just a promise."],
        ],
    },

    'dialogue_h2': 'Closing the <span class="accent">Partnership</span>',
    'dialogue': [
        ('anders', 'arthur', "Andrea, thanks for meeting. I spoke to my director yesterday, and he said we could offer you fifteen percent if the volume is high enough.",
         "Andrea, thanks for meeting. I spoke to my director yesterday, and he said we could offer you fifteen percent if the volume is high enough."),
        ('andrea', 'ellen', "That is a good start, Anders. But last month you told me the rate would be fixed for two years. Is that still in the contract?",
         "That is a good start, Anders. But last month you told me the rate would be fixed for two years. Is that still in the <span class=\"vocab-highlight\">contract</span>?"),
        ('anders', 'arthur', "It is. The clause is already in the draft. My director asked if you could commit to fifty room nights a month.",
         "It is. The <span class=\"vocab-highlight\">clause</span> is already in the <span class=\"vocab-highlight\">draft</span>. My director asked if you could commit to fifty room nights a month."),
        ('andrea', 'ellen', "We can meet halfway. If we commit to forty, would you sign off on the fifteen percent and renew for two years?",
         "We can <span class=\"vocab-highlight\">meet halfway</span>. If we commit to forty, would you <span class=\"vocab-highlight\">sign off</span> on the fifteen percent and <span class=\"vocab-highlight\">renew</span> for two years?"),
        ('anders', 'arthur', "Let me be honest -- I need something in return. The deadline for the new season is tight.",
         "Let me be honest -- I need something in return. The <span class=\"vocab-highlight\">deadline</span> for the new season is tight."),
        ('andrea', 'ellen', "Understood. I will confirm forty room nights in writing today, so you have leverage with your director. That gives us both a binding agreement we can trust.",
         "Understood. I will confirm forty room nights in writing today, so you have <span class=\"vocab-highlight\">leverage</span> with your director. That gives us both a <span class=\"vocab-highlight\">binding</span> agreement we can trust."),
        ('anders', 'arthur', "That works. I will update the draft and send it over. Once we both sign off, the partnership is official.",
         "That works. I will update the draft and send it over. Once we both sign off, the <span class=\"vocab-highlight\">partnership</span> is official."),
        ('andrea', 'ellen', "Perfect. I appreciate how clearly you have laid out the terms, Anders. This is exactly how a good partnership should start.",
         "Perfect. I appreciate how clearly you have laid out the <span class=\"vocab-highlight\">terms</span>, Anders. This is exactly how a good partnership should start."),
    ],
    'comprehension': [
        ("1. What did Anders's director agree to offer?", "Fifteen percent, if the volume is high enough."),
        ("2. What did the director ask Andrea to commit to?", "Fifty room nights a month."),
        ("3. Why is the deadline important to Anders?", "The new season is starting soon, so the timing is tight."),
    ],

    'listen1_h2': 'A Deal <span class="accent">Update</span>',
    'listen1_sub': 'Anders leaves a voicemail reporting the latest from head office. Sound first -- no text.',
    'listen1_qs': [
        ("1. What condition did head office set for the fifteen percent?", "Signing the contract before the end of the month."),
        ("2. What did the director say about the two-year term?", "It would not be a problem, as long as volume stays above forty room nights."),
        ("3. What does legal want Andrea to review?", "Clause seven, about cancellations -- it needs one small change."),
    ],
    'listen2_h2': 'Reporting a <span class="accent">Negotiation</span>',
    'listen2_sub': 'A short business tip on reported speech at the deal table. Sound first -- no text.',
    'listen2_qs': [
        ("1. What happens to the tense in reported speech?", "It moves back one step: will becomes would, have becomes had."),
        ("2. How do you report a question?", "Drop the inversion and use if or whether."),
        ("3. What is the difference between tell and say?", "Tell needs a person (told me); say does not (he said that)."),
    ],
    'listenings': [
        {'file': 'a12_listening_anders.mp3', 'voice': 'arthur',
         'text': "Hi Andrea, it is Anders. Quick update after my meeting. I spoke to head office this morning, and they said the fifteen percent was approved, but only if we sign before the end of the month. My director also told me that the two-year term would not be a problem, as long as the volume stays above forty room nights. Oh, and legal asked whether you could review clause seven, about cancellations. They said it needed one small change. Could you look at the draft and let me know if the terms work for you? If they do, I will send the final version to sign. Thanks a lot, and talk soon."},
        {'file': 'a12_listening_reporting.mp3', 'voice': 'ellen',
         'text': "Welcome to this short segment on reporting a negotiation. When you agree something important, never rely on memory. Report it back, and write it down. In English, we use reported speech. Notice how the tense moves back one step. If your partner says, the rate will be fixed, you report, he said the rate would be fixed. If they say, we have approved the discount, you report, they said they had approved the discount. For questions, drop the inversion and use if or whether: they asked if we could meet halfway. Two small tips: use tell with a person, told me, told us, but use say without one, he said that. And always confirm the terms out loud before you sign. A deal that is reported clearly is a deal that gets renewed."},
    ],

    'gapfill_parts': [
        "After the meeting, Anders called to confirm the terms. He said the discount ", ["1"],
        " be approved before the end of the month. He also ", ["2"],
        " me that the two-year ", ["3"], " was fine. Then legal asked ", ["4"],
        " I could review one ", ["5"], " about cancellations.",
    ],
    'gapfill_bank': ["would", "told", "term", "if", "clause"],
    'vocabnote': "Reported speech: move the tense back one step (will -> would, is -> was, has -> had). Use tell + a person (told me), and say without one (said that). For reported questions, drop the inversion and use if/whether: 'She asked if we could...'.",

    'bank_label_top': 'Report',
    'bank_label': 'Useful language for negotiating and reporting a deal',
    'bank_items': [
        "You said the rate would be fixed for two years.",
        "My director told me the deadline was the end of March.",
        "They asked if we could meet halfway.",
        "Let us meet halfway on the volume.",
        "Once we both sign off, the deal is binding.",
        "I will send you the first draft today.",
        "Can we renew the partnership for two more years?",
        "I will confirm all the terms in writing.",
    ],

    'scenarios_h2': 'Close the <span class="accent">Deal</span>',
    'scenario_items': [
        ["Scenario 1", "A partner offered a discount last week. Report it back to confirm: 'You said the rate would be...'."],
        ["Scenario 2", "Your director set a condition. Report it to your partner using reported speech."],
        ["Scenario 3", "A partner asks for more volume than you can give. Offer to meet halfway."],
        ["Scenario 4", "Confirm the final terms of a partnership and explain the next step: draft, then sign off."],
    ],
    'answerkey_list': [
        "Gap-fill: 1 = would, 2 = told, 3 = term, 4 = if, 5 = clause.",
        "Reported statement: 'He said the rate would be fixed.' (will -> would).",
        "Reported question: 'She asked if we could meet halfway.' (drop the inversion, use if).",
        "Use 'told me' (tell + person) but 'said that' (say, no person).",
    ],
    'answerkey_note': "Reported speech: backshift the tense one step; tell + person, say + no person; reported questions use if/whether with no inversion.",

    'roleplays': [
        {'h2': 'Confirm the <span class="accent">Offer</span>',
         'scenario': "A partner offered a fifteen percent discount last week. Report it back to confirm the terms, using reported speech.",
         'keywords': ["You said...", "the rate would be...", "you told me..."]},
        {'h2': 'Report and <span class="accent">Negotiate</span>',
         'scenario': "Your director set a condition (forty room nights). Report it to your partner and negotiate the discount.",
         'keywords': ["My director said...", "meet halfway", "sign off on"]},
        {'h2': 'Close with <span class="accent">Confidence</span>',
         'scenario': "Negotiate a full partnership from the opening offer to the final terms: confirm what was said, ask for what you need, meet halfway, and agree the next step.",
         'keywords': []},
    ],

    'survival_h2': 'Close Like a <span class="accent">Pro</span>',
    'survival': [
        ("You said the rate would be fixed for two years.", "Você disse que a tarifa ficaria fixa por dois anos."),
        ("My director told me the deadline was Friday.", "Meu diretor me disse que o prazo era sexta-feira."),
        ("Can we meet halfway on the volume?", "Podemos chegar a um meio-termo no volume?"),
        ("Once we both sign off, the deal is binding.", "Assim que ambos aprovarmos, o acordo é vinculante."),
        ("I will confirm all the terms in writing today.", "Vou confirmar todos os termos por escrito hoje."),
    ],
    'learned': [
        "I can report what someone said using reported speech (he said it would...).",
        "I can report a question with if/whether and no inversion.",
        "I can use tell + person and say without a person correctly.",
        "I can negotiate terms and offer to meet halfway.",
        "I know the words: contract, terms, clause, to negotiate, partnership, to sign off on, deadline, draft, to renew, binding, to meet halfway, leverage.",
    ],
    'badge_name': 'Deal Maker Badge',
    'badge_p': 'You can negotiate a partnership from the first offer to a signed contract -- confirming every term with clear reported speech, Andrea.',
    'next_lesson': 'Presenting Your Company at a Trade Fair',

    # ----- new B2 slides (pipeline v2) -----
    'spot_errors': [
        ("He said the rate will be fixed.", "He said the rate would be fixed."),
        ("She told that the deal was ready.", "She told me that the deal was ready."),
        ("They asked can we meet halfway.", "They asked if we could meet halfway."),
        ("He said me the deadline was Friday.", "He told me the deadline was Friday."),
    ],
    'bridge5': {
        'h2': 'Voices at the <span class="accent">Deal Table</span>',
        'sub': 'Listen to a real negotiation, then confirm the terms in your own words.',
        'bg': BG5,
    },
    'register': [
        ("Take it or leave it.", "Let us find terms that work for both of us."),
        ("That price is final.", "There may be some room if we look at the volume."),
        ("You are wrong about the deadline.", "Let me check -- I understood the deadline was the end of March."),
        ("We will not change the contract.", "We could review that clause and meet halfway."),
    ],
    'artifact': {
        'label': 'The Draft',
        'h2': 'Partnership <span class="accent">Terms</span>',
        'meta': [
            ("From:", "Anders Lindqvist -- Nordic Hotels"),
            ("To:", "Andrea Aggio -- Escape Turismo"),
            ("Subject:", "Draft agreement -- for your review"),
        ],
        'paras': [
            "Dear Andrea, thank you for a productive meeting. As agreed, the key terms for our two-year partnership are below. Once you sign off, I will send the binding version.",
            "1. Discount: fifteen percent on all group bookings, fixed for two years. 2. Volume: a minimum of forty room nights per month. 3. Deadline: both sides to sign before the end of the month.",
            "You mentioned that clause seven, on cancellations, needed one small change, so I have updated it. If the terms work for you, reply to confirm and we will make it official. Best regards, Anders.",
        ],
    },
    'artifact_qs': [
        ("1. What discount was agreed, and for how long?", "Fifteen percent on all group bookings, fixed for two years."),
        ("2. What is the minimum volume in the terms?", "Forty room nights per month."),
        ("3. What change did Andrea ask for?", "A small change to clause seven, on cancellations."),
    ],
    'pron_lines': [
        ("Let us meet halfway on this.", "'meet halfway on this' links -- mee-thal-fway-on-this."),
        ("He said it would be fine.", "'said it would' links smoothly -- sai-dit-wood."),
        ("Once we sign off, it is done.", "'sign off' links -- sy-noff; stress the word DONE."),
        ("I will send you the draft today.", "'send you the' blends -- sen-juh-thuh."),
    ],
    'bridge6': {
        'h2': 'Now You <span class="accent">Close</span>',
        'sub': 'Your turn: report the terms and negotiate each deal out loud.',
        'bg': BG6,
    },
    'quickfire': [
        {'situation': "A partner offers a ten percent discount, but you need fifteen.",
         'tips': ["'You said you could offer more on volume.'", "Meet halfway: 'Could we agree on twelve?'", "'Let me confirm that in writing.'"]},
        {'situation': "Your director set a strict deadline that you must report to the partner.",
         'tips': ["'My director told me...'", "Backshift: '...the deadline was Friday.'", "'Can we meet the deadline together?'"]},
        {'situation': "A partner asks for more room nights than you can commit to.",
         'tips': ["'They asked if we could...'", "'Let us meet halfway on forty.'", "'That gives you leverage with head office.'"]},
        {'situation': "You need to confirm the terms before signing a binding contract.",
         'tips': ["'So, you said the rate would be fixed?'", "'Once we both sign off...'", "'I will send the final draft today.'"]},
        {'situation': "A partner wants to renew, but on worse terms than before.",
         'tips': ["'When we signed, you said the rate was fixed.'", "'Let us renew, but meet halfway.'", "'Shall I put the new terms in writing?'"]},
    ],

    'preclass_title': 'Negotiating Partnerships and Contracts',
    'preclass_desc': "How to negotiate a partnership and report what was agreed. Key words: contract, terms, clause, to negotiate, partnership, to sign off on, deadline, draft, to renew, binding, to meet halfway, leverage. Structure: reported speech (backshift the tense, tell + person vs say, reported questions with if/whether).",
    'context': ("Andrea is negotiating a two-year <strong>partnership</strong> with Anders. After the meeting, she "
                "confirms every point using reported speech. 'You <strong>said</strong> the rate <strong>would</strong> "
                "be fixed for two years,' she reminds him, 'and you <strong>told</strong> me the <strong>deadline</strong> "
                "was the end of March.' Anders replies that his director <strong>asked if</strong> she could commit to more "
                "volume. Andrea offers to <strong>meet halfway</strong>. Every point they agree is written into a "
                "<strong>clause</strong> in the <strong>draft</strong>; once both sides <strong>sign off</strong>, the "
                "<strong>contract</strong> is <strong>binding</strong> and the partnership can <strong>renew</strong> for years."),
    'context_quiz': [
        ("1. 'He said the rate would be fixed' reports which sentence?",
         [("A", "'The rate will be fixed.'", True),
          ("B", "'The rate is fixed right now.'", False),
          ("C", "'Fix the rate, please.'", False)]),
        ("2. To report a question, you:",
         [("A", "keep the inversion: 'asked could we meet'.", False),
          ("B", "use if/whether with no inversion: 'asked if we could meet'.", True),
          ("C", "just add a question mark.", False)]),
        ("3. Which sentence uses 'tell' correctly?",
         [("A", "He told me the deadline was Friday.", True),
          ("B", "He told the deadline was Friday.", False),
          ("C", "He said me the deadline was Friday.", False)]),
    ],
    'tip_title': 'Reported Speech',
    'tip_sub': "Como relatar o que alguém disse ao confirmar um acordo (explicação em inglês e português).",
    'tip_rows': [
        ("Recuar 1 passo / Backshift one step", "will->would, is->was, has->had.", "He said it <strong>would</strong> start Monday."),
        ("say vs tell", "tell + pessoa (told me); say sem pessoa. tell needs a person.", "She <strong>told me</strong> / She <strong>said</strong> that..."),
        ("Perguntas reportadas / Reported questions", "sem inversão; use if/whether ou wh-.", "He asked <strong>if</strong> we could meet halfway."),
        ("Regra de ouro / Golden rule", "relate o que foi dito, um tempo verbal atrás.", "You said the rate <strong>would</strong> be fixed."),
    ],
    'fill': [
        ('"He said the rate ', "would", "Dica: will vira would", "He said the rate would be fixed.", ' be fixed."'),
        ('"She ', "told", "Dica: tell + pessoa (told me)", "She told me the deadline was Friday.", ' me the deadline was Friday."'),
        ('"They asked ', "if", "Dica: pergunta reportada (if/whether)", "They asked if we could meet halfway.", ' we could meet halfway."'),
        ('"Let us meet ', "halfway", "Dica: chegar a um meio-termo", "Let us meet halfway on the volume.", ' on the volume."'),
        ('"Once we both sign ', "off", "Dica: aprovar formalmente (sign ___)", "Once we both sign off, the deal is binding.", ', the deal is binding."'),
        ('"We renewed the ', "contract", "Dica: o acordo formal escrito", "We renewed the contract for two years.", ' for two years."'),
    ],
    'order_intro': "Coloque os passos de uma boa negociação na ordem correta.",
    'order': [
        "Ask what the other side really needs.",
        "Confirm what was said, using reported speech.",
        "Offer to meet halfway on the key point.",
        "Write every agreed point into a clause.",
        "Both sides sign off to make it binding.",
    ],
    'speech': [
        ("You said the rate would be fixed for two years.", "Você disse que a tarifa ficaria fixa por dois anos."),
        ("My director told me the deadline was Friday.", "Meu diretor me disse que o prazo era sexta-feira."),
        ("Can we meet halfway on the volume?", "Podemos chegar a um meio-termo no volume?"),
        ("Once we both sign off, the deal is binding.", "Assim que ambos aprovarmos, o acordo é vinculante."),
        ("I will confirm all the terms in writing.", "Vou confirmar todos os termos por escrito."),
    ],
    'quiz': [
        ("A partner promised a fixed rate last week. You confirm it:",
         [("A", "You said the rate would be fixed for two years.", True),
          ("B", "You say the rate will be fixed for two years.", False),
          ("C", "You said the rate is fixed two years.", False)]),
        ("You report your director's condition to the partner. You say:",
         [("A", "My director told me we needed forty room nights.", True),
          ("B", "My director said me we need forty room nights.", False),
          ("C", "My director told we need forty room nights.", False)]),
        ("You report the partner's question. You say:",
         [("A", "They asked if we could lower the deposit.", True),
          ("B", "They asked could we lower the deposit.", False),
          ("C", "They asked if could we lower the deposit.", False)]),
        ("You want to compromise on the volume. You say:",
         [("A", "Let us meet halfway on the room nights.", True),
          ("B", "Meet halfway room nights you must.", False),
          ("C", "The room nights meet in the half.", False)]),
    ],
    'think': "Imagine you have just finished negotiating a partnership. Record a short summary for your director. Report what the partner said and asked, using reported speech ('He said the rate would be fixed', 'They asked if we could...'), explain where you agreed to meet halfway, and say what the next step is (draft, then sign off). Take your time.",

    'media': [
        ('series', "Suits (Netflix / streaming) -- Season 1",
         "A fast, stylish drama set in a top law firm, packed with negotiations, contracts, and high-stakes deals. Listen for how the lawyers report offers and confirm terms. Connection to Lesson 12: negotiating partnerships and reporting what was said.",
         'Tip: pick one negotiation scene and report it back in reported speech: "He said he would...".',
         'https://www.imdb.com/title/tt1632701/'),
        ('podcast', '6 Minute English (BBC Learning English)',
         "A short, learner-friendly podcast on everyday and business English. Choose an episode on deals, work, or communication to hear reporting language used naturally. Connection to Lesson 12: confirming and reporting what was agreed.",
         'Tip: after listening, report one thing a speaker said using reported speech.',
         'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'),
        ('youtube', '"How to use reported speech" -- 6 Minute Grammar, BBC Learning English',
         "A clear lesson on the exact grammar of this class: reported speech, backshifting the tense, and reporting questions. Connection to Lesson 12: confirming a deal with 'He said the rate would be fixed'.",
         'Tip: after each example, report a sentence from your own last negotiation at Escape Turismo.',
         'https://www.youtube.com/watch?v=L-wTVCByxzk'),
    ],
}
